### ISSUE TITLE
Jitterbug Mk II

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#10]
While players no longer jitter on top of vehicles, they can get stuck in the same jitter issue by walking into the sides.

**Comment by fsendventd** [comment]
I have also experienced this.

**Comment by Nianor** [comment]
I have video of this too if you want it. From the same session as my video on the wonky plane crash stuff.

**Comment by DonBruce64** [comment]
I'll take it for data, but it may take a bit to fin the source of this bug.  Minecraft collisions are wonky.

**Comment by DonBruce64** [comment]
Condensing this bug into #83 for clarity on ground system issues.
