### ISSUE TITLE
Request: Haul-able Vehicles

### ISSUE THREAD

**Issue by Blue20Boy17** [DonBruce64/MinecraftTransportSimulator#100]
I think it'd be neat for vehicles to be able to be loaded onto a larger vehicle (ie: the Scout onto the GMC). It offers a similar thing to trailers, but the physics aren't as hard.

**Comment by DonBruce64** [comment]
Although a few people have asked for this, I see no reason to add such a thing.  Besides being VERY difficult to do from a code standpoint (Entities don't like to move based on other entities; they get glitchy), the fact that players can carry around tanks and trucks in their inventory makes this point moot and only valid for decorative purposes.  If that's the case, then pack makers can just make trailer beds with vehicles on them, similar to how the GMC has logs on it.  That would be a far more efficient way to do rendering anyways.

**Comment by Blue20Boy17** [comment]
dangit...
