### ISSUE TITLE
[Bug] Duplicate undestructable lights

### ISSUE THREAD

**Issue by ktokto313** [DonBruce64/MinecraftTransportSimulator#1000]
When holding right click at a pole with the light in hand, it'll stack up and bug the game out so the light can't be destroy.
![2021-11-29_08 45 33](https://user-images.githubusercontent.com/57142191/144347003-110bd33c-24ce-4385-9287-d4238f384401.png)

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
