### ISSUE TITLE
minecraft will crash if i try to put buildcraft's fluids in mts fuel pumps

### ISSUE THREAD

**Issue by JoenneTV** [DonBruce64/MinecraftTransportSimulator#1001]
[BUG]
i'm using mts mts v22 and buildcraft 7.99.24.8  in minecraft 1.12.2 with 1.12.2-forge-14.23.5.2855 forge.
When i try to put any buildcraft fluid in mts fuel pumps, the game crashs and makes the world unusable, because it will always crash if you try to open the same world again.

[crash-2021-12-02_11.36.40-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7642981/crash-2021-12-02_11.36.40-client.txt)

**Comment by DonBruce64** [comment]
This was addressed in commit 7662f45e7eeb2b30c963cdd4b4c37066bdd02871.  There's a beta on Discord with it fixed if you don't want to wait for a release.

**Comment by JoenneTV** [comment]
Ok.
Thanks!

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
