### ISSUE TITLE
Helicopters are less maneuverable

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#1002]
I'm back!

While working on making sure my pack is up to "IV_v20.0" snuff, I noticed the helicopter physics had changed. You can no longer pitch/roll past the defined max elevator/aileron values, and that the helicopter automatically trims back to level when no control inputs are made. After a little digging, it looks like the changes came in this commit:
https://github.com/DonBruce64/MinecraftTransportSimulator/commit/b8dbf808c1b49846e6573948e9f83419ccc22c5f#diff-6cf8a910457e6b5b6bcb20f0b58fdd06baeb6fb1b35b387c5cbaaa76636de9ec

I understand the intent with this was most likely to make helicopters easier to fly, but I think it compromises both realism and maneuverability. By default, the attitude of the helicopter should remain steady unless control inputs are made. 

A potential compromise here could be an "auto-level" mode that either works similarly to the current auto-pilot mode (which could be renamed "auto-hover" for helicopters), or it could be a config option like "simpleHelicopters" or something.

If you're good with it and pending your input on the best way to proceed, I may work on this myself.

**Comment by DonBruce64** [comment]
Went ahead and added a client-side config for this.  When a user is controlling a heli, it's rotor mode will get set to whatever their config is set to.

**Comment by DonBruce64** [comment]
Implemented in V20.4.0.
