### ISSUE TITLE
[Needed Addition] Variable for when a bullet has active burntime

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1003]
When the particle system changed, there was never a variable added to make sure that bullets can have particles that are generated while burntime is active, and stops them once burnTime runs out

**Comment by gyrohero** [comment]
Still getting back into dev-ing, but I think this one should be fairly straighforward

**Comment by DonBruce64** [comment]
Implemented in V20.4.0.
