### ISSUE TITLE
Lagging vehicles on the server.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1005]
Lags occur most often due to the large number of players, as well as how quickly they move between chunks.

This was not the case in version 19 of MTS, everything was quite stable.

JVM arguments on server: java -Xms128M -Xmx5120M -XX:+UseSerialGC -XX:+OptimizeStringConcat -XX:G1HeapRegionSize=32M -Dfml.queryResult=confirm -Dterminal.jline=false -Dterminal.ansi=true -DIReallyKnowWhatIAmDoingISwear=true -Duser.timezone=Europe/Moscow -jar -Dfile.encoding=UTF-8 Magma-788465c-DEV-server.jar nogui

**Comment by DonBruce64** [comment]
Are you able to test a beta on Discord?  I think I found the issue here, but haven't been able to get confirmation.

**Comment by DonBruce64** [comment]
Calling fixed in V20.4.0 given user feedback.
