### ISSUE TITLE
when motor breaks befor a prop server / game crashes to desktop

### ISSUE THREAD

**Issue by BloodMoonAbyss** [DonBruce64/MinecraftTransportSimulator#1006]
[crash-2021-12-06_23.06.35-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7669559/crash-2021-12-06_23.06.35-server.txt)

that is the exact crash it gave it basicly said what the hell am i connected to "prop" and created a tic loop crash because engine already exploded

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
