### ISSUE TITLE
rollers in dev mode dupe lagacy rollers back into vehicle even if it already has rollers animated and in it

### ISSUE THREAD

**Issue by BloodMoonAbyss** [DonBruce64/MinecraftTransportSimulator#1007]
as title says lagacy code in dev mode re adds extra rollers on tracked vehicles even if they are in the code and it causes tracks to move faster then rollers or animation insanity like this "basicly spin like a crazzy and ignore proper locations"
![tracks going durhh](https://user-images.githubusercontent.com/92669440/145061757-2c197633-07d0-4c16-9137-9f3f69651170.png
this is sloved by just reimporting a dev mode of it with duped rollers removed from code and then works as intended

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
