### ISSUE TITLE
Issue with GUI when opening aircraft joystick controls (CRASHES WORLD, AND MC)

### ISSUE THREAD

**Issue by WANK3R** [DonBruce64/MinecraftTransportSimulator#1008]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.5.1 (1).jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  SoundUnpack (OpenSecurity-MC1.12.2-1.0-35.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 12/7/21 11:49 PM
Description: Rendering screen

java.lang.ArrayIndexOutOfBoundsException: -1
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at org.lwjgl.input.JInputController.getButtonName(JInputController.java:184)
	at minecrafttransportsimulator.mcinterface.InterfaceInput.getJoystickComponentName(InterfaceInput.java:235)
	at minecrafttransportsimulator.guis.instances.GUIConfig.setStates(GUIConfig.java:424)
	at minecrafttransportsimulator.mcinterface.BuilderGUI.func_73863_a(BuilderGUI.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1456)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1119)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.elementData(ArrayList.java:418)
	at java.util.ArrayList.get(ArrayList.java:431)
	at org.lwjgl.input.JInputController.getButtonName(JInputController.java:184)
	at minecrafttransportsimulator.mcinterface.InterfaceInput.getJoystickComponentName(InterfaceInput.java:235)
	at minecrafttransportsimulator.guis.instances.GUIConfig.setStates(GUIConfig.java:424)
	at minecrafttransportsimulator.mcinterface.BuilderGUI.func_73863_a(BuilderGUI.java:75)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:396)
	at sun.reflect.GeneratedMethodAccessor40.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.optifine.reflect.Reflector.callVoid(Reflector.java:660)

-- Screen render details --
Details:
	Screen name: minecrafttransportsimulator.mcinterface.BuilderGUI
	Mouse location: Scaled: (175, 123). Absolute: (526, 530)
	Screen size: Scaled: (480, 300). Absolute: (1440, 900). Scale factor of 3

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['aherndevin'/25, l='MpServer', x=23.46, y=56.00, z=-14.45]]
	Chunk stats: MultiplayerChunkCache: 289, 289
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (33,4,-21), Chunk: (at 1,0,11 in 2,-2; contains blocks 32,0,-32 to 47,255,-17), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 53625 game time, 53625 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 4 total; [BuilderEntityExisting['entity.mts_entity.name'/18, l='MpServer', x=33.00, y=57.79, z=-22.00], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/40, l='MpServer', x=22.82, y=57.42, z=-15.20], BuilderEntityExisting['entity.mts_entity.name'/41, l='MpServer', x=23.46, y=56.00, z=-14.45], EntityPlayerSP['aherndevin'/25, l='MpServer', x=23.46, y=56.00, z=-14.45]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:532)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 8713234928 bytes (8309 MB) / 15535702016 bytes (14816 MB) up to 16106127360 bytes (15360 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx15G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_E3 111 mods loaded, 111 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                        | Version               | Source                                             | Signature                                |
	|:------ |:------------------------- |:--------------------- |:-------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                 | 1.12.2                | minecraft.jar                                      | None                                     |
	| LCHIJA | mcp                       | 9.42                  | minecraft.jar                                      | None                                     |
	| LCHIJA | FML                       | 8.0.99.99             | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                     | 14.23.5.2854          | forge-1.12.2-14.23.5.2854.jar                      | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | openmodscore              | 0.12.2                | minecraft.jar                                      | None                                     |
	| LCHIJA | obfuscate                 | 0.4.2                 | minecraft.jar                                      | None                                     |
	| LCHIJA | opencomputers|core        | 1.7.5.192             | minecraft.jar                                      | None                                     |
	| LCHIJA | bobs_road_mod             | 1.7                   | [1.12.2]+Bob's+Road+Mod+v1.7.jar                   | None                                     |
	| LCHIJA | ctm                       | MC1.12.2-1.0.2.31     | CTM-MC1.12.2-1.0.2.31.jar                          | None                                     |
	| LCHIJA | appliedenergistics2       | rv6-stable-7          | appliedenergistics2-rv6-stable-7.jar               | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LCHIJA | atomicscience             | 1.12.2-3.0.6.19       | Atomic-Science-1.12.2-3.0.6b19.jar                 | None                                     |
	| LCHIJA | betteranimals             | 5.3.0                 | betteranimals-1.12.2-5.3.0.jar                     | None                                     |
	| LCHIJA | betterbuilderswands       | 0.11.1                | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar    | None                                     |
	| LCHIJA | bibliocraft               | 2.4.5                 | BiblioCraft[v2.4.5][MC1.12.2].jar                  | None                                     |
	| LCHIJA | buildcraftlib             | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftcore            | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftbuilders        | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcrafttransport       | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftsilicon         | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | tesla                     | 1.0.63                | Tesla-1.12.2-1.0.63.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LCHIJA | theoneprobe               | 1.4.28                | theoneprobe-1.12-1.4.28.jar                        | None                                     |
	| LCHIJA | buildcraftcompat          | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftenergy          | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftfactory         | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildcraftrobotics        | 7.99.24.6             | buildcraft-all-7.99.24.6.jar                       | None                                     |
	| LCHIJA | buildhelper               | 1.0.1                 | BuildHelper-Mod-1.12.2.jar                         | None                                     |
	| LCHIJA | cdm                       | 0.4.1                 | cdm-0.4.1-mc1.12.2.jar                             | None                                     |
	| LCHIJA | jei                       | 4.15.0.296            | jei_1.12.2-4.15.0.296.jar                          | None                                     |
	| LCHIJA | chisel                    | MC1.12.2-1.0.2.45     | Chisel-MC1.12.2-1.0.2.45.jar                       | None                                     |
	| LCHIJA | codechickenlib            | 3.2.3.358             | CodeChickenLib-1.12.2-3.2.3.358-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux              | 2.1.1                 | RedstoneFlux-1.12-2.1.1.1-universal.jar            | None                                     |
	| LCHIJA | cofhcore                  | 4.6.6                 | CoFHCore-1.12.2-4.6.6.1-universal.jar              | None                                     |
	| LCHIJA | cofhworld                 | 1.4.0                 | CoFHWorld-1.12.2-1.4.0.1-universal.jar             | None                                     |
	| LCHIJA | extendedrenderer          | v1.0                  | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LCHIJA | coroutil                  | 1.12.1-1.2.37         | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LCHIJA | configmod                 | v1.0                  | coroutil-1.12.1-1.2.37.jar                         | None                                     |
	| LCHIJA | drugz_mod                 | 1.0.0                 | Drugs+and+Psychedelics+1.0.0.jar                   | None                                     |
	| LCHIJA | effortlessbuilding        | 1.12.2-2.16           | effortlessbuilding-1.12.2-2.16.jar                 | None                                     |
	| LCHIJA | engineersdecor            | 1.1.1                 | engineersdecor-1.12.2-1.1.1.jar                    | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | motnt                     | 1.0.1                 | EvenMoreTNT-1.0.1.jar                              | None                                     |
	| LCHIJA | extrautils2               | 1.0                   | extrautils2-1.12-1.9.9.jar                         | None                                     |
	| LCHIJA | opencomputers             | 1.7.5.192             | OpenComputers-MC1.12.2-1.7.5.192.jar               | None                                     |
	| LCHIJA | zerocore                  | 1.12.2-0.1.2.8        | zerocore-1.12.2-0.1.2.8.jar                        | None                                     |
	| LCHIJA | bigreactors               | 1.12.2-0.4.5.67       | ExtremeReactors-1.12.2-0.4.5.67.jar                | None                                     |
	| LCHIJA | forgemultipartcbe         | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | microblockcbe             | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | minecraftmultipartcbe     | 2.6.2.83              | ForgeMultipart-1.12.2-2.6.2.83-universal.jar       | None                                     |
	| LCHIJA | lizardfurnituremod        | 1.1.0                 | Furbishcraft+1.1.1+[1.12.2].jar                    | None                                     |
	| LCHIJA | cfm                       | 6.3.1                 | furniture-6.3.1-1.12.2.jar                         | None                                     |
	| LCHIJA | mts                       | 20.3.0                | Immersive+Vehicles-1.12.2-20.3.0.jar               | None                                     |
	| LCHIJA | helicopterpack            | 2.7.0                 | Helicopter_Pack-2.7.0.jar                          | None                                     |
	| LCHIJA | igwmod                    | 1.4.4-15              | IGW-Mod-1.12.2-1.4.4-15-universal.jar              | None                                     |
	| LCHIJA | ic2                       | 2.8.220-ex112         | industrialcraft-2-2.8.220-ex112.jar                | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | railcraft                 | 12.0.0                | railcraft-12.0.0.jar                               | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LCHIJA | thermalfoundation         | 2.6.7                 | ThermalFoundation-1.12.2-2.6.7.1-universal.jar     | None                                     |
	| LCHIJA | immersiveengineering      | 0.12-98               | ImmersiveEngineering-0.12-98.jar                   | None                                     |
	| LCHIJA | immersiveintelligence     | 0.1.1                 | immersiveintelligence-1.12.2-0.1.1.jar             | None                                     |
	| LCHIJA | immersivepetroleum        | 1.1.9                 | immersivepetroleum-1.12.2-1.1.9.jar                | None                                     |
	| LCHIJA | immersiveposts            | 0.2.1                 | ImmersivePosts-0.2.1.jar                           | 0ba8738eadcf158e7fe1452255a73a022fb15feb |
	| LCHIJA | trackapi                  | 1.2                   | TrackAPI-1.2.jar                                   | None                                     |
	| LCHIJA | universalmodcore          | 1.0.1                 | UniversalModCore-1.12.2-forge-1.0.1.jar            | None                                     |
	| LCHIJA | immersiverailroading      | 1.8.0-7e0f82          | ImmersiveRailroading-1.12.2-forge-1.8.0-7e0f82.jar | None                                     |
	| LCHIJA | immersivetech             | 1.3.10                | immersivetech-1.12-1.3.10.jar                      | None                                     |
	| LCHIJA | industrialrenewal         | 0.17.6                | IndustrialRenewal_1.12.2-0.17.6.jar                | None                                     |
	| LCHIJA | ironchest                 | 1.12.2-7.0.67.844     | ironchest-1.12.2-7.0.72.847.jar                    | None                                     |
	| LCHIJA | iv_timp                   | 1.0.0                 | IV_Trin_Industrial_Machinery_Pack_1.0.3.jar        | None                                     |
	| LCHIJA | journeymap                | 1.12.2-5.7.1          | journeymap-1.12.2-5.7.1.jar                        | None                                     |
	| LCHIJA | lunatriuscore             | 1.2.0.42              | LunatriusCore-1.12.2-1.2.0.42-universal.jar        | None                                     |
	| LCHIJA | malisiscore               | 1.12.2-6.5.1-SNAPSHOT | malisiscore-1.12.2-6.5.1 (1).jar                   | None                                     |
	| LCHIJA | malisisdoors              | 1.12.2-7.3.0          | malisisdoors-1.12.2-7.3.0.jar                      | None                                     |
	| LCHIJA | mekanism                  | 1.12.2-9.8.3.390      | Mekanism-1.12.2-9.8.3.390.jar                      | None                                     |
	| LCHIJA | mekanismgenerators        | 1.12.2-9.8.3.390      | MekanismGenerators-1.12.2-9.8.3.390.jar            | None                                     |
	| LCHIJA | mekanismtools             | 1.12.2-9.8.3.390      | MekanismTools-1.12.2-9.8.3.390.jar                 | None                                     |
	| LCHIJA | modroadworksreborn        | 0.0.3                 | modroadworksreborn-0.0.3.jar                       | None                                     |
	| LCHIJA | movingelevators           | 1.2.17                | movingelevators-1.2.17-mc1.12.jar                  | None                                     |
	| LCHIJA | mrtjpcore                 | 2.1.4.43              | MrTJPCore-1.12.2-2.1.4.43-universal.jar            | None                                     |
	| LCHIJA | notenoughwands            | 1.5.9                 | Not-Enough-Wands-Mod-1.12.1.jar                    | None                                     |
	| LCHIJA | nei                       | 2.4.3                 | NotEnoughItems-1.12.2-2.4.3.245-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | nuclearcraft              | 2o.3.4                | NuclearCraft-2o.3.4-1.12.2.jar                     | None                                     |
	| LCHIJA | openmods                  | 0.12.2                | OpenModsLib-1.12.2-0.12.2.jar                      | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | openblocks                | 1.8.1                 | OpenBlocks-1.12.2-1.8.1.jar                        | d2a9a8e8440196e26a268d1f3ddc01b2e9c572a5 |
	| LCHIJA | opensecurity              | 1.0-35                | OpenSecurity-MC1.12.2-1.0-35.jar                   | None                                     |
	| LCHIJA | projectred-core           | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-Base.jar               | None                                     |
	| LCHIJA | projectred-compat         | 1.0                   | ProjectRed-1.12.2-4.9.4.120-compat.jar             | None                                     |
	| LCHIJA | projectred-integration    | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-integration.jar        | None                                     |
	| LCHIJA | projectred-transmission   | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-integration.jar        | None                                     |
	| LCHIJA | projectred-fabrication    | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-fabrication.jar        | None                                     |
	| LCHIJA | projectred-illumination   | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-lighting.jar           | None                                     |
	| LCHIJA | projectred-expansion      | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| LCHIJA | projectred-relocation     | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| LCHIJA | projectred-transportation | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-mechanical.jar         | None                                     |
	| LCHIJA | projectred-exploration    | 4.9.4.120             | ProjectRed-1.12.2-4.9.4.120-world.jar              | None                                     |
	| LCHIJA | railstuff                 | 0.2.5                 | railstuff-0.2.5.jar                                | None                                     |
	| LCHIJA | rsgauges                  | 1.2.4                 | rsgauges-1.12.2-1.2.4.jar                          | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | soundfilters              | 0.12_for_1.12         | SoundFilters-0.12_for_1.12.jar                     | None                                     |
	| LCHIJA | supertnt                  | 1.0.1                 | SuperTNT-1.12.2-1.0.1.jar                          | None                                     |
	| LCHIJA | thermalexpansion          | 5.5.7                 | ThermalExpansion-1.12.2-5.5.7.1-universal.jar      | None                                     |
	| LCHIJA | thermalcultivation        | 0.3.6                 | ThermalCultivation-1.12.2-0.3.6.1-universal.jar    | None                                     |
	| LCHIJA | thermaldynamics           | 2.5.6                 | ThermalDynamics-1.12.2-2.5.6.1-universal.jar       | None                                     |
	| LCHIJA | thermalinnovation         | 0.3.6                 | ThermalInnovation-1.12.2-0.3.6.1-universal.jar     | None                                     |
	| LCHIJA | trafficcontrol            | 0.2.2                 | trafficcontrol-0.2.2.jar                           | None                                     |
	| LCHIJA | bspkrscore                | at_0.9                | TreeCapitator-Mod-1.12.jar                         | None                                     |
	| LCHIJA | treecapitator             | at_0.9                | TreeCapitator-Mod-1.12.jar                         | None                                     |
	| LCHIJA | unuparts                  | 4.4.2                 | UNU+Parts+Pack+[MTS]+1.12.2-20.1.0-4.4.2.jar       | None                                     |
	| LCHIJA | unucivil                  | 4.2.5                 | UNU+Civilian+Pack+[MTS]+1.12.2-19.15.5-4.2.5.jar   | None                                     |
	| LCHIJA | weather2                  | 1.12.1-2.6.12         | weather2-1.12.1-2.6.12.jar                         | None                                     |
	| LCHIJA | worldcontrol              | 1.0.31                | WorldControl-1.0.31.jar                            | None                                     |
	| LCHIJA | wrcbe                     | 2.3.2                 | WR-CBE-1.12.2-2.3.2.33-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | betteranimalsplus         | 9.0.1                 | betteranimalsplus-1.12.2-9.0.1.jar                 | None                                     |
	| LCHIJA | industrialwires           | 1.7-36                | IndustrialWires-1.7-36.jar                         | 7e11c175d1e24007afec7498a1616bef0000027d |
	| LCHIJA | orelib                    | 3.6.0.1               | OreLib-1.12.2-3.6.0.1.jar                          | 7a2128d395ad96ceb9d9030fbd41d035b435753a |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
TransformerLoader (OpenComputers-MC1.12.2-1.7.5.192.jar)
  li.cil.oc.common.asm.ClassTransformer
MekanismCoremod (Mekanism-1.12.2-9.8.3.390.jar)
  mekanism.coremod.KeybindingMigrationHelper
MalisisCorePlugin (malisiscore-1.12.2-6.5.1 (1).jar)
  
OpenModsCorePlugin (OpenModsLib-1.12.2-0.12.2.jar)
  openmods.core.OpenModsClassTransformer
SoundUnpack (OpenSecurity-MC1.12.2-1.0-35.jar)
  
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
CTMCorePlugin (CTM-MC1.12.2-1.0.2.31.jar)
  team.chisel.ctm.client.asm.CTMTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 471.68' Renderer: 'NVIDIA GeForce GTX 960/PCIe/SSE2'
	OpenModsLib class transformers: [llama_null_fix:FINISHED],[horse_base_null_fix:FINISHED],[pre_world_render_hook:FINISHED],[player_render_hook:FINISHED],[horse_null_fix:FINISHED]
	AE2 Version: stable rv6-stable-7 for Forge 14.23.5.2768
	AE2 Integration: IC2:ON, RC:ON, MFR:OFF, Waila:OFF, InvTweaks:OFF, JEI:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:ON, TESLA:ON, CRAFTTWEAKER:OFF
	Launched Version: 1.12.2-forge-14.23.5.2854
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 960/PCIe/SSE2 GL version 4.6.0 NVIDIA 471.68, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Heavy+Industrial+1.6.7.0+by+adam+r+k.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x AMD FX(tm)-6300 Six-Core Processor 
	OptiFine Version: OptiFine_1.12.2_HD_U_E3
	OptiFine Build: 20181210-121000
	Render Distance Chunks: 8
	Mipmaps: 0
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 471.68
	OpenGlRenderer: NVIDIA GeForce GTX 960/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 6

**Comment by DonBruce64** [comment]
This was addressed in commit 39ba1babefaf3f113914a1a4b32b32b6b8d2ed67.  You can either get a beta from Discord, or wait for a release.  I leave the choice up to you.  But thanks for reporting the bug!  It was a while before I got anything for this one.

**Comment by WANK3R** [comment]
whats your discord?

**Comment by DonBruce64** [comment]
Link is in the wiki, or on the Curse site that brought you here.

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.

**Comment by WANK3R** [comment]
Thanks for the fix don
