### ISSUE TITLE
Teleporting long distances causes game to freeze

### ISSUE THREAD

**Issue by MrRedstoneA1** [DonBruce64/MinecraftTransportSimulator#1009]
It's pretty much as title says. If you teleport long distances, like over 30000 blocks, the game may freeze at any time. It's not always consistent and you might have to load new chunks, but eventually it always happens.

Forge 14.23.5.2855
-Immersive Vehicles 1.12.2-20.3.0
-Optifine 1.12.2-HD-U-G5 (might have something to do with this)
-Any vehicle pack, I used MTS Official Pack V22

Steps to reproduce:
Install all mods. Make a new world. To make testing easier, I'd recommended teleporting to x=0 and z=0 as it's easy to remember and is inside spawn chunks. 
Then teleport far away, like x=0 z=50000 and start teleporting back and forth. You might need to move and load new chunks but eventually the game will freeze.

Tested in a clean install of Minecraft and only with the listed mods. Was able to reliably reproduce the issue. There is no crash log because the game freezes, forcing me to forcibly close minecraft. I can try getting a crash log if required, but the game will not crash on its own. Just frozen.

If having trouble reproducing, try these java arguments:
-XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=50 -XX:+UseStringDeduplication -XX:+UseCompressedOops -XX:+UseCodeCacheFlushing -XX:ParallelGCThreads=8 -XX:+UseConcMarkSweepGC -XX:G1HeapRegionSize=64M -Dfml.doNotBackup=true

I don't know if these java arguments may contribute to the issue, but the issue disappears if IV is removed from the mods folder.

**Comment by DonBruce64** [comment]
Does this happen as of V20.5.0?

**Comment by MrRedstoneA1** [comment]
No, it does not freeze in 20.5.0 no matter how many times I teleported. Only in 20.3.0 it froze after 5-10 teleports.
