### ISSUE TITLE
Pull the stick back only make the heli pitch up vertically, no matter the bank angle

### ISSUE THREAD

**Issue by ktokto313** [DonBruce64/MinecraftTransportSimulator#1014]

**Comment by DonBruce64** [comment]
This will take some physics work.  Expect it to get done closer to the rotation overhaul.  I need to get through some existing bugs, and some owed features, then drop a release, then overhaul GUI rendering, and THEN I should be able to hit this.

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
