### ISSUE TITLE
animation centerpoint get messed with partslot scaling animation

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1018]
https://user-images.githubusercontent.com/79125581/146664195-3704cdc2-2374-49e9-b8c7-9a4dd2fc8493.mp4

https://user-images.githubusercontent.com/79125581/146664202-5487f293-6068-4eda-9a60-7af4cab33614.mp4

**Comment by DonBruce64** [comment]
This one is icky and due to the difference in the movement of parts vs the movement of rendering animations.  I'll fix it, but it'll take a bit as it's part of the animation abstraction overhauls.

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
