### ISSUE TITLE
[Suggestion] Snowplow part

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#102]
A snowplow part that breaks snow layer blocks, and perhaps other blocks.

**Comment by DonBruce64** [comment]
While I can see this being a nice novelty, I don't see this actually being useful for much of anything.  Perhaps in the future when helis and guns and boats and everything else is in, we can see about novelties, but for now, it won't happen.

**Comment by Blue20Boy17** [comment]
Yeah, like Immersive Engineering's snowplow car...
