### ISSUE TITLE
Misspelling in "IV operators manual"

### ISSUE THREAD

**Issue by AbnormalG1** [DonBruce64/MinecraftTransportSimulator#1020]
Page 3 from the very start of the book. at the very start of basic crafting it says "basic drafting"end of line 3

**Comment by DonBruce64** [comment]
I don't see anything about "basic drafting" here?
![2022-01-01_23 11 16](https://user-images.githubusercontent.com/15241611/147867019-fadb1214-fb57-43bd-b91d-f646261f06d1.png)

**Comment by mylesbartlett72** [comment]
It says "The Drafting Table is used to craft vehicles" starting end of line 3

**Comment by DonBruce64** [comment]
Ah!  I totally missed that.  It used to be called the Drafting Table, but that was changed a few versions back.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
