### ISSUE TITLE
"game crashes when attacking cars".

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1022]
![image](https://user-images.githubusercontent.com/79125581/146779412-ceb93d31-8bdd-4ca7-a0c6-5e38fd7d4657.png)

**Comment by Naxgeneral** [comment]
[crash-2021-12-19_22.33.29-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7745822/crash-2021-12-19_22.33.29-server.txt)

**Comment by DonBruce64** [comment]
Seems to be related to collision boxes.  Did you do a devMode import before this?

**Comment by DonBruce64** [comment]
Closing as suspected invalid on current release due to various code changes.
