### ISSUE TITLE
Parts that have inverseMirror don't mirror their parts

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1026]
The wheel in the trunk is identical to the wheel on the vehicle, but the hubcap is mounted on the back instead of the front.

![2021-12-26_16 47 42](https://user-images.githubusercontent.com/36775575/147424043-1c8181c7-eaa2-4229-ae0d-01f5114a2e9e.png)

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
