### ISSUE TITLE
Vehicle Text Fields darken with F1

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1030]
When F1 is pressed, vehicle text darkens. While DB said "Looks like I've got more qiurks to deal with.  The text darkening I really need to figure out as it's getting on my nerves.  Especially the flashing darkness when you're riding in a car" I was only able replicate it with F1.

This is only really noticeable with non-black text.

![2021-12-26_23 56 37](https://user-images.githubusercontent.com/36775575/147491765-5b6cd95b-4702-4605-abc7-dbd9f5e99a6a.png)
![2021-12-26_23 59 57](https://user-images.githubusercontent.com/36775575/147491766-5d996021-40f0-4d9f-a0cc-6b143fa3547c.png)

**Comment by DrprofLuigi** [comment]
I also notice that they darken when you hover over items in your inventory. I don't know how much that helps but hey

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
