### ISSUE TITLE
Hitbox rotations don't line up with model rotations

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1031]
All my hitboxes that have rotation animations are slightly off from the model, which is strange since every one is just copied from the animations section with the sounds removed.

It isn't very noticeable on small angles like the common 60, but it gets very obvious at larger angles, or when the door opens at an odd angle.

I'm guessing this has gone unnoticed since the vast majority of packs still seem to use the 'teleporting hitbox'

![image](https://user-images.githubusercontent.com/36775575/147491906-83071236-338a-4859-b0e2-ccf536ab14ae.png)
![image](https://user-images.githubusercontent.com/36775575/147491916-0cd109b8-28de-4cb0-8cfd-9a976e7506ae.png)
![image](https://user-images.githubusercontent.com/36775575/147491923-e7beff1f-42ad-4277-943e-6e29e84eaff8.png)

**Comment by DrprofLuigi** [comment]
I narrowed down the problem to being with _multiple_ rotations in an animation block. These Bucket trucks illustrate the issue perfectly:

The White truck only has the second part of the boom rotated, so the hitboxes line up fine since the first part is unrotated.

The Green truck has the first boom and the second boom rotated. The hitboxes on the first part is fine, however the second part is messed up.

Finally, the Blue truck has the base rotated, and all the boom sections partially rotated. As a result, all the hitboxes are messed up.

The Bucket Truck in the UNU DEV is a good test bed. I'll take a crack at this at some point when I can.

![2021-12-29_14 07 03](https://user-images.githubusercontent.com/36775575/147707022-2aef864e-6115-4190-84e2-734323edc2ec.png)

**Comment by DonBruce64** [comment]
Suspect this is related to #782, as the rotation math for the part rotation is the same math as for the hitboxes.

**Comment by DrprofLuigi** [comment]
Fixed in MTS V21

**Comment by DonBruce64** [comment]
Re-opening.  Tickets stay open until the release version drops with the fix.

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
