### ISSUE TITLE
Joystick crashes when going from V19 to V20

### ISSUE THREAD

**Issue by WANK3R** [DonBruce64/MinecraftTransportSimulator#1033]
I've narrowed the issue down to occurring after version 19.15.7(This is the last version the GUI was able to populate the screen) Crash Report Below
[crash-2021-12-27_22.21.47-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7782735/crash-2021-12-27_22.21.47-client.txt)

After fully reading the crash report. It seems the BuilderGUI.class file is the issue. 19.15.7 class file below.
[BuilderGUI.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7782745/BuilderGUI.txt)

**Comment by DonBruce64** [comment]
Would you be able to join the Discord so I could give you some beta builds?  I'll need to have specific code in there based on your situation to figure out why this is happening.  The main reason is there's two control systems in the mod now, and the mod defaults to the new one as the old one causes crashes on more units.  But that fouls the button mapping.  You can prevent crashing by deleting you config, but IV SHOULD detect these conflicts and resolve them before it gets to that point.

**Comment by WANK3R** [comment]
I will try the beta builds as well as replace the joystick driver to a more relevant one.

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
