### ISSUE TITLE
[BUG] Vehicles on roads don't try to revert steering? Or they do but not enough? ?????????

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1036]
https://user-images.githubusercontent.com/53581325/147866470-dd108355-5936-48c7-98a1-e459a011e28d.mp4

**Comment by DonBruce64** [comment]
I'm going to table this one for a bit.  I really need to re-visit roads,, but I don't want to do so until the trains from UNU or one of the other folks come into being, as that's really all road path-following is good for at this point.  Plus, I'd like to make the vehicles not use the main thread and not need to load chunks, but that's likely to happen after the rendering overhaul as trying to modify save/load operations while fighting render bugs is a recipe for pain.

**Comment by Jimmy805** [comment]
Wow! How did you do that? (I'm sorry but I haven't played MC for a while and I might have missed a few updates.)

**Comment by DonBruce64** [comment]
Fixed in V20.5.1.
