### ISSUE TITLE
Vehicles falling through ARK flatbed trailers

### ISSUE THREAD

**Issue by G0ingRogue** [DonBruce64/MinecraftTransportSimulator#1037]
feature worked fine up to beta 20.4.0-beta9. I don't have access to beta 10, so I am unsure if beta 10 or 11 is where it got broken

this is the feature in beta 9; https://i.imgur.com/fNFvdyJ.png
and this is on beta 11;  https://i.imgur.com/XZOk2aC.png

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
