### ISSUE TITLE
Texturepacks don't work in newer versions

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1038]
![e](https://user-images.githubusercontent.com/97041048/147949575-fb5f54f2-4368-43de-9529-89b1988906fb.png)

Latest version in which my texture pack is working is:
IV 19.3.0 - MTSOCP V19

My Texture pack changes the old wood texture of the MC-172 to the new wood texture introduced to minecraft as of 1.14.
The directory/path is correct, however the texture does not change in newer versions of MTSOCP & IV

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
