### ISSUE TITLE
Add objectName to activeAnimations.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1045]
This is necessary for easy creation of parts. Thus, for the base of machine guns or cannons, you will not need to create separate parts.

**Comment by DonBruce64** [comment]
This is not what activeAnimations do.  Those activate the part physics systems.  They do not active movement of the part.  That's in the rendering section.

**Comment by Prophet2002** [comment]
Ah, I mean movementAnimations.
