### ISSUE TITLE
Multiple boat-related issues

### ISSUE THREAD

**Issue by KikoKuso** [DonBruce64/MinecraftTransportSimulator#1049]
Boats cannot change direction (forward to reverse) or fully stop, dropping the anchor doesn't work and the only time you can get them to stop is when you get out of the vehicle.

Boats tested:
UNU dingly
UNU salmon
Mackerel Seagull
IVLabs boat
Trin Speedboat
Trin Reefer

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
