### ISSUE TITLE
Crash while in Vehicle

### ISSUE THREAD

**Issue by voidswrath** [DonBruce64/MinecraftTransportSimulator#105]
May be an issue with CMDcam or moreplayermodels. Hit the C keybind and it froze everyones game on my server and crashed us anytime we joined. Only fix was deleting player files and then when we did go on the vehicle was destroyed on login. I did also have a custom npc mounted in the vehicle

Client crash only

https://pastebin.com/J3xXLXGj

**Comment by DonBruce64** [comment]
What's CMDcam?  From what I can tell, pressing the horn button shouldn't crash your game...

**Comment by voidswrath** [comment]
yeah many things were happening. I am not sure CMDcam is related. It was a keybind apart of that mod.

https://minecraft.curseforge.com/projects/cmdcam

**Comment by DonBruce64** [comment]
Gotcha.  What does that keybind do when pressed?

**Comment by voidswrath** [comment]
The keybinds were changing the camera view.

**Comment by DonBruce64** [comment]
Can you be a bit more specific?  That crash shouldn't be able to happen, so anything that you can give me is helpful.

**Comment by voidswrath** [comment]
Here is the modpack packages up. It may be easier to bug test with it.

https://www.dropbox.com/s/jhtowikod9olts2/mods%201.12.2%20forge%202807.zip?dl=0

As for the server we are running 2814 and spongeforge-1.12.2-2768-7.1.4.jar
forge-1.12.2-14.23.5.2814-universal.jar

The crashing issue happens when hitting a certain keybind or randomly while in the vehicle (try H saw a client console log about an error with the horn)

A side issue is you can only sit in the vehicles once and then you can no longer get in the driver seat. You can get in other seats but not the drivers. you have to break the driver seat and replace it to sit again. 

The issues may be mod related or apart of spongeforge. Will take a deeper dive myself tomorrow.

**Comment by DonBruce64** [comment]
I can say that the seat issue is indeed related to Sponge.  It is documented in #73.  In short, Sponge is not calling the appropriate Forge events for the code it executes.

**Comment by DonBruce64** [comment]
Any updates on this @voidswrath?

**Comment by DonBruce64** [comment]
Closing due to a month without a response from the issuer.
