### ISSUE TITLE
[For the future] Add an animated crosshair for the guns.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1050]
By animated, I mean a crosshair similar to the one in War Thunder and Arm 3. That is, the crosshair will be displayed in the place where the bullet should fly. I think this is a very convenient and necessary feature, since without it it's hard to shoot from guns now.

**Comment by DonBruce64** [comment]
Given the math involved with this, it's not something I'm really keen on doing.  None of the the other gun mods do this, and gun creation itself is rather limited with MTS.  So it's not something I want to or see a need to do.  Maybe in the future when more packs with weapons come out and there's a demand for this type of content.  But not now.
