### ISSUE TITLE
Weapons, JSON and scaling

### ISSUE THREAD

**Issue by KikoKuso** [DonBruce64/MinecraftTransportSimulator#1052]
The weapons do not scale properly on higher and lower FOVs, making them a JSON object would solve this issue.

**Comment by DonBruce64** [comment]
They will never be able to be a JSON object, as JSON models don't support the same shapes as OBJ models.  However, I might be able to get them to render properly depending on where I put my rendering calls.  Backburnering as this is a visual and not a functional bug, and will be harder to fix than most things.

**Comment by DonBruce64** [comment]
So, I went and looked all though the code and took a deep think.  This is not something I will be able to fix without breaking other code assurances (like how the bullet must always spawn at the same point and that's at the end of the gun), this, and the HUGE offering of other gun mods that folks say are just so much better, means it's literally not worth the time to re-code the rendering system to fix what is a minor visual bug.
