### ISSUE TITLE
Vehicle Control Issues on Server(s)

### ISSUE THREAD

**Issue by Astro9986** [DonBruce64/MinecraftTransportSimulator#1055]
Been having issues on servers with cars forcibly "slalom-ing" without input after giving and releasing a steering input. No issues on Singleplayer. Servers were on version 20.3 and there were no issues, issues started after updating to 20.4 (which to my knowledge is the most recent non-beta release).

Singleplayer: https://drive.google.com/file/d/1psUNSoYNIZOFrz72ppss6Zjba-Wjrvaz/view?usp=sharing 

Server: https://drive.google.com/file/d/1qbgw4B7hiKalKYbQKmd5L8kbLFjqsFrr/view?usp=sharing

**Comment by Astro9986** [comment]
I would like to note that there were others complaining in #repair-shop in the MTS Discord not too long ago, myself included. This is not *just* me.

**Comment by DonBruce64** [comment]
Fixed in V20.5.0.
