### ISSUE TITLE
[BUG] Instrument Y Pos is flipped on the panel

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#1059]
The Y pos for instruments on the panel is flipped
Earlier [0,0] used to be the bottom left, but now it's top left
And a positive Y value moves the instrument downwards
Observed in v20.5.0 BETA22 and on Potato Vehicle Industries pack

**Comment by DonBruce64** [comment]
So, this is actually proper behavior.  Instrument positon should match the pixel position in texture editors.  Those use 0,0 as top left, and then +Y is down and +X is right.  So while this is a change and might break a few positions, it's actually proper.
