### ISSUE TITLE
[Suggestion] APU/GPU for recharging aircraft batteries.

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#106]
Jumper cables aren't the most realistic way to start up a plane with no battery. Provided with a model, could we get an APU part or a GPU block. This could help with people burning out the battery on the eclipse.

**Comment by DonBruce64** [comment]
Not sure about this.  I would like to have a single system for engines.  Although Jumper Cables work, it might actually be easier to make a "power block" that will generate power and can be hooked to engines.  Then again, block rendering is hard, so just drawing a line between two engines seems simpler.  Will consider.

**Comment by DonBruce64** [comment]
Considered.  For the sake of simplicity, and user-familiarity, I am going with jumper cables as being the standard way to re-charge vehicle batteries.  Should users wish another way we can investigate this, but for now jumper cables it will be.

**Comment by DonBruce64** [comment]
Added in V14.0.0.
