### ISSUE TITLE
The game crashes because of the treads.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1060]
[crash-2022-01-16_16.18.12-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7876650/crash-2022-01-16_16.18.12-client.txt)

**Comment by DonBruce64** [comment]
Does this:

Happen with just MTS installed?
Happen with other tanks besides the one you tried (which one was that)?

Need more information.

**Comment by Prophet2002** [comment]
> Does this:
> 
> Happen with just MTS installed? Happen with other tanks besides the one you tried (which one was that)?
> 
> Need more information.

incompatibility with Shoulder Surfing, info confirmed now

**Comment by DonBruce64** [comment]
Fixed in 20.5.1.
