### ISSUE TITLE
[BUG?] Doing variableModifiers incorrectly causes MTS to crash.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1068]
Unfortunately I've lost the json since then, sorry )
[crash-2022-01-21_16.22.00-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7917676/crash-2022-01-21_16.22.00-server.txt)
:

**Comment by DonBruce64** [comment]
Was fixed in commit f1c70570b2bc89b1b315a1094ff181bf7ff94cc7.

**Comment by DonBruce64** [comment]
Fixed in V20.5.2.
