### ISSUE TITLE
particle transparency bug

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1069]
![image](https://user-images.githubusercontent.com/63666200/150653205-5381a688-b5c8-46b7-aa8b-a481ecc0cf0f.png)
![image](https://user-images.githubusercontent.com/63666200/150653214-bff6e63b-48b1-4914-a123-309d0d12d2bd.png)
![image](https://user-images.githubusercontent.com/63666200/150653219-c21beed3-64c5-4ae0-9dda-df4292b0118d.png)
![image](https://user-images.githubusercontent.com/63666200/150653226-0d85e280-c5bc-447b-a33c-0f4bc6b5e116.png)

**Comment by DonBruce64** [comment]
Fixed in V20.5.2.
