### ISSUE TITLE
[BUG] Opening the instruments menu with no gauges in your inventory crashes the game.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1071]
Obviously only in survival
[crash-2022-01-23_01.41.48-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7919934/crash-2022-01-23_01.41.48-client.txt)

**Comment by DonBruce64** [comment]
Fixed in V20.5.2.
