### ISSUE TITLE
Immersive Vehicles Font

### ISSUE THREAD

**Issue by Chassx2** [DonBruce64/MinecraftTransportSimulator#1072]
![image](https://user-images.githubusercontent.com/56740526/151056552-610a81d5-baf2-45d9-ab3e-57be2797ae5e.png)
Cant seem to identify what is causing this font issue.

Did a complete reinstall of minecraft with optifine 
no shaders no resourcepacks.

**Comment by boot2big** [comment]
This is caused by the latest version of IAV.
Remove the parts pack for now, or try to remove their vanilla font override files.

**Comment by DonBruce64** [comment]
And as a duplicate this ticket gets closed!

**Comment by Orvngex** [comment]
I don't have IAV installed and this exact thing is happening now

**Comment by DonBruce64** [comment]
Then please open a new ticket.  This one is for IAV font issues.  Will need to know your exact version, what mods you are using, etc.
