### ISSUE TITLE
[BUG] Car panel's turn signal icon only blinks for right even if the left signal is on instead of flashers.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1073]
https://user-images.githubusercontent.com/53581325/151098201-5b35bb5f-4b49-4278-bbba-8c5df33a674c.mp4

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/152276471-d2a008cd-87a9-41ac-ba50-83a3968347e2.png)
Now it appears the panel tries to pull textures for *other* things from the panel's panel itself!?
![image](https://user-images.githubusercontent.com/53581325/152276540-11a742d1-95dc-47fe-aa51-d7b77f21b2bb.png)

**Comment by DonBruce64** [comment]
Fixed in 20.6.0.
