### ISSUE TITLE
[Plz Fix] Trying to back up the ocp brigadier to the scout for towing causes it to kill any health the scout had left

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1075]

**Comment by DonBruce64** [comment]
I mean, you were trying to tow it.  So it shouldn't matter if it's borken!

That being said, I'll disable all non-gun damage to vehicles in the next update.  That will fix propellers hurting vehicles, and wheels hurting vehicles, and suffocating hurting vehicles, and it'll help with the random 0-health issues I'm seeing too.  Plus makes for cleaner code as will it *really* hurt a car to chuck arrows at it?  Though this will break compat with other gun mods, but I don't really care about gun mods in general given how VMW is doing vehicles.

**Comment by DonBruce64** [comment]
Fixed in 20.6.0.
