### ISSUE TITLE
player being jumping on seat when press space and it not happen in old version

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1076]
https://user-images.githubusercontent.com/79125581/151177370-7b34e134-373e-4020-aa07-53c9e9132406.mp4

**Comment by boot2big** [comment]
Can confirm this issue, although personally I don't find it _too_ bothersome imo.
~~You probably hop in your seat when firing a gun or yanking the handbrake anyways~~

**Comment by Naxgeneral** [comment]
![image](https://user-images.githubusercontent.com/79125581/151498443-95478a6d-81cd-420c-80ae-c9d9e98c56a1.png)
probably no

**Comment by DonBruce64** [comment]
Fixed in 20.6.0.
