### ISSUE TITLE
Damage clamps are not in %

### ISSUE THREAD

**Issue by HashimIsaPotato** [DonBruce64/MinecraftTransportSimulator#1077]
Id like em to be in % so incase of increasing or decreasing the health, the vehicles damage animations dont have to be redone.
_pls i have like 40 damage animations done and i need to balance my weapons i cri_

**Comment by DonBruce64** [comment]
This probably could, and should, be PR territory.  I'm sure @DrprofLuigi could put it in if you were to ~~bribe him~~ ask nicely.

**Comment by DonBruce64** [comment]
Implemented in 20.6.0.
