### ISSUE TITLE
ticking entity crash

### ISSUE THREAD

**Issue by tomtomat0** [DonBruce64/MinecraftTransportSimulator#1079]
when i try to join my server it crashes
its only happening when vehicles are in the chunks that are gonna load if a player joins

**Comment by DonBruce64** [comment]
Gonna need a crash report if you want me to do anything about that.

**Comment by tomtomat0** [comment]
[crash-2022-01-25_22.10.10-server (1).txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7964247/crash-2022-01-25_22.10.10-server.1.txt)

**Comment by DonBruce64** [comment]
Released a beta on Discord that should have fixed this.  Can you test it?

**Comment by tomtomat0** [comment]
it now crashes on startup of the server 
[crash-2022-01-30_09.17.38-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7965540/crash-2022-01-30_09.17.38-server.txt)

**Comment by DonBruce64** [comment]
This should be fixed in the latest beta posted on Discord now?

**Comment by DonBruce64** [comment]
Fixed in 20.6.0.
