### ISSUE TITLE
[Suggestion] Scratches and Dents

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#108]
Create scratches and dents (texture) when crashing into blocks. These dents and scratches could be fixed either with a new item such as a hammer or a paint can.

**Comment by TheCactus27** [comment]
I would be fine with having the scratches just be rendered anywhere despite that area not being damaged, it would just give more immersion.

**Comment by DonBruce64** [comment]
Not going to happen.  Too hard to get the rendering right, and would require massive code overhauls and linkings between the model rendering systems and collision systems, and those are bloated and cumbersome enough already.
