### ISSUE TITLE
[Minor BUG] MTS disobeys .json model scaling, please whack with wrench

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1083]
![image](https://user-images.githubusercontent.com/53581325/152666020-9763b716-5492-48ce-9d05-0f52d284b34a.png)
![image](https://user-images.githubusercontent.com/53581325/152666025-d6bcb068-6b45-49cb-af86-6b03c191acc9.png)
![image](https://user-images.githubusercontent.com/53581325/152666031-729dd297-cbea-4b27-848a-dc8472a9a246.png)
I wish to threateningly inform you that you have placed poor misjudgement in your choice to commit home invasion and trespassing upon my property

**Comment by DonBruce64** [comment]
Fixed in 20.6.0.
