### ISSUE TITLE
Aternos kickt mich vom Server wenn ich Item in die Hand nehme

### ISSUE THREAD

**Issue by Ghostflori** [DonBruce64/MinecraftTransportSimulator#1088]
Ich habe ein Aternos Forge Server und wollte dort die Mod ausprobieren. Sobald ich alles heruntergeladen habe, wollte ich die Mod testen. So nahm ich ein Item von der Mod in die Hand und im gleichen Moment trennte es die Verbindung vom Server. Nach einer kurzen Zeit habe ich es im Einzelspieler modus versucht und dort ist es gegangen. Ich hoffe ihr könnt mir helfen!

**Comment by DonBruce64** [comment]
Wenn Sie mir nicht eine Latest.log-Datei von Ihnen und dem Server geben können, wenn Sie gekickt werden, kann ich Ihnen nicht helfen. Ich vermute, dass Sie auf Ihrem Server nicht die gleichen Pakete haben wie auf Ihrem Client.

**Comment by DonBruce64** [comment]
Closing due to no response from the user.
