### ISSUE TITLE
[Bug] Driveshaft Variable Speed

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#109]
Woah, I'm actually using the issue tracker to post a bug, and not make a suggestion? wack

Anyway, I noticed a few updates ago the driveshaft variable spins slower than wheels, making my hubs look funny.

I attached a Quality UNU vehicle .json, but github didn't like that so it's a .txt for now
[btcivil_vehicle_unu_cp497ltc_2089_sedan.json.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/2976296/btcivil_vehicle_unu_cp497ltc_2089_sedan.json.txt)

**Comment by DonBruce64** [comment]
Fixed in V14.0.0.
