### ISSUE TITLE
Black items in all IV GUI's

### ISSUE THREAD

**Issue by MrRedstoneA1** [DonBruce64/MinecraftTransportSimulator#1090]
When any IV GUI is opened, like a crate or bench, all items displayed in the GUI turn pitch black. That includes the player's inventory, except after exiting the GUI and opening the vanilla inventory with E everything is back to normal.

mod version:
Immersive Vehicles 1.12.2-20.6.1
Immersive Vehicles 1.12.2-21.0.0 BETA 18
EDIT: Turns out their brightness is applied using world brightness, so during the day they're bright and during the night they turn black.

**Comment by DonBruce64** [comment]
Fixed in V20.6.2.
