### ISSUE TITLE
Sometimes players can get shredded by their own propellers and run over by their own tires when driving/piloting

### ISSUE THREAD

**Issue by MrRedstoneA1** [DonBruce64/MinecraftTransportSimulator#1091]
Basically, sometimes when piloting a plane, the plane's propeller will start damaging the pilot. Death message looks something like "MrRedstoneA1 was shredded by MrRedstoneA1's propeller". Same can happen when driving cars, the tire death message probably looks the same. Difficult to reproduce, it seems to only happen sometimes. For me it happened once while piloting the Ford tri-motor. Will add steps to reproduce if I find them reliably.

Steps to reproduce for plane:
1. Make a plane. Ford trimotor seems to produce reliable results.
2. Take off.
3. Bank hard to either side.
4. The propellers start to damage the player.

Steps to reproduce for car:
1. Make a car. I used a blue scout.
2. Start driving. Accelerate and steer fully to the left or right.
3. The wheels seem to kind of come off the car and lag behind, damaging the player.

Mod version:
Immersive Vehicles 1.12.2-20.6.0 (initial encounter by me)
Immersive Vehicles 1.12.2-20.6.1 (other users experienced)
MTS_Official_Pack_V23

**Comment by DonBruce64** [comment]
Fixed in V20.6.2.
