### ISSUE TITLE
HUD is on top of open GUIs

### ISSUE THREAD

**Issue by MrRedstoneA1** [DonBruce64/MinecraftTransportSimulator#1095]
The player HUD like health bar, armor bar, food bar and other HUDs added by other mods like thirst bar appear on top of certain GUIs like crates.
Steps to reproduce:
1. make a vehicle and add a crate to it.
2. open the crate.
3. the HUD is on top of the GUI.

**Comment by DonBruce64** [comment]
Fixed in V20.6.2.
