### ISSUE TITLE
Plane Crashes Are Wonky

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#11]
Or rather, the lack thereof. Being able to drive a plane on one wing and a pontoon with no consequences is just wrong.

Video on YouTube now! https://youtu.be/GD4d1pFcQvY

(Basically, the mod needs crash physics/fuselage damage in order to behave properly.)

**Comment by DonBruce64** [comment]
Did you have BlockBreakage turned off during that?  With those speeds I'd expect the plane to dig into the dirt....

**Comment by DonBruce64** [comment]
Checked this in-game just now.  And while I do see planes running on one wing, I would rather they be able to have a wingstrike that's gentle and not crash than an instant KO or loss of a wing.  Flansmod is that was with collisions, and while I want to penalize players for flying into a tree, I don't want them to have too much lag on a tight bank and having a wing strike blow them up.

Now if MC get to not be a lag-fest, then we can change a few things.  But that's not looking too good right now...
