### ISSUE TITLE
Request: Convertible Tops (not as hard as it sounds, I promise)

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#110]
Could just be created using two model part names, like $ConvertibleTopUp and $ConvertibleTopDown, or something along those lines. When you hit the button to raise or lower the top (only works while stopped), the "up" model goes invisible and the "down" model appears, or vise versa.

**Comment by DonBruce64** [comment]
The biggest issue here is one you might not have thought about: sound.  Specifically, vehicles with tops muffle the sound of the engines, while those with open tops do not.  There's a parameter in the JSON for this, so having vehicles that can have open tops or non-open tops would involve SoundSystem changes.  Those wouldn't be too hard, but would require some care to ensure nothing gets fouled up for vehicles without convertible tops (like planes).

On a related note, how do you plan on doing keybindings?  Remember: we don't want any more than what is absolutely required as IV has enough keybindings as it is.

**Comment by fsendventd** [comment]
I was thinking a button on the dash or something. Maybe a modifier key plus a function key (like W) could work.

**Comment by DonBruce64** [comment]
After many days of thought I've decided not to implement this.  It's a lot of work, involves yet another keybind (there's no panel/dash for vehicles, so you have to use a keybind), and would mean I have to re-do the SoundSystem.  All in all, lots of work for very little reward, especially when most people will just make convertibles in their top-down state as they look cooler.

**Comment by fsendventd** [comment]
Sadness. I suppose I can just make the top a part instead.
