### ISSUE TITLE
Controller Causes Crash

### ISSUE THREAD

**Issue by CSX8600** [DonBruce64/MinecraftTransportSimulator#1101]
With a PC-specific XBox controller plugged in while Minecraft loads, mounting a vehicle causes a crash...looks to be due to controls

https://pastebin.com/UbpmAMaL

**Comment by DonBruce64** [comment]
Odd, could you join the Discord and ping me so I can send you a few betas?  I'm like 95% sure that this should have been fixed in the latest version...

**Comment by DonBruce64** [comment]
Closing due to no response from user.
