### ISSUE TITLE
Rendering issue (screen turns white)

### ISSUE THREAD

**Issue by InkPhoenix** [DonBruce64/MinecraftTransportSimulator#1102]
Been getting this weird issue lately where some vehicles make the screen go completely white when placed down (sometimes the colour changes depending on the time of day in-game)
![0](https://user-images.githubusercontent.com/99095585/154860677-df170f63-fd28-4b37-9df2-19e86407c69f.PNG)

The game continues to run fine though and if i manage to break the vehicle the screen goes back to normal
![1](https://user-images.githubusercontent.com/99095585/154860718-3e38e911-95a2-4699-a8fe-ba9d368145de.PNG)

I'm playing with Optifine and with fast render off, if i enable it the world seems to only render half of the faces.
![3](https://user-images.githubusercontent.com/99095585/154860827-71db47a9-fc45-4d2e-ab07-cf17526f7426.PNG)
![2](https://user-images.githubusercontent.com/99095585/154860836-62555286-3b58-4e52-be93-851f91b4a0ce.PNG)

I'm playing on version 1.12.2 with these mods:
![4_1](https://user-images.githubusercontent.com/99095585/154860949-3ac638dc-493d-4d6a-8d92-887b99670c2c.PNG)

I can also provide a world download if required

**Comment by DonBruce64** [comment]
Linked to mirroring states and the switch from back to front-face culling on models.

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
