### ISSUE TITLE
crash for unknown reason (vanillafix says MTS cause crash)

### ISSUE THREAD

**Issue by leonpano2006** [DonBruce64/MinecraftTransportSimulator#1104]
[crash-2022-02-28_20.51.49-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8156447/crash-2022-02-28_20.51.49-client.txt)

**Comment by DonBruce64** [comment]
Seems to be related to the debug profiler that shows up when you press SNEAK+F3?  Does something there trigger this crash?

**Comment by DonBruce64** [comment]
Closing due to no response from user.

**Comment by leonpano2006** [comment]
Oops I didn't 
Yes as what you said

**Comment by leonpano2006** [comment]
Sry for 21days no response
