### ISSUE TITLE
Seat parts don't animate.

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1108]
Seat parts do not animate with applyAfter or their own animations on the part slot on a vehicle.

**Comment by DonBruce64** [comment]
Odd, can you give me a specific example of a seat part/slot to try this out with?  I don't see what's going wrong...

**Comment by DonBruce64** [comment]
Seems to be working to me, and was told to close ticket, so is a-closing.
