### ISSUE TITLE
(Request): Jacks and lifts

### ISSUE THREAD

**Issue by Blue20Boy17** [DonBruce64/MinecraftTransportSimulator#111]
It would be a neat feature (though you will probably label this as "wontdo") to have jacks to lift up you vehicle to change your flat tire or whatever, and also have lifts like you see in garages that raise the whole vehicle. Jacks, prolly not too hard, lifts, prolly pretty hard.

**Comment by DonBruce64** [comment]
This would only serve to add an extra layer of complexity to the wheel system, and would involve lots of extra JSON work for pack authors to define jack points, height, and lift sizes.  Not to mention vehicles in packs being widely different in sizes.  Not going to be implementing this any time soon.
