### ISSUE TITLE
Bugs with rotations.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1110]
1) The camera from 1st and 3rd person, as well as the camera from MTS are out of sync;
2) Muzzle position and gun animation are out of sync;
3) The rotation speed of several guns is different for the controller, although they have the same speed in the config;
4) The pitch angle of one gun adds angle to the other if it is selected when the gun has reached its maximum angle.
https://youtu.be/htiTxxaYj7M

**Comment by DonBruce64** [comment]
1. Define: out of synch.
2. Show video please, with F3+B bounding boxes turned on.
3. Can you give me exact gun configutations?
4. The issue in that video is that your MG is being allowed to rotate on its mount and change firing angle.  For coaxial guns, you need to not define a min/max yaw on the part slot as that will result in them rotating when selected.  If you have min/max yaw on the gun's JSON, remove it, as that will cause issues with the rotation code.

**Comment by DonBruce64** [comment]
Closing due to no response in 2 months.
