### ISSUE TITLE
Editable Text Miscolor

### ISSUE THREAD

**Issue by bobgrey1997** [DonBruce64/MinecraftTransportSimulator#1111]
If editable text is given the same color code as a part of the base texture, it will show up the same in the GUI, but different in the world.
For example, I have some signs with a blue or green background and white text and outline. The editable text will show up darker than the outline or non-editable text (part of the actual texture).
Attached are some images.
This does not seem to effect black text, presumably because the editable text can not any darker than the non-editable black segments.

Here is an image of the sign GUI with a clip of the signs placed in the world.
In the preview in the GUI, you can see all the text and outline are the same white color. However, in the world, the outline and any base text (the word "Interstate") are a light gray, almost white, while the editable text (route number and "Arkansas") are a darker gray.
https://i.imgur.com/uBObqHn.png

In these images, you can see the same happens with yellow text.
Here is a county route sign in the preview, where you can see all the text and outline matching:
https://i.imgur.com/phlGDNU.png

In this image of the sign placed in the world, the "Test" and "88" (editable) are darker than the "County" and outline (in the base texture):
https://i.imgur.com/6n28KZU.png

**Comment by DonBruce64** [comment]
Turns out this was due to some oddness in how the normals were exported from the model, and how it was being shaded.  As Blender showed this behavior too, I'm going to close this ticket as the rendering system is rendering the model as the model is defined, just the model is defined incorrectly.  Really, this is a FMT issue.
