### ISSUE TITLE
[Suggestion] Road Speed Limits

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#1112]
Add a feature to roads where all vehicles match the designated speed limit. The limit can either be changed using a wrench on already placed roads or set when placing the road (clicking in the air opens a GUI). When changing speed limits with the wrench, have a setting to apply the new speed limit to all road segments or just the currently selected segment.

**Comment by DonBruce64** [comment]
This will likely happen after the global road multi-threading addition, as it'll let me make a controlled road system independent from the main system.  I for sure want this, as I can see it having multiple applications, but given current road usage I can't rightfully prioritize it.

**Comment by DonBruce64** [comment]
So, after a long thought, I'm gonna can this. I want to do this, but I just can't see me devoting this much time to roads given the usage they are getting currently (i.e., no packs with roads in them).  If they become more popular, then I'll see about automating them.
