### ISSUE TITLE
Incorrect MTS Weapon Kill Feeds

### ISSUE THREAD

**Issue by Dubbington** [DonBruce64/MinecraftTransportSimulator#1113]
When killing a named entity with an MTS Gun Mount (whether that be a player or something like a wolf), the kill feed will appear reversed

Eg.
Normal Kill Feed: [Killed Entity] was slain by [PLAYER]
Example shown below: [PLAYER] was slain by [Killed Entity]

![2022-03-05_11 46 12](https://user-images.githubusercontent.com/75969752/157136321-9d45d9a0-1665-4247-b4aa-91bbbd0a0b4a.png)

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
