### ISSUE TITLE
seat scale factor dose not adjust camera or actual location properly 

### ISSUE THREAD

**Issue by BloodMoonAbyss** [DonBruce64/MinecraftTransportSimulator#1114]
okayconfirmed its only resizing the visual player model but nothing else
also seats are borked in mini cooper tryed to use the same style that is shared with bunno cc and dose the same thing model resize but not camera or other stuff and player is not rotated properly in seat

this only applies to seats with size scale factors all else works as intended
![unknown](https://user-images.githubusercontent.com/92669440/157457359-6bf4e9f1-e855-43e2-9d51-c9bdc31b88c7.png)
![image](https://user-images.githubusercontent.com/92669440/157457461-3100800b-ec9b-4bf7-b88f-c4050acb3aaf.png)

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
