### ISSUE TITLE
all external controlers aside from keyboard and mouse reset / wipe config every time game is rebooted 

### ISSUE THREAD

**Issue by BloodMoonAbyss** [DonBruce64/MinecraftTransportSimulator#1115]
as title says when you rejoin a server or map with the mts config for controlers it wipes what controls are set to what and must be remapped every time you rejoin or restart the exact controler i use is a xbox one s wired controler and or a steering wheel logitec one ment for ps2 pc and xbox 360 forgot the exact name of wheel

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
