### ISSUE TITLE
gauge cluster ui dose not hide armor health or xp bar and only hides hunger bar and wont overlay over them 

### ISSUE THREAD

**Issue by BloodMoonAbyss** [DonBruce64/MinecraftTransportSimulator#1116]
![image](https://user-images.githubusercontent.com/92669440/157484759-fb452662-4064-4e00-9075-12547737a1ba.png)

so it dose not overlay over the stock minecraft ui like it did in past but dose hide the hunger bar as intended ? maby ? 

and half size one gets even more wonky

![image](https://user-images.githubusercontent.com/92669440/157485152-6da7c400-3c60-4a81-a509-90f60a74cc1d.png)

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
