### ISSUE TITLE
incomprehensible artifacts

### ISSUE THREAD

**Issue by XviktorwoodX** [DonBruce64/MinecraftTransportSimulator#1118]
the fact is that I have a good pc, and I have a whole video card (other games work fine), but something similar happens in minecraft, as you can see in these photos
![2022-02-21_17 38 35](https://user-images.githubusercontent.com/93402694/157700275-d2dbd76a-782c-4a07-b0a4-96c18a3581f3.png)
![2022-02-21_17 38 39](https://user-images.githubusercontent.com/93402694/157700290-aa0faacd-d696-418a-81bb-71a7428f1172.png)

crash report and logs: 
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8224899/latest.log)
[crash-2022-03-10_13.06.14-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8224903/crash-2022-03-10_13.06.14-client.txt)

**Comment by DonBruce64** [comment]
Fixed in V21.0.0.
