### ISSUE TITLE
[Suggestion] currentMass variable

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1124]
A simple variable that outputs the current mass of the vehicle (taking into account installed parts and whatnot). 

Bonus points if we also get a massPercent that outputs as a percentage of the vehicles' mass (so it would usually be above 1 unless a VM modifies base mass). Extra cool if massPercent was 1 when the vehicle had all defaultParts installed, but the current mass would be plenty.

Of course I may PR this, so no stress.

**Comment by DonBruce64** [comment]
Mass percent won't work, as you won't know how much a "full" vehicle is.  But you can get a raw value and just compare it against a rated value.  You can PR this one, as it's literally one line though!

**Comment by DonBruce64** [comment]
Implemented in V21.2.0.
