### ISSUE TITLE
The game crashes when fired from a handheld gun.

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#1126]
The problem appeared, most likely with V21 BETA-60.

Crash log:
[crash-2022-03-14_08.24.50-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8241103/crash-2022-03-14_08.24.50-client.txt)

**Comment by DonBruce64** [comment]
Fixed in V21.1.0.
