### ISSUE TITLE
[CRASH] Immersive Vehicles is Causing Crashes On World Exit

### ISSUE THREAD

**Issue by PyroSimba** [DonBruce64/MinecraftTransportSimulator#1128]
VanillaFix is saying the crash is caused by Immersive Vehicles but I'm at a loss for what the problem is. Is there anything I should be doing on my end?

[**Crash Report**](https://pastebin.com/hZDthXgw)

**Comment by DonBruce64** [comment]
Fixed in V21.1.0.  I actually saw this one before seeing this ticket.  Go figure!
