### ISSUE TITLE
player facing is incorrect 

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1129]
https://user-images.githubusercontent.com/79125581/159149887-aaa3f647-cc84-4f35-97e6-6aa03431c962.mp4

**Comment by DonBruce64** [comment]
This is gonna be rather icky to fix, as I'll need to add code that will split out the MC player yaw, and the internal head-yaw I have for vehicles.  Since it'd just sound, it's low priority, but will get done eventually.

**Comment by DonBruce64** [comment]
Fixed in V21.1.0.
