### ISSUE TITLE
Custom variables created with variableModifiers not working on part animations

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1130]

**Comment by DonBruce64** [comment]
Is this on the part slot or the part itself?  Where is this variableModifier defined?  Where is it being referenced?

**Comment by BlazeWolf1122** [comment]
the variable is defined in variableModifier, and it is being referenced on part slots
like in #1131, it's on the part slot

**Comment by DonBruce64** [comment]
`Where is this variableModifier defined? `

**Comment by BlazeWolf1122** [comment]
defined, as in?

**Comment by BlazeWolf1122** [comment]
it's literally created in variableModifiers
![image](https://user-images.githubusercontent.com/63666200/159804791-84e40cf8-fb6f-4f6b-98ab-0aa92437c7ce.png)

**Comment by DonBruce64** [comment]
But where is this variableModifiers?  The part?  The vehicle?  The spare tire in the trunk?

**Comment by BlazeWolf1122** [comment]
the vehicle

**Comment by BlazeWolf1122** [comment]
it suddenly works in the current beta
ok no wonder this ticket is closed

**Comment by DonBruce64** [comment]
Ooops, I didn't mean to click that button.  I meant to click comment, not close with comment.  But, if it works, then it works I reckon.
