### ISSUE TITLE
Speedometers broken

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1132]
https://user-images.githubusercontent.com/63666200/159200181-334d73ac-0069-4a7d-a407-7ac3a3be738a.mp4

**Comment by DonBruce64** [comment]
Was fixed in commit 24e7060cfa3afa7e4c071737d32f3ce6e4005135, is fixed in latest beta.  Will close when release version is fixed.

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
