### ISSUE TITLE
Crash with painting cars from GGVP in v21.2

### ISSUE THREAD

**Issue by XviktorwoodX** [DonBruce64/MinecraftTransportSimulator#1133]
the problem I face when repainting nax cars, namely, I encountered such a problem with Toyota Camry XV40 (fully) and Datsun 100a (partially)

here is logs:

[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8325567/latest.log)
[crash-2022-03-20_23.43.48-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8325569/crash-2022-03-20_23.43.48-client.txt)

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
