### ISSUE TITLE
speedometers work, but somehow tachometers don't

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1134]
what

**Comment by DonBruce64** [comment]
https://user-images.githubusercontent.com/15241611/159840914-6e976575-aa91-4bf7-9def-a4bab0fa7304.mp4

They seem just fine to me?

**Comment by BlazeWolf1122** [comment]
will check the latest beta

**Comment by BlazeWolf1122** [comment]
![image](https://user-images.githubusercontent.com/63666200/159860793-3326075b-5caf-4ad1-911f-f87e6c34e8a0.png)
Seems to be a [packard] with that specific vehicle then, my bad

**Comment by BlazeWolf1122** [comment]
but i've never seen a bug like it before, so that confuses me

**Comment by BlazeWolf1122** [comment]
what causes a vehicle to make the engine gauge not work, despite a running and functional engine in it?

**Comment by BlazeWolf1122** [comment]
![image](https://user-images.githubusercontent.com/63666200/159862705-74b35044-9902-4efa-aee6-52c5ffb78e3a.png)
does this help?

**Comment by BlazeWolf1122** [comment]
Does this help?
![image](https://user-images.githubusercontent.com/63666200/159862876-ad5ad673-0144-4ca0-b763-59cf60753a5f.png)

**Comment by DonBruce64** [comment]
Your instrument slot def probably has an optionalPartNumber on it that's making IV look for an engine that doesn't exist.  Spedometer works because that variable doesn't care what it's on, but since RPM is an engine-specific variable, the code won't ask the vehicle for that info as it knows it won't have it.

**Comment by DonBruce64** [comment]
Closing as this was due to part slot being incorrectly referenced.
