### ISSUE TITLE
Handhelds face a fixed position when held in vehicles

### ISSUE THREAD

**Issue by Dubbington** [DonBruce64/MinecraftTransportSimulator#1136]
Since players are technically only facing one specific way while riding vehicles, it causes handhelds to also face that way, causing whatever the hell you want to describe this anomaly as.
![2022-03-23_23 57 35](https://user-images.githubusercontent.com/75969752/159968123-9d8b1952-93f4-4dd6-8021-7f16be8199d4.png)

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
