### ISSUE TITLE
Request: Configurable shift RPM for automatics

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#114]
The majority of automatic transmissions out there don't shift at the engine redline (unless they're in a mode where they're specifically told to do so). Is it possible in MTS to allow people to set a shift RPM in the engine JSON instead of letting the mod do it?

**Comment by DonBruce64** [comment]
It's possible for sure.  The only issue is that you'd have to be careful when you set your RPMs to avoid a feedback loop.  If you set your up RPM to be 2500 or so, and then your down RPM to be 1500, then it's quite possible for you to get "stuck" between two gears and shift up and down constantly as the system tries to keep you between those two values.

That being said, it does make code simpler, though it wouldn't take into account the throttle position like real vehicles do.

**Comment by fsendventd** [comment]
Simple code is good. And I could probably get it to account for the throttle position if you threw a decompiled code chunk at me.

**Comment by DonBruce64** [comment]
Relevant code line for shifting up/down decisions:
https://github.com/DonBruce64/MinecraftTransportSimulator/blob/cd478e500a3f27d5f61de45395a156911445d4ba/main/java/minecrafttransportsimulator/vehicles/parts/PartEngineCar.java#L48

**Comment by DonBruce64** [comment]
Closing due to lack of community support and difficulty of coding.
