### ISSUE TITLE
engine_clutch_upshift/downshift variable does not work in automatics unless user input in shifting up/down is given

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1141]
i kinda need it (clutch_up/downshift to work) for automatics, not just manual engines exclusively, or in a really specific case where in an automatic you shift into drive/reverse
if someone wants clutch up/downshift to be disabled while gearing up or down, they can get the gear the car is in then clamp it/inhibit it

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
