### ISSUE TITLE
(Bug) Crafting recipe for most benches not working on a server

### ISSUE THREAD

**Issue by DNGDynamo** [DonBruce64/MinecraftTransportSimulator#1146]
We are playing on a 1.12.2 fairly modded server with IV and a couple of addons and for some reason the recipes for the benches aren't showing up on JEI and looking up the recipe doesn't help either

**Comment by DonBruce64** [comment]
This is because I removed them for the latest update.  Fixed in this commit, 10426f3acc6f4faeb77b41593d7f3be6c3e2f851, and will be fixed in the next update.

**Comment by recolic** [comment]
I have a similar issue: 

 I upgraded to MTS_Official_Pack_V23 just now. However, I realized I can not see recipes with JEI anymore. (I'm using jei_1.12.2-4.16.1.302, and it was working in V19)  
I can see the recipes for vehicles, but I cannot see any recipes for decor bench or any other benches.

**Comment by JediMaster66406** [comment]
I also cannot see the recipes for the workbenches and cannot find them online.

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
