### ISSUE TITLE
Server crashes when vehicle lights are turned on

### ISSUE THREAD

**Issue by Cosmic-8** [DonBruce64/MinecraftTransportSimulator#1148]
For some reason my 1.12.2 server will crash whenever I try to turn the lights on on any vehicle. Both the official pack and UNU display this behavior.

**Comment by DonBruce64** [comment]
Noted and addressed in commit b23f8c321c86733bbb165e3dfe3192979d2133cb.  Beta is on Discord with the fix, release should come out sometime next week.

**Comment by Cosmic-8** [comment]
Ok! Thanks!

**Comment by DonBruce64** [comment]
I am re-opening this issue as it's not fixed in the release version.  Will close when it's pushed to Curse.

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
