### ISSUE TITLE
Request: Manual mode for automatics 

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#115]
This would be useless without #114, but if that did get implemented, then we could have a keybind or dash button (potentially Ctrl+R) that switches automatics into manual mode. They would still shift up if the engine hit redline, but otherwise you could do whatever you wanted.

**Comment by DonBruce64** [comment]
Automatics shift automatically.  Manuals get shifted manually.  If players want to change this, then they can change engines.  It's why they are parts in the first place...

**Comment by fsendventd** [comment]
...have you not seen modern automatics? A lot of performance cars with automatics have paddle shifters to allow for some control over the shift points. Makes them more fun to drive, and also allows for better performance in situations where the computer deems it "unnecessary" to go fast.
