### ISSUE TITLE
Bell Helicopter [bug?]

### ISSUE THREAD

**Issue by Colt44Magnum** [DonBruce64/MinecraftTransportSimulator#1151]
When leaving the Bell helicopter in the OCP I have been consistently put into the blades. This might be a jsoning issue or just a bug. The only time it worked close to normal was it placed me on top the helicopter then put me over three blocks to the side.

**Comment by DonBruce64** [comment]
Un-sure if this is a pack bug or a core code bug.  I suspect it's a pack one, so I'm flagging it as such for the moment.

**Comment by DonBruce64** [comment]
Turns out it's not just this vehicle, and is global.  Re-routing to the global ticket #1167 and flagging this as a dupe.
