### ISSUE TITLE
Fuel pumps not displaying contents or level

### ISSUE THREAD

**Issue by Bomboy09** [DonBruce64/MinecraftTransportSimulator#1153]
I place a fuel pump and when I try to fill it, it fills but nothing displays on the pump. I have removed Optifine and tried again to see if that was the issue and there was no change. I also re-installed and replaced my file and it did nothing. Please fix this issue. Thank you.
(See images below)
Before
![2022-04-05_17 36 33](https://user-images.githubusercontent.com/103078406/161862362-a288ad78-6621-4447-a341-f22ed5b34036.png)
After
![2022-04-05_17 36 37](https://user-images.githubusercontent.com/103078406/161862407-3b7c44c7-634d-418d-aeab-6dd0bc78f0dd.png)

**Comment by DonBruce64** [comment]
Noting this as addressed in commit d47cc6c5a4127335379908feb6b548fe8e7ed849.  Will close ticket when release drops on Curse.

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
