### ISSUE TITLE
Plane physics buggy

### ISSUE THREAD

**Issue by WANK3R** [DonBruce64/MinecraftTransportSimulator#1156]
When trying to take off with any plane(except the heli) they seem to stick to the ground but still slightly tilt up or down or roll. The planes also jitter when using yaw movements. This issue arises randomly but once it does its permanently there. This is after the most recent release.

**Comment by DonBruce64** [comment]
Was fixed in commit 24e7060cfa3afa7e4c071737d32f3ce6e4005135, is fixed in latest beta. Will close when release version is fixed.

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
