### ISSUE TITLE
[Render Issue] Armor doesn't move with the player when using Obfuscate

### ISSUE THREAD

**Issue by gatoborrachon** [DonBruce64/MinecraftTransportSimulator#1159]
**What is happening**
When you use [Obfuscate](https://www.curseforge.com/minecraft/mc-mods/obfuscate) (a library mod) and MTS, the render of things like Armors or the [Ido](https://www.curseforge.com/minecraft/mc-mods/ido) new movement mechanics go wrong

**Steps to reproduce**
1. Add Obfuscate and MTS
2. Wear any vanilla armor
3. Move

**Screenshots**
Notice how the armor acts like a static chunk, while the arms and legs of the player entity are moving
![2022-04-10_12 06 04](https://user-images.githubusercontent.com/61126174/162631146-3d2ce7e6-2c66-4ece-aafc-b3baa2d91388.png)

**Versions**
Immersive Vehicles: 1.12.2-21.1.0
Obfuscate: 0.4.2-1.12.2

**Additional Notes**
Downgrading to MTS 1.12.2-20.5.2 fixes the issue (since it was the last version before i updated to 21.1.0, idk if any other version between 20.5.2 and 21.1.0 causes this issue)

**Comment by DonBruce64** [comment]
Hrm, if you disable player tweaks and reboot the game, does this still happen?

**Comment by gatoborrachon** [comment]
yeah, disabling that config option fixes the issue
![2022-04-11_08 50 53](https://user-images.githubusercontent.com/61126174/162754371-7cbbcf0c-49f2-4e25-94c9-5740fa9b9119.png)

**Comment by DonBruce64** [comment]
In that case, this feature is behaving as expected.  Some mods override the player model to do their stuff.  IV needs to do that to render guns and proper seating animations.  So you either get one or the other, not both.  Nothing I can do as Forge doesn't provide hooks for the player model modifications.

**Comment by gatoborrachon** [comment]
ok, no problem, i saw the animation you say inside cars, and it is pretty, but i guess i will require to choose the lesser evil, thanks anyways

**Comment by DonBruce64** [comment]
Yeah, unless Forge updates there's nothing I can do on 1.12.2.  I might be able to fix this with Mixins on a higher MC, but I've not yet coded for that, so not sure at the moment.  Will investigate when I get to that point.

**Comment by gatoborrachon** [comment]
hahaha, well, we well know that Forge doesn't even support newer versions like 1.17 today, and since the new movement mechanics are part of vanilla, I don't think there should be a (bigger) problem in newer versions
