### ISSUE TITLE
I can't seem to find any Bullets in 1.12.2-19.15.7

### ISSUE THREAD

**Issue by KitLoaf1** [DonBruce64/MinecraftTransportSimulator#1161]
I can't seem to find any Bullets in 1.12.2-19.15.7.
I use this version since i use the Warfare 44 extension Pack that needs this Version. I can only find the M1919 but no Ammunition.
Any solutions or do i need to drop the extension pack?
And yes the Bullets do appear in newer version.

**Comment by DonBruce64** [comment]
This is for an obsolete version of IV.  Therefore, it is not a bug.  W44 needs to move things in their folders to the new locations to be compatible with the new bullet systems that all other packs now use.
