### ISSUE TITLE
Dismount position appears to be broken

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1167]
Apart from the several people complaining about being dismounted into the rotor blades of helis, this also happens to me and my heli. Probably because IV is deciding to place the player at 0.0 (0.0 is usually the centre of the rotor shaft in helis), and indeed this happens with all my vehicles.

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
