### ISSUE TITLE
Car with Manual engine being internal skip shifting or do shift two time randomly 

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1169]
Car with Manual engine being internal skip shifting or do shift two time randomly and it forgot what gear and what speed it was on and make car being weird on handling and speed is not correct as the gauge displayed and sometime when engine is in N gear and car still think it was in 1 or R when you throttle the car car will slide in direction that it think it was in that gear without spining the wheel and sometime when you in 1 or R but car think it still in N car wheel will spin and car move but will got stuck at its position

**Comment by DonBruce64** [comment]
Addressed in commit 25dd4154e523e2393729bbaf29c46e4ef094a2a7

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
