### ISSUE TITLE
Secondary choice for car textures 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#117]
Hi, so I thought it would be nice, in the car crafting gui, to make a 3rd line of arrow to choose the textures of models, like the 2nd arrows that actually makes you roll through every single color, make it only scroll through car models (=jsons) with another arrow that will choose the color/textures of cars, to prevent the annoying task of scrolling through every single color to reach another model.

**Comment by DonBruce64** [comment]
That's do-able.  Would require some tweaks to the GUI, but do-able for sure.
Do note that it's not really do-able for parts.  And on that note I should ask: are there gobs of parts in packs like cars, or less so?

**Comment by TheOddlySeagull** [comment]
Don bruce, for parts, use the « model name » in parts jsons to make the main and secondary segment
Like, my wheels, if they are off road wheels, race wheels, or classic wheels, only textures and json stats changes, but the « model name » is the same

**Comment by DonBruce64** [comment]
That would be a bit difficult, as the majority of parts don't use that system.  I would also have to increase the size of the GUI to accommodate that.  How many different wheels do you have anyways?

**Comment by TheOddlySeagull** [comment]
Hummm… my trin part pack has about 50 wheels, and lots more are to come xD
That makes a bit less than 20 objs

Maybe, just an idea, make the wheel system UNU, dvc and Trin uses (in the naming of our wheels we have 14t4d, (dvc only would say 14x4), t being the radius in pixels of our wheels, d being the width) make a little text menu that allows you to search the part like creative inventory would do? So players can look for specific sizes.

**Comment by DonBruce64** [comment]
Good lord man that's a lot of wheels!  The whole point of a pack system is that you *don't* have to duplicate that many wheels, not so every pack can have every possible wheel configuration.  I can do a sub-menu for cars as they make sense to have lots of variations, but 50 wheels?  Gracious...

**Comment by TheOddlySeagull** [comment]
Yeah, I have wheels for everything, going from 11*4 pix to atm 20*8, and I plan on going up to 32*10, for a specific Military vehicle I plan on making, along side adding more possibilities for Jerembla’s pack that uses my part pack xD
Btw, why not make it possible to scroll using middle key rather than clicking for every single part? x)

**Comment by DonBruce64** [comment]
Uuuh, you can scroll though the parts using the middle key.  Well, the middle scroll wheel at least.  Most mice have one of those now, and laptops have them built-in to their touchpads, so I expect that 95% or more users will have the required hardware for that operation.

**Comment by TheOddlySeagull** [comment]
When I scroll with my middle key, it doesn’t scroll through the parts, at all :x

**Comment by DonBruce64** [comment]
Middle *key*?  You're not using a scroll wheel?  Does your mouse have 3 buttons, then?

**Comment by TheOddlySeagull** [comment]
I was talking about a scroll wheel, and when I scroll it, it doesn’t change the parts in the part bench. It does nothing at all. So I need to spamm click in the borkbench if I want to build a car in survival.

**Comment by DonBruce64** [comment]
That doesn't make sense, as I'm almost sure I added that feature.  What MC version and MTS version are you using, and what bench are you using?

**Comment by TheOddlySeagull** [comment]
Sorry, it does work, idk with what I got confused :x

**Comment by DonBruce64** [comment]
Implemented in V14.3.0.
