### ISSUE TITLE
[bug] Part slots don't rotate with parts.

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1173]
Currently if you rotate a part, and the part is not installed, the part 'slot' (the green holobox that lets you place the part) does not move. 

It would be better if the part 'slot' moved, because it would make placing parts on moving systems more intutitve (think a seat in a tilt-cab, or a weapon on a tank turret).

If the defined animations reference the part in the slot (say gun_yaw), then that animation should return zero.  This should work as-is since that is what happens in the vehicle's rendering section, but it is something to consider.

**Comment by DonBruce64** [comment]
Re-classifying this as a bug, as it's the issue of the part slot not moving with the part's rotation rather than any definition being required.

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
