### ISSUE TITLE
light subpart not working propally

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#118]
ok, light related sub-part don't work properly (this is a bull bar part, and on that bull bar are 2 spots for LEDs parts, here are the 2 leds on the bull bar, and as you see, they don't work properly (they should be both on) (those 2 LEDs are 2 times the same part.)
The same issue has been noted on the UNU light bars.

https://cdn.discordapp.com/attachments/289084393442639872/569858185939255297/2019-04-22_14.06.20.png

**Comment by DonBruce64** [comment]
Noted and will try to fix.

**Comment by DonBruce64** [comment]
Fixed in V14.1.0.
