### ISSUE TITLE
ticket item and entities in seats have odd behavior.

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#1181]
Putting an entity into a seat with the ticket tool leads to weird ghosting effects of some sort. The car will move, but the entity stays behind.
![2022-04-25_22 42 37](https://user-images.githubusercontent.com/43540281/165216989-5059b15c-0aae-427e-98e0-300de94b9df9.png)
?

**Comment by DonBruce64** [comment]
Not sure when this got fixed, but been told it has.  I suspect in this commit ea2b4b59e702c1d1db7327aad4f08a743641870c

**Comment by NightScale5755** [comment]
take note it still happens, and the easiest way to reproduce is to mount a mob, say a sheep, in a seat, drive the car a bit. Then quit to main menu, and rejoin. (from Discord)

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
