### ISSUE TITLE
Add "damage box" for vehicles

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1183]
A type of hitbox that doesn't hit anything, or in fact does anything at all but recieve damage from bullets. "damage boxes" can also have a damage multiplier applied to it, that will increase the amount of damage dealt to a vehicle beyond the damage value of the bullet that hit it.

**Comment by DonBruce64** [comment]
Implemented in V21.3.0.
