### ISSUE TITLE
[Bug] Linkedvariables on subparts of a part

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1186]
![image](https://user-images.githubusercontent.com/53153740/165653208-87f803e4-ab01-485c-a481-ea00fd2a5ac1.png)
[https://discord.com/channels/232316230852280320/289084393442639872/969010123630583849](https://discord.com/channels/232316230852280320/289084393442639872/969010123630583849) this link to let you get back to the conversation

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
