### ISSUE TITLE
[Bug] Part slot rotating faster than part itself when on turret

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1187]
[https://discord.com/channels/232316230852280320/289084393442639872/969020681520025620](https://discord.com/channels/232316230852280320/289084393442639872/969020681520025620)

watch the videos to know whats going on

**Comment by DonBruce64** [comment]
Turns out this isn't completely fixed.  I'm still seeing some de-synch, but it's due to known math fuzzies, not any bad code this time.  Going to the backburner as it's not a horrid bug.

**Comment by DonBruce64** [comment]
Bug should be pretty much fixed.

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
