### ISSUE TITLE
Crash while looking through parts

### ISSUE THREAD

**Issue by TheRealDadbeard** [DonBruce64/MinecraftTransportSimulator#119]
https://paste.dimdev.org/acayulesir.mccrash

Minecraft 1.12.2
Forge 2836
Immersive Vehicles-1.12.2-13.1.0

**Comment by Nianor** [comment]
Any chance you could put the crash on pastebin instead?

**Comment by TheRealDadbeard** [comment]
https://pastebin.com/CTBNwBYK

**Comment by DonBruce64** [comment]
Very odd.  Which part bench was this you were looking through, and which content packs have you installed?  I'm wondering if one of them has a bug.

**Comment by DonBruce64** [comment]
@TheRealDadbeard Any updates?  Still suspecting a pack might be to blame here.

**Comment by TheRealDadbeard** [comment]
Yeah sorry. Think this was caused by a pack that isn't used anymore. Smooth sailing since then

**Comment by DonBruce64** [comment]
Gotcha.  Marking this issue as closed, then.
