### ISSUE TITLE
Package for set Health full

### ISSUE THREAD

**Issue by OrionGplayss** [DonBruce64/MinecraftTransportSimulator#1191]
in the vehicle mod there is a feature to repair the entire life of the vehicle based on its NBT tag
would it be possible to create something like this?
https://user-images.githubusercontent.com/104666731/166091824-42c706bb-2d2f-4951-9894-c94fb8ea9490.mp4

**Comment by DonBruce64** [comment]
Repair will stay as it is.  Generic repair items break the balance of the mod since they don't allow for consideration for the complexity and materials of the vehicle.  A wooden plane should be repairable with a few planks.  A tank needs a lotta steel and rubber and whatnot.
