### ISSUE TITLE
Incompatibility with mods that change player model

### ISSUE THREAD

**Issue by Zephyriumtdw** [DonBruce64/MinecraftTransportSimulator#1193]
Using IV with mods such as [ModularMovements](https://www.curseforge.com/minecraft/mc-mods/modularmovements/files/3594035) and [Obfuscate](https://www.curseforge.com/minecraft/mc-mods/obfuscate/files/2916310) causes various bugs, wich break these mods or game visual itself

Left side - only Obfuscate, Right side -Obfuscate and IV(With Official Pack)
https://user-images.githubusercontent.com/95984832/166098659-7701619d-d832-4c8e-9916-bbce56ad6093.mp4

Left side - only ModularMovements, Right side -ModularMovements and IV(With Official Pack)
https://user-images.githubusercontent.com/95984832/166098809-be66b7b0-4c2f-4acf-981a-442b299e9fae.mp4

**Comment by DonBruce64** [comment]
This can be fixed by turning of playerTweaks in the IV config and rebooting.  I'm marking this ticket as invalid since a way exists to ensure compat between the mods, though it will result in some IV features not working since they require modifying the player model like those other mods do.
