### ISSUE TITLE
The car climb structures (bug)

### ISSUE THREAD

**Issue by OrionGplayss** [DonBruce64/MinecraftTransportSimulator#1196]
In any pack, take a vehicle, get close to a tree from the front, then accelerate forcing contact with the tree, your vehicle will climb it, this happens with light poles, buildings etc.

in all packs happen this

https://user-images.githubusercontent.com/104666731/166504454-a5e98b9e-b04e-48bb-86ef-aa435d84fb35.mp4

**Comment by DonBruce64** [comment]
This is not a bug with the code.  This is due to the location of the hitboxes defined in the pack, and those hitboxes not being over the wheels.  Ask the pack maker to fix this issue.
