### ISSUE TITLE
Server Crash on Start-up

### ISSUE THREAD

**Issue by LegionSkull** [DonBruce64/MinecraftTransportSimulator#1197]
Hi!
I've run into an issue that crashes my server every time I try to turn it on and the crash log states that IV is causing the problem.
Minecraft version 1.12.2, IV version 21.2.0. I have installed Hero's Aviation Pack and MTS official pack but idk if it's relevant
Here are some of the crash logs:
[crash-2022-05-08_12.49.55-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8646859/crash-2022-05-08_12.49.55-server.txt)
[crash-2022-05-08_12.35.18-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/8646860/crash-2022-05-08_12.35.18-server.txt)

**Comment by DonBruce64** [comment]
Question: If you remove exoplanets, does this crash still exist?

**Comment by LegionSkull** [comment]
> Question: If you remove exoplanets, does this crash still exist?

No, deleting Exoplanets fixed it. Weird, can I ask if you have any idea why this two are incompatible with each other?

**Comment by DonBruce64** [comment]
So, this is due to Exoplanets overriding Forge code (Probably with some ASM or Mixin or crud), and using the wrong translator class.  Forge uses a global translator, whereas Exoplantets is using a client-side only one.  I really should move the registry away from this type of fluid check though, as it won't play nice if the server is a different language than the client.

**Comment by LegionSkull** [comment]
Oh okay I think I get it, So it could be fixed in the future?

**Comment by DonBruce64** [comment]
Yes, it will be fixed in a future release.  I just need to get though the bugs that were submitted before this one before I fix this one.

**Comment by LegionSkull** [comment]
Okay, thank you! Sorry for maybe a stupid question (it's my first bug report like this), should I close the issue now?

**Comment by DonBruce64** [comment]
Nah, I always leave issues open until they are resolved and the fix is on the version on Curse.  That way other people can see them and that they are being worked on, rather than them making a new issue.  I'll close it when the fix is posted.

**Comment by LegionSkull** [comment]
Okay. Goodluck and keep up the good work!

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
