### ISSUE TITLE
Add no data item for removing hand render in camera objects

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1198]
{
	"credit": "Made by franz, I am proud don't steal model thx",
	"texture_size": [32, 32],
	"textures": {
		"0": "mts:items/items/paintgun"
	},
	"elements": [],
	"display": {}
}

put this in a json, git didn't allow me to upload the file itself

**Comment by DonBruce64** [comment]
Turns out this is a Bad Idea.  Will just use more hand events instead.
