### ISSUE TITLE
[bug] Vehicles with floating hitboxes don't level when hitting water.

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1200]
![2022-05-02_01 39 21](https://user-images.githubusercontent.com/63523852/167468041-314e21ae-de62-4056-8fb8-bb9032555b61.png)

Example here has two hitboxes up front and two at the back

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
