### ISSUE TITLE
MTS mod sound error

### ISSUE THREAD

**Issue by choonsik32** [DonBruce64/MinecraftTransportSimulator#1203]
while driving a vehicle ths message pops in the chat 
![2022-05-10_22 11 03_2](https://user-images.githubusercontent.com/104640340/167803120-86add29b-25eb-4468-8087-b4c23da41397.png)
Cant hear the vehicle's sound 
Pls fix this

**Comment by DonBruce64** [comment]
Do you have either of those mods installed?

**Comment by choonsik32** [comment]
> Do you have either of those mods installed?

Yes i have immersive railroading installed

**Comment by DonBruce64** [comment]
Then this is not an issue, as the message says what to do.
