### ISSUE TITLE
Potion effects for bullet explosions

### ISSUE THREAD

**Issue by HashimIsaPotato** [DonBruce64/MinecraftTransportSimulator#1205]
![Screenshot (20938)](https://user-images.githubusercontent.com/77245397/167969453-9f98f724-f7f4-456f-8787-bffb601c287e.png)

**Comment by DonBruce64** [comment]
Closing as I'm not likely to do this without a custom explosion code, and such code is not likely to happen, and the requester is not currently making pack content.
