### ISSUE TITLE
MFS Flight Manual word error

### ISSUE THREAD

**Issue by xXN1ckWa1k3rXx** [DonBruce64/MinecraftTransportSimulator#1206]
![XBO7C$X2TIYKRX09T2$80}R](https://user-images.githubusercontent.com/85390877/168423921-ebee804b-e8a8-4698-9671-b26652beefec.png)
![image](https://user-images.githubusercontent.com/85390877/168423937-41def894-89e8-44dc-b8ab-03d1e0c4d3a3.png)

Elecator -> elevator

**Comment by DonBruce64** [comment]
Good catch, will fix.

**Comment by DonBruce64** [comment]
Re-opening as this hasn't been released as a fix yet.  Will close when released.

**Comment by xXN1ckWa1k3rXx** [comment]
Oh. understood

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
