### ISSUE TITLE
[suggestion] Track pattern for tracks

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1207]
suggestion for adding in some way to do patterns for tracks so you can alternate between different models in a set pattern. I imagine you'd add in the name of the secondary track model and write in a ratio for how often it appears. This is not a hard need or anything just putting it here as a suggestion
![bilde](https://user-images.githubusercontent.com/63523852/168431776-47cfffbc-cd6b-4a91-970d-42a3203da00d.png)
![bilde](https://user-images.githubusercontent.com/63523852/168432089-b1cfc04f-383b-4625-8179-d826d9644015.png)

**Comment by DonBruce64** [comment]
Considering all tracks are just chunks of data, this shouldn't be that hard.  Especially if I can force using the same texture.

**Comment by DonBruce64** [comment]
Implemented in V21.3.0.
