### ISSUE TITLE
gears still shows up in some planes whenever I close them up

### ISSUE THREAD

**Issue by ItzDaOofyGuy** [DonBruce64/MinecraftTransportSimulator#1210]
Ok so I'm having a problem with the gear of the planes, so whenever I land with any random planes like the eclipse or the Comanche, once I flew away and close the gears, the gears still show up, I don't know why did this bug happen, I think the latest version of this mod which is "Immersive+Vehicles-1.12.2-21.2.0" is broken or something.
![Capture](https://user-images.githubusercontent.com/77014804/168471020-86f4c5b8-65d2-423e-b59d-d4b33098beab.PNG)
.

**Comment by DonBruce64** [comment]
This is due to internal positional changes in that version that allows for easier pack creation.  Will fix in the next OCP update.

**Comment by Colt44Magnum** [comment]
Fixed the issue

**Comment by IpGa13** [comment]
Still got the issue in latest version
![2022-12-04_11 50 33](https://user-images.githubusercontent.com/83000938/205492581-b716d086-036f-42b9-a287-0980362b20b7.png)

**Comment by DonBruce64** [comment]
Yup, because the issues was in the Official Content Pack, not the core mod.  When the pack update drops, this will be fixed.  But I do thank you for getting back to us here.  Very few people do.  They just submit the ticket and ghost.

**Comment by DonBruce64** [comment]
Fixed as of latest OCP release.
