### ISSUE TITLE
Crash when using IV Farming Fertilizer

### ISSUE THREAD

**Issue by CSX8600** [DonBruce64/MinecraftTransportSimulator#1212]
I'm starting here instead of reporting to IV Farming since the stack trace doesn't seem to be specific to IV Farming and, instead, with the `fertilizeBlock` method. Our server runs an older version of IV but I did try with the latest version and still had the same results. World crashes upon load, probably because it's trying to load that entity.

Here's the pastebin of the crash: https://pastebin.com/PaquV36C

**Comment by DonBruce64** [comment]
Dug into this, and I'm now not quite sure how it's happening.  There's no reason that the stack should be null.  Just that it should be air.  Could you join the discord so I could send you some debug builds to test this?

**Comment by Colt44Magnum** [comment]
Acquired the same crash log when I tried with MTS 21.2, https://pastebin.com/FZ0THR8R

The interesting thing was that the crash only occurred after the fertilizer effector acquired a crate to pull from.

**Comment by DonBruce64** [comment]
So not sure how I fixed this, but this got fixed with commit ea2b4b59e702c1d1db7327aad4f08a743641870c.

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
