### ISSUE TITLE
OptiFine causing Sound slot error

### ISSUE THREAD

**Issue by LavaHoleD** [DonBruce64/MinecraftTransportSimulator#1213]
Hello! Even tho it's strange, it looks like that on some hardware OptiFine is messing with sound slots, as when it's added, immersive vehicles can't find any available. We double-checked it was OptiFine and looks like so. If optimizing the modpack is a must, then VanillaFix should be used instead, as it also works even much better than OptiFine itself. Also, disclaimer when using VanillaFix: when logging in a world in the very first moment (still on some hardware) vehicle models might not load, but they will shortly after.

**Comment by DonBruce64** [comment]
So the vehicle model not loading for the first moment is actually per design.  There are some rendering overrides that run to allow large vehicles to render even outside the player's viewpoint.  These wait a few seconds after you join the world to ensure all other code has time to run.

For the Optifine issue, the best I can do it add that mod to the list of the mods in the warning text, and recommend folks use VanillaFix instead.  Optifine doesn't share their code, so I can't fathom what they might be doing with sounds that causes IV to get none.

**Comment by LavaHoleD** [comment]
> So the vehicle model not loading for the first moment is actually per design. There are some rendering overrides that run to allow large vehicles to render even outside the player's viewpoint. These wait a few seconds after you join the world to ensure all other code has time to run.
> 
> For the Optifine issue, the best I can do it add that mod to the list of the mods in the warning text, and recommend folks use VanillaFix instead. Optifine doesn't share their code, so I can't fathom what they might be doing with sounds that causes IV to get none.

About the vehicle model not loading for the very first moment, well, it has kind of changed now. It just started to not load immersive vehicles models at all, unless you unload and load the chunk again. I removed all unsupported mods except Modular Movements. This could be fine as the server is currently private, but will be extremely unconfortable when the server will release to the public.

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
