### ISSUE TITLE
Error executing task

### ISSUE THREAD

**Issue by LavaHoleD** [DonBruce64/MinecraftTransportSimulator#1217]
Sometimes when someone reaches me with a vehicle (from a distance where the chunks are not loaded), and it loads the player with him inside driving, vanillafix says that it found an error and shows up this report.
https://pastebin.com/Adb1TE6p
No idea why this happens.

**Comment by DonBruce64** [comment]
Interesting.  Does it break any of the game and cause anything odd to happen besides throwing that error?  The error itself is saying that IV is having issues while removing a rider from a vehicle, though no clue why it's removing him as he's clearly driving the vehicle.

Also, is this on your client, his client, the server, or a combination of the three?

**Comment by LavaHoleD** [comment]
> Interesting. Does it break any of the game and cause anything odd to happen besides throwing that error? The error itself is saying that IV is having issues while removing a rider from a vehicle, though no clue why it's removing him as he's clearly driving the vehicle.
> 
> Also, is this on your client, his client, the server, or a combination of the three?

Looks like it's just throwing an error, perhaps it's nothing relevant. Vanillafix says that errors like this have a chance of corrupting the world and such, but it just might be the general advice it says.

**Comment by DonBruce64** [comment]
Could you join the Discord and try the latest beta?  We made some changes with the entity loading logic that might have fixed this.  If you're already there, just ping me.  I don't see anyone with your username in there.

**Comment by DonBruce64** [comment]
Closing due to no user response in over a month.
