### ISSUE TITLE
Rendering issue with Tails mod

### ISSUE THREAD

**Issue by Xavienth** [DonBruce64/MinecraftTransportSimulator#1220]
In Immersive Vehicles versions 21.0.0 and above, Immersive Vehicles causes a bug with the Tails mod. Only tested with Tails version 1.10.0. Ears and snouts are unable to follow the orientation of the head, instead only following the body. As such, if the player turns their head only slightly or looks up and down, the ears and snout remain still.
This issue even occurs when the two mods are installed together and nothing else, and only with Immersive Vehicles versions 21.0.0+

**Comment by DonBruce64** [comment]
Does this still happen if you turn off playerTweaks and reboot?

**Comment by Xavienth** [comment]
Immediately fixed the issue without a reboot.

**Comment by DonBruce64** [comment]
Noted.  I'll see if I can auto-detect the mod and disable PTs with it installed.  Will leave that as this action to close this ticket.

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
