### ISSUE TITLE
[Suggestion] swap out isFront/RearWheelDrive booleans

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1221]
Replace the old system with a boolean on the part slot instead 

"isDrive": True/False

For instance.
Nothing super nessecary for now but I think it'd be useful overall

**Comment by DonBruce64** [comment]
Could you elaborate?

**Comment by DonBruce64** [comment]
Implemented in V22.0.0
