### ISSUE TITLE
Request to make input values such as rudder affectable via variableModifiers

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1222]
![image](https://user-images.githubusercontent.com/53153740/171545889-e6cb3934-8a7c-4fc6-ac73-e4ac2ec902f2.png)

**Comment by DrprofLuigi** [comment]
This completely breaks my suspension systems, `rudder` can no longer be used as an input value, possibly among other things. The best part is that this kind of feature could be handled with VMs. If you doubt me, let's make a deal :sans:

**Comment by DonBruce64** [comment]
Implemented in V21.3.0.
