### ISSUE TITLE
[Incompatibility] GregTech

### ISSUE THREAD

**Issue by Chocodu31** [DonBruce64/MinecraftTransportSimulator#1225]
I know that is not your problem, just for notice : GregTech is incompatible with MTS (at least gregtech 2.1.4-beta) in default option.

Bugs :
![2022-06-12_12 52 41](https://user-images.githubusercontent.com/54859478/173239881-68ba0fae-07ca-48a6-afd5-d390e3846dfd.png)

There is some black square around the particle.
You can fix it in _"Client Options"_, _"Shader Options"_, just turn _"Emissive Textures Bloom"_ to **False**

![greg0](https://user-images.githubusercontent.com/54859478/173240157-b7cabe3a-4569-4172-8160-0700661a62b1.PNG)
![greg1](https://user-images.githubusercontent.com/54859478/173239965-1e1fbc9f-04c2-4245-b627-d4c1c75a1a32.PNG)
![greg2](https://user-images.githubusercontent.com/54859478/173239983-c3167641-dd2b-4b81-9a8b-95496064f3e0.PNG)

And there is another bug, a sound bug :
`[Client thread/INFO]: [CHAT] IMMERSIVE VEHICLES ERROR: Tried to play a sound, but was told no sound slots were available.  Some mod is taking up all the slots.  Probabaly Immersive Railroading or Dynamic Surroundings.  If you have those installed, complain to the mod author or check the mod configs.  Sound will not play.`

I think that can be fix in _"Client Options"_ and the section _"MaxNumSounds"_, but i don't know what values i need to put in, so if somebody can help me.
![greg0](https://user-images.githubusercontent.com/54859478/173240232-600cf4c3-94b4-4d0f-8586-94286fa723a0.PNG)
![greg3](https://user-images.githubusercontent.com/54859478/173240238-d4e215c6-4bfe-4754-8ad5-ff565a68ff6a.PNG)

Thanks.

**Comment by Chocodu31** [comment]
Update : If u put 28 (the lowest number according to gregtech) that work.

Do you think is possible to put more ? (cause the mod say that would have some bug with some machine)

**Comment by DonBruce64** [comment]
Beats me.  That's GregTech's config box, not IV's.  From what it looks like, that's a config that takes sounds away from the main system for GregTech's exclusive use.  They shouldn't be doing that.  That's what Immersive Railroading does by default, and it leads to the same issue with IV.  They should be sharing the sound pool and releasing the sound handles when they aren't using them, not requesting 512 of them and then not letting other mods use them if they're only using 20.

**Comment by DonBruce64** [comment]
Flagging this as an issue with GregTech's code.  I'll note them as another mod in the list of mods that hog sound slots during the next update.

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
