### ISSUE TITLE
Treads don't animate properly

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1226]
Going from 21.1.0 to 21.3.0 the treads go from mostly fine to this.

Also, rollers no longer automatically animate, so what is the proper speed to set them at? i.e. what would the diameter of t he wheel be with a ground_rotation of value 1?

![2022-06-12_12 40 00](https://user-images.githubusercontent.com/36775575/173250446-388f8f12-cdac-4c48-95c2-23a1d0403cc2.png)

**Comment by DonBruce64** [comment]
Question 1: Can you try the latest beta and let me know if this still happens.
Question 2: Do you have any animations defined on those rollers?  If so, they won't auto-animate since the code doesn't want to clobber rollers that are manually animated and won't apply auto-animation LCs to them.

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
