### ISSUE TITLE
Helicopters push themselves through the ground

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1227]
When landing, helicopters don't sit on the ground properly, and push themselves in the ground when the throttle lets the heli drift down.

https://user-images.githubusercontent.com/36775575/174386704-bae167a9-59ad-4b50-a607-2f0050d48614.mp4

https://user-images.githubusercontent.com/36775575/174386674-b76ce70d-6b0a-48b1-840c-222a7609a16f.mp4

**Comment by DonBruce64** [comment]
Do those skids have "suspension" on them?  The blue wheel boxes look like they're moving...  Also, what's the pitch of that rotor?

**Comment by DonBruce64** [comment]
Closing as this is more related to #1339 than bad ground physics.  The rotor is not happy, that needs to get fixed, not the skids.
