### ISSUE TITLE
[Request] Make LightLevel on decor capable of being modified, for things like lamps that can be turned on and off

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1228]
like it says on the tin. the most likely way to do this is using variableModifiers, and i think that if that works on decors, it will work fine. just, a simple way to make it so that if you have a decor with a specialized lightObject, make it so the lightLevel variable can be modified to do what the lightObjects do, such as being turned off when the decor is clicked, or if the decor has to be powered by redstone to turn on, etc

**Comment by DonBruce64** [comment]
Tin instructions un-clear, modified light level according to proximity of player.  Other ideas welcome.

**Comment by DonBruce64** [comment]
Implemented in V21.3.0.
