### ISSUE TITLE
Implement olive/military Bell47g variant > OCP

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1231]
Resources for the olive Bell (external tank, main texture, skids, crate, rotor)
There are two different military variant main rotor textures, implement the one you like more (or both ;) )
I've included pictures to make the decision easier.

[Olive-Bell47g.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9035643/Olive-Bell47g.zip)

Hope you're doing better by the way, im glad you're active on Discord again :)

**Comment by DonBruce64** [comment]
Completed via PR.
