### ISSUE TITLE
What is the general ID (if any) of the vehicles in the mod?

### ISSUE THREAD

**Issue by Bomboy09** [DonBruce64/MinecraftTransportSimulator#1232]
I don't know if this is where I am supposed to ask this, but it would help for a different mod I have for config.

**Comment by boot2big** [comment]
mts:[packid].[item]

mts:trin_tcp_v3.trin_formula

**Comment by Bomboy09** [comment]
thank you but is there a single id for all the cars?

**Comment by DonBruce64** [comment]
Uuuh no?  Each car has its own ID as they are unique and the mod needs to know the difference between them.

**Comment by Bomboy09** [comment]
ok thank you
