### ISSUE TITLE
Modifiable gravity value on vehicle json

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1233]
since it very annoying to see car get fly off on very small slope
and on curve slope road that you need to turn it will make car wheel not touch ground and unable to turn
same as use it as downforce simulation cause down force should push car to ground
and why not in config? 
1. user dont have to mess with config file
2. if i ask users to modify gravity value in config it will also modify other pack gravity value same as aircraft

**Comment by DonBruce64** [comment]
Should this be a gravity multiplier like the config is?  And should it affect all vehicles (cars/planes/boats), or just not-planes?

**Comment by DonBruce64** [comment]
Outsourcing with 1-month timeline from last comment.

**Comment by DonBruce64** [comment]
Time is up.  No clear path and no people wanting to PR.
