### ISSUE TITLE
iv 21.3.0 beta 2 causes servers to pitch a random error and then hard crash out

### ISSUE THREAD

**Issue by BloodMoonAbyss** [DonBruce64/MinecraftTransportSimulator#1234]
as it says on the tin will get a crash report for you so you can see what exact thing it is
[crash-2022-06-25_08.14.22-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9027230/crash-2022-06-25_08.14.22-server.txt)
[crash-2022-06-25_08.15.21-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9027231/crash-2022-06-25_08.15.21-server.txt)

**Comment by DonBruce64** [comment]
Related to #1197, as both stem from some mod using different translators on boot.
