### ISSUE TITLE
[suggestion] Automated Crafting

### ISSUE THREAD

**Issue by Colt44Magnum** [DonBruce64/MinecraftTransportSimulator#1237]
### **Preamble**
With the advent of linking parts I think that the inclusion of autocrafting from linked parts is a great step forward. Currently you can place a crafting table on a vehicle, but having the capability for the crafting bench to automatically pull items into it and make the finished item would bring this function to the next level. This would also work for allowing furnaces to pull from an interactive crate part. 

### **Examples**
Some of these things I don't think have an irl equivalent but could have very Minecraft esk playability.  
For irl agricultural production this would be useful for bailers that would pick up stalks "autocraft" bales and then place them out (however the placing of a block out of a vehicle would be a whole nother function not necessarily needed.  It could just output into another inventory).  
![image](https://user-images.githubusercontent.com/51977107/177048308-92d6ce69-61d8-49f4-a8a5-b3d5d63b5d68.png)

For industrial equipment this could be turning stone/cobble into gravel as it crushes through a mountain or is brought those materials.
![image](https://user-images.githubusercontent.com/51977107/177048389-de301efc-024a-470a-bb77-dce282158b3f.png)

For lumber equipment the capability to turn logs into planks at a better ratio than standard minecraft would also be fun and allow for portable saw mills. 
![image](https://user-images.githubusercontent.com/51977107/177048283-fd0638ea-7e0a-489a-8767-363c0ae43fc9.png)

### **Towards the Future**
Immersive Vehicles can help make the mining in Minecraft that much easier and even more fun with this kind of enhancement no doubt. Currently the mod is a **fun way to get around a world**, now it can be made into a **fun way to change the world**!

**Comment by Colt44Magnum** [comment]
"crafting": [
	{
      "itemTypes": [],
      "partTypes": [],
	},
	{
	  "items": [minecraft:hay_block]
	  "materialList": [randallag:wheat_chaff:0:5]
	},
	{
	  "items": [minecraft:hay_block]
	  "materialList": [minecraft:wheat:0:6]
	}
    ] 
    
    So currently this is what my brain can think of for a json code section. Essentially all the original crafting definitons would be used, though in this case if a specific item is wanted to be crafted in the part it needs a materialList to accompany it. linkedParts would be used in the part slot on the vehicle to link an interactable_crate to the crafting part and then to another interactable_crate for it to dispense the items its making into. When there is not enough storage I would suggest the items would just dump onto the ground (though on lower end pc's that might cause lag), another solution would be that the crafting would just stop. This would require the crafting_item to know how full an interactable_crate is though. Currently if an effector breaks blocks and the player is too far away the blocks all end up on the ground, so dropping the items in my own opinion isn't that bad. The GUI for benches would be used when the collision area of the part is right clicked, allowing the player to choose what is being made. In the above case the same item is being made but with different recipes.

**Comment by DonBruce64** [comment]
Closing this due to the ticket owner taking a break from pack-making in the foreseeable future.  Will re-open when they return, or when another pack comes up with a valid solution for implementing such a system.
