### ISSUE TITLE
CAN YOU PLEASE MAKE IT AVAILABLE FOR 1.18.2. PLEASE

### ISSUE THREAD

**Issue by Dylanalyd1234321** [DonBruce64/MinecraftTransportSimulator#1239]
please. I really love vehicles and struggle to find any other good ones but this. I can't play it though because its not 1.18.2

**Comment by DonBruce64** [comment]
This isn't an issue, this is a request.  Clearly, you can find the links to the GitHub, but not read the Curse page.  Closing ticket and blocking you from creating more.
