### ISSUE TITLE
Request: Magneto rotation variable

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#124]
Could have a bunch of variants (e.g. "magneto_1"-"magneto_8" to cover the maximum number of engines currently possible) for multi-engine craft.

**Comment by DonBruce64** [comment]
If it's in that format, I can just make it dynamic based on the number for any number.  Though I doubt we're going to magneto_25 levels...

**Comment by DonBruce64** [comment]
Implemented in V14.1.0.
