### ISSUE TITLE
SUGGESTION: DIM-Blacklists for engines.

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#1241]
Carried over from Discord:
Literally just a config entry for a dimension blacklist/whitelist, for greater control over what dimensions each engine type would function in.
Particularly useful for cases like Galacticraft, cuz most engines no worky in space.
Or even the Aether, cuz cars might be useless.

**Comment by DonBruce64** [comment]
Implemented in V21.3.0.
