### ISSUE TITLE
Beacons only update after joining world

### ISSUE THREAD

**Issue by KongstonCodes** [DonBruce64/MinecraftTransportSimulator#1242]
1.12.2
Immersive Vehicles V21.2.0
Content Packs:
IV_Trin_Civil_Pack_V3.17.0.jar
IV_Trin_Part_Pack_2.19.1.jar
Golden Airport Pack [IV] 3.2.6.jar
Helicopter_Pack-2.7.0.jar
MTS_Official_Pack_V23.jar
UNU Civilian Pack [MTS] 1.12.2-21.1.0-5.3.0.jar
UNU Parts Pack [MTS] 1.12.2-21.1.0-5.1.2.jar
Miszko's Polish Trackside Decor Pack 0.4.jar

How to replicate:
Place a beacon and name it
try to see it in a plane
rejoin the world
do step 2 again

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
