### ISSUE TITLE
Scroll bar for oversized cargo

### ISSUE THREAD

**Issue by DrKevin111** [DonBruce64/MinecraftTransportSimulator#1245]
Bug:
Scroll bar moves horizontally instead of vertically for oversized cargo

Version:
Minecraft Version 1.12.2
Immersive Vehicles 1.12.2-21.2.0

Afflicted Packs:
2 instances documented 
+ UNU Parts Pack [MTS]
  - File Name: UNU Parts Pack [MTS] 1.12.2-21.1.0-5.1.2
  - Can be found on:
    - UNU Cargo Container (BlackThorne), UNU Cargo Container (Blue), UNU Cargo Container (Green), UNU Cargo Container (UNU)
        [mts:unuparts.unuparts_parts_unu_container_color]
      + Placeable on Types:interactable_container_single.
      + Vehicle/Trailers that can equip:
        - UNU Container Trailer (Double)
            [mts:unuparts.unuparts_trailer_unu_container_double]
        - UNU Container Trailer (Single)
            [mts:unuparts.unuparts_trailer_unu_container_single]
        - [From UNU Civilian Pack] UNU Camel Container Hauler (Any Color)
            [mts:unucivil_vehicle_unu_camel_container_(Color)]
      + Notes
        - Inventory Size: 432

+ [Immersive Vehicles] IAV Parts pack
  - File Name: IAV_Parts_Pack_Beta_13.jar
  - Can be found on:
    - Trailer Mounted Bulk transport Hopper Gray, Trailer Mounted Bulk transport Hopper Smell, Trailer Mounted Bulk transport Hopper Yellow
        [mts:iav.iav_tank_grain_(color)]
      + Placeable on Types:generic_containermount_2.5_10.
      + Vehicle/Trailers that can equip:
        - Trailer Frame
            [mts:iav.iav_trailer]
      + Notes
        - Inventory Size: 990

Current Packs:
+ [Immersive Vehicles] IAV Parts Pack
    [IAV_Parts_Pack_Beta_13.jar]
+ [Immersive Vehicles/IV/MTS] VEB Automobilwerke Schwikau Military/Civilian
    [Automobilwerke_Schwikau_VEB-1971_february_beta_1.jar]
+ [MTS/IV] immersive Poker's Garage
    [immersive_Pokers_Garage_1.1.jar]
+ Blu's Sign Pack [MTS/IV]
    [Blus_Sign_Pack_V1.2.0.jar]
+ Golden Airport Pack (GAP) [Immersive Vehicles content pack]
    [Golden Airport Pack [IV] 3.2.6.jar]
+ Hero Aviation Helicopter Pack [IV/MTS content pack]
    [Helicopter_Pack-2.7.0.jar]
+ Immersive Vehicles (MTS/IV) - Official Content Pack
    [MTS_Official_Pack_V23.jar]
+ Immersive Vehicles Trin Civil Pack V2
    [IV_Trin_Civil_Pack_V2.6.1.jar]
+ Immersive Vehicles Trin Civil Pack V3
    [IV_Trin_Civil_Pack_V3.18.0.jar]
+ Immersive Vehicles Trin Part Pack
    [IV_Trin_Part_Pack_2.20.0.jar]
+ Kadwin Jurassic Park Vehicles Pack [MTS/IV]
    [MTS_Kadwin_JP_Vehicles_Pack_3.2.jar]
+ Potato Vehicle Industries
    [Potato-vehicle-Industries-BETA2.jar]
+ UNU Civilian Vehicles [MTS/IV] [IR] (immersive cars trucks planes & trains)
    [UNU Civilian Pack [MTS] 1.12.2-21.1.0-5.3.0.jar]
+ UNU Parts Pack [MTS]
    [UNU Parts Pack [MTS] 1.12.2-21.1.0-5.1.2.jar]

![unknown](https://user-images.githubusercontent.com/108896694/177848273-0b4075fb-e62a-4187-9bde-0b483c65dfde.png)

**Comment by DonBruce64** [comment]
Fixed in V21.3.0.
