### ISSUE TITLE
[enhancement] Indirect fire weaponry

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1248]
So my idea was this; isIndirectFire : adds a button and three text fields in the panel. Button changes from player line of sight aim to coordinate aim. The player can input coordinates x y and z to these three text fields (one per axis) and the gun will aim automatically to hit that coordinate at the best of its ability based on how fast the bullet drops, muzzle velocity, rocket/not rocket, etc. The chunks the bullets lands on are loaded when the weapon is aimed, or optionally the bullet itself is a chunk loader

**Comment by DonBruce64** [comment]
No chunkloading of bullets.  They'll go where they go, and you'd better hope the chunk is loaded.  Chunkloaders are nasty, lag-causing things, especially if they are for bullets that fly super fast.

However, I WILL allow for bullets to travel and hit chunks far away that are loaded, say for long-distance engagements between bases.  But that will require significant code changes to the bullets.

**Comment by DonBruce64** [comment]
Implemented in V21.3.0.
