### ISSUE TITLE
[Enhancement] Animation Variable for Benches/Interactables

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1249]
allows animations to play when interactable is being interacted with, allowing animations akin to chests in vanilla minecraft, as an example

**Comment by DonBruce64** [comment]
This is now on a 1-month timeline.  Either present me with a model in that timeline that I can test with, or this ticket gets closed.

**Comment by DonBruce64** [comment]
Added in 22.3.0.
