### ISSUE TITLE
Third person view stops working after using scope

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1253]
https://user-images.githubusercontent.com/46074580/178323192-a9505502-132c-4a96-a13e-370cfcbf4750.mp4

**Comment by Wartich** [comment]
also, hand stops rendering

**Comment by DonBruce64** [comment]
Closing as it's technically a beta bug, and I'd rather not track these.  But, it should also be fixed as of the latest beta.
