### ISSUE TITLE
[Bug] reversed torque on vehicle from single jet engine on

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1256]
left jet engine puts vehicle into left hand turn, and right jet engine puts vehicle into right hand turn. discussed over discord, this is backwards. left engine only should put plane into right hand turn, and vise versa

**Comment by DonBruce64** [comment]
Un-closing, since this bug is in the latest release version and others may have it.  I don't want to close bugs that are in release versions since it can lead to folks making another ticket for the same bug because it isn't currently ticketed.

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
