### ISSUE TITLE
JourneyMap Waypoints and Minimap Bugged

### ISSUE THREAD

**Issue by Doublehelix13** [DonBruce64/MinecraftTransportSimulator#1258]
![Screen Shot 2022-07-17 at 4 34 38 AM](https://user-images.githubusercontent.com/40927088/179426827-d54115b3-98a6-4f18-855b-cb5fa056c0ad.png)
![Screen Shot 2022-07-17 at 4 33 14 AM](https://user-images.githubusercontent.com/40927088/179426829-85f6c0ca-16cd-4db8-b14e-1691314ddf0d.png)

When sitting in a vehicle, the names and distances of waypoints are not visible.  Also, the player icon on the minimap is rotated -90 degrees, so if I'm facing west, the map shows me facing south.  This problem is not present in version 20.6.2 but it is present in 21.0.0, 21.1.0, 21.2.0, and in the latest release, 21.3.0.

**Comment by DonBruce64** [comment]
Fixed in V21.1.0.
