### ISSUE TITLE
Custom Bench not working properly

### ISSUE THREAD

**Issue by IDNSIIDNSI** [DonBruce64/MinecraftTransportSimulator#1259]
Machine tools doesn't see wood in inventory and can't craft items that require these plankwoods

**Comment by DonBruce64** [comment]
Which wood, which IV version, which pack version?

**Comment by IDNSIIDNSI** [comment]
![image](https://user-images.githubusercontent.com/109505841/179784165-bf089e41-3ea1-467f-829f-7becf8bef632.png)
Version 23 

In survival mode, some items require wood, such as "Brigadier", but if there is wood in the inventory, the workbench does not see it

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
