### ISSUE TITLE
Request: Jet engine related death messages

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#126]
With the population of jet aircrafts growing, it would be nice to have some new death messages to go with the propeller one.

“playername has been sucked into a jet engine” for approaching the front face of the engine, and “playername has been burnt by jet exhaust” for standing too near the jet engine exhaust.
For the second one, if possible, the action will only set the player on fire and the message will appear once the player is burnt down.

**Comment by fsendventd** [comment]
Only problem is that the current jet in the mod only has a 14 inch diameter intake. Nobody's getting sucked into that anytime soon...

**Comment by DonBruce64** [comment]
Well, you suck an arm into that and you'll die of blood loss...

**Comment by DonBruce64** [comment]
Implemented in V14.1.0.
