### ISSUE TITLE
Accelerational Roads - Elephant_1214

### ISSUE THREAD

**Issue by mic2139** [DonBruce64/MinecraftTransportSimulator#1261]
Accelerational roads should cause any vehicle **under a set condition such as the engine being on** to accelerate a pre determined degree per second whilst on said road, I envision this specifically for aircraft and possibly what can be done in regards to "Catapults" - a problem with my idea here is that gliders don't have an engine, but maybe they'd have a small "Electronics" one just to fufill this role if they're to be compatible

**Comment by DonBruce64** [comment]
Until I see people actually release roads in their pack, I don't wanna even consider this.  It's WAY too far in the future.  Focus for the next year should be quelling existing bugs and supporting a multi-version platform.

**Comment by boot2big** [comment]
OYE!! I've released roads!

**Comment by DonBruce64** [comment]
That *is* true....  Guess I'll have to re-open this ticket then.  Oh goody, more work for me!  That being said, I'll probably make these roads more like speed limited ones, where the vehicle will keep accelerating until it reaches the set speed on the road and then will maintain that speed.  I can see this being good for machinimas and whatnots.

**Comment by DonBruce64** [comment]
Closing again, as I can't see doing this anywhere in the near future.  This is closer to AI driving and would not really be a good use of my time to try and configure what IR already has for its stuff.
