### ISSUE TITLE
[enhancement] more functions for decoration blocks

### ISSUE THREAD

**Issue by KikoKuso** [DonBruce64/MinecraftTransportSimulator#1262]
The decorations that MTS allows you to put in right now are a bit... lacking in my opinion. They can only stay still and do nothing.

My suggestion is to add more functions to these blocks (for example chairs you can actually sit on or ovens that can work as a furnace).

**Comment by DonBruce64** [comment]
The sittable chairs are something that I would need to code in.  But the furnace blocks are already possible.  You'll need to bug the pack authors for those.

**Comment by DonBruce64** [comment]
Implemented in V22.2.0.
