### ISSUE TITLE
[bug] On latest beta, wheels as subparts break

### ISSUE THREAD

**Issue by razeruu** [DonBruce64/MinecraftTransportSimulator#1263]
On the "Immersive_Vehicles-1.12.2-21.4L.0-BETA2.jar", if you have parts that have subparts at wheels, the vehicle sinks. For example, my car has removable axles, and the wheel slots are defined inside the axles' json as subparts, and on the specified beta build, you cannot see the green box where you're supposed to mount the wheels, but you can mount them and if you do, the car sinks in the ground as if it had no wheels

**Comment by DonBruce64** [comment]
This is a beta bug, which doesn't belong on this tracker.  Closing, but also noting.
