### ISSUE TITLE
Server constantly crashing after using UNU Laboratories Configurator

### ISSUE THREAD

**Issue by detimo03** [DonBruce64/MinecraftTransportSimulator#1269]
I wanted to set an UNU Laboratories Configurator on a UNU Laboratories Rabbit Coupé. My friend was able to join, cause he was at a different place when he logged out the last time. Crash-log attached.
Chunkfix didn't work, kill @e neither.

[crash-2022-07-28_14.09.07-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9210878/crash-2022-07-28_14.09.07-server.txt)

**Comment by DonBruce64** [comment]
Don't use that.  That's a debug thing.  You need to poke Luigi about that.  Marking as the pack's issue and leaving ticket open until solved.

**Comment by DonBruce64** [comment]
Was wrong, was my fault, is fixed in beta, will be fixed in release.

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
