### ISSUE TITLE
Engine rotation variable seems to only rotate at max engine speed. 

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#127]
As the title says. 
![Minecraft11225_4_20198_50_3](https://user-images.githubusercontent.com/44233145/57181535-e549d580-6e49-11e9-9311-2dba860f34a6.gif)

**Comment by fsendventd** [comment]
After further investigation, this seems to also apply to the driveshaft variable.

**Comment by DonBruce64** [comment]
Addressed in V14.2.0.
