### ISSUE TITLE
[ENHANCEMENT] Proper "electric" fueltype implementation

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1270]
Immersive Vehicles Vanity has had electric motors for vehicles since V1.1, and lord knows where and when GPP (the precursor to ivlabs vehicle and parts production) had it, I only have the .jar archived.

Anyways, it isnt very immersive if you have to charge an electric car using fluids, moreover the default lava (although any fluid besides Thermal's destabilized redstone just isnt realistic) and while I _could_ try to work around it by explaining it as a generator powering the motor, that's just not very practical for cheap EV cars, or civilian passenger cars in general.

Two proposed concepts:

- Implementation of direct vehicle redstone flux/forge energy support, where vehicles can have a separate battCapacity level (and if not defined, it'll be LCd to be the same as fuelCapacity) that isnt affected by the vehicle's regular 12V battery for lights and (unused) starter motors, but could presumably charge said battery up or be used to power the lights instead of the 12V battery.
- Internal electric system that uses the existing 12V system, and we consume from the vehicle battery directly instead of the fuel tanks, which would also indirectly implement the above lore workaround as you could have an actual generator motor running on a separate fuel system from the wheel motors that also charges the battery.
Additionally for the second one, electric motors would have to stop alternator-ing the vehicle battery either by automatically disabling it similarly to oil pressure, or by having a manual variable to disable battery charging on a per-engine basis.

One other possible snag with option two is that most three or four wheeled electric vehicles typically run on systems of at least 400v, and even little electric skateboards and scooters tend to use 18v or 24v. This could be fixed by having separate variables for how much battery capacity a vehicle has with "fuelBatteryCapacity" and "electricBatteryCapacity" or something of the sort, names to be improved on of course.

_...Or IVLabs is able to make sedan-moving motors that can run on a lead acid car battery, thanks to our extremely efficient motors!_ :sans:
No, seriously, uhh... 12v would be a bit low.

**Comment by boot2big** [comment]
P.S: Current electrical system just isn't ideal for realistic EV batteries in general as voltage works as the current amount of power in the system rather than the rate it's moving at and blablabla, but it can be made to work

**Comment by DonBruce64** [comment]
Yeah, I know it's not ideal.  The proper way is to link with RF systems, but that's gonna take quite a while to do since I'm in the thick of other bugs and overhauls to prep for version updates.  But, I know it's something folks will want, especially for vehicles in space, so I'll just consider the engines as "isElectricPowered" as the companion to the "isSteamPowered" ticket.  Don't hold your breath for this one though.

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/183517322-fd908d8b-3b2c-419f-87d3-3f0ce13acf56.png)
Another idea is powering vehicles using redstone dust, see pic related

**Comment by DonBruce64** [comment]
That could be done, but TBH having them work with an existing RF grid is probably the better option of the two, since it allows working with IE, which _doesn't_ allow their electricity to be converted to a solid item form.

**Comment by DonBruce64** [comment]
Will do this once Cactus or someone makes an electric vehicle charger block.  Should match core mod fuel pump, which ain't saying much TBH.

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/189765947-639d4363-c417-4908-a1ee-46edbf9c918c.png)
![image](https://user-images.githubusercontent.com/53581325/189765961-95c66479-e2e7-47ea-8739-6de9a84e7c2d.png)
How's this?

**Comment by DonBruce64** [comment]
That'll do.  Post it here as an OBJ with an item icon and JSON to make it a fuel pump, and I'll turn it into a charger block to work with electrics sometime in the future once versions are updated.

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/189815205-4340d221-1ca3-438e-8e25-6ffc83f95077.png)
![image](https://user-images.githubusercontent.com/53581325/189815218-5dfcc140-1777-4b73-96a0-6932bd11f0cb.png)

Charger block MkII. Now with hover mode and missile countermeasures! (Because R* say faka you.)

**Comment by DonBruce64** [comment]
Implemented in V22.2.0.
