### ISSUE TITLE
[ENHANCEMENT] Pre-defined fuel for rocket engines.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1271]
IVV currently has a rocket thruster which *should* run on its own internal tank rather than relying on the vehicle, because you can't have "avgas" and "diesel" in the same car unless your modpack admin either keeps lava as a universal fuel, or you use a gasoline/avgas engine alongside the avgas rocket thruster... or you put the rocket on its own fuel system where it isn't fuelable with regular pumps, but can still be filled up using jerrycans.

Fuel gauges probably aren't particularly important since the limited usecase count of engines with their own internal fuel tanks don't really justify all the sort of jank that would come from it, so either an engine_fuel variable that defaults to current vehicle fuel when no tank is defined, or a numbered case similar to engine_rpm_# would do, or we can leave out fuel variables entirely.
It's your responsibility to make sure your rockets are all filled up before takeoff anyways!

**Comment by DonBruce64** [comment]
So, I'm wondering if this would be easier with engines that contain their own fuel rather than multiple tanks.  That is going to be quite difficult for me to implement with the current code.  If you wanted to re-use the rocket, then you can just use a "repair" recipe.  Thoughts?

**Comment by boot2big** [comment]
Sounds good, a rocket would likely need repairs and maintenance after running itself empty anyways. As long as it isn't drawing from the main vehicle at least, so that other engine fueltypes are useable

**Comment by DonBruce64** [comment]
I wouldn't have it use fuel as much as it would run at 100% throttle for the allotted time when the magneto is triggered.  The idea being that rocket boosters are uncontrolled burns once ignited and they are single-use.  This also prevents the need to make ones own fuel for the rocket, and deal with modpack folks mucking up the configs and breaking said rockets.  Cause you know most MC users can't handle rocket science.

**Comment by boot2big** [comment]
Fair nuff, less json work on my end for good sounds anyways then. Get rid of everything except for the cranking sound for lighting it and the full throttle whoooosh sound, baboom baby. Sounds better!

**Comment by DonBruce64** [comment]
Implemented in V22.0.0
