### ISSUE TITLE
[ENHANCEMENT] Multiple recipes per json/item/etc

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1273]
On the tin, would allow for conversion between different states of a material (ingots between blocks) as well as slightly different manufacturing processes for the same item (you may have one simpler recipe that takes more of a material, or a refined recipe that requires more work but returns the same product for less material) 

_Not_ related to allowed/blocked mod ids as those only switch between different json folders to load into the game while still having one recipe per json

**Comment by boot2big** [comment]
Crafting quantities would also fit nicely here, so that a Nuts item from the OCP could be crafted from two sticks, or nine Nuts items could be made from a Nuts Block (example)

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/183229891-b97c5711-272e-4b28-a1f4-5143dd206120.png)
Example of a needed usecase, a long planned paperclips material

I also plan on finally adding a TC alloy block, though I might rename the terrillium carbonic alloy to something more creative

**Comment by DonBruce64** [comment]
This would fit nicely with the version updates, which will require changes to all recipies since item names changed in higher MC versions.  This'll be a hair icky for extraMaterials.  And how would one handle the GUI displaying these multiple recipes?

**Comment by boot2big** [comment]
Either a sort of loopy arrow button to show multiple recipes, or cycle through available ones in the bench (as well as multiple JEI entries)

**Comment by DonBruce64** [comment]
I think the button is better, since there's less confusion.  Will bug @Ooferine for a GUI update.

**Comment by DonBruce64** [comment]
Implemented in V21.1.0.
