### ISSUE TITLE
[ENHANCEMENT] Animatable .json items? (Well, not really)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1274]
Visibility animations or some other method of switching between .json models for items based on animation variables (clicked/activated, time/tick, etc)

**Comment by DonBruce64** [comment]
Not possible.  JSON item animation and rendering is wholly handled by MC.  I can't do anything about anything there.  The only hope is to make the item a gun and use that animation system.
