### ISSUE TITLE
Scaling of vehicles in the config causing misaligned parts

### ISSUE THREAD

**Issue by NicodemusN** [DonBruce64/MinecraftTransportSimulator#1276]
I noticed this problem only with UNU vehicles, but Dr_prof_luigi told me to ticket it to the core mod since it appears to be a core mod issue. So, when scaling vehicles in the config their parts get misaligned. Wheels move weirdly and switching a UNU vehicle to right hand drive causes the seats get misaligned.

Using latest UNU mods and IV (and no, optifine is not cause, I tested!)
Immersive Vehicles-1.12.2-21.3.0
UNU Civilian Pack [MTS] 1.12.2-21.3.0-5.3.2
UNU Military Pack [MTS] 1.12.2-21.3.0-5.0.0
UNU Parts Pack [MTS] 1.12.2-21.3.0-5.1.4

![ticket2](https://user-images.githubusercontent.com/87670335/182384023-5260a5d2-f2b9-486f-9ef2-055594f4c548.png)
![ticket](https://user-images.githubusercontent.com/87670335/182384031-887e8c07-bf6e-4d1b-ab45-acb438d43a37.png)

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
