### ISSUE TITLE
[BUG] Guns don't reload if they can fit ammo, they only reload when empty.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1277]
For shotguns, missiles or the like where you're physically loading in a single ammo item at a time without doing it every time the gun runs out of ammo, because you only loaded in one shot.

Basically:
Undefined/False: Current load system, keep firing and wait to reload until the gun is at 0 ammo or the user manually reloads
True: Old load system where the gun would reload the first chance it gets, but less buggily so we don't load more ammo into the gun than it should hold.

Another possible solution to both this and a bug that you _may_ have already patched, though I haven't tested for it recently, would be to just check if current ammo count > max ammo count, and if so then set the ammo to max ammo count minus one (or minus none, since you could theoretically have a fully loaded mag/clip along with a chambered round)

**Comment by DonBruce64** [comment]
I'm confused what you want here?  As to guns, they reload whenever they have enough ammo slots to take an ammo.  So a 6-shooter will fill up with a bullet if you fire one bullet, or if you fire all 6.  It'll just take a while to fill up the shooter because you have a slow reload time.  Or you can have pre-loaded cartriges like IE, and it'll load all 6.

**Comment by boot2big** [comment]
In my experience guns have _not_ been working that way though.

Say I have two shotguns, a double barrel and a street sweeper, at least in creative mode the street sweeper only loads itself with one ammo item similarly to the DB shotty (Shotgun slug item is equivalent to two ammo bullets) meaning the streetsweeper essentially only seems to hold as much ammo as the DB.

I may need to test more in survival mode, but if this is too complex of a ticket I won't be heartbroken if it gets backburnered or wontdo'ed

**Comment by DonBruce64** [comment]
Since guns should always take ammo if they can fit it, this ticket is actually a bug, not an enhancement.  If you could confirm and give me a gun to test with, it would be appreciated.

**Comment by boot2big** [comment]
Sure, will build a jar real quick and DM it to you ASAP

**Comment by boot2big** [comment]
Survival devmode test, it seems part of the issue _could_ be related to devmode infinite ammo, or else guns just aren't consuming ammo at all.
Reloading game with devmode disabled
https://user-images.githubusercontent.com/53581325/183258006-4351d077-a25d-4dc6-b9d7-3fb50b67516f.mp4

**Comment by boot2big** [comment]
Unrelated to devmode ammo consumption, gun still won't load past two rounds (one item)
https://user-images.githubusercontent.com/53581325/183258090-c577148b-ba8c-4238-bc73-90183429a9b6.mp4

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
