### ISSUE TITLE
[ENHANCEMENT] Birdshot/Spray/Pellet ammo that shoots multiple of itself per single shot

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1278]
Random trajectories that differ from eachother so that a gun with a proper bulletSpreadFactor set will have each "bullet" (pellet) fire at a different angle, and amount of pellets can be set (with 0 being LCd to one, for a single bullet, or possibly the variable being an additive thing meaning 0 adds 0 bullets, 4 gives a total of five shots per round, etc)

**Comment by DonBruce64** [comment]
BSF is for the firing from the gun, not for actual spread.  What you're looking for is some system to fire off multiple bullets per shot.  Granted, a shotgun will probably use the BSF for each of those pellets, but there has to be a "count" of some sort to tell the gun to spawn all those bullets in the first place.  So for sure add that variable and LC it to 1, but no need to poke BSF.

**Comment by ktokto313** [comment]
I got a working beta for this on the-open-road, Laura and I both performed individual test on the pack and have seen no bug or error, I am currently putting a pull request for that.

**Comment by DonBruce64** [comment]
Implemented in V22.0.0
