### ISSUE TITLE
How to completely remove the dead zone from the gaming wheel?

### ISSUE THREAD

**Issue by Rostislave-42** [DonBruce64/MinecraftTransportSimulator#1279]
After one of the updates, the cars had a large dead zone, which makes it difficult to accurately control. I can't remember a version where everything worked the way it should. Even if you set a zero dead zone in the mod settings, it still be present as originally set.

**Comment by DonBruce64** [comment]
Does the dead zone not get saved in the config?  Or does it just not get used?  Because I haven't noticed this being an issue.

**Comment by Rostislave-42** [comment]
I don't know about the config, but previous versions of the mod didn't have a deadzone before tweaking settings. Now, when I turn the steering wheel 10-15 degrees, the steering wheel does not turn at all in the game. But when I turn it 20 degrees or more, the steering wheel in the game starts to rotate with the same accuracy.

**Comment by DonBruce64** [comment]
Ah, can you use the Offical Content Pack Scout for a test?  UNU vehicles do fancy variables for their vehicles that might be affecting this.

**Comment by Rostislave-42** [comment]
> Ah, can you use the Offical Content Pack Scout for a test? UNU vehicles do fancy variables for their vehicles that might be affecting this.

Same problem. No sense when turn steering wheel 10-15 degrees.

**Comment by DonBruce64** [comment]
Odd, would you be able to join the Discord and ping me so I can send you a debug beta and get some logs?

**Comment by DonBruce64** [comment]
Closing due to no response.
