### ISSUE TITLE
Click events on parts

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#128]
So you probably know I finished my RV, and is fully debugged and working in Minecraft. But still a few things misses: we can’t sleep, cook, craft… in it, so I would suggest adding those features as new json lines for parts like:
« Click_event »: {crafting_gui/furnace_gui/sleep [x,y,z]/fuel_pump} (fuel pump click event could use fuel from barrels on the vehicle to fuel nearby like planes, cars…)
And why not add some kind of modded gui support? Don’t gui have id or something we can use as click event?

**Comment by DonBruce64** [comment]
Click events aren't the way to go with MTS as the whole point of parts is to prevent players from putting parts where they don't belong.  With click events, you'd have a generic part that could be anything, which is not good as the places you'd put a seat and a bed are not the same.  I'm more than happy to add other parts besides crates and barrels, but they're going to be actual parts, not something more generic.
