### ISSUE TITLE
[BUG] Handheld guns can ignore reloadTime if you switch items in the hotbar quickly enough

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1280]
Now all mts needs is some griefer to EWO themselves after spamming rockets up your arse...

https://user-images.githubusercontent.com/53581325/183258166-0a1a62da-3d69-4c65-9092-4ed8ac9bcc35.mp4

**Comment by boot2big** [comment]
https://user-images.githubusercontent.com/53581325/183258211-50dfeedb-acb2-4734-b1c4-2ab5ee4ec0e0.mp4

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
