### ISSUE TITLE
[Bug] Seat rotation on OCP FT-17 turret

### ISSUE THREAD

**Issue by ktokto313** [DonBruce64/MinecraftTransportSimulator#1281]
It seems like that the position of rotation was wrong.
![image](https://user-images.githubusercontent.com/57142191/183279363-12269c10-720f-4e9c-b1f6-77b7ad9b7df6.png)

**Comment by DonBruce64** [comment]
Yep, this is a known issue with the OCP.

**Comment by Colt44Magnum** [comment]
So github apparently doesn't like jsons being posted in a reply. Here is the json as a .txt that will fix this issue!

[ft17.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9481497/ft17.txt)

**Comment by Colt44Magnum** [comment]
Fixed with https://github.com/DonBruce64/MTSOfficialPack/pull/15

**Comment by DonBruce64** [comment]
Fixed as of latest OCP release.
