### ISSUE TITLE
Immersive Vehicles sound error: tried to play sound, but was told no sound slots available

### ISSUE THREAD

**Issue by AstraxVZ** [DonBruce64/MinecraftTransportSimulator#1284]
When I opened the door of a car I got this error:
`IMMERSIVE VEHICLES ERROR: Tried to play a sound, but was told no sound slots were available. Some mod is taking up all slots. If you have Immersive Engineering, set override sound channels to false in that mod's config. If running GregTech, set maxNumSounds to a lower value in that mod's config. Dynamic Surroundings and Optifine also may cause issues. Apply fixes, or complain to those mod's authors. Sounds will not play.`

I have both Optifine and Immersive Engineering with a lot of other vehicle mods.
I've searched Immersive Engineering mod options, there was no option to disable override sound channels.

**Comment by DonBruce64** [comment]
Whoops, that should say Immersive Railroading.  I need to fix that.

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
