### ISSUE TITLE
[1.12.2] Ford Tri-Motor propeller not working

### ISSUE THREAD

**Issue by gooseapple5** [DonBruce64/MinecraftTransportSimulator#129]
The Large 2 bladed propeller won't actually start, just spin. However, using the 3 bladed propeller works, and the engine start, although it isn't enough power to fly with. 

EDIT 1; Just found out it doesn't work with anything that used the Large 2 bladed propeller, such as on the PZL. I tried the latest version of the mod (14.0.0) and the same error occurred.

**Comment by DonBruce64** [comment]
This is due to the engine stalling out when you start it due to it not having enough throttle at lower speeds.  Seeing as how this is a common issue, I need to find a way to address it so it doesn't happen anymore.  Might have to add a bit of throttle to the engine when starting or something...

**Comment by gooseapple5** [comment]
Alright, thanks Mr. Bruce.

**Comment by DonBruce64** [comment]
I'm going to re-open this, as it's something I need to fix.  Will leave it open until fixed so others who have the same issue can see it.

**Comment by DonBruce64** [comment]
Addressed in V14.2.0.
