### ISSUE TITLE
An axleRatio of 0 should act like neutral

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1291]
With an axleRatio of zero is zero, the engine should be able to free rev like when the transmission gear is zero. I would suggest having a check on the final drive ratio for simplicity.

Also, negative axleRatios don't do do anything, and should result in reverse rotation.

**Comment by DonBruce64** [comment]
AxleRatio shouldn't be ever set to 0, that implies in the code there's no axle.  If one wants to adjust gear ratios for transmissions, it should be done via the engine's currentGearRatio variable.
