### ISSUE TITLE
Animation type for hydraulics and other objects fixed at two locations 

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#1292]
Discussed on Discord.

**Comment by DonBruce64** [comment]
Smells like trig that @DrprofLuigi might be able to help with.  I hate trig as much as Indy hates snakes.

**Comment by DrprofLuigi** [comment]
It's something that could be approximated (take a look at the UNU Solenodon), however more accurate animation would necessitate trig function suffixes for more variables. Though, perhaps something with VMs could be done...

VMs use translations to apply their changes. What if rotation VMs execute trig math? @DonBruce64, if you can point me to the file that handles VM math processing, I might be able to whack something together 🤔

**Comment by DonBruce64** [comment]
@DrprofLuigi You'll wanna go after the code that does variable processing in general, not the VMs.  VMs just run code though the animation system and store that result into a variable on the entity.  So https://github.com/DonBruce64/MinecraftTransportSimulator/blob/bd95182e8ecb9f43367528d0cb72925d3e0b8f5e/src/main/java/minecrafttransportsimulator/entities/components/AEntityD_Definable.java#L644

**Comment by DonBruce64** [comment]
I'm going to hold off on this personally until someone _releases_ a model that can use this.  I an't coding trig for future content.  I hate it enough for current content.

**Comment by LauraDarkez** [comment]
ping seagull. he has a bed that is already released that this could benefit

**Comment by LauraDarkez** [comment]
right now the hydraulic piston clips through the floor of the bed when lifting

**Comment by LauraDarkez** [comment]
actually, there is something it would benefit thats publically released. franz's giant artillery cannon

**Comment by Colt44Magnum** [comment]
My farming equipment use hydraulic cylinders. Almost all of them have cylinders on them somewhere but only some (just one currently) actually have animations for them...

**Comment by DonBruce64** [comment]
I'm gonna punt this ticket to @DonBruce64 for a PR, since he's working on engine and rotational animations right now.  1-month outsourcing timeline starts now.

**Comment by DonBruce64** [comment]
I think the ping above was for @DrprofLuigi and I mis-clicked.  But he's not working on these, and probably never will given our convos, so I'm going to table this for the moment.  I think it's a good idea, but I don't have the brain to do it.
