### ISSUE TITLE
[BUG?] Controller seats that are subparts of a part on a vehicle can't control the rudder.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1294]
https://user-images.githubusercontent.com/53581325/186534390-0b662f97-d0d5-422a-80ae-5016f72cba0e.mp4

Ignore the broken animations, those are (hopefully) unrelated to this bug

**Comment by DonBruce64** [comment]
Fixed in V22.0.0
