### ISSUE TITLE
MTS Insane Log Spam

### ISSUE THREAD

**Issue by JustDesoroxxx** [DonBruce64/MinecraftTransportSimulator#1296]
MTS is just insanely spamming log at game start

[Console/Log]

[Console/Log]: https://mclo.gs/oaxLSTN

**Comment by DonBruce64** [comment]
Looks like a pack with missing JSONs.  That being said, that really should only be on during devMode.  Will take as an enhancement.

**Comment by DonBruce64** [comment]
Implemented in V22.0.0
