### ISSUE TITLE
I cannot turn off the setting : "players will be given a manual on their first join"

### ISSUE THREAD

**Issue by EFWGithubMC** [DonBruce64/MinecraftTransportSimulator#1297]
I found out that the player will be automatically given 2 manuals when they joins for the first time: 
![image](https://user-images.githubusercontent.com/101224207/186827107-ed12552f-f3e5-44f7-ac3d-7f2024c35f7f.png)
Please add a way to turn off this feature. 
Also I could also get my uuid leaked to the public when I post my modpack.

**Comment by DonBruce64** [comment]
Implemented in V22.0.0

**Comment by EFWGithubMC** [comment]
Do I need to regenerate the config for this update?

**Comment by EFWGithubMC** [comment]
> Implemented in V22.0.0

Do I need to regenerate the config for this update?

**Comment by DonBruce64** [comment]
It'll show up in the config next time you boot.  Just change it there and reboot.
