### ISSUE TITLE
Cars not damaging

### ISSUE THREAD

**Issue by Workersteve** [DonBruce64/MinecraftTransportSimulator#1299]
Hello , I used tnt , bow and even "techguns mod" guns but vehicles are not damaging even 1%
This bug wasnt at 20.6.2 but in 21+ vehicles arent damaging , I wish you can help me

**Comment by Workersteve** [comment]
If you read this issue , i have some ideas for the future of this mod.
1.Engine and the battery of vehicles get older.
For example the battery max durability get less after a long time and you must use "battery changer" tool to fix vehicles battery.
Even engine get weaker and it can be overheat easier and even get lower speed. Old engines some times turn off automatic. If the engine get so old it can be stalled.

2. Temperature effect at start time and battery power (I mean for example in snow or maybe high places that the weather is cold the battery of cars work weaker and take more time to start.

I wish you like my ideas. I think immersive vehicles would be really more fun with this mods!
I really like your mods , please continue them!

**Comment by Prophet2002** [comment]
Turn on the option in mts_config.json "allowExternalDamage" to the "true"

**Comment by Workersteve** [comment]
It worked! Thanks for your help
