### ISSUE TITLE
Request: Contra-rotating Propellers

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#13]
Self-explanatory.

**Comment by DonBruce64** [comment]
This would be very hard to do with the current physics system as engines expect only one propeller for their force feedback.  Multiple propellers would throw far more physics issues into the works than are needed for such a small set of planes.  If MTS matures enough that there's nothing else to do, then I'll consider it, but for the foreseeable future, it's not going to happen.

**Comment by fsendventd** [comment]
May I note that I have put multiple propellers on an engine before.

**Comment by fsendventd** [comment]
~~also I believe that all propeller-driven tailsitters have contra-rotating props~~
