### ISSUE TITLE
Hitbox "overlapping" issues

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#130]
I have a problem, I made my RV fully modular by making a grid inside to build like if you were in a minecraft house. But I have an issue: it seems the game doesn't allow to put parts in those hitboxes, like if they were "overlapping" what isn't the case as hitboxes are like air cubes so to say.

**Comment by DrprofLuigi** [comment]
![Capture911](https://user-images.githubusercontent.com/36775575/57192329-1aa30180-6ee4-11e9-810f-163ce0f7f7f0.PNG)

**Comment by DonBruce64** [comment]
Will investigate how to accommodate this.  I've seen it become an issue with smaller custom parts.

**Comment by DonBruce64** [comment]
Addressed in V14.2.0.
