### ISSUE TITLE
[Bug/Enhancement] StreetLamp Functions

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1303]
![image](https://user-images.githubusercontent.com/53153740/187126488-7ae0d49f-5696-480f-9def-1950419f3dee.png)

* Give Streetlamps lightLevel (variable modifier option if possible please)
* make them able to be turned on and off either using a signal controller or other method

**Comment by DonBruce64** [comment]
One item per ticket is standard, this ticket will focus on the first bullet point.

**Comment by DonBruce64** [comment]
Implemented in 22.4.0.
