### ISSUE TITLE
Minecraft Crashes when aircrafts are  going too fast

### ISSUE THREAD

**Issue by UltraDlayer1** [DonBruce64/MinecraftTransportSimulator#1306]
My game legit crashes when im going im going too fast with a turbo jet airplane, and yes, I have a good GPU and etc, and I have a ultrawide monitor, so there should be no reason as to why my game is crashing. This is a bug that needs to be worked upon.   Btw, I have multiple airports in my world that are scattered throughout my world.

**Comment by DonBruce64** [comment]
Crash report or it didn't happen.

**Comment by UltraDlayer1** [comment]
It gave me a crash report after I was flying too fast, I guess it happened cause I was rendering too much chunks at a fast rate, idk, but its a bug.

**Comment by UltraDlayer1** [comment]
Look for yourself, im not lying bruh.    [Minecraft Crash](https://streamable.com/agwuj4)

**Comment by Elephant1214** [comment]
That's a video, not a crash report. Also, earlier in that video, you were over the speed (without any issues) at which your game later crashed.

**Comment by UltraDlayer1** [comment]
@Elephant1214  Listen, you dont have to believe me, but I guess the mod will never get fixed then since yall think im lying, im giving as much evidence as you need, I even provided the crash report code in the video, so I don't understand what's so fake about my issue, when I provided detail and a video, I even talked to Naxgeneral about this(He is a contributor) and he said its a issue as well.

**Comment by Elephant1214** [comment]
No one said you were lying. Don asked for a crash report, not a video that showed the exit code for half a second and ended.

**Comment by DonBruce64** [comment]
Closing due to no response from the ticket owner.
