### ISSUE TITLE
[Question] true lighting

### ISSUE THREAD

**Issue by Workersteve** [DonBruce64/MinecraftTransportSimulator#1312]
Hello again , how to active true lighting for all content packs? (For example craftspeed doesnt have true lighting)
Or it is impossible?
![2018-02-03_14](https://user-images.githubusercontent.com/112183943/187953542-753c72df-1158-4cae-b07c-bcbd3e304ea0.png)
![2022-07-31_21](https://user-images.githubusercontent.com/112183943/187953557-83a86d24-9efa-41a2-b3ee-7b1b76eefb22.png)

**Comment by DonBruce64** [comment]
That is something you will need to bring up with Craftsepeed.  It's an issue with their pack.

**Comment by Workersteve** [comment]
Ok thanks.

**Comment by DonBruce64** [comment]
Poked them for ya.  Turns out it's by design.  Go figure?
![image](https://user-images.githubusercontent.com/15241611/188252036-efcecf71-f0c4-4f1e-9bff-1cacb1b844a3.png)

**Comment by Workersteve** [comment]
Thanks , but i wish he do it and add something in config that if someone wants he/she can turn it off.
Because driving at night is a bit hard 😶.
