### ISSUE TITLE
Certain Planes Keep Ascending when Engines Turn Off During Flight

### ISSUE THREAD

**Issue by Doublehelix13** [DonBruce64/MinecraftTransportSimulator#1314]
When the Vulcanair, the Comanche, or the MC-172 are being flown and the aircraft either runs out of fuel or the engines are turned off, rather than gliding down to the ground, these aircraft will speed up and fly higher.  They will continue to ascend unless the pilot forces them to pitch down.  Once an aircraft in this state has landed, unless breaks are applied until the aircraft comes to a complete stop, it will speed up until it takes off again.  So long as the engine is running, the aircraft appears to behave as expected.  This does not affect any of the other planes from the OCP nor the ones from UNU Civilian or Military.  This issue occurs on the latest release version of IV, 1.12.2-22.0.0.

**Comment by DonBruce64** [comment]
Fixed in V21.1.0.
