### ISSUE TITLE
Scaling animation cant scale single axis in multiblock animation

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1316]
![image](https://user-images.githubusercontent.com/79125581/188320846-be1f02da-8157-496f-8863-a7a8bcfa0b2f.png)

https://user-images.githubusercontent.com/79125581/188320851-1c8992bd-8ddf-4a4d-ba3a-32b9d70018e1.mp4

![image](https://user-images.githubusercontent.com/79125581/188320865-dbafde49-5467-406f-8626-d0a783271243.png)
i have to do this or it will not animate  i cant make axis being [1,0,0] and make other block animate [0,1,1] with constant value

**Comment by DonBruce64** [comment]
Fixed in V21.1.0.
