### ISSUE TITLE
[Suggestion] Crate Capacity

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#132]
Would it be possible to have the capacity of a crate determined by the item size? Basically, it would be nice if a duffel bag didn't hold the same amount as a cargo container.

![2019-05-05_14 59 14](https://user-images.githubusercontent.com/36775575/57200936-86b65180-6f46-11e9-811a-0f3be956f837.png)

**Comment by TheOddlySeagull** [comment]
And why not add a key that’ll open all inventories from the vehicle?

**Comment by DonBruce64** [comment]
The regular key works the same for the vehicle and the inventories.  The idea behind that is if you have something like a crate in a car, you kinda need the key to get into the car to get at the crate.  Same goes for locked RVs.

As to the capacity, that can be changed, but you have to remember that chests have 27 slots by default.  Changing the code to non-chest code means making a custom GUI, and that's quite complex to get right and not mess up mods.  Heck, that's one of the reasons there's not a GUI for assembling vehicles any more.

**Comment by TheOddlySeagull** [comment]
When I told key I meant keyboard key
Perfect example of me failing with words xD

**Comment by DonBruce64** [comment]
Keyboard key will not be implemented.  That would defeat the point of reloading guns at the gun, and having cargo crates able to be swapped out.  Not to mention it'd be really hard to find out what part has what inventory.

Still, capacity is something we can look at, but the way I see it it'll be one of two ways.
1) I add a custom GUI, and risk it breaking with other mods installed as it has in the past.
2) I restrict inventories to be single-item like IE silos, and just impose a stack limit.

**Comment by DonBruce64** [comment]
Implemented in V14.3.0.
