### ISSUE TITLE
[Bug] Guns are loaded from the ammo crate only once.

### ISSUE THREAD

**Issue by dldev32** [DonBruce64/MinecraftTransportSimulator#1320]
Reference parts:
![IMG_20220908_181556](https://user-images.githubusercontent.com/65333989/189131635-6ef6c805-3eee-4963-9d26-adb7ac591bfa.jpg)
![IMG_20220908_181618](https://user-images.githubusercontent.com/65333989/189131905-2c2e346d-c33b-4073-856d-ab799afe1d4f.jpg)

**Comment by DonBruce64** [comment]
Do you have devMode enabled?

**Comment by dldev32** [comment]
> Do you have devMode enabled?

Yes, devMode enabled.

**Comment by DonBruce64** [comment]
Then that's per design.  devMode keeps you from running out of ammo by reloading the gun with bullets from the crate but it doesn't actually decrease the item in the crate when it does so.
