### ISSUE TITLE
Horn (sometimes) stutters on singleplayer

### ISSUE THREAD

**Issue by SilverDisturbed** [DonBruce64/MinecraftTransportSimulator#1321]
I noticed this as I was messing around with the OCP scout after making a second seat model for the right side seat slots... Not sure why but my current IV version is: "Immersive_Vehicles-1.12.2-22.1.0-BETA9"

And not too sure if anyone else reported this either so... forgive me if this is a duplicate report.

EDIT: This is possibly a freak incident but still reporting just in case

**Comment by boot2big** [comment]
I've experienced this a couple times on singleplayer, but I've had it happen way more often on multiplayer. I figured this was known and hard to fix though due to how MTS handles control inputs (if i recall correctly at least)

**Comment by DonBruce64** [comment]
See, I don't get why it'd stutter.  It should see a keyboard key go down, turn on the horn, and leave it on until that key goes up.  There's no reason the horn should turn on and off because the key is staying down.

I've had it happen every once and a while myself, but ignored it figuring it was lag or some such stuff.  Will investigate further when it comes up again.

**Comment by SilverDisturbed** [comment]
Noted.

**Comment by boot2big** [comment]
https://user-images.githubusercontent.com/53581325/197344549-ac9596ed-2594-4cb7-a717-4436aba3fbc4.mp4

Some minor testing of this on a multiplayer server.

Note that this server is using an older version of MTS though!! (21.2.0) If updating to the latest version will help with testing, please ask Seagull, this isn't my server. (But it's a very cool one and I'mma making big time monnys on it. :sunglasses:)
![image](https://user-images.githubusercontent.com/53581325/197344636-da8291ba-1bd1-4ad5-ae98-98bbf8e567b4.png)

**Comment by DonBruce64** [comment]
Interesting. Does this happen on singleplayer with the same mods installed?  Or is only on servers?

**Comment by boot2big** [comment]
It seems to only happen on servers, like I said I've rarely ever seen it in singleplayer. That's actually where it seems to work fine, so I don't see why it would be any different on a server. Testing is to be done with the latest version of MTS and a locally hosted server however, to reduce variance between versions and ping.

**Comment by boot2big** [comment]
Appears to be fixed as of... uhhh, the last 22.4.0 I had gotten!
https://user-images.githubusercontent.com/53581325/205211436-3d8f574b-caca-4c74-a20e-6faf7d4024d8.mp4

**Comment by DonBruce64** [comment]
Since the issuing user hasn't responded and went to poke other users on Discord, I'mma calling this ticket done.
