### ISSUE TITLE
[Enhancement] Distant sounds support.

### ISSUE THREAD

**Issue by dldev32** [DonBruce64/MinecraftTransportSimulator#1322]
Let's say that we need to diversify the sound playback at different distances. To do this, we simply specify the "minDistance": 0 and "maxDistance": 32 parameters, these sounds will be played from the source to the specified distance. Also, do not forget to specify whether the sound will fade linearly using the "linearFading" parameter to true/false. I think this feature will be useful to many PAs.

Concept:
```json
"sounds": [
      {
        "name": "packID:cannon_shot_close",
        "activeAnimations": [
          {
            "animationType": "visibility",
            "variable": "gun_fired",
            "clampMin": 1.0,
            "clampMax": 1.0
          }
        ],
        "minDistance": 0.0,
        "maxDistance": 32.0,
        "linearFading": false, //will the sound fade out?
        "forceSound": true
      },
      {
        "name": "packID:cannon_shot_mid",
        "activeAnimations": [
          {
            "animationType": "visibility",
            "variable": "gun_fired",
            "clampMin": 1.0,
            "clampMax": 1.0
          }
        ],
        "minDistance": 32.0,
        "maxDistance": 64.0,
        "linearFading": true, //will the sound fade out?
        "forceSound": true
      },
]
```

**Comment by DonBruce64** [comment]
I can see this being a good thing to have.  However, let us assume a PA says that the sound should play for a 20 block radius.  Does that mean the sound should immediately cut off at 20 blocks?  If not, where should the cutoff be defined?

**Comment by Prophet2002** [comment]
> I can see this being a good thing to have. However, let us assume a PA says that the sound should play for a 20 block radius. Does that mean the sound should immediately cut off at 20 blocks? If not, where should the cutoff be defined?

You can try to make the sound fade out if the "sound engine" allows it, but such a function should be controlled by another parameter.

**Comment by BlazeWolf1122** [comment]
Would personally like this functionality and would use it, useful for separating quiet economical engines from loud engines, and could benefit jet based aircrafts that make a loud whooshing noise when you're far away from them

**Comment by Ilya-torshov** [comment]
I would certainly like this feature.

**Comment by dldev32** [comment]
Addition: the parameter must have a range, say, 0-50.  This is necessary in order to play another sound in the range, for example, 50-90.

**Comment by DonBruce64** [comment]
So, this is super simple to do.  Y'all have 1 month to submit a PR (or bug E) to do this.  After that, ticked will close with a wontdo.  Tick tock!

**Comment by DonBruce64** [comment]
Tis been 1 month.  Closing time.
