### ISSUE TITLE
[Bug] Clicking door hitboxes with key triggers lock/unlock but it doesnt effect the locked variable

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1323]
when the vehicle is going from unlocked to locked, clicking the door with the key triggers it, but then if i go to unlock a vehicle using the door, the animation trigger doesnt apply
![2022-09-09_14 34 37](https://user-images.githubusercontent.com/53153740/189420564-04a61d03-07cd-416b-9ca3-71603f55e444.png)

**Comment by DonBruce64** [comment]
Fixed in V22.2.0.
