### ISSUE TITLE
Double Brackets for json materials optional when in devMode importing

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1324]
Putting this here in case if by chance you accidentally forget about it

**Comment by DonBruce64** [comment]
We already talked about this, and why it's not appropriate.

**Comment by BlazeWolf1122** [comment]
Yes you talked to me about it, no you never responded to me as to *why* it's not appropriate (except for when i asked about it originally) after after i gave several explanations, only that first time which feels like you chalked up my words to "i dont like devmode export i dont want to use it", which is very far from the real case
As far as i can recall, you responded with "use devmode export to fix the double brackets when importing" but i've told you (and explained why) i can't use devmode export, so my options are to either manually update the JSONs myself or outsource manual JSON updates to some random mts person, which is not ideal either
(ignoring the mind numbing task of updating my existing in-pack pack jsons just to add brackets) my mts devmode folder is littered with several dozen devmode export jsons, and to re-export them would 1. be a hassle 2. make me loose work
maybe there's some other reason that you might had told me as to why you don't wanna add this quality of life improvement, but my brain has forgotten about it since then

**Comment by DonBruce64** [comment]
It's not appropriate as you're asking me to make the importer import non-compliant JSONs, for a single section, just because you don't wanna update your own JSONs.  JSONs, mind you, that you don't *have* to update to have them work with newer versions.

I'm NOT adding an exception to the importer just because you wanna be lazy and not add the double-brackets to a few files.  Trin does this stuff manually, UNU does it, Franz and Laura do it, you can too.

**Comment by BlazeWolf1122** [comment]
"mind you, that you don't have to update to *have* them work with newer versions."
the logic is broken because with this logic it should mean that devmode would already work out of the box with this change, when this is not the case. it only works halfway

"Trin does this stuff manually, UNU does it, Franz and Laura do it, you can too."
Surprisingly, seagull runs his stuff through devmode half the time, and if he doesn't then there's a good chance his work is outsourced, usually by volunteers
Franz wanted this change to begin with, so of course he's gonna be accepting of it and updating his stuff, for i know he might even use devmode export himself to speed up the process
DPL works at a machine-like rate and efficiency, he takes it so seriously he's monetizing his work
Laura dedicates a large chunk of her life to mts, possibly at DPL level

"I'm NOT adding an exception to the importer just because you wanna be lazy and not add the double-brackets to a few files."
a *few*?
someone tried giving me similar reasoning last night and i threw them ALL my JSONs at them, they didn't wanna touch it either, not to mention all the other updates that you've let go through devmode import *with* legacyCompats (which thankfully exist)
![image](https://user-images.githubusercontent.com/63666200/189540498-fc4f5d4a-429a-4b4a-8e77-2742dc605aba.png)
of course the file amount seems comical, almost exaggerated, but that was quite literally all my JSONs, devmode JSONs which i actively use included

i'm displeased in how you consider me "lazy" in contrast to others, i've got more hobbies in my life than just mts y'know
i told you that i can't just go work on mts all day every day or something, though i said that a while back so it could had been forgotten
when i do go and work on anything mts related i go and burnout a week later, and mts pack making is the one exception to it in the sense that despite burning out i still hold out and do mts stuff, but as a result i literally feel like i have to drag myself to do anything half the time, which really just isn't healthy
burnout isn't exclusive to mts either though, it happens in all parts of my life
of course mts devmode isn't supposed to be the most fun thing in the world, but updates like these make me feel like an employee where half of his work is put down a paper shredder at random by his boss, since you're basically backtracking and halting all new potential progress by going back and replacing old progress

i mean, thank god me and them came to a solution to work around the json materials update in a reasonable workflow last night, otherwise this update would be dozens of times more brutal, (despite already stinging a bit) and i'd still continue this conversation in the context of "json materials update" rather than "stop calling me lazy jeez"
