### ISSUE TITLE
[bug] isInterior and isExterior variables don't work (when on parts)

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1326]
What it says on the tin

**Comment by Ilya-torshov** [comment]
It is to be noted that the variable works when its on the vehicle itself, like UNUs rain sound

**Comment by DonBruce64** [comment]
Technically, this isn't complete until a release version drops.

**Comment by DonBruce64** [comment]
Fixed in V22.2.0.
