### ISSUE TITLE
[BUG?] AutoReload handguns do NOT wait. Even a second. Jeeesuuus.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1334]
https://user-images.githubusercontent.com/53581325/190365681-ebaeee17-4860-4bc2-b731-f2892f2891d2.mp4

https://user-images.githubusercontent.com/53581325/190365686-6d8807d2-5787-4c02-8295-b9fa93f904c9.mp4

Testing is to be done with devmode disabled however, just in case.

Nothing urgeeent though... it is kinda fun.

**Comment by DonBruce64** [comment]
Odd, what's the JSON for the paramters look like?  This looks like the reload time is 0, so you're not getting a delay.

**Comment by boot2big** [comment]
`
    "handHeld": true,
    "isSemiAuto": true,
    "autoReload": true,
    "capacity": 6,
    "reloadTime": 5,
    "muzzleVelocity": 1100,
    "fireDelay": 6.0,`

**Comment by DonBruce64** [comment]
So looking at this, it seems like the reload time is 5 ticks, and the fire delay is 6 ticks.  That means that you'll only have 6 ticks between shots, or ~1/4 of a second.

**Comment by boot2big** [comment]
The thought process behind that though was that you wouldn't be *able* to fire when the gun is busy reloading, meaning the total reload time would've been 30 ticks. Still a fairly short time for a revolver, but a cooldown-and-reload time nonetheless.

**Comment by DonBruce64** [comment]
See, that's not how gun code runs.  It runs the cooldown and reloading timers simultaniously.  That's required for guns that can take ammo while being fired, like clip-based SMGs or gattling guns.  Cooldown (fireDelay) is a pure indicator of how many ticks pass between each firing, and reloading is just for the reloading of bullets.  They don't mix.

**Comment by boot2big** [comment]
Well I'll just have to set the reload time to 10 or 20 then, at least so that spam firing isn't as viable as vid related.

**Comment by DonBruce64** [comment]
Rodger.  LMK if the reload time takes proper effect when it's increased.  Want to make sure this isn't still a bug and I'm just not noticing.

**Comment by DonBruce64** [comment]
Is confirmed to not be a bug, just slight confusion as to how reloadDelay and fireDelay work.
