### ISSUE TITLE
UNU Helis don't work after engine 'fix'

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1339]
MTS V22.1.0-BETA9 broke UNU Helis. This was allegedly a fix to fix planes from gliding up with the engines off, however in my testing, they work fine in BETA 8 (I tested the UNU Navigator as well as all OCP planes).

This is a ticket in reference to our discussion in PMs

**Comment by DonBruce64** [comment]
Fixed in V22.2.0.  Well, back to the way it was in the beta before this one anyways, just a little less thrust than before.
