### ISSUE TITLE
[Wiki] Error in the text of the Particles section.

### ISSUE THREAD

**Issue by dldev32** [DonBruce64/MinecraftTransportSimulator#1342]
![IMG_20220927_164126](https://user-images.githubusercontent.com/65333989/192534622-5926d1d5-4be9-49ea-9742-e49c8cedc982.jpg)

**Comment by LauraDarkez** [comment]
i can fix this

**Comment by LauraDarkez** [comment]
i unfortunately cant close this ticket even though i have done the fix
