### ISSUE TITLE
[Enhancement] Road curve conformity variable

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1345]
I refer to our discussion in Garage a couple days ago. Currently I have no way to make the bogies on my rail vehicles actually turn correctly with the curvature of the rail  (road) they are on

**Comment by DonBruce64** [comment]
This is super easy, as all it requires is checking the angle between the vehicle and follower in the Y axis.  Outsourcing with a 1-month timeline.  Go bug a Luigi, Elephant, or make a Don a deal.

**Comment by DonBruce64** [comment]
Implemented in V22.2.0.
