### ISSUE TITLE
[enhancement] Snap connections

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1348]
add a boolean, say for instance "isSnapCouple": true, that will make two connections with this and otherwise compatible automatically connect when close enough. For rolling stock with knuckle connectors and others that are expected to function this way.

**Comment by DonBruce64** [comment]
But how do you un-couple them?  They'd just re-connect.

**Comment by Ilya-torshov** [comment]
You got me there actually lets move this to discord

**Comment by Ilya-torshov** [comment]
Note: As discussed on discord, the un couple problem mentioned would be fixed like such: they are uncoupled with either a wrench or hitbox, and the coupler will remain disabled until they are clicked/wrenched again

**Comment by DonBruce64** [comment]
Added in 22.3.0.
