### ISSUE TITLE
broken font color

### ISSUE THREAD

**Issue by xXN1ckWa1k3rXx** [DonBruce64/MinecraftTransportSimulator#1349]
![1866}@68 7OKKG}8GHVHAO1](https://user-images.githubusercontent.com/85390877/193451350-84f6b354-7cd8-453e-9dde-d9a5333e349e.png)

version 22.0 is normal and work.
I won't put the 22.0 image because I'm worried that rolling back the mod will cause compatibility issues with the map.

**Comment by DonBruce64** [comment]
Which exact version is this? 22.0 is not an actual version.

**Comment by DonBruce64** [comment]
This ticket is now invalid as of V22.2.0, which removes creative engines in lieu of having them become creative when one sits in the vehicle while in creative.  Therefore, the creative text will never exist and will never display.
