### ISSUE TITLE
[BUG] Disabled seats won't remove you from the seat, despite blocking you from entering it.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1351]
Forces the player out of their seat and outward under certain conditions, for jets and the like.
Probably _nooot_ the best idea in a helicopter though.

**Comment by boot2big** [comment]
Tested doing this with seat activeAnimations, but having an AA on a seat doesn't seem to boot you out of it when the seat becomes inactive. It only prevents you from getting back in *once* you're out... Plus, it don't shoot you out!

**Comment by DonBruce64** [comment]
Well, one could always make the seat start moving but be invisible to simulate ejection.  But yeah, active should boot you out of it becomes no longer that.  So techincally a bug I suppose in that case?

**Comment by boot2big** [comment]
I'd take that to implement ejector seats too, then!

**Comment by boot2big** [comment]
https://user-images.githubusercontent.com/53581325/194452823-9eb39261-228b-4a5a-907d-81c4cbfbb8a1.mp4


https://user-images.githubusercontent.com/53581325/194452824-1c294e6b-beae-4ed1-a3c3-ac84fd67b620.mp4

**Comment by DonBruce64** [comment]
Fixed in 22.3.0.
