### ISSUE TITLE
[BUG?] Holding a button collisionbox and moving the cursor off of it will lock it on.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1354]
Unsure if a fix is even possible, but this *will* be problematic for my ejector button... I didn't quite want it on the panel.
If no fix is possible then I'mma just have to move it there and use VMs to disable the switch.

**Comment by DonBruce64** [comment]
A fix is indeed possible.  I didn't even think one would do such a thing.  But now I know I was wrong!

**Comment by DonBruce64** [comment]
Fixed in 22.3.0.
