### ISSUE TITLE
[Enchantment] Remote control item, that can control cars.

### ISSUE THREAD

**Issue by NBGReal** [DonBruce64/MinecraftTransportSimulator#1355]
Vehicles could have a special type like remote-control,
or any vehicle can be controlled.
You would have the same frequency on the remote and car to be able to control It.
Optionally a config option could be added that allows/denies other player to use frequencies that are already In use.

**Comment by boot2big** [comment]
There's an addon mod for MTS that can _indirectly_ do this, but you'd need to know some Lua and API stuff to make any of that. And OpenComputers/ComputerCraft.

TBH I actually agree here, and can even make an RC item model if need be.

**Comment by DonBruce64** [comment]
I don't want to code this.  Too much for me to do right now with version updates and all the other features people keep dumping on me.  I'll let it sit for two weeks, and if nobody picks it up then I'm wontdoing it.

**Comment by boot2big** [comment]
Could wontdo it because of the Immersive Vehicles Remote Control mod _anyways,_ and just have users get gud with coding Lua on Pocket Computers/Tablets. It's fun anyways!

**Comment by DonBruce64** [comment]
Works for me!
