### ISSUE TITLE
[BUG?] Ground devices can "kill" items. 

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1357]
May not be fixable, but it _could_ be a problem for harvesters. It's pretty fun though.

**Comment by DonBruce64** [comment]
Eh, that's so much of an edge-case I'm gonna call it a feature.  Besides, if you run over that seat, it won't be a seat anymore!  As to harvesters: they shouldn't drop the wheat right under the wheels.  Wind-rowers have a wide track stance just for that reason.
