### ISSUE TITLE
Crash with Phosphor on latest version.

### ISSUE THREAD

**Issue by MaepleCake** [DonBruce64/MinecraftTransportSimulator#1359]
I recently installed this mod and have been getting crashes on startup before the pack could properly load. I found out that phosphor was the conflict, removing it fixes the startup crash both in my large modpack and a test environment. However, downgrading to 22.1 also appears to fix it. I'm aware it's essentially abandoned at this point, but if a fix is possible it'd be nice to be able to run both on the latest version for the performance gains it provides.

https://paste.ee/p/7odQV

**Comment by DonBruce64** [comment]
This was fixed in commit 198378f534e0064845a5024a03f347f77b9199c5 and will be fixed in the next update.

**Comment by DonBruce64** [comment]
Fixed in 22.3.0.
