### ISSUE TITLE
Request:  Configurable weight for parts

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#136]
Seems self explanatory, would be a JSON variable under the "general" section.

**Comment by DonBruce64** [comment]
Not doing this.  Would force people to make a weight for every single part they make, and would throw packs off-balance due to differing weights for different parts.

**Comment by fsendventd** [comment]
Ehhh.... okay, that checks out. I can compensate for the stupid weight values myself.
