### ISSUE TITLE
[Feature Suggestion] Radars

### ISSUE THREAD

**Issue by conman180** [DonBruce64/MinecraftTransportSimulator#1363]
### **Preface**
Since bullet code was recently changed to have them be server side, it opened up the possibility of beyond visual range (BVR) combat. Only a few instances can currently fully take advantage of this. An example would be long range artillery. With an entity radar system, it would expand the usefulness of bullets being server side.

### **Possible Uses**
Air Traffic Control- It would allow being able to "see" aircraft outside the render distance

BVR air-to-air combat. While seeing entities beyond the render distance wouldn't totally implement this, it is required to make it feasible. being able to see what's out there will allow you to shoot at it.

Target distinction- The radar could be set up in a way to be able to distinguish between, aircraft, ground vehicles, mobs(however it would clutter a screen), or players.

### **Future Uses**
Proper lock-on mechanics- Having radars would open up the possibility of locking on to a target without having to constantly have the player look at it. Rather than basing it off of the player's look vector, it could be set up to keep a lock within a specified cone around the forward vector of either the radar or the vehicle it's on.

Different bullet guidance and target types- It could allow for weapons that only go for specific targets. An air-to-air missile shouldn't be able to track a tank or truck. Overall it could add more customization options. Possible guidance types could be as follows:

-Infrared: Already implemented with bullets being able to track engines. Addition would be the ability to track aircraft or ground vehicles, or both if configured to be able to. Example: AIM-9 Sidewinder (Air-to-air), AGM-65 Maverick (Air-to-ground)
-Semi-Active Radar: Tracks the entity the radar is locked on to, but if target lock is lost during it's flight from the target moving outside the radar's cone where it can see things, it stops tracking the target and cant reacquire. Example: AIM-7 Sparrow
-Active Radar: Tracks the locked target once fired, but locked onto the vehicle entity itself rather than the engine. A cooled engine wouldn't fool it. Example: AIM-120 AMRAAM

-"laser" guided: tracks to wherever the player is looking until impact

![FP04zyxWYAEn8sh](https://user-images.githubusercontent.com/78190656/195262101-13ea0309-7cfa-4767-b3a1-c12834ac944e.jpg)

I'd be able to go more into depth on the discord and have models to test the variables on if implemented. I feel it could make this side of the mod more immersive and out-do other other mods if it could be done right.

**Comment by DonBruce64** [comment]
There's a lot of content in here.  And some mis-understandings on the client-server architecture.  Please ping me on Discord so we can discuss further.

**Comment by DonBruce64** [comment]
I'm going to table this ticket, as I eventually want to load all entities in IV on the client and server side for various reasons.  Once that happens, radar will be possible.

**Comment by conman180** [comment]
Sounds good. Thanks for taking a look at it.

**Comment by DonBruce64** [comment]
Implemented in 22.5.0.
