### ISSUE TITLE
[Suggestion] Repeating features on roads

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1364]
I know we've spoken about this already but I figured it was best to put it up as a ticket in any case, if nothing else to be annoying
cheers

**Comment by DonBruce64** [comment]
I don't see myself getting to this until roads get a larger sphere of adoption.  In that case, it'll get lumped into a whole road-centeric-feature-update.  As it stands, I won't do it as a one-off feature implementation as I literally don't have the time.
