### ISSUE TITLE
new animation variable

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1365]
new animation variable for checking if user is making steering input
press steer button then value = 1
not pressing steer button then value = 0
for a non keyboard input, this would be checking if the user made significant changes to steering input with a deadzone, say if i have a joystick and move it from 0 to 0.5, but held it at 0.5, but the input wobbled between 0.49 and 0.51 because its an analog and not digital input, plus nobody's hands are perfectly still

new animation variable for checking if user is steering left or right
like previous one, using the same logic, but instead checking if there's any input and it goes to 0 1, it goes to -1 0 1 since it's checking if the user input is a left input or a right input

~~i think at this point it would be better if packs handled steering logic rather than the core mod so that not everyone has to deal with one singular steering method the core mod provides that might help one sector of IV vehicle but absolutely destroy another sector of IV vehicles, but this is all off topic since the chances of you doing this is rather unlikely~~

**Comment by DonBruce64** [comment]
This won't work as you expect.  Due to packet loss, there's going to be periods on the server where the user won't be steering, but will still be holding down the steer button.  Only clients know the exact number of ticks that button is held down.  This is why there's the small steering delay.

**Comment by BlazeWolf1122** [comment]
dammit

**Comment by BlazeWolf1122** [comment]
would you be able to do the pack/vehicle based steering rather than core mod based steering thing though, or is that just not feasible?

**Comment by DonBruce64** [comment]
I don't know what you mean by that.

**Comment by BlazeWolf1122** [comment]
ping me on the mts discord about it some tome and i'll get back to you about it later, my brain can't think of how to put it in to words right now

**Comment by DonBruce64** [comment]
I know what this is for.  Even without you explaining it.  And it won't work.
