### ISSUE TITLE
Animated plane cockpit

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#137]
Just like how cars have animated steering wheel, gear shifter and pedals, planes should have animated parts in their cockpit too.

That includes:
Throttle
Flaps
Rudder pedals
Yoke(or side stick)
Break
(future)landing gear

**Comment by DonBruce64** [comment]
All of these things are currently possible right now, but are not implemented in OCP vehicles due to the fact they are older and simpler models.  I would love to have them in the OCP vehicles, but detailed cockpits are not in the cards.
