### ISSUE TITLE
Wheel hitboxes stick behind when a mounted connection happens

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1375]
Wheel hitboxes stick behind when a mounted connection happens. My guess is that the wheel collisions go away when mounted, the boxes just linger because that was their 'last position' since they move back upon disconnection.

This seems to be visual since the blue boxes don't block block placement or seem to have any impact whatsoever.

![2022-10-14_23 16 50](https://user-images.githubusercontent.com/36775575/195972462-38138a13-47a6-41e9-9bf1-69dae7bcf8b8.png)

**Comment by DonBruce64** [comment]
Fixed in 22.3.0.
