### ISSUE TITLE
[bug] Health NaN%

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1376]
I've seen several instances of this, not sure why

**Comment by DonBruce64** [comment]
Unless you can tell me how to reproduce the bug, I won't be able to do much about it as I rarely mess with damage systems during dev, so it happening to me is unlikely.

**Comment by Ilya-torshov** [comment]
Just get seated in a vehicle. they will be NaN by default. I'm not sure if its save based or what it is

**Comment by boot2big** [comment]
I've never seen this before to be honest. I've gotten them to _negative_ health, but that was with devmode fuckery, and it was still a number.

**Comment by DonBruce64** [comment]
Closing as issuer says they haven't had this in a long time, and I suspect it was caused by importing 0 max health and / by 0, which is NaN.
