### ISSUE TITLE
[Bug] Removed parts don't always match color.

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1377]
When a default part has a tone that is different, upon removal the part matches the default part, not the part that is actually installed ans hown.

For example, an UNU Wolf has a default Offroad Wheel that is no color. The part color is changed to match the paint via tones. When this wheel is removed, the part that comes off is the non colored variant.

The same can be seen by painting a part. If you install a green wheel, paint it beige with the gun, and remove it, you get a green wheel.

**Comment by DonBruce64** [comment]
Fixed in 22.3.0.
