### ISSUE TITLE
[Enhancement] Few suggestions about camera enhancements

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1379]
1. Variable, so something can only be rendered/enabled in first person
2. Variable, so something is rendered only for one client
3. Variable, so camera can be always active when in first person
Those things can solve a problem with first person viewmodels with handhelds.
Video is demonstration why third suggestion is useful

https://user-images.githubusercontent.com/46074580/196266694-d4204518-5c42-4803-8291-851fb6cb3855.mp4

**Comment by DonBruce64** [comment]
On item per ticket only.  You get the first one.

**Comment by DonBruce64** [comment]
Added in 22.3.0.
