### ISSUE TITLE
Request: "control" version of propeller pitch variable

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#138]
Instead of showing the blade's actual angle like the current variable, it could display as a percentage of the blade's angle (with 0 being no pitch/feathered and 100 being maximum pitch). This would work better for a propeller pitch control as it would always rotate the same amount no matter the blade's pitch, meaning that the lever wouldn't go off the mount with a very high pitch prop.

**Comment by DonBruce64** [comment]
While I agree with that, my concern is that most people who will implement these levers or dials will use numbers as a reference.  Plus, with reverse thrust there's not a good way to scale the output to make it work with all propellers.  It's easy to add, however, so I'll be doing so in this upcoming release.

**Comment by DonBruce64** [comment]
Implemented in V15.0.0.
