### ISSUE TITLE
[Enhancement] Variable for rendering something client side only

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1381]
title says everything

**Comment by DonBruce64** [comment]
No it don't.  You can only render things on the client.  The server can't render things.  I suspect you mean something else?

**Comment by dldev32** [comment]
> No it don't. You can only render things on the client. The server can't render things. I suspect you mean something else?

I suspect he is referring to controller-only rendering of models.

**Comment by boot2big** [comment]
In that case you can already somewhat do that? Just have something linked to a "seat_occupied_client_#" variable, and only the driver will see it.

**Comment by Wartich** [comment]
Sorry for being unclear, i meant rendering models for one client only with animation variable. It would be useful for hiding some parts of models for other players. For example hands model for first person with handhelds or ammo counters

**Comment by DonBruce64** [comment]
Exists with `gun_controller_firstperson`

**Comment by DonBruce64** [comment]
Implemented in 22.4.0.
