### ISSUE TITLE
[Enhancement] Variable for making camera on handhelds always active when in first person.

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1382]
https://user-images.githubusercontent.com/46074580/196266694-d4204518-5c42-4803-8291-851fb6cb3855.mp4

Would allow to (kinda) make viewmodels and HUDs with ammo counters

**Comment by DonBruce64** [comment]
So basically, you want the gun to act as if it's always aimed and always uses the camera?  I can do that, though it'll be a gun parameter rather than a camera parameter.

**Comment by DonBruce64** [comment]
Implemented in 22.4.0.
