### ISSUE TITLE
[Bug] IsCoAxial being weird

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1386]
![bilde](https://user-images.githubusercontent.com/63523852/197231665-a0367e35-1aff-4d43-a590-a57af0044094.png)
1 is coaxial, 2 is part of the turret

when 1 is selected, everything moves as expected
when 2 (turret) is selected, 1 does not animate.
Putting animation on the parts slot for 1 does nothing, neither does applyAfter

![bilde](https://user-images.githubusercontent.com/63523852/197231962-198884d9-543c-405f-b3b7-b5f030b5ad14.png)

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
