### ISSUE TITLE
Parts don't always place when also looking at a close hitbox (even if the hitbox doesn't occlude the holobox)

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1388]
In the first picture the part will not place. In the second picture, it does. I am guessing that MTS thinks the closer collision box is blocking the part since the center is closer to the player.

I would suggest making it so collision boxes don't block part placement, in my opinion that should be done with interactable variables.

![2022-10-21_21 01 14](https://user-images.githubusercontent.com/36775575/197357741-7919fe4d-93a9-4757-b8be-1746a9686d86.png)
![2022-10-21_21 01 23](https://user-images.githubusercontent.com/36775575/197357747-0b6dde4c-afd3-4ac1-9098-d9f8dadd12a2.png)

**Comment by DonBruce64** [comment]
I can't really do the collision box blocking not blocking stuff, since the slot boxes are collision boxes themselves, and the game needs to know if the player has clicked a holobox or a door/seat/etc.  But one should be able to place parts whose hitboxes are closer than the other boxes.

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
