### ISSUE TITLE
Bench crafting recipes in manual

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#139]
If we could have the recipe to all benches in MTS in the manual, It’ll be quite practical, plus, why not add screenshots of how to craft them in the Curseforge page?

**Comment by DonBruce64** [comment]
I'll add them to the manual for sure, but I won't be adding them to the Curse page, as that would require me to update that page whenever a recipe changes or gets added, and that's annoying.  Much rather have everything in one place, and seeing as how everyone should have a copy of the manual (just like in Immersive Engineering), that's a good place for them to be.

**Comment by DonBruce64** [comment]
Added in V14.3.0.
