### ISSUE TITLE
This happen in game when trying to edit a beacon :

### ISSUE THREAD

**Issue by Ninovui** [DonBruce64/MinecraftTransportSimulator#1394]
[crash-2022-10-29_15.13.49-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9893753/crash-2022-10-29_15.13.49-client.txt)

**Comment by DonBruce64** [comment]
Yup, that's indeed a bug.  Does it happen every time, or only sometimes?  On a newly-placed beacon, or one that's already been placed down and saved into the world at one point?

**Comment by DonBruce64** [comment]
Closing as this ticket is for a Waaaaay outdated version of Immersive+Vehicles-1.12.2-19.15.7.jar.  Also,, cause no response.
