### ISSUE TITLE
[Enhancement] Make "resetPosition": true able to be defined on a part slot

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1398]
reason being: defaultYaw and defaultPitch can be defined on part slots, but not all guns that go in these slots have a "resetPosition": true defined in their jsons

**Comment by boot2big** [comment]
^ on this one

**Comment by DonBruce64** [comment]
So basically if either are true, make this true?  That's super easy, and can be done similar to how the existing code is done for the min/max yaw.  This gets to be a PR for youse three (cause I KNOW Franz is involved in this).  Y'all get 1 month to put your Cerberus coding brains together to make this a reality.  Tut tut!

**Comment by LauraDarkez** [comment]
actually franz wasnt involved. this was @Wartich and i's discussion. but, hopefully we can figure this out

**Comment by LauraDarkez** [comment]
ugh... i asked both franz and wartich, and they dont understand what to do

**Comment by DonBruce64** [comment]
_Somebody_ deleted a comment on here.  Too bad I get emails with said comments.  But for once, it wasn't the usual suspect!

Y'all gonna hafta find someone to code this code though.  There are people that can code minor code codes with copy-paste logic of stuff that does similar things.

**Comment by LauraDarkez** [comment]
i deleted the comment cause i posted it before getting a full answer from franz

**Comment by DonBruce64** [comment]
Implemented in 22.4.0.
