### ISSUE TITLE
Support for more than 4 engines

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#14]
Currently, the MAG and START buttons for aircraft engines go off the panel when more than 4 engines are added, so you cannot access any more than 4 of the engines. Can this be changed?

**Comment by DonBruce64** [comment]
This is more of a bug than a feature, as you *should* be able to have more.  I don't know if I can fit more buttons, or if I'll have to move them over to make space.  Will investigate.

**Comment by DonBruce64** [comment]
Come to think of it, is there any aircraft that has more than 4 engines that anyone has made?  I think I'll put this bug on the backburner until such a time that I need to address it for pack systems.

**Comment by fsendventd** [comment]
An-225. And I'm making a B-36.

**Comment by DonBruce64** [comment]
Addressed in V13.0.1.  Now the MAG and START buttons form a second column if there are more than 4 engines.  The trim and reverse thrust buttons are then moved 1 column over, so this means 5-engine planes actually have less panel space for instruments.  Choose wisely what you put where!

**Comment by fsendventd** [comment]
Still doesn't support 10-engine planes....

**Comment by DonBruce64** [comment]
No, but it supports the An-225, which is six-engine, and it can support the B-36 if the pod-based jets are considered one engine rather than two.  I see no reason for 10-engine support right now.
