### ISSUE TITLE
[BUG] Viewing a repair recipe and switching to an item that doesn't have an existing repair recipe will cause MTS to crash.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1404]
[crash-2022-11-01_16.50.55-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9913905/crash-2022-11-01_16.50.55-client.txt)

**Comment by DonBruce64** [comment]
Well, that's a dumb oversight on my part... Should I just make the recipe default to not-repair whenever you switch I would assume?

**Comment by boot2big** [comment]
Sounds good

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
