### ISSUE TITLE
Helicopter kills me

### ISSUE THREAD

**Issue by HeavyTankr** [DonBruce64/MinecraftTransportSimulator#1405]
Using the helicopter included with the main pack, as well as the wayward helicopters, kills me randomly. I think it might be related to how much of an angle I'm at, but I'm not sure. One of my mods that I use with this has breath you can see, and the breath is much higher than usual. I think my player hitbox may be much higher than it should be, causing it to hit the propeller while flying, and killing me. I know the propeller is killing me as it says it is in the chat. Any help would be appreciated!

**Comment by HeavyTankr** [comment]
I just had to change my version of immersive vehicles to 21.3.0. if anybody else was having this problem.

**Comment by DonBruce64** [comment]
Downgrading is not a fix.  Re-opening this ticket.

**Comment by DonBruce64** [comment]
The odd thing is, I swore I fixed this issue.  If you fly with just IV installed, do you get killed by the propellers?  I've had folks say that they used to have issues like this, but they've been fixed since then I thought.

**Comment by DonBruce64** [comment]
Closing due to no response by user, and testing with Bell Helicopter not showing this behavior as of latest version.
