### ISSUE TITLE
[BUG] fireDelay and windupTime work together incorrectly on vehicles.

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1407]
https://user-images.githubusercontent.com/46074580/199679841-7c7b62fa-72d4-4178-bf9c-723fdedf931a.mp4

As you can see, it works properly on handhelds, but on vehicle fireDelay applies after windup time which causes additional delay.

**Comment by boot2big** [comment]
SEEE? I TOLD YOU I WASN'T CRAZY!!! IT DOES THIS EVEN WITHOUT A WINDUP TIME!!!!!!

**Comment by DonBruce64** [comment]
Wait... is that a Spammton NEO mech suit?

**Comment by boot2big** [comment]
Wait.
What the fuck

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/199872208-44ff6b84-04cc-4514-a907-9696f9b04259.png)
Welp, no better time to point out that I'll have a drivable dalek suit soon!

**Comment by Ilya-torshov** [comment]
Yeah I can attest to this, my tanks take ages to fire because of it

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
