### ISSUE TITLE
Request: Trailer

### ISSUE THREAD

**Issue by jeremblafr** [DonBruce64/MinecraftTransportSimulator#141]
Hello,
I made trailers for one of my vehicles by creating an anchor point on my vehicle and putting my trailer in shares, however my system does not work, would it be possible to add a new function or that the parts move with a position relative to the rotation
![2019-05-08_19 14 31](https://user-images.githubusercontent.com/50443190/57440275-00508700-7248-11e9-9959-9a2ab663d442.png)

**Comment by DonBruce64** [comment]
Trailer physics has already been requested.  See #46 for details.
