### ISSUE TITLE
Parts cannot initiate connections

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1410]
When I have a connection on a part (on a vehicle) and try to initiate that connection, it works the first time but not again.

This can be tested on my forklift with a pallet. The first connection works, but when I disconnect it and try to connect it again, it just says 'no trailers found'.

This seems to only be with connections with parts.

First connection works:
![2022-11-05_20 50 26](https://user-images.githubusercontent.com/36775575/200153251-b054083c-28d6-43be-a247-f9ff4a66ac51.png)
Disconnects fine:
![2022-11-05_20 50 32](https://user-images.githubusercontent.com/36775575/200153252-705e94cb-3914-43ce-b28f-08252942706f.png)
Won't reconnect:
![2022-11-05_20 50 34](https://user-images.githubusercontent.com/36775575/200153253-ff4eda93-bbf9-4537-8749-535c4db2478c.png)

**Comment by DonBruce64** [comment]
Very odd.  Is there anything in the logs about bad packets?  And if you re-log, can you then connect that pallet?

**Comment by boot2big** [comment]
This must explain an issue me and another fella experienced on an MC server, though I probably won't be able to get any logs for you, sorry.

Similar scenario here, where a part with a connectionPoint is trying to connect to a vehicle.
May do some extended testing involving a local server, to suss this out issue along with the laggy horn.

**Comment by DrprofLuigi** [comment]
> The second picture in the chat says that no trailers were found, which shouldn't appear when disconnecting a trailer.

That is some fanciness with the pallet, ignore that second message as it is working properly.

**Comment by DonBruce64** [comment]
Can you show the panel status with the pallet first disconnected, with it connected, and after you try and connect it the second time and it fails?  The panel status tells me information the picture and chat messages don't.

**Comment by LauraDarkez** [comment]
in my testing, the panel shows a proper connection when connected, and doesnt show a connection when it fails after disconnecting

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
