### ISSUE TITLE
[Enhancement] Support for sequenced particles.

### ISSUE THREAD

**Issue by dldev32** [DonBruce64/MinecraftTransportSimulator#1411]

**Comment by DonBruce64** [comment]
Such things are already possible with VMs.  Either use that, or PR this.  1-month deadline.

**Comment by boot2big** [comment]
TF even is a "sequenced particle"? And what use would I even have for one?

**Comment by dldev32** [comment]
> TF even is a "sequenced particle"? And what use would I even have for one?

Applying texture atlases as the same particle explosion was done in vanilla MC.

**Comment by boot2big** [comment]
I don't see much of a use for this besides saving total texture atlas space, and even then that seems like it'd be _more_ wasteful.
Besides, newer MC versions split particles into their own little textures anyways, just like we have in MTS right now!

**Comment by dldev32** [comment]
> I don't see much of a use for this besides saving total texture atlas space, and even then that seems like it'd be _more_ wasteful. Besides, newer MC versions split particles into their own little textures anyways, just like we have in MTS right now!

But in MTS there is no way to make the texture of the particle be animated.

**Comment by boot2big** [comment]
Modern MC also handles this by having numbered particle files, and a .json for the particle. Nevertheless, I can't see myself having much use for animated particles besides explosions, so I'mma say this is still on you to PR. I don't gots a use for this.
![image](https://user-images.githubusercontent.com/53581325/200449094-7e60becc-38b8-46c3-8a9f-9cc497cae85c.png)
![image](https://user-images.githubusercontent.com/53581325/200449147-cd9a828a-3dbe-4aff-bfb9-3ad912ca3c9b.png)

**Comment by DonBruce64** [comment]
Implemented in 22.5.0.
