### ISSUE TITLE
The game fails to launch

### ISSUE THREAD

**Issue by LasthopeBR** [DonBruce64/MinecraftTransportSimulator#1414]
Whenever I try to launch the game, this message is displayed in the latest.log:

[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9948067/latest.log)

https://mclo.gs/G6PXwpw

**Comment by DonBruce64** [comment]
Dassa nother @Elephant1214 issue.  Related to #1402 probably.

**Comment by Elephant1214** [comment]
It only happens with SecurityCraft, technically a duplicate of that other ticket. Send the log in that issue just to track it.

**Comment by Elephant1214** [comment]
Scratch that, doesn't seem to be the issue

**Comment by Elephant1214** [comment]
Can you Try without Security Craft just to be sure?

**Comment by Elephant1214** [comment]
I need the crash report, the partial log that you sent doesn't seem to contain everything.

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
