### ISSUE TITLE
[BUG] Electric motors don't work very well with default fuel quantities.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1415]
Which, I guess makes sense considering it shouldn't be running on "fuel", but I feel like the car should still be coming pre-charged then?

Curiously enough, this must either be happening client-side only or the electric motor and/or vehicle gets confused, because the motor still thinks there's fuel/battery charge and will still run even if you hop out of the driver's seat. It only resets this behavior once you pick up the vehicle as an item and place it back down, where the motor will then only run if you recharge the vehicle or you're in creative.

**Comment by DonBruce64** [comment]
It should indeed be pre-charged.  But I see where this issue will crop up given how default fuel stuff works.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
