### ISSUE TITLE
[Enhancement] starterHoldTime: ##

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1416]
As I'm looking to make my vehicles more realistic I think this will be a useful feature for engines that take a while to start up

Basicly you define a time in ticks you have to hold the starter, unaffected by starter time. When this time had elapsed the engine will continue the startup on its own

Useful for
-aircraft with automatic starters that only require a click on the button, but still needs time to wind up
-any jet engine that needs to be held for some time but still need to wind up after the starter can be released

Before you say "oh but the vehicle does not have enough battery for very slow starts" If this is added I will make APUs and ground power devices

**Comment by DonBruce64** [comment]
For sure possible, and not super hard either.

**Comment by LauraDarkez** [comment]
unu already has a ground power device. this would make that a useful object. there is one thing i dont like though, if the battery fully charges while starting, the jumpers will automatically disconnect

**Comment by DonBruce64** [comment]
Is it possible to make this rather than a starter hold, a simple engagement of the auto-starter when the starter button is pressed?

**Comment by DonBruce64** [comment]
Closing due to no response for 1 month, and the making of an APU not being likely given current IAV pack development.  Can re-open when development resumes.
