### ISSUE TITLE
[Enhancement] propeller_rpm variables

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#1417]
As it says on the tin. Same as the engine ones, rpm and rpm_percent.
Helis have gauges for this

**Comment by DonBruce64** [comment]
Should be super-easy to add, since it's just one line of code for each in the same places as other variables in PartPropeller.  1-month PR timeline.

**Comment by DonBruce64** [comment]
Seeing as how nobody can agree on %, and RPM was done by Laura, I'mma calling this "done".

**Comment by DonBruce64** [comment]
Implemeted in 22.4.0.
