### ISSUE TITLE
Plane AP

### ISSUE THREAD

**Issue by UTrosh** [DonBruce64/MinecraftTransportSimulator#1418]
Make a real plane autopilot, that follow the beacon, right and left :D

**Comment by DonBruce64** [comment]
Since you think it's so easy, you have 1 month to do this before I close the ticket as a wontdo.

**Comment by UTrosh** [comment]
I dont Say its easy, its just a good suggestions

**Comment by boot2big** [comment]
Issa good suggestion, that _you've_ been put to work on!

**Comment by UTrosh** [comment]
i will try

**Comment by ktokto313** [comment]
> i will try

are you going to code it?

**Comment by UTrosh** [comment]
yeah bc donbruce dont want :(

**Comment by ktokto313** [comment]
I am asking because i am also working on this thing too, but the result is quite far for me, how is your progress, can you handle this by yourself?

**Comment by DonBruce64** [comment]
Somehow, I doubt it.  Folks who don't use proper grammar don't tend to have the mindset to learn computer code.

**Comment by UTrosh** [comment]
I'm french i'm not english

**Comment by ktokto313** [comment]
@UTrosh uhm, how about my question? I nearly figured the horizontal navigation out, how is things on your side?

**Comment by UTrosh** [comment]
i have school so i didnt started yet xd sorry. but i think i can use actual autopilot and edit something

**Comment by ktokto313** [comment]
![image](https://user-images.githubusercontent.com/57142191/202489009-0d265702-ff4f-4a06-a5ac-18b3c279f4bc.png)
I have some concern about this idea, maybe it was a bad idea from the beginning

**Comment by UTrosh** [comment]
nice start

**Comment by UTrosh** [comment]
but i thing we can copy the altitude but need to make math to autopilot to beacon

**Comment by UTrosh** [comment]
you think you can do this or you will need help?

**Comment by ktokto313** [comment]
of course, I will, you may access to my code on my personal fork and use it as you like.

**Comment by UTrosh** [comment]
ok i will check this, currently what works?

**Comment by DonBruce64** [comment]
1-month timeline has been reached.  Ticket is now closed.
