### ISSUE TITLE
[BUG?] Something's messed up a-gooden with the LCs regarding the `fuelpump_purchased` variable.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1419]
[fuelpump.json.pre.gameload.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9976398/fuelpump.json.pre.gameload.txt)
[fuelpump.json.post.gameload.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/9976399/fuelpump.json.post.gameload.txt)

Normally the screen on the fuel pump's supposed to have three variables showing how much fuel you've purchased, how much fuel is in the pump and how much fuel the pump has put out.
Additionally the top part on the pump finally gets used for text instead of being a blank decorative thing.
However it seems MTS has a different idea of how my pump should be laid out and while I respect the LC system and devmode a lot, I'mma have to disagree with how it thinks my pump should look.

![image](https://user-images.githubusercontent.com/53581325/200976973-bc765db6-df88-476b-830e-7af034f986b1.png)
![image](https://user-images.githubusercontent.com/53581325/200977016-912a646c-5a39-46bd-83a0-5d16d9c997d4.png)
Before/after game load (pre-game loading json was restored using devmode)

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
