### ISSUE TITLE
Cant Delete Vehicle

### ISSUE THREAD

**Issue by owenc2088** [DonBruce64/MinecraftTransportSimulator#142]
I have built a couple of vehicles now. but i cant find a way to actually delete these. I've tried left clicking all over the vehicles multiple times. the most I've achieved is popping the tyres on a plan. I have tried to look for a manual and searched as best as i can but this seems to be eluding me. I've even tried just blowing them up with tnt but now i just have a bus sat in a crater.

**Comment by TheOddlySeagull** [comment]
Use the wrench from MTS, and shift right click the vehicle, it’ll be destroyed and dropped

**Comment by DonBruce64** [comment]
Incorrect.  It's shift-left-click, or sneak-attack, that drops the vehicle.  Right-clicking is used to interact with parts and add instruments.  @owenc2088, you'll need a wrench to perform this action.  Also, there is an in-game manual.  Did you not find that in the creative inventory?

**Comment by DonBruce64** [comment]
Assigning Bug label for now.  Will re-evaluated based on user's response, or lack therof in one week.

**Comment by TheOddlySeagull** [comment]
Oof, sorry, I didn’t have any mouse under my hand, I got confused :x

**Comment by owenc2088** [comment]
Hey guys. It's just me being an idiot It never occured to me that the manual would be in-game. I was trying to find one on the net at source of download 🤣 haha just ignore me.  All correct now with the mighty spanner!
