### ISSUE TITLE
subParts on parts placed on the Ground have issues being placed and removed.

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1421]
When a part is placed on the ground, it doesn't accept parts to be placed on it consistently.

**Comment by DonBruce64** [comment]
Do the hitboxes if you do a F3+B show up properly?  Does it depend on the direction of rotation of the part?  I'd like more input if you could.

**Comment by DrprofLuigi** [comment]
With the engine stand, the holobox shows up, but the part can't be placed.
![2022-11-12_15 32 43](https://user-images.githubusercontent.com/36775575/201498679-be1227a5-e3c0-46cb-a1ae-048c118c4c86.png)

With the tire machine, I can place the wheel and remove the tire, but then I can't remove the rim or install a tire.
![2022-11-12_15 32 49](https://user-images.githubusercontent.com/36775575/201498683-b2cccb13-6864-422b-9375-8acac37e31ae.png)
![2022-11-12_15 32 51](https://user-images.githubusercontent.com/36775575/201498684-aee6a3bd-a286-40ae-98d4-7d10efe8fd67.png)
![2022-11-12_15 33 59](https://user-images.githubusercontent.com/36775575/201498693-255fc889-7767-45c0-902f-39c9fc59d7ed.png)

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
