### ISSUE TITLE
[BUG] You can lock wheels, and presumably any parts that aren't seats or interactable.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1422]
This does _not_ lock the main vehicle, and leaves you with a key that is useless. Thankfully last I checked there is a recipe in the base mod to fix that, but nevertheless it's an issue in my eyes seeing as how it doesn't lock the vehicle, and can (and has) left a couple users confused.

**Comment by DonBruce64** [comment]
New feature.  Fixes people stealerizing wheels.  Really popular in Detroit.  But I can change it.  If I have to.  I guess.

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
