### ISSUE TITLE
! READ ME BEFORE YOU REPORT A CRASH !

### ISSUE THREAD

**Issue by Elephant1214** [DonBruce64/MinecraftTransportSimulator#1424]
Let me start by making it clear that **downgrading is not a fix for issues**.

Now to the actual stuff that this was created to address.

1. If your game crashes and you get an access exception error, it is most likely caused by outdated mods and not an issue with Immersive Vehicles. Be sure that all of your mods are up-to-date before reporting a crash with this error.

2. The game crashes when dependencies for mods are missing because of Forge things and doesn't tell you that that's what happened until you look at the latest log. If you see the below error in a crash report, it means you're missing mods. Currently not 100% sure how to fix this one, but [this 22.3.0 jar might fix it](https://cdn.discordapp.com/attachments/407041732988108810/1041506576260931634/Immersive_Vehicles-1.12.2-22.3.0.jar); let me know if it does or not. The changes in this jar should be included in all versions built after 2022/11/03.

```
java.lang.NullPointerException: Initializing game
	at net.minecraft.client.gui.GuiMainMenu.handler$zza000$addCustomSpMpButtons(GuiMainMenu.java:727)
	at net.minecraft.client.gui.GuiMainMenu.func_73969_a(GuiMainMenu.java)
	at net.minecraft.client.gui.GuiMainMenu.func_73866_w_(GuiMainMenu.java:185)
	at net.minecraft.client.gui.GuiScreen.func_146280_a(GuiScreen.java:478))
```

**Comment by DonBruce64** [comment]
Made obsolete as of 22.4.0.
