### ISSUE TITLE
[BUG] Game crashes whenever I open gun-bench

### ISSUE THREAD

**Issue by InstSnipe** [DonBruce64/MinecraftTransportSimulator#1425]
https://paste.ee/p/yzH5O

**Comment by DonBruce64** [comment]
I can't get that site to show me the whole report.  Please attach it to this ticket.

**Comment by InstSnipe** [comment]
that should show the full log, are you asking for the crash log specifically?

**Comment by DonBruce64** [comment]
Either or.  The full log shows the crash report at the end usually.

**Comment by InstSnipe** [comment]
[crash-2022-11-15_21.02.09-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10013185/crash-2022-11-15_21.02.09-client.txt)

**Comment by DonBruce64** [comment]
You're using an obsolete version of IV.  Please update, as that crash has been fixed already.  See ticket #1325

**Comment by InstSnipe** [comment]
oh alright, sorry for the trouble, thank you :)
