### ISSUE TITLE
Rotation Bug on destroying and placing

### ISSUE THREAD

**Issue by DrKevin111** [DonBruce64/MinecraftTransportSimulator#1426]
Problem: Orientation of picked up objects don't place facing the same way as originally placed. Occurs to any props in survival.

Possible cause: NBT tag of orientation is kept on destruction of the props.

Video referable [here](https://cdn.discordapp.com/attachments/407041732988108810/1024850712624123966/20220928_18-00-05.mp4)

Minecraft Version : 1.12.2
Immersive Vehicle Version: Immersive Vehicles-1.12.2-22.1.0.jar

(Note: Publishing this late, but still occurs on version 22.3.0 of Immersive Vehicles)

Packs Included:
  - Immersive Vehicles (MTS/IV) - Official Content Pack
    - MTS_Official_Pack_V23.jar
  - [Immersive Vehicles] IAV Parts pack
    - IAV_Parts_Pack_Beta_15.jar
  - [Immersive Vehicles/IV/MTS] VEB Automobilwerke Schwikau Military/Civilian
    - Automobilwerke_Schwikau_VEB-1971_february_1st.jar
  - [MTS/IV] immersive Poker's Garage
    - immersive_Pokers_Garage_1.1.jar
  - Blu's Sign Pack [MTS/IV]
    - Blus_Sign_Pack_V1.2.0.jar
  - Golden Airport Pack (GAP) [Immersive Vehicles content pack]
    - Golden Airport Pack [IV] 3.2.6.jar
  - Hero Aviation Helicopter Pack [IV/MTS content pack]
    - Helicopter_Pack-2.7.0.jar
  - Immersive Vehicles Trin Civil Pack V2
    - IV_Trin_Civil_Pack_V2.6.1.jar
  - Immersive Vehicles Trin Civil Pack V3
    - IV_Trin_Civil_Pack_V3.18.0.jar
  - Immersive Vehicles Trin Part Pack
    - IV_Trin_Part_Pack_2.20.0.jar
  - Kadwin Jurassic Park Vehicles Pack [MTS/IV]
    - MTS_Kadwin_JP_Vehicles_Pack_3.2.jar
  - Potato Vehicle Industries
    - Potato-vehicle-Industries-BETA2.jar
  - UNU Civilian Vehicles [MTS/IV] [IR] (immersive cars trucks planes & trains)
    - UNU Civilian Pack [MTS] 1.12.2-21.3.0-5.3.2.jar
  - UNU Parts Pack [MTS]
    - UNU Parts Pack [MTS] 1.12.2-21.3.0-5.1.4.jar

**Comment by DonBruce64** [comment]
That... is an odd one!

**Comment by DrKevin111** [comment]
Also, just wanted to state that this happens to anything that can be placed on the ground.

**Comment by DonBruce64** [comment]
All ground placement things use the same code, so that makes sense.  Should be easy to fix when I get a chance.

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
