### ISSUE TITLE
[BUG] engine Creative detection runs off the last person to get in a seat, not off the controller seat

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1431]
as it says on the tin. this should be running only on controller seats, shouldnt it?

**Comment by DonBruce64** [comment]
It should.  Will fix.  I'm assuming if a survival person gets in the driver seat, and a creative person gets in the passenger seat, the engine becomes creative?  What exactly happened that brought up this bug?

**Comment by LauraDarkez** [comment]
thats one of two things that can happen. the other is a driver is already in the seat in creative, and the passenger gets in and the vehicle engine becomes survival until the creative person either switches seats or gets out and gets back in

**Comment by DonBruce64** [comment]
Unable to reproduce, suspect server setup error.
