### ISSUE TITLE
[BUG] Missiles track players inside the vehicle that is firing it

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1432]
gun points anywhere i am aiming but when it fires the missile goes in the direction of the seat that the passenger is sitting in

**Comment by DonBruce64** [comment]
Is this a hand-held missile launcher, or one on the vehicle?  Cause I'm pretty sure it doesn't happen with Hashim's stuff.

**Comment by LauraDarkez** [comment]
thats cause hashims A: doesnt have yaw or pitch. B: doesnt go on vehicles with multiple player seats

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
