### ISSUE TITLE
[BUG/OS] Every item/block in the core mod "pack" is free.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1433]
You heard me right. All of em, each core mod crafting table.
This isn't as problematic until you realize that the decor table can craft the IVV 3D printer, which can craft anything in the mod... (ergo by extension, everything in the core mod) or the fact that, even without IVV, all of the items (jumper cables, battery chargers, etc) are free if you craft the compy crafting bench.

I'll get to this when I can so just slap an Outsourced sticker on this, but uhhh... Yeah. They're free.
![image](https://user-images.githubusercontent.com/53581325/204106437-d8e182a9-4ad1-48bd-ae69-8a5df4f749a6.png)

**Comment by DonBruce64** [comment]
Odd, they don't have a recipe, so they shouldn't be in the table at all...  Tis probably due to the code with the multiple recipes.

**Comment by boot2big** [comment]
Weeell that would fix it too then, I'll still get onto setting up some recipes for them anyways though. No reason they shouldn't be craftable in a bench methinks?

**Comment by DonBruce64** [comment]
There's no reason specifically, no.  It's more that you'll expect you have to make them via the standard bench and thus having them be there, and in the part benches is somewhat redundant.  So I never bothered to make recipes for them.

**Comment by DonBruce64** [comment]
Fixed in 22.4.0.
