### ISSUE TITLE
[Bug] All sounds plays at any distance. 

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1435]
You can hear any sound from any distance as long as the source is in the loaded chunk. The sounds never fade away.
Tested on clean new IV version from discord server without sound config PR (Immersive_Vehicles-1.12.2-22.4.0-BETA1)
Can be reproduced with any pack, but sirens and other looping sounds are easier to test on.

https://streamable.com/dh44j9

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
