### ISSUE TITLE
[Bug] Added parts on vehicles removed when failing to place

### ISSUE THREAD

**Issue by DrKevin111** [DonBruce64/MinecraftTransportSimulator#1436]
Problem: When attempting to place a vehicle too close to blocks, the added parts on the vehicle will remove themselves when later successes of spawning occur.

Video Evidence [Here](https://cdn.discordapp.com/attachments/407041732988108810/1048367659105910924/20221202_14-32-51.mp4):
https://cdn.discordapp.com/attachments/407041732988108810/1048367659105910924/20221202_14-32-51.mp4

Version: Minecraft 1.12.2
Immersive Vehicle Version: Immersive Vehicles-1.12.2-22.3.0.jar

Packs Included:

- Immersive Vehicles (MTS/IV) - Official Content Pack
     + MTS_Official_Pack_V23.jar
- Immersive Vehicles Trin Civil Pack V2
     + IV_Trin_Civil_Pack_V2.6.1.jar
- Immersive Vehicles Trin Civil Pack V3
     + IV_Trin_Civil_Pack_V3.19.0.jar
- Immersive Vehicles Trin Part Pack
     + IV_Trin_Part_Pack_2.21.0.jar
- UNU Civilian Vehicles [MTS/IV] [IR] (immersive cars trucks planes & trains)
     + UNU Civilian Pack [MTS] 1.12.2-21.3.0-5.3.2.jar
- UNU Parts Pack [MTS]
     + UNU Parts Pack [MTS] 1.12.2-21.3.0-5.1.4.jar

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
