### ISSUE TITLE
[Enhancement] No Variable Exists for if a part is placed on ground/not placed in a part slot

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1437]
I had been under the impression that such variable already existed but i cant find it anywhere

**Comment by DonBruce64** [comment]
I can see this being useful for gun mounts.  Will add.

**Comment by LauraDarkez** [comment]
i had thought you said that a variable for such would be implemented with the addition of being able to place parts on the ground, but i guess i had been mistaken?

**Comment by DonBruce64** [comment]
I do recall saying that I would add such a thing, but looking though the code I confirm that I did not.   I must've forgotten.

**Comment by DonBruce64** [comment]
Implemented in 22.5.0.
