### ISSUE TITLE
[Enhancement] variable that detects when innerWindows is true/false in the config rendering screen

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1438]
![image](https://user-images.githubusercontent.com/53153740/205659231-200fd088-a3b3-4455-a3eb-269ff85db33a.png)

**Comment by DonBruce64** [comment]
I'll add this, though do expect the config variable that's in the system for the other config variable to change names if it doesn't start with config_

**Comment by LauraDarkez** [comment]
i believe it does start with config_

**Comment by DonBruce64** [comment]
Implemented in 22.5.0.

**Comment by LauraDarkez** [comment]
im afraid that this feature is not working in the official release, that or the variable is wrong in the wiki

**Comment by LauraDarkez** [comment]
so i found out something. the issue has to do with how translucency, visibility and clamps all work now
