### ISSUE TITLE
Intractable_barrel becomes unusable if set below 10.000mb capacity

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1439]
I noticed this bug when trying to lower the OCP-Bell47g's external tank fuel capacity from 30.000 mb to 7.000mb.
When loading up the game, the tank showed either 300/0 mb (filled tank) or EMPTY (empty tank). 
It could not be filled via bucket or hose, as it normally would be the case.

When changing the "inventoryUnits": back to 1.0, the tank was usable again and i could fill it to the brim with fuel.

Setting "inventoryUnits" < 1.0 makes the tank unusable and in-intractable, capping absolute min. capacity at 10.000 mb

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
