### ISSUE TITLE
[Enhancement] handHeldHandOffset: [X.x,Y.y,Z.z]

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1440]
this parameter would allow you to make the hand-origin reference point be set to a specific point of a handheld gun, rather than being stuck in reference to the origin. would allow for better use of the playertweaks arm when it comes to the use of handheld guns, since things like conventional fire extinguishers suffer from having the arm at an unusual angle when it should be relative to the handle.
![2022-12-06_15 24 21](https://user-images.githubusercontent.com/53153740/206015472-2acb896c-ee5c-4975-80f9-97d5b73eddcd.png)
would give guns a defined point to reference the hand to, which is beneficial overall to convention-users

**Comment by LauraDarkez** [comment]
if this is something that could be relatively simple, i might be willing to pr it myself, as long as im directed to what parts of the code i should be looking at

**Comment by DonBruce64** [comment]
But you already have this?

handHeldNormalOffset – The offset where this gun will be when held normally by the player. An offset of 0,0,0 will render the gun in the center of the player's right shoulder rotation point. For reference, this is 0.3125 blocks to the right, and 1.375 blocks from the bottom-center of the player's feet.

**Comment by LauraDarkez** [comment]
that isnt though. handheldNormalOffset is the reason the arm is at the weird angle that it is at. its in reference to the origin of the gun

**Comment by LauraDarkez** [comment]
![image](https://user-images.githubusercontent.com/53153740/206236899-73f10fec-0a09-447b-9f74-158664de0616.png)
origin of this extinguisher is at the bottom so that it can be conventionally placed on vehicles like crates and barrels. this makes sense from a convention standpoint. but as a result the handHeldNormalOffset has to be very low on the Y axis. this results in the arm being angled down very low when it SHOULD be angled to the handle instead of the base

**Comment by LauraDarkez** [comment]
![image](https://user-images.githubusercontent.com/53153740/206243753-92ea47d4-0585-41f0-91f6-9e50c06964f2.png)
the only way to get the last image as a result without adding this parameter is to put the gun's origin here instead, which isnt as nice when it comes to convention

**Comment by DonBruce64** [comment]
Ah, so you're saying that you'd rather have the hand-held offset adjust the position of the gun in the player's hands, rather than the position of the hand relative to the 0 position of the gun?  Or should I have both and call this one something different?

**Comment by LauraDarkez** [comment]
i gave you a name for this parameter, have both

"handHeldHandOffset"

**Comment by DonBruce64** [comment]
Implemented in V22.6.0.
