### ISSUE TITLE
[BUG] Blank/missing description entries still result in a description entry being written, just an empty one.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1444]
Could've sworn the previous behavior to this was that the item just, wouldn't get a description? Similar to vanilla items.
![image](https://user-images.githubusercontent.com/53581325/206587363-71375766-a386-49bc-89db-ccd3dca59543.png)
![image](https://user-images.githubusercontent.com/53581325/206587374-4d7e0a4e-dffe-4c16-8452-62273c1cfca0.png)
![image](https://user-images.githubusercontent.com/53581325/206587386-4a21cbfd-dcca-421f-b6d4-33e9f5f29512.png)

Debatably applicable to weapons, still looks a bit off though.
![image](https://user-images.githubusercontent.com/53581325/206587490-aa6cbe4d-df8d-47c0-b412-fa35996dd901.png)
![image](https://user-images.githubusercontent.com/53581325/206587500-4052cf69-0c54-4293-b7b4-3a82a5c494a6.png)
![image](https://user-images.githubusercontent.com/53581325/206587515-5f9a0979-1b7e-4b15-b03d-d7c18e6b220b.png)
![image](https://user-images.githubusercontent.com/53581325/206587531-dd5f1a03-9d82-40bf-bd1d-75ffd1e4a78a.png)

**Comment by boot2big** [comment]
![image](https://user-images.githubusercontent.com/53581325/206587633-0e132672-e73a-4346-a804-86ec818332c3.png)
Additional important note, I don't think this is because of LCs or blank existing "description" entries. There ain't even a description entry in this json, before or after devmode!
All it does is clean up the json.
![image](https://user-images.githubusercontent.com/53581325/206587775-cad6748a-771c-4b5e-a6fd-2a382e970617.png)
![image](https://user-images.githubusercontent.com/53581325/206587787-f1f70fd8-785c-4d0c-8dae-c5a87431726e.png)
(And arguably to no effect)

**Comment by DonBruce64** [comment]
Interesting... Will fix though!

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
