### ISSUE TITLE
turret_yawing Variable not work properly as they should after vehicle is move from its spawn point

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#1445]
this turret_yawing variable used on Type 74 turret which make it play sound while turret moving 
but after it move out from start point it keep playing constantly 
as in this video
https://user-images.githubusercontent.com/79125581/206713222-5f3aab41-47ce-481d-8088-ed20f8ee924a.mp4

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
