### ISSUE TITLE
[BUG] Weapon cooldown doesn't behave correctly (I think)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1447]
![image](https://user-images.githubusercontent.com/53581325/206828221-37edca1d-0b96-4bbc-8e38-2403d792a766.png)
I... don't think that's 30 ticks?
![image](https://user-images.githubusercontent.com/53581325/206828237-28ee3bc1-55d3-47bb-8c7b-f03ecf186fcd.png)
![image](https://user-images.githubusercontent.com/53581325/206828240-4b09ace2-4694-4a4a-b459-0af3c1f09e33.png)

https://user-images.githubusercontent.com/53581325/206828265-08b26b54-6f77-4403-b8f2-b92320f24bb4.mp4

**Comment by DonBruce64** [comment]
Yeah, I have bad code in there somewhere.  MC is funky with how it handles attack speed, and I probably got it wrong.  Will fix when I get time, but that might not be for a while as I don't feel like digging into MC code more now that I've spent time in the 1.16.5 mess.  So expect this bug to linger for a while.

**Comment by DonBruce64** [comment]
So, come to find out MC doesn't allow you to change the speed between attacks.  When it changes attack speed, it's the delay between full-strength attacks, not the delay between total attacks.  That being said, my math is indeed wrong on the latter, so will fix.

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
