### ISSUE TITLE
Item unloader crashes game when placing hopper under it

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1448]
MTS Official pack V24

Don -> "Nah, I did a stupid and told Forge my block could handle items, but I didn't give it the right code to actually do so."

Crashlog:
[crash-2022-12-10_04.43.54-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10200160/crash-2022-12-10_04.43.54-server.txt)

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
