### ISSUE TITLE
[BUG] Jerrycans allow you to add any fluids to any engine, MTS/IV has no idea what to do when an engine with the wrong fluid starts and causess the game to crash.

### ISSUE THREAD

**Issue by BOTFerris** [DonBruce64/MinecraftTransportSimulator#1451]
The title pretty much says most of the bug. Pumps don't allow you to put (for example) water in a gasoline engine, but with a jerrycan, you can do just that. When you start the engine with a fluid other than the required one (make sure you aren't in creative when doing this) MTS/IV freaks out and crashes, taking your game/server down with it.

**Comment by DonBruce64** [comment]
I'm honestly surprised nobody caught this before now.  Will fix right now and post build on Discord with fix when complete if you want to get it there to recover your server.  Just ping me.

**Comment by BOTFerris** [comment]
> I'm honestly surprised nobody caught this before now. Will fix right now and post build on Discord with fix when complete if you want to get it there to recover your server. Just ping me.

Thank you,  [Also the server I experienced the bug on was not mine :)]

**Comment by DonBruce64** [comment]
Fixed in 22.5.0.
