### ISSUE TITLE
Missing-texture-break particle bug

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1452]
In case of bullets and bullet_hit_block, the break particle usually pulls its texture from the block that is hit by a projectile.
I some cases though, the missing texture texture appears when hitting blocks from a certain angle/position.

<img width="881" alt="fawwewe" src="https://user-images.githubusercontent.com/97041048/207350644-0b18e876-c6f8-419d-ad57-70c34b7f41bb.png">

"Cause I'm wondering if it's grabbing the air above the block if you hit the top half." - Don, regarding the error

Full auto smokeless FT for testung purposes:
[full_auto_ft.jar.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10218574/full_auto_ft.jar.zip)

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
