### ISSUE TITLE
Unable to edit text on vehicles

### ISSUE THREAD

**Issue by RealAaeroO** [DonBruce64/MinecraftTransportSimulator#1457]
We can edit text on parts but text that comes with the vehicle itself (like bus destinations signs) cannot be edited.

**Comment by DonBruce64** [comment]
Please provide mod version, pack version, and pack used, and vehicle used.

**Comment by RealAaeroO** [comment]
> Please provide mod version, pack version, and pack used, and vehicle used.

IV version: 22.3.0
Vehicle : UNU Scarab & Solaris Urbino 12
Pack/s : UNU civilian & Blocky Rage

**Comment by DonBruce64** [comment]
Update your mod, this was addressed in #1413 .

**Comment by RealAaeroO** [comment]
alright
