### ISSUE TITLE
[BUG] .json format item models do not support non-square (but Po2 respectful) textures

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1458]
This indirectly seems to be a kick in the gnads for animated item textures (not the same as an animated model), since animated textures are literally width resolution, times frames equals height resolution.

**Comment by DonBruce64** [comment]
IIRC, item models don't support this natively?  You have to use a square texture for all item models, and if you want to animate them, you do so by switching the texture out, not a-la-blocks via .mcmeta files.  Correct me if I'm wrong, please.  Either way, I don't do anything with the .json files from IV's end, I just forward them to MC.  But I could have a funny bug somewhere.

**Comment by boot2big** [comment]
Well I got some nasty words for BlockBench if they aren't supported natively, their UV editor automatically adjusts to account for this! And it even lets you play the animation!! Will have to test this further, perhaps with some sorta fancy resource pack.

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.

**Comment by boot2big** [comment]
May still be an issue for horizontally-offset textures VS vertical offset textures?

https://github.com/boot2big/immersive_vehicles_vanity/blob/main/out/Immersive%20Vehicles%20Vanity-1.12.2-2.3.0.jar

Affects the picket sign

**Comment by DonBruce64** [comment]
IIRC, those offsets aren't supported by MC?
