### ISSUE TITLE
[BUG/ENHANCEMENT?] Handheld gun animations do not seem to account for left-handedness.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1459]
Not entirely a problem since, the only actual visible issue is that your left-handed player holds guns in their right hand.
As a result I don't see this as a major issue, since it would probably require some less than fun changes to handhelds and because it doesn't actually majorly affect gameplay or appearances...

**Comment by DonBruce64** [comment]
Is player primary hand a setting now?  I wasn't aware it was...

**Comment by boot2big** [comment]
It is, apparently. Like I said, not a huuuge issue (at least IMO) if this goes untouched. Besides, aren't some guns made specifically right-handed anyways?

**Comment by DonBruce64** [comment]
Easy enough for me to add this, I'm flagging it as a bug, but a backburnered one at that, since I'll hafta add hooks for the other arm on the player model to rotate it.

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
