### ISSUE TITLE
Switching F5 while seated on a placeable part crashes the game

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1460]
[crash-2022-12-18_19.21.32-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10254392/crash-2022-12-18_19.21.32-client.txt)

When making a part placable which happens to have a seat / seat function, place that on the ground, sitting in it and pressing F5 twice, the game crashes.

To test this ive made the OCP seat placable:
I can sit in it and switch to the 3rd person back-view perspective. 
As soon as im switching to 3rd person front-view perspective, the game crashes.

I can sit in the seat in 3rd front when i switched to 3rd front before sitting down.

when placing the same seat on a vehicle instead if the ground, i can freely switch between perspectives.

Have a part > make it placeable > put seat on placeable part > sit > switch to 3rd front perspective > crash

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
