### ISSUE TITLE
"proximityFuze" parameter update required

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1461]
Proxy ammo only detects blocks in its current state, but not entities.
Entities are only detected when turnRate is added.
This requires a lock on target, which makes it impossible to lead shots which in return makes proxy unusable for non-missile projectiles.

Don: "Ah, you are right.  It only checks for the target entity being close.  I can make it check for all entities, but keep in mind it'll be a hair laggy if there are a lot and the bullet is going fast."

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
