### ISSUE TITLE
Camera doesn't work when they're on a gun's subpart

### ISSUE THREAD

**Issue by Kadwinflo** [DonBruce64/MinecraftTransportSimulator#1463]
CameraObject do nothing when they are on a gun's subpart (like a scope). also, the textures of the subparts are too dark

**Comment by boot2big** [comment]
TBH I've simply gone with having a "one size fits all" scope with four different model states (shortrange,medium range,longrange, invisible) and simply having the gun itself pick which scope to use, as well as having the cameraObject on the gun itself.

Perhaps try going with this? You can have the gun ping its subpart for a constantVariable, to use a different camera depending on which scope is installed. I was just lazy and wanted something clever and simple to use!

**Comment by Kadwinflo** [comment]
> 

i'll be curious to see your files because i haven't understood everything (i've limited english knowledge). how it is modular ? my goal is to make a modular system.

**Comment by boot2big** [comment]
See https://github.com/boot2big/immersive_vehicles_vanity, though a release is imminent for the winter holiday season... :wink:

**Comment by Kadwinflo** [comment]
> See https://github.com/boot2big/immersive_vehicles_vanity, though a release is imminent for the winter holiday season... 😉

i'll check. also, i'm hyped ! IVV is on my modlist since i came across

**Comment by boot2big** [comment]
You can have more than one type of scope, the main thing is that this part system has a more automatic-adjustment sort of system.
You could have a small, medium or long range ACOG scope (yes, you don't needa tell me that it isn't how ACOGs work), or an invisible one if the gun model already has an ACOG scope.
In fact, all the ACOG really needs to do is be told that it should be visible or invisible (by default visible) and to have its own constant variable, that the gun uses.
So, you could have a regular zoom scope and ACOG scope camera object.

**Comment by DonBruce64** [comment]
I do need to get this fixed though, as I can see others wanting to make their own scopes.  So you could put a not-IVV scope on an IVV gun and it'd work.  Though why you'd do that I don't know, but IV has always let you do silly things, like put turrets on turrets, or put tiny tires on a SUV.  I still need to fix this, and expect it to work in future versions.  Though if someone wants to figure it out today, CameraSystem.class is where to look.

**Comment by Kadwinflo** [comment]
> I do need to get this fixed though, as I can see others wanting to make their own scopes. So you could put a not-IVV scope on an IVV gun and it'd work. Though why you'd do that I don't know, but IV has always let you do silly things, like put turrets on turrets, or put tiny tires on a SUV. I still need to fix this, and expect it to work in future versions. Though if someone wants to figure it out today, CameraSystem.class is where to look.

exactly what's i want in fact. so my scopes could be used on other guns =)

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
