### ISSUE TITLE
[BUG] Desync between server and client can result in ghost missiles

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1464]
Sprung up from #1462 
![Screenshot from 2022-12-20 15-09-36](https://user-images.githubusercontent.com/53581325/208757246-32889124-18ed-444e-9cf7-e64b1d9627ac.png)

**Comment by boot2big** [comment]
Missiles tracking on the client but not the server. VERY annoying!! I can manage to miss something while pointing my cursor right at it!!

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
