### ISSUE TITLE
[Enhancement/Reminder] change the wheelbase code

### ISSUE THREAD

**Issue by Lila-Bat-Huntress** [DonBruce64/MinecraftTransportSimulator#1466]
https://discord.com/channels/232316230852280320/789711773132783636/1054765726449270864

i hope i did this ticket correctly

**Comment by DonBruce64** [comment]
Marking this as a bug, since technically turning should be based on the wheelbase normally, not whatever the center of mass/rotation is for the vehicle.

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
