### ISSUE TITLE
"Exception ticking world entities" bug causes crash

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1467]
[crash-2022-12-20_18.18.07-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10279015/crash-2022-12-20_18.18.07-server.txt)
<img width="747" alt="fweffwf" src="https://user-images.githubusercontent.com/97041048/208941875-cb066cce-7c76-47aa-bff4-4293a6a3af63.png">

**Comment by DonBruce64** [comment]
Unable to reproduce by ticket issuer.
