### ISSUE TITLE
IV 1.12.2-22.6.0-BETA causes chunk-unloading + other visual bugs when looking straight up in a vehicle

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1469]
https://user-images.githubusercontent.com/97041048/208992334-a85bbb23-5ff3-4cdd-a513-ea0f08270475.mov

<img width="828" alt="deaedq" src="https://user-images.githubusercontent.com/97041048/208992719-16836339-a28e-47fc-9b35-db61ce8a8cfd.png">
<img width="844" alt="QDwdqDW" src="https://user-images.githubusercontent.com/97041048/208992722-342cb07a-c8b1-41f5-b9a5-39b620807cad.png">

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
