### ISSUE TITLE
[Enhancement] Sub-particles

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1471]
Particles that can be emitted from other particles.
For example it can be used to make burning or smoking debris or flares with trails

**Comment by LauraDarkez** [comment]
or fireworks that do that multiplying thing

**Comment by DonBruce64** [comment]
I can see this being useful.  Will add sometime.

**Comment by DonBruce64** [comment]
Implemented in V22.6.0.
