### ISSUE TITLE
[Bug] Parts on the walls

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1474]
Would've been nice if we could put parts not just on a ground, but on walls too.
Flags, posters, all kinds of hanging stuff.

**Comment by DonBruce64** [comment]
You should be able to do this just by clicking the block?

**Comment by Wartich** [comment]
they are getting placed on top of the block

**Comment by DonBruce64** [comment]
Ah, that's a different issue.  I can fix.  If you click decor on the side of the block do they go on the side or top?

**Comment by Wartich** [comment]
top

**Comment by Wartich** [comment]
https://streamable.com/ouajky

Demonstration

**Comment by DonBruce64** [comment]
Looks like my click code assumes top.  Will fix.

**Comment by Wartich** [comment]
i remember similar issue with fire and water bullets

**Comment by DonBruce64** [comment]
So, decor does NOT place on the wrong side of the block.  This is only for placable parts.

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
