### ISSUE TITLE
Advanced Rocketry's Iron Rod vs IV Wrench recipe conflict

### ISSUE THREAD

**Issue by polyzium** [DonBruce64/MinecraftTransportSimulator#148]
![image](https://user-images.githubusercontent.com/22579935/58590777-8a9b7200-826d-11e9-9477-5ee89aeca73a.png)
![image](https://user-images.githubusercontent.com/22579935/58590802-97b86100-826d-11e9-9026-f507acc1d1e5.png)

**Comment by DonBruce64** [comment]
I'll look into this as it's something that I can see conflicting with other mods, but I'm not sure of any alternate recipes that I can use in place of this one.  Got a suggestion for something to change it to?

**Comment by TheCactus27** [comment]
iron pressure plate at the end?

**Comment by polyzium** [comment]
Could this work?
![image](https://user-images.githubusercontent.com/22579935/58618025-38d50500-82ca-11e9-9047-64a41c069e08.png)
Or you can split it into 2 recipes

**Comment by DonBruce64** [comment]
@polyzium I think the Y formation you gave is quite good.  Does that conflict with anything that you know of?

**Comment by polyzium** [comment]
@DonBruce64 So far I haven't saw anything that uses this recipe.

**Comment by DonBruce64** [comment]
Changed in V14.3.1.
