### ISSUE TITLE
Hud Hitch Rework

### ISSUE THREAD

**Issue by mic2139** [DonBruce64/MinecraftTransportSimulator#1481]
I originally brought this up on discord, but I thought I'd propose it more cleanly here

The current usage of space for hitches on the HUD is *highly* inefficient, ignoring the fact it dedicates a button for every connection. This makes the construction of any sort of train more tedious when you consider they are very frequently over 6 or so cars long. I think that improvement could occur in 2 different ways. One would be maintaining strictly one button for every link, rather than the two which i see sometimes (one seemingly lit up and one dim, describing the same existent link), upgrading the carriage capacity by at least one, to this I see no drawbacks. Preferably, I would advocate for the removal of every individual link being displayed there, and instead have permanent buttons to "dissolve all" connections between every trailer in the consist, and then switches for the status each of the driving vehicle's connections, just to remove the connection between it and the entire rest of the train. This could total 3 permanent buttons if the vehicle has 2 hitch points for instance. Additional switches would then only be those that are the *current* vacant slots anywhere in the consist, the switch for it disappearing if a connection is made there. In this hypothetical, if we had thomas the cursed steam train with FOUR carriages infront and behind him respectively (totalling 8 additional carriages), you would still expect to see 5 buttons for this on your dash board, and this number would never be exceeded for trains and their trailers.  (one to delink all connections, two for front and back hitches of thomas, and two for the very vacant ends of the train, so the frontmost and endmost carriage. I refer those who want to fine control absolutely every connection to establish hitboxes for this purpose, as this is far less relevant than simply connecting the carriages.

**Comment by DonBruce64** [comment]
I really do need to take a look at trailers for trains.  Lemme look into the code feasiblity of this.  I know that I can at least prevent duplicate connection buttons by being smart about not adding hookup and hitch connections.  But other than that I'd need some input from other PAs as I need to know how they structure their packs for trailers.

**Comment by boot2big** [comment]
Input on trailers and how IVV uses em:

I uhhhh, do not use 'em much. Obviously the locomotive uses 'em like hell, since you can make and drop a literal train with it.
Aside from that, I really only use the trailer system for vehicle towing (see tow truck bed and winch) and a basic trailer hitch part system (right now you can really only turn vehicles _into_ trailers, I gots to make an actual U-Haul trailer for it)

Input from Trin and UNU would probably be more helpful.

**Comment by DonBruce64** [comment]
Given the new HUD system, one can configure trailers with more granularity.  And for trains, the HUD shouldn't be used for anything except the main couplers of the locomotive.  For cars and such, the hitbox-snap-connectors should be used, as that's literally what they're designed for.  Calling this Good Enough until we get more folks using trains and get more traction on traction engines.
