### ISSUE TITLE
Sometimes front and rear wheels are combined into the same wheel box...

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1484]
![Here is a picture](https://i.imgur.com/XTyjly3.png)

The top UNU Baron has the blue wheel box in the middle, while the bottom one has the boxes on both wheels.

![This is likely due to how the suspension is animated, the wheel sometimes pivots in front of z=0.](https://cdn.discordapp.com/attachments/927056637037019216/1058303402066579526/2022-12-30_00.38.09.png)

I would suggest one of two solutions:
The wheel calculation is not dynamic, so what wheel is in which 'region' is determined by placement only. The other solution would be to have a manual override to hard-define which 'region' the wheel should be tied to..

**Comment by DrprofLuigi** [comment]
This appears to happen even on vehicles that only have vertical suspension travel. My guess is that this has something to do with how my frames are set up.

I think the best solution would be to allow the option to hard-define a wheel 'slot' as part of a certain wheel group.

[image](https://media.discordapp.net/attachments/927056637037019216/1065166567488376853/2023-01-18_02.06.41.png?width=1078&height=559)

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
