### ISSUE TITLE
[ENHANCEMENT] Animation variable for when the user is aiming down a handheld gun's sight/scope/etc.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1488]
Variable for when holding RMB with a gun!
`gun_handheld_aiming` perhaps

Would especially be useful for unifying, conventifying and efficiency on gun scopes as instead of having a cameraObject on the gun itself, each scope just has its own cameraObject that refers to "parent_gun_handheld_aiming" (as well as sounds linked to gun_handheld_aiming, or animations, etc.)

**Comment by DonBruce64** [comment]
EZ, probably can be PRed.  Goes to bottom of pile under current nasty bugs because of that.

**Comment by boot2big** [comment]
That's fine, this can go on the backburner even. The one main use I'd thought of besides general aiming animations/sounds turns out to have been fixed with another ticket, no harm if all the bugs get squashed and the more useful enhancements get done first. :+1:

**Comment by DonBruce64** [comment]
Implemented in V22.6.0.
