### ISSUE TITLE
Handheld Gun Cameras Render Third Person Playermodel

### ISSUE THREAD

**Issue by Dubbington** [DonBruce64/MinecraftTransportSimulator#1489]
When using cameras on non-vehicle mounted weapons, the camera will render the player as well as either freezing you in place therefore not allowing you to more, or the player will keep moving in a certain direction if they were moving in such direction prior to aiming, thus triggering the camera.

Video example provided.
Immersive Vehicles 1.12.2-22.6.0

https://user-images.githubusercontent.com/75969752/210425453-27c4324d-e5ff-4f61-a9a7-998cd22118e1.mp4

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
