### ISSUE TITLE
[Suggestion (for the future)] Simplification of Json Process.

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#149]
As it is, the current jsoning process has its easy and difficult sections. As the mod progresses, this process may get more difficult for newer modelers. A suggestion, once many of the important features are added, would be allowing the user, in dev mode to place and rotate parts in a special part of dev mode. Using the Little Tiles advanced placement system as a basis for the whole system, when a certain key is pressed, the jsoning system is activated. A GUI could open, where you select the part. Once selected, you would use arrow keys and either in the game or in the GUI, you can move a marker representing the seat into a proper position. A similar system could be done with rotation points, where the marker represents the origin. Similarly, the collision boxes could be done using a scale method once positioned correctly. This idea may be more trouble than it is worth or something that another coder would have to do, but it would make the pack process easier for beginners

**Comment by DonBruce64** [comment]
Collision boxes would be rather difficult to do like this, but moving parts, once the moving hitboxes are established, may actually be possible.  The biggest issue would be selecting the part.  The way Java works kinda prevents hot-swapping parts out.  You could for sure add them and use the system to tweak them, but making new ones would be problematic.

Saving too is an issue, as that requires the JSON to be saved, and you can't save into a .jar file: you can only read from it.  Still, it's not a bad issue.  Will table it for now and see how it works.

**Comment by TheCactus27** [comment]
Kinda late to respond, but for saving, couldn't you reuse the old MTS file and write the Json in that?

**Comment by PearlCGDoesYT** [comment]
I'm thinking about coding a modelling program that uses the TB coords system (maybe not) and maybe make a plugin that aids in making a IV/MTS Json file by allowing that program to make a specific group such as the wheels, engines, extra stuff or make that plugin for certain modelling programs that support plugins

**Comment by DonBruce64** [comment]
Going to close this, as I'm not going to be doing any work on the JSON system.  I'm already in the thick of doing code overhauls and adding features, and making a whole new UI for editing models is far harder than one would think given MC's current systems.  Perhaps I'll do some scripts for auto-generation, but that'll be the extent of things.
