### ISSUE TITLE
[Bug] Plane shaking

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1490]
Planes shake sometimes when you fly straight. I'm sure that you are aware of that issue

https://streamable.com/t4s4w7

**Comment by DonBruce64** [comment]
You have too much lift or elevator area for that plane.  It's a configuration issue, not an IV one.  It's been like that since the MFS days, and happens when you take a plane past their designed physics.  For example, the Trimotor does it around 30 blk/s, but the Eclipse only does it around 50.
