### ISSUE TITLE
[Bug] HEAT projectiles damage changes based on distance

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1492]
Told you about it on discord

https://user-images.githubusercontent.com/46074580/210742534-7f535ca4-0ea8-46b5-8190-3569179bf0ee.mp4

**Comment by boot2big** [comment]
I thought it was based on speed?

**Comment by Wartich** [comment]
And on speed, but HEAT shouldn't be affected anyways

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
