### ISSUE TITLE
Gun firing through VMs/hitboxes

### ISSUE THREAD

**Issue by mic2139** [DonBruce64/MinecraftTransportSimulator#1496]
As an enhancement I was wondering if it would be practical to allow for guns to be fired through VMs or hitboxes. This could allow a few things such as a gun automatically firing when the vehicle does certain things (perhaps an explosion being triggered by the magneto if your car is located in Belfast), or an artillery piece to be operated without sitting on a seat, and instead aimed (i assume this is a feature already based on what Laura said) and fired from 3rd person. This doesn't address actually scoping in for that but good enough for crudely aiming I'd think. Would this feature allow for a gun attached to an engine to be triggered by the vehicle they're mounted on respectively in the same way?

**Comment by mic2139** [comment]
i will be back!!!!! eventually!!!

**Comment by LauraDarkez** [comment]
why did you close this? is it already possible?

**Comment by boot2big** [comment]
I'm all for this actually, I can also think of those secondary "guns" you can install onto other guns, the ones that shoot grenades and stuff. You could even make guns that recursively stack onto eachother for more firepower per LMB, though I would imagine reloading to be quite the bitch even with Steve's Arse of Holding.
![image](https://user-images.githubusercontent.com/53581325/211172688-f3b4e6bb-44d6-475f-bd87-aa6f7c54cb70.png)
