### ISSUE TITLE
[ENHANCEMENT] reloadDelay variable to slow down reloading

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1498]
The amount of time after firing to wait before this gun starts to reload.
Would be mainly useful for single-bullet fed guns that hold more than one bullet since, it isn't going to be easy to stuff that gun with a new round every time you fire. It'd be more efficient to just empty the gun into your enemy and then reload!
Could also be used with those fancier guns with all the moving first-person hands and advanced reload procedures, I think.

If 0, guns reload as they do now.
If not 0, wait until the gun stops firing, and then wait this defined time before trying to reload.

**Comment by DonBruce64** [comment]
Implemented in V22.6.0.
