### ISSUE TITLE
Request: Multiple engines in cars

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#15]
Self-explanatory.

**Comment by DonBruce64** [comment]
Ehh, not really.  There are literally only two cars in the world that have this system, and nobody is making either of them.  I'd have to re-do the entire engine and wheel system to support such a thing, not to mention dealing with multiple drivetrain systems in a single vehicle, and differential thrust for different engines wreaking havoc with the physics systems.

No, methinks this kind of tinkering is best left to Professor Fate and his Hannibal 8...

**Comment by Nianor** [comment]
Which cars even are those? I totally didn't know that was a thing.
