### ISSUE TITLE
items in ur content pack not working with waila mod

### ISSUE THREAD

**Issue by zacharyhenry** [DonBruce64/MinecraftTransportSimulator#150]
Forge version 14.23,5,2838
Minecraft version 1.12.2
MTS(immersive vechiles) version 14.3.1

items that are being affected(list might change) 
1. crash barrier
2. traffic signal controller
![Minecraft 1 12 2 6_3_2019 1_26_17 PM](https://user-images.githubusercontent.com/49297302/59171927-08cc0400-8b0b-11e9-8545-1c32cbac0628.png)
![Minecraft 1 12 2 6_9_2019 10_31_35 PM](https://user-images.githubusercontent.com/49297302/59171928-08cc0400-8b0b-11e9-95e4-d925e3d6521f.png)

**Comment by DonBruce64** [comment]
Fixed in V15.7.0.
