### ISSUE TITLE
[BUG] Editable textObjects cannot be combined with variable-displaying textObjects.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1500]
Hi, my name is- _crash_

[crash-2023-01-08_18.09.21-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10369834/crash-2023-01-08_18.09.21-client.txt)

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.

**Comment by boot2big** [comment]
_Might_ still be an issue, actually... now instead of customizable tOs fighting with variable tOs, it is imageURL fighting with the variable textObjects!
https://discord.com/channels/232316230852280320/1117507501890486302

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
