### ISSUE TITLE
[Enhancement] Ability to Define some kind of animations on muzzleObject groups to allow muzzleObjects to move in more than just a pitch rotation type of way

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1506]
this feature would allow for more use with things like mirroring when necessary, and for things with adjustable length barrels. i already have two things that need this feature and are ready to test

**Comment by DonBruce64** [comment]
I disagree with needing to have adjustable barrel lengths.  It's a super-slight visual quirk and one that won't affect the bullet's trajectory.

If it's just mirroing though, I can do that automatically in the code without animations.

**Comment by LauraDarkez** [comment]
it has an effect when it comes to pellet firing guns.

**Comment by LauraDarkez** [comment]
with the barrel length, its either i leave the muzzles at the extra long barrel end, resulting in it being practically useless at close-range with the sawnoff barrel, or i put the muzzle at the sawnoff point and make the bullets clip through the barrel when firing. it also has an effect on what the spread looks like. this feature is also good in general for things where barrel accessories are put on certain guns, as discussed with @boot2big

**Comment by DonBruce64** [comment]
Outsourcing with 1-month timeline.  There are two folks who can code guns, and I don't have time to add yet more gun features when I can't get anyone who uses guns to test betas with any regularity.

**Comment by DonBruce64** [comment]
Bing bing, time is up.
