### ISSUE TITLE
[Enhancement] Make isTwoHanded, fireDelay and spreadFactor able to be modified using VariableModifiers

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1508]
as the name says, nothing special. just make these values able to be modified using variableModifiers

**Comment by LauraDarkez** [comment]
there are a few ideas for this to be used: variable-fire rate guns such as the a10's main cannon, or guns that have inconsistent fire rates, alternatively guns that can be configured for a slower ground-unit vs a faster aircraft-mounted fixture, and spreadfactor is to correspond with cut-down barrels, or modular barrels

**Comment by LauraDarkez** [comment]
the reason for adding "isTwoHanded" to the vmable list is because customization could include turning a rifle into a "pistol" (such as the draco ak pistol). this would not be held by two hands the way a rifle would, and it would also make sense to use on some sawnoffs, and pistols converted into carbines via stock attachment

**Comment by LauraDarkez** [comment]
and if you tell me i need to split all of these into separate tickets, then so be it.

**Comment by DonBruce64** [comment]
Given that this is something both Prop or Rotor can do, and I really don't want to poke considering the state of the other gun bugs already existing in the new systems, I'm outsourcing this with a 1-month timeline.  Tick Tock.

**Comment by DonBruce64** [comment]
@boot2big

**Comment by DonBruce64** [comment]
Drat.  I was hoping it'd let me assign you the issue if I mentioned you, it would appear I can only do that if ye speak a spoken word on here or something....

**Comment by boot2big** [comment]
Ding ding

**Comment by boot2big** [comment]
Beep beep!!

**Comment by DonBruce64** [comment]
There we go!

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
