### ISSUE TITLE
Parts don't render when rotated 180 degrees with VMs

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1509]
When a part is rotated 180 degrees via VMs the part does not render.

![image](https://cdn.discordapp.com/attachments/604874468254285825/1063701880141774908/2023-01-13_21.56.52.png)

**Comment by DonBruce64** [comment]
180 degrees in which axis exactly?  All of them, or one of them?

**Comment by DrprofLuigi** [comment]
This is in any axis. The engine is the Z axis and the record is the Y axis. But this is only when rotated with VMs since engines and wheels are fine when rotated 180 degrees, and wheels don't vanish when rotating on their axle.

**Comment by DonBruce64** [comment]
This does not appear to be an issue as of the current release.  Can you confirm?
![2023-02-19_17 24 08](https://user-images.githubusercontent.com/15241611/219981853-c153165f-594f-43b9-9444-65d5a68a7715.png)

**Comment by DonBruce64** [comment]
Closing due to no user response.
