### ISSUE TITLE
Variables don't permiate on parts placed on the ground 

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1510]
Things like applyAfter and interactableVariables don't work properly when a part is placed on the ground. Animations for collisions also don't work properly.

This can be seen in these pictures

When I lose the lid, the hitbox that has applyAfter does not move:
![image](https://cdn.discordapp.com/attachments/604874468254285825/1063700150998020197/2023-01-13_22.02.08.png)

When I reload the world, the box animates properly
![image](https://cdn.discordapp.com/attachments/604874468254285825/1063701439895060481/2023-01-13_22.09.37.png)

Same is true when I open it.
![image](https://cdn.discordapp.com/attachments/604874468254285825/1063700151220314172/2023-01-13_22.03.55.png)

The button hitbox on the stereo has a visibility animation that also does not work.
![image](https://cdn.discordapp.com/attachments/604874468254285825/1063700151463592016/2023-01-13_22.04.15.png)

**Comment by DonBruce64** [comment]
Is this the hitbox, or the actual animation or both?

**Comment by DrprofLuigi** [comment]
The animations work fine (as shown in the first and third image), however the hitboxes don't move, and the interactableVariables don't change. It's like only the animations work.

**Comment by boot2big** [comment]
Can confirm this is a bug, this vehicle hoist does not work correctly. (As seen in the video, the red hitboxes are supposed to follow the track, but this is not the case.)
Additionally, the green hitbox seen hovering above the control panel is supposed to disappear when the hoist is lowered, as it would not be possible to flip it.

https://user-images.githubusercontent.com/53581325/215592200-3fdd83ae-0484-471f-b6d1-d296d200bb6b.mp4

I was also going to report vehicles not being able to drive on the hitboxes themselves, but I remembered that this exact thing actually came up if I'm not mistaken. Sad, but at least it's only a slab up, so the connector part will still be close enough to the wheels to pick them up onto the hoist.

**Comment by boot2big** [comment]
Found a PA-side workaround for now, although the original reason I had made this lift for doesn't quite work yet anyways. Nevertheless, development time can easily be focused on other things at the moment!

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
