### ISSUE TITLE
[bug] Horn loop is not played corectly 

### ISSUE THREAD

**Issue by TonySokachu** [DonBruce64/MinecraftTransportSimulator#1513]
whenever i touch the horn button the sound is not played as it should be, probably the loops is not made correctly. [https://cdn.discordapp.com/attachments/407041732988108810/1064276404683931659/2023-01-15_21-00-47.mov](url)

**Comment by DonBruce64** [comment]
Might be related to #1321 @boot2big?

**Comment by boot2big** [comment]
Semi related... although the HORRIBLY looped engine sound had me thinking it was a user error at first. Post the horn soundfile itself? (Or its waveform in Audacity)

**Comment by TonySokachu** [comment]
I forgot to mention: Horn works perfect on singleplayer worlds, but on server the sound isjust awfull, and is the same for all users, you can hear the funky horn from all the users.

**Comment by LauraDarkez** [comment]
then yes its definitely related to the bug with horns that don linked to a previous ticket

**Comment by LauraDarkez** [comment]
and from my experience on a server with a couple friends of mine the horn issue is still present. we are running 22.6.0 beta

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
