### ISSUE TITLE
[bug] Camera locked after leaving SP world in a vehicle in F5 mode and re-entering the world

### ISSUE THREAD

**Issue by Colt44Magnum** [DonBruce64/MinecraftTransportSimulator#1514]
This is using the IV v22.6.0 BETA. All that is need to reproduce this is to be seated in a vehicle and F5 leave the Singleplayer world (might also do this in multiplayer but I don't have a server to test with) when you rejoin the singleplayer world you will be stuck where you were seated but can still drive around the vehicle. 

Video showing the problem:
https://youtu.be/DTvVpLQVq1o

**Comment by Colt44Magnum** [comment]
![image](https://user-images.githubusercontent.com/51977107/213054698-7b1a3476-c645-465e-a508-ad2ef7580330.png)
Was asked if this happened in 22.3.0
I downloaded off of Curseforge to test. The results conclude it does not happen on 22.3.0, but rather the player gets unseated when re-entering the world

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
