### ISSUE TITLE
[bug] Guns don't count as a player-dealt source of damage

### ISSUE THREAD

**Issue by Dubbington** [DonBruce64/MinecraftTransportSimulator#1515]
**Copied from initial Discord report:**
They don't really deal a damage source that is recognized as coming from the player. I'm not exactly sure how this works but just this along breaks quite a few things with other mods if you kill mobs using any IV gun.

https://user-images.githubusercontent.com/75969752/213084772-95e82545-2379-45c7-81b4-a2f8ec66e350.mp4

**Comment by DonBruce64** [comment]
Fixed in V22.6.0.
