### ISSUE TITLE
[Enhancement] "noWater" hitboxes

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1517]
Hitboxes that do not collide with anything, but remove water physics when you are inside of them. Would be useful for sub interiors and ships where you can walk under the waterline

**Comment by DonBruce64** [comment]
Not possible without significant lag, as MC checks for water physics based on the block you are in.  The only way I could prevent that would be to remove the water block, and that causes lots of lag when you do that due to falling water updates.
