### ISSUE TITLE
[Video]Is it a bug? The vehicle moves tiny and continually after stopping

### ISSUE THREAD

**Issue by Somebodygoodluck** [DonBruce64/MinecraftTransportSimulator#1519]
I found that my car will move slowly even I stop my car. At this time, its wheels will not turn, but it is still moving, and the direction of movement is even different from the direction of the front of the car. If one of the wheels of the vehicle is raised, the displacement will occur more severely when parked, and even the direction will be offset while driving. If I go on a This phenomenon is not very obvious, but it can be found by observing the coordinates. And the vehicle stops this movement after re-entering the save. I've tested several vehicle packs and replaced versions of IVs, but all have this nasty issue which makes me unhappy. I even closed other mods but it didn't work, either. It seems that many people don't care about this, but I really care about it. I wonder if it is a bug and I hope it can be fixed.
I really like IV until I found this problem, and I'll much more like it if this can be fixed.
![2023-01-25_00 58 17](https://user-images.githubusercontent.com/123488584/214358051-9b9e644a-a8fa-463f-ae03-750e6c462779.png)
![2023-01-25_00 58 23](https://user-images.githubusercontent.com/123488584/214358062-f9a3220c-ae20-4702-84cf-dadb562168f4.png)
The first image above is taken after I brake and stop the vehicle, during which I kept pressing the brakes, but the vehicle still moved, which made the module seem unrealistic. It might seem tiny, but I really care about it. (Notice the change in the coordinates of the upper left corner)
IV is really a excellent mod, so I don't expect it to be affected by this issue. I really hope the owner can fix it.

**Comment by boot2big** [comment]
If I'm not mistaken, this is partially caused by a desync between your client and the server (even in singleplayer, as your game is just running a hidden server)
Correct me if I'm wrong though, Don.

**Comment by DonBruce64** [comment]
You are correct about how the syncing works, however, without a video I cannot say if this is syncing or something else entirely.

**Comment by Somebodygoodluck** [comment]
Maybe the pictures above don't express the meaning clearly, so I can record a video later to better express my question.  Thanks for your help!

**Comment by Somebodygoodluck** [comment]
> You are correct about how the syncing works, however, without a video I cannot say if this is syncing or something else entirely.


https://user-images.githubusercontent.com/123488584/214509423-e6ec94aa-c722-4206-b83a-df73de39334e.mp4

https://user-images.githubusercontent.com/123488584/214509428-223f38e4-b2bb-446c-b826-a5b848530ef0.mp4

I recorded two videos, the one in the car where the coordinates in the upper left corner changed after I stopped, and the second video showed the vehicle's displacement.

**Comment by Somebodygoodluck** [comment]
> If I'm not mistaken, this is partially caused by a desync between your client and the server (even in singleplayer, as your game is just running a hidden server) Correct me if I'm wrong though, Don.

Thanks for replying! But it seems that my problem isn't caused by a desync.

**Comment by DonBruce64** [comment]
Oh, that little amount?  Yeah, that is a de-sync.  IV does a rubber-band-syncing system that allows the keeping of vehicles in sync without jarring jumping.  The 1/4 block movement you see after stopping is natural, and should go away in about 1-3 seconds or so.  If it keeps up for more, like 10 seconds, or you move over 1 block, then that's a problem.  But I can't tell that from your videos as they end quickly.

**Comment by boot2big** [comment]
TBH you don't even notice it after a while. If anything I'd rather it be like this rather than instantly jumping to where it should be, as that'd be a lot more noticeable! 
~~Besides... Maaaybee your car doesn't wanna stop moving, y'knooow... :point_right::point_left:~~

**Comment by Somebodygoodluck** [comment]
> 哦，那么少？是的，这是一种不同步。IV有一个橡皮筋同步系统，允许车辆保持同步而不会产生刺耳的跳跃。停止后您看到的 1/4 块运动是自然的，应该在大约 1-3 秒左右消失。如果它保持更长时间，比如 10 秒，或者你移动超过 1 个街区，那么这就是一个问题。但我无法从您的视频中看出这一点，因为它们很快就会结束。


https://user-images.githubusercontent.com/123488584/215794823-5f4eb27a-4f26-43d6-962d-c50cb4078cd5.mp4

OK, I know your meaning now. But my car moves more than 10 seconds, and it doesn't stop...
(Maybe the video quality is poor, because I have to make it less than 10M in size)

**Comment by Somebodygoodluck** [comment]
> TBH 过了一会儿你甚至没有注意到它。如果有的话，我宁愿它是这样的，而不是立即跳到它应该在的地方，因为那会更引人注目！ ~此外。。。Maaaybee你的车不想停止移动，呸呸呸...👉👈~

I know you meaning now. But I really care about it after I find this problem.

**Comment by Somebodygoodluck** [comment]
> TBH 过了一会儿你甚至没有注意到它。如果有的话，我宁愿它是这样的，而不是立即跳到它应该在的地方，因为那会更引人注目！ ~此外。。。Maaaybee你的车不想停止移动，呸呸呸...👉👈~

Yes, it's less noticeable as this than instantly jump to where it should be. I agree this. But I really care about this problem after I found it because it moves for a long time.

**Comment by DonBruce64** [comment]
Given that video, I can confirm this is part of the gradual syncing system.  Yes, the vehicle does move for a bit after stopping.  But it's no more than 1/4 block.  If I change the syncing code, then it'll be a lot worse when in motion around things.  This is one of the issues that comes with a client/server system like Minecraft, and this is a designed trade-off versus the alternative of faster syncing which makes the vehicle rubberband and jump around more if playing on an actual server, especially one with lag.

**Comment by Somebodygoodluck** [comment]
> 鉴于该视频，我可以确认这是逐步同步系统的一部分。是的，车辆在停车后确实移动了一会儿。但它不超过 1/4 块。如果我更改同步代码，那么在事物周围移动时情况会更糟。这是像 Minecraft 这样的客户端/服务器系统附带的问题之一，这是一种设计权衡，而不是更快同步的替代方案，如果在实际服务器上播放，尤其是延迟的服务器，会使车辆橡皮筋和跳跃更多。

OK, I understand. Thanks for helping!
