### ISSUE TITLE
[ENHANCEMENT] `preventRecursivePlacement` variable, or similarly named

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1521]
If True, prevents this part from being placed on itself. Simple enough.
Does not affect whether this part can be placed on other parts, regardless of whether those parts are on a similar one of its kind.

(And yes, to clarify I mean "on itself" as in, on another part of its kind.)

**Comment by LauraDarkez** [comment]
like, avoiding being able to do what franz did and stacking his tank turrets to build limit?

**Comment by boot2big** [comment]
Same concept, though not targeting that in particular no. Mainly stems from my old janky solution to preventing users from doing this with the hydraulic parts, as well as my current non-solution of just being able to stack hover wheels onto hover wheels.
And anyways, it would be opt-in rather than opt-out.

**Comment by DonBruce64** [comment]
Would this use the `type` parameter I'm assuming and block placement if the type matches?  Or would it just be if the same part is requested?

**Comment by boot2big** [comment]
If the same part is requested. Having unique parts is okay since you'll probably be left with parts that won't recurse anyways, and if you want to block a part type entirely... don't include it! Easy. Don't gotta block no budd wheels if you don't include them in the first place.

**Comment by DonBruce64** [comment]
Then this won't fix your hydraulic stuff, as you have 4 different hydralic parts, so while you can't stick a H#1 on a H#1, you can still stick a H#1 on a H#3, then a H#1 on that.

**Comment by boot2big** [comment]
Okaaaay, fair enough then. I sorta forgot I've got 4 different hydraulics with their own different switches. But this still would making blocking it with `type` quite difficult since the hydraulic part and/or hoverwheel has to take a wheel its own size, while not taking itself.

**Comment by boot2big** [comment]
Although y'know... Thinking about it more, this probably isn't even necessary. If someone wants to recurse parts, then laginess and unexpected behavior is to be, well, expected! Besides, it's not like it'd make you hover any higher, or make your hydraulics into a turboboost. If anything thinking about it, having stacked hydraulics might be pretty fun.
