### ISSUE TITLE
[BUG] Vehicles lose it and flip if... _something_ happens on the Y axis of one or two ground devices.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1522]
I don't know how to describe what causes it, other than driving a floatable ground device on water, or driving any normal ground device over a 1x1x1sq meter pothole. If you find it, you'll know because your vehicle flips anywhere between 90 and 180 degrees in either direction. Direction doesn't seem to be related to which side of the vehicle the pothole/water is on.
Can even sometimes happen with slabs or carpet, though carpet rarely does this.

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
