### ISSUE TITLE
says roads in the manual but can't find how to really use them anywhere online.

### ISSUE THREAD

**Issue by steiger9350** [DonBruce64/MinecraftTransportSimulator#1525]
i have been trying to find how make roads? and there is a npc thing, i heard that also has something to do with that? im not going to use the brush from world edit, takes too long to put lines in.

**Comment by DonBruce64** [comment]
This is not a bug, it's a help request.  These belong on Discord.

**Comment by steiger9350** [comment]
oh welp i don't got discord, im screwed.

**Comment by DonBruce64** [comment]
You don't have to have Discord to use Discord, but if you wanna stay screwed, who am I to judge?

**Comment by steiger9350** [comment]
i have it now but no one really knows what the road tool is or how to use it. so i give up for now

**Comment by boot2big** [comment]
It sounds like you'sa talking about FVTM's road generator tool, not the custom pack-defined roads in MTS. I'll clarify both for you.

FVTM has a tool that lets you build/generate roads using defined blocks. It's tricky to use, but once you get a hang of it you can place down some pretty cool looking roads that may only need some touching up. (And it's Furenikus compatible!)
MTS packs have the option to define modeled roads that stay mostly the same visually, and can't (yet) be customized much beyond where you make 'em go. Vehicles will snap to these and follow them, meaning they can also be used to make railroads for trains. This, coming from the first pack author to (as far as I'm aware) actually release an MTS train!
