### ISSUE TITLE
[BUG] Incindiary bullets shouldn't ignite blocks if explosions are disabled

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1529]
If nothing else, this is because explosive+incendiary bullets will still make flames even if their explosions don't leave craters.

**Comment by DonBruce64** [comment]
@gyrohero FYI, the assignment is for completed stuff.  I won't poke nuthing in here for bullets since I expect either you or @conman180 will get to it waaay before I do.  Just do what y'all do and when you push for completion just put your marker on it.

**Comment by DonBruce64** [comment]
Re-opening, as this is still a bug as of current release, and I want users to know that it's being worked on rather than them making another ticket.

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
