### ISSUE TITLE
[Suggestion] Tough as Nails integration

### ISSUE THREAD

**Issue by Captain26050** [DonBruce64/MinecraftTransportSimulator#153]
Hello! Firstly, I would like to say congratulations for the Immersive Vehicles team, your mod is incredible and is now a must have in my modpacks. However, I'm having some trouble to keep myself warm while flying.

  I would love if heaters were added to airplanes as either an extra acessory or coming built into the plane. 

  The heaters could be activated manually, adding +10 degrees to the temperature or having a manual control, allowing a more precise temperature control. 

  I don't know how complicated Tough as Nails' coding is though, so I apologize if what I'm asking is too complicated.

Best regards
-Captain26050

**Comment by DonBruce64** [comment]
Went and took a look.  From what I can find, TAN does not have an API I can use to allow vehicles to have heaters.  While there are some things in Serene Seasons, everything I could find uses blocks and items to define temp, not entities.  I suspect this will be rather hard to do, so if you're going flying you either need to stay low, or wear really warm clothes like WWI pilots.  Apologies about that.
