### ISSUE TITLE
pole with problems

### ISSUE THREAD

**Issue by Doncarlonn** [DonBruce64/MinecraftTransportSimulator#1530]
![2023-02-04_11 44 42](https://user-images.githubusercontent.com/124437220/216956153-0b4c495d-5630-43b6-818b-7b760f3c8320.png)

**Comment by boot2big** [comment]
Which pack is this? Do you have the Official Content Pack installed? If so, could you try using those poles for now to see if it really is decor block animations or if its simply this pack's poles?

**Comment by DonBruce64** [comment]
Well, I don't know what fixed this issue, but it's fixed!
