### ISSUE TITLE
[BUG] Blocks will wait until the end of impactDespawnTime to break if the bullet is heavy enough to break them

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1531]
Related to #1494 in nature.
Thought it was heavy server lag at first, but nope. Apparently if the bullet doesn't have an explosion that destroys the blocks first but the bullet is heavy enough to destroy a single block, that block will wait until the very end of impactDespawnTime.

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
