### ISSUE TITLE
Broken Turret Left/Right Rotation (Yaw)

### ISSUE THREAD

**Issue by PawelW2006** [DonBruce64/MinecraftTransportSimulator#1532]
Turrets Do not rotate Left/Right (Known as Yaw in aviation) both in the Official Pack Renault FT and in almost all other Packs.

Versions: From 22.0.0 To 22.6.0 - Bug as Decribed
Version: 21.3.0 - Turrets Rotate Fine but in the Official Pack Renault FT-17 the player glitches out of the turret when the seat is up.

In Both Version MTS Official Pack v23 was used.

**Comment by DonBruce64** [comment]
Strange.  Talking with the folks on Discord they say none of them have a similar issue.  Can you post a video?

**Comment by PawelW2006** [comment]
Here is a link to a Video, i've uploaded it to mediafire as GitHub Limits Upload size to 10mb.
https://www.mediafire.com/file/h2hkxiwjns4eahs/Jre1.8.0_351_2023.02.12_-_04.06.19.01.mp4/file

Here is the log in case it can help in any way.
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10715204/latest.log)

A Bunch of Extra Info:
- I Have a bunch of other Packs Installed but i don't think a Pack should affect the core functionality of the mod.
- All of the Keystrokes in the Video is Clicking Space which is the key i assigned to shoot (And correct if i'm wrong but i think it's also the default key for shoot)
- The Same Issue happens in most other Guns from Other Packs with the Exception of the UNU Military Pack which Works Fine.

**Comment by DonBruce64** [comment]
Ah, I see.  The gun doesn't think the seat you are in is linked to it.  That's strange.  Pinging @SnailPerson since he's working with the OCP on this.  I suspect this is a pack issue.  If you could go to the Discord and ping me I can send you a beta of what we have that will probably fix this.

**Comment by DonBruce64** [comment]
Fixed as of latest OCP release.
