### ISSUE TITLE
endless engine

### ISSUE THREAD

**Issue by RomanSav09** [DonBruce64/MinecraftTransportSimulator#1534]
car is not consuming fuel

**Comment by DonBruce64** [comment]
You're in creative mode, it won't consume fuel if you're in creative mode.  Much like how you won't take damage, you won't loose oxygen in space mods, most guns from other mods won't consume ammo, etc.

That being said, I'm thinking this might be better off as a config than based on the player's state.  Will adjust.

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
