### ISSUE TITLE
[Enhancement] Auxiliary pointer for guns

### ISSUE THREAD

**Issue by dldev32** [DonBruce64/MinecraftTransportSimulator#1536]
This idea was posted here 2 years ago, but was closed, since military affairs in IV wasn't yet so developed.

Such a critically important thing is simply necessary in a mod where there are guns. At the moment, sights don't provide high accuracy, and self-propelled guns pose a difficult task for the player, especially for inexperienced folks.

Many people have seen how the pointer works in a game called War Thunder, but I have references for _the code in a [separate repo](https://github.com/dldev32/MTS-CROSSHAIR)_. Unfortunately my addon doesn't work properly and _it will only be supported on 1.12.2_. In addition, it uses hooks, a fundamental change in the affected code can fetch _the addon unusable_. Btw, I don't recommend using the 3D model as a pointer render, as it doesn't render correctly in game. It's best to use a 2D component, as done in [Shoulder Surfing](https://github.com/Exopandora/shouldersurfing).

**Comment by DonBruce64** [comment]
Unless this can be coded in a version-agnostic manner, I do not see any use adding it.  Especially when current coding is being focused on updating the code to 1.16.5.  Adding an outsourced label and 1-month timeframe.  If you want this, get with @conman180 or @gyrohero.  They understand this stuff way better than I do.

**Comment by DonBruce64** [comment]
Bing bing, time is up.
