### ISSUE TITLE
[BUG] Particles loop through transparency when over 1

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1539]
Ideally should work as before, where the particle remains fully opaque until the duration gets the transparency below 1

https://user-images.githubusercontent.com/53581325/219891103-40c45c45-d13b-4b53-bac4-1a32512c05e7.mp4

**Comment by DonBruce64** [comment]
What's the fromTransparency and toTransparency for this behavior?

**Comment by boot2big** [comment]
toTransparency is a value basically a smidge above 0, something like 0.00001
However, fromTransparency is a value between 2 and 8 depending on the application, because this keeps the particle from fading away until the very last moments of its duration. I believe it's 8 here for the tire marks though, IIRC.

**Comment by boot2big** [comment]
To clarify, if we have a particle with a duration of 60, and a fromTransparency of 3, the particle will remain solid for two seconds and will fade away within one second.
This is very useful for specific particles like bullet casings or tiremarks.

**Comment by boot2big** [comment]
Uuuh, new bug. :smile: 
Now sizes are clamped, which wouldn't be so bad except for the fact that they're clamped to 1. This doesn't affect handguns or exhaust smoke any, but try backfire smoke or explosions, or large fires and it'll become very obvious.

**Comment by boot2big** [comment]
(scale issue)
Fixed in latest 22.6.0-beta (As of 6:47pm)

https://user-images.githubusercontent.com/53581325/222858053-9e540626-71a0-4f85-ba9d-1de0c9e7f48f.mp4

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
