### ISSUE TITLE
Feature Request: Parts Type for Impacting Blocks Driven Over

### ISSUE THREAD

**Issue by znaxcy** [DonBruce64/MinecraftTransportSimulator#154]
I'm sure someone has posted something like this before, but all I could find was #102 regarding snowplows and this is broader than that. Apologies also if this is possible and I just missed it reading your guides (which are excellent, thank you for great docs):

I, like everyone else, am building a pack with agricultural equipment.
I'd like to see a way to to make it such that the implement I attach to the back of a tractor can actually turn grass below it into farmland. Then, of course, that other implements can harvest configurable crops as it passes over them, fertilize crops or grass, cut plants on top of grass blocks, make paths, etc. 
I imagine this being configurable via json to specific part types, such that we can swap out implements as parts on a vehicle rather than deal with trailers (I was disappointed to read about #46 re trailers being marked as wontdo, but I can certainly understand why.)

I know other mods out there focus on functionality like this, but they aren't as configurable or advanced and I'd like to put some of my vehicles to use beyond transportation.

Thanks and keep up the fantastic work!

**Comment by DonBruce64** [comment]
Having such a system is actually not as hard as you might think.  It's more what functionality you want and how you want it done.  Your first example of an implement that can turn grass to farmland is quite possible.  Can't speak to other implements as I've never looked at the code, but I can see it being something that's possible for sure.  I always work by the motto: you give me a model, I'll make the feature, so if you get to the point where you have the models done and need the features let me know!  Discord is good for prodding me as I'm on there pretty much daily.

**Comment by TheCactus27** [comment]
I have a tractor I made for treads, but I gave up on it, if you'd like it, I'll gladly finish the model for you @znaxcy

**Comment by znaxcy** [comment]
I have a first model that I need to write .json for. Now that I know you're up for it, I'll get to it. I'll write up a list of ideas regarding implement functionalities.

Thank you!

@TheCactus27 I'd love to see your model, DM me? I'll get onto the MTS discord and will have the same handle.

**Comment by DonBruce64** [comment]
@znaxcy should let you know I'm currently working on this ticket.  Took a while for me to get here, so I apologize.  Would have pinged you on Discord, but I see you're not there.

**Comment by DonBruce64** [comment]
Added multiple farm implements in V15.7.0.
