### ISSUE TITLE
HE and HEAT round pen + damage calculation breaks when editing blastStrength values

### ISSUE THREAD

**Issue by HighQGithub** [DonBruce64/MinecraftTransportSimulator#1540]
If the blastStrength config of a heat round is edited above a value of 1 (for instance in IAV parts pack and other packs), immersive vehicles seems to completely ignore set damage and penetration values resulting in vehicles being one shot even if penetration or damage values are extremely low.

**Comment by boot2big** [comment]
I had noticed a somewhat similar effect, though I theorized that this was vehicles receiving damage from each hitbox individually for explosions.

**Comment by HighQGithub** [comment]
I initially theorized this as well, I guess a work around for something like this would be to have the explosions for specified heat rounds deal no external damage to vehicles and act as an armor piercing round while still damaging nearby players from the blast.

**Comment by DonBruce64** [comment]
Checked with VEB dev and they have confirmed no issues as of current version.  Either this has been fixed by an un-related fix of another thing, or it was some mis-placed hitboxes.
