### ISSUE TITLE
Comanche texture has two doors.

### ISSUE THREAD

**Issue by PigeonOnACub** [DonBruce64/MinecraftTransportSimulator#1541]
The Comanche on the new v24 beta has two doors (left and right) textured, while it only have one door (right door). Fortunately the model is correct. (Image showing the left side of the aircraft)
![2023-02-20_12 35 22](https://user-images.githubusercontent.com/125898089/220148230-2770ed5f-2094-4bb9-9869-b987aa515c63.png)

**Comment by DonBruce64** [comment]
Closing as this is a Beta issue, not a release issue.
