### ISSUE TITLE
[Enhancement] More collision boxes for treads

### ISSUE THREAD

**Issue by dldev32** [DonBruce64/MinecraftTransportSimulator#1544]
This feature will allow not only to fix problems with inclined surfaces, but also to make a kind of suspension for the chassis rollers.

EDIT: Probably better to make a section for the "wheels" in JSON for the treads, this will allow each roller to be "indexed" on the chassis and successfully animated on the tank.

**Comment by DonBruce64** [comment]
Not going to happen.  I tried this during the early days of IV in making each wheel its own collision box.  It just lead to a lot of bugs and poor vehicle handling of said slopes and inclines.
