### ISSUE TITLE
[ENHANCEMENT] Self-linking parts parameter

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1547]
`forceLinkToController` would force guns to forcibly link to parented controllers regardless of any links to parenting part slots.

See IVV with Weapon Mounting Gear (for weaponized vehicles with machine guns or flares) or Hashim's CIWS model. It don't work if pack authors don't think ahead to link their vehicle controller seats to their license plates or lightbar slots. (Which, the WMG guns specifically relied on that not being required... or rather were JSON'd up and released when we did not yet have linked parts.)

Normal parts without this parameter will still function normally (unlinked wheels won't be powered by anything/unlinked engines won't power wheels, unlinked seats will not control guns or cameras, etc etc)

**Comment by boot2big** [comment]
Clarification: Would be the bestest of the best if it worked on all parts, was in a discussion about this variable that mainly mentioned guns. Still okay if it only links guns though should forceLinking all parts not be as easily applicable.

**Comment by DonBruce64** [comment]
So all parts as in you can put a wheel on, and it'll link to engines?  Cause those aren't controllers, only seats are controllers.

**Comment by boot2big** [comment]
That is a fair point, that variable name was brought up in such discussion. Nevertheless still preferable if we had a variable to force this part to self-link to other parts it is a parent/child of, as well as neighboring parts on a part and/or vehicle. 

`forceLinkToOthers`
`forceAllLinks`
`forceLinkToParts`
`forcePartLink`

or such.

**Comment by DonBruce64** [comment]
Would this be on the part slot, or the part itself?  And can I assume if the latter, it'd basically mean "if anything would link to this part in a linked slot, link to it".  Say you can put a wheel with this paramter anywhere and all engines will link to it.  Or you can put a gun anywhere and any seats will link to it?

**Comment by boot2big** [comment]
The part itself (There'd be almost no point to putting it on the part slot, as at that point you could link a part normally, as one does with `linkedParts`) and correct. If on a wheel, all engines link to it and if on a gun all seats link to it, etc. (effectors come to mind at least?)

**Comment by boot2big** [comment]
Does not work as of latest 22.6.0-beta (As of 8:16pm)

![image](https://user-images.githubusercontent.com/53581325/222868956-361ecbae-7d2a-475c-9b03-7913250d07d6.png)
![image](https://user-images.githubusercontent.com/53581325/222868965-a75fde89-f604-40b4-9834-ff1cb2b806f7.png)
![image](https://user-images.githubusercontent.com/53581325/222868970-58da85ab-58fa-4e35-a569-6b8cbef1f741.png)


https://user-images.githubusercontent.com/53581325/222869098-fcf78d84-a8e9-4071-a0ad-71d7c9dcc2af.mp4

**Comment by boot2big** [comment]
(`forceAllLinks` was also applied to part holders such as weapon mounting bar and CIWS base)

**Comment by DonBruce64** [comment]
Implemented in V22.7.0.
