### ISSUE TITLE
[BUG] Camera seems to be zoomed out by default, can't zoom in further

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1549]
This can be seen when trying to put the camera into the ground, you can clip it into the ground long before it will collide with hte ground
Applies to regular third person (facing ahead and facing behind), not to custom cameras

**Comment by DonBruce64** [comment]
Is this a beta bug?  If so, it doesn't belong here.

**Comment by boot2big** [comment]
If you no respond to DMs, me'sa gonna use the next available method. Otherwise it'll be your paper telling you about beta bugs!!
