### ISSUE TITLE
Immersive vehicles crashes when I switch the tab in the component bench

### ISSUE THREAD

**Issue by IronSasquatch33** [DonBruce64/MinecraftTransportSimulator#1550]
Immersive vehicles is crashing minecraft when I go to switch tabs in the component bench while the recipe for super steel ingots is open, it is when the ingot recipe for the ingot is shown in the tab not the block recipe.
Here is the crash report:

---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  IILoadingPlugin (immersiveintelligence-core-0.3.0.jar)
  WitcheryLoadingPlugin (WitcheryResurrected-1.12.2-0.5.2.4-forge-all.jar)
Contact their authors BEFORE contacting forge

// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 2/26/23 3:05 PM
Description: Updating screen events

java.lang.IndexOutOfBoundsException: Index: 1, Size: 1
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at minecrafttransportsimulator.packloading.PackMaterialComponent.parseFromJSON(PackMaterialComponent.java:63)
	at minecrafttransportsimulator.guis.instances.GUIPartBench.updateNames(GUIPartBench.java:466)
	at minecrafttransportsimulator.guis.instances.GUIPartBench.access$400(GUIPartBench.java:44)
	at minecrafttransportsimulator.guis.instances.GUIPartBench$4.onClicked(GUIPartBench.java:156)
	at mcinterface1122.BuilderGUI.func_73864_a(BuilderGUI.java:48)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at minecrafttransportsimulator.packloading.PackMaterialComponent.parseFromJSON(PackMaterialComponent.java:63)
	at minecrafttransportsimulator.guis.instances.GUIPartBench.updateNames(GUIPartBench.java:466)
	at minecrafttransportsimulator.guis.instances.GUIPartBench.access$400(GUIPartBench.java:44)
	at minecrafttransportsimulator.guis.instances.GUIPartBench$4.onClicked(GUIPartBench.java:156)
	at mcinterface1122.BuilderGUI.func_73864_a(BuilderGUI.java:48)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: mcinterface1122.BuilderGUI

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['ironsasquatch33'/57, l='MpServer', x=577.05, y=44.00, z=1535.50]]
	Chunk stats: MultiplayerChunkCache: 2401, 2401
	Level seed: 0
	Level generator: ID 02 - largeBiomes, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (0,88,0), Chunk: (at 0,5,0 in 0,0; contains blocks 0,0,0 to 15,255,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Level time: 1564385 game time, 393760 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 15 total; [EntityChicken['Chicken'/68, l='MpServer', x=523.48, y=68.00, z=1578.86], EntityChicken['Chicken'/69, l='MpServer', x=523.80, y=68.00, z=1580.47], BuilderEntityExisting['entity.mts_entity.name'/70, l='MpServer', x=560.52, y=68.44, z=1507.43], BuilderEntityExisting['entity.mts_entity.name'/71, l='MpServer', x=559.78, y=68.34, z=1503.28], BuilderEntityExisting['entity.mts_entity.name'/72, l='MpServer', x=569.50, y=44.00, z=1526.50], BuilderEntityExisting['entity.mts_entity.name'/73, l='MpServer', x=590.64, y=68.44, z=1499.58], EntityArmorStand['Armor Stand'/78, l='MpServer', x=602.50, y=73.00, z=1615.50], EntityArmorStand['Armor Stand'/79, l='MpServer', x=603.50, y=73.00, z=1615.50], EntityArmorStand['Armor Stand'/80, l='MpServer', x=601.50, y=73.00, z=1615.50], EntityArmorStand['Armor Stand'/81, l='MpServer', x=603.50, y=73.00, z=1616.50], EntityArmorStand['Armor Stand'/82, l='MpServer', x=603.50, y=73.00, z=1617.50], BuilderEntityExisting['entity.mts_entity.name'/2934, l='MpServer', x=577.05, y=44.00, z=1535.50], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/16438, l='MpServer', x=577.56, y=45.77, z=1536.49], BuilderEntityExisting['entity.mts_entity.name'/89, l='MpServer', x=616.50, y=68.00, z=1769.50], EntityPlayerSP['ironsasquatch33'/57, l='MpServer', x=577.05, y=44.00, z=1535.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 17536839296 bytes (16724 MB) / 24159191040 bytes (23040 MB) up to 30064771072 bytes (28672 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx28G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=64M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2859 66 mods loaded, 66 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                    | Version              | Source                                               | Signature                                |
	|:------ |:--------------------- |:-------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft             | 1.12.2               | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                   | 9.42                 | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                   | 8.0.99.99            | forge-1.12.2-14.23.5.2859.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge                 | 14.23.5.2859         | forge-1.12.2-14.23.5.2859.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | opencomputers|core    | 1.7.7+5413028        | minecraft.jar                                        | None                                     |
	| LCHIJA | witchery              | 1.12.2-0.5.2.4-forge | WitcheryResurrected-1.12.2-0.5.2.4-forge-all.jar     | None                                     |
	| LCHIJA | artemislib            | 1.0.6                | ArtemisLib-1.12.2-v1.0.6.jar                         | None                                     |
	| LCHIJA | astikorcarts          | 1.12.2-0.1.2.8       | astikorcarts-1.12.2-0.1.2.8.jar                      | None                                     |
	| LCHIJA | baubles               | 1.5.2                | Baubles-1.12-1.5.2.jar                               | None                                     |
	| LCHIJA | astralsorcery         | 1.10.27              | astralsorcery-1.12.2-1.10.27.jar                     | a0f0b759d895c15ceb3e3bcb5f3c2db7c582edf0 |
	| LCHIJA | bibliocraft           | 2.4.6                | BiblioCraft[v2.4.6][MC1.12.2].jar                    | None                                     |
	| LCHIJA | guideapi              | 1.12-2.1.8-63        | Guide-API-1.12-2.1.8-63 (3).jar                      | None                                     |
	| LCHIJA | bloodmagic            | 1.12.2-2.4.3-105     | BloodMagic-1.12.2-2.4.3-105.jar                      | None                                     |
	| LCHIJA | jei                   | 4.16.1.301           | jei_1.12.2-4.16.1.301.jar                            | None                                     |
	| LCHIJA | botania               | r1.10-364            | Botania r1.10-364.4.jar                              | None                                     |
	| LCHIJA | capsule               | 1.12.2-3.4.76        | Capsule-1.12.2-3.4.76.jar                            | None                                     |
	| LCHIJA | codechickenlib        | 3.2.3.358            | CodeChickenLib-1.12.2-3.2.3.358-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | chickenchunks         | 2.4.2.74             | ChickenChunks-1.12.2-2.4.2.74-universal.jar          | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LCHIJA | redstoneflux          | 2.1.1                | RedstoneFlux-1.12-2.1.1.1-universal.jar              | None                                     |
	| LCHIJA | cofhcore              | 4.6.6                | CoFHCore-1.12.2-4.6.6.1-universal.jar                | None                                     |
	| LCHIJA | cofhworld             | 1.4.0                | CoFHWorld-1.12.2-1.4.0.1-universal.jar               | None                                     |
	| LCHIJA | mantle                | 1.12-1.3.3.55        | Mantle-1.12-1.3.3.55.jar                             | None                                     |
	| LCHIJA | tconstruct            | 1.12.2-2.13.0.183    | TConstruct-1.12.2-2.13.0.183.jar                     | None                                     |
	| LCHIJA | conarm                | 1.2.5.10             | conarm-1.12.2-1.2.5.10.jar                           | b33d2c8df492beff56d1bbbc92da49b8ab7345a1 |
	| LCHIJA | ptrmodellib           | 1.0.5                | PTRLib-1.0.5.jar                                     | None                                     |
	| LCHIJA | props                 | 2.6.3.7              | Decocraft-2.6.3.7_1.12.2.jar                         | None                                     |
	| LCHIJA | ebwizardry            | 4.3.7                | ElectroblobsWizardry-4.3.8.jar                       | None                                     |
	| LCHIJA | mts                   | 22.6.0               | Immersive+Vehicles-1.12.2-22.6.0.jar                 | None                                     |
	| LCHIJA | unuparts              | 5.1.4                | UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar         | None                                     |
	| LCHIJA | unuverse              | 1.3.0                | Expanded+UNUverse+Pack+[MTS]+1.12.2-18.0.0-1.3.0.jar | None                                     |
	| LCHIJA | floocraftft           | 1.9.6                | Floocraft+1.12.2-1.9.6.jar                           | None                                     |
	| LCHIJA | craftablewizardry     | 2.0                  | GIsCraftableWizardryItems-2.0.jar                    | None                                     |
	| LCHIJA | thermalfoundation     | 2.6.7                | ThermalFoundation-1.12.2-2.6.7.1-universal.jar       | None                                     |
	| LCHIJA | immersiveengineering  | 0.12-98              | ImmersiveEngineering-0.12-98.jar                     | None                                     |
	| LCHIJA | immersive_energy      | 0.5.5                | Immersive Energy-1.12.2-0.5.5.jar                    | None                                     |
	| LCHIJA | immersivegunpowder    | 1.0.0                | immersivegunpowder1.1.1.jar                          | None                                     |
	| LCHIJA | immersivepetroleum    | 1.1.10               | immersivepetroleum-1.12.2-1.1.10.jar                 | None                                     |
	| LCHIJA | trackapi              | 1.2                  | TrackAPI-1.2.jar                                     | None                                     |
	| LCHIJA | universalmodcore      | 1.1.4                | UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar       | None                                     |
	| LCHIJA | immersiverailroading  | 1.9.1                | ImmersiveRailroading-1.12.2-forge-1.9.1.jar          | None                                     |
	| LCHIJA | ic2                   | 2.8.170-ex112        | industrialcraft-2-2.8.170-ex112.jar                  | de041f9f6187debbc77034a344134053277aa3b0 |
	| LCHIJA | ironchest             | 1.12.2-7.0.67.844    | ironchest-1.12.2-7.0.72.847.jar                      | None                                     |
	| LCHIJA | ivv                   | 2.2.0                | IV-Vanity-1.12.2-2.2.0.jar                           | None                                     |
	| LCHIJA | journeymap            | 1.12.2-5.7.1         | journeymap-1.12.2-5.7.1.jar                          | None                                     |
	| LCHIJA | mahoutsukai           | 1.12.2-v1.19.55      | mahoutsukai-1.12.2-v1.19.55.jar                      | None                                     |
	| LCHIJA | mcjtylib_ng           | 3.5.4                | mcjtylib-1.12-3.5.4.jar                              | None                                     |
	| LCHIJA | immersivetech         | 1.9.100              | MCTImmersiveTechnology-1.12.2-1.9.100.jar            | None                                     |
	| LCHIJA | opencomputers         | 1.7.7+5413028        | OpenComputers-MC1.12.2-1.7.7+5413028.jar             | None                                     |
	| LCHIJA | harvestcraft          | 1.12.2zb             | Pam's+HarvestCraft+1.12.2zg.jar                      | None                                     |
	| LCHIJA | patchouli             | 1.0-23.6             | Patchouli-1.0-23.6.jar                               | None                                     |
	| LCHIJA | questionablyimmersive | @VERSION@            | questionablyimmersive-1.12.2-0.1.0.jar               | None                                     |
	| LCHIJA | rustic                | 1.1.7                | rustic-1.1.7.jar                                     | None                                     |
	| LCHIJA | t3s4ebw               | 1.0                  | SeedsForWizardryReforged.jar                         | None                                     |
	| LCHIJA | thermalexpansion      | 5.5.7                | ThermalExpansion-1.12.2-5.5.7.1-universal.jar        | None                                     |
	| LCHIJA | thermaldynamics       | 2.5.6                | ThermalDynamics-1.12.2-2.5.6.1-universal.jar         | None                                     |
	| LCHIJA | thermalinnovation     | 0.3.6                | ThermalInnovation-1.12.2-0.3.6.1-universal.jar       | None                                     |
	| LCHIJA | unucivil              | 5.3.2                | UNU+Civilian+Pack+[MTS]+1.12.2-21.3.0-5.3.2.jar      | None                                     |
	| LCHIJA | unumilitary           | 5.0.0                | UNU+Military+Pack+[MTS]+1.12.2-21.3.0-5.0.0.jar      | None                                     |
	| LCHIJA | variedcommodities     | 1.12.2               | VariedCommodities_1.12.2-(13Jan22).jar               | None                                     |
	| LCHIJA | wizardryfates         | 2.1.0                | WizardryFates-2.1.0.jar                              | None                                     |
	| LCHIJA | zettaigrimoires       | 1.5.0                | ZettaiGrimoires-1.5.0.jar                            | None                                     |
	| LCHIJA | zettaimagic           | 1.4.7                | ZettaiMagic-1.4.7.jar                                | None                                     |
	| LCHIJA | ancientspellcraft     | 1.12.2-1.5.9         | AncientSpellcraft-1.12.2-1.5.9.jar                   | None                                     |
	| LCHIJA | ignitingarrows        | 1.12.2-INDEV         | IgnitingArrows-1.12.2-1.0.0.jar                      | None                                     |
	| LCHIJA | immersiveintelligence | 0.3.0                | immersiveintelligence-0.3.0.jar                      | None                                     |
	| LCHIJA | wizardryutils         | 1.12.2-1.1.3         | WizardryUtils-1.12.2-1.1.3.jar                       | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
AstralCore (astralsorcery-1.12.2-1.10.27.jar)
  
TransformerLoader (OpenComputers-MC1.12.2-1.7.7+5413028.jar)
  li.cil.oc.common.asm.ClassTransformer
IILoadingPlugin (immersiveintelligence-core-0.3.0.jar)
  pl.pabilo8.immersiveintelligence.common.asm.IIClassTransformer
WitcheryLoadingPlugin (WitcheryResurrected-1.12.2-0.5.2.4-forge-all.jar)
  net.msrandom.witchery.asm.WitcheryLoadingPlugin$Transformer
	GL info: ' Vendor: 'Intel' Version: '4.6.0 - Build 30.0.101.1994' Renderer: 'Intel(R) UHD Graphics'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)

	Patchouli open book context: n/a
	Launched Version: 1.12.2-forge-14.23.5.2859
	LWJGL: 2.9.4
	OpenGL: Intel(R) UHD Graphics GL version 4.6.0 - Build 30.0.101.1994, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: No
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Lich's+3D+Wands.zip
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz

**Comment by DonBruce64** [comment]
Not sure which commit fixed this, but it's confirmed fixed.  I know I changed the code at some point to account for this, as I was not resetting the recipeIndex on changing items, so it'd be 1 on one item, but that didn't exist on another.

**Comment by DonBruce64** [comment]
Fixed in V22.7.0.
