### ISSUE TITLE
[1.16.5] - Starter sticks on in some cases

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1559]
This issue applies to the  UNU Dynometer, but likely also any other vehicle that VM's the starter variable.

Here is the VM block:
```
		{
			"variable": "engine_starter_1",
			"animations": [
				{
					"animationType" : "translation",
					"variable" : "EngineON",
					"axis" : [0, 0, 1]
				},
				{
					"animationType" : "translation",
					"variable" : "engine_running_1",
					"axis" : [0, -1, 0]
				},
				{
					"animationType" : "inhibitor",
					"variable" : "fuel",
					"clampMin": 0.01,
					"clampMax": 1
				},
				{
					"animationType" : "translation",
					"variable" : "!unuisbest",
					"axis" : [0, 0, 1]
				}
			],
			"minValue": 0,
			"maxValue": 1
		}
```

In 1.12.2 this works as intended, however in 1.16.5 the starter sticks on when reloading the world with the `EngineON`. In 1.12.2 the sound plays for an instant, suggesting that on 1.12.2 the variable is 1 for a moment, but something 'triggers' an update that is not happening in 1.16.5.

In 1.16.5, if I turn the engine off and back on again, it is fine until the world is reloaded.

To replicate, put an engine on the UNU Dynometer (UNU Parts Pack), fuel it, open the panel at the back and press the lower green button to t urn on the engine, then reload the world.

**Comment by LauraDarkez** [comment]
i didnt get it to stick when i relogged

**Comment by DonBruce64** [comment]
I couldn't get it either, so I think it might already be fixed?  Will close and can re-open if needed.
