### ISSUE TITLE
[1.16.5] - Cant insert an indicators in survival

### ISSUE THREAD

**Issue by Azimkin** [DonBruce64/MinecraftTransportSimulator#1566]
When u want to insert an indicator into car in survival you can't do this.

https://user-images.githubusercontent.com/112006710/223975887-cc1c3a60-95fa-4500-999c-1552e403f78b.mp4

**Comment by DonBruce64** [comment]
Please post beta bugs on Discord, this tracker is for relese bugs only.

**Comment by DonBruce64** [comment]
That being said, this is fixed as of latest commit.
