### ISSUE TITLE
[1.16.5] - Fuel pumps don't display fuels from immersive petroleum.

### ISSUE THREAD

**Issue by Azimkin** [DonBruce64/MinecraftTransportSimulator#1567]
Fuel pumps don't display fuels from immersive petroleum

https://user-images.githubusercontent.com/112006710/223980764-910b49c9-f415-4914-8859-fa480a5e19c2.mp4

But cars can ride on fuels from the mod.

**Comment by DonBruce64** [comment]
Addressed in 22.8.0.
