### ISSUE TITLE
[BUG] 1.12.2 mod using client function on server

### ISSUE THREAD

**Issue by UTrosh** [DonBruce64/MinecraftTransportSimulator#1570]
The mod use net.minecraft.world.World.func_72971_b(F)F in minecraft server, but this is a client methods.
(at WrapperWorld: 645)

[crash-2023-03-15_12.11.00-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10980501/crash-2023-03-15_12.11.00-server.txt)

**Comment by DonBruce64** [comment]
Addressed in 22.8.0.
