### ISSUE TITLE
[BUG] Weird crash on 1.16.5, possibly related to water-wheels.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1571]
Need to test with a less janky water wheel such as the OCP pontoons, ideally to rule out variables such as, well, variable modifiers.

[crash-2023-03-15_21.45.34-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/10985927/crash-2023-03-15_21.45.34-client.txt)

**Comment by DonBruce64** [comment]
I thought I fixed all of these issues, as I literally had this happen to me during dev building.  I must've missed one...

**Comment by DonBruce64** [comment]
And fixed.  Strange this one didn't show up before.

**Comment by DonBruce64** [comment]
Addressed in 22.8.0.
