### ISSUE TITLE
[ENHANCEMENT] Part transfer, drop and pickup.

### ISSUE THREAD

**Issue by TonySokachu** [DonBruce64/MinecraftTransportSimulator#1572]
It would be like this: one vehicle is passive; most likely a container trailer or truck, they can lose or gain possesion of parts when the "Active" vehicle requests a part transfer.

The button in the Vehicle's pannel should be; by default, called "Attach" or "Detach".

As of picking up:
When you press the "attach" button it would first check for any passive vehicles that awaites detach requests, if the result value is false, then it searches for an entity(part) on the ground, in an 2blocks radius; and if the result value is true, then it attaches the part in the given posission.

As of dropping:
When you press the "detach" button it would first check for any passive vehicles that awaites attach requests, if the result value is false, then it drops the part on the ground/air, at current y level and facing preset of the vehicle (north/south/est/west)

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
