### ISSUE TITLE
MTS preventing MC from starting

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1573]
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/11012642/latest.log)

**Comment by BlazeWolf1122** [comment]
where the heck was this when i was looking for it?
https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-General-File-Structure
It's nowhere to be found here, if anything there should at least be mention of it here, the very spot you'd be looking when you're planning to choose a file structure

**Comment by DonBruce64** [comment]
It's linked in the spot where everything else is in that file.  The Master File page here https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-General-Master-File.

This is literally the second link in the introduction page (the first being model formatting).  The introduction being the first thing a new user should be going.

Additionally, your File Structure link is linked to by the Master File page.  So the only way you would have gotten there is to either have clicked on the Master File page and then ignored that page, or you went browsing manually on the side-bar.  And if you did that, you should note that the Master File page is above the File Structure page, ergo, you should have the former open while looking at the latter.

Animation Variables page is the same.  It doesn't link to the Decor, Vehicles, and whatnot pages.  Those link to it as it's a sub-set of those.
