### ISSUE TITLE
[ENHANCEMENT] master or batt switch

### ISSUE THREAD

**Issue by UTrosh** [DonBruce64/MinecraftTransportSimulator#1574]
Add a "master" or "batt" button, which allows you to activate/deactivate the battery of vehicles (planes, cars, etc.)

**Comment by DonBruce64** [comment]
What are you wanting to use this for?

**Comment by UTrosh** [comment]
It just to add more realistic thing

**Comment by DonBruce64** [comment]
No no, specifically what are you looking to do with it?  What realistic functions?

**Comment by UTrosh** [comment]
I would like a button/switch in the panel which allows to activate the main current of the vehicle (master switch), for example we will not be able to start the engine / lamps without the master being on

**Comment by DonBruce64** [comment]
Ah, in that case what you can do is make a customVariable, then, if it's 0, you turn off any engine magnetos or starters that show up.  This is something that can happen with current custom panels and variableModifiers, and I don't see a need to add internally because of this.

**Comment by boot2big** [comment]
The newest version of IVV even uses this with the IVLabs ACIVE! The on-board computer (hidden seat driver) is able to activate a drivers seat control lockout in the event that the interior cabin is compromised. (You can hide all the buttons from the driver's seat)
