### ISSUE TITLE
[Enhancement] Customizable wheel climb value

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1576]
I would've been convenient if we could cap the height to which each wheel can climb
that would allow to make some wheels that can only go on a ( by minecraft standards) smooth roads and offroad wheels that can climb more than 1 block. It also would solve the issue with vehicles climbing to the roof and through it

**Comment by DonBruce64** [comment]
Addressed in 22.8.0.
