### ISSUE TITLE
[BUG] Laser guidance only works with vehicles

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1577]
Laser guided missiles only work properly when you fire them from vehicle. 
When you fire them from handheld, they work visually, so it looks like bullet follows your cursor, but actual bullet does not change it's course and flies as if it was unguided
When it's on part, not vehicle (stationary guns) It's also somewhat broken, but bullet does change it's trajectory.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
