### ISSUE TITLE
1.16.5 Vehicle Bench crafting ingredients not showing

### ISSUE THREAD

**Issue by LippBrot20** [DonBruce64/MinecraftTransportSimulator#1580]
I am playing on an Aternos server and as the title says, crafting ingredients are not showing up. It just shows red squares. Here is the log:
(note that we removed mrcrayfish vehicle mod)
[https://mclo.gs/aWIOLq0](url)

**Comment by DonBruce64** [comment]
That link is invalid.  Can you re-upload?  Also, I need a picture of the crafting bench.

**Comment by LippBrot20** [comment]
Log: https://mclo.gs/sjQwXbh

Also sometimes it just does not show at all. It only works for the blimp and boat. This happens to all packs
![2023-03-25_13 55 39](https://user-images.githubusercontent.com/106226745/227718522-9cda52c0-b583-494e-9571-0671bd383490.png)
![2023-03-25_13 55 48](https://user-images.githubusercontent.com/106226745/227718526-b934ea4b-ad3f-4880-824c-4bd107120067.png)
![2023-03-25_13 56 21](https://user-images.githubusercontent.com/106226745/227718529-02987e7b-43c4-4c54-a6fd-10585a9889ff.png)

**Comment by DonBruce64** [comment]
So with the first one, can you show your inventory?  The red boxes mean you don't have the items in the inventory.  The last two recipes though are invalid, so you'll need to get with the pack author about that, as the message says.

**Comment by DonBruce64** [comment]
Somewhat addressed in 22.8.0, but needs more work to be complete.

**Comment by Tampastrike** [comment]
Official parts pack also experiencing this issue, survival crafting disabled.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
