### ISSUE TITLE
[ ENHANCEMENT ] Block Placer effector

### ISSUE THREAD

**Issue by TonySokachu** [DonBruce64/MinecraftTransportSimulator#1585]
They use items from linked crates, and place them in the world, "effecting the ground".
They would have a ["blockPerSecond": 1.0] so that you can define the speed of a block placer. For reference, if you are making an concrete pump, it would place _concrete powder_, and these blocks, as soon as they feel the air they become entities, so instead of having tons of gravel and sand blocks getting out in one second - .

They can also use modded blocks, and every block that's put in the linked inventory crate.
Almost all of these informations are from the discord chat. so you don't have to search for em.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
