### ISSUE TITLE
[BUG] Config option heliAutoLevel conflicts with panel autopilot

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1591]
heliAutoLevel behavior conflicts with VTOL/helicopter autopilot and will cause the aircraft to wobble from side to side (though this appears to be mostly visual, or at least the autopilot does a good job of keeping the helicopter in one spot despite the artificial turbulence)
When hAL is disabled, autopilot will function as expected by keeping the helicopter in its mostly-exact current position, upright and at the same altitude.

Bonus bug: heliAutoLevel remains active even after exiting the helicopter, which makes viewing the main bug a lot easier. The vehicle also won't change its behavior if the ex-pilot disables heliAutoLevel while outside of the helicopter, as the lack of an arse-to-seat connection means the vehicle won't be notified of this... or something.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
