### ISSUE TITLE
[ENHANCEMENT] Decor blocks with text ought to be locked behind the wrench

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1592]
Similarly to how gas pump/charger prices require you to right-click the pump with a wrench, decor blocks with text should require you to right-click the block with a wrench to edit it. Useful for things with text that also need to use `activated` or `clicked`

**Comment by DonBruce64** [comment]
But this won't work for signs, where you have to hold a wrench to _remove_ the sign from the pole.

**Comment by boot2big** [comment]
Hmm, fair point. Maybe behind shift-RMB instead?

**Comment by DonBruce64** [comment]
El done.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
