### ISSUE TITLE
[BUG?] Scaling vehicles also scales the player size.

### ISSUE THREAD

**Issue by TonySokachu** [DonBruce64/MinecraftTransportSimulator#1603]
i've seen this, if you scale a vehicle by 1.2, the player will also be scaled by that size when sitting.
Most people want to scale their 1:1 content packs to fit steve size, but they endup scaling themselves.
I think this should not be a thing and scaling should only scale the vehicle, nor the player.

**Comment by DonBruce64** [comment]
That is a correct thought process, will fix.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
