### ISSUE TITLE
[BUG] Other players turn into penguins when shifting, while another player is riding/controlling a vehicle

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1605]
![2023-04-16_00 33 06](https://user-images.githubusercontent.com/53581325/232266809-8f79dd8d-60cb-48f0-89ea-5a47f2d0c06d.png)

laura hit me with cat uwu

**Comment by DonBruce64** [comment]
Which version of MC?

**Comment by boot2big** [comment]
1.12.2, apologies.

Immersive+Vehicles-1.12.2-22.8.0

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
