### ISSUE TITLE
[BUG?] Vehicles (or at least cars) don't let you push the throttle with 2 or more active player controllers

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1609]
Rudder (and presumably other control surfaces, not tested planes yet) works as expected, brakes will flutter causing vehicle brake lights to flash on and off though, and the throttle is completely unusable for all but the last person to enter an isController seat.

Not major considering guidance controls work as expected, and the oh-shit controls still function despite visually being wonky.

**Comment by DonBruce64** [comment]
So, this is going to be normal on cars since they either have a 0 or 1 throttle, and you don't know which state to pick because whose keyboard is the right one?  That being said, this should NOT happen on anything with incremental throttle, like planes or some boats.  Can you confirm?

**Comment by boot2big** [comment]
Allow me to load up one'a'dem fancy LAN worlds and I shall check, this was a bug I found during regular multiplayer gameplay so I hadn't done the usual bout of testing.

**Comment by boot2big** [comment]
https://user-images.githubusercontent.com/53581325/232353653-518f5b21-2ce0-4888-b476-df97d302f47a.mp4

Confirmed, seems to work A-OK with planes. The control surfaces and (incremental) throttle all worked as expected, at least when both players are nicely sharing and are on KB+M. Likely will not work as expected if both are fighting over the control surfaces, but you can't turn a wheel or rudder in two directions at once. Likewise the smarter player will just know to use the control surface that stops the entire vehicle!

**Comment by DonBruce64** [comment]
Yup, that's how it's designed.  If both have joysticks then you're both hosed since it won't know who to pick, but there is a keybind to inhibit controls for just this reason.  Not used barely at all though, since I don't know many people who actually have co-pilots on flights that much.  Most are solo, even in the larger planes.

Marking as nottabug.
