### ISSUE TITLE
[BUG] Weapons on parts(?) only fire once until deactivated and reactivated

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1610]
May have something to do with forceAllLinks, unsure though.
Beta build will be provided to assist with testing
https://github.com/boot2big/immersive_vehicles_vanity/blob/main/out/Immersive%20Vehicles%20Vanity-1.12.2-2.3.0.jar

Video showcasing actual VS expected behavior (Black&gray KARR is expected as it is gun-on-vehicle, white car is the actual gun-on-parts behavior)

https://user-images.githubusercontent.com/53581325/232358551-07735d53-653c-4ff3-b765-c4dfad0e6728.mp4

Make sure to use the Devom Custom kit to mount guns onto a part! This requires you to open the hood to access and/or load the guns. (Or alternatively you can test this with the license plate slotted Weaponized Mounting Gear part, which takes the same missile launcher and dual machine gun. This part suffers from the same issue.)

**Comment by boot2big** [comment]
P.S: Sorry for not telling you that I was going on break, I was not there to respond to your message. Unfortunately it did not occur to me, plus I had forgotten to tell various other PAs as well. I understand that this is how things will be going forth though and will abide accordingly.

**Comment by DonBruce64** [comment]
https://user-images.githubusercontent.com/15241611/233509155-e1485efb-6673-4635-8f1f-0ae25842b550.mp4

This appears to not be an issue with the gun on the licence plate though?

**Comment by boot2big** [comment]
Try using this with gun on the Devom Custom? Small note, you will need to open the hood to install and/or reload the guns.

**Comment by boot2big** [comment]
Okay, weeird. It works _now,_ it shoots normally. I have no idea where to trace the route cause now, so maybe mark this as invalid for now... I swear it didn't work earlier though.
