### ISSUE TITLE
[BUG] Hang when engine with propeller is mounted on a world-placed part (such as a bench)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1611]
[crash-2023-04-16_22.45.41-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/11245700/crash-2023-04-16_22.45.41-server.txt)
Internal server will crash, client will simply hang until ended externally

**Comment by boot2big** [comment]
To replicate this with IVV, place the `IVLabs "Shortstack" Experimental Motor` jet onto the Engine Bench, as it comes with an invisible propeller rotor by default for the Jetpack.

**Comment by DonBruce64** [comment]
I thought I caught all the not-vehicle crashes for parts.  It would appear I missed one.  le fixed.

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
