### ISSUE TITLE
Turret Rotation Still Broken

### ISSUE THREAD

**Issue by PawelW2006** [DonBruce64/MinecraftTransportSimulator#1612]
Turret rotation issue which i described:
https://github.com/DonBruce64/MinecraftTransportSimulator/issues/1532#issuecomment-1483812664

Is still a thing as of Version V25 1.12.2, nothing has changed. The turret rotation was fixed in the Beta version on the Discord server but is again broken in the full release.

**Comment by DonBruce64** [comment]
That's a @SnailPerson question.

**Comment by DonBruce64** [comment]
I have been told this is still an issue and will be fixed next release.

**Comment by DonBruce64** [comment]
Fixed with new OCP update.
