### ISSUE TITLE
[BUG] Arrows go through hitboxes on 1.16.5

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1614]
Arrows on 1.16.5 ignore hitboxes and go straight through. Issue is not present on 1.12.2. Tested with both versions on the same vehicle

1.16.5

https://user-images.githubusercontent.com/46074580/233798069-9dc65f7a-8718-4c22-a5a6-5d52ef25fc61.mp4

1.12.2

https://user-images.githubusercontent.com/46074580/233798085-9c8b3a47-7218-4423-917f-26937a88b6f5.mp4

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
