### ISSUE TITLE
[BUG] simpleThrottle holds both throttle and brake when at a standstill

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1616]
https://github.com/boot2big/immersive_vehicles_vanity/issues/18

https://user-images.githubusercontent.com/53581325/235240539-76a67c38-9804-47d2-876b-769f3fa0e0a6.mp4

**Comment by boot2big** [comment]
https://user-images.githubusercontent.com/53581325/235241237-205beb0d-eddf-413e-994d-e328b02b5ce9.mp4

More test footage

**Comment by DonBruce64** [comment]
Very strange.  Does it happen if you never hit the brake key?  Like if you just coast to a stop?  I'm wondering if it's something to do with shifting where the system thinks you shifted but you didn't.

**Comment by boot2big** [comment]
I don't recall, I think that's what I had caught in the second video. All I know for sure is that it happens if you tap the throttle while already stopped.

In particular this bug behaves with my veihcles in the way it does, because holding the brakes and gas will always force them to do a burnout. However this bug still occurs on other vehicles as long as simpleThrottle is enabled, it just won't show as easily.

**Comment by DonBruce64** [comment]
Yeah, I've seen it sometimes on normal vehicles where they refuse to move.  I always thought it was something to do with the parking brake not releasing, but now I know it's something else.

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
