### ISSUE TITLE
Items that don't have a definitions section don't work with `materialLists`

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1617]
If an item doesn't have a definitions section, the LCs create one that has an `extraMaterialLists` with only one entry, which then mismatches if you have more than one entry in `materialLists`.

I would suggest doing the selection of a valid list first, _then_ combining the base list with the extra list to reduce mismatching if possible.

![image](https://user-images.githubusercontent.com/36775575/235268923-2bcb0bb3-d874-46ca-83a3-98cfc81c10b4.png)

**Comment by DonBruce64** [comment]
Eh, the correct thing to do is to make LCs smart enough to notice the multiple `materialLists` and correct for that in the auto-generation of the `extraMaterialLists`

**Comment by DonBruce64** [comment]
Addressed in 22.9.0.
