### ISSUE TITLE
Joystick not working 1.16.5

### ISSUE THREAD

**Issue by ScrapUSS** [DonBruce64/MinecraftTransportSimulator#1618]
[BUG}I'm playing on 1.16.5. I go into the control settings, and instead of the joystick control settings tab, I see that the IV did not initialize the joystick. It's about USB. But I turned everything off, connected the keyboard and mouse while the game was starting (the Joystick was connected before starting), but I got an error. I did it without extraneous mods, and the original pack, also tried version 22.7.0 instead of 22.8.0, but still nothing changed!

If there is a way to play with joystick mod IV on 1.16.5 please tell me. I don't understand

**Comment by ScrapUSS** [comment]
Yes, sorry about that, i forgot to remove the question, he decided. The problem is "Classic joystick" switch

Also, you can add shifter settings? Like this: You press the button and turn on the gear like an h shifter

**Comment by DonBruce64** [comment]
Huh?  What about the Classic Joystick?

And no, there are too many gear configurations to make an H shiffter a reality.

**Comment by DonBruce64** [comment]
Closing due to no response.
