### ISSUE TITLE
[BUG?] Sounds are quieter in first person vs third person while on foot

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1619]
Unsure if related to isOpenTop or not, in fact I almost wonder if it is inverted as sounds do _not_ get quieter in first person, whilst in a vehicle that I know isn't an open top.

As of Immersive+Vehicles-1.12.2-22.8.0

**Comment by SnailPerson** [comment]
Can confirm, sounds are louder when walking in third person.
Also happens when sitting in a vehicle iirc

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
