### ISSUE TITLE
Getting into a vehicle and starting the engine crashes the game

### ISSUE THREAD

**Issue by joebieden23** [DonBruce64/MinecraftTransportSimulator#1624]
https://pastebin.com/tKcJrfAV, here is the crash report.

**Comment by joebieden23** [comment]
Did some extra testing and it seems that custom fuels cause this on the Renault ft-17 for whatever reason.

**Comment by DonBruce64** [comment]
Strange, this shouldn't be happening.  Can you post your mtsconfig.json file?  And if you're playing on a server, I'll need the one from the server and your client.

**Comment by SnailPerson** [comment]
Does this happen to other content packs as well? 
Im suspecting this might be an internal issue or mod conflict, not a pack one...

**Comment by DonBruce64** [comment]
Ah, now having your configs not match, that's 100% going to break things.  Closing as this isn't a code issue, it's a setup issue.
