### ISSUE TITLE
[Bug] Vehicle GUI stays on screen after crash - BETA 22.10.0 - 1.16

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1626]
https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/ba5420b6-99b0-49c0-80d1-fc30d85e658d

**Comment by DonBruce64** [comment]
Don't know how this got fixed, but it somehow got fixed in recent commits.

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
