### ISSUE TITLE
[BUG] Bullet desync when moving and shooting

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1629]
https://github.com/DonBruce64/MinecraftTransportSimulator/assets/46074580/d9972ab4-d928-4b1e-9337-5623767a92f3

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/46074580/94b67f9f-43db-40a1-8638-93125e2176ee

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
