### ISSUE TITLE
A lack of benches

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#163]
Here's your bug report :P

Basically, bullets and custom parts can't be crafted yo!

![Capture1063](https://user-images.githubusercontent.com/36775575/62418416-34580000-b61d-11e9-8aa0-2c8a20e254cd.PNG)

**Comment by DonBruce64** [comment]
Will get to it when I can.  Either with a bullet-specific bench or using the one for the guns.  Probably the one for the guns given the lack of guns in the mod.

Not sure yet about the decor bench.

**Comment by DonBruce64** [comment]
Tried to add bullets to the benches in V15.6.0, but got crashes because bullets don't have any models.  Might need to enforce the 3D bullet system after all.  Bleck...

**Comment by DonBruce64** [comment]
Bullets are now craft-able in V15.8.0.
