### ISSUE TITLE
Possible incompatibility with CMDCam

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1630]
https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/de94c6f5-decc-4aff-8bcb-0b81f88742fe

Issue had previously cropped up with Optifine installed, although after removing it this bug still occurs. Uuurggh! And only with CMDCam's most useful mode too.

(This bug occurs when the camera is set to /cam mode outside)

**Comment by DonBruce64** [comment]
Hrm, I *might* be able to fix this.  What's the MC version?

**Comment by boot2big** [comment]
1.12.2

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
