### ISSUE TITLE
[Bug] Emissive things become purple sometimes

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1632]
Emissive things sometimes become purple, i noticed that bug some time ago already, but now i found a reliable way to reproduce it so i'm ticketing it. They become purple when you are above 256

![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/46074580/fc392dd4-9878-467d-8ad5-bcc58d36cbc9)

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
