### ISSUE TITLE
[Bug] Particles phase through blocks

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1633]
Long standing bug. Particles of any kind do collide with blocks, but eventually phase through them for some cursed reason.
pls fix
pls fix
1.19 fabric RTX raytracing physics update when 
among us 3am mode when
please make pack mod bedrock add-on for me Don, i want 100000009000$ spaceship that goes 69k blocks per second it should be 1000 blocks long and have free bucks generator

anyways, here's bug footage uwu.

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/2abf3cab-26cd-4ed2-80fc-731c15e1034d

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
