### ISSUE TITLE
[Bug] Armor hitboxes damage forwarding

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1636]
Armor hitboxes forward damage to vehicle when you punch them with hands. May also be the case for arrows. Armor hitboxes shouldn't forward any damage, not just bullet damage

**Comment by boot2big** [comment]
Isn't that the intention?  If you don't want a box to forward damage to the vehicle you simply give its collision group a health value? At least if I'm understanding your ticket correctly, that is.

**Comment by DonBruce64** [comment]
yeah, but if the armor blocks the damage, then it shouldn't forward it.  But external damage bypasses armor checks because those are in the bullet code, not the damage code.  I need to move it over to fix this.

**Comment by DonBruce64** [comment]
Addressed in 22.10.0.
