### ISSUE TITLE
[Bug] Skin packs do not remove definitions after you remove them

### ISSUE THREAD

**Issue by Wartich** [DonBruce64/MinecraftTransportSimulator#1637]
When you remove the skin pack, definitions it added stay and skin items appear in the pack tab,but they don't work probably because they don't have textures

**Comment by boot2big** [comment]
Are you using devmode? IIRC this is how such definitions get lobbed in, I've made that mistake more than a few times myself

**Comment by DonBruce64** [comment]
Confirmed this is how this happens.
