### ISSUE TITLE
[Reminder] Wiki Entry for setting up/ updating Packs to 1.16

### ISSUE THREAD

**Issue by Colt44Magnum** [DonBruce64/MinecraftTransportSimulator#1638]
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/51977107/52706a46-4ce3-49fb-819a-a04113075a73)

Ticket made to remind Don about a Wiki Entry pertaining to the steps needed to set up a 1.16 Pack for the mod

**Comment by DonBruce64** [comment]
Added to the introduction page.  Though really it just tells you to get scripts from the OCP that will do all the updating for you.  Why document when you can automate?
