### ISSUE TITLE
Vehicle fuel level only updates while seat is unoccupied in Creative mode

### ISSUE THREAD

**Issue by BenjiroDaimon** [DonBruce64/MinecraftTransportSimulator#1639]
When driving vehicles in Creative mode, the fuel level doesn't update while the player is sitting in the driver's seat, regardless of the config setting. Works fine on survival, or when the seat is unoccupied.

**Comment by BenjiroDaimon** [comment]
To further clarify, if the player drives the vehicle in Creative mode, the fuel usage that would have occurred while driving will be reflected after the player leaves the vehicle.

**Comment by DonBruce64** [comment]
This is per design.  Much like how a creative player doesn't lose their items when placing blocks, or when equipping vehicles, creative players can fly vehicles without needing to fuel them.
