### ISSUE TITLE
[1.12.2] Bench recipe ingredients with metadata -1 are replaced with minecraft:air

### ISSUE THREAD

**Issue by QBFreak** [DonBruce64/MinecraftTransportSimulator#164]
## Description

Using any of the IV benches to craft a part or vehicle where the json specifies an ingredient with metadata of `-1` results in that ingredient being replaced with `minecraft:air` in the bench GUI and not required when crafting in survival.

As an experiment, I edited one of the JSONs to use specific metadata (`0`) instead of `-1` and after restarting the game all the ingredients were visible for that vehicle.

## Steps to reproduce

- Install Immersive Vehicles and MTS Official Vehicle Set
- Place and open Drafting table
- Browse to GMC Brigadier
- Observe that the only visible ingredient is 2x `Ink Sac`
- Mouse over empty slots to the left of `Ink Sac`, observe that they are `Air`
- Browse other vehicles, note they are missing various ingredients as well

I only chose the GMC Brigadier because it's a really obvious example with the majority of it's ingredients missing. The issue is not limited to just the drafting table or the Official Vehicle Set. It appears to be affecting other vehicle and parts packs as well.

## Expected Behavior

All ingredients should properly display in the various benches, and be required from the user if crafting in survival.

## Details
|| Versions |
|--|--|
| **Minecraft:** | 1.12.2 |
| **Forge:** | 14.23.5.2836 |
| **Immersive Vehicles:** | 14.3.1 |
| **MTS Official Vehicle Set:** | v11 |
| **Other mods:** | No, reproducible with just IV and the official vehicle set |

**Comment by DonBruce64** [comment]
Yup, that's a bug.  In fact, it's related to the bug where the crafting bench recipes in the manual don't show the correct dye for themselves.  Will work towards fixing this in the next update.

**Comment by DonBruce64** [comment]
Corrected in V15.0.0.
