### ISSUE TITLE
When dismounting from a seat with no dismountPos defined, MTS will unmount players under collision boxes

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1647]
I unfortunately forgot to mention this before it got released in 22.10.0, sorry...
The main thing is that it hadn't occurred _before_ this release, and that it gets players stuck in the ground whenever they exit from a vehicle.

**Comment by DonBruce64** [comment]
Is this MC 12, MC 16, or both?

**Comment by boot2big** [comment]
Have only tested on MC 12, will test on 16 in a moment or two.

**Comment by boot2big** [comment]
https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/8c0f5959-84e6-4971-9252-d760901734b0

Confirmed, still occurs even on MC 16

**Comment by boot2big** [comment]
Additionally found a bonus bug while logging back in, unsure if whether to file under its own ticket or not...

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/44a0db0c-02a2-4147-ac8e-aa199e87a4de

This seems to occur with handguns as well. Still V22.10.0

**Comment by DonBruce64** [comment]
It should be, as that's for gun collision boxes, which shouldn't even be a thing MC is considering.  However, that issue will 100% go away with the EOBETA methinks since that beta removes the gun as an entity that MC knows about.  Can't collide with what you don't know exists!

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
