### ISSUE TITLE
Animations should work on textObjects in instruments

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1649]
Alternative title: There's a secret method for animating textObjects on instruments that nobody has told me yet. :stuck_out_tongue_closed_eyes: 

In all seriousness though, surely this should work, right? (It doesn't, but it just feels like it should.)
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/feca73e1-355d-434f-93e0-c35b6d452ada)

P.S: Can be backburnered to focus time on squashing bugs, particularly with EOBETA

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
