### ISSUE TITLE
Suggestion for update

### ISSUE THREAD

**Issue by MinecraftKen59** [DonBruce64/MinecraftTransportSimulator#165]
Would it be possible to add support for XBox one controllers?

**Comment by DonBruce64** [comment]
Uuuh, they should already be supported, yeah?  How do they connect to the PC?

**Comment by SnaveSutit** [comment]
Usually via Bluetooth or usb. Mine works just fine

**Comment by DonBruce64** [comment]
Closing due to lack of response from user.
