### ISSUE TITLE
shift + f3 crashes when MTS is installed with Optifine (latest 1.12.2 MTS ver)

### ISSUE THREAD

**Issue by HighQGithub** [DonBruce64/MinecraftTransportSimulator#1651]
Pretty self explanatory but when Optifine is installed in conjunction with Immersive Vehicles (latest ver for 1.12.2), pressing shift + f3 crashes the game.

**Comment by DonBruce64** [comment]
Does this happen without Optifine installed?

**Comment by HighQGithub** [comment]
Just tested, it doesn't crash w/out optifine

**Comment by HighQGithub** [comment]
Just so you know the crash only occurs post version 22.7.0, version 22.6.0 is completely fine.

**Comment by DonBruce64** [comment]
Understood.  I'll need a crash report to figure out why it's crashing.  I know the profiler is to blame, but there's a lot of profiler things so I need to know where to look.

Also: Can you do a test where you don't have any vehicles or guns in a fresh world and tell me if this happens?  If not, can you then put down a decor block like a cone and tell me?

**Comment by DonBruce64** [comment]
Closing due to no response and no crash report.
