### ISSUE TITLE
Putting parts in a validSubNames slot and re-coloring the vehicle causes that part to disappear on reload

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1654]
Part gets Detroited either when the world is reloaded, or when the vehicle is wrenched and respawned.

**Comment by DonBruce64** [comment]
This brings up the question of what to do.  Should they get yeeted during the painting process, or is it acceptable for you to paint your ex-police-interceptor taxicab yellow and keep the noisy bois and party strobes?

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
