### ISSUE TITLE
[Bug] Placing parts onto vehicles with transferVariable causes a crash

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1656]
When I place a pallet from a forklift onto a truck, the game crashes. Pallets can be placed on the ground just fine. When I reload the game, sometimes the pallet is on the truck, and sometimes it is on the forklift.

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/36775575/aad7e2bc-ab2e-48a4-b7f0-7b37fca6d2cb

[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/11673346/latest.log)

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
