### ISSUE TITLE
Hitboxes don't seem to let you click them if both you and the box itself are outside of the entity's white box radius?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1657]
https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/7606221d-e174-4eed-88c1-b3a722c98f6d

V22.10.0, 1.12.2

**Comment by boot2big** [comment]
Come to think of it, I thought they should've been within the white box anyways? As in, the white box already expands to accommodate like, a tenth of the box... but if I open a door on *both* sides the box will expand to fit both of them, and they'll both be equally as clickable.

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
