### ISSUE TITLE
Crash when seating a vehicle 

### ISSUE THREAD

**Issue by StoneGuy76** [DonBruce64/MinecraftTransportSimulator#1658]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2023-06-10 05:55:50 MDT
Description: Ticking entity

java.lang.IndexOutOfBoundsException
    at java.nio.Buffer.checkIndex(Buffer.java:540)
    at java.nio.DirectByteBuffer.get(DirectByteBuffer.java:253)
    at org.lwjgl.input.Keyboard.isKeyDown(Keyboard.java:407)
    at mcinterface1122.InterfaceInput.isKeyPressed(InterfaceInput.java:189)
    at minecrafttransportsimulator.systems.ControlSystem$ControlsKeyboard.isPressed(ControlSystem.java:671)
    at minecrafttransportsimulator.systems.ControlSystem.controlCamera(ControlSystem.java:139)
    at minecrafttransportsimulator.systems.ControlSystem.controlAircraft(ControlSystem.java:295)
    at minecrafttransportsimulator.systems.ControlSystem.controlMultipart(ControlSystem.java:124)
    at minecrafttransportsimulator.entities.instances.PartSeat.updateRider(PartSeat.java:332)
    at mcinterface1122.BuilderEntityLinkedSeat.func_184232_k(BuilderEntityLinkedSeat.java:121)
    at net.minecraft.entity.Entity.func_70098_U(Entity.java:2020)
    at net.minecraft.entity.EntityLivingBase.func_70098_U(EntityLivingBase.java:2489)
    at net.minecraft.entity.player.EntityPlayer.func_70098_U(EntityPlayer.java:461)
    at net.minecraft.client.entity.EntityPlayerSP.func_70098_U(EntityPlayerSP.java:1022)
    at net.minecraft.world.World.func_72866_a(World.java:1991)
    at net.minecraft.world.World.func_72870_g(World.java:1958)
    at net.minecraft.world.World.func_72866_a(World.java:2056)
    at net.minecraft.world.World.func_72870_g(World.java:1958)
    at net.minecraft.world.World.redirect$zbe000$updateEntity(World.java:4123)
    at net.minecraft.world.World.func_72939_s(World.java:1762)
    at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: mts:mts_entity_seat (mcinterface1122.BuilderEntityLinkedSeat)
  Entity ID: 232004
  Entity Name: entity.mts_entity_seat.name
  Entity's Exact location: 30.56, 71.85, 179.68
  Entity's Block location: World: (30,71,179), Chunk: (at 14,4,3 in 1,11; contains blocks 16,0,176 to 31,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: [EntityPlayerSP['_Stone_Guy_'/230163, l='MpServer', x=30.56, y=71.85, z=179.68]]
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {Motion:[0.0d,0.0d,0.0d],entityUUIDMost:-5851539879521464579L,UUIDLeast:-6514454793728826887L,Invulnerable:0b,Air:300s,OnGround:0b,Dimension:0,PortalCooldown:0,Rotation:[0.0f,0.0f],UpdateBlocked:0b,FallDistance:0.0f,UUIDMost:-5444062452993932800L,Pos:[30.560504261646326d,71.84514190996947d,179.67691243825502d],Fire:-1s,entityUUIDLeast:-6496202182993927930L}

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['_Stone_Guy_'/230163, l='MpServer', x=30.56, y=71.85, z=179.68]]
  Chunk stats: MultiplayerChunkCache: 3657, 3657
  Level seed: 0
  Level generator: ID 00 - default, ver 1. Features enabled: false
  Level generator options: 
  Level spawn location: World: (16,64,184), Chunk: (at 0,4,8 in 1,11; contains blocks 16,0,176 to 31,255,191), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
  Level time: 687 game time, 687 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 124 total; [EntitySheep['Авечка'/230666, l='MpServer', x=-43.50, y=64.00, z=208.50], EntitySkeleton['Шкілет'/230665, l='MpServer', x=-47.30, y=48.00, z=212.36], EntitySkeleton['Шкілет'/230664, l='MpServer', x=-43.52, y=49.00, z=214.05], EntitySheep['Авечка'/230671, l='MpServer', x=-47.50, y=68.00, z=238.50], EntityCreeper['Крыпер'/230167, l='MpServer', x=19.50, y=32.00, z=188.50], EntityCreeper['Крыпер'/230166, l='MpServer', x=17.50, y=32.00, z=187.50], EntityZombie['Мярцвяк'/230678, l='MpServer', x=35.50, y=48.00, z=196.50], EntityZombie['Мярцвяк'/230165, l='MpServer', x=19.50, y=32.00, z=187.50], EntityBat['Кажан'/230164, l='MpServer', x=12.87, y=40.66, z=200.69], BuilderEntityExisting['entity.mts_entity.name'/230169, l='MpServer', x=25.50, y=70.25, z=185.50], EntityHorse['Конь'/230168, l='MpServer', x=31.33, y=69.00, z=184.28], EntityBat['Кажан'/230175, l='MpServer', x=41.46, y=48.98, z=188.25], EntityBat['Кажан'/230174, l='MpServer', x=38.36, y=50.41, z=187.16], EntityCreeper['Крыпер'/230173, l='MpServer', x=37.50, y=17.00, z=180.50], EntityHorse['Конь'/230178, l='MpServer', x=33.65, y=69.00, z=183.52], EntityHorse['Конь'/230177, l='MpServer', x=33.69, y=69.00, z=184.59], EntityHorse['Конь'/230176, l='MpServer', x=32.79, y=69.00, z=183.17], EntityPlayerSP['_Stone_Guy_'/230163, l='MpServer', x=30.56, y=71.85, z=179.68], BuilderEntityExisting['entity.mts_entity.name'/231743, l='MpServer', x=30.56, y=71.77, z=179.68], BuilderEntityLinkedSeat['entity.mts_entity_seat.name'/232004, l='MpServer', x=30.56, y=71.85, z=179.68], EntityZombie['Мярцвяк'/230734, l='MpServer', x=-7.75, y=12.00, z=114.48], EntitySkeleton['Шкілет'/230743, l='MpServer', x=-15.50, y=15.00, z=120.50], EntitySkeleton['Шкілет'/230742, l='MpServer', x=-15.50, y=15.00, z=119.50], EntityWitch['Ведзьма'/230741, l='MpServer', x=-1.50, y=14.00, z=114.50], EntityItem['item.tile.doublePlant.syringa'/230747, l='MpServer', x=-10.69, y=64.00, z=117.80], EntityBat['Кажан'/230746, l='MpServer', x=-2.14, y=15.64, z=116.58], EntityZombie['Мярцвяк'/230745, l='MpServer', x=-6.50, y=15.00, z=113.50], EntityHorse['Конь'/231001, l='MpServer', x=32.17, y=64.00, z=109.96], EntityZombie['Мярцвяк'/230744, l='MpServer', x=-5.50, y=15.00, z=113.50], EntityHorse['Конь'/231000, l='MpServer', x=42.50, y=63.00, z=105.50], EntityCreeper['Крыпер'/230751, l='MpServer', x=-15.50, y=24.00, z=143.50], EntityCreeper['Крыпер'/230750, l='MpServer', x=-25.50, y=32.00, z=130.50], EntityZombie['Мярцвяк'/230749, l='MpServer', x=-25.50, y=32.00, z=134.50], EntityZombie['Мярцвяк'/230748, l='MpServer', x=-20.50, y=41.00, z=136.50], EntityItem['item.item.seeds'/230754, l='MpServer', x=-4.88, y=63.00, z=138.14], EntityZombieVillager['Мярцвяк-селянін'/230753, l='MpServer', x=-15.50, y=37.00, z=130.50], EntityBat['Кажан'/230752, l='MpServer', x=3.56, y=16.85, z=129.53], EntityHorse['Конь'/230759, l='MpServer', x=-26.88, y=64.00, z=163.75], EntityHorse['Конь'/230758, l='MpServer', x=-25.18, y=64.00, z=162.92], EntityItem['item.item.seeds'/231019, l='MpServer', x=74.42, y=64.00, z=148.22], EntitySkeleton['Шкілет'/230762, l='MpServer', x=-6.45, y=50.00, z=138.29], EntityCreeper['Крыпер'/230761, l='MpServer', x=-6.70, y=49.00, z=140.66], EntityHorse['Конь'/230760, l='MpServer', x=-27.50, y=64.00, z=165.50], EntitySkeleton['Шкілет'/231020, l='MpServer', x=53.21, y=50.00, z=180.51], EntityZombie['Мярцвяк'/231027, l='MpServer', x=67.50, y=37.00, z=184.50], EntitySkeleton['Шкілет'/231026, l='MpServer', x=69.50, y=37.00, z=182.50], EntitySkeleton['Шкілет'/231025, l='MpServer', x=90.54, y=60.00, z=166.24], EntityItem['item.item.seeds'/231024, l='MpServer', x=38.90, y=69.00, z=210.45], EntityCow['Карова'/231031, l='MpServer', x=76.50, y=68.00, z=179.50], EntityCow['Карова'/231030, l='MpServer', x=75.22, y=69.00, z=182.14], EntityZombie['Мярцвяк'/231029, l='MpServer', x=75.50, y=53.00, z=191.50], EntityCreeper['Крыпер'/231028, l='MpServer', x=67.50, y=37.00, z=182.50], EntityCow['Карова'/231033, l='MpServer', x=70.84, y=68.00, z=176.53], EntityCow['Карова'/231032, l='MpServer', x=63.77, y=68.00, z=175.50], EntityCreeper['Крыпер'/230783, l='MpServer', x=28.50, y=14.00, z=214.50], EntitySheep['Авечка'/231039, l='MpServer', x=40.44, y=65.00, z=237.45], EntitySheep['Авечка'/231038, l='MpServer', x=40.14, y=66.00, z=236.04], EntitySheep['Авечка'/231037, l='MpServer', x=39.60, y=65.00, z=239.43], EntitySheep['Авечка'/231036, l='MpServer', x=42.26, y=65.00, z=238.52], EntitySheep['Авечка'/231043, l='MpServer', x=50.49, y=69.00, z=225.19], EntityZombie['Мярцвяк'/230786, l='MpServer', x=27.50, y=14.00, z=215.50], EntityBat['Кажан'/231042, l='MpServer', x=72.81, y=33.11, z=206.44], EntityZombie['Мярцвяк'/230785, l='MpServer', x=28.50, y=14.00, z=216.50], EntitySheep['Авечка'/231041, l='MpServer', x=42.50, y=66.00, z=236.50], EntityCreeper['Крыпер'/230784, l='MpServer', x=26.50, y=14.00, z=216.50], EntitySheep['Авечка'/231040, l='MpServer', x=45.51, y=66.00, z=238.60], EntitySkeleton['Шкілет'/230789, l='MpServer', x=19.50, y=20.00, z=241.50], EntitySheep['Авечка'/231044, l='MpServer', x=39.50, y=64.00, z=240.50], EntityZombie['Мярцвяк'/230795, l='MpServer', x=16.50, y=45.00, z=143.50], EntitySkeleton['Шкілет'/230799, l='MpServer', x=11.50, y=46.00, z=150.50], EntitySkeleton['Шкілет'/230798, l='MpServer', x=11.50, y=46.00, z=148.50], EntityCreeper['Крыпер'/230797, l='MpServer', x=25.50, y=46.00, z=141.50], EntityZombie['Мярцвяк'/230796, l='MpServer', x=9.52, y=46.00, z=148.35], EntityChicken['Курыца'/230803, l='MpServer', x=14.18, y=66.00, z=146.51], EntityChicken['Курыца'/230802, l='MpServer', x=3.50, y=65.00, z=151.50], EntityChicken['Курыца'/230801, l='MpServer', x=5.50, y=66.00, z=150.50], EntityChicken['Курыца'/230800, l='MpServer', x=-0.09, y=63.00, z=144.29], EntityHorse['Конь'/230807, l='MpServer', x=-10.35, y=64.00, z=172.65], EntityHorse['Конь'/230806, l='MpServer', x=-13.55, y=64.00, z=171.65], EntityHorse['Конь'/230805, l='MpServer', x=-4.88, y=65.00, z=177.98], EntityChicken['Курыца'/230804, l='MpServer', x=12.89, y=66.00, z=159.37], EntityCreeper['Крыпер'/230811, l='MpServer', x=-25.50, y=62.00, z=182.50], EntitySkeleton['Шкілет'/230810, l='MpServer', x=-27.50, y=62.00, z=184.50], EntityHorse['Конь'/230809, l='MpServer', x=-13.26, y=65.00, z=170.11], EntityHorse['Конь'/230808, l='MpServer', x=-11.23, y=65.00, z=170.24], EntityBat['Кажан'/231070, l='MpServer', x=50.75, y=49.10, z=175.64], EntitySkeleton['Шкілет'/230813, l='MpServer', x=43.50, y=33.00, z=119.69], EntityBat['Кажан'/231069, l='MpServer', x=50.30, y=45.20, z=165.73], EntityCreeper['Крыпер'/230812, l='MpServer', x=-27.50, y=62.00, z=182.50], EntityZombie['Мярцвяк'/230819, l='MpServer', x=4.50, y=31.00, z=163.58], EntityCreeper['Крыпер'/230818, l='MpServer', x=-1.23, y=31.00, z=158.59], EntityCreeper['Крыпер'/230817, l='MpServer', x=6.19, y=31.00, z=162.42], EntitySkeleton['Шкілет'/230816, l='MpServer', x=21.50, y=41.00, z=153.50], EntityCow['Карова'/230823, l='MpServer', x=15.80, y=67.00, z=172.50], EntityChicken['Курыца'/230822, l='MpServer', x=14.50, y=65.00, z=160.50], EntityChicken['Курыца'/230821, l='MpServer', x=12.50, y=65.00, z=161.50], EntityChicken['Курыца'/230820, l='MpServer', x=8.47, y=66.00, z=156.83], EntitySheep['Авечка'/230827, l='MpServer', x=-6.50, y=65.00, z=227.50], EntitySheep['Авечка'/230826, l='MpServer', x=-0.72, y=65.00, z=229.49], EntityCow['Карова'/230825, l='MpServer', x=27.21, y=68.00, z=176.36], EntityCow['Карова'/230824, l='MpServer', x=20.61, y=67.00, z=171.06], EntitySpider['Павук'/230831, l='MpServer', x=-19.50, y=36.00, z=246.50], EntityWitch['Ведзьма'/230830, l='MpServer', x=-20.50, y=36.00, z=244.50], EntitySheep['Авечка'/230829, l='MpServer', x=-1.42, y=65.00, z=228.40], EntitySheep['Авечка'/230828, l='MpServer', x=-5.50, y=66.00, z=224.50], BuilderEntityRenderForwarder['entity.mts_entity_renderer.name'/230589, l='MpServer', x=31.15, y=73.11, z=178.85], EntityBat['Кажан'/230853, l='MpServer', x=16.63, y=33.62, z=185.81], EntityCreeper['Крыпер'/230615, l='MpServer', x=-38.50, y=54.00, z=203.50], EntityItem['item.item.seeds'/231127, l='MpServer', x=80.25, y=63.00, z=210.73], EntityCreeper['Крыпер'/230614, l='MpServer', x=-34.50, y=54.00, z=205.50], EntitySkeleton['Шкілет'/230619, l='MpServer', x=-39.73, y=51.00, z=213.50], EntitySheep['Авечка'/230618, l='MpServer', x=-43.50, y=64.00, z=205.50], EntitySheep['Авечка'/230617, l='MpServer', x=-41.50, y=65.00, z=205.50], EntitySheep['Авечка'/230616, l='MpServer', x=-41.50, y=65.00, z=205.50], EntityCow['Карова'/230367, l='MpServer', x=35.16, y=68.00, z=171.47], EntityBat['Кажан'/230366, l='MpServer', x=48.21, y=44.07, z=161.27], EntityRabbit['Трус'/231134, l='MpServer', x=89.52, y=63.00, z=238.51], EntityBat['Кажан'/230365, l='MpServer', x=52.45, y=45.07, z=166.68], EntityRabbit['Трус'/231133, l='MpServer', x=88.50, y=64.00, z=233.50], EntityBat['Кажан'/231139, l='MpServer', x=101.75, y=51.77, z=227.08], EntityRabbit['Трус'/231142, l='MpServer', x=103.93, y=64.00, z=242.59], EntityRabbit['Трус'/231141, l='MpServer', x=99.50, y=64.00, z=236.50], EntityRabbit['Трус'/231140, l='MpServer', x=102.50, y=64.00, z=238.50], EntityBat['Кажан'/230638, l='MpServer', x=-45.11, y=58.97, z=104.28]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (amd64) version 10.0
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 190059216 bytes (181 MB) / 1778384896 bytes (1696 MB) up to 2147483648 bytes (2048 MB)
  JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
  FML: MCP 9.42 Powered by Forge 14.23.5.2859 7 mods loaded, 7 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID         | Version      | Source                                       | Signature                                |
       |:------ |:---------- |:------------ |:-------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft  | 1.12.2       | minecraft.jar                                | None                                     |
       | LCHIJA | mcp        | 9.42         | minecraft.jar                                | None                                     |
       | LCHIJA | FML        | 8.0.99.99    | forge-1.12.2-14.23.5.2859.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge      | 14.23.5.2859 | forge-1.12.2-14.23.5.2859.jar                | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | mts        | 22.8.0       | Immersive+Vehicles-1.12.2-22.8.0 (1).jar     | None                                     |
       | LCHIJA | unuparts   | 5.1.4        | UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar | None                                     |
       | LCHIJA | vanillafix | 1.0.10-150   | VanillaFix-1.0.10-150.jar                    | None                                     |
  Loaded coremods (and transformers): VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 517.00' Renderer: 'NVIDIA GeForce RTX 2060/PCIe/SSE2'
  Suspected Mods: Immersive Vehicles (formerly MTS) (mts)
  Launched Version: 1.12.2-forge-14.23.5.2859
  LWJGL: 2.9.4
  OpenGL: NVIDIA GeForce RTX 2060/PCIe/SSE2 GL version 4.6.0 NVIDIA 517.00, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: vanilla
  Current Language: Беларуская (Беларусь)
  Profiler Position: N/A (disabled)
  CPU: 12x Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
  Client Crashes Since Restart: 4
  Integrated Server Crashes Since Restart: 0

**Comment by DonBruce64** [comment]
This bug has already been fixed in a newer release.  Update.
