### ISSUE TITLE
Game Crashed.

### ISSUE THREAD

**Issue by phildeus** [DonBruce64/MinecraftTransportSimulator#166]
https://pastebin.com/eRrfds4u

Thats the log of the crash. It happens when i click on a block of the mod (cant remmeber the name, something like a workbench with a diamond)

**Comment by DonBruce64** [comment]
No description, version, or crash report given for crash, unable to determine cause.  Marking as invalid.

**Comment by DonBruce64** [comment]
Marked issue as invalid, but got crash report after issue was edited.  Re-opening.

**Comment by DonBruce64** [comment]
@phildeus does this occur if you remove the two packs from Dr. Professor Luigi?

**Comment by phildeus** [comment]
Ok Update: Its the "riffling machine" and it only happens on my server now..

**Comment by DonBruce64** [comment]
Again though, does it happen with only the Official Content Pack installed?  Need to isolate if it's a pack issue or a code issue, as it *seems* to be an issue with how the pack has crafting set up.

Though that does beg the question: does it happen in Singleplayer with the same modset?

**Comment by kminhc** [comment]
The Rifling machine and Propeller Bench both crash the game with 
`Error: java.lang.NullPointerException: Rendering screen` when right clicked.
I got the UNU Parts Pack and BlackThorne Civilian Vehicles installed.

**Comment by DonBruce64** [comment]
@kminhc Please open a new issue ticket.  This one is for one specific issue that phildeus has.  Also, please provide a full crash report, not just one line.

**Comment by DonBruce64** [comment]
Closing due to lack of response from user.  Suspect this is related to a bad JSON in a a pack by Dr. Prof. Luigi, however.
