### ISSUE TITLE
A doesNotDrop parameter for parts

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1661]
Useful for invisi-parts or always permanent parts, which usually either come with your vehicle/part/etc. for free or can be crafted at no cost because they're air.

Name is not final, the idea is just that the parameter forcibly pulls this part out of the vehicle crash drops no matter what.

**Comment by DonBruce64** [comment]
Permanent parts shouldn't drop.  If they do, that's a bug?

**Comment by boot2big** [comment]
I believe they do yeah, let me verify.

**Comment by boot2big** [comment]
Is false, they do NOT drop! I could have sworn that was a bug before, but alas for the bug it is nevermore!
