### ISSUE TITLE
Vehicles move without using the throttle

### ISSUE THREAD

**Issue by Somebodygoodluck** [DonBruce64/MinecraftTransportSimulator#1664]
I just change the gear, and the car moves. But I don't use the throttle at all. The vehicle moves itself.

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/123488584/70d86935-bd67-499a-89cf-15daa1cdf047

**Comment by boot2big** [comment]
https://en.wikipedia.org/wiki/Idle_creep

**Comment by Somebodygoodluck** [comment]
Oh, I didn't use to know this. Now I understand. Thanks so much!
By the way, I find there's other problems in the newest version:

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/123488584/8672cf76-f04d-483a-bddc-d6ff3099d891

1.There's a white flash when I get in the car.
2.When I get off, I'm caught in the land.

**Comment by boot2big** [comment]
Had not really noticed the first issue so good on catching that, however the second one has been ticketed with #1647
:+1:

**Comment by DonBruce64** [comment]
This first one is normal.  This happens because the camera has to init and get adjusted to the player's position.  I've tried to make MC not do this, but it's something funky internal that has to do with chunk updates or something that I can't do anything to fix.

**Comment by Somebodygoodluck** [comment]
I see. But I find that these problems don't happen in 22.5.0. Is it caused by something in new versions?
