### ISSUE TITLE
Headlights do not work on UNU 750 De Luxe Sport Coupe [BA-205-LTC] in 1.16.5

### ISSUE THREAD

**Issue by Polybius223** [DonBruce64/MinecraftTransportSimulator#1665]
![2023-06-23_14 43 36](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/137554854/4994cb3e-90cc-4c01-a9e3-7ce20518af72)
![2023-06-23_14 43 55](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/137554854/08238eec-db91-4deb-b58a-100a43c43b8e)

It was broken in the previous version as well.

**Comment by DonBruce64** [comment]
This is a UNU issue, all other pack headlights work in 1.16.5.

**Comment by DonBruce64** [comment]
Confirmed fixed by UNU pack author.
