### ISSUE TITLE
Multiplayer Causes Car bug out While getting out Latest 1.16.5-22.10.0

### ISSUE THREAD

**Issue by Storkclips** [DonBruce64/MinecraftTransportSimulator#1666]
This is really only happening on Multiplayer, Tried Single it works.

https://drive.google.com/file/d/1U07f4rFA10m9nFD1yZNWZSWCLdkZ1l6m/view?usp=sharing

**Comment by DonBruce64** [comment]
What server host are you using?

**Comment by Storkclips** [comment]
Currently Pebblehost.

**Comment by DonBruce64** [comment]
Noted.  I've been seeing this with other hosts, and I suspect it's due to some issues with packets.  I'm looking into it, but it'll take a while to debug.  Out of curiosity though, did this happen in older versions?  Or is it new to this update?

**Comment by Storkclips** [comment]
I'd love to say. "I can easily check" But I am brain stumped.  Do you mean New versions of Pebble host?

**Comment by DonBruce64** [comment]
I meant older versions of this mod.  Like, did you update to 22.10.0 and this issue occured for you, or are you just starting out your server and don't have any idea if the older versions of the mod have this issue?

**Comment by Storkclips** [comment]
Newer for

**Comment by Storkclips** [comment]
I thought you meant something else.

**Comment by Storkclips** [comment]
I did put it in the title. 1.16.5-22.10.0 Maybe I should've posted it in the comments too. for clarity.

**Comment by Storkclips** [comment]
Tomorrow (it's 10 pm for me rn.) let me try older versions

**Comment by ChenBestHero** [comment]
У меня такая же проблема , при выходе из транспорта в одиночной игре всё хорошо . Когда я на хостинге выхожу из транспорта то камера остаётся в машине , а сам я в позе сидя передвигаюсь и смотрю в одну сторону .

**Comment by Cidatis** [comment]
I tested and found out this was a bug since 22.7.0. The only thing you can do right now is to just set your spawn then /kill yourself and set keepInventory to true if you want to keep your stuff.

**Comment by Storkclips** [comment]
Alright, so I played around. I checked out Mohist. and it works fine, but everything else I need is really buggy. Arclight might be a big area, but I'm not sure tho. https://gyazo.com/d7c134df504ea393d09889447314f6f6 This is with the recent version of the mod.

**Comment by Cidatis** [comment]
You might want to read this before continuing to use Mohist.
https://essentialsx.net/do-not-use-mohist.html

**Comment by Storkclips** [comment]
> 

No worries, I HATE Mohist. But good info for newbies.

**Comment by ChenBestHero** [comment]
Tell me, are you working on this problem??? I really like this mod, but I just can't use it on the server because of this bug. In what month should we expect the bug to be fixed???

**Comment by DonBruce64** [comment]
I'm working on it, but other bugs are hitting me every week.  That being said, they are mostly gone, and I should be focusing on this in the next few weeks.  It's not a n easy fix though when it's server-dependent.

**Comment by SuperAnt220** [comment]
I have the same problem, using Magma server 1.16.5, I've tried 22.12.0 and 22.11.0 versions of the mod.

**Comment by Storkclips** [comment]
> a

It's been noted, and I am sure he's working on it.

**Comment by DonBruce64** [comment]
Can y'all join the Discord and ping me?  I've got a beta build that should fix this but I want to confirm.

**Comment by Storkclips** [comment]
> Can y'all join the Discord and ping me?  I've got a beta build that should fix this but I want to confirm.

Sure thing on my part!

**Comment by ChenBestHero** [comment]
> Можете ли вы присоединиться к Discord и пинговать меня? У меня есть бета-версия, которая должна это исправить, но я хочу подтвердить.

Можно ли мне получить эту бету версию мода с исправленной ошибкой ?? мой дискорд айди:  cbh_

**Comment by DonBruce64** [comment]
Likely addressed in 22.14.0 with various commits.
