### ISSUE TITLE
[Suggestion] H-shifter for manual

### ISSUE THREAD

**Issue by ScrapUSS** [DonBruce64/MinecraftTransportSimulator#1667]
I asked a question not too long ago, but I worded it wrong. Actually, can you add H-shifter support for a manual transmission? The way it works is that you put the buttons in gear 1, gear 2, reverse gear, neutral gear, and the like, for example, gear 5.

**Comment by DonBruce64** [comment]
Likely not, but I can consider.  Question: what is the button layout of the H-shifter?  Is it an axis or actual buttons that show up in the controls menu?

**Comment by ScrapUSS** [comment]
These are buttons. I think they are constantly clamped, or not. But I don't think there will be any big difference.

**Comment by ScrapUSS** [comment]
And one more thing - if the gear is not engaged, it will be neutral.

**Comment by DonBruce64** [comment]
There will be.  Can you post the configuration screen of the shifter when you run "joy.cpl" on your Windows machine?  I need to know if it's buttons or an axis.

**Comment by ScrapUSS** [comment]
Oh. These are just buttons, when the gear is on - the button is pressed. When the transmission is in neutral, neutral is engaged

**Comment by DonBruce64** [comment]
that does not address the question I asked.  If you want H-shifter support, I need to see how windows handles said shifter.

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
