### ISSUE TITLE
Incompatibility and crashing with the Censored ASM/Loli ASM mod

### ISSUE THREAD

**Issue by XvaleX10** [DonBruce64/MinecraftTransportSimulator#1668]
Incompatibility and crashing with the Censored ASM/Loli ASM mod when firing a weapon, in this case with the Kadwins Jurassic Park vehicle pack
Minecraft 1.12.2
[crash-2023-06-22_23.24.37-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/11860173/crash-2023-06-22_23.24.37-server.txt)

**Comment by DonBruce64** [comment]
Please join the Discord and ping me there.  I need to send you a specific beta for some log information to fix this.  The bullet shouldn't have nulls there...

**Comment by DonBruce64** [comment]
Fixed as of V22.11.0.
