### ISSUE TITLE
Mod can't initialize control system on Linux

### ISSUE THREAD

**Issue by Ocawesome101** [DonBruce64/MinecraftTransportSimulator#167]
I am playing on Deepin Linux x64, and I cannot start vehicles due to the fact that it can't initialize the control system. I have tried two different mice.

I have a Rii K63C mechanical keyboard and a Redragon Centrophorus M601-3 wired optical mouse. The othe rone I tried is a generic cheap one.

Please fix this, this mod is otherwise amazing!

**Comment by DonBruce64** [comment]
Do you happen to have a log you can send, and perhaps a picture you can send as well of the in-game error?  Would help me to debug the system.

**Comment by Ocawesome101** [comment]
I’m away from my computer right now, but I’ll send you one ASAP.

**Comment by Ocawesome101** [comment]
Never mind, it seems to work now. Here's my game log, just the same, as it
still says it can't initialize the control system (even though it did).

**Comment by DonBruce64** [comment]
Uuuh, I don't see a log here.  More than happy to try to debug this even though it is fixed, however.

**Comment by Ocawesome101** [comment]
Funny. I attached a log file...

**Comment by DonBruce64** [comment]
It looks like you replied via email.  I don't think that works for attaching files to the Git system.  You may need to do it through the web interface.

**Comment by Ocawesome101** [comment]
That would be why :P 
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/3587927/latest.log)

**Comment by DonBruce64** [comment]
Looking at that, I keep seeing lines like this:
`[14:57:04] [Client thread/WARN]: Skipping bad option: key_key.use:key.mouse.right
[14:57:04] [Client thread/INFO]: [net.minecraft.client.settings.GameSettings:func_74300_a:1403]: java.lang.NumberFormatException: For input string: "key.mouse.right"`

To me it looks like something in your config settings was fouled up, causing keys that didn't exist to try to be loaded.  Guess whatever you did fixed it?  Also, those lines are from the core Minecraft game, not IV, so whatever went wrong it was bad enough to affect the non-modded parts of the code.

**Comment by Ocawesome101** [comment]
Huh.
