### ISSUE TITLE
Ticking entity crash every time when i get in vehicle.

### ISSUE THREAD

**Issue by sy5ka** [DonBruce64/MinecraftTransportSimulator#1673]
Problem is not in vehicle itself but in seat (every pack that i have) in older versions of immersive vehicles for example 20.6.2 it works but any newer don't
[crash-2023-06-29_11.25.52-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/11904226/crash-2023-06-29_11.25.52-client.txt)

**Comment by DonBruce64** [comment]
Post your mtsconfigclient.json file.

**Comment by DonBruce64** [comment]
Closing due to no response and likely fix by commit 03a7ee8ad36a705a8aea617b2851c34490cdab7f.
