### ISSUE TITLE
Treads with patterns should probably use the entire array count

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1675]
To expand on the title, they should probably run through the length of however long the tread's pattern is before snapping back to a default position... or at least, I _presume_ that's what is happening in this video.

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/3141807a-af56-47ad-8bfa-4057d26d1a3c

**Comment by boot2big** [comment]
I plead the fifth.

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
