### ISSUE TITLE
White flash when first entering vehicles.

### ISSUE THREAD

**Issue by Somebodygoodluck** [DonBruce64/MinecraftTransportSimulator#1676]
I'm so sorry to mention this again, but I found that the problems I mentioned in #1664 don't happen in 22.5.0.
Also, I found that entity.mts_entity.name, a entity that is near the player in 22.5.0, was removed in 22.10.0. Do my problems have to do with this?
(The old issue is closed, so I opened this issue to discuss these problems)

**Comment by DonBruce64** [comment]
Which issue are you talking about specifically here?  You mentioned multiple issues in that ticket.

**Comment by Somebodygoodluck** [comment]
There's a white flashing when I get in the car, and I'm caught in the land when getting off.
I find they only happen in newer versions.

**Comment by DonBruce64** [comment]
Gotcha.  The getting caught in land.  Is that like #1647 ?

The white flashing though I can see about.  I think it's due to the camera changes, so I might not be able to fix it entirely.  Might just be a thing.

**Comment by DonBruce64** [comment]
Closing due to no user response.
