### ISSUE TITLE
autostartEng override in vehicle JSON

### ISSUE THREAD

**Issue by Gliese-832-c** [DonBruce64/MinecraftTransportSimulator#1680]
You should be able to manually override the autostartEng config in the vehicle JSON. Although that setting is pleasant to have with cars and other small vehicles, I am currently working on a big cargo ship and I believe that regardless of the setting the engine should keep running. You should be able to exit the control seat and walk around while the ship keeps going forward.

**Comment by DonBruce64** [comment]
Implemented in PR #1678 .

**Comment by DonBruce64** [comment]
Addressed in 22.11.0.
