### ISSUE TITLE
There is no sound from the vehicle

### ISSUE THREAD

**Issue by LawrenceWollaston** [DonBruce64/MinecraftTransportSimulator#1683]
![2023-07-09_23 46 36](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/109683629/17e4dca5-feeb-4ddc-b50f-dd805c31f19a)
There is no sound from the vehicle, the lights are fine, the driving is fine, but there is no sound. I tried reinstalling the mod, but it didn't work.

**Comment by DonBruce64** [comment]
Did you do what the text chat said?

**Comment by LawrenceWollaston** [comment]
> 你按照文字聊天所說的做了嗎？

No, because I am not very good at setting these mods, and I will cause more problems if I take the settings, so I have encountered this problem before and reinstalled the mods directly.

**Comment by LawrenceWollaston** [comment]
> Did you do what the text chat said?

No, because I am not very good at setting these mods, I am afraid that the settings will cause more problems, so I have encountered this problem before and reinstalled the mods directly.

**Comment by LawrenceWollaston** [comment]
No

**Comment by LawrenceWollaston** [comment]
> Did you do what the text chat said?

Not yet, I thought it was just an error, I'll try it now

**Comment by LawrenceWollaston** [comment]
> Did you do what the text chat said?

I tried it and the sound is back to normal, problem solved.Thanks
