### ISSUE TITLE
[BUG] Vehicles become invisible after adding and removing some mods

### ISSUE THREAD

**Issue by AstraxVZ** [DonBruce64/MinecraftTransportSimulator#1685]
After I added the mods Xaero's Minimap, Xaero's World Map, Thermal Foundation, Thermal Expansion, Patchouli, CoFH World, CodeChickenLib, CoFH Core and Redstone Flux, the vehicles stopped rendering and appear as invisible entities and don't even work. I removed those mods but the vehicles are still invisible.

Here are my mods (filenames of the mods):
adminshop-1.5.1.jar
ArtemisLib-1.12.2-v1.0.6.jar
BetterQuesting-3.5.329.jar
car-1.12.2-2.0.1.jar
Chisel-MC1.12.2-1.0.2.45.jar
craftingstation-0.1.8a.jar
Craftspeed+1.1.4.jar
CraftTweaker2-1.12-4.1.20.682.jar
CTM-MC1.12.2-1.0.2.31.jar
ctrades-1.3.3.jar
Currency-1.12.0-1.3.11.jar
CustomNPCs_1.12.2-(05Jul20).jar
debugstick-1.2.jar
device-mod-0.4.1-1.12.2.jar
DoggyTalents-1.12.2-1.15.1.6.jar
eating-1.0.0.jar
EconomyInc-1.6.2MC1.12.jar
effortlessbuilding-1.12.2-2.16.jar
Fluidlogged-API-v1.9.0.4-mc1.12.2.jar
FNaFUniverseMod~1.12.2-Release+2.5.jar
Forgelin-1.8.3.jar
FredBear Family Diner Mod Beta 2.jar
Fureniku's+Roads-1.1.10.jar
furniture-6.3.1-1.12.2.jar
Generals_General_Vehicles_1.8.1.jar
GitWeb+Builder-1.1.jar
Golden+Airport+Pack+[IV]+3.2.6.jar
hbm-1.3.7.1a.jar
Immersive+Vehicles-1.12.2-21.3.0.jar
ImmersiveEngineering-0.12-98.jar
ImmersiveRailroading-1.12.2-forge-1.9.1.jar
industrialcraft-2-2.8.170-ex112.jar
IndustrialWires-1.7-36.jar
infinityeditor-0.15.jar
invisiblights-3.2-10.jar
IV_Trin_Industrial_Machinery_Pack_1.0.3.jar
jei_1.12.2-4.16.1.302.jar
Keystrokes-7.0 (1.12.2).jar
luaj-jse-3.0.1.jar
lucky-block-forge-1.12.2-2.0.jar
Magneticraft_1.12-2.8.5-dev.jar
malisiscore-1.12.2-6.5.1.jar
malisisdoors-1.12.2-7.3.0.jar
mcw-bridges-1.0.6b-mc1.12.2.jar
mcw-doors-1.0.0-mc1.12.2.jar
mcw-furniture-1.0.1-mc1.12.2beta.jar
mcw-roofs-1.0.2-mc1.12.2.jar
mcw-trapdoors-1.0.3-mc1.12.2.jar
mcw-windows-1.0.0-mc1.12.2.jar
memory_repo
modelloader-1.1.7.jar
movingelevators-1.3.6-mc1.12.jar
MTR-1.12.2-alpha-test-0.0.1.jar
MTS_Official_Pack_V23.jar
NPCIntegration-3.4.34.jar
OptiFine_1.12.2_HD_U_G5.jar
railcraft-12.0.0.jar
SCP_Lockdown-1.12.2-2.4.0-hotfix.jar
secretroomsmod-1.12.2-5.6.4.jar
simplycats-1.12.2-0.2.2.jar
SRParasites-1.12.2v1.9.8.jar
supermartijn642configlib-1.1.6-forge-mc1.12.jar
supermartijn642corelib-1.0.19-forge-mc1.12.jar
Sweeter_Than_Honey_Alpha_Build_1.0.jar
techguns-1.12.2-2.0.2.0_pre3.2.jar
theoneprobe-1.12-1.4.28.jar
TheRCMod-v4.0.1.1+[1.12.2].jar
TrackAPI-1.2.jar
UniversalModCore-1.12.2-forge-1.1.4-2b81e7.jar
UNU+Civilian+Pack+[MTS]+1.12.2-21.3.0-5.3.2.jar
UNU+Military+Pack+[MTS]+1.12.2-21.3.0-5.0.0.jar
UNU+Parts+Pack+[MTS]+1.12.2-21.3.0-5.1.4.jar
VariedCommodities_1.12.2-(31Mar23).jar
worldedit-forge-mc1.12.2-6.1.10-dist.jar
xplosives-1.1.jar
[1.12.2]+SecurityCraft+v1.8.23.2.jar

The problem was first caused by the Replay Mod, but after I removed it, the problem was fixed and now I am experiencing this problem. Is there a fix for that?

**Comment by DonBruce64** [comment]
This is usually caused by an "optimization" mod removing IV entities it should not.  Try removing all optimization mods and then restarting to see if this fixes it.

**Comment by AstraxVZ** [comment]
> This is usually caused by an "optimization" mod removing IV entities it should not. Try removing all optimization mods and then restarting to see if this fixes it.

I have searched through all those mods and none of them are optimization mods, for some reason this didn't happen before i added the mods and I had the exact same mods?

**Comment by DonBruce64** [comment]
Do you still have this issue?  Sorry for the long reply delay.

**Comment by DonBruce64** [comment]
Closing due to no response.
