### ISSUE TITLE
`isForBullets` hitboxes don't seem to transfer damage to the vehicle?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1686]
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/6b601c18-7d35-4f88-8a47-c9a4cb1366a0)
Ain't no box health defined, so it's not that...

Am I simply misunderstanding what isForBullets is meant to be used for? Is it meant for just blocking bullets, or is it supposed to let you place big chonky boxes for bullet collision without having a buncha physics-running isInterior boxes?

**Comment by boot2big** [comment]
P.S: Was not the damageMultiplier, I checked. Decided I didn't want them anyways and yeeted them, but isForBullet boxes still don't forward damage.

**Comment by DonBruce64** [comment]
`Am I simply misunderstanding what isForBullets is meant to be used for? Is it meant for just blocking bullets, or is it supposed to let you place big chonky boxes for bullet collision without having a buncha physics-running isInterior boxes?`
The latter is correct.  It's supposed to be boxes that only bullet can collide with.  Not anything else.  Will fix.

**Comment by DonBruce64** [comment]
Addressed in e0ff05b8c7ca159896cb9f90767dd487500b25a6

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
