### ISSUE TITLE
Localization Issue and Improved Chinese Translation 

### ISSUE THREAD

**Issue by 3247332139** [DonBruce64/MinecraftTransportSimulator#1687]
MTS mod moved Localization file to config folder and rename it to mtslanguage_XX_XX.json after v19.15.7.Altough it can automatic add text when we add a new pack,but it borke all localization resourcepack before v19.15.7. Now it is very hard to localize by editing config file.
To fix that, We probably need to contrl tmtslanguage file by editing mtsconfig.json and generate a resourcepack that we can localize by assets,lang or sth more easily like I18nUpdateMod.
The other problem is that the hand book text and the advancements text is not in the mtslanguage.json,it mean we need to edit mod file every time when the new update come out.
At last, i improved old Chinese localization so that it work on v22.1.0 but i cant edit handbook text because it have to edit mod file.i will submit here cause i didnt find any branches about localization on PR(plz add it or on discord).
thank you reading all my long long story(-.-

[mts chinese Localization .zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/12061458/mts.chinese.Localization.zip)

**Comment by DonBruce64** [comment]
Understood.  Let me think about how to fix this.  Is there a reason you don't want to change the mtslanguage.json file?

**Comment by 3247332139** [comment]
just it is strange to put these file inside the config folder

**Comment by 3247332139** [comment]
The may be a way to fix it
1 use command like /mtslanguage or what ever to generate a resources pack 
2 generate a resources pack like asset/mts/lang/XX_XX/core.json, mtsofficialpack.json, packXXX.json, packXXX.json...
3  use command to load the resources pack
4 let people share their own localization pack on discord ,github or what ever
5 add the localisation pack that u like into next version let it become the official localisation pack that it can be auto laod in game
It may be a little bit late🤨

**Comment by DonBruce64** [comment]
I don't see why you'd want a command or loading or anything.  The configs are already distributed in mopacks and should be synced from server to client anyways.  The fact you're generating a pack, sharing it, posting it, etc, is just a far more complex thing than what is already present.

However, I can see about allowing packs to include their own language files built-in to apply as the default entries if no file is present for the language.  That way you can still get 5 without needing to mess with configs.

**Comment by 3247332139** [comment]
l ve been thinking a while that i found a new idea. Is it possible to use config to enable or disable the language cfg generation and set rule like the priorities to control all the language file from cfg ,resources ,jar or sth, each file can overwrite the file below? It make that pack can add their own language files without conflict with others and players can chose the file they want.

**Comment by DonBruce64** [comment]
Made a thread in Discord if you want to keep up with it.
https://discord.com/channels/232316230852280320/1146156259939205281

**Comment by DonBruce64** [comment]
Re-opening as this issue isn't resolved, this still should be something I do for language pack stuff.

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.

**Comment by sssssLug** [comment]
Maybe Im stupid but can you give an example with such as the official content pack?I made a localizing resource pack with common syntax,and it seemed not to work.

**Comment by boot2big** [comment]
^ I could see myself using localization as well, I just dunno how exactly yet. Maybe I missed it in the wiki?

**Comment by DonBruce64** [comment]
Added to the Wiki.  This is what you get for letting Snail test things.  You miss out on things!
https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-General-Languages
