### ISSUE TITLE
Faulty "sounds": code-block queueing when using same sound file twice

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1688]
Shitty title but you know the issue....

**To view the "blinker issue" ->** https://discord.com/channels/232316230852280320/289084393442639872/1129859557238259743

**The "wheel_skidding issue":**
There is a block of code that makes the wheel screech when slipping and a
second block that makes the wheel screech when braking while moving quickly.
take note, both use the same file but one comes from coremod and one from OCPs assets.

If i do some drifts, the skidding noise should be heard perfectly fine, which it does. 
<img width="363" alt="Bildschirmfoto 2023-07-15 um 21 47 26" src="https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/f89d9e89-85a1-4052-852e-bd143187f8fe">

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/60043f0c-4d0d-41b2-a9bb-a10da3e232d6

But if i now make both blocks use the same sound-file from OCPs assets instead, this happens:
<img width="363" alt="Bildschirmfoto 2023-07-15 um 21 51 27" src="https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/1688efe2-723b-47a3-834f-eb2eefdf17e7">

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/06346234-f78e-4530-ad4e-51beee0dac4e

**so for whatever reason, if two blocks of code share the same targeted sound file, the one breaks the other or both break completley** 

Your response:
_"I know why that happens.  It's because I check the first block, see the sound should be playing, and then check the second block, see the sound shouldn't be playing, and it is playing, and then I stop it.  I don't check sounds against the JSON that spawned them.  Please ticket."_

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
