### ISSUE TITLE
[Shaders] Vehicles flicker in and out of sight in first-person.

### ISSUE THREAD

**Issue by ytHighQ** [DonBruce64/MinecraftTransportSimulator#169]
Basically when shaders are enabled, vehicle textures not only flicker but can dissapear entirely. Eventually they return when the vehicle shifts position or when I move my line of sight. Can become extremely annoying however...
![2019-08-28_00 42 21](https://user-images.githubusercontent.com/54249388/63826390-c9a09880-c92c-11e9-9fe0-94a9f61a89f4.png)
![2019-08-28_00 42 32](https://user-images.githubusercontent.com/54249388/63826395-ce654c80-c92c-11e9-8001-489f68555139.png)

**Comment by DonBruce64** [comment]
Yeah, shaders break a LOT of things.  Does this happen in third-person or just first-person?  Does it happen with other entities, or just the planes?

**Comment by shiron7** [comment]
Im having the same issue here~

**Comment by ytHighQ** [comment]
> Yeah, shaders break a LOT of things. Does this happen in third-person or just first-person? Does it happen with other entities, or just the planes?

It happens with all entities as well as both third and first person. It may be a lighting issue (I could be wrong) but for every major lighting update that occurs seems to be the interval at which the vehicle flickers. I've decided to not use shaders and have switched to PR Luminance which is a basic lighting resource pack which uses optifine and doesn't affect the vehicles. It seems to only occur with lighting related to dedicated shader packs and not resource packs which have a similar mechanic.

Really nice mod btw! Flan's mod doesn't really like me so I had to do some digging to find an alternative. Came across this and I'm glad I did!

**Comment by DonBruce64** [comment]
Interesting.  This is on 1.12.2, yes?  Do any other entities in other mods flicker, or is it just MTS vehicles?  If I had to pick two to check it'd be Crayfish's vehicles and Flansmod vehicles.  If neither of those flicker, I can release a few test versions here to see if I can isolate the problem.  I probably can't fix it, but I can at least document why it's happening and possibly make a work-around in a config.

**Comment by DonBruce64** [comment]
Been doing some tests with another user on this, and can confirm it's related at least to the fustrum check not being ignored in some cases, despite me setting the bit.  Flickering is due to another issue that's still under investigation.  Tagging this appropriately.

**Comment by DonBruce64** [comment]
Fixed in V15.7.0.
