### ISSUE TITLE
devMode messes with part installing and deinstalling

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1693]
oh yeah, on the topic of destroying:
When i sit in a fully assembled car, press import on devmode and try to remove any part, it drops itself but the functional part itself still stays on the vehicle.
So say i sit in car, import, remove engine with wrench (engine drops), engine is still there, visible, but not functional.
If i pick the car up with shiftrnb an place it down again, the part i previously removed is gone .
same goes for installingn parts. A vehicle that has passed a devmode import cycle can no longer accept parts. only vehicles that are placed after the import can accept parts

VIDEO => https://discord.com/channels/232316230852280320/289084393442639872/1135719557160505354

**Comment by DonBruce64** [comment]
Prolly fixed with e9307c806aab04f0fe7911b6668a3886cbe6830c

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
