### ISSUE TITLE
Not compatible with bettercombat mod

### ISSUE THREAD

**Issue by DJQ28** [DonBruce64/MinecraftTransportSimulator#1694]
The latest version of Immersive Vehicles is Not compatible with bettercombat mod.
The wrench cannot be used to Dismantle the vehicle.

**Comment by DJQ28** [comment]
mc version 1.12.2
mod version 22.11.0
I tested the previous version and it seems that there has been this problem since version 20, I wonder if it is caused by the new version rewriting the code?

**Comment by DJQ28** [comment]
It's not the problem with the mod.
 It seems that  bettercombat mod modifying the keys causes the key conflicts.
I'm still looking for a way to resolve the key conflict, as I don't see the settings for both mods.
Maybe you have a way to fix it in the next release?

**Comment by DonBruce64** [comment]
There's no keys for the wrench.  It just looks as the right-click of the player.  But... it should always see that?  Please create a thread on the Discord and ping me so I can send you some betas to test this.  I don't have the ability to test it myself.

**Comment by DJQ28** [comment]
ok,I will ping you on discord.
keep in touch

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
