### ISSUE TITLE
[Suggestion] Despawn config

### ISSUE THREAD

**Issue by andryqx** [DonBruce64/MinecraftTransportSimulator#1695]
Hi! 
**I would like to suggest that you add the "/mts despawn * time * " command to the mod. This command would work like this: all vehicles in the world that have 0% health would simply disappear from the world in * time * seconds. This would help avoid lags on the servers and even on the client side. Each user can manually set the despawn time, or not enable this function at all (by default, or "/mts despawn 0")**
(sry for my english)

**Comment by DonBruce64** [comment]
I can add this, but it'll be as a config, not a command.  Configs are where such timers and settings should be saved.  Normally, vehicles should not despawn since you'll lose them, but it's quite possible for me to add this for creative and battle servers.  Expect to see this in the next update.

**Comment by andryqx** [comment]
Only vehicles with 0% hp will be despawned, yes?

**Comment by DonBruce64** [comment]
That is correct.

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
