### ISSUE TITLE
How to disable drifting

### ISSUE THREAD

**Issue by Torizem** [DonBruce64/MinecraftTransportSimulator#1696]
Good morning everyone, can you tell me how to disable drifting in this mod? Or somehow you can get rid of it? Looked through the configs, there is nothing about disabling drifting

**Comment by ScrapUSS** [comment]
(This doesn't disable drift, but it can significantly reduce it) As an idea, you can put other wheels that have a higher density to the surface (It says it is better to choose the highest value for a comfortable ride). You can also open the pack as a zip archive and search for the car config, and select either front-wheel drive or all-wheel drive on true

**Comment by DonBruce64** [comment]
Yeah, disabling drifting sounds all well and good, but if you DO disable it, the cars actually handle worse at high speeds since you turn instantly.  Not gonna duh.
