### ISSUE TITLE
Radio volume text is offset when set to 10

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1697]
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/b699f4e2-3ea0-4af3-8514-1bd36ed65b80)

**Comment by boot2big** [comment]
Additional note: text is aligned properly when volume is 0 to 9

**Comment by DonBruce64** [comment]
![2023-08-15_22 46 54](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/15241611/7d9e1f3b-5297-4e03-a0ac-c6b1bd697c4f)
*Why doesn't mine look like that!*

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
