### ISSUE TITLE
Suggestion: Raise fishing item drop height

### ISSUE THREAD

**Issue by Gliese-832-c** [DonBruce64/MinecraftTransportSimulator#1704]
I don't know if this can be classified as a bug, but I tried fishing from the sailboat I made (https://www.curseforge.com/minecraft/mc-mods/nova-lux-vehiculum) and when you pull the rod out, what happens is that the item you fish out of the water gets spawned too low, misses the boat, and plummets deep into the ocean.

I don't know if it's within the scope of this mod, but would it be possible to add an option somewhere (vehicle, seat part, seat part slots in vehicles, global config) to raise the height at which the item gets spawned in?

**Comment by DonBruce64** [comment]
Not really, no.  All of that code is handled by Mojang and their core code.  I can only mess with that code in very limited ways.  As said messing doesn't allow me to adjust the item drop height, only what drops.
