### ISSUE TITLE
[ENHANCEMENT] Make vehicle entities get an unique entity name.

### ISSUE THREAD

**Issue by TonySokachu** [DonBruce64/MinecraftTransportSimulator#1707]
Right now every MTS vehicles have an entity Identifier name that goes like this:
 entity.mts_entity.name(on 1.12.2) and 
mts.builder.existing(on 1.16.5). 
You can kill the vehicles by running: {"/kill @e[type=mts.builder.existing]"} but you can't summon them, because running "/summon mts.builder.existing" brings up an invisible fake entity.
What i want and i'm sure more people are looking toward this feature is to be able to identify each vehicle by the name of their item: mts:packid.name
ex. 
Item name: mts:warkvehicle.containerhandler
entity name: mts:warkvehicle.containerhandler

I believe this would help servers in a big way. They could setup minigames, Races, Roleplays and so much more.

**Comment by TonySokachu** [comment]
> Can it be assumed what you actually want is a command to summon vehicles, not them having a unique name specificall?

Sorry for not responding.
Yes but i requested entity names as you have multiple minecraft command, ex. kill, tp, execute if entity execute at, etc

**Comment by DonBruce64** [comment]
They will not have unique names.  IV registers vehicles as a single entity.  Their JSON defines what they do.  So no, you just get the basic names.

**Comment by TonySokachu** [comment]
So is the /summon command possible at least?

**Comment by DonBruce64** [comment]
If you use the right NBT, yes, you can summon a vehicle now.  You don't need anything special for that.

**Comment by TonySokachu** [comment]
So whats the right NBG? How do we know what to put in in?

**Comment by DonBruce64** [comment]
I honestly have no clue.  I don't mess with summon commands with NBT normally.  Would ask one of the folks who is on servers regularly that do.
