### ISSUE TITLE
Part Scanner does not work in the 1.16.5

### ISSUE THREAD

**Issue by Sarocesch** [DonBruce64/MinecraftTransportSimulator#1710]
Good evening
I played today in survival with the mod in the 1.16.5 and unfortunately had to find that the part scanner shows nothing so the areas where yes but when I look at it is not timed what matches

**Comment by DonBruce64** [comment]
Video, mod version, post please.

**Comment by Sarocesch** [comment]
can only make it in a par days

**Comment by Sarocesch** [comment]
it is somehow fixed out of nowhere 
I will do more tests again because it could be the mod Essentials on their multiplayer system
but as I said I must test again

**Comment by DonBruce64** [comment]
Closing due to lack of user response.
