### ISSUE TITLE
Unable to drive UNU Mastodon Sedan

### ISSUE THREAD

**Issue by LawrenceWollaston** [DonBruce64/MinecraftTransportSimulator#1712]
The UNU Mastodon Sedan cannot be driven. When pressing the control button, there is an animation of stepping on the accelerator, but the car does not move. I tried filling up the tank and starting the car and the engine started normally but the car still wouldn't move and there were no messages or errors.

**Comment by DonBruce64** [comment]
Is your battery dead?  That can happen.

**Comment by LawrenceWollaston** [comment]
> 你的電池沒電了嗎？這可能會發生。

I don't think so, because the car's engine starts normally, but it just won't drive away.

**Comment by DonBruce64** [comment]
Can you send a video?  And can you show if simpleThrottle and autoStartEngine is turned on in the config screen that you get to by pressing P?

**Comment by LawrenceWollaston** [comment]
![2023-10-24_17 57 26](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/109683629/7123a7cb-e20b-42ed-8085-916a2e2cdc00)

**Comment by DonBruce64** [comment]
Hrm.  It looks like you probably have a dead battery then, since the engine doesn't want to start.  Use a battery pack to charge it up and then see what happens.

**Comment by LawrenceWollaston** [comment]
![2023-10-25_19 14 54](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/109683629/8299b589-bc7f-44e8-907b-e09ca3751481)
Is it this one?

**Comment by LawrenceWollaston** [comment]
Um, let me ask, what does the battery pack look like? I looked in my inventory and searched, but couldn't find the battery pack.

**Comment by DonBruce64** [comment]
It's the yellow thing.  Actually called Jumper Pack, my bad.

**Comment by LawrenceWollaston** [comment]
> It's the yellow thing. Actually called Jumper Pack, my bad.

Jumper Pack? I tried it, but it didn't work, the car still won't move.

**Comment by DonBruce64** [comment]
Please post a video if you could.

**Comment by LawrenceWollaston** [comment]
> 如果可以的話請發布影片。
I don't know how to send it? Github cannot reply to the video. How should I send it to you, email?

**Comment by LawrenceWollaston** [comment]
> Please post a video if you could.

I uploaded the video to Google Drive. The URL is https://drive.google.com/file/d/1mtAcTYSZOhunuGFVDZqobWsrSRIqmuMD/view?usp=drive_link

**Comment by DonBruce64** [comment]
That file is not accessible to the public and therefore I cannot access it.

**Comment by LawrenceWollaston** [comment]
> That file is not accessible to the public and therefore I cannot access it.

OK, uh, I just reset the relevant permissions of the file, now see if you can watch this video? The URL is https://drive.google.com/file/d/1mtAcTYSZOhunuGFVDZqobWsrSRIqmuMD/view?usp=sharing

**Comment by DonBruce64** [comment]
Very strange.  This shouldn't be happening as the vehicle is clearly starting, and the parking brake is off, and it should be going in-gear.  Can you install a gear indicator instrument with the wrench and see if the vehicle is going into gear?

**Comment by LawrenceWollaston** [comment]
> 很奇怪。這種情況不應該發生，因為車輛明顯正在啟動，並且駐車煞車已關閉，並且應該掛檔。可以用扳手安裝檔位指示器來檢查車輛是否掛檔嗎？
I just tried it and the car can be put into gear normally.

**Comment by LawrenceWollaston** [comment]
> 很奇怪。這種情況不應該發生，因為車輛明顯正在啟動，並且駐車煞車已關閉，並且掛檔。可以用扳手安裝檔位來檢查車輛是否掛檔嗎？

The vehicle is in gear

**Comment by DonBruce64** [comment]
I'm going to pull in @DrprofLuigi here as maybe he has seen this or knows what's up with the car.  Maybe it's a version issue?

**Comment by DonBruce64** [comment]
Please join the main IV Discord and ask there for help.  This isn't going to be a quick fix I see.

**Comment by LawrenceWollaston** [comment]
> Please join the main IV Discord and ask there for help. This isn't going to be a quick fix I see.

ok
