### ISSUE TITLE
Game freezes with mr.crayfish's gun mod

### ISSUE THREAD

**Issue by meowkitty9694e** [DonBruce64/MinecraftTransportSimulator#1713]
The game freezes when trying to load with mrcrayfish's gun mod and immersive vehicles loaded at the same time, oddly though, the log does give any errors.

Version: 1.16.5-22.11.0
log:
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/12552770/latest.log)

**Comment by DonBruce64** [comment]
please join the Discord and this thread
https://discord.com/channels/232316230852280320/1150264649632198697

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
