### ISSUE TITLE
[1.16.5 - 22.11.0]Out of Memory (actually not) when placing various (unofficial) mts vehicles sometime

### ISSUE THREAD

**Issue by sssssLug** [DonBruce64/MinecraftTransportSimulator#1714]
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/12567604/latest.log)
Don't know if it was really by mts. Please view the last lines of this log file.
Because the game didn't crash, there's no crash report.
[system details.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/12567609/system.details.txt)
And maybe useless though: 
[randallchiselplow3.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/12567613/randallchiselplow3.txt)
----That's one of the vehicle in this pack that triggered the issue. It's from Randall's IV Farming mod.

BTW the trailers, such as the one I've uploaded, just don't move with the towing (even if connected), so I wonder if I made some mistake in the file......If it is please tell me.

**Comment by ajh123** [comment]
If your (In F3 screen) "Mem: xx%" is roughly 90 then you might need to allocate more memory to Minecraft, hence the "Out of Memory". To allocate more memory you need to do it in the launcher.

**Comment by DonBruce64** [comment]
I don't think he's truly out of memory.  At least not in the traditional sense.  He has a LOT.
@sssssLug  can you do this:
Tell me how much memory total you have on your machine, VS what you have allocated to MC.
With no vehicles placed, show a screenshot of your memory allocation in F3 debug.
With 1 vehicle that's not Randall, show me your F3 allocation.  Wait a bit and tell me if the allocation keeps going up.

I suspect you either have to much memory allocated that you're lacking stack memory in leiu of tons of heap, or I have a memory leak, and the farming vehicles just happen to be the ones around when you crash.

**Comment by sssssLug** [comment]
Sorry I can't reproduce that crash, but I think you are right and my memory allocating was to blame ---- I just noticed I allocated 10 Gb of only 13 total available.
As I tried many times there's no memory uprush or keeping going up with the vechiles placed(but short game freezing sometimes), so I think it's not a bug of the mod, just my mistake.
![2023-10-05_14 08 15](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/114668379/f9ec4f4a-0eed-48d0-b95f-27d935dd4628)
![2023-10-05_14 08 58](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/114668379/22aebe0b-72bc-4df5-95ff-48e754c97df6)

> I don't think he's truly out of memory. At least not in the traditional sense. He has a LOT. @sssssLug can you do this: Tell me how much memory total you have on your machine, VS what you have allocated to MC. With no vehicles placed, show a screenshot of your memory allocation in F3 debug. With 1 vehicle that's not Randall, show me your F3 allocation. Wait a bit and tell me if the allocation keeps going up.
> 
> I suspect you either have to much memory allocated that you're lacking stack memory in leiu of tons of heap, or I have a memory leak, and the farming vehicles just happen to be the ones around when you crash.
