### ISSUE TITLE
when i leave the car i cant move and it acts like im still in the car ( im shaking etc.)

### ISSUE THREAD

**Issue by dupa123lol** [DonBruce64/MinecraftTransportSimulator#1717]
version 1.16.5 if ya need more info tell me

**Comment by dupa123lol** [comment]
oh on of those glitches that heppen and in few hours theyre gone

**Comment by dupa123lol** [comment]
nvm its back and idk why

**Comment by DonBruce64** [comment]
What IV version you using?

**Comment by DonBruce64** [comment]
Closing due to no response.
