### ISSUE TITLE
[Suggestion] Configure Bullet Damage Per Pack

### ISSUE THREAD

**Issue by Doublehelix13** [DonBruce64/MinecraftTransportSimulator#1720]
Similar to how vehicle scales and speed factors can be configured per-pack, would it be possible to add a config option to adjust bullet damage per-pack?  That way, if one pack's guns are way more powerful than another, players could balance them out, just like how the per-pack speed factors can balance things out if one pack is vehicles that are way faster than another.

Thank you for creating this awesome mod and considering my suggestion!

**Comment by DonBruce64** [comment]
Honestly, that's not a bad idea at all.  Though ideally folks would make more balanced guns.  Is there a specific pack that is OP, or is this just a general feel thing?

**Comment by Doublehelix13** [comment]
My modpack has weapons from UNU Military, Nova Prospekt Armory, and IAV.  UNU is pretty underpowered compared to the other two, with its big vehicle-mounted guns only dealing 2-5 damage.  Meanwhile, little handguns from Nova Prospekt deal 6 damage minimum.  Most guns from the other packs deal 8-25 damage.  I don't think the other packs are OP, at least not with the buffed mobs in my modpack, but  I think UNU's guns need a big buff.  I can't do that right now without making the other pack's guns OP since all guns get multiplied the same amount by the bullet damage factor.

**Comment by DonBruce64** [comment]
Gotcha.  Will implement this when able.  This makes sense.

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
