### ISSUE TITLE
Instrument slots on parts ignore renderHUD_#P

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1724]
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/ded2ec2b-387d-4386-a74d-305e346991fe)
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/4890c83a-7f0e-4822-a891-f9252f771d73)
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/3d2ca8ce-db76-4482-8412-8d323e70d876)
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/04a6c503-da76-4b2e-b5ad-bb915f5c90f1)

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
