### ISSUE TITLE
 funky shit happens to rendering when enabling a shader

### ISSUE THREAD

**Issue by Hubi31** [DonBruce64/MinecraftTransportSimulator#1725]
i know and i tried to do the information from the chat. But i don't know is MTS compatible with Optifine and Complementary Shaders?

![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/147256699/ddae3194-cd73-4857-903e-dfc64a901c17)

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
