### ISSUE TITLE
Guns linked via forceAllLinks to sub-part seats (nary the gun be on the seat's parent part or somewhere else on the vehicle) cannot autofire, and must be switched between in order to fire another round regardless of whether they're semi-auto or full automatic.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1729]
...expiallidicous!

Can be tested with that there Devom Custom kit you have, *or* you can follow these lengthy instructions for a similar part setup.

![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/a750f35f-40dc-4fe0-805b-e03bf0185ee0)
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/eb2fba05-f303-4f65-be27-7f5c6d15ee9c)

Install these parts onto any vehicle with IVV tires (gun mounted to the gun circle part can be of your choice _as long as it's also_ an IVV gun, since that's related to another bug that I can't remember if I reported yet or not)

Sit inside the vehicle, hit F3+B and look at the LIDAR part to sit in the cheekily hidden invisiseat.

Shoot the gun - make sure it's been loaded - and watch as it does not fire correctly, versus sitting in a regularly-defined vehicle seat.

**Comment by boot2big** [comment]
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/656daad4-5d57-4614-a01b-1c163c921c91)
![image](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/53581325/4f8fdb9d-e72c-42ec-9215-061d9966a8e9)

Alternatively, slap these onto your customized Trin Devom and then click on the hidden seat on the center console shifter. Same thing really!

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
