### ISSUE TITLE
Throttle modifier key

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#173]
I didn't find any suggestions before this that got closed, but maybe you might've been suggested this on CurseForge/Discord

Basically, holding W could be 50% throttle (not slamming foot down) whereas holding the mod key used to stop the engine/engage parking breaks could be full throttle, or perhaps the other way around?

No extra keybinds are added, plus iirc there aren't any combos for RShift + W

**Comment by DonBruce64** [comment]
This has never been suggested, and I admittedly have never even thought of it, but it makes sense.  If you have a vehicle with an automatic transmission you can't regulate your speed without tapping the key.  I think most players will want to give the vehicle full-throttle most of the time, so will make the MOD+GAS a 50% throttle.  Expect this in the next release!

**Comment by DonBruce64** [comment]
Added in V15.0.0.
