### ISSUE TITLE
Mod Quality Drop

### ISSUE THREAD

**Issue by Big1N** [DonBruce64/MinecraftTransportSimulator#1734]
hi, and I appreciate making such an awesome mod and making my childhood flying mod. but ever since I've started playing with it again the quality has dropped significantly. When I use the jet airplane I notice that the blades are not spinning when powered on and also to some other attention to detail with engine movement and propeller movement. Another example is when I steer airplanes and cars it seems like I'm gliding on ice and the steering physics is just almost broken which is cringe. idk if this is due to shortcuts or cutbacks in quality or just a bug but whatever the case is I just wish for this unique 1 of a kind mod to go back to awesome realistic physics like it used to be. 

Thanks and love big1n

**Comment by Big1N** [comment]
I understand thanks for explaining the steering better and it’s just jet in the official vehicle pack that the blades don’t spin when the engine is on official

**Comment by LauraDarkez** [comment]
the blades do spin, but the framerate ive noticed have had a major impact on it. and in terms of exhaust smoke, rest assured the man who is now in charge of OCP will have particle effects overhauled massively in the next update. particles are kinda his thing and he only just got to the e500 content overhauls

**Comment by Big1N** [comment]
Thank you so much and thanks again for your support and this awsome mod
