### ISSUE TITLE
A question about 1.20.1version support

### ISSUE THREAD

**Issue by JiaqiYi** [DonBruce64/MinecraftTransportSimulator#1737]
是否打算支持1.20.1版本？希望支持一下。
Are you going to do 1.20.1 rewrite for this mod? I want you to support this version’s minecraft.
(If you think my issue is impolite,please forgive.I am a Chinese middle school student.)

**Comment by SnailPerson** [comment]
👹

**Comment by DonBruce64** [comment]
This is not a bug.  Version updates will come when the core code bugs have been flushed out.  As to when this is, I cannot say.
