### ISSUE TITLE
Disable engine wear-off for all creative mode engines

### ISSUE THREAD

**Issue by TheAdventurerMC** [DonBruce64/MinecraftTransportSimulator#174]
DaanDGM here, reminding you of this important task. Reason: Creative engines are already not limited by fuel, so why not take the limitation of (the very short) engine durability away and give us more freedom! Happy flying!

**Comment by DonBruce64** [comment]
Was thinking you wanted this as a config option, but putting it for creative engines sounds far better as those will be used on servers where the internal plane system aren't desired and planes are more for quick transport than anything else.  I think I'll also prevent them from blowing up, as that's also a common complaint from casual users.  Should be a quick change!

**Comment by DonBruce64** [comment]
Implemented in V15.0.0.
