### ISSUE TITLE
Subparts of ground-placed parts can be screwdrivered, even if they're not marked as "mustBeRemovedWithScrewdriver"

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1747]
I forget if this tin has a label. Have a spare one!

Subparts of ground-placed parts can be screwdrivered, even if they're not marked as "mustBeRemovedWithScrewdriver"

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
