### ISSUE TITLE
Vehicles spawn "isTotaled-particles" when being unloaded

### ISSUE THREAD

**Issue by SnailPerson** [DonBruce64/MinecraftTransportSimulator#1748]
ive noticed that vehicles go through their "isTotaled" particle spawn condidtions as soon as they leave the render distance, eventhough they already preformed that action.

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/97041048/3b63d492-2ef6-4011-9af7-31f2f079880a

the bells in the video are totalled. as i fly past them, you can see them "pop" again in the distance, beginning to burn and smoke.
this also only happens when "leaving" vehicles behind, not when coming back.
So its a "getting OUT of renderDistance" occurrence. EOBETA shenanigans?

Your Answer:
"_No, this is probably due to core code stuff, since the vehicles would load up as un-totaled initially.  If it is a core thing with release, please put in a ticket so I don't forget once I get out of EOBETA hell._ "

**Comment by DonBruce64** [comment]
Was told this was a beta issue and not a release issue that needs fixing.
