### ISSUE TITLE
[BUG] Mts will allow ESC to be used as a keybind

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1749]
I dont even know how i messed up so badly lmao
Mega blunders only with blaze
anyways the problem is that when you bind ESC to the radio whether by intention or accident, MTS will bring up the radio screen and you can't close it or bring up the minecraft ESC screen, basically soft locking the game
<img width="263" alt="image" src="https://github.com/DonBruce64/MinecraftTransportSimulator/assets/63666200/d97cc855-6a53-4051-87f1-0012cc49849d">
<img width="574" alt="image" src="https://github.com/DonBruce64/MinecraftTransportSimulator/assets/63666200/4d4305fb-7042-4796-8d07-8c34086bd738">

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
