### ISSUE TITLE
[Future] [Request] Zero length launch system

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#175]
A launch platform that holds a plane with a rocket booster on the bottom of the plane. The angle and direction of the launch can be changed by rotating the platform. It can be a placeable structure or a movable vehicle.
![image](https://user-images.githubusercontent.com/33960693/65463714-42a8e800-de26-11e9-8667-81eb4d7793b2.png)

**Comment by TheCactus27** [comment]
could also be turned into the launch systems on aircraft carriers

**Comment by DonBruce64** [comment]
This is for sure a no-go.  The physics system for planes is already wonky enough.  The last thing I need are attachments that provide forces the system isn't expecting.  Besides, aircraft carriers will never be a thing.  Far too laggy and complex to build, plus there's no way to get planes to land/stay on them.
