### ISSUE TITLE
[Bug] Stuck after dismount on forge server

### ISSUE THREAD

**Issue by AlphaCTX** [DonBruce64/MinecraftTransportSimulator#1750]
When playing on a forge server (1.16.5) i noticed that when i try to dismont from a vehicle i get stuck and can't move.
This does not happen while in singleplayer.

**To Reproduce**
1.  go into a forge server
2. enter any vehicle
3. try to dismount

**Comment by DonBruce64** [comment]
I've been told this is a server hosting issue, do you have a specific host you are using?  I also have a beta on Discord that should fix this issue.

**Comment by DonBruce64** [comment]
Addressed in 22.14.0.
