### ISSUE TITLE
Missing project license

### ISSUE THREAD

**Issue by zcmp7** [DonBruce64/MinecraftTransportSimulator#1751]
The license for code in this repository appears to be missing. 
A LICENSE file or a note in the README should be added to make clear how code can be modified, redistributed, etc.
Ideally the project should be licensed as free software under the [GNU GPL](https://www.gnu.org/licenses/gpl-3.0.en.html) or similar. Otherwise, please clarify for contributors and users.

**Comment by DonBruce64** [comment]
TBH, I figured people would just contribute if they want to, or not if they don't.  Licencing is only for super-big projects where folks care about money and selling and whatnot.  Folks will copy code if they wanna copy, licence or not, and I don't have the money or the care to go after those folks with litigation that won't do a dang thing to stop them from copying stuff.

But, if you think a licence of something is needed, I'll add one.

**Comment by otakup0pe** [comment]
Given the level of laissez faire you are expressing, I'd recommend a MIT license. Having a clearly defined license can make folk feel more comfortable in contributing - especially when they have signed intellectual property agreements with over-zealous employers.

**Comment by zcmp7** [comment]
I definitely think contributors can be discouraged by a lack of clear license. 
This site is a useful resource for comparing different licenses you may use: [https://choosealicense.com/no-permission](https://choosealicense.com). 
It also has a page on the problems of a missing license: [https://choosealicense.com/no-permission](https://choosealicense.com/no-permission).

**Comment by DonBruce64** [comment]
I've gone and added a licence to the project.  If there's anything un-clear, please let me know.

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
