### ISSUE TITLE
[Suggestion] Option for max flight altitude

### ISSUE THREAD

**Issue by FranklinMCA** [DonBruce64/MinecraftTransportSimulator#1756]
I don't know if this setting exists, but if not I think it would be a useful thing. This setting allows you to set the flight altitude by specifying the y level, above which the aircraft can no longer fly. Useful when the aircraft is flying high enough to still be able to see the terrain when render distance is set to 8 or 16.

Example for the setting:

“maxFlightAltitude”: {
     “value”: 170,
     “comment”: “Limits the flight altitude of aircrafts to the specified y level.”
}

With this setting, the aircraft will not be able to fly above y level 170.

**Comment by boot2big** [comment]
Out of curiosity how would an aircraft be "unable" to fly above this level? As in, what method would be used to prevent the aircraft from flying about this altitude?

Also in my opinion it should be disabled by default, as it would likely confuse most users as to why their fighter jet is unable to break the block-height limit barrier while being able to break the sound barrier.

**Comment by FranklinMCA** [comment]
> Out of curiosity how would an aircraft be "unable" to fly above this level? As in, what method would be used to prevent the aircraft from flying about this altitude?
> 
> Also in my opinion it should be disabled by default (but enabled when it is set) as it would likely confuse most users as to why their fighter jet is unable to break the block-height limit barrier while being able to break the sound barrier.

I mean that the aircraft would not climb continuously upwards, but once they reach a certain altitude, they would adjust to a horizontal position.

**Comment by LauraDarkez** [comment]
I would think that much like irl, if a plane goes past this altitude the wings stop generating lift and risk a stall

**Comment by FranklinMCA** [comment]
Then it might be a bit more complicated than I thought.

**Comment by boot2big** [comment]
@FranklinMCA Such was my point, though it isn't _super_ complex either, as I said I was just curious.
@LauraDarkez VariableModifiers? :sparkles:

**Comment by DonBruce64** [comment]
The thing here is: WHY .  Why would you want such a thing?  I don't see there being any real reason why it's nessicarally bad the aircraft is forced to cap out at say 300 blocks vs 400.  Why not let players fly higher if they want to?

**Comment by FranklinMCA** [comment]
> The thing here is: WHY . Why would you want such a thing? I don't see there being any real reason why it's nessicarally bad the aircraft is forced to cap out at say 300 blocks vs 400. Why not let players fly higher if they want to?

This could be an option that can be turned off, is not mandatory and would be disabled by default.

**Comment by DonBruce64** [comment]
Yes, I know it's an option.  But what's the use-case for this?  I'm not in the business of adding options for the reason of "why not?". I've got multiple people asking me all the time for options and features.  What benefit does this feature bring that makes it worthwhile to prioritize over the other features?

**Comment by andryqx** [comment]
> Yes, I know it's an option. But what's the use-case for this? I'm not in the business of adding options for the reason of "why not?". I've got multiple people asking me all the time for options and features. What benefit does this feature bring that makes it worthwhile to prioritize over the other features?

There is one. If you're higher - your rockets and other ammo will fly longer distance, and maybe people don't want that, it may provoque TPS drops, or just fly through world border.

**Comment by FranklinMCA** [comment]
> Yes, I know it's an option. But what's the use-case for this? I'm not in the business of adding options for the reason of "why not?". I've got multiple people asking me all the time for options and features. What benefit does this feature bring that makes it worthwhile to prioritize over the other features?

One of the reasons for this setting is the render distance, because even though I have it set to 16, if I fly very high the terrain disappears from under me after a while.

**Comment by FranklinMCA** [comment]
> > Yes, I know it's an option. But what's the use-case for this? I'm not in the business of adding options for the reason of "why not?". I've got multiple people asking me all the time for options and features. What benefit does this feature bring that makes it worthwhile to prioritize over the other features?
> 
> There is one. If you're higher - your rockets and other ammo will fly longer distance, and maybe people don't want that, it may provoque TPS drops, or just fly through world border.

Yes the world border, there is a pre-generated map in my case which i dont want to expand with newly generated chunks by players.

**Comment by FranklinMCA** [comment]
Oh and @LauraDarkez mentioned before the wings stop generating lift when the aircraft reach this altitude like irl.

**Comment by DonBruce64** [comment]
Well, join Discord to test it, and I'll whip up a config that will stop vehicles from flying above X height.  But it's gonna be for all vehicles, and will default to no limit, so if you want it for your server you can set it, but it won't be set on normally.

**Comment by FranklinMCA** [comment]
> Well, join Discord to test it, and I'll whip up a config that will stop vehicles from flying above X height. But it's gonna be for all vehicles, and will default to no limit, so if you want it for your server you can set it, but it won't be set on normally.

Im already on it

**Comment by LauraDarkez** [comment]
> Oh and @LauraDarkez mentioned before the wings stop generating lift when the aircraft reach this altitude like irl.

the problem with this is that if you dont make it per-vehicle json then it is universal, and therefore cuts off the realism of making planes with higher flying advantages compared to others

**Comment by boot2big** [comment]
If I could veer back into the convo for a moment, perhaps a vehicle-size parameter that multiplies the limit (and is either LC'd to one, or has 1 added to it so that we account for planes that don't have this defined) such that you could have a plane go slightly/way above or below the altitude limit, without having to hard-define it either?

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
