### ISSUE TITLE
[Suggestion] Option to set up block hardness to vehicles in config.

### ISSUE THREAD

**Issue by Raptor324** [DonBruce64/MinecraftTransportSimulator#1757]
I think, everyone faced with such problem, when car, instead of breaking blocks in front of it, just climbing them. It's most noticeable when you drive a vehicle into the woods. The car just lifts up on the tree crowns, and you starting to driving around them. Which is quite unrealistic, especially if it's a heavy tank or truck. I suggest to add an ability to set up block hardness in config file, by the same system as with fluids already done. All blocks in game just loads into the list inside of the config file, and you can change the hardness values. Like, "0" - is always-breakable, even if vehicle just stands on this block. "1" - default value, and so on.

**Comment by andryqx** [comment]
Yes! I agree, that would be really nice, often vehicles can grief structures even on servers, and you can't fix that.

**Comment by DonBruce64** [comment]
You can fix the greifing by turning off block breakage.  That's what that particular config option is for.

**Comment by andryqx** [comment]
> You can fix the greifing by turning off block breakage. That's what that particular config option is for.

When you off that thing you can't use guns (rockets and etc.), can you make two different config options for guns and block breakage

**Comment by DonBruce64** [comment]
that I can.  But I'll need someone to test that on the Discord, if you want to join and ping me.

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
