### ISSUE TITLE
[Suggestion]  Vehicle related suggestions

### ISSUE THREAD

**Issue by Munancho-Hepetonas** [DonBruce64/MinecraftTransportSimulator#1758]
1
The parking brake is activated by switching by pressing Rshift + brake key.
In addition to this, could you please add a parking brake to the keybinds and controlbinds that only works while the key is pressed?

2
Also, like above, could you consider adding a manual clutch that operates while the key is pressed and a clutch variable for this?
 I don't want a function that is TOO realistic, I just want it to be in the same state as a neutral gear, where the engine rpm changes while the key is pressed but does not move forward.

(I think pack creators who want to make realistic clutches can freely create them in VM.In fact, I think the appeal of this mod is that it is too realistic compared to other mods.)

I think this will expand the possibilities for fun for both players and creators of vehicle packs.
It's long, but I'd be happy if you could think about it.

**Comment by boot2big** [comment]
1 sounds like a cool suggestion when steering wheel setups are considered, particularly handbrake controls. (Similar to H-shifters)
However 2 I believe has been discussed before, with little positive reception to its inclusion in the main mod. _That beeing saaaid_ I may know a pack that does implement clutch-like behavior, although it is not manually controllable and is instead initiated whenever the player shifts a manual engine. The positive to this though is that you can quickly shift through several gears without actually engaging them! ~~If you can't tell I'm shilling my own pack.~~ Try some of the regular joe-schmoe engines in IVV! (Insolvo, Median, Velocitus, Torqueline)

**Comment by DonBruce64** [comment]
> could you please add a parking brake to the keybinds and controlbinds that only works while the key is pressed?
I don't understand what you mean by this.  Do you mean a parking brake that's on when the key is pressed, and off when the key is released?  Cause if you're asking for that, well, that's a regular brake, which we kinda already have.,

> Also, like above, could you consider adding a manual clutch that operates while the key is pressed and a clutch variable for this?
What I'm understanding here is you basically want pressing the key to put the car in neutral.  But what happens when you release the key?  Car goes back into the same gear?  I get the feeling this is something you want in tandem with some other control system.  Some sort of dedicated shiftier perhaps?

**Comment by Munancho-Hepetonas** [comment]
Thank you for your response, I will write my thoughts in detail.

They wanted us to implement a function that would disconnect engine power from the vehicle and prevent it from being transmitted when the manual clutch operates.
Sorry, the way I said "same condition as neutral gear" was inappropriate.

If the manual clutch variable is not activated during a shift change, the gear will not move or will shift back. (It would be nice if engine_shifting_grinding.ogg sounds here)
However, if "clutchTime" is set in the engine json, the clutch variable will operate when changing gears, allowing you to change gears without manually pressing the clutch key.

This is the function of the clutch that I thought of.
But implementing this would, as you say, require a lot of changes to other control systems. That might be too selfish of me.

Another idea was to add a variable that simply decouples engine power from the vehicle.
I feel that this has less significance than the above functions, but it does not need to be combined with other control systems, and I think it will expand the range of pack production.

As for the parking brake...sorry, that's just my personal opinion. Because I like drifting.
However, after seeing many packs that implement sports cars, I feel that many of them also take into account drifting.
In addition to the toggle, I think the range of play will be expanded if an easy-to-operate parking brake that operates with hold is added.

（When the p_brake variable is activated, instead of just stopping with "brakingFactor", the friction of the wheel is greatly reduced, 
and it looks even better if the specified wheel (basically the rear wheel) stops rotating. I feel like this would be very difficult to implement）

I realize that these are far less important than the bugs and improvements that MTS has to deal with.
I just thought it would be nice if that were the case, so if you feel it's not good, feel free to ignore it.

**Comment by DonBruce64** [comment]
Unless this is for a specialized control system where clutches are possible, I don't see this being a feasible thing to handle.  Especially not considering most players use a keyboard.  If such a controller set up is provided for testing, I could see about adding clutch support.  But honestly, it's such a niche case that I'm not about to program in the feature with nobody set to use it in the first place.
