### ISSUE TITLE
More engines types 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#176]
Hi, I’m here for a few suggestions to improve engines:
- electric engines:
They come with a json defined battery, to be recharged they don’t need lava but redstone, maybe let it support RF from other mods? The « fuel pump » will be a charger fed with redstone dust.
- Nuclear engines:
Boats? Submarines? Trin Frog? There will allways be a use for nuclear powered engines. As minecraft doesn’t have any radioactive stuff, maybe use dragon breath or glowstone as « fuel »? (I know technically nuclear powered engines are electric engines, so maybe make the nuclear power supply a part as the same title as batteries for electric engines? Just slightly bigger.)

**Comment by DonBruce64** [comment]
Nuclear engines are out, if only because there's no good way to have that powering them, except using radioactive liquid fuels, and that's just a new engine type for nothing.  Electric engines are a possibility, though I need to check how Forge/MC does energy in 1.12.2.  Putting this on the backburner for now as it doesn't fit well with the current liquid-fuel system.

**Comment by TheOddlySeagull** [comment]
Other solutions: add more default fluid types to MTS base config:
- electric: uses all those sweet fluid redstone added by several mods, tho I don’t have the names in my mind
- nuclear: uses all uranium plutonium and so on

**Comment by DonBruce64** [comment]
Will need the fluid names for these fluids in order to be able to add them.  Can you provide them?

**Comment by TheOddlySeagull** [comment]
All that redstone stuff is FluidRedstone
But idk about uranium

**Comment by DonBruce64** [comment]
Pretty sure that's not the name, as all identifications in Minecraft have to be lowercase as of 1.12.2.  Again, if you can give me the exact fluid name then that'll work.  Might need to use the older versions of MTS that print all the fluids to get that, or check the mod's wiki pages.

**Comment by DonBruce64** [comment]
Closing this as I don't feel I'll ever add more engine types besides what are already present.  It'd be too hard to change the engine systems to work with not internal-combustion engines.  I will consider new fuel liquids, but that's for #222, not this one.
