### ISSUE TITLE
Death Time tag in player data prevent players from entering a vehicle when set to -1.

### ISSUE THREAD

**Issue by AntoineC118** [DonBruce64/MinecraftTransportSimulator#1764]
As said in the title. When a player in dead, the death time is set to -1 but when he revive by any others way than the respawn button (like commands) the Death time tag is not reseted and stay at -1. This prevent users from entering any vehicle as the mod think they are dead. The only to fix the problem then is to delete the player's data are modifying it to make delete set the tag to 0 manually.

**Comment by AntoineC118** [comment]
Precising it's in 1.16

**Comment by DonBruce64** [comment]
Addressed in 22.13.0.
