### ISSUE TITLE
Sound Issue

### ISSUE THREAD

**Issue by LoganTheGamer1907** [DonBruce64/MinecraftTransportSimulator#1765]
For some reason in my 1.12.2 game, any vehicle with active YAW control, be it flying or for guns, they just turn the camera and not execute the proper task.

**Comment by LoganTheGamer1907** [comment]
(Fixed by updating mods)

**Comment by LoganTheGamer1907** [comment]
Now i have an issue with sounds and no matter what i do with sound config for IR it won't fix it

**Comment by DonBruce64** [comment]
There's nothing I can do with the sound issue.  If it's not IR doing the sound slot thing, it must be another mod.  Do you have any of those mods listed in the notification?

**Comment by LoganTheGamer1907** [comment]
No unfortunately. I am looking at other sound mods that may interfere supposedly a FTB mod can. But other than that i am not sure.

**Comment by LoganTheGamer1907** [comment]
Every sound works accept for any vehicle mods. (excluding flan's)

**Comment by LoganTheGamer1907** [comment]
It's not FTB mods. I can upload my mods if you would like me to do so

**Comment by DonBruce64** [comment]
All IV sounds are done the same way.  Can you remove some of your mods and keep trying to see if sounds occur?  And do you get the sound slot error?  Also, feel free to ping me on Discord if you want faster response.

What I'm trying to find out here is which mod is blocking IV's sounds, so I can look into what setting needs changing, or which mod needs to be added to the error message.  I can't fix this issue, but I can better document it for future people.

**Comment by LoganTheGamer1907** [comment]
Yeah, makes sense, you won't always know all and will learn from mistakes benefiting from them in the future. And i will reach out via discord. Great mods you do though, been using them for a long time

**Comment by DonBruce64** [comment]
Addressed in 22.14.0.
