### ISSUE TITLE
[Feature request] Rounding variables.

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#1767]
Add some way to round variables. Maybe `_floor`, `_ceiling`, and `_round` suffixes for variable names.

i.e. `engine_hours_1_floor` would make `174.7` hours into `174`. I'm not sure whether having it after or before the part index number would be best.

I can likely do this myself, I just wanted input particularly on specific implementation.

**Comment by DrprofLuigi** [comment]
Actually adding an argument to the animation may be more consistent, similar to `absolute` and `offset`.

`"roundingType": "round"`, `"roundingType": "floor"`, and `"roundingType": "ceiling"`

**Comment by DonBruce64** [comment]
The only time I can see this being useful is for the text display functions, and those let you round variables by displaying the desired number of decimal points.  Is there a spot for the feature where such rounding would be desired?

**Comment by DrprofLuigi** [comment]
> Is there a spot for the feature where such rounding would be desired?

I had something specific in mind, but after some thought I realized I can do it just fine with VMs.
