### ISSUE TITLE
roads????

### ISSUE THREAD

**Issue by abysschroma** [DonBruce64/MinecraftTransportSimulator#1768]
the in-game manual talks about how you place dynamic/static roads. While I can't find them anywhere in the first place.
Do they even exist?

**Comment by abysschroma** [comment]
found similar post
well that was so confusing also ig the mod doesn't really add roads despite the fact the manual says theres 2 types of roads "in the mod" lol

**Comment by DonBruce64** [comment]
Clearly, you haven't checked the IVV pack...

**Comment by abysschroma** [comment]
Well there's so many packs and I've only installed what looked like what I needed.
Would be nice if there was bit more explanation on what it adds.

**Comment by Polybius223** [comment]
Where we’re going we don’t need, roads.
Sorry I had to
