### ISSUE TITLE
Sound engine issue

### ISSUE THREAD

**Issue by sssssLug** [DonBruce64/MinecraftTransportSimulator#1769]
mts version: 1.16.5 - 22.12.1 (newest)

When you add Immersive Vehicles and any addon pack to the game, place any vehicle and start the engine, your latest.log will be stuffed with [Sound engine/INFO]: [net.minecraft.client.audio.Listener:handler$zzc000$inject_setListenerOrientation:533]: SETTING; And
it will start to freeze the game gradually.
I dont think this log would be useful ...
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/14135241/latest.log)
And here is the config file
[mtsconfig.json](https://github.com/DonBruce64/MinecraftTransportSimulator/files/14135245/mtsconfig.json)

**Comment by DonBruce64** [comment]
Issue found, fixed, and will be in next update.

**Comment by DonBruce64** [comment]
I'm leaving this open until said update drops, since it affects current users.

**Comment by DonBruce64** [comment]
Addressed in 22.14.0.
