### ISSUE TITLE
Furniture 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#177]
Well, another suggestion:
Furniture, such as functional crafting tables, furnaces, beds…
I mean, crafting tables part would be useful in any utility vehicles (pickups, vans…) or RVs, furnaces for onboard «kitchens/heaters » (like in airplanes, boats, RVs…) and sweet beds for RVs, roof tents, or even first class airplane places?
Obviously all those will be usable. Maybe even add a way to define its efficiency in the json?

**Comment by DonBruce64** [comment]
Since you said crafting tables first, I'm going to limit this ticket to those only.  Will be a good small step for such things, especially since I shouldn't need to code any extra systems for those parts besides the ones that open the GUI.

**Comment by TheCactus27** [comment]
The bed could just be a different seat type that renders the player as lying down without changing the time or setting the spawn.

**Comment by DonBruce64** [comment]
For sure not changing the spawn.  Because all you'd need is a bed in the air setting your spawn above the ocean.  However, changing time isn't a bad idea as if you have an RV or an airship you can sleep there.  Same reason Archimedes is popular.

**Comment by DonBruce64** [comment]
Added in V15.3.0.
