### ISSUE TITLE
NBT storage/data yeeting parameter

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1773]
Essentially, you have a part so basic in function that it doesn't need to save any data when removed and turned into an item (lightbar, bumper sticker, a part as a crafting item, any simple generic_ part, etc.) that it, well, doesn't do that when you wrench it. We're talking doesn't actually do anything when damaged or totaled, doesn't take any subparts (or cannot be removed when they're installed), _absolutely nothing on it_ needs to be saved and reloaded when it is wrenched. You basically just get a fresh item!

**Comment by boot2big** [comment]
Ahhh, I see. In that case perhaps I could also throw it out there, a parameter for VMs that keeps them from being saved as NBT data? I'd say assume they need to be stored by default, with the parameter selectively marking VMs for not-storing?

**Comment by DonBruce64** [comment]
VMs are designed to modify existing variables, not create/store new ones.  If those get trashed, then such things will need to wait for the animaton overhaul I'm working on.

**Comment by boot2big** [comment]
Eerrrr... you mean I _wasn't_ supposed to be using those to store things like vehicle mileage, and the like? Uh oh. It's not a big request anyways, no worries.

**Comment by DonBruce64** [comment]
Addressed in 22.14.0.
