### ISSUE TITLE
Can't ride specific pack vehicles as well as crash when being able to enter other certain vehicles

### ISSUE THREAD

**Issue by MatheusMM75** [DonBruce64/MinecraftTransportSimulator#1774]
Sadly, minecraft isn't giving a crash .txt for me to attach here, but when putting vehicles(cars, planes, jets, military trucks) from these following mods, this message is given on chat: "Attempted to add (item from mod)(e.g.:iav:iav_seat_none) but that part doesn't exist in the pack item registry." I'm able to put them on the ground but right-clicking any of the vehicles that should be functioning just by right clicking works. Following mods are:
- ZDVehicles
- City Cars
- VEB Automobilwerke Schwikau
- R.A.G.E

And game crashes when trying to ride cars from Sphase Vehicles. I can enter them and briefly walk for like 2sec, but game crashes with no log of it. Any ideas on how should I proceed?

**Comment by DonBruce64** [comment]
Closing due to seemingly fixed due to missing packs.
