### ISSUE TITLE
[bug?] about lightObjects in 1.16

### ISSUE THREAD

**Issue by Munancho-Hepetonas** [DonBruce64/MinecraftTransportSimulator#1776]
I think brightnessAnimations of lightObjects is not working properly in 1.16.

![ezgif-2-b9f582a86e](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/156426414/93e49576-a7e2-4244-ae77-3cedebbb8d43)

left is 1.16 and right is 1.12, and the json is the same in both.
I used "duration" and "clampMax" to create a lamp that glows at 70~80% or lights up smoothly, but it doesn't work in version 1.16.
Only beam and flare seem to be working correctly.
Is this a bug or by design? Or is it just my environment?

**Comment by DonBruce64** [comment]
Potentially?  What graphics settings are you using in 1.16.5?  Are you using the Wonderful/Fabulous?  Because I'm just now hearing issues about that setting.

**Comment by Munancho-Hepetonas** [comment]
![saddsa](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/156426414/16677181-d402-4e8b-922f-36487a56f80f)

I had the graphics settings set to Fast until now. And optifine was not introduced.
Similarly for Fancy, duration and clampMax didn't work properly.
When set to Fabulous, lightObjects itself stopped working and transparent objects disappeared.

**Comment by DonBruce64** [comment]
Noted.  I've got a thread active on Discord looking at this very issue, so if you want to join there you'll find some similar folks and test builds once I figure this out.  Otherwise, keep tabs here and when you see a commit pushed you'll know it's fixed.

**Comment by DonBruce64** [comment]
@Munancho-Hepetonas are you using the latest release build or the source code?

**Comment by Munancho-Hepetonas** [comment]
Do you mean whether the mod version is the latest? I'm using 22.13.0 version

**Comment by DonBruce64** [comment]
That is indeed what I mean.  Are you able to join this Discord thread?  I'm working on blended issues right now, and having yours in there and you able to test would help.

https://discord.com/channels/232316230852280320/1216077287653507112

**Comment by DonBruce64** [comment]
Fixed as of one of the latest beta builds.  Not sure which one though.

**Comment by DonBruce64** [comment]
Fixed in 22.15.0.
