### ISSUE TITLE
Radios don't support m4a files.

### ISSUE THREAD

**Issue by YiceLi** [DonBruce64/MinecraftTransportSimulator#1779]
As the title says, when I pasted the music link generated by the web music player to the station, it didn't work, the mod's manual doesn't seem to be detailed enough for the description of the car station, hope to adjust it in a future version, thank you very much!

**Comment by DonBruce64** [comment]
If you want help, you'll need to give me more information than "it didn't work".  The link used, the player used, the version used, are all important.  There are so many different players I literally can't have a section for all of them.

**Comment by YiceLi** [comment]
Sorry I didn't provide more details in the previous question, the version of the mod is 22.12.0, as for the music link, I tried all the web players in my country (CHN), all invalid, maybe I should try the link on the Windows Media Player first, and then enter it into the game when available.thank you for your answer!

**Comment by YiceLi** [comment]
Hello, this time I used the browser's dev mode to grab the music address, and after testing, the links generated by the websites I tested before can be played on Windows Media Player, but pasted into the game will show "is not an audio format". May this be due to the media format? 

https://github.com/DonBruce64/MinecraftTransportSimulator/assets/113981961/2e6b7803-5e02-475e-8791-c3805adfe93a

**Comment by DonBruce64** [comment]
I don't think that's the issue.  Can you paste the link here?  I'm thinking that the link you're using is a playlist link to other streams, and IV isn't smart enough to detect the forwarding.

**Comment by YiceLi** [comment]
Here's the link: 
https://m804.music.126.net/20240309093256/7d64211daa5ebf300141d9bb28a54c98/jdyyaac/obj/w5rDlsOJwrLDjj7CmsOj/29345195293/d94f/5c08/5028/04cb67f2539fb2379aca2873c988b947.m4a
 but it looks like a temporary address, and may be blocked by the Great Firewall of China when you access

**Comment by DonBruce64** [comment]
Hrm, you're not wrong. Can you go where you got that link and right-click and save-as it to your computer?  It should download a small file.  If it looks like it's downloading a lot, then that's an actual internet stream.  But I've encountered this before where some music "links" are actually files with multiple other links in them.

**Comment by YiceLi** [comment]
It does download one music file
![Screenshot 2024-04-16 185339](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/113981961/f842d021-38d1-4b2c-8e7c-0cd75f74aebb)

**Comment by DonBruce64** [comment]
That's a surprisingly large file for a media stream....  Usually those are smaller.  Can you upload it here?

**Comment by YiceLi** [comment]
Here

**Comment by YiceLi** [comment]
Here

**Comment by DonBruce64** [comment]
Ah, okay, I see what's happening here.

So what you have there on the website is the actual audio file.  However, the file is M4A, which is a format that's a container-based format by Apple, which IV doesn't support with its parsers.  It only supports MP3 and the Minecraft-standard OGG formats (though it also supports WAV as that's what it internally converts files to, but _nobody_ stores files in that format online anymore).

So what you can do is download the files you want to your computer, convert them to MP3 files using some sort of converter program, and then put those in a local folder for playback on the LOCAL setting vs using the URL for the INTERNET setting.

I myself cannot code in M4A support, so this is where it will have to stand unfortunately.
