### ISSUE TITLE
How do we have storage in vehicule + Gauge can't be placed!!!!

### ISSUE THREAD

**Issue by guilefilou2** [DonBruce64/MinecraftTransportSimulator#1781]
Hello,

I need help and i can't find doc or help on this. We have crate. (nice!) but i can't place it into my car/truck (i test 5 different vehicule and dosen't working...)
I won't download UNU car pack.

2nd problem... i can't place gauge on my car (any). i don't have black GUI to select where to place the gauge.

to respond my, I will prefer gmail (guilemuguet@gmail.com)
thx to help

**Comment by DonBruce64** [comment]
Crates that you place on the ground need to be configured to be placed in vehicles.  Most pack authors have not done this, and so their placable crates are block-decor, and aren't compatible as vehicle parts.  You'll need to get with the pack authors of those crates for them to fix this.

As far as the gauge, you need to use the wrench to open the GUI for this.  Do you have nothing in the GUI you mean?  Post a picture.

**Comment by guilefilou2** [comment]
Hello,

finally i find the solution: i have downloaded another of your vehicule
mods (with the Bell helicopter)
and it work so i will replace my vehicule by this.
(helicopter is too good for exploring)
thx for your mod and thx for don't crash my game (because i have an old
computer)

GG
goodbye

Le mar. 19 mars 2024 à 05:49, DonBruce64 ***@***.***> a
écrit :
