### ISSUE TITLE
Radio doesn't work in 22.15.0?

### ISSUE THREAD

**Issue by HolaSoyTuVieja** [DonBruce64/MinecraftTransportSimulator#1786]
So I've been trying to get the radio to work by using audio files on my pc. The only problem I have is that the radio only plays the first seconds in the song, and then stops. It happens in all 6 folders, and if were to try to play the song again, it would continue from where it stopped before. I did notice that this doesn't happen in version 22.13.0, but I do not want to change the version. I'm using mp3 files and I'm on version 1.12.2 using 22.14.2

**Comment by DonBruce64** [comment]
Drat, my code changes to fix the radio issues must have broken local playback.  Will review and fix.

**Comment by DonBruce64** [comment]
Seems to be fixed with latest radio audio beta.

**Comment by LeoCraft15** [comment]
ye i got the same issue here

**Comment by DonBruce64** [comment]
Fixed in 22.15.0.

**Comment by CSdiscoveries** [comment]
No audio files have played for me whatsoever

**Comment by DonBruce64** [comment]
This for the internet stuff or the local files?

**Comment by CSdiscoveries** [comment]
Both.

**Comment by DonBruce64** [comment]
Well, it works for me, so something must be up with your installation.  I'll be on Discord later on in the week (maybe Friday, or Monday) and can do some debugging then.

**Comment by DonBruce64** [comment]
Closing due to no response.
