### ISSUE TITLE
forceCameras causes cameras to rapidly switch between all views

### ISSUE THREAD

**Issue by vinidamiani** [DonBruce64/MinecraftTransportSimulator#1790]
Basically when you add "forceCameras" to a part, it makes so the view rapidly switches between all available cameras

Also, camera overlays are missing the alpha channel and will be completely distorted if using any aspect ratio other than 16:9, which weren't an issue in V21.0

**Comment by LauraDarkez** [comment]
@vinidamiani the alpha channel missing is because you now need to include "_translucent" or "translucent_" in the filename.

**Comment by DonBruce64** [comment]
@LauraDarkez Did this really happen though?  I thought I just made all camera overlays translucent by default?

@vinidamiani Noted on the camera stuff.  That's likely another mod that's fouling things since I can confirm it works on my end.  What other mods do you have installed and does this happen if you remove all others?

**Comment by vinidamiani** [comment]
Thank you very much for the replies, adding _translucent at the end of the texture seems to work well, there is still the distortion issue, I don't know if that qualifies as an issue or a suggestion for an improvement

As for the flickering

I only have Immersive Vehicles V22.14.2 installed with Forge 14.23.5.2859

The issue seems to persist trough multiple computers and other packs besides my own

I could be using forceCameras improperly? Its currently inside the seat part slot, above the gun that adds on to it, and the gun has the camera. If I switch using F5 it works

**Comment by LauraDarkez** [comment]
oh, question: do you have more than one camera "available" for forcedCameras to detect? im wondering if maybe you need to perhaps add activeAnimation visibility anims that disables all but one camera at a time at any given time. for example, make the first camera active only when main gun is active, second camera only when on secondary gun, or something akin to that

**Comment by vinidamiani** [comment]
I only have the one camera in the entire vehicle, and I even set up a visibility animation already in case I add more and so the camera isn't visible from the other seats

otherwise, only the one camera, I don't know if the vanilla cameras matter? Cause it is cycling between the gun camera and the default first person view camera

**Comment by DonBruce64** [comment]
@vinidamiani I know you're not about to join the IV discord, but can you get with me in DMs so I can send you a beta with camera changes?  We re-did a few things recently and I want to check if it'll fix this issue or not.

**Comment by DonBruce64** [comment]
Closing due to no response.
