### ISSUE TITLE
Suggestion: Part Weight Adjustment

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#180]
Currently all parts are 50kg. It may not look like a big problem but imagine a 100-seated plane. That’s a solid 5000kg added to the weight. It’s not only hard to tune but also makes player's life harder.
Making each part’s weight customizable will fix most of the things, but making them completely weightless will save even more trouble as pack authors won’t have to worry about one more number.

**Comment by DonBruce64** [comment]
Since most vehicles won't notice the extra 200Kg being lost relative to Steve's lard butt and his huge inventory, the removal of the 50kg per-part calculation isn't a huge loss.  Well, except in the case of jets, but you get the point.  Can-do.

**Comment by TheOddlySeagull** [comment]
Still, it’s weird to have a bumper sticker as heavy as a 2m diameter off roading wheels, or a i2 engine as heavy as a 5x2 pixel cheap wheel :x

**Comment by DonBruce64** [comment]
Implemented in V15.0.0.

**Comment by fsendventd** [comment]
So parts are weightless now? That sounds good... we can make extremely light motorcycles now. And I'll be able to get the Tornado tuned better.
