### ISSUE TITLE
mts error

### ISSUE THREAD

**Issue by samet9999** [DonBruce64/MinecraftTransportSimulator#1803]
![Ekran görüntüsü 2024-06-08 170358](https://github.com/DonBruce64/MinecraftTransportSimulator/assets/156913291/c8698942-73c2-4d7e-b841-036ba6ecdecf)

how to fix this?

**Comment by DonBruce64** [comment]
You _read what it says_.  You can read, right?

**Comment by SnailPerson** [comment]
goofy aah bug report
bro went out of his way to post this on git instead of reading 10 lines of text 💀
