### ISSUE TITLE
You can not hear the Cars audio

### ISSUE THREAD

**Issue by TheGTApro178** [DonBruce64/MinecraftTransportSimulator#1808]
Its a Random bug that popped up MTS Is claiming that their are No Audio slots present.

**Comment by DonBruce64** [comment]
You're gonna hafta give me more information than this....

**Comment by TheGTApro178** [comment]
I just found out what the problem was It is Immersive Railroading Addons Conflicting with the Audio Slots. Or some mods that use the MTS formula.

**Comment by CSdiscoveries** [comment]
This issue can occur even without any of the "conflicting" mods listed in the error message.

**Comment by DonBruce64** [comment]
Yeah, but in that case it's either a yet-unknown conflicting mod (which we should document), or it's a bad sound block in an IV vehicle that's spamming sounds or leaving them playing.  Both should be handled on a case-by-case basis.
