### ISSUE TITLE
`variableModifiers` don't seem to run on handheld guns

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1811]
I don't know how I didn't notice this earlier (other than a hard dip in motivation lately.. sorry) but VMs just, don't run on guns.

Not ideal for all my handhelds since they do fancy shoot-better-when-aiming-(because-you-shoot-worse-when-freehanding) stuffs, but also worse for specific ones that need VMs like the minigun.

**Comment by DonBruce64** [comment]
Interesting, I never expected anyone to want to run VMs on hand-held parts.  I did have them for placed parts, but apparently not hand-helds.

**Comment by LauraDarkez** [comment]
they worked on handheld guns before though, weve been using them for a couple of things, including the toggle lock on my luger

**Comment by LauraDarkez** [comment]
also, good to see youre still alive at least, even if you havent been active on the discord.

**Comment by DonBruce64** [comment]
Addressed in 22.16.0.
