### ISSUE TITLE
Shift Rmb on beacons doesnt open the beacon gui (issue fixed itself)

### ISSUE THREAD

**Issue by bbass42** [DonBruce64/MinecraftTransportSimulator#1814]
unable to open the beacon gui, using a wrench while holding down shift and rmb newest version of MTS version 1.12.2

https://github.com/user-attachments/assets/de4a7942-1614-4ea7-913b-a1a99cfc4b3c

**Comment by boot2big** [comment]
As a temporary solution, try closing and reloading your world after placing all interactable decor blocks such as beacons, ImageURLs and radios

**Comment by bbass42** [comment]
the issue has fixed itself, not sure what caused it

**Comment by CSdiscoveries** [comment]
I am having the same issue.

**Comment by DonBruce64** [comment]
Is this only beacons, or also vehicles?

**Comment by CSdiscoveries** [comment]
Only beacons

**Comment by boot2big** [comment]
I believe the reason for this issue "fixing" itself is to do with this ticket on the Discord server

https://discord.com/channels/232316230852280320/1257866341658923008

**Comment by bbass42** [comment]
beacons have to be unloaded for them to be useable, placing them down and going far enough way to unload them and coming back and then they are usable

**Comment by CSdiscoveries** [comment]
Still inconvenient

**Comment by DonBruce64** [comment]
Yeah, still a bug if it don't work right.

**Comment by DonBruce64** [comment]
Addressed in 22.16.0.
