### ISSUE TITLE
Constantly appearing "entity.mts.builder_rendering" with HUD mods

### ISSUE THREAD

**Issue by CSdiscoveries** [DonBruce64/MinecraftTransportSimulator#1817]
While it doesn't impact the ability to break blocks, HUD mods such as Jade register an entity called "entity.mts.builder_rendering" at 8 specific positions around the player, when the player is looking 30-60 degrees up or down, and at roughly 45 degree angles to the global X/Z axis.

**Comment by DonBruce64** [comment]
Can you show me a video with Jade installed and bounding boxes shown?  There should be a little blue one that's the rendering entity that should always be visible just above the player's eyes.  That one should move with your player.  If it's not, that's an issue of some mod blocking it.  If it is, then Jade shouldn't be saying anything unless you have mouseover over it.  If you don't, and Jade reports it, then it's a Jade issue.  Though if it's 1.16.5 (version wasn't specified here) it might be a server/client syncing issue, but I think Jade is a client-only mod so I doubt this.

**Comment by malvineikemo** [comment]
I got the same issue, using Jade, on 1.16.5, kinda annoying xD

**Comment by DonBruce64** [comment]
Well then can you give me the info I need to fix it?  Still waiting on the other feller to respond.

**Comment by malvineikemo** [comment]
What is a bounding box though...

**Comment by malvineikemo** [comment]
I'll try

**Comment by VladTheEvilCat** [comment]
I have encountered the same entity, however it does prevent placing and breaking of blocks for me. This mod is being used in a modpack, which miight explain why it blocks placing and breaking blocks when it's being looked at.
![2024-08-12_19 02 37](https://github.com/user-attachments/assets/ae5ee3e1-f8ed-4326-b071-0de703c524c5)

**Comment by DonBruce64** [comment]
Again folks, need to see bounding boxes...

**Comment by VladTheEvilCat** [comment]
The bounding boxes are not visible, with or without f3+b

**Comment by DonBruce64** [comment]
> The bounding boxes are not visible, with or without f3+b

Then you need to fix this.  Without the bounding boxes of entities displayed, I cannot debug this.  Some mod is hiding those, remove it and please report back.

**Comment by VladTheEvilCat** [comment]
>  > The bounding boxes are not visible, with or without f3+b
> 
> Then you need to fix this.  Without the bounding boxes of entities displayed, I cannot debug this.  Some mod is hiding those, remove it and please report back.
Got it, will do- will report back in 1 hour tops

**Comment by VladTheEvilCat** [comment]
> >  > The bounding boxes are not visible, with or without f3+b
> > 
> > Then you need to fix this.  Without the bounding boxes of entities displayed, I cannot debug this.  Some mod is hiding those, remove it and please report back.
> Got it, will do- will report back in 1 hour tops
> 

Nevermind, I may not be able to report back today

**Comment by DonBruce64** [comment]
Closing due to no response.
