### ISSUE TITLE
Handheld gun firedelay and spreadfactor appears to be ignored

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#1818]
as it states. if you fire any handheld gun, it fires with 0 tick delay it feels like. and spreadfactor also doesnt work, so its like shooting laser beams

**Comment by LauraDarkez** [comment]
@boot2big has examples of this as well

**Comment by DonBruce64** [comment]
Addressed in 22.16.0.
