### ISSUE TITLE
Option to Remove Lava Fuel

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#182]
With the new fuel system, I would recommend a config file option that disables vehicles being able to use lava. This would mostly be for modpacks where using lava would cheat around more advanced fuels.

**Comment by DonBruce64** [comment]
Uuuh, that's already a config option.  In fact, with V14 and the upcoming V15 you can remove Lava as a fuel source via the config.
