### ISSUE TITLE
Electric ovens not shutting off after they have nothing else to smelt

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1820]
When a furnace is electric and runs out of cookable goodies, it may continue to run while drawing power from the vehicle (and generating heat) for no reason, as it has nothing else to process

**Comment by LauraDarkez** [comment]
in addition to this, it holds its heat and never depletes even if it has used all the battery power in the vehicle

**Comment by DonBruce64** [comment]
Addressed in 22.16.0.
