### ISSUE TITLE
Instruments on parts don't check for engines on said parts if optionalPartNumber is used

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#1821]
Ticket submitted upon Laura's account of this issue

**Comment by LauraDarkez** [comment]
correction, instruments on parts dont exclusively read for engines on the same part, regardless of optionalPartNumber

**Comment by boot2big** [comment]
>.<

**Comment by DonBruce64** [comment]
388d23b594671e0450d9a22a0c65f9335802daa0

**Comment by DonBruce64** [comment]
Addressed in 22.16.0.
