### ISSUE TITLE
Removal of outdated Universal Tweaks warning

### ISSUE THREAD

**Issue by ACGaming** [DonBruce64/MinecraftTransportSimulator#1825]
Hey there,

I'm the author of Universal Tweaks and can assure that the Entity Desync functionality was improved to no longer cull Immersive Vehicles' entities.

The implemented warning can be safely removed now:

https://github.com/DonBruce64/MinecraftTransportSimulator/blob/master/mcinterfaceforge1122/src/main/java/mcinterface1122/InterfaceClient.java#L206-L213

Kind regards
ACGaming

**Comment by DonBruce64** [comment]
Rodger that.  Thanks for letting me know!  I'm honestly not surprised that your mod culled the entities since they have some funky logic in them to prevent MC's default shenanigans from occurring.  Will remove that notice on the next relese!

**Comment by DonBruce64** [comment]
Addressed in 22.16.0.
