### ISSUE TITLE
No Cleaner for the Spray Cans and I miss more colours. (Mod: Immersive Vehicles - Official Content Pack)

### ISSUE THREAD

**Issue by Titoo8899** [DonBruce64/MinecraftTransportSimulator#1826]
Hi,
I have many Problems found in your mod. One of this was the new Functions of the Spray Cans. Okay I can a wall with a colour spray but I have no chance to clear it. Please it a cleaner for the Spray Can Colours. 
I Hope you can a Water Can add with the function to clear the Colours of the Spray Cans and I hope you can more colours add in the next update. 
![2024-07-31_18 03 29](https://github.com/user-attachments/assets/ae382c22-3fb8-477f-9b58-8e07976e1def)

**Comment by DonBruce64** [comment]
@Titoo8899 just reload the chunk, they'll go away.  They're just particles.

Say @SnailPerson I realized that the particles for the spray can will go away.  Thoughts on something that makes particles persist and just do no logic on death and just render?

**Comment by SnailPerson** [comment]
@DonBruce64 would they be removed on world reload? Persistent particles

**Comment by DonBruce64** [comment]
> @DonBruce64 would they be removed on world reload? Persistent particles

No, I'm thinking of saving them on world load.  They'd persist in the world file itself and stay forever, or at least for a far longer time, but they wouldn't do logic during that time.  No physics or sounds or anything.  Just a maintained state.  Though I'm un-sure what this would be used for EXCEPT the paint.  Perhaps bullet casings and bullet holes and such?  Though eventually I could see this being an issue with too many causing lag.  Thoughts on how to handle that?

**Comment by Mike74846** [comment]
When I checked it, I had removed the block and the sprayed part was still there despite the block being removed, which logically makes no sense since it is floating at the moment

**Comment by DonBruce64** [comment]
@SnailPerson yeah, it's probably not the best since there's not a good way to handle their removal.  TBH @Titoo8899 the paint it more just for fun than anything else.  I'm keeping them as-is for the moment.

@SnailPerson how long does the paint stay present in the world?
