### ISSUE TITLE
The new Mustang have a Seat Problem (Mod: Immersive Vehicles - Official Content Pack)

### ISSUE THREAD

**Issue by Titoo8899** [DonBruce64/MinecraftTransportSimulator#1827]
Hi,
in this Issue will I speak a Problem with the new Mustang. I have all thinks add. Wheels, a engine and seats. But to see in the Picture is the Seats was not conform to the Vehicle and have a bad texture on the Top of the Car. I hope you can fix it.
![2024-07-31_18 00 35](https://github.com/user-attachments/assets/7841abb5-1ba3-404d-8885-1f28b0a02f83)

**Comment by DonBruce64** [comment]
You're using the wrong seats.  You need to use the car seats, not the plane ones.  @SnailPerson it says that the plane seats don't go to cars, right?

**Comment by Titoo8899** [comment]
Change this please. Make a check what items in a object can I place and what not.

**Comment by SnailPerson** [comment]
@Titoo8899 as don_bruce mentioned, you're using the wrong seats. These are aircraft seat and the mustang is no aircraft.
besides that, its only a visual error, not a functional one.

**Comment by DonBruce64** [comment]
> @Titoo8899 as don_bruce mentioned, you're using the wrong seats. These are aircraft seat and the mustang is no aircraft. besides that, its only a visual error, not a functional one. Also you're using the wrong wheels. Those a medium wheels, you must use large ones.

Do the seats on the tooltip say they're for planes?  I think they do, but if not, we should probably specify.  If they do, that's on the user to realize that while you _can_ put the wrong seat into vehicles, it'll just look silly.  It's like putting a super big engine on a plane, or tiny tires on the GMC.  Part of the fun of IV is wacky combinations of parts.

**Comment by DonBruce64** [comment]
I just confirmed the seats do have this listed, this is a user choice, not an actual issue.
