### ISSUE TITLE
The Barrier only comes in one type (Mod: Immersive Vehicles - Official Content Pack)

### ISSUE THREAD

**Issue by Titoo8899** [DonBruce64/MinecraftTransportSimulator#1828]
hi,
this is a think what I hope you can add in the next update. The Barrier have only one type. But I hope you can add more varients of this type with curves or as cross.
![2024-07-31_18 02 10](https://github.com/user-attachments/assets/b2d47d42-2008-4725-a53e-d531db90e7e7)

**Comment by DonBruce64** [comment]
This isn't a bug, this is a feature request.  They belong on the OCP Discord, not here.
