### ISSUE TITLE
Signs, Pools and the Traffic had not Hitbox (Mod: Immersive Vehicles - Official Content Pack)

### ISSUE THREAD

**Issue by Titoo8899** [DonBruce64/MinecraftTransportSimulator#1829]
hi,
in this Issue will I the Problem with the new Sign, Pools and Traffic design speak. The Problem is the Items have then I have this Place and will it clear or higher make (pools 2 blocks higher make) no Hitbox. This is bad and I must so often click to place a Items or expand. I hope you can fix it.

![2024-07-31_18 01 57](https://github.com/user-attachments/assets/322cd0eb-4e3f-4e38-9f12-465dacf1370d)

**Comment by DonBruce64** [comment]
@SnailPerson correct me if I'm wrong, but I don't think IV makes the hitboxes bigger on poles when signs are present, right?  I think hitboxes are handled by collisions turning on and off by the main pole?  Thoughts on adding collisions when signs are present on a face?

**Comment by Titoo8899** [comment]
then a collision add to a sign was it good.

**Comment by DonBruce64** [comment]
Calling this fixed as poles don't have super-complex hitboxes to prevent lag.  What you get is simple collision.
