### ISSUE TITLE
More additional parts

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#183]
Yet we can only have parts on parts, but it would be very useful to have the ability to have more subparts, like a part on a part on a part :)

**Comment by DonBruce64** [comment]
While partception sounds fun for pack makers, it's somewhat hard to do in code without fouling things up.  You have to be careful to not have circular references with your stacked parts.  That being said, I can see it being useful for high-customibility of vehicles, so expect it to happen once all the bugs and core features get fleshed out.

**Comment by DonBruce64** [comment]
Implemented in 15.1.0.
