### ISSUE TITLE
World Load the Models of all places Models in 5-10 sec. (Mod: Immersive Vehicles - Official Content Pack)

### ISSUE THREAD

**Issue by Titoo8899** [DonBruce64/MinecraftTransportSimulator#1831]
Hi,
in this Issue will I speak of the Loading time. The World Load normal but then I spawn in the world the Models what I have place was for the first 5 - 10 sec not load and then I have wait the Models will spawn. I hope you can fix the Loading time of the Models then I enter a world.

Enter a World no Models to see:
![2024-07-31_19 07 31](https://github.com/user-attachments/assets/857b3ab5-c241-450b-9935-0e02714c1c38)

Later 5 - 10 seconds of enter a world the Models was load and then I can see it:
![2024-07-31_19 07 34](https://github.com/user-attachments/assets/510cb2af-419a-4f2f-98db-137d9f2360bd)

**Comment by DonBruce64** [comment]
This is per design.  IV delays loading of models to allow the world to sync up and to not overload the Java VM.

**Comment by Titoo8899** [comment]
ah thanks for the answer
