### ISSUE TITLE
New traffic lights are terrible

### ISSUE THREAD

**Issue by Kasardas** [DonBruce64/MinecraftTransportSimulator#1833]
I just wanted to say that new traffic lights are terrible. Like 3 times too big, do not align to poles (which look nice but have terrible hitboxes). Old traffic light was way better and didn't obstruct road sign above it

![2024-08-01_21 06 32](https://github.com/user-attachments/assets/39f2e178-e9f0-48f9-a089-d6be15668eb7)

**Comment by DonBruce64** [comment]
Bruh, literally the prior issue #1830 is about this.  Pls don't post duplicates.
