### ISSUE TITLE
1.16.5 OCP V26 - New Vehicles Dont Show

### ISSUE THREAD

**Issue by Xylush** [DonBruce64/MinecraftTransportSimulator#1834]
I recently downloaded the new 1.16.5 OCP version to discover that the new vehicles aren't on the inventory list. 
Is this a bug or am I not doing something right?
![image](https://github.com/user-attachments/assets/e68e9573-6a20-4425-9f03-4b91ffa8cf3e)
![image](https://github.com/user-attachments/assets/eca7c987-c3f3-449c-a881-9d0ad854dcf4)
![image](https://github.com/user-attachments/assets/0a310b33-dce9-4e98-a7d8-cd401652443c)
![image](https://github.com/user-attachments/assets/068976bb-fc7a-4b8f-864b-850985adb213)

**Comment by SnailPerson** [comment]
@Xylush 
-> what is your MTS core version
-> please post latest.log
-> optionally, join the official MTS server and ping me with @mr.mulle. we can communicate quicker there.

**Comment by SnailPerson** [comment]
@Xylush has this issue been resolved?

**Comment by Xylush** [comment]
Issue has been resolved.

**Comment by SnailPerson** [comment]
> Issue has been resolved.

Awesome! What was the source of the problem?

**Comment by DonBruce64** [comment]
Closing due to no response.
