### ISSUE TITLE
Startup crash with 15.0.0

### ISSUE THREAD

**Issue by BrisingrAerowing** [DonBruce64/MinecraftTransportSimulator#184]
[Crash Log](https://paste.dimdev.org/xecesobowi.mccrash)

I'll revert to the previous version for now.

**Comment by DonBruce64** [comment]
Do you have any packs besides the OCP installed?  If so, they likely haven't updated yet.  This update overhauled the fuel system, so their engines are incompatible with the most recent updates.

**Comment by BrisingrAerowing** [comment]
Ah. That explains it.
