### ISSUE TITLE
[bug] the models for the vehicles are invisible when in replay mod 1.16.5

### ISSUE THREAD

**Issue by turbonoot** [DonBruce64/MinecraftTransportSimulator#1849]
I'm working on a project and I'm not sure if it's on my end or not but whenether i go into replay mod with immersive vehicles models being present, they just disappear. I thought it must of been one of my mods so i made a new forge instance with just immersive vehicles and immersive vehicles vanity and it was still invisible with replay mod. 
is this a 1.16.5 thing or is this fixable? 

this is the replay mod im using in case that's the reason why: https://www.curseforge.com/minecraft/mc-mods/replaymod-1-16/files/all?page=1&pageSize=20&version=1.16.5 
![Screenshot 2024-09-04 221439](https://github.com/user-attachments/assets/552ea626-b3a1-4dcb-b6ee-26ed213eb3d8)
![Screenshot 2024-09-04 221553](https://github.com/user-attachments/assets/784e39ad-a0f2-484d-bc43-4bf6b45e2763)

i could really use the help.

**Comment by DonBruce64** [comment]
There's already a config for this in the config file.

**Comment by turbonoot** [comment]
Oh i didn't know that. tysm i thought my project was about to be over

**Comment by DonBruce64** [comment]
It's on the config because it makes cars ignore shaders.  But that's the only way to get them to render in replay mod because that mod doesn't play nice with the main rendering entity.

**Comment by turbonoot** [comment]
oh ok that makes more sense
