### ISSUE TITLE
Game crashes when trying to load Imersive vehicles

### ISSUE THREAD

**Issue by DamondSword2247** [DonBruce64/MinecraftTransportSimulator#185]
The 1.12.2-15.0.0 version of Immersive vehicles causes a game crash when trying to load the mod.

**Comment by DonBruce64** [comment]
Crash report or it didn't happen.

**Comment by DamondSword2247** [comment]
Shit, I forgot to give a crash report sorry here
[crash-2019-09-27_19.02.52-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/3664780/crash-2019-09-27_19.02.52-client.txt)

**Comment by DonBruce64** [comment]
This is a duplicate of #184.  Will leave this one open for other to see until @DrprofLuigi updates his packs.

**Comment by DonBruce64** [comment]
This won't happen anymore in V15.1.0.  Added legacy support.
