### ISSUE TITLE
[1.12.2] Client crashing when trying startup the engine

### ISSUE THREAD

**Issue by 464444** [DonBruce64/MinecraftTransportSimulator#1857]
Crashing when trying to start engine or something..
including crash report
Been flying on the plane, engines got off for some reason, i landed and tryed startup the engine, i figured out that i didnt have fuel on my plane, ok i fueled up, and tried to startup the engine just hitting the propeller, and got CRASHED, tried again and got crashed :\
Myself and my friend just keep crashing when we wanted to start the engine, but server still working for some reason.
[crash-2024-10-12_05.44.29-client.txt](https://github.com/user-attachments/files/17348315/crash-2024-10-12_05.44.29-client.txt)

**Comment by 464444** [comment]
[crash-2024-10-12_22.23.49-client.txt](https://github.com/user-attachments/files/17350857/crash-2024-10-12_22.23.49-client.txt)
Trying to take off the ground, plane do not take off the ground, i crashed, and i get out of the plane, and game crashed.

**Comment by 464444** [comment]
I found out that thing, after creative in survival, engine can turn on without fuel, i tried to fuel up the engine, start the engine i GOT CRASHED. that's the thing.

**Comment by DonBruce64** [comment]
You have different configs on your client than the server.  Your client is confused what to do since it doesn't have the right fluids.
