### ISSUE TITLE
Undocumented animation varibles in mts 

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#1859]
Ticketing this cause i heard about this in mts passing conversation. the prefix "parent_" prefix thats useful for parts with VMs that need to read or write values from a vehicle, and varible "engine_gear_ratio", which displays the current gear ratio of an engine and can be VMd

**Comment by DonBruce64** [comment]
Added to the wiki animation hierarchy.
https://github.com/DonBruce64/MinecraftTransportSimulator/wiki/Pack-Making-JSON-Animations#animation-hierarchy
