### ISSUE TITLE
Crash with some vehicle packs in 1.19.2

### ISSUE THREAD

**Issue by AstralOreo** [DonBruce64/MinecraftTransportSimulator#1864]
When i spawn helicopters from ZD Vehicles pack and Hero Aviation Helicopter Pack in the 1.19.2 version, it crashes minecraft. 
[crash-2024-11-25_18.51.42-client.txt](https://github.com/user-attachments/files/17907270/crash-2024-11-25_18.51.42-client.txt)

**Comment by DonBruce64** [comment]
Don't post bugs here for versions that aren't released on Curse.  Those belong in Discord.
