### ISSUE TITLE
Animation format support that can be exported from 3d modeling programs

### ISSUE THREAD

**Issue by koapilot** [DonBruce64/MinecraftTransportSimulator#1867]
Basically a way to use animations that you made in blender and export them in gltf format for example, so you can use them ingame. This will make things way easier for complicated animations, especially landing gear.

**Comment by DonBruce64** [comment]
I won't do this as I don't have the time, but you can roll your own parser in the code and make a PR.  Plus, you gotta be a significant PA to be asking for new model formats.
