### ISSUE TITLE
Fuel Pump can fuel car after driving past 16 block limit while pumping

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#188]
The driver can start pumping fuel into the car, and then drive away as the pump continues to fuel the car... even though it's way past 16 blocks.
This continues until either the pump runs out of fuel, or the car and player drive far enough away that results in the chunk that the pump is in being unloaded and disconnecting from the car.

Also, you can connect multiple pumps to one car, which makes fueling much quicker, and probably isn't intended? (If it is, don't mind this part)

**Comment by DonBruce64** [comment]
The driving away is a bug for sure, but the multiple pumps is actually intended.  The idea being that larger vehicles can use multiple pumps to fill so they don't take forever.

**Comment by DonBruce64** [comment]
Fuel pump now disconnects in V15.1.0.
