### ISSUE TITLE
Brakes are way too powerful.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#189]
I just stopped a roughly 1500 kg car from 27.5 blocks per second (accounting for the speed factor, that's 175 MPH) in under 4 seconds. That seems... a bit much.

**Comment by boot2big** [comment]
After some calculation, the driver experiences 2.1 G's from this.

**Comment by fsendventd** [comment]
> 
> 
> After some calculation, the driver experiences 2.1 G's from this.

Thank you, I was wondering.

**Comment by boot2big** [comment]
Well technically negative G's, but that still can't be good.

Also, those brakes are gonna wear out very quickly.

**Comment by DonBruce64** [comment]
While I see your point about the forces, I feel that for the set of vehicles we have, the brake force is correct and well-rounded enough to not cause issues with the majority of vehicles.  Especially considering that more people have complained about the brakes not stopping quickly than stopping too quickly (racing games teach bad habits...).

I'm not going to look into this, but feel free to mess with the code yourself and submit a Pull Request for a system you feel to be better.
