### ISSUE TITLE
rotatableModelObjects in parts

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#19]
The ability to have rotatableModelObjects on parts would be nice. This would work great for contra-props, as well as for pulleys and fans on engines, and my axle part.

**Comment by DonBruce64** [comment]
Moving hitboxes are different that rotatable parts on parts.  The former involves a physical property that's on both the server and client.  The latter is simply a visual property that only affects the rendering code.

**Comment by fsendventd** [comment]
Oh, yeah, that's from when this had multiple requests in one issue. Not relevant anymore.
