### ISSUE TITLE
Override mirror from item

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#191]
It would be nice if the « overrideMirror: True » on parts themselves would work, rather than having it on the main model

**Comment by DonBruce64** [comment]
I don't follow.  What use-case is this that you are having this issue on?  Like what configuration?

**Comment by TheOddlySeagull** [comment]
When a part has « overridesmirror » it doesn’t work, it only works when the « override mirror » is in the main car

**Comment by TheOddlySeagull** [comment]
And the suggestion is to make that « override mirror » work from the parts json too

**Comment by DonBruce64** [comment]
Well yeah.  Because parts don't have that.  What exactly are you trying to do with your parts that the part needs to implement that logic?

**Comment by TheOddlySeagull** [comment]
Ok, I should also add that overrideMirror doesn’t work on everything, some « custom » types part will ignore the overrideMirror

**Comment by DonBruce64** [comment]
Will get with the current pack authors to make sure this doesn't affect them.  Otherwise, wouldn't be a bad idea.

**Comment by DonBruce64** [comment]
Didn't hear from authors, so figured it's fine.  Use overrideMirror in V15.4.0 now under the "general" section for parts to make them never mirror.  Same goes for vehicle JSON under the "parts" section.  No double-mirroring logic anymore.
