### ISSUE TITLE
Request: Dummy items for crafting.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#192]
Exactly what it says on the tin. I'm not sure how I can elaborate.

**Comment by DonBruce64** [comment]
This is planned.  However, it's a little harder to do than one would first think.  Expect it somewhere in the next few releases, but not in the next one.

**Comment by boot2big** [comment]
By dummy items, I'm presuming you mean pistons, gaskets and the such?
If not, I don't understand

**Comment by fsendventd** [comment]
> 
> 
> This is planned. However, it's a little harder to do than one would first think. Expect it somewhere in the next few releases, but not in the next one.

You asked me to put in a ticket...

**Comment by DonBruce64** [comment]
Implemented in V15.4.0.
