### ISSUE TITLE
(Suggestion) Allow for individual vehicle parts to play music disks.

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#195]
Pretty self-explanatory.
Allowing for pack creators to add things like car radios.
It would be amazing to have.

**Comment by TheOddlySeagull** [comment]
https://media.discordapp.net/attachments/572201695682101248/591943174285426719/seagull_approved_stamp.png

**Comment by DonBruce64** [comment]
But, why would you want to play the same music you normally hear in-game?

**Comment by NightScale5755** [comment]
well... Consider it a mobile jukebox? Like... There are mods for custom music discs... It would be hella cool to drive around blasting some tunes.

**Comment by boot2big** [comment]
I mean, some of them do add their discs as their own items, but some of them _do_ use the vanilla disc system, which means they'd probably work with a system like this.
_If_ you added this, it probably wouldn't drop the disc as an item when right clicked, though... not a good idea if you're moving

**Comment by DonBruce64** [comment]
While I can do this, I'd like to hook in support for actual radio.  Or at least saved mp3 files on the server.  Would allow people to make mixtapes and whatnot.

**Comment by DonBruce64** [comment]
Looked into this.  None of the mods that do music on 1.12.2 have good documentation, and I can't find much on Java-based systems that allow for playing MP3s.  Will leave this as a Backburner, but it I don't get assistance in figuring out what to use for this, I'm going to close it in a month.  Got other things to do than try to figure out other's people's wonky sound-systems.

**Comment by DonBruce64** [comment]
Somewhat implemented in V15.5.0, in that you can play your own music and internet radio.  Am calling this closed right now, but expect feature enhancements to come down the pipeline after the V16.0.0 update once pack creation and code abstraction is completed.
