### ISSUE TITLE
Overridemirror: true not working 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#197]
I guess you understood, but it’s been a while that I kept having problems with overridemirror, lately while working with police vehicles and all those little leds parts around grills and windows, in the json of the car I made those leds overridemirror, in the game it just doesn’t change anything, like if there was no overridemirror lines… and the json line itself shouldn’t be wrong.
Help

**Comment by DonBruce64** [comment]
Duplicate of #191.  Closing.

**Comment by DonBruce64** [comment]
Actually, this is an invalid ticket, not a duplicate.  User was un-aware of how overrideMirror functioned.
