### ISSUE TITLE
Light emitting decors

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#198]
Pretty self explanatory, but I’ll add a few details:
Adding MTS light system to those decors would be a good idea, but normal minecraft light emitting from decors would be even better, and probably more easy as it doesn’t request any orientation nor angle.

**Comment by DonBruce64** [comment]
Decor already allows for you to allow it to light up using MC's lighting system.  No code work for me!
https://github.com/DonBruce64/MinecraftTransportSimulator/blob/master/main/java/minecrafttransportsimulator/dataclasses/PackDecorObject.java
