### ISSUE TITLE
Incompatible with OCGlasses

### ISSUE THREAD

**Issue by nrllewellyn** [DonBruce64/MinecraftTransportSimulator#199]
**Describe the bug**
Installing OCGlasses prevents Immersive Vehicles' controls screen form displaying.

**To Reproduce**
1. Install OpenCompuiters, OCGlasses, and Immersive Vehicles
2. Try to open the Open Vehicles controls screen

**Minecraft:**
 - OpenGlasses-MC1.12.2-2.2-36
- OpenComputers-MC1.12.2-1.7.4.153
- Immersive+Vehicles-1.12.2-15.3.0
 - Minecraft 1.12
 - Forge 14.23.5.2847

**Comment by nrllewellyn** [comment]
Issue in OCGlasses' Github: https://github.com/StarChasers/OCGlasses/issues/77

**Comment by nrllewellyn** [comment]
Note: This appears to be an issue with the way one of the mods does keybindings, as with both mods installed the keybinding for Immersive Vehicles controls is labeled as "Glasses Config" in the controls menu.

**Comment by nrllewellyn** [comment]
![2019-10-13_02 43 27](https://user-images.githubusercontent.com/4811061/66711941-49f74d80-ed63-11e9-8961-e32fecc18e3f.png)

**Comment by nrllewellyn** [comment]
Without OCGlasses installed:
![2019-10-13_02 45 08](https://user-images.githubusercontent.com/4811061/66711959-8dea5280-ed63-11e9-8394-a8c98aa086c9.png)

**Comment by DonBruce64** [comment]
Yup, that's a bug for sure.  Will let the other mod's author know and will fix when I get a chance.

**Comment by DonBruce64** [comment]
Fixed in V15.4.0.
