### ISSUE TITLE
Request: Configurable car griefing for RP servers

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#2]
I would like to request the ability to grief others' (or our own) cars.
Potatoes up tail pipes, keyed phrases into paint (or creeper faces), ping pong balls in gas tanks, and the ability to break into somebody's car and hotwire it (using XP? Shears?)

This would be configurable server-side with a carGriefing boolean, allowing server owners and players to decide if their cars can be broken into and griefed. It would add realism to servers that aim to complete a city or hardcore experience.

Thanks for reading!

**Comment by Nianor** [comment]
I mean, you can already steal wheels...

**Comment by DonBruce64** [comment]
Not on owned vehicles.  If you can, that's a bug and needs to be reported.

**Comment by DonBruce64** [comment]
After a long bit of thought, I don't see this ever being implemented by me.  The spray-paint can be done though custom parts easy enough, and trying to implement something like that from the core mod side would require some sort of compliance from pack authors that we're not likely to get.  Not to mention the ways of damaging vehicles can already be accomplished through some crafty TNT or lava work.

No, if anyone wants this, they can submit a pull request, as it's too much work for me to go after for such a specific feature.
