### ISSUE TITLE
Have a 'mirror' function for vehicle parts

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#20]
Similar to overrideMirror, but instead allows parts to be manually mirrored. This would be nice for parts like dually wheels on semi trucks.

**Comment by fsendventd** [comment]
Is that what this did?
https://github.com/DonBruce64/MinecraftTransportSimulator/commit/b4617a8b81a6392c263b224e273ed4a38f5a2008

**Comment by DonBruce64** [comment]
Yes.  I didn't close the issue as the version with this fix has not been released yet.

**Comment by DonBruce64** [comment]
Added in Commit b4617a8b81a6392c263b224e273ed4a38f5a2008.
