### ISSUE TITLE
Request: Afterburning jet engines

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#201]
What it says on the tin. This could increase the fuel consumption significantly (perhaps by a value set in the JSON) to also increase the thrust. It wouldn't put out as much power per mB/t as the engine itself (assume zero bypass ratio, afterburners are essentially ramjets), but it would be more efficient at higher speeds (again, afterburners are essentially ramjets). Perhaps this could be accompanied by a flame texture that's rendered, facing the back of the plane, at a specific point in the engine JSON.

**Comment by DonBruce64** [comment]
If we ever get a jet-fighting community, sure.  But now?  Not a chance.  FAR too much code to be done on engines and rendering to get this to work given its a feature none of the mod's users have a use for.
