### ISSUE TITLE
upload correct project structure

### ISSUE THREAD

**Issue by SirWindfield** [DonBruce64/MinecraftTransportSimulator#202]
Contributing is quite hard as you only uploaded the source code without the proper project structure. `main` should reside within a `src` folder. Your git repository is basically one folder to deep. It should be in the parent folder of your source folder. Your build script even indicates that you actually use the right folder structure (`cd src`) but didn't push it properly to git.

**Comment by DonBruce64** [comment]
Wait, how does the project structure affect contributing?  All you'd need to do is go into the src folder and clone the repo and you're good to go.  Also means you don't have all the git bits clogging up your workspace.

**Comment by SirWindfield** [comment]
Well, if you see it that way, it would work, yes. But I think (and many more) that a repo should be clonable and allow work without having to do anything else. I would have to setup a new workspace by downloading a version from forge.

The way you do it means that people might work on different versions of forge, forgegradle, and libraries. It might not be a problem now but tracking down bugs that are basically not 100% reproducable because people don't have the exact same copy of the workspace.

All projects add build files and stuff like that to the repo to make the repo self contained and allow people to directly start working on it.

It's just good practice (especially gradle and Java) to upload the parent directory of src instead of the content of src only.

In the end, it's up to you. But I think that it is, in fact, bad practice and should be avoided.

Not sure what you mean by git bits, but they are still there (if you mean the dotgit folder).

You don't need to push the run folder that contains your minecraft instance used to test the mod. But all gradle files, the src folder and any other configuration file should be pushed respectively.

**Comment by SirWindfield** [comment]
For example, buildcraft, one of the most used and biggest mods out there, does it as I stated above

https://github.com/BuildCraft/BuildCraft

**Comment by DonBruce64** [comment]
Ended up doing this as I'm trying to include custom libraries, and those need to be noted in the gradle files.
