### ISSUE TITLE
Wrong part hitboxes

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#204]
We talked about this earlier but I'll just put this here to make sure its in line.
To re-state the problem, according to you the seats and crates shouldn't have collision boxes, which they currently do.

**Comment by DonBruce64** [comment]
Will attempt to fix in the next release.  May or may not be possible depending on how MC does collision.  I think there's a rule about how you can't interact with entities that don't have hitboxes, but I *think* there's something to allow you to interact with them, but not collide with them.  Will have to check.

**Comment by DonBruce64** [comment]
Implemented in V15.5.0.
