### ISSUE TITLE
Easier Navigation in Sign Panel

### ISSUE THREAD

**Issue by TrafficAhead** [DonBruce64/MinecraftTransportSimulator#206]
I honestly feel like navigating through the sign block is a bit time-consuming. Some signs that are important wind up at the end of the selections, and if you make large signs this might take up to more than 10 minutes. I have a proposed idea on how to possibly have that improved.

When you select one of the boxes, it can still bring up the current menu you see in the latest versions to type at your discretion.

![Annotation 2019-10-25 161453](https://user-images.githubusercontent.com/39660964/67601628-d5e57e00-f742-11e9-9615-096573a93958.png)

Replacing the gray boxes would be textures of signs. There would also be a scroll bar on the side to scroll through the selection of signs.

**Comment by DonBruce64** [comment]
This is not a bad idea.  Will attempt to put it into a future release.

**Comment by DonBruce64** [comment]
Implemented scrolling sign GUI in V15.6.0.  Should make sign navigation *significantly* less painful.  Won't be doing the new GUI as I need the current one with the text box ability for things like speed limit and route signs.
