### ISSUE TITLE
Some things about the puter

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#207]
The puter used for crafting custom items is currently not functioning. If you press the craft button (green light), it will kick you out the UI and play sound, but doesn't give you the item nor consume the materials. Please unbork it in the next update.

Also some suggestions:
1. Make it not kick you out the UI when crafting. Some items needs to be mass crafted like the iron plates and having to open the UI constantly might be annoying.
2. Make a similar variant system like the vehicles. But unlike vehicles, they are grouped not by json but name. Lets say we have some paint buckets- red, blue, and green. Having them scattered in the selecting menu would be a mess. If we can group them by naming them “paint_(color)“ and they go in the same group, you just need to select them like the vehicle variants that would be great.

**Comment by DonBruce64** [comment]
I'll address the un-borking with this ticket.  Cannot promise the other two features.

**Comment by DonBruce64** [comment]
Fixed issue, and implemented item 1 in V15.6.0.  Won't be doing item 2.
