### ISSUE TITLE
Keys become invalid after picking up and replacing vehicle with wrench.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#208]
This might be a tad bit annoying when you have to move your locked car, and suddenly you can't unlock it anymore because the vehicle's ID changes when you place the car down again, meaning the key thinks it's another vehicle and it won't let you use the key on that vehicle.

**Comment by DonBruce64** [comment]
While I can see this as an issue in this case, how would such a thing work with vehicles dispensed via mod shops?  You'd essentially be selling keyed-alike vehicles, which is great for cop cars, but not so great for your privately-owned pickup truck...

**Comment by boot2big** [comment]
Good point, although could there be a feature to unbind a key from a car, while keeping the owner of the car saved?
(So that you could rebind it, and so that when you unbind it, nobody can run up to the car and claim it as their own

**Comment by DonBruce64** [comment]
But how is that different than making a new key?

**Comment by boot2big** [comment]
A little bit, because you aren't crafting a new key and being left with a useless one

**Comment by DonBruce64** [comment]
That's a fair point.  Would it work then to allow resetting the key's vehicle if you were to put it back in the crafting table?  That way you'd still be the owner of the vehicle you placed back down, and your keys wouldn't be useless as you could reset them.  It wouldn't break shops either, as the vehicles they dispense would be un-owned and even if they were keyed when placed in the shop the key wouldn't work with the dispensed vehicles.

**Comment by boot2big** [comment]
Yeah, that'd work pretty well.

**Comment by DonBruce64** [comment]
Implemented in V15.6.0.
