### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#21]
You already have doors rotate through an angle. So, animations could simply rotate along the angle. You could introduce two new variables, "animationStart" and "animationDuration". Both default to zero (making the animation identical to how it is), but the start and duration can allow for complex movements for parts like landing gear, and even convertibles.

Along this grain, the ability to have custom-defined animations would make landing gear much easier. It could correspond to a custom-defined control button (like magneto or nav lights)

Further, the ability to have wheels or other parts move with animations would be nice as well.

**Comment by DonBruce64** [comment]
This is indeed something I want to do.  However, it is very complex and will take a while, so it gets lower priority than new vehicles or other pack content.

**Comment by DrprofLuigi** [comment]
If you added translations, this could be a very powerful system. Users could custom-code animations (even advanced ones if you include delays and multiple rotations) for anything from LAMBO doors to convertibles, even complex landing gear.

For maximum expandability, custom animations that go beyond the typical 'engine' or 'gearshift' could be linked to buttons on the dashboard much like plane lights.

Finally, some animations like gearshift could have variables (such as current gear) for things like H-patter shifters.

Why make a bajillion animations? Make the users do it!

**Comment by TheCactus27** [comment]
I also presume something like smoker and regular windows would be openable too?

**Comment by DonBruce64** [comment]
No.  Opening windows are outside the scope of this change, and will likely never be implemented due to the complexity of animating them.  Besides, if you want your windows open you can just break them!

**Comment by fsendventd** [comment]
We couldn't just add a window translation variable that moves when a key is pressed? Windows can move, we do it all the time with our doors.

**Comment by DonBruce64** [comment]
No.  No more keybinds.  We already have enough in the mod that I get complaints from users that they run out of space on the keyboard.

**Comment by fsendventd** [comment]
I haven't seen any of those, got an example? Also, in that case, could we eventually implement a panel-like system for cars?

**Comment by DonBruce64** [comment]
Mainly chatting with users on servers and other areas.  If I have 20+ keybinds, that's too many.  Panel systems are possible for cars for sure, but would take a bit of time to get implemented.

**Comment by TrafficAhead** [comment]
Animated landing gear is possible. The parking brake already sets an animated opening door, so this could have similar characteristics to the landing gear.

**Comment by DonBruce64** [comment]
Moving a part of the model is easy.  Moving a part itself?  Not so much.  They follow different rules.  Not to mention all the animation is done client-side, so if you tried to to land the plane you'd end up with the wheels in the air because the server still thinks they are down.

**Comment by TrafficAhead** [comment]
Reasonable. I can see why now. Take your time.

**Comment by DrprofLuigi** [comment]
The option of custom-defined animations is closer with the new HUD system. People could define their own buttons and where they're placed (possibly even the buttons that exist).

**Comment by DonBruce64** [comment]
Well, after about two years I can FINALLY close this ticket with the release of V19.  You get duration/delay, custom variables, custom switches, and moving parts.  Goodbye 21!
