### ISSUE TITLE
modelName for decors

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#210]
I have a bunch of cargo container and paint decorations that share models. It would be nice to be able to use "modelName" : "unuparts_decor_unu_container" for decors like you can for parts.

Bonus points if you can add a definitions section for parts and decors!

**Comment by DonBruce64** [comment]
Will do the former when I get the block changes done in V16.  Good time to suggest this!

**Comment by DonBruce64** [comment]
Implemented in V15.6.0.
