### ISSUE TITLE
[Suggestion] Trailer popup

### ISSUE THREAD

**Issue by slava110** [DonBruce64/MinecraftTransportSimulator#212]
Add something like a popup message when you can attach the trailer (maybe like in Farming Simulator: message in the bottom of the screen).
![изображение](https://user-images.githubusercontent.com/26705162/68529331-a3c14800-030e-11ea-8823-786148d97931.png)

**Comment by DonBruce64** [comment]
Adding a pop-up will be rather hard, as there's not a good way to do overlays in MC.  That being said, I should at least see about making something to let you know that you're pressing the hookup button from too far away.  Will ponder.

**Comment by DonBruce64** [comment]
Implemented in V15.6.0.
