### ISSUE TITLE
[Suggestion] [API] Add API for modders

### ISSUE THREAD

**Issue by slava110** [DonBruce64/MinecraftTransportSimulator#215]
An API to add new vehicle types, part types with custom functionality. Like a part that will collect wheat (part of a combiner). Maybe keybinds too if it's possible.
And also maybe basic API to get part inventory etc

**Comment by DonBruce64** [comment]
It's not an API that needs to be added for new parts.  It's being able to register them at the start of the game.  Once V16.0.0 is done you should be able to create a new sub-class of APart and send it to the PackLoader and have it registered.  My goal is to abstract all the systems to not use static lists and instead use classes that can be created either from MTS code or other mods.  Was a common request from @DrprofLuigi so he should be glad to see this one come into being.

**Comment by DonBruce64** [comment]
So, V16 may not be forthcoming, and when it is, it'll likely look way different.  I'm going to close this issue, however in leiu of an API I'll point you to #154, as that ticket is essentially for heavy machinery, which will likely be implemented in the V15 system before V16 ever comes out.  Of course, that's pending models that can use such things, but that's another matter entirely.
