### ISSUE TITLE
Reloading the sound engine using RandomTweaks's keybind causes a crash

### ISSUE THREAD

**Issue by floral-qua-floral** [DonBruce64/MinecraftTransportSimulator#216]
Pressing [RandomTweaks](https://www.curseforge.com/minecraft/mc-mods/randomtweaks)'s "Reload Sounds" button causes a client crash. My crash report is [here.](https://paste.dimdev.org/loqewiwivu.mccrash)

This is a _very_ heavily modded environment. If requested, I can try and isolate the problem to see if it still occurs with only these two mods, and if it does not occur in an isolated environment I can try to find out which of my mods is causing a conflict. Since I don't have time to do that tonight, though, I figured I'd just drop the report here, both so that I won't forget about this later & also just on the off-chance this report might be useable even in the big pack environment. Let me know if it's not, and I'll get around to making a cleaner report as soon as I'm able. 👍

**Comment by boot2big** [comment]
I'm pretty sure this is due to the fact that MTS uses its own custom sound system, iirc

**Comment by DonBruce64** [comment]
Yup, but that still shouldn't cause a crash.  Best I can tell, the system is faulting for something being null.    I'll have to tweak the code to catch and detect what it's doing there; the current crash debug info isn't enough for me to tell what's happening.  Will have to get back with you on this one.

**Comment by boot2big** [comment]
This also occurs with another mod called Sound Reloader, which does the same thing.
However, it doesn't crash if you spawn into a world where no vehicles are loaded in the chunks you're in, reload the sound system, and then go into a chunk with a car or spawn a car near you.

**Comment by DonBruce64** [comment]
That makes sense, as that crash comes from trying to play a vehicle sound.  So if you don't have any vehicles present, there are no sounds to play.

**Comment by DonBruce64** [comment]
Can confirm this happens.  Cause appears to be due to the fact that when SoundLoadEvent is called and I get the event, the SoundSystem isn't ready to be used yet.  Might be due to me, or might be due to RandomTweaks not having it ready when the event is called.  Either way, I can fix.

**Comment by DonBruce64** [comment]
Fixed in V15.7.0.
