### ISSUE TITLE
[BUG] Keys can't lock the car from inside anymore.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#217]
I'm not sure if I'm doing it wrong, or if this was never even a feature, but I recall being able to hop into a car with a paired key, and right clicking the air while in the driver's seat to lock the car while inside.

**Comment by DonBruce64** [comment]
Yup, that's a bug.  I accidentally removed that feature when I was cleaning the code for V15.0.0.  Was wondering when someone would notice!  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V15.6.0.
