### ISSUE TITLE
Vehicle camera movement

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#218]
Not sure if it's a bug or impossible to implement, but the camera tends to get confusing when sitting in a pitching or rolling vehicle.
When looking forward,the camera will roll and pitch with the vehicle just right, but it's a different story when looking sideways. It neither pitches nor rolls with the vehicle and doing it at extreme angles will totally confuse the camera (or at least be confusing to control).
I assume its doable since the rolling is already abusing the camera gimbal lock, but is it possible to push it a bit further?

**Comment by DonBruce64** [comment]
It's possible for sure.  The main issue is that while pitch in a vehicle does imply pitch in the camera when facing forwards, it's actually roll that needs to be changed when looking sideways.  Sounds like some trigonometry, which I'm not the best at.  Expect this to be lower on the priority list than some of the other enhancements.

**Comment by DonBruce64** [comment]
Fixed in V15.6.0.
