### ISSUE TITLE
Joystick Axes imput doesn't work

### ISSUE THREAD

**Issue by Liquid-Banana** [DonBruce64/MinecraftTransportSimulator#221]
When i'm in the control screen of the mod, the mod seams to recognize my joystick just fine. The red state indicator of the x and y axes are working perfectly. But when i bind the axes to pitch and yaw and i close the screen. The planes and cars are completely ignoring the bonded pitch and yaw imputes from the joysticks and keyboard.

**Comment by Liquid-Banana** [comment]
In Addition:
My joystick is a "Thrustmaster F.16000M FCS"
I first tried it with mod version 15.5.0
i also tried it with mod version 14.2.0 (because this was the last time that there was a update for the joystick)
I had no other mods installed

**Comment by DonBruce64** [comment]
Odd, got a picture of you in a car with the control screen up and the joystick button pressed?

**Comment by Liquid-Banana** [comment]
Sure
![20191202_123846](https://user-images.githubusercontent.com/52746821/69956586-b3dcd980-1500-11ea-8051-eae7f1d27c56.jpg)

**Comment by Liquid-Banana** [comment]
![20191202_123312](https://user-images.githubusercontent.com/52746821/69956623-c2c38c00-1500-11ea-820e-3038c2f79a42.jpg)
And here is also a picture with me moving the joystick

**Comment by DonBruce64** [comment]
Okay, that's good.  Shows it's mapping correctly.  You wouldn't be able to post your log, would you?  Might be something in there I can see.  If not, I'll have to do some deeper debugging and digging.  For all intents, if the thing is mapped, it *should* work as-is...

**Comment by Liquid-Banana** [comment]
Oke i found out that is was a user error
Didnt noticed that i had to move the joystick to set its max positions
Sorry for wasting your time :)

**Comment by DonBruce64** [comment]
No worries.  Glad you got it resolved!
