### ISSUE TITLE
Generate new fuel types from packs

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#222]
Some packs like UNU and Trin would like to have new special fuel types for our engines (hydrogen, electric, nuclear…) but it might overload the config and require a core mod update if ever we want to modify those fuel systems at the moment, that’s why it would be great to automatically update the MTS fuel config by adding a MTS pack (maybe by some kind of jsons?)

**Comment by DonBruce64** [comment]
But, you can already add different fuels.  Once you add them they'll be available in the config for modifying.  Seeing as how I still have yet to get any response on the issue of other liquids for other default fuels, I'm hesitant to mess with fuel even further.

**Comment by TheOddlySeagull** [comment]
You got pinged on discord with a list of potential redstone related liquids, but it so hard to find, it’s said nowhere

**Comment by DonBruce64** [comment]
Implemented in V15.7.0.  Use fuelType of "redstone".
