### ISSUE TITLE
Jerrycans should not be stackable (at least when trying to fill them)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#223]
When filling an entire stack of jerrycans (64), it requires the same amount of fuel as filling one single can, meaning you can get up to 64x the amount of fuel simply by stacking jerrycans and then right clicking the fuel pump with a stack.

**Comment by DonBruce64** [comment]
Yup, that's a bug for sure.  Will have to fix.

**Comment by DonBruce64** [comment]
Fixed in V15.6.0.
