### ISSUE TITLE
Boat issues

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#224]
So, I have a few issues with boats, first, the engine seems to not move the boat that much (I might make it more powerful, it might fix it but still) but there is a bigger issue: you told me that boats would steer by default without needing any ground device nor anything, but when I try to steer, even on a large distance, it will not turn, sometimes it will slightly drift on the side, but so slightly and random (not due to steering)

**Comment by DonBruce64** [comment]
Throw a pack my way and I'll get it sussed.

**Comment by DonBruce64** [comment]
Fixed boat physics to not be horridly broken in V15.7.0.
