### ISSUE TITLE
Mod compatibility farming vehicles 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#227]
Hey! I’ve seen that MTS is turning into Farming Simulator, and that’s amazing, tho here is a few mods I would like MTS to be compatible with:
Growthcraft: adds grapes, it would be great if MTS would be able to harvest those specific grapes, I plan on modeling those grape harvesting farm vehicles, it would be ashamed if it wasn’t compatible :(
Pam’s Harvestcraft: I expect all the crops to be already compatible, but there is also the fruit trees, that drop the fruits when right clicking the grown version of fruit blocks, that would be a great addition if vehicles could do that. Same deal for Forestry trees.
Also, last but not least:
Make the tilting/harvesting/bonemealing independant parts, so you can customize your tractor :)

**Comment by DonBruce64** [comment]
You do realize that you've just submitted two tickets for a total of 7 new features, all while I'm trying to get old tickets closed and put in features nobody has even made a model for yet, don't you?  Expect my reception here to be rather cool...

Anyways, to your items:
Growthcraft: I cannot say whether or not the grapes will be compatible with current or planned MTS systems.  All depends if they are a regular plant or are some fancy custom block.  Will have to see.
Pams: I don't see why Pams wouldn't be compatible.  They have plants just like Vanilla, and if they implement IPlantable that's in Forge for plants like they should, then they should work out-of-the-box.  Trees, on the other hand, are blocks the player has to click.  Kinda hard to make an auto-clicker out of a vehicle, especially one that won't crash the game when it clicks on things that aren't expecting it.  No support for that, I'm afraid.
Parts: The plow, planter, and harvester I'm working on are parts.  Makes it easier to segment the code, and makes swapping rear-ends on tractors far simpler.

Marking this as wontdo as there's nothing really in here that I'm planning on doing differently or changing.
