### ISSUE TITLE
Land interactions ideas

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#228]
Now if ever you plan on going further with map interaction, here are a few suggestions:
- new type of hitboxes that will break blocks without damaging the vehicle(for bulldozers)
- very very heavy vehicles should stamp farmland (turn it into dirt, and why not turn grass into grass paths)
- Hydrator vehicles: they will hydrate farmlands that will not dry as soon as vanilla ones
- Make lawnmowing possible (it will break tall grass and flowers.)

**Comment by DonBruce64** [comment]
1) Hitboxes already don't damage vehicles.  Have you not seen my YouTube video of driving the firetruck into the trees?
2) Possible, but that would mean a lot of code for not much of an effect.   I can see about adding path-making parts, however.  That's for later on in the cycle, though.
3) Impossible.  The hydration of farmland is directly related to the block itself and MC's random update system.  I'd have to replace the default farmland with custom farmland, or do ASM hackery like AppleCore does.  Both are very bad things to do for a vehicle mod that wants to not break things.
4) That's quite possible, planned, and will be what I do to close this ticket.

**Comment by DonBruce64** [comment]
Added lawnmowing support in V15.7.0.
