### ISSUE TITLE
'inheritProperties' for Trailers

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#229]
It would be nice to add an 'inheritProperties' argument for vehicle jsons.

Basically, if a vehicle had "inheritProperties" : true, then if it is towed, any rotations or lights applied to the towing vehicle, are applied to the towed vehicle.

**Comment by DonBruce64** [comment]
I can imagine what you'd use this for, but mind giving me a few use-case situations so I can make sure I'm thinking along the same lines?

**Comment by DonBruce64** [comment]
Implemented in V15.8.0.
