### ISSUE TITLE
Request: Configurable Speed For Players Standing On Hitboxes

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#23]
What it says on the tin.
I wanna be able to have Just Cause Shenanigans if it seems appropriate to me.
![image](https://user-images.githubusercontent.com/11527859/47128529-2df7c380-d257-11e8-875b-cafa3d8fe1e8.png)

**Comment by DonBruce64** [comment]
Added in Commit 78181d86a6dd4cbf58a981e99a275453b37d12be.
