### ISSUE TITLE
Traffic lights wont sync with controll box.

### ISSUE THREAD

**Issue by MarcusGuy1108** [DonBruce64/MinecraftTransportSimulator#231]
So traffic lights don't / are really buggy for me. Sometimes, I can get them to sync with the box, but after a world reload, they resume to blinking red again.

Forge versions : 1.12.2-forge1.12.2-14.23.5.2847
MTS Ver : 15.5.0
Packs :
Mts heavy industrial 1.9.1
Unu parts pack 1.12.2-15.5.0-1.5.0-3.0.0
Unu civilian pack 1.12.2-15.5.0-1.5.0-3.0.0
Moonspire met motors 1.10.2-15.5.0-1.5.0-3.0.0
Mts official pack v12
MTS Caterpillar pack v1.1.1
MTS airport pack p1
tim3games European sign pack 1.0.1
IV Trin civil pack 2.2.0
if there is anymore information required or wanted, just say and I'll get them.

**Comment by MarcusGuy1108** [comment]
![mods](https://user-images.githubusercontent.com/43551581/71117758-ab59f380-21ce-11ea-83ec-5c1c2f84e136.PNG)My mods

**Comment by MarcusGuy1108** [comment]
Updating my mods. Didn't know the mod was running an outdated version as Twitch said it was up to date

**Comment by DonBruce64** [comment]
So does this still happen with the updated mods?

**Comment by MarcusGuy1108** [comment]
Yes. Also, sometimes they sync bur after a world reload they blink red again.

**Comment by DonBruce64** [comment]
Odd.  If you try the signal box with only MTS installed, do you have the same issue? I can't seem to re-produce it on my end.

**Comment by MarcusGuy1108** [comment]
I will make sure all my mods are up to date, and also run it with just MTS to test it.

**Comment by DonBruce64** [comment]
Fixed in V15.9.0.
