### ISSUE TITLE
Exploding vehicles on small hit

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#233]
This issue only happens when you disable the « block breaking »
Here’s the issue: when you slowly hit a wall, with block breakage dissabled, then the vehicle will explode, but, if with block breaking enabled, the same crash would just break a dirt block, without damaging the vehicle. I think it would be better with block breakage disabled to just stop the car rather than exploding it, when it should of only broke a dirt block.
I had several issues of car exploding when hitting a leaf wall at 20 kph, whitch is a bit overkill.
At least make in the config the ability to make collisions more or less sensitive

**Comment by DonBruce64** [comment]
Yeah, that does make sense.  Will implement.

**Comment by DonBruce64** [comment]
@TheOddlySeagull I *thought* I fixed this in V15.8.0, but I may not have.  Can you test when you get a chance?

**Comment by DonBruce64** [comment]
Calling this closed due to no response and no further complaints.
