### ISSUE TITLE
Aircraft placed down with fuel already in them do not consume fuel until additional fuel has been provided.

### ISSUE THREAD

**Issue by radostin04** [DonBruce64/MinecraftTransportSimulator#235]
Placing down a premade aircraft with fuel already inside causes the aircraft to not use fuel, until additional fuel has been loaded into the aircraft by fuel pump or jerrycan. Any amount of fuel (even 10mb) will suffice. Once additional fuel has been loaded onto the aircraft, it will start consuming fuel at a normal rate. I have observed this issue with the MC-172, the Vulcanair and the P-11

MTS version: 15.7.0
Installed content packs: MTS Official
Related mods: Immersive petrolium is installed for fuel
Full mod list wlll be provided upon request, since I'm not sure if there is an easy way to export it

**Steps to reproduce:**
1. Build an aircraft and load it with any amount of fuel.
2. Pick up the aircraft using the wrench
3. Place down the aircraft.
4. Start one or both engines. Usage of a fuel flow gauge is recommended to easily see fuel consumption. No matter the throttle setting, number of engines started, or any other variable (to my knowledge), fuel conumtion will be at zero.
5. Load any amount of fuel into the aircraft via fuel pump or jerrycan. As soon as this is done, the aircraft will start consuming fuel at a normal rate. The aircraft will continue consuming fuel normally until it is picked up and placed down again. 

These aircraft have been created in survival. They are using normal survival engines.

Any additional info will be provided on request. Note that I may not see updates here particularly quickly. I can also be reached on Discord (radostin04 in the official server).

**Comment by DonBruce64** [comment]
Yup, that's a problem.  Will check and fix next release.

**Comment by DonBruce64** [comment]
Fixed in V15.8.0.
