### ISSUE TITLE
Popped tire sound effect

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#236]
Do I need to add more?
It would be great, you know that sound that you also have on BeamNG.drive :p

**Comment by DonBruce64** [comment]
You provide me with a sound that won't get me a copyright claim, and I'll put it in.

**Comment by boot2big** [comment]
https://www.dropbox.com/s/o13jgr2do41ayz0/tirepop.ogg?dl=0
How is this for a tire... exploding?

**Comment by DonBruce64** [comment]
Works for me!  Hope you didn't have to blow one out to get that sound.... ;)  Will be in the next release.

**Comment by boot2big** [comment]
Luckily not, although if I did it definitely would've sounded more realistic!

**Comment by DonBruce64** [comment]
Added in V15.9.0.
