### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by ym1025** [DonBruce64/MinecraftTransportSimulator#237]
1.How to connect trailers to tractors?
2.How to Rotate fixed-mount guns?
3.Are there HP system on cars?

**Comment by DonBruce64** [comment]
1. Trailers up to V15.7.0, may be connected by pressing the G (Trailer) key when driving the tractor.  In V15.8.0 this will be changed to a button press on the panel that may be by pressing the U (Panel) key.

2. You cannot rotate fixed-mount guns.  They are fixed, hence the name.

3. Not on the cars themselves, but parts do have HP.  Engines will wear out more and more when hit, wheels will pop, etc.  You don't hurt a car by firing at the door.  You hurt it by firing at the engine, or the person inside of it.
