### ISSUE TITLE
Reverse thrust animation speed

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#239]
Currently it takes 5 seconds, for realism it should be 1. Also better for spoiler animations.

**Comment by DonBruce64** [comment]
Yup.  Will put this change into the next release.

**Comment by SYDoukou** [comment]
Maybe shorten the sound effect too
Its like 3 seconds or something

**Comment by DonBruce64** [comment]
Implemented in V15.9.0.
