### ISSUE TITLE
Duplication Glitch

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#244]
If the server is extremely laggy and you pick up a vehicle with a wrench, it may be duplicated up to four times (Giving you four vehicles from one)

**Comment by DonBruce64** [comment]
If I had to guess, this stems from me not checking if the vehicle has been marked as dead/inactive on the server prior to calling the code to drop an item, leading to the vehicle dropping itself however many times the packet is sent.  Will fix.

**Comment by DonBruce64** [comment]
Should be fixed as of V15.9.1.

**Comment by DonBruce64** [comment]
So it turns out I put the fix in the wrong packet.  Re-opening.

**Comment by DonBruce64** [comment]
Fixed in 15.10.0.

**Comment by DonBruce64** [comment]
Apparently UN-fixed in V19.15.7.

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
