### ISSUE TITLE
[Suggestion] Disable picking up vehicles with the wrench (Besides operators)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#245]
![image](https://user-images.githubusercontent.com/53581325/71754866-1e619c00-2e56-11ea-81ab-ec6fdb305f2c.png)

**Comment by TheOddlySeagull** [comment]
(Even a config option would work)

**Comment by DonBruce64** [comment]
Should OPs be able to bypass this permission?  Should owners of the vehicle be able to wrench their own vehicles.  Should the wrench just not wrench any vehicle whatsoever?  Need more context here to implement this.

**Comment by SYDoukou** [comment]
Whats the point? No longer able to pick up vehicles? *Mr. Crayfish intensifies*

**Comment by DrprofLuigi** [comment]
Just lock yo vehicle so it don't get got

**Comment by boot2big** [comment]
OPs yes, owners no, only for operators (For when vehicles get too stuck/bugged to be moved by a tow truck)

**Comment by TheOddlySeagull** [comment]
My vision of that feature:
A car owner can use the wrench on their own car to change parts and so on, but should not be able to shift wrench their UNUcord and fit it in the inventory between porkchops and a shovel, tho, if being in gamemode 1: you may shift wrench only if you are owner, if you are OP, you may shift wrench any cars regardless of gamemode and so on.

**Comment by DonBruce64** [comment]
That sounds complicated, though not necessarily impossible.  Will consider, but not right now.

**Comment by DonBruce64** [comment]
Implemented in 15.10.0.
