### ISSUE TITLE
Players can hear certain sounds from engines at any distance

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#246]
To replicate, you need another player (if possible) or a car that skids in place for no reason.
Make sure the car remains in a loaded chunk, and have the player hold the starter motor when you're very far away.
Despite being too far to hear the engine running, they will hear the starter motor as well as the engine spinning up/shutting off

**Comment by DonBruce64** [comment]
I have custom code to make the sounds for those things audible further away, but it appears that the code is making the sounds a bit _too_ audible.  Will have to investigate and see what can be done to balance the sound properly.

**Comment by boot2big** [comment]
Radios also seem to do this, not just engines

**Comment by DonBruce64** [comment]
Looks like I have the non-looping sounds to always be loud relative to the player's position, but I always assume that the player is the one causing the sound to exist.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in 15.10.0.
