### ISSUE TITLE
Minecraft crashes while my world is loading and any shaders turned on

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#247]
Attaching my crash reports' files for more information

[crash-2020-01-04_21.35.55-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4021958/crash-2020-01-04_21.35.55-client.txt)
[crash-2020-01-04_21.29.07-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4021961/crash-2020-01-04_21.29.07-client.txt)

Hope you'll help, Starter

**Comment by DonBruce64** [comment]
Will have to look into this.  I have the same report from a few other users.

**Comment by DonBruce64** [comment]
Fixed in 15.10.0.
