### ISSUE TITLE
Noticable delay (Anywhere from half a second to almost a full second) on radio

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#248]
If you start a radio, then hop out and walk away, you'll know what I mean

**Comment by DonBruce64** [comment]
This is due to the sound API I use to play music.  This API allows for more file support than simple one MC has, but as a result is slower to respond to update commands.  Nothing I can do about that except replace the system, and that's basically installing a new radio.  Not gonna happen.
