### ISSUE TITLE
World crash (Description: Ticking Rotating Particle  java.util.ConcurrentModificationException)

### ISSUE THREAD

**Issue by josh-65** [DonBruce64/MinecraftTransportSimulator#249]
It started to happen when using your mod.

Versions:
Minecraft: 1.12.2
Forge: 14.23.5.2847
Mod: 15.9

The packs i got are:
Air-Cooled+Pack+[MTS]+1.10.2-14.0.0-1.0.1
Golden+Airport+Pack+[Immersive-Vehicles]+0.2.1
Iconic+Film+Vehicles+[MTS]+1.10.2-1.5.0-ALPHA
Immersive+Vehicles-1.12.2-15.9.0
IV_Trin_Civil_Pack_(extended)_2.4.0
IV_Trin_Part_Pack_2.7.0
Melvins_Simple_Sign_Pack-Release-0.1.0
Merlyn's+Luxurious+Vehicle+Pack+5.4.6
MTS_Caterpillar_Pack_V1.1.1
MTS_Heavy_Industrial_by_AdamRK_1.9.1
MTS_Official_Pack_V13
MTS_P1_airportpack
RedCliffe+Republic+Vehicles+[MTS]+1.10.2-1.5.0-1.0.2
UNU+Civilian+Vehicles+[MTS]+[IR]+1.12.2-15.5.0-1.5.0-3.0.0
UNU+Military+Vehicles+[MTS]+[IR]+1.12.2-15.5.0-1.5.0-3.0.0
UNU+Parts+Pack+[MTS]+[IR]+1.12.2-15.5.0-1.5.0-3.0.0

logs:
[crash-2020-01-05_13.05.48-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4023411/crash-2020-01-05_13.05.48-client.txt)

**Comment by DonBruce64** [comment]
Perhaps it has, but this is not the fault of my mod as the particle being ticked is not from MTS.  It is:
```
Rotating Particle: ParticleTexLeafColor, Pos (-33.06543562095091,40.0,-28.546716809310283), RGBA (0.5098347,0.26402155,0.059177242,1.0), Age 90
	Particle Type: TERRAIN_TEXTURE
```

The last mod in the stack trace is this one:
```	at buildcraft.builders.BCBuildersEventDist.onGetCollisionBoxesForQuarry(BCBuildersEventDist.java:78)
```
I would get with them about this crash.
