### ISSUE TITLE
Crash when getting near a thread vehicle (from UNU)

### ISSUE THREAD

**Issue by HydrogenC** [DonBruce64/MinecraftTransportSimulator#251]
[crash-2020-01-06_17.50.17-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4025561/crash-2020-01-06_17.50.17-client.txt)
I was approaching my parking area when it crashed, and I can actually infer that the crash is caused by rendering the threads of the vehicles from the crash report.

**Comment by boot2big** [comment]
The tread system was changed recently to allow for automatic tread creation, which iirc broke how treads _were_ rendered/registered, which means Dr_Prof_Luigi is gonna have to update their pack soon (May already be updated, not sure)

**Comment by HydrogenC** [comment]
> The tread system was changed recently to allow for automatic tread creation, which iirc broke how treads _were_ rendered/registered, which means Dr_Prof_Luigi is gonna have to update their pack soon (May already be updated, not sure)

Thanks for replying.

**Comment by DonBruce64** [comment]
This is fixed as of the latest UNU update.  Closing.
