### ISSUE TITLE
Car engine sometimes stuck at starting state

### ISSUE THREAD

**Issue by HydrogenC** [DonBruce64/MinecraftTransportSimulator#253]
Sometimes when I start a car engine, I press on the "START" button, and after I released it, it will think that I'm still pressing it. The engine would be stuck at the starting state, and I am unable to drive the car. 
In older versions, I could fix this by switching off the "PVG" button, but it is removed in the latest release. I tried to press at the "START" button again, but the engine still remained the starting state.

**Comment by boot2big** [comment]
I reproduced this myself, it happens if you close the panel while holding the button (from my testing, may be different for you)
You'll have to remove and replace the engine, sorry...

**Comment by HydrogenC** [comment]
> I reproduced this myself, it happens if you close the panel while holding the button (from my testing, may be different for you)
> You'll have to remove and replace the engine, sorry...

Exactly.

**Comment by DonBruce64** [comment]
I've seen this with planes before, but didn't realize the change to a single-button system for cars would cause this issue.  Will fix.

**Comment by DonBruce64** [comment]
Fixed as of V15.9.1.
