### ISSUE TITLE
Turret/useVehicleTexture related bugs

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#255]
When I use 'useVehicleTexture', it seems to pull the texture from any part placed prior to the turret.

Also, the turret occasionally rotates the long way around, but I don't know why and it doesn't always happen.

Also, it would be nice if the turret automatically returned to zero when someone left the controlling seat.

![2020-01-06_18 08 53](https://user-images.githubusercontent.com/36775575/71862739-ab536200-30af-11ea-8418-c810f1f4cebb.png)
![2020-01-06_15 17 28](https://user-images.githubusercontent.com/36775575/71856157-e6e23200-3097-11ea-9c29-135c848dc1a9.png)
![2020-01-06_18 09 52](https://user-images.githubusercontent.com/36775575/71862784-cd4ce480-30af-11ea-8098-30903d49b3ae.png)

**Comment by DrprofLuigi** [comment]
The rotation bug (where it will sometimes take the long way around to line up with the player view) seems to be affected by the vehicle's heading.

Additionally, the reloading of the ammo is a bit buggy. Pressing fire doesn't seem to reload the ammo every time, so I find I have to hold the fire button for a bit, wait for the ammo to load, then shoot.

A reload animation would be nice. It could rotate 'open' when the ammo is being loaded in, then 'closed' when it's loaded. You could also add an animation that rotates when the gun is ready to fire (or a light, or both!). Feedback would make destroying villages much easier.

**Comment by DonBruce64** [comment]
This is like 7 tickets in one.  Will be treating it as only the first issue of the texture being incorrect for tanks.  Other issues/features should be in their own tickets.

**Comment by DonBruce64** [comment]
Marking the first item of this ticket as fixed as of V15.9.1, and closing the ticket.  If other items are still an issue, please submit additional tickets for them.  Hard to do tickets with 5 items.
