### ISSUE TITLE
[Suggestion] Tow Trucks/Tugs For Planes of IV

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#256]
**Tow trucks are necessary in Immersive Vehicles mod.** 

I had discussed this topic with devs via Discord server. One of the devs gave me a good recommendation - create a post here.

> Again as i said, a github ticket will work better than saying it here
(GAP) Don_Oofed™ at 12:11 Tue 7 January 2020 (UTC+8)

**Comment by StarterCraft** [comment]
I would love to have ability to tow planes while taxiing in the airports. Due to planes' controls' inflexibility, taxiing is an very difficult task. To see, how difficult can the taxiing to the runway process can be, you can visit this short YouTube Video: https://youtu.be/npJFn27x4Ug.

Mini tow trucks/tugs for the planes are the best way to solve this problem. In real life some companies are manufacturing tugs for towing small aircraft like the Vulcanair: https://airtug.com/airtug-aircraft-tugs/. I think that the IV core code must be improved to give possibility to tow planes and tow tugs&trucks need to be added.

**Comment by DonBruce64** [comment]
I can see about adding this compatibility, but I will not be able to assure you that such compatibility will be added by the pack authors that make such equipment.  The OCP for sure doesn't have any vehicles capable of towing planes, so it will be up to other people to make such vehicles.  That being said, if such vehicles are made I will make sure the OCP planes support them.  As such vehicles don't currently exist, this will go on the backburner for now.

**Comment by StarterCraft** [comment]
Can I learn more about this? Does the problem of fixing the issue exist due to a lack of tow tugs' models? I can try to make one, but btw it will be a backburner to me. 🤨

**Comment by DonBruce64** [comment]
Somewhat.  Though mostly it's a use-case issue.  Only one other pack besides the OCP has planes, and most users don't even use planes due to the requirement for a runway and beefy computer to render far enough ahead to see it.  If you were to make such a model, it would be helpful, however I suggest you ask Wolfvanox in the Discord about his, as he had one partially completed last time we spoke.

**Comment by StarterCraft** [comment]
There is an existing Wolfanox's model of a mini tow truck. It's a blocky tabula model, instead of a fancy OBJ model, but the model is OK. There're problems that the model hasn't any ready to use textures for it.

**Comment by DonBruce64** [comment]
Well, most of the OCP vehicles aren't fancy OBJ models, so it'd fit into that pack if it was used.  In fact, Wolfvanox made the Vulcanair and Commanche, so his style is just as much a part of that pack as mine, Limit's, or Cactus's.

**Comment by StarterCraft** [comment]
What shall we do next? There is no a tow truck coupler in the model, so should I make it myself? It is not a very complicated task. Also, would you like to see the model's screenshots and shall I send

**Comment by DonBruce64** [comment]
Pictures/model networking is better left to Discord where things can flow faster.  GitHub is mainly for tracking bugs, not discussing them.

**Comment by StarterCraft** [comment]
OK. So I would try to give you the tow tug's model at Discord, if you want.

**Comment by DonBruce64** [comment]
Yup.  You of course can post it here when it's done like the traffic signal was, but I assure you it won't be right on the first try, and constant iteration is best left to Discord where the community can critique.

**Comment by DonBruce64** [comment]
Added the ability to do this in V18.4.0.  It's up to pack authors to make models and configure them to work with planes.
