### ISSUE TITLE
Rendering Entity Null on other Player in Vechile

### ISSUE THREAD

**Issue by kandivia** [DonBruce64/MinecraftTransportSimulator#26]
On a server, while a player is mounted in a vehicle, if another player walks into render distance of it, they receive a null pointer exception and crashes their client.

**Comment by DonBruce64** [comment]
This is caused by the client not getting the vehicle data from the server before the player starts to render.  There's a delay in Minecraft between the basic entity data, and the supplemental data that MTS sends.  Will patch.

**Comment by DonBruce64** [comment]
Fixed in Commit 3436ec1a4678eed39c85bd1848c6d4362930c796.
