### ISSUE TITLE
[Suggestion] Retractable Gear Functionality for further Aircraft 

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#261]
**Immersive Vehicles Development is continuing, more aircraft is being developed and added, so new features are required.**

Today all the aircraft in IV have fixed gear. For some micro aircraft like OCP MC-172 it is suitable, but it is not so suitable for larger aircraft like OCP Vulcanair and OCP Eclipse 500. It will be great to have an option to retract gear in-flight on these airliners. Gear retractability is not an impossible feature, because gear can be a rotatable part as a rudder, for example, is. 

> having yet another keybind would make the joystick GUI overflow and doesn't add too much to aircraft systems, 
> - @DonBruce64 

I think that it is a way to scale the configuration screen to make it bigger, and this is quite not a problem, I guess.

**Comment by DonBruce64** [comment]
Retractable gear animations are easy.  Getting the hitboxes to move into the fuselage?  Not so much.  I've been wanting to do this for a long time, but just haven't had the ability to due to other code concerns.  Expect this to come eventually when moving parts are a thing, but don't expect it soon.

**Comment by SYDoukou** [comment]
I like how he's putting so much concern in planes yet ignores the existence and ~~significance~~ of GAP. Thanks for making it an actual ticket, as we'll be benefiting from it the most.

**Comment by DrprofLuigi** [comment]
A more robust system is also discussed in #21

**Comment by fsendventd** [comment]
I know I'm _super_ late to this, but I just realized the Vulcanair was mentioned when the real P.68 actually has fixed gear. The only planes in the OCP with RG systems are the Comanche and E500.

**Comment by StarterCraft** [comment]
This is not the thing. Actually, it'll be quite cool to have retractable
gear on the Vulcanair. But the Vulcanair is too small. Although my Volfnox
11 airliner's modeling process is still not started, I hope retractable
gear will be ingame when it will be released.

**Comment by DonBruce64** [comment]
Added in 18.3.0.  Up to pack authors to configure their planes to use this feature, so won't be available immediately.
