### ISSUE TITLE
[Suggestion] Air-Brakes for aircraft

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#262]
## In the post I'll publish my suggestions which are related to Aircraft in IV.
*Any other users can also post their suggestions here.*

**Comment by StarterCraft** [comment]
#### Suggestion: 1. Airbrakes functionality.
   Airbrakes became a necessary feature just after adding the jet-engined aircraft. They can fly much more faster, up to **36 m/s**, so it'll be great to add airbrakes to the aircraft. The keybind can be targeted to the same button as the ground brake is targeted to, and there must be an ability to switch the airbrakes on/off on the U-panel.

**Comment by StarterCraft** [comment]
#### Suggestion: 2. Inflight alarm sounds.

There can be some situations during any flight, which require an emergency alarm sounds, like stall or overspeed. So the alarm sounds are necessary to be integrated into IV.

**Comment by DonBruce64** [comment]
I'm going to stop you right there and take this as an Airbrakes request.  One item per GitHub ticket, please.  On the subject of air-brakes, while I understand planes can go fast, the whole point of flaps is to allow them to go slower.  And if you really need to stop fast, you can just turn on the reverse thrust, which will get you from "really shouldn't be going over two chunks a second" to nothing fast.  MTS, while it does pride itself on aircraft physics, isn't really designed to be a fully-fledged flight sim.  For starters, you can't see far enough to make super-fast jets really viable.  If anything, helicopters are better than jets.  Perhaps if more jets come into the picture I can see about air-brakes, but it's not likely to happen anytime soon.
