### ISSUE TITLE
Functional fishing nets for boats

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#263]
Well… do I have to add anything? A part, put it on a boat, and fishing look will end up in crates! Re-using the normal fishing loot table.

**Comment by DonBruce64** [comment]
Nope!  Not going to touch loot tables with a 10 1/2 foot fishing pole!  Block interaction is as easy as adding 1+1 over messing with MC's loot and fishing systems.
