### ISSUE TITLE
Crosswalk signal model

### ISSUE THREAD

**Issue by InuYasha86000** [DonBruce64/MinecraftTransportSimulator#264]
here's that crosswalk model for you with the modified texture pallets.
[Crossing Signal Attempt.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4057487/Crossing.Signal.Attempt.zip)

**Comment by InuYasha86000** [comment]
[Crossing Signal Attempt.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4074898/Crossing.Signal.Attempt.zip)

added the .json version into that zip

**Comment by DonBruce64** [comment]
Implemented in 15.10.0.
