### ISSUE TITLE
[SUGGESTION] Engine Hours Config

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#266]
If there's a well hidden repair system feel free to tell me I'm an idiot, tell me how and then close this.

Cost increases exponentially, with three cost repair types of light, medium and heavy (if not listed: iron nugget, iron ingot and iron block by default) as well as three factors into the cost. 

These factors are the engine hours, oil/fuel leak or broken starter, and previous repairs

Hours will dictate whether you need two iron nuggets, a bucket of water (if dictated in json) or an iron block.

Oil and fuel leaks can be treated with (if also not listed) an empty bucket, while the starter motor (again if not listed) a redstone block.

Now for previous repairs..
The first couple repairs may need two iron nuggets, but then the next one might need four, then eight, and then two ingots... proceeding to an iron block, where it either keeps doubling if there's no more stages, or more than three could be listed with certain repair numbers before advancing, with the above example by default for engines without this setting. (Especially useful for DPF's IE version of UNU)

Additionally, some players and I agree that 200hrs may be a bit low for engines to stop stalling, so could it be possible to have a a config setting to change the wear rate, or disable engine wear altogether? (Without having to use a creative engine, for fuel consumption)

If neither of these are possible or you don't want these, I understand.

**Comment by DonBruce64** [comment]
Engine repair actually used to exist back in the older versions of MFS, but that only worked when engines were made in the crafting benches.  When we switched to the new benches, we lost the ability to do repair work as the new benches just take materials and make an engine, seat, vehicle, etc.  Heck, the creative engines are a special item that has a flag that's only available in items in the creative menu.  While repairs are not likely to happen, I for sure can add a config factor that will adjust engine hours to be longer or shorter.  That way if you find engines die too soon, you just set the config lower and then make a new engine when you feel the material cost is equal to the usage you got out of the engine.

As to engine leaks/starters, those only happen if the engine is physically damaged, say from arrows, guns, or TNT.  So for most people you won't see such things.

**Comment by boot2big** [comment]
Thank you, I think most of the citizens of Gramados (Multiplayer modpack where one of the main gameplay elements is IV vehicles) would appreciate that

**Comment by DonBruce64** [comment]
Implemented in 15.10.0.

**Comment by boot2big** [comment]
Could engine repairs perhaps be revisited?
Different repair materials for different damages could be used (instead of varying hour repair, one could define the amount of hours an item removes, as well as defining items to repair starters or leaks)

By default nothing would repair the engine as it is right now, but say an iron ingot is defined to "repair" an engine by 4 hours, an iron block by 20 and a redstone block would fix a broken starter, one could click an engine with three ingots to get their plane running enough to get home, or completely repair an engine without having to remove it and be left with a junk engine (when presumably the oil pan could be replaced, a spark plug got unplugged, etc)

**Comment by boot2big** [comment]
I really do hope a proper repair system is considered a-la MFS, because another flaw of using sub-definitions for "overhauled/repaired" engines is that you can only do it once... you can't make easily enterable recursive recipes in MTS (takes an item beforehand, spits out an item that can be crafted to make another one of itself, doesn't require the new infinitely craftable item beforehand)

**Comment by DonBruce64** [comment]
Hrm, I can possibly see this.  Though in all honesty most players seem to blow their vehicles up before they need to repair the engine.  That being said, if you really want it, put in a ticket for it (that's not this one) and I'll queue it up alongside your other feature requests to get to when I'm done doing overhauls in the code.
