### ISSUE TITLE
[Suggestion] Incendiary Boolets/Firefighting "Boolets" 

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#267]
When the bullet hits a block, the bullet ignites a flame in a similar way to a fire charge and light players/entities on fire.
When a firefighting "Bullet" is fired from a cannon, the bullet will damage the player/entities, while also extinguishing fires if the bullet and the fire interact.

**Comment by DonBruce64** [comment]
Can promise the first, and the first half of the second.  Would consider making a water bullet that puts out fires and pushes entities rather than one that damages them.

**Comment by TheCactus27** [comment]
Can the water bullet both push and do slight damage

**Comment by DonBruce64** [comment]
Would prefer not to be able to kill players with water.  Then again, such bullets would be interchangeable with other guns that use actual ammo, so it'd allow for things like firetrucks that fire explosives.  Not sure I want that...

**Comment by SYDoukou** [comment]
Not wanting that.
Id rather have a “sprayer” that fires liquid particles- water or fertilizer. You dont use guns to flower your garden you know

**Comment by TheOddlySeagull** [comment]
The water bullet would be perfect, I mean MTS has several fire trucks…

**Comment by DonBruce64** [comment]
While a sprayer part would visually make sense code-wise a sprayer is just a gun that shoots slow, large "bullets".  Easier to just make them guns and let them use the same code rather than their own unique code.

**Comment by DrprofLuigi** [comment]
It could easily be regulated by the caliber parameter as long as you don't accidentally make your fire hose 12.7mm or anything.

**Comment by DonBruce64** [comment]
Implemented in V18.0.0.
