### ISSUE TITLE
Boat engines die too fast

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#268]
Unlike a car, on a boat, we can’t stop pressing the gas pedal, because seas are flat, terrain less, and has no turn to do, so you need to keep pressing the gas. Sadly, boat engines are like car engines, when you press the gas pedal for more than 40 seconds, the engine will sputter and die, so it will die after like 200 blocks of sea…

**Comment by DonBruce64** [comment]
Guess that's what I get for testing with creative engines.  Will investigate.

**Comment by DonBruce64** [comment]
Fixed in 15.10.0.
