### ISSUE TITLE
Boat anchors 

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#270]
Maybe active with parking brake.
boats are very annoying to park in the way they won’t move (it is possible but long and unreliable) so it would be good to have a system, anchor or rope, able to tie down a boat for it not to move

**Comment by DonBruce64** [comment]
I can see about applying "braking" force when boats have "parking brakes" engaged.  Would be essentially the anchor you want.  Up to you to render the anchor, though.  Best get used to the translation variables!

**Comment by TheOddlySeagull** [comment]
With the front end loader and all its moving hydraulics, trust me, I’m starting to get very good at translation xD
Also, smooth rotations? When will we get smooth translations?

**Comment by DonBruce64** [comment]
Smooth brake translations are already a thing.  They were added in V15.9.1.

**Comment by DonBruce64** [comment]
Implemented in 15.10.0.
