### ISSUE TITLE
can't get in plane

### ISSUE THREAD

**Issue by arit123** [DonBruce64/MinecraftTransportSimulator#271]
i can't even sit down in the pilot seat or fly the plane. I've feuled the plane and i am the owner of it

**Comment by StarterCraft** [comment]
More information is required to investigate this problem. Make some screenshots or a short YouTube video

**Comment by DonBruce64** [comment]
Yup.  Especially helpful would be the MTS version you are using, and if you are using Sponge.

**Comment by DonBruce64** [comment]
Closing as issue was lack of seats in the vehicle.
