### ISSUE TITLE
[Suggestion] Aircraft Navigation System

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#274]
### Hello everyone.

Flights and airline services are very difficult task in IV for now. Mostly the problem is that it is difficult to **approach the runway** good and land on the centerline, because there are no any systems to help. 

Some new pilots who are going to service flights between point A and the other point B can not remember the flight path visually, btw the flight instructor will not help in a flight. This issue is very important due to a risk of crashes on servers.

I would like to ask for some features to fix this problem.

**Comment by DonBruce64** [comment]
I've considered features like this in the past, but every time I do, I've felt that there are other mods that do such things far better.  Those mods are the mapper mods that add waypoints to the world, such as Journeymap.  With those, you would just make two waypoints, one for each end of the runway. You'd then use the waypoints to keep yourself aligned with the runway as you come in.  Alternately, you could use the GPS-like systems those mods contain to visually line yourself up with the runway.  In both cases, what I would do would be nearly identical to those mods, so it's not really worth my time to duplicate their work.

**Comment by StarterCraft** [comment]
The current functionality of these mods is not very big. It can't help to make the approach easier. Or do you know a mod with an aircraft's navigation system functionality?

**Comment by DonBruce64** [comment]
Yes, such mods can help to make approach easier.  If you make multiple waypoints you can simply follow them as a flight path as you would a VOR or ILB.  With the GPS functionality, you have a large map where you can't possibly approach the runway at the wrong angle.  If you're not landing well each time, you're either coming in too fast, or have too short a runway.
