### ISSUE TITLE
[Suggestion] Save Sign NBT Data

### ISSUE THREAD

**Issue by Tim3Game** [DonBruce64/MinecraftTransportSimulator#275]
Hello,
It would be cool, if you added a feature, that when a sign is destroyed, it will retain it's NBT Data, so when it's placed, it will keep the selected sign and text. But add something to know, what sign is selected, for instance a lore with: 
> Pack: Pack Name
> Sign: Sign 57

Or, if it's somewhat possible, render the sign texture in the inventory, so instead of the MTS texture, it would show the texture of the sign.

**Comment by DonBruce64** [comment]
I should be able to make the sign remember what it was, however making it render accordingly will be very difficult as to my knowledge MC doesn't allow for dynamic item texture.  You have to use a JSON and associated texture to get that, which means for every sign you'll need a JSON to get an item.  Clearly not good if you have a pack with lots of them.  Will investigate.

**Comment by DrprofLuigi** [comment]
I think having the sign description change to whatever sign it is would be enough, especially if you had the pack parameter as suggested.

**Comment by DonBruce64** [comment]
Implemented in V18.0.0.  Signs when middle-clicked will save their data for use later.  When destroyed they won't keep this data as they and the pole they're on will both drop as regular items.
