### ISSUE TITLE
Air intake offset

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#276]
The Trin Rodeo has a tuba, so the air intake is like 2 blocks above wheel level, but the car will still drown in a 1 block deep water. So I would like the ability to offset the intake to that tuba so the engine drowns only when the tuba is in water

**Comment by SYDoukou** [comment]
So it isn't determined by engine height?

**Comment by DonBruce64** [comment]
I don't think that's a variable anymore, is it?

**Comment by DonBruce64** [comment]
Implemented in V16.0.0.
