### ISSUE TITLE
[BUG] Cars are able to drive past world border

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#278]
This sounds ridiculous, especially if they're playing normal survival where the border is a ludicrous way away from spawn, and going past it damages the player until they go back or die, but nonetheless cars can still cross the world border.
I don't expect this to be an easy, or even possible fix, seeing as how it may require some changes to the physics engine, as well as questions like "What should happen to a vehicle that attempts to cross the world border?" "What happens if a server admin shrinks the border while there's cars?" or "How do I get my car back? It's up that wall that I can't get to, because I drove through another wall", not to mention this being useless for something besides modpacks with mods that let you travel an insane distance and with some form of protection against the neverending damage, not to mention how players can't interact with much of anything beyond the border anyways.

**Comment by DonBruce64** [comment]
It's possible, but making it so vehicles don't go past a set point is BOUND to have issues with physics systems if I don't add lots of checks.  Given that nobody in their right mind should be building things or moving around the world border, I'm going to leave this issue as it is.  Besides, as you said there are a lot of edge-cases that I'd have to consider that I'd rather not.

**Comment by DonBruce64** [comment]
Addressed in 22.12.0.
