### ISSUE TITLE
Lag when attaching parts

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#28]
I have noticed, when using MTS, the models do not lag at all. But once you add parts (even OCP ones), the FPS drops significantly. For example, with my Eclipse 500 model I've been working on, I can place tens of them with no visible FPS drop. But when I add the parts, any more than three fully equipped aircraft will cause each frame to be visible.

**Comment by fsendventd** [comment]
Thought I would open one anyway so you can remember if you've already fixed it or not. :stuck_out_tongue:

**Comment by DonBruce64** [comment]
I should mention here that we did some testing and found that wheels are far more laggy than seats, even if both the wheel and the seat are the same model.  Conversely, we can use a more-complex wheel model on a seat and a less-complex seat model on a wheel and the wheel will still cause an FPS hit while the seat will not.

**Comment by fsendventd** [comment]
Huh.

**Comment by DonBruce64** [comment]
Fixed in V12 though Commit cc953f215a858a1dba3a32dbcf7a2a3c32fbee12.
