### ISSUE TITLE
Version 15.10.0 might be incompatible with Immersive Engineering fluids

### ISSUE THREAD

**Issue by Perseus27** [DonBruce64/MinecraftTransportSimulator#281]
It seems like version 15.10.0 might have compatibility issues with modded fluids. Whenever I start up an engine fueled by biodiesel or ethanol, the game immediately crashes with a ticking entity error. I could easily reproduce this error on a local server, so I suspect it might have something to do with the engine not correctly reading the fuel type from the new json, but since I didn't take a look at the code yet, I can't tell.
The only vehicles and parts I used were those from the official pack.

**Comment by Perseus27** [comment]
Lava works though, as do the creative engines with no fuel draw.

**Comment by DonBruce64** [comment]
Does sound like it could be a compat issue.  Got a crash report?

**Comment by Perseus27** [comment]
[crash-2020-01-27_20.01.53-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4118952/crash-2020-01-27_20.01.53-client.txt)

Yup, here you go.

**Comment by DonBruce64** [comment]
This is similar to #315.  For both, I added debug information V16.1.0's crash report that should tell you exactly what is wrong.  Will leave this ticket open for a few days and if I don't hear anything else I"ll assume it's fixed.

**Comment by DonBruce64** [comment]
Assuming it's fixed.

**Comment by DonBruce64** [comment]
So it turns out this was NOT fixed, and is related to pack loading order, not other mods. 
 See Commit:305be9f504329310f5ed9e1fcb36bb7b20525e43
