### ISSUE TITLE
Bug with dealing damage to the mobs near the cars

### ISSUE THREAD

**Issue by mrveprb** [DonBruce64/MinecraftTransportSimulator#282]
Describe the bug
Being in close proximity to the car, I can't deal damage to mobs that are far away from it. Accordingly, while away, I can't kill the mob, which spawned close to the car

In which environment did the Bug appear?
Single Player and Dedicated Server

To Reproduce

Create a car and try to deal damage to mobs, being at a distance of 2 blocks from it, and then at a more remote distance.

Minecraft:

Immersive+Vehicles-1.12.2-15.5.0
Minecraft 1.12.2
ModularWarfare-0.2
Forge 14.23.5.2847
several addons to MTS

**Comment by DonBruce64** [comment]
Will look into this.  More than likely it's my custom collision code that's causing problems.

**Comment by DonBruce64** [comment]
Couldn't find initial issues, as was able to hit a mob from all sides.  Asked user for further information to narrow down if it's due to a specific pack's vehicle or a general issue that's perhaps due to a mod conflict.

**Comment by mrveprb** [comment]
https://www.dropbox.com/s/k9or91c5la1vq1y/test.zip?dl=0

**Comment by DonBruce64** [comment]
Watched your video.  Very interesting.  As far as damaging the villagers goes, is it only the modular warfare gun that's preventing damage?  Or is it both the gun and the bow that can't hurt them?  Is the bow more effective?  I ask, because I tried replicating the video with a bow, and was able to hit the villagers pretty much every time.

**Comment by mrveprb** [comment]
I will check it as soon as possible.

**Comment by mrveprb** [comment]
Yes, the bow does damage mobs regardless of distance. I also tested the Flans mod, the result is the same, I can always hit the target.

**Comment by DonBruce64** [comment]
So it's only Modular Warfare guns that have this issue, then?

**Comment by mrveprb** [comment]
No, there was another mod with the same problem. I don't remember its name, though.

**Comment by DonBruce64** [comment]
Well, if you ever do let me know and we can see about re-opening this ticket.  Since bows and guns from multiple mods work, it's likely something that one specific mod does, not something specific to MTS's code.
