### ISSUE TITLE
[Suggestion] Airline Decals for Airliners

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#285]
### This is the third ticket related to "Realistic Aircraft Update". In this ticket I'm gonna tell you about the decoration items.

Currently we already have decals for cars and ground vehicles, (for example the UNU pack's decals), but we don't have any similar functionality for the aircraft. As for use, it will be great to install airline's logo on the tail or on the fuselage.

**Comment by DonBruce64** [comment]
This is already possible.  Just no pack authors have done such a thing.  You'll need to ask them about it.
