### ISSUE TITLE
[BUG] Despite ownership, other players can still add/remove gauges from a car.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#286]
So imagine Player A puts ownership on his car by shift clicking it, and then locks the car.
Player B runs up, and despite all his efforts, his wrench does not remove the tire. He's able to pop it, but not steal it.
He moves onto the engine, seats and all the other little fancy parts, but he's not able to get them off.
Finally, he goes for the gauges... and he's able to take them all out.
Because of Johnny "xdg22" Spaghetti-Stain AKA Player B, Player A must shell out $200 for new gauges, as for some reason it seems that other players are totally able to bypass car security.

**Comment by DonBruce64** [comment]
What nows?  Players are stealerizing?  From mah cars?  I'll git that fixed I will!
In all serious-ness, I really should re-do the interaction code.  It's rather hacky right now and could use a cleaning prior to making it generic.  Will fix.

**Comment by dentesdracula** [comment]
Hello, my problem is identical, players can steal the vehicle, even if it is locked. Players just have to craft a new key, or sneack with the wrench to pick up the vehicle.
Please fix this as soon as possible

THANK YOU FOR THE BEST MOD.

**Comment by DonBruce64** [comment]
Should be fixed in V16.1.0.  If not, let me know.
