### ISSUE TITLE
[Suggestion] New doors opening&closing system

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#287]
#### Current system of doors opening&closing is opening/closing them only when the parking brake's active. That's not great, imagine a taxi car, when it arrives to you and when the driver activates the parking brake, all doors and covers of this car are opening. So, I'd like to suggest an alternative algorhythm of doors' opening&closing process. 

On the U-Panel in some tab (see #284 for further info) there exist some buttons called DoorFrontLeft, DoorFrontRight and so on. In any case, if the user clicks one of the buttons and makes it on, the related door/cover opens. If the user clicks a button related to an open door, the door's closing. 

If nobody is inside the vehicle and the vehicle is locked by individual key, if its owner unlocks the vehicle with his individual key:
_**Cars:**_ the door, what is near the controlling seat, opens;
_**Aircraft:**_ the front right door opens. In any case, the user can close the door using a correct button.

Waiting for your response. I can give yo any further information, if you need.

**Comment by SYDoukou** [comment]
Sorry but you should be aware of, or at least inquire about the existing door discussion. It is already decided, or officially confirmed, that individual doors will be done by clicking the doors hitbox to open them. And that will be after most important updates such as moving hitbox and more rendering or physics enhancements.

**Comment by DonBruce64** [comment]
Yup.  Not going to do doors this way as you'd have to pre-define each door and have gobs of buttons in a panel.  That's for things like GTAV's mod interfaces that let you open and shut each door and hood individually.  I want a more interactive experience.  But core code does indeed come first.
