### ISSUE TITLE
Add in a hood release button [ENHANCEMENT]

### ISSUE THREAD

**Issue by InuYasha86000** [DonBruce64/MinecraftTransportSimulator#288]
I would like to suggest adding a hood release button, all vehicles have hood release latches/buttons so I figure that vehicles should have one for good reason:
1) if you want to swap an engine in a vehicle instead of clicking through the grill randomly.
2) for jumpstarting a vehicle, makes it easier to make the connection.
3) better visual for a broken down vehicle to have the hood up (side of the road or in a repair shop).

**Comment by DonBruce64** [comment]
While I can see this being a thing, I don't want to do a push-button animation system for vehicles.  I'd much rather do a holistic update as defined in #21.  Expect that one to add a feature to open the hood when you click on it, not this ticket.
