### ISSUE TITLE
Component Bench Crash

### ISSUE THREAD

**Issue by shijo123** [DonBruce64/MinecraftTransportSimulator#291]
[crash-2020-02-04_20.21.40-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4155488/crash-2020-02-04_20.21.40-client.txt)

hey,
on the Server the game crashes everytime, when someone tries to open the component bench.
Can anyone help?

**Comment by DonBruce64** [comment]
I see you currently have V12 of the Official Content Pack.  Does this crash go away if you use V13?  I think the issue is that you don't have any packs installed with components, so it's crashing as there's nothing to render.

**Comment by shijo123** [comment]
ah. okay could be. ill try
thx

**Comment by DonBruce64** [comment]
Can confirm this is related to benches without any items in them.

**Comment by DonBruce64** [comment]
Fixed in V16.0.0.
