### ISSUE TITLE
Part lights don’t show up in U menu

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#292]
So, you have a car, that by default has no emergency lights. But, when you add a part that has emergency lights to it, they will not show up in the U panel preventing us from starting the emergency lights.

**Comment by DonBruce64** [comment]
Yup, this sounds like a possible bug.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V16.0.0.
