### ISSUE TITLE
[BUG] You have to hold an item in hand when attempting to switch seats.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#294]
This is a small one, but you need to be holding anything in order to switch seats.

**Comment by DonBruce64** [comment]
See now, I have specific code in place that's supposed to keep that from happening.  What MTS version are you using?

**Comment by boot2big** [comment]
15.9, although iirc it might've been the same for 15.10 as I had tried to test it in my own personal and more updated modpack.

**Comment by DonBruce64** [comment]
Could you update to 15.10.0 and double-check?

**Comment by boot2big** [comment]
Confirmed, issue is still in 15.10.0

**Comment by DonBruce64** [comment]
Yuck.  Guess I got a bug to fix.... AGAIN.

**Comment by DonBruce64** [comment]
So I just checked this on V16.0.0 on a GAP plane and don't have this issue.  Can you double-check this?  If you still have this issue, can you try the same configuration with only MTS installed?  I'm starting to suspect there might be a mod mucking with events that I'm not aware of....

**Comment by boot2big** [comment]
After rechecking, I've noticed that for some reason, holding an item seems to make switching seats easier, as after holding right click for about a second with an empty hand on pretty much the center of the seat it worked, yet with items I had more freedom in the time I could press the button, and where...

**Comment by DonBruce64** [comment]
VERY interesting.  I'll try this on the Scout and see what's going on.  I do know that the switching code checks entity collision if you have an item in-hand, so it may be that my entity collision checks are behaving differently depending on whether or not you have an item in-hand.  This may be a V17.1.0 fix though as I suspect it'll require significant click-check changes.

**Comment by DonBruce64** [comment]
Stupid Don.  This issue ain't fixed!

**Comment by fsendventd** [comment]
I'm still experiencing this on V16.1.1. It does seem that seat separation distance changes how they behave, as I need to hold an item when switching seats in my Leone I've been working on, but it's mostly fine for larger vehicles.

**Comment by DonBruce64** [comment]
This is going on the Backburner until I get a chance to fix the vehicle interaction code.  Right now it's very messy and barely held together to not crash.  Fixing that code will be a significant time sink, and I really don't want to do that right now.

**Comment by DonBruce64** [comment]
Fixed in the interaction overhaul that was done in V17.2.0.
