### ISSUE TITLE
[Suggestion] Altitude, Pitch, Heading and roll hold

### ISSUE THREAD

**Issue by Oracuda** [DonBruce64/MinecraftTransportSimulator#295]
It would be **very** Useful for cruising phases of flight in my opinion, Maybe as some sort of upgrade for the planes.

**Comment by DonBruce64** [comment]
Altitude hold I can see, but how would heading and roll hold be useful?  Planes don't roll if you keep em level...

**Comment by StarterCraft** [comment]
This's kinda what I had suggested in #290 (point 1). Ehhhh... But I support you much, @Oracuda !

@DonBruce64 , the heading hold is useful while a runway approach. It will be **VERY** useful in these cases.

**Comment by fsendventd** [comment]
Altitude hold, or at least a fairly janky version of it, is already mostly possible if you manipulate the trim properly. I do it all the time when speed testing my planes so that the jittering from constantly pitching slightly up and then slightly down doesn't slow them down.

**Comment by DonBruce64** [comment]
What I'm saying is that planes don't turn themselves unless you put in inputs.  So if you're flying at a heading of 0, you will continue at that heading forever because wind doesn't exist in MC.  There's nothing really to *hold* per-se.

**Comment by DonBruce64** [comment]
Will plan on doing this, but expect it to be a while.  Need to get over the instrument, GUI, and vehicle interaction overhaul hills first.

**Comment by DonBruce64** [comment]
So I actually didn't end up doing this.  @DrprofLuigi did it in #378, #379, #380, #381, and #383.  Will be added in the V18.0.0 release.

**Comment by DonBruce64** [comment]
Implemented in V18.0.0.
