### ISSUE TITLE
Issue with "U" menu on GAP pack planes ( Game Crash ) 1.12.2

### ISSUE THREAD

**Issue by marlonpupo24** [DonBruce64/MinecraftTransportSimulator#296]
I have my CRJ ready to taxi for takeoff ; now, when I open the control panel with the "U" key to turn the engines on it works but when I want to close it pressing "U" again the whole game crashes. I tried with the small fan jet engine from UNU parts and it was working better than with the CF34 engines but after turning off an on the engines a couple of times and exciting the control panel the game crashed
but this time it let me turn on and off the engines. On the third try the game crashed. 
Note: Planes from Official Pack are working fine.

<img width="960" alt="2020 02 05-23 17" src="https://user-images.githubusercontent.com/51809422/73906339-8dc11600-4870-11ea-8ca0-2e1eb887a420.png">
<img width="960" alt="2020 02 05-23 17_01" src="https://user-images.githubusercontent.com/51809422/73906343-8f8ad980-4870-11ea-99b4-ba7cbc57c053.png">
<img width="960" alt="2020 02 02-04 53" src="https://user-images.githubusercontent.com/51809422/73906473-01632300-4871-11ea-8d29-a8e0c1b67cf8.png">
<img width="960" alt="2020 02 02-04 54" src="https://user-images.githubusercontent.com/51809422/73906476-02945000-4871-11ea-8f93-2d6d77c25c72.png">

**Comment by fsendventd** [comment]
Can you send the log and GAP jar files? I happen to be the one who made the CF34 and I want to see why that one in particular seems to be causing more problems. Highly suspect it's a missing file in the pack.

**Comment by marlonpupo24** [comment]
Yes Sir, here they are:
I made the GAP pack into a zip. file because it wont let me transfer jar. files.
[crash-2020-02-05_23.13.42-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4166407/crash-2020-02-05_23.13.42-client.txt)
[Golden+Airport+Pack+[Immersive-Vehicles]+0.2.2.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4166434/Golden%2BAirport%2BPack%2B.Immersive-Vehicles.%2B0.2.2.zip)

**Comment by marlonpupo24** [comment]
Sorry, this is the log file. 
[2020-02-05-2.log.gz](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4166530/2020-02-05-2.log.gz)

**Comment by marlonpupo24** [comment]
Also, why does the CRJ shows 3 engine starters on the U menu when the CRJ only has 2 engines?

**Comment by marlonpupo24** [comment]
Not only CF34 , I just tested the small fan engine from UNU parts and it is doing the same thing, the game crashes, however, the standard fan engines from UNU works perfectly fine on the A320.

**Comment by fsendventd** [comment]
The CRJ shows 3 engine starters on the menu even though it's a twin because it also allows for an APU (tiny engine so that the big ones don't need to be run just to generate power) to be placed in the tail. Problem is, GAP has the APU as the first engine in their JSON entries, so the two main engines are the second and third starters instead of the first and second ones. I've just experienced a similar issue myself, when attempting to start a plane without an engine. Game crashed as soon as I clicked "MAG." Try only using the second and third starters to see if that does anything.

**Comment by DonBruce64** [comment]
Had a chance to test this.  Looks like the game crashes if you open the panel and close it without pressing an engine button and there's no engine in the 1st slot.  Will fix.

**Comment by marlonpupo24** [comment]
Yeah exactly. Just opening and closing the panel crashes the game. I tried to exit the panel by pressing "shift" to get out of the plane but it crashes as well.

**Comment by DonBruce64** [comment]
Yeah.  If you press a starter button it should behave when you exit.  You could also put an engine in the middle area for an APU.  Will have this fixed in the next release, so shouldn't be a problem for long.

**Comment by marlonpupo24** [comment]
Oh yeah it works with the APU engine nice. A temporal fix for now. I love what you did with the reverse thrust animation its super realistic, I haven't got a chance to see it because of bug until now.

**Comment by DonBruce64** [comment]
Hey, don't thank me.  Thank the modelers who put that in.  I just provide a number, they provide the animations!

**Comment by marlonpupo24** [comment]
I would like to! How could I contact them? on GAP discord channel?

**Comment by DonBruce64** [comment]
Yup.  He's also on the main MTS channel.  Just look for anyone with GAP in their username.

**Comment by DonBruce64** [comment]
Fixed in V16.0.0.
