### ISSUE TITLE
Request: Size variable for all part types

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#30]
So we can use min and max sizes for custom parts/crates. Mostly useful for insignia that would be too big for an aircraft's wing or fuselage, so you want to prevent insignia of that size of larger from being able to be placed on the aircraft.

**Comment by DonBruce64** [comment]
Insignia should be sized such that the same marking can fit anywhere on the craft, as that's the way most older planes work.  If different sizes exist, it is up to the pack maker to name the appropriately (insignia_small, insignia_large, etc.).  The whole point of custom parts is that their ability to be placed on vehicles is based on their names, not their properties like all other parts.  Adding min-max requirements for a single part is only going to make for more JSON, which for all other custom parts is not needed.  I'm trying to stay away from uber-customization where one vehicle can only get one part.  That's not the design philosophy of MTS...

**Comment by fsendventd** [comment]
Well, the idea is more for newer aircraft that have smaller insignia where larger ones won't fit. Applying the larger one in MTS would look weird. So I don't want people to be able to put a wing-sized insignia on the tail, for example.
