### ISSUE TITLE
Bombs

### ISSUE THREAD

**Issue by gooseapple5** [DonBruce64/MinecraftTransportSimulator#301]
Will there be some sort of droppable bomb or some sort of bomb bay added? It would make adding bombers or other bomb-dropping planes possible to the pack designer.

**Comment by DonBruce64** [comment]
Bombs are already possible.  They are just explosive bullets with a muzzle velocity of 0.  It's just nobody has made a bomber to carry such things.

**Comment by gooseapple5** [comment]
Alright, thanks
