### ISSUE TITLE
[JSON Structure Issue] No any ability to translate vehicles' and parts' names inside of the packs

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#302]
After v16 JSONs structure's update, there are no more .lang files inside of the packs. Either, inside of a vehicle's/part's JSON there's a single name parameter and a single description parameter. This means that Minecraft will show the name from the part's JSON irrespective of the currently selected language of the game. This structure issue must be resolved.

**Comment by DonBruce64** [comment]
Negative.  In the entirety of all the pack makers making packs, nobody has translated the packs into any other language, despite the packs supporting such functionality.  Even the core mod is only translated into three languages, and some of those translations are very old.  It's far better to have the names in the JSON and not have to have a lang file that nobody uses and that changes format in newer MC versions.

**Comment by StarterCraft** [comment]
OCP Pack has a custom Russian translation provided by me, so that's unfair!

**Comment by StarterCraft** [comment]
Please fix! You would make a little fix in the JSON's' structure just for me, because I was planning to translate ALL existing IV packs to Russian! Is it such difficult?

**Comment by DonBruce64** [comment]
I highly doubt you translated the OCP, as the last time I changed that file was back in December of 2018, and you weren't the person who gave it to me according to my commit history.  As to translating other packs: the lang file system makes translation very difficult for creators, and makes for even more files for people to create.  In the future I may re-consider, but not right now.  Certainly given the low amount of downloads.
