### ISSUE TITLE
[Bug] Incompatibility with MTS deco and HWYLA

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#303]
Crash occurs when looking at MTS deco when HWYLA is enabled.
https://cdn.discordapp.com/attachments/672405041574969347/676757955831529473/crash-2020-02-11_02.33.37-client.txt
https://cdn.discordapp.com/attachments/672405041574969347/676758119325630474/crash-2020-02-11_02.33.47-client.txt
https://cdn.discordapp.com/attachments/672405041574969347/676760957997023262/crash-2020-02-11_04.03.30-client.txt

**Comment by DonBruce64** [comment]
Fixed in V16.1.0.
