### ISSUE TITLE
[Bug] OCP Vulcanair is unable to move

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#305]
I had assembled a OCP Vulcanair in my hangar, and I had tried to move it directly from the build position, but I couldn't. I had switched off my parking brake and checked for any collisions with no result.

**Comment by StarterCraft** [comment]
[Watch this short video to get further info about the problem.](https://youtu.be/RzIt261a0A4)

**Comment by DonBruce64** [comment]
Does this work outside of your hangar?

**Comment by StarterCraft** [comment]
Yes. The plane was able to move outside of the hangar. I had thought that

**Comment by DonBruce64** [comment]
Likely this is due to some block in your hangar preventing movement.  If you can back the plane into the hanger, you should be able to find out which block is blocking you.  Either way, this isn't an issue with the mod.

**Comment by StarterCraft** [comment]
I already checked the chance of any collisions, as I already said. The only
blocks I have in my plane building area are the Immersive Engineering steel
scaffolding slabs and the steel block's slabs.

чт, 13 февр. 2020 г., 22:32 DonBruce64 <notifications@github.com>:
