### ISSUE TITLE
can't see gauges

### ISSUE THREAD

**Issue by hacker104** [DonBruce64/MinecraftTransportSimulator#307]
version: Immersive Vehicles-1.12.2-16.0.0
i can't see gauges because the don't have textures

**Comment by hacker104** [comment]
![afbeelding](https://user-images.githubusercontent.com/15986802/74588373-4ff48800-4ffc-11ea-80fc-634788a8d365.png)

**Comment by hacker104** [comment]
![afbeelding](https://user-images.githubusercontent.com/15986802/74588382-63075800-4ffc-11ea-9c6e-cdc7e89927be.png)

![afbeelding](https://user-images.githubusercontent.com/15986802/74588388-6a2e6600-4ffc-11ea-92a6-6e22e6c2c682.png)

**Comment by boot2big** [comment]
This is because V16 recently changed how gauges work.
Download the Official Content Pack and use those for now, until DPL updates his UNU gauges to V16 standards

**Comment by DonBruce64** [comment]
Yup.  I even mentioned this in the most-recent update video.

**Comment by hacker104** [comment]
unu has updated to 3.2.0
