### ISSUE TITLE
Issue with joystick throttle

### ISSUE THREAD

**Issue by slimit75** [DonBruce64/MinecraftTransportSimulator#308]
Good morning/afternoon/night, I am currently experiencing an issue with controlling my throttle in Immersive Vehicles. I have the [Logitech Extreme 3D Pro](https://www.logitechg.com/en-us/products/gamepads/extreme-3d-pro-joystick.html) joystick. Right under the joystick itself is a slider I have set to control my throttle. The only thing I need to do is to invert the throttle through Immersive Vehicles.

On earlier versions of Immersive Vehicles, it works fine with no issue at all.

I am not sure about versions between 15.9.1-15.10.0, but on 16.0.0, I have a slight issue.
Immersive Vehicles sees the slider and it sees its full range of motion (-1.0 to 1.0 in the screen with the invert/normal button). However, idle throttle for me is moving the slider to the center (would be 0.0 in the screen I think). If I bring it all the way down, where it would be idle on older versions, the engine shuts off completely.

I am not sure if this is intentional or not, as it works fine keeping the slider above the middle, but I 
don't think it is as it worked on older versions.

### information that may or may not help
Immersive Vehicles 16.0.0
MTS Official Pack 14
Windows 10 Home (1909)

Im sorry if I don't have enough information, or it isnt an issue at all.

**Comment by DonBruce64** [comment]
I suspect that is indeed a valid issue.  I re-did the config and control system in V15.10.0 and in doing so I had a lot of code changes.  I distinctly remember having to fix the throttles once, and it's quite possible that given my controller only goes from 0.0 to 1.0 I failed to set up the system correct.  Will check and fix.

**Comment by DrprofLuigi** [comment]
On the vein of controllers, I would recommend allowing multiple assignments per analog input.

For example, my xBox 360 controller's analog triggers range from -1 to 0 on one trigger, and 0 to 1 on the other. I tried to set one as brake, and the other as gas, but because they're technically the same 'joystick' it doesn't work. This would also allow the brake to automatically be applied when the gas is released (if the player so desired).

**Comment by DonBruce64** [comment]
"On the vein of controllers, I would recommend allowing multiple assignments per analog input."  Uuuh, not sure what you're assigning, but I just did that and can confirm it does allow you to assign the gas and brake to the same axis.  You running an old version?

**Comment by DonBruce64** [comment]
Fixed in V16.1.0.
