### ISSUE TITLE
Separate Controller Buttons for Engine Starter and Engine Stop

### ISSUE THREAD

**Issue by EmeraldTiger64** [DonBruce64/MinecraftTransportSimulator#31]
Would it be possible to add a config option that can allow people to set different buttons on a controller to the engine starter and engine stop? I just find this to be a neat idea.

Here is a link to an idea of what I am talking about. https://www.youtube.com/watch?v=Dk8GSy6zR_o&t=

**Comment by DonBruce64** [comment]
It wouldn't be a config.  More of an addition of a stop button on the joystick config for cars that can be bound to a key.  The standard mod+start would work in addition to that for people with controllers with fewer buttons, as not everyone has a PS3 number of inputs they can use.
