### ISSUE TITLE
[bug]Defining New Line

### ISSUE THREAD

**Issue by SYDoukou** [DonBruce64/MinecraftTransportSimulator#311]
When not specified, lines will fold up according to the space left.
However, in a specified vehicle definition, it won't fold up unless there's not enough space, and it will fold up as specified rather than by space.
![ezgif-6-682f299b2321](https://user-images.githubusercontent.com/45642968/74890037-c8bd6080-53bd-11ea-8986-16b9e4331e0e.gif)

**Comment by DrprofLuigi** [comment]
In the old description system, you could add in line breaks. I would think there is a way to do that via the json. However, I think it would be best to have the item description and description in the crafting bench be separate json entries.

**Comment by DonBruce64** [comment]
Fixed in V16.1.0.
