### ISSUE TITLE
[Bug?] You can place parts into vehicles you don't own.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#312]
Player A can put his engine into Player B's van, even though Player B owns said van, and Player A shouldn't be able to remove parts.

**Comment by DonBruce64** [comment]
I mean, you can't complain about a free engine can you?

Will fix though.

**Comment by DonBruce64** [comment]
Should be fixed in V16.1.0.  If not, let me know.
