### ISSUE TITLE
[Enhancement] HUD Switches

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#313]
Just a basic idea:

What if you could define the switch position in the vehicle json? There could be default values. If combined with the ability to have custom textures, this could allow HUDs to go from a boring, utilitarian, and overlooked part of MTS, to something that really makes each vehicle seem different!

It would also pave the way for custom buttons for good ol' #21

**Comment by DonBruce64** [comment]
I'm going to hold off on this until I see people actually making custom panels.  (HUDs don't have switches).  Considering that few people have offered to help with the panel texture as-is, I'm not about to make more features on a system that's getting little support in its default format.

That being said, I'll probably have to look into this again when #21 gets implemented, so I'm going to close this ticket with the knowledge that it'll get a second pass when that feature gets added.  Maybe by then the panel designs I'm seeing will warrant the extra work.
