### ISSUE TITLE
Cars Accumulate Run Hours While Not running

### ISSUE THREAD

**Issue by hacker104** [DonBruce64/MinecraftTransportSimulator#314]
the car gets run hours while not running at all
please help?

**Comment by DonBruce64** [comment]
Does the car get hot and smoke too?

**Comment by DonBruce64** [comment]
Had this issue from another user.  Turns out a recent update to Terra Firma Craft is to blame.  See https://github.com/TerraFirmaCraft/TerraFirmaCraft/issues/842

**Comment by hacker104** [comment]
the car does not smoke or gets hot.
the car doen't do anything

**Comment by hacker104** [comment]
only that the hours go up

**Comment by boot2big** [comment]
An additional note to anyone reading up on this is that I've also had this with non-TFC biomes, thought with the exact same reason of ambient temperature. (573c is a bit high...)

**Comment by DonBruce64** [comment]
TFC has fixed this issue in a recent commit.  Whenever their next update drops can one of y'all let me know if this issue goes away?

**Comment by DonBruce64** [comment]
Confirmed closed.  Except in hell, but it's not my problem engines can't run in lava flows!
