### ISSUE TITLE
malformed OBJ causes crash

### ISSUE THREAD

**Issue by FightingPickles** [DonBruce64/MinecraftTransportSimulator#316]
OBJ files with verts/faces not assigned texture coordinates cause IV to crash with little explanation in crash log. Possible solution would be to validate OBJ files on pack load and provide an error message, allowing the game to load so the OBJ can be replaced with a texture pack/dev mode would make debugging new models faster.

**Comment by DonBruce64** [comment]
Will look into ways to make error messages appear for these things.  I want to do this being in devMode or not, as it's up to pack creators to make a good pack before they release it, so you shouldn't have any packs released to the public with errors.

**Comment by DonBruce64** [comment]
Added better debugging crash messages in V17.2.0.
