### ISSUE TITLE
Dev mode data output

### ISSUE THREAD

**Issue by FightingPickles** [DonBruce64/MinecraftTransportSimulator#317]
I would like to request the ability to have data output (like the F3 debug screen in minecraft, but a logfile would do if displaying the text is a lot of work) in dev mode for the forces acting on a vehicle, as well as the variables IV makes available to vehicle/part JSONs. It would make debugging vehicles easier. ie you keep making your vehicle lighter but the engine is outputting 0 thrust for some reason.

**Comment by DonBruce64** [comment]
You wouldn't want to put that stuff into a logfile.  That'd cause you pain given the amount of text that would be in there.  I can see about displaying that in an overlay, however.  Heck, I do that myself when figuring out the functions for forces.  Wouldn't hurt to make it an official feature.

**Comment by DonBruce64** [comment]
Added this as console spam that turns on when devMode is enabled in V18.4.0.
