### ISSUE TITLE
Packs sometimes don't load correctly.

### ISSUE THREAD

**Issue by DonBruce64** [DonBruce64/MinecraftTransportSimulator#32]
Transferred from Curse:

SleepMineFly

Is anyone else experiencing an issue where FML randomly decides that the blocks & items in the content pack are missing? (I'm running MTS as an add-on to FTB Infinity Lite 1.10 so it could well be a conflict with some other mod.)

Every so often (maybe once every 3-5 game starts on average; I can't seem to narrow down a set of conditions to trigger it), I'll get the "Forge Mod Loader detected missing blocks/items" screen, telling me that there are 81 missing blocks & items and listing lots of things like "mtsofficialpack:brigbedbox" etc.

Any "spare" bits (instruments, wheels, etc.) in inventories will, of course, be gone on entering the world but placed vehicles will be fine - until I remove a part or break the entire vehicle. At that point, the part(s) that get dropped into the world and picked up have the black & magenta "missing" texture. On opening my inventory, they are visible with this texture but the game immediately freezes for a few seconds then exits.

The items are visible in the various crafting benches/machines but they don't get their "proper" names - the Blue Comanche airframe, for example, shows as "item.comanche_blue.name" - and attempting to craft one causes the game to hang. Therefore, when I do get the message, it's necessary to exit and restart the game before attempting to craft anything.

**Comment by molletts** [comment]
[EatSleepMineFly here]
I haven't managed to reproduce the issue using MTS v12 & Vehicle Pack v8 yet, despite exiting & reloading the game many times, placing & breaking vehicles, etc.

I'm thinking it might be some kind of race condition. If you want me to try downgrading back to MTS11/VP7 and have a go at reproducing it again, I can do that.

**Comment by DonBruce64** [comment]
Eh, if you don't have the issue with V12 then I'll close the bug.  I changed a few thing in the loader system in the V12 update, so race conditions applicable to V11 may not manifest themselves in V12.  If the bug happens again, feel free to re-open this issue.  For now, based on what you said, I'm closing it.
