### ISSUE TITLE
[SUGGESTION] Minor behavior change for when engines explode

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#320]
Maybe instead of disappearing and having the hood pop open, a different set of actions?
When the explosion goes off, it could have a ton of smoke puff out of the engine bay (where the engine is place) and the engine remain would, but no longer functions and when removed, will not drop anything. (Or maybe it could drop random items that the engine was crafted from, with the chances being set by crashItemDropPercentage)
After several seconds, the smoke should stop and the engine should not be crankable. (The button gets pressed, but nothing will happen since we can assume the engine may have seized or the starter motor simply isn't connecting with the flywheel anymore)

**Comment by DonBruce64** [comment]
But why?  IRL engines can blow themselves if overheated and over-stressed.  And exploding is a generally-accepted method of indicating that you done screwed up when doing something in Minecraft.

**Comment by boot2big** [comment]
They can still explode, they just remain (though useless, like popped tires)

**Comment by DonBruce64** [comment]
And see now, that's my question.  Is there a reason they should remain versus go away?

**Comment by boot2big** [comment]
So that players will know that this car isn't just missing an engine, the engine it has is destroyed.

**Comment by boot2big** [comment]
Additionally, the dropped crafting parts would be helpful, since you could get some scrap metal out of a broken engine block. (Not as much especially if it exploded, but you could get _something_ out of it.)

**Comment by SYDoukou** [comment]
The tires is a good point. Bet you don't ask that much when implementing that?

**Comment by DonBruce64** [comment]
Yeah, negatory on the broken engine model unless you want ALL packs to crash MTS like the tires do. Behavior changes aren't that hard to code, though.

**Comment by boot2big** [comment]
I don't think a broken engine model should be done, since it'd cause the issue above.
However, at least have an indicator that the engine isn't just missing if someone somehow wasn't there, or didn't hear the explosion, as well as giving them a little bit of resources. (Especially for the Trin jets... a whole nether star.)

**Comment by DonBruce64** [comment]
Really, they use that much?  Yeah, I for sure can see about that.  When vehicles crash their parts drop resources, though if you crash a jet full of fuel none of those will survive the explosion.  For an overheated locked-up engine it's not that hard to code the same code, though for wheels folks might want the same thing.  Ah well.  One part at a time I suppose.

**Comment by boot2big** [comment]
Would asking for the hood to pop open after the engine blows be too much? I don't wanna make this too complicated, plus that may add to decorations (I understand if you don't want that though either due to back end code or just not wanting the hood to open)

**Comment by DonBruce64** [comment]
But, the hood already pops open when the engine blows.  Because it blows up, there isn't an engine in the engine bay, and so the hood is open...

**Comment by boot2big** [comment]
True, though most engines don't get completely annihilated when they explode, even if it's a pretty serious explosion you'll still have wreckage to pull out.

**Comment by DonBruce64** [comment]
So, after thinking a lot about this, I've decided I'm going to keep the current code where the engine blows up if you run it too hard, if only due to simplicity and ease of understanding for players.
