### ISSUE TITLE
Request: Daytime running light type

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#323]
Basically it would be on whenever the engine comes on. Could be nice for some accent lighting-type things.

**Comment by DonBruce64** [comment]
Not a bad idea!  I'll add it to the lighting list.

**Comment by DrprofLuigi** [comment]
This would be perfect for cyberpunk vehicles too

**Comment by TheOddlySeagull** [comment]
I absolutely like that idea, that’ll allow me to add cars that actually fit with the cyberpunk gauges I have lol

**Comment by DonBruce64** [comment]
Implemented in V17.1.0.
