### ISSUE TITLE
v16.1 other players can break the wheels

### ISSUE THREAD

**Issue by dentesdracula** [DonBruce64/MinecraftTransportSimulator#324]
Player A buys a vehicle, he locks it, but the other players B C D. . . can break player A wheels .

**Comment by DonBruce64** [comment]
This is actually per-design, as wheel breakage is based on the vehicle damage system which allows anyone to damage vehicles, even if they aren't the owner.  Not to mention IRL there's nothing stopping bandits from slashing your tires.  Mayhaps you need to stop going to the rough part of town?
