### ISSUE TITLE
V16.1 Code issue where wrenching on a vehicle dash to place instruments will crash the game.

### ISSUE THREAD

**Issue by Grrpapa** [DonBruce64/MinecraftTransportSimulator#325]
This happens with MC 1.12.2 and IV 16.1.0.  don_bruce is aware and looking into this to fix.

**Comment by DonBruce64** [comment]
Indeed I am.  This is directly due to the changes made in d7c9400a1b6f85ae0c7d490f27bc8dc022480629 for instrument ownership.

**Comment by DonBruce64** [comment]
Fixed in V16.1.1.
