### ISSUE TITLE
[Suggestion] A different method for boats allowing amphibious vehicles

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#326]
I see two ways to handle amphibious vehicles. One is to add an amphibious type that combines boat and car vehicle types. Another system is a bit more complex but more robust in my opinion:

Remove the boat type and engine_boat. Boats are just cars that have floating hitboxes. If a 'car' has a propellor, then the engine_car acts like an engine_boat in addition to driving wheels. Bonus points if the propellor adds a load to the engine when it's colliding with water. The Prop wouldn't need to rotate on its own, but rather have the rotation coded via the json.

Why do this? In addition to making amphibious vehicles easier from both a json and coding standpoint, it also allows boats to accept regular car engines (like a racing boat that uses a V8 car engine).

What about the boat that currently exists? That boat engine becomes a car engine with the boat customType (so it can't be put anywhere), and the prop becomes its own part. If that prop is set as a 'defaultPart' of the engine, there would be no change in the user experience whatsoever.

Because Trin has the only boat, it's still early enough to improve this system.

![2020-02-23_02 32 00](https://user-images.githubusercontent.com/36775575/75170420-f0bf0380-56de-11ea-935b-5151efdadd64.png)

**Comment by TheOddlySeagull** [comment]
Trin also has an amphibious car remember 
Trin Alligator 
And that since V14 or V13

**Comment by DrprofLuigi** [comment]
I know Trin has an ambitious car, but it doesn't work.

**Comment by SYDoukou** [comment]
Every vehicle should have water physics improved tbh. I want a proper Hudson ditching instead of falling in like nothing is there

**Comment by DrprofLuigi** [comment]
For non-floating vehicles, it _could_ be as simple as reducing gravity if the center is in water ¯\_(ツ)_/¯

**Comment by DonBruce64** [comment]
So..

As to collision, that's hard to do.  I think I have two ground points now for boats and cars, but I'm not entirely sure.  As to the power, car engines use the feedback of the wheels and the speed of the car to define their speeds.  One of the big points of overhauling the HUD code was to allow multiple engines in a single car and to thus allow boat and car engines in one vehicle, so I ain't going to do a 180 now that I'm making dual-engined vehicles like I've been asked.

As to the boat/car bit, I can probably combine them into a single car vehicle.  Would just mean making them turn if a ground device (wheel, etc) or a boat engine is in the water.  Drag is another issue, though I think cars have a drag coefficient?  If not, that's something I need to take into account.

Either way, expect something like this, but not exactly what is proposed.  I'm not going to kill myself messing with ground collisions a third time.

**Comment by DonBruce64** [comment]
All vehicles have been made mostly generic in V17.3.0.  You can put both car and boat engines on a vehicle.  Which you'll want to do, as car engines drown when submerged, but boat engines won't.

Oh, and jet-powered boats are now possible.  Have fun!
