### ISSUE TITLE
Black seat for OCP

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#327]
Put in a ticket so that it was documented.
![seatblack](https://user-images.githubusercontent.com/44233145/75206609-14606900-5734-11ea-9956-fb7d2cc3a2a8.png)

**Comment by DonBruce64** [comment]
Will put this in the next pack update.  I need to make one anyways for the new instrument code in V17.

**Comment by DonBruce64** [comment]
Added in V15 of the OCP.  Thanks!
