### ISSUE TITLE
[Suggestion] Change the maximum value of guns to use barrel lenght instead of caliber

### ISSUE THREAD

**Issue by vinidamiani** [DonBruce64/MinecraftTransportSimulator#330]
This way we won't be able to stick a huge 20mm AA cannon on a biplane. The barrel lenght is more indicative of the actual size of the gun, so it fits better for guns inside a compartment

**Comment by fsendventd** [comment]
Yeah, but why would your biplane be able to accept 20mm guns? Plus we have different types of guns for different things, so you can't stick a turret gun in a slot where a fixed gun is meant to go.

Also, think about this. Some long-barrel 20mm AA guns have much longer barrels than high-caliber howitzers. Would you want a high-caliber howitzer on your 20mm AA station?

**Comment by vinidamiani** [comment]
My 20mm Hispano for the Spitfire fits on the PZL11 gun slots

**Comment by DonBruce64** [comment]
I get that.  Though can you see any time that barrel length might not be the appropriate parameter for guns?  Are there guns that have barrels as long as other guns but are far too OP a caliber for those mounts?

**Comment by vinidamiani** [comment]
True, makes sense. Easier to just define individual guns for mounts

**Comment by DonBruce64** [comment]
I can make it so different gun lengths are different types.  So could be gun_fixed_short, gun_fixed_long, etc.

**Comment by fsendventd** [comment]
@vinidamiani That issue is caused by the P11's maximum gun size being 20 instead of roughly 8. It's a JSON issue. Since nobody else has made guns until now, it hasn't been pointed out.
