### ISSUE TITLE
[Bug] MTS screams at you when you put a part in your own vehicle.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#332]
Whether you own the vehicle or if it's unowned, it'll send you several messages saying it's not yours when you can still put a part on.

**Comment by DonBruce64** [comment]
This is going on the Backburner until I get a chance to fix the vehicle interaction code.  Right now it's very messy and barely held together to not crash.  Fixing that code will be a significant time sink, and I really don't want to do that right now.

**Comment by DonBruce64** [comment]
Fixed in the interaction overhaul that was done in V17.2.0.
