### ISSUE TITLE
[Suggestion] option not break the vehicle wheels

### ISSUE THREAD

**Issue by dentesdracula** [DonBruce64/MinecraftTransportSimulator#333]
I would like if possible to add an option not to break the vehicle wheels.
My server is an only pve server and I do not want malicious players to break the wheels of honest players.
THANK YOU.

**Comment by DonBruce64** [comment]
I can't do this, but I can completely disable damage on vehicles with such a config if that's okay with you.

**Comment by dentesdracula** [comment]
Oh yes it would be perfect for me, if you don't mind it's an option that would be perfect for my server
thank you so much

**Comment by dentesdracula** [comment]
> I can't do this, but I can completely disable damage on vehicles with such a config if that's okay with you.

Oh yes it would be perfect for me, if you don't mind it's an option that would be perfect for my server
thank you so much

**Comment by DonBruce64** [comment]
Ended up adding a config to disable popped wheels in V17.0.0.  Request granted!
