### ISSUE TITLE
Broken Harvest

### ISSUE THREAD

**Issue by Colt44Magnum** [DonBruce64/MinecraftTransportSimulator#337]
When creating a part with the type harvester the breaking of crop blocks works great, however after breaking the crops the items do not end up on the crates added on the vehicle. I've noticed that Seagull and I are both having this problem, just wondering if we are doing something wrong or if its a bug needing fixed

**Comment by DonBruce64** [comment]
Rodger.  Will look into this.

**Comment by DonBruce64** [comment]
Fixed in V17.1.0.
