### ISSUE TITLE
Crash when using MTS Version 16.1.1

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#340]
As it says on the title.  Crash report below
[crash-2020-03-03_20.06.40-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4290301/crash-2020-03-03_20.06.40-client.txt)

**Comment by DonBruce64** [comment]
The hell?  What's your game doing trying to find tooltip info when it loads up?  Either way, one of your packs is missing components on a crate.  Can you remove them one by one until the startup crash doesn't occur?

**Comment by SanjivanM** [comment]
I was being dumb, updated the official content pack, then it behaved.
