### ISSUE TITLE
Bug when placing rear wheels of an aircraft at exactly 0 Z.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#342]
Picture says it all. Tested with the MC-172 as well. It makes sense that this would happen, but at the same time it really shouldn't. To reproduce it. build an MC-172 and place a slab under the front wheel, then remove the slab.
![2020-03-05_07 06 15](https://user-images.githubusercontent.com/44233145/75989148-fd4a1580-5eaf-11ea-9a7c-535e0d6a1eb9.png)

**Comment by DonBruce64** [comment]
Huh.  It should be considering wheels at Z=0 to be rear wheels.  Though there might be some code oddities that are causing that issue.  Rotations get nasty when you have 0s around.  Will investigate.

**Comment by DonBruce64** [comment]
Canceling as this is due to intended behavior with the collision boxes and not wheel placement.
