### ISSUE TITLE
Unable To Place Barrels On Stake Bed

### ISSUE THREAD

**Issue by jackleofsparta** [DonBruce64/MinecraftTransportSimulator#344]
Hey Don,

I mentioned this in the comments but thought I would make an actual post here. I'm not sure if you already know but as of V16.1.1 I am unable to place the Barrels on the stake bed of the brigadier. The boxes show red and no matter what I do don't show green. Apologies in advance if you already have this on your list of stuff to do.

Thank you.

**Comment by DonBruce64** [comment]
OH!  I honestly completely forgot about this, but this is a perfect time as I'm due to release a pack update soon, so I can fix before that.  Thanks for the ticket!

**Comment by DonBruce64** [comment]
Confirmed working as of V17.0.0.
