### ISSUE TITLE
Multiplayer crash

### ISSUE THREAD

**Issue by dentesdracula** [DonBruce64/MinecraftTransportSimulator#346]
Hello and thank you for adding the anti wheel breaker option ;-). We have another serious problem ;-(
When player A enters a vehicle, player B has minecraft which crashes and cannot connect until player A leaves his vehicle. the same if player B enters his vehicle, it is player A who crashes.
Thank you.

**Comment by DonBruce64** [comment]
Actually already had this fixed.  Just hadn't pushed out the release to curse.  Fix was applied in commit 4fd147ce8f2163ab63e5658ae008b859dc678329, and released as of V17.1.0.
