### ISSUE TITLE
Engine fuel crashes

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#348]
If you have a gasoline engine in a car, put some fuel in, and then swap to a diesel engine, the game crashes.

I also noticed that if you fuel a car with lava, then remove lava from the accepted fuels list in the config, the game crashes.

I would suggest making it so if a vehicle's tank has the wrong fuel, it just gets emptied.

**Comment by DonBruce64** [comment]
Yup.  That's a problem.  Same issue happens if the default fueling factor is set to a fuel that doesn't exist.  Will have to tweak both to prevent this issue.

**Comment by DonBruce64** [comment]
Fixed in V17.2.0.
