### ISSUE TITLE
Suggestion: A possible system for Vehicle-on-Vehicle collisions?

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#353]
Hello.
How's a togglable-via-config option for vehicle to vehicle collisions sound?
I'd assume it won't be easy... But what if it utilizes a bounding box system?
i.e. The bounding box specified in the vehicle .jsons... For all vehicles involved in the collision. So like, When Vehicle A (VA), and Vehicle B (VB) collide, MTS/IV Uses the bounding boxes specified in the .jsons. To clarify speed issues, if VA is going at 10BPS, and VB is stationary, VA could potentially take more damage.
To enhance my idea further, vehicles could have a sort of HP system. For the frame/body only, and collisions. Whether blocks or vehicles, don't matter. Tack off on the hypothetical HP system. Vehicles could be "healed" via a new bench. I'm thinking one of those vehicle lifts found in mechanic shops. And it could potentially render the vehicle placed on/in it.
of course, the max HP would be defined via .json, and when the vehicle's HP reaches 0 or lower, it explodes or breaks.
In the case of servers/trolls...
The system could either be disabled entirely, or have a blacklist/whitelist of damage sources.

Please forgive me for the bad grammar and punctuation...

**Comment by SYDoukou** [comment]
1. In a collision both objects should take the same damage, just some physics for ya
2. I remember asking don for part damage, like engine will decrease HP rather than just explode when overheating, maybe even let propellers or jets take damage when entities interact with them. I dont remember what don said about that but all i remember is a no

**Comment by DonBruce64** [comment]
So, I'm not sure if I want to do this or not.  The big issue is making vehicles behave correctly when colliding and not getting stuck.  They do that enough already with blocks and walls.  Am not going to say no, but will also not say yes.  Tabling for now.

**Comment by DonBruce64** [comment]
Implemented as good as I'm gonna do it in V20.0.0.
