### ISSUE TITLE
Vehicle Phantom

### ISSUE THREAD

**Issue by SebastianSoftware** [DonBruce64/MinecraftTransportSimulator#354]
I have a big problem because in my server of aternos the vehicle is like a ghost it drives itself, example: I ride and the steering wheel handles itself, the pedals the same and I can't turn it on because it would crash me many times, please help, version 1.12.2, from MTS Official Pack V15, Latest Version of Forge, Postscript: It Only Happens to Me on the servers in my lonely world it does not happen

**Comment by DonBruce64** [comment]
Not the first I've heard about this.  Will check.

**Comment by DonBruce64** [comment]
Should be fixed as of V17.3.0.
