### ISSUE TITLE
Farseek Crash

### ISSUE THREAD

**Issue by ytHighQ** [DonBruce64/MinecraftTransportSimulator#355]
The API Farseek for the mod Streams and Repose mod seems to crash everytime I turn on a cars headlights in the latest release of MTS. As soon as I turn on a vehicles headlights (tested on the UNU Corsair Police) my screen goes white and the game crashes. I'm assuming it's a rendering issue if you wouldn't mind looking into it

**Comment by ytHighQ** [comment]
Here's the crash log: https://paste.dimdev.org/pacaciqemo.mccrash

**Comment by alnega31** [comment]
That´s what happened to me as well. Please try to find the error
[MInecraft crash.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4356718/MInecraft.crash.txt)

**Comment by alnega31** [comment]
But it happens also in planes and once it happens you can´t go in to the world again it happens all the time

**Comment by DonBruce64** [comment]
This is due to code errors in MTS with how lights are handled.  If you can wait for a few days without turning on the headlights I'll have it pactched.

**Comment by DonBruce64** [comment]
Issue was patched in Commit: bc88325295747b13c9e561692e093925a901ff18, but that's not in the final build of the mod yet.

**Comment by DonBruce64** [comment]
Fixed as of V17.3.0.
