### ISSUE TITLE
Immersive Railroading and Immersive Vehicles Crashing on Startup (Minecraft 1.12.2 Forge ver. 2847 Ubuntu 18,04)

### ISSUE THREAD

**Issue by YOLOSTONE** [DonBruce64/MinecraftTransportSimulator#358]
Whenever I load MTS mods both with other mods and by themselves, they end up crashing during initialization without a crash log. Output logs don't say anything either. It commonly happens in the Texture Mipmap and Upload stage.

Please help

**Comment by DonBruce64** [comment]
If you can't give me a crash log or a game log, there's not anything I can do.  You're basically telling me that it doesn't work, but I have no clue why.

**Comment by YOLOSTONE** [comment]
> If you can't give me a crash log or a game log, there's not anything I can do. You're basically telling me that it doesn't work, but I have no clue why.

I've accessed the output log and these were the last few entries. It froze so I killed the process in the terminal.
```
10:44:47.659 
[10:44:47] [Client thread/INFO] [FML]: Applying holder lookups
10:44:47.662
[10:44:47] [Client thread/INFO] [FML]: Holder lookups applied
10:44:48.463
[10:44:48] [Client thread/INFO] [universalmodcore]: GPU Memory: 100% 1024/1024MB
10:44:48.942
[10:44:48] [Client thread/INFO] [universalmodcore]: GPU Memory: 100% 1024/1024MB
10:45:39.971
Process crashed with exit code 9
```
Here's the full output log: [https://paste.ubuntu.com/p/KNG3ZQ6KcG/](url)

**Comment by DonBruce64** [comment]
Huh?  You closed this?  I'm guessing it wasn't an IV issue?
