### ISSUE TITLE
Incompatibility with Real First Person Render

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#36]
My body glitches back and forth in the seat, when it's not clipping into said seat behind me. The latter I guess is not fixable, but it'd be nice if, while sitting still, my body didn't flip out.

**Comment by DonBruce64** [comment]
I'll have to take a look at this.  I know that MTS used to be compatible with RFPR.  Not sure why it isn't compatible now.  Would be best if I don't make my own mods incompatible with one another, wouldn't it. ;)

**Comment by DonBruce64** [comment]
This glitching, is it just jitters or is is a lot of movement?  I was testing on 1.10.2-13.0.1, and saw some jittering when turning, but nothing major.

**Comment by fsendventd** [comment]
It's a big mess. Very jittery with a good bit of movement. I've been experiencing it as well.

**Comment by DonBruce64** [comment]
Very odd.  Would one of you be able to post a video of this happening?  I'm more familiar with jittering based on context than anything.

**Comment by fsendventd** [comment]
Video right here. Had to try a few times to get it to happen, though.

![ezgif-2-6098351ce8b6](https://user-images.githubusercontent.com/44233145/54282061-64144780-4558-11e9-8b90-1d78d590671e.gif)

**Comment by DonBruce64** [comment]
Now THAT is not what I was seeing on my end.  Does this happen with newly-placed vehicles, or does it only happen with existing vehicles?

**Comment by fsendventd** [comment]
It happens with new vehicles, for sure. It doesn't happen every time, though, and it's only in that one "mode" of RFPR (it seems to have one where the arms don't render and one that disables the mod that you can toggle to by pressing F1).

**Comment by obsidian29** [comment]
Wait, what? You can toggle it?

**Comment by DonBruce64** [comment]
@fsendventd Can you clarify which mode you mean?  I don't quite follow your comment.

**Comment by fsendventd** [comment]
It's the mode where the entire body is rendered in first person, as opposed to just the torso and arms. Doesn't happen in that mode or in "disabled" mode.

**Comment by DonBruce64** [comment]
But the torso and arms are *always* rendered in full-body mode.  You can toggle between the torso *or* the arms, but if you have the torso *and* the 3D arms then you are in full-body rendering mode.

**Comment by obsidian29** [comment]
Mine toggles between torso and legs; torso legs and arms; and nothing, at its own will.

**Comment by fsendventd** [comment]
Yeah, that's what I meant. Mis-worded my original comment.

**Comment by DonBruce64** [comment]
Fixed in 13.1.0.
