### ISSUE TITLE
[1.12.2] Client crash - java.lang.IllegalArgumentException: Cannot get property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing,

### ISSUE THREAD

**Issue by ProsperCraft** [DonBruce64/MinecraftTransportSimulator#360]
https://gist.github.com/ProsperCraft/fdb352fd65390089c55046b28573dd49

We suspect it is from street lights.

**Comment by DonBruce64** [comment]
Odd, I can't seem to reproduce this on my end.  Are you on a server?

**Comment by ProsperCraft** [comment]
Yes, TownCraft official server.

**Comment by DonBruce64** [comment]
Doubly odd.  From what it looks like, you have a partially-destroyed block.  The game didn't destroy the entity that does the rendering, so it's trying to render air.  Did this happen when you broke a block?

**Comment by DonBruce64** [comment]
Should be fixed in V17.4.0.
