### ISSUE TITLE
 [BUG?] Headlights don't work with Hardcore Darkness installed

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#367]
Quick rundown on Hardcore Darkness: At light level 0 or at nighttime, things become pitch black instead of just the usual ambient lighting Minecraft has.
The issue? You can't have cool headlight helpfulness at night with MTS!
[Their git here](https://github.com/lumien231/Hardcore-Darkness/issues)
![image](https://user-images.githubusercontent.com/53581325/77813237-7a1a7a80-707d-11ea-8fb6-2bce57b37012.png)

EDIT: Possible theory is that due to how Hardcore Darkness makes entity models dark, it may be darkening the beams as well.

**Comment by DonBruce64** [comment]
Will get with them to see if they can tell me where to look.

**Comment by DonBruce64** [comment]
So, they didn't seem to want to help with this issue.  I'm closing it on my end due to the fact I've done all I can do, but you can bet your bippy I ain't closing it on theirs till they respond to the ticket.
