### ISSUE TITLE
Suggestion: "Absolute value" steering rotation variable

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#371]
I was working on one of DVC's new suspension-complete vehicles this morning, and came across an issue when doing rotations for the steering. When trying to keep the tie rods attached to the hubs, I realized that the regular steering wheel rotation variable would make the tie rod rotate in the wrong direction when steering the wheels one way. This could be easily fixed by adding a new rotation variable that works similarly to the steering wheel, but takes the absolute value of the steering angle so that it only rotates one way no matter which direction you're steering. It's a hard situation to explain, but it seems like an easy enough variable to add so I didn't think I'd have to really sell you on it...

**Comment by DonBruce64** [comment]
Should be easy to add a JSON parameter to make the returned variable absolute.  Then you can add the sign of the vector to define how you want to behave.

**Comment by DonBruce64** [comment]
Implemented in V18.0.0.
