### ISSUE TITLE
[1.12.2] Crash when launching component bench

### ISSUE THREAD

**Issue by martset** [DonBruce64/MinecraftTransportSimulator#372]
Hello all,

MTS is crashing my entire game when I open the component bench, and logging an error message saying "java.lang.NullPointerException: Unexpected error".

I have the UNU Civilian Pack, Military Pack, and iconic movies pack installed.

**Comment by DonBruce64** [comment]
Going to need the whole crash report, please.

**Comment by martset** [comment]
[crash-2020-04-03_12.04.56-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4424826/crash-2020-04-03_12.04.56-client.txt)

**Comment by DonBruce64** [comment]
How the heck did THAT happen?  Is that the first time you open the component bench in a game, or did it happen when re-opening it?

**Comment by martset** [comment]
At first I can open the bench, but the grid is completely empty. I can close it, but if I try and open it again, it crashes.

**Comment by DonBruce64** [comment]
Ah, I can see how this would happen.  Will fix.  For the moment, just avoid opening empty benches.

**Comment by DonBruce64** [comment]
Fixed in V18.0.0.
