### ISSUE TITLE
Bug: Steering offset for wheels seems to not be working (perhaps I'm doing it wrong?). 

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#374]
What it says on the tin. I put a steering offset into a part slot that accepts wheels, but the wheel I added doesn't seem to rotate its model around the offset point. I suspect I'm doing something wrong.

**Comment by DonBruce64** [comment]
Will look into this after this block update.

**Comment by DonBruce64** [comment]
Steering offset removed and replaced with generic part offset system in V18.3.0, so this bug is no longer applicable as the whole system has been overhauled.
