### ISSUE TITLE
Trailers explode at random.

### ISSUE THREAD

**Issue by Onikage056** [DonBruce64/MinecraftTransportSimulator#375]
As the name says.
I was using a Mule truck with a double trailer dolly and a two container trailer attached to that... rounded a corner, stopped the truck, and both trailers promptly launched off the truck like they'd been dropkicked by the Hulk in two different directions and exploded.

**Comment by DonBruce64** [comment]
That would be a @DrprofLuigi question!

**Comment by DonBruce64** [comment]
Fixed in V19.6.0.
