### ISSUE TITLE
[suggestion]Tanks and fluid loaders

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#377]
Talked about it before, just putting it here for the far future.

New fluid container type: **tank**
>**Tank** can be a barrel variable "isTank" or have a new "fluid" part type and have "barrel" and "tank" as sub types.

New machine: **fluid loader/unloader** (FL)
>Switches between *load* and *unload* state with wrench right click, activated with right click or redstone signal. 

Behavior:
**Tank** is just like barrel, except that it cant be filled with buckets and needs to interact with **FL**. **FL** in *load mode* works like fuel pumps, can take pipe inputs and fill the **tank** its linked with. It will interact with the nearest **tank** that isnt full or contains other fluid within 15 blocks. Right clicking toggles it on/off while the state will try to match the redstone signal, just like doors. It will stop automatically when theres no valid tanks in said range.
In *unload mode*, it will unload the fluid in the nearest tank within 15 blocks. A filter option might be too complex but would be useful. The extracted fluid can be piped out. 
When a **tank** contains any valid fuel specified in the configs, it will act like a fuel pump. There will be a **fuel button** on the HUD of the vehicle its on or towing it. Right clicking and pressing the button will both activate it, clicking toggles it on/of but it will ***always*** match the button in the HUD. It will try to fuel the nearest vehicle that will accept the fuel its holding. 

Some of the controls may not make the most sense but the general idea is there.

**Comment by DonBruce64** [comment]
So I likely won't do an implementation exactly like this (HUD buttons are meant for controlling vehicles, not controlling parts on those vehicles), but I will do something that will allow for, at a minimum, pumping fluids from a block-based tank to a vehicle tank and vice-versa.

**Comment by SYDoukou** [comment]
Well it doesnt need to be a HUD button, right clicking would make sense too. The main point here is pumping fuel from tanks into vehicles, of it isnt completely impossible

**Comment by fsendventd** [comment]
HUD buttons would be almost required for anything related to mid-air refueling, as you wouldn't be able to get out of a moving plane to click on another plane if you needed to connect them.

**Comment by DonBruce64** [comment]
Well, seeing as how nobody is making warplanes, or even has made a jet fighter, I'm not about to care about such a feature.

**Comment by LauraDarkez** [comment]
an instance of `supply equals demand` where if a pack author supplies the models, the demand will be met

**Comment by fsendventd** [comment]
So this could also have some use for removable tip tanks for certain planes. Currently if you made them barrels, they wouldn't allow the plane to pull from them, but theoretically with use of the tank system they could link to the vehicle's fuel tank and allow it to actually have a longer range.

**Comment by DonBruce64** [comment]
@fsendventd As of the latest MTS, you can allow barrel parts to feed the main vehicle tank.  So that particular point is good.
@Ooferine Also, as of the latest MTS, you can use a jerrycan on a tank to pull fuel from it, and then use that jerrycan on a vehicle to fill it up, so the "rescue truck" code is at least somewhat possible.  Fuel trucks are still not possible, as vehicle-to-vehicle transfer isn't functional.  Neither is the functionality to load fuel into tanks from a pump-based system like the fuel pump does to the vehicle's internal fuel tank.

**Comment by DonBruce64** [comment]
Implemented in 19.4.0.
