### ISSUE TITLE
Sound doesn't stop after removing the Aircraft

### ISSUE THREAD

**Issue by Rinma** [DonBruce64/MinecraftTransportSimulator#382]
Hi,

When I sneak attack an aircraft with the wrench I have this sound which does not go away. It only plays outside of the aircraft and as far as I can hear it it is not played when I fly the aircraft. It is also not played before I first start the engine. It sounds like a type of fan for cooling.
When I leave and reenter the game the sound is gone.

**Comment by DonBruce64** [comment]
When this happens, is a sound already playing?  Is it the engine sound that's playing?  What version of IV are you using?  Going to need more information.

**Comment by Rinma** [comment]
Versions:
- Minecraft: 1.12.2
- Forge: 14.23.5.2847
- Mod: 17.4.2
- MTS Official Pack: V15

Video of what happens: https://media.over-world.org/videos/watch/a4853862-fe42-418c-898a-e90848199982

**Comment by DonBruce64** [comment]
Odd, I can't hear anything except the engines running, and when you wrench the plane the sound goes away.  Is there something I'm missing?

**Comment by DonBruce64** [comment]
I took a second listen at the video.  I do hear a real faint sound.  But that sounds like a running jet engine.  Do you have any jets in the world with their engines on?

**Comment by Rinma** [comment]
The world was just created for this video. This was the only aircraft I build. Yes, the sound is not noisy but when you wear headphones it can bother.

**Comment by DonBruce64** [comment]
Odd.  Does the sound only occur once a vehicle's engines have started, or does this happen on a new world?  i.e., do you hear it if you never start an engine?  Trying to find out the exact steps to reproduce on my end.

**Comment by Rinma** [comment]
I only hear it after I started an engine.

**Comment by DonBruce64** [comment]
Very odd. I can't seem to re-produce this bug.  Are you able to get on the Discord so I can give you a test version to do some advanced debugging?

**Comment by DonBruce64** [comment]
Fixed in V18.1.0.  This one was a doozy, thanks for getting with me!
