### ISSUE TITLE
[PACKARD] The ENTIRE light bulb for any light glows on the OCP Firetruck.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#386]
![image](https://user-images.githubusercontent.com/53581325/79256182-8f512080-7e55-11ea-9f8f-3eefecb16097.png)
![image](https://user-images.githubusercontent.com/53581325/79256205-9710c500-7e55-11ea-89d9-db71cb448510.png)
(How they appear on vs off)

**Comment by DonBruce64** [comment]
Wait, which turn signal is this?

**Comment by boot2big** [comment]
I've turned both on, so hazards.

**Comment by DonBruce64** [comment]
I see now.  Will note for fixing.

**Comment by fsendventd** [comment]
This is one of those things that's not obvious but really annoying once you do notice it.

**Comment by DonBruce64** [comment]
Fixed in V17 of the OCP.  Or rather, this was made redundant by the re-modeling of the Firetruck where there aren't any bezels on the lights.
