### ISSUE TITLE
Updated handbook to include something I forgot.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#388]
Needed to mention that supercharged engines heat up faster. 
[MTSPackHandbook.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4482344/MTSPackHandbook.zip)

**Comment by DonBruce64** [comment]
That's not the most-current handbook uploaded to the Git System.  If need be you can just post the edits here and I can apply.

**Comment by fsendventd** [comment]
Alright. Replace the "superchargerEfficiency" section with this. I forgot that you had to update it to include other things.

•	superchargerEfficiency – The efficiency of the supercharger on this engine (if any). The supercharger fuel consumption of this engine (but not the base fuel consumption) will be multiplied by this value. A value of 1 will make the supercharger add the same amount of power for its fuel consumption as adding that number to the base fuel consumption, so make sure to set it to greater than that if you want your supercharger to have any power benefits! 
This also affects the engine wear calculations, with a value of 1 or below leaving them the same as what it would be without a supercharger. By setting this value to significantly below 1 you can simulate inefficient, gas-guzzling engines if you have a high supercharger fuel consumption, as it won’t add much power but will make the engine use a lot more fuel. 
And one more thing, supercharged engines heat up faster than non-supercharged engines. A supercharger efficiency of 0 would make the calculations the same as a non-supercharged engine in this case, though setting it to 1 will not make the engine heat up twice as fast. This is intended behavior, as real supercharged engines heat up faster than naturally aspirated ones even if the supercharger itself isn’t very efficient. 
This variable can be omitted if your engine doesn’t have a supercharger.
