### ISSUE TITLE
Jump Start and other rotation variables

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#390]
I'm back, with more rotation variable requests!

'engine_jump_x' is 1 when the engine is connected to a jump start
'fueling' is 1 when the vehicle is connected to a fuel pump
'liquid_flowing' is 1 when connected to a liquid loader (for barrels, variable can be better)
'wheel_rotation_x' is the same as the rotation of the specified wheel
'engine_present_x' is 1 when a vehicle is in slot X (similar to hood, but part-specific.
'wheel_floating' is 1 when !wheelColliding

**Comment by DonBruce64** [comment]
This is gonna take a while.  But it'll finally get people off my back for the blasted fuel pump animations.

**Comment by DonBruce64** [comment]
Implemented the following variables:

"fueling" for when the engine is fueling from a fuel pump.
"engine_jumper_cable" for when the engine is connected to a jumper cable.
"ground_rotation" for the current ground device rotation.
"ground_onground" for if the ground device is on the ground (may be in the ground, keep that in mind).
"ground_inliquid" for if the ground device is in liquid (may be in liquid).

I'm going to hold off on the liquid loader/unloader variables as those are dependent on loader/unloader functionality actually being present, so will get put in during that system addition.  Also, you can't have engine_present.  The MTS system doesn't work based on animations of things that don't exist, and I really don't want to try to code such a thing.  Y'all have this fancy new click-able hood thing, so use that!
