### ISSUE TITLE
Pole tweaks

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#391]
When I break a traffic signal, stoplight, etc. it drops the pole with the NBT of the light. Wrenching it off is handy, but I think it would also be nice to drop everything when it's broken, rather than saving it in the NBT.

Also, decors and poles drop in creative, it would be nice if they didn't - Ooferine

Finally, it would be nice if you could lock text signs for servers, if there isn't a way to already.

**Comment by DonBruce64** [comment]
Last one exists.  Will tweak the former two prior to release day.

**Comment by DonBruce64** [comment]
Addressed in 5a186cb8f9508dc8f884e42b7311ceacb4bb9d28

**Comment by DonBruce64** [comment]
Fixed in V18.0.0.
