### ISSUE TITLE
Traffic signal light tweaks

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#392]
When a traffic light is on (Stop, Go, or Warning), they should blink according to the light duration hex bit.

That way, if you have a two-light signal like the crosswalk, you can set the caution light to blink red and the stop light can be solid.

**Comment by DrprofLuigi** [comment]
Also, when the light is off, the lens face is invisible, rather than showing the normal texture. My guess is that these aren't working 100% like vehicle lights.

![2020-04-15_22 40 04](https://user-images.githubusercontent.com/36775575/79418692-1a233f80-7f6a-11ea-874b-9f1838155311.png)

**Comment by DonBruce64** [comment]
Traffic lights blink according to the hex bit when they are told to blink.  So only for blinking red or blinking nowalk.  Go doesn't blink because it's always a solid color.

Will check the lens faces though.

**Comment by DonBruce64** [comment]
Fixed in V18.0.0.
