### ISSUE TITLE
[Suggestion] Decorative "armor"

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#393]
Decorative armor items such as helmets and headsets for aesthetics and not looking like poorly made 2d armors. Uses are mostly for RPs situations (Pilot headset, hardhat, police uniforms, etc)

**Comment by DonBruce64** [comment]
Yeah, this is gonna be a nightmare to code.  Armor rendering requires armor items, and specific models and lots of game-specific code.  I'm gonna leave this to the mods that specialize in such things.
