### ISSUE TITLE
Crash: placing fuel pump on grass

### ISSUE THREAD

**Issue by KamilValko** [DonBruce64/MinecraftTransportSimulator#395]
The game crashes when I try to place fuel pump on grass (NOT grass block). After I load the world again, the fuel pump is where I tried to place it, but the crash is kind of annoying and should be fixed.

[crash-2020-04-17_19.35.32-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4494450/crash-2020-04-17_19.35.32-client.txt)

**Comment by DonBruce64** [comment]
Freaking WAILA mod getting things before the exist on clients!

I'll fix it, but I do get tired of these things from them.  Can't they wait a tiff before trying to get things?  Ah well....

**Comment by DonBruce64** [comment]
Addressed in hotfix V18.0.1.
