### ISSUE TITLE
Planes w/ Pontoons Shake when Sitting in Water [MTS V16 on MC 1.12.2]

### ISSUE THREAD

**Issue by Falconier16** [DonBruce64/MinecraftTransportSimulator#399]
When planes equipped with pontoons are sitting in water, they shake, making the experience less enjoyable and the planes far less aesthetic. I am playing on a singleplayer worls in MC 1.12.2 with just IV and MTS V16 installed.

**Comment by fsendventd** [comment]
Can confirm this. Really quite annoying.

**Comment by LauraDarkez** [comment]
i believe this is an issue with the way the water handling physics is, and i also notice it jitters/shakes more often on a vehicle that is staying still, aka parkingbraked, or translated from land to water (amphibious stuff). the hope is that this can be fixed with a bit of physics

**Comment by DonBruce64** [comment]
It's in the works, but since we don't have a consensus on how boat physics should be I'm not too concerned about it right now.

**Comment by DonBruce64** [comment]
Fixed with the ground physics update in V19.0.0.
