### ISSUE TITLE
[SUGGESTION] Engine damage variable.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#401]
This value decides whether your engine can take a bunch of abuse and beatings, or will fall apart if you dare breath on it.

Lets say if a pack maker sets it to 1, or doesn't even add it at all, the game does nothing. Your engine will wear out as it usually does, which is dependent on the engineHours factor.
However, if they set it to 0.5, the engine wears out half as fast... and is probably twice, or even thrice the price of a normal engine. Meanwhile, if they set their other, cheaper engine to 2, not only is it a lot weaker in terms of power, but as well as defence.

Why would this be added? Balancing, I guess.
You could have really cheap engines that don't last that long, or you could have robust futuristic engines that wouldn't stop running if the universe came to its heat death.

**Comment by fsendventd** [comment]
The only issue here is that people could set their engine durability to 0, making them infinitely strong, and then let you craft them for a block of dirt. That's the reason we use fuel consumption to dictate power. It's so that people can't make stupid engines that use no fuel.

**Comment by DonBruce64** [comment]
I'm gonna flag this as a wontdo, for the simple reason we have the supercharger code to leverage durability and inefficient/efficient engines.  This still allows for more or less durable engines, but doesn't allow for hackery.  If modpacks don't like the hour accumulation, they can always turn down the factor in the config.  Should be good enough for most situations.
