### ISSUE TITLE
Client Crash Adding Sign to Vehicle using Trin Part Pack

### ISSUE THREAD

**Issue by RobertSnype** [DonBruce64/MinecraftTransportSimulator#403]
What:
      Placing police car sign on vehicle from trin pack causes client to crash. Player screen goes white then rapidly strobes screen and white blank screen. Serious seizure risk! Cannot move player and others who approach get caught and crash.
Steps to reproduce:
     put a police car top sign on the hotrod from trin pack
     trin splite (Magenta) #10535 and a Police Car Roof Sign #11210
Crash Report:
(https://github.com/DonBruce64/MinecraftTransportSimulator/files/4531520/crash-2020-04-24_05.58.45-client.txt)
[crash-2020-04-24_05.58.45-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4531524/crash-2020-04-24_05.58.45-client.txt)

**Comment by DonBruce64** [comment]
This is an issue with the Trin Emergency pack.  You'll have to get with that author to fix it, not me.

**Comment by TheOddlySeagull** [comment]
The issue comes from the Trin Part Pack, not the Trin Emergency Pack, it’s a known bug that has been fixed in dev, it will update fixed in the month.

**Comment by TheOddlySeagull** [comment]
Forgot about that github, all those issues have been fixed in the last update that came out a few weeks ago.
