### ISSUE TITLE
[suggestion] Allow named mobs to sit in vehicles/ be moved around?

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#405]
This would make mob moving much easier that the conventional minecart methods, and would add to the immersion (Villagers in the passenger seat(s) if you use Minecraft Comes Alive, or a tamed wolf poking its nose out of the window).  As a reference, bibliocraft adds in this ability to have named mobs sit in/ dismount the Seats, not so sure if it would require some adaptation to this aspect, however, it would be a nice thing to have.

**Comment by SanjivanM** [comment]
nvm... there's the ticket.  Haven't updated in a WHILE :P But there's a ton of stuff that's not working in the new version...

**Comment by SanjivanM** [comment]
Aaaand I'm back.  Sneak+using on a MCA villager doesn't do anything, can it be fixed on your part?

**Comment by DonBruce64** [comment]
I don't follow.  Do they not get linked?  Do they still ride in the vehicle if you use the ticket while in the vehicle?  I don't know if I documented it, but if you're driving a vehicle and use the ticket (without clicking the vehicle) all villagers auto-mount.  Do they not do this?

**Comment by DonBruce64** [comment]
Closing this issue as the main discussion seems to have been on #406.  Will handle discussions there.
