### ISSUE TITLE
Odd bug with the new custom sounds.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#407]
The volume parameter for the custom sounds seems to only be effective after the engine has reached the point where volume should start increasing. Then, if you bring it back down to idle, it works properly, but if you shut off the engine and start it again the sounds all behave like they're volume-adjustment-less.

**Comment by DonBruce64** [comment]
I'm going to let @BlazeWolf1122 handle this one, as he's the one who put that system in.

**Comment by DonBruce64** [comment]
Turns out this is easy enough to fix.  Will do this in the next release.

**Comment by DonBruce64** [comment]
Fixed in V19.2.0.
