### ISSUE TITLE
Rotation offsets don't seem to work on rotatable model objects, just instruments.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#411]
What it says on the tin. Can't really describe it any better.

**Comment by DonBruce64** [comment]
Well, yeah, they don't work because they don't exist.  They aren't in the JSON nor in the handbook as something that exists.

**Comment by fsendventd** [comment]
Well darn. I thought that they had been a thing that was added. I kinda needed them to work...

**Comment by DonBruce64** [comment]
Well, sounds like a PR to me!

**Comment by fsendventd** [comment]
Rotations aren't my forte. I have no idea how they work. I'm much better with the math parts of the code.
