### ISSUE TITLE
Request: textMarkings color in the definitions section (doable?)

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#413]
This would be mostly useful for planes, where the part the text is on isn't always the same color. On one plane, black text might look great, where on another it could blend right into the paint, and vice versa.

**Comment by DrprofLuigi** [comment]
I agree. It would also be nice to have the hudTexture and panelTexture be here as well, so you could have color-keyed instrument panels.

**Comment by DonBruce64** [comment]
If I do this, it'll break packs a second time. Is this really what y'all want?

**Comment by fsendventd** [comment]
Yes. Doc is the only one that's actually used custom panels if I remember correctly.

**Comment by DonBruce64** [comment]
If he's okay with it, I'll go ahead and change it.  It's not hard to do.

**Comment by DrprofLuigi** [comment]
I mean, I came up with the idea XD. _Maybe_ for maximum compatibility the definitions could override the panel texture if present, but I wouldn't have a problem moving them.

**Comment by DonBruce64** [comment]
Flagging this as a backburner as I'll be putting it in when I re-do the animations for duration and delay in V19.  That'll take a while, and will break all the animations for packs, so it'll be a good time to break text markings too.

**Comment by DonBruce64** [comment]
Implemented in V19.6.0.
