### ISSUE TITLE
Crash when opening in-game manual (1.12.2)

### ISSUE THREAD

**Issue by Aiva418** [DonBruce64/MinecraftTransportSimulator#414]
Minecraft Forge version: 14.23.4.2847
Immersive Vehicles version: 18.1.4

I was flipping through pages in the manual, and I hit a bit of input lag, and it must have queued up too many clicks because I got an "out of bounds" exception. Now the game crashes whenever I try to use the manual in that world. I think the page number is stuck on "-3" or something.

[crash-2020-05-04_13.30.10-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4576744/crash-2020-05-04_13.30.10-client.txt)

As a sidenote/suggestion, it would be nice if the table of contents had links to the respective pages and there was a button that sent you back to the beginning of the book. It would make the book easier to use.

**Comment by DonBruce64** [comment]
See the crash make sense on that, but it doesn't make sense on world re-load as the books don't save their page number.  I can see about making the TOC take you to the listed page, however.  That's not a bad idea.  This is one of the few tickets that gets both a bug and enhancement label!

**Comment by DonBruce64** [comment]
So I tried a whole bunch to re-create that crash, but couldn't.  I can see it happening on older MTS versions, but I don't see how it would happen on the new ones.

That being said, I did add a click-able TOC and TOC button to bring you back to that page in V18.2.0, so I'm going to call this ticket done.
