### ISSUE TITLE
[Suggestion] OBD "Computers"

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#415]
OBD tools, in the real world are devices that basically tell you what problems your car has.  See https://en.wikipedia.org/wiki/On-board_diagnostics for more information.

I suggest that such a system be implemented into MTS as an item, that a user can 'use' on their car/truck and get a screen showing an overview of the vehicles 'vitals', such as Fuel level/type, engine wear stats/ if it is leaking, etc.  The OBD device could also be used to tell you when to take your car in for repair, if you're on a server, or it could be used for those DIY repairs.

//End main OBD discussion.  Below is stuff that shouldn't be too hard (correct me if I'm wrong), but would definitely increase the immersion

This also introduces the possibility to add tire wear, in 2 possible ways.

1. All tires wear the tread down by x amount (with a safe driveable range) for every y blocks travelled.  This allows for tires of the same wear, e.g. from the same vehicle, to stack
2. Tires wear at a constant rate, as defined above, but only if they are touching the ground (if that's even possible/ detectable).  The downside to this is that each tire then, is essentially unstackable.  Storage would likely have to be in your own car workshop, or a "Used Tire Depot", built by whoever doesn't want to throw old tires into lava (recycle them and get some resources back, perhaps?)

This could be implemented by some NBT tags on the tires: minWear, maxWear, currWear.  Example:
Tire
*minWear=2.0
*maxWear=0.1
*currWear=1.3

So if the current wear gets to below maxWear, the tire would be essentially useless (if possible, the friction provided by the tire could be reduced)
The OBD could then have additional tire wear information, to tell you when to replace/rotate the tires, depending on the implementation.  THis also gives you a reason to have some spares and an OBD with you, or in your vehicle.

Now if you're saying "well, wait a minute, if you have so much implementation suggestions, why not do them yourself?"
Well, yes, I could; however, I don't know my way around this project as well as those who've been here from the beginning.  My modding skills are also nowhere near those of the people who made this mod.  I could help, if desired, but it would most likely be after my exams are over (mid May).

**Comment by fsendventd** [comment]
Engines can already be tested for leaks by removing them from the vehicle and hovering over them. Same for the hours. As to fuel, you have fuel gauges for that, and if you know what fuel type your engine uses then you should know what type you have in your car.

And about tire wear... sounds really complicated. And wouldn't really add to the mod in a beneficial way.

**Comment by DonBruce64** [comment]
Completely agree with Fsend about this one.
