### ISSUE TITLE
Backup sound increases in pitch when speed increases

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#420]
So while I was testing the new engine sounds BlazeWolf1122 had provided me, I noticed that the backup sound was increasing in pitch while reversing. I though it was odd that the sound was pitching up while it shouldn't, like it doesn't irl. So just noticed that and decided put up an issues on fsendventd's advice

**Comment by RishiMenon2004** [comment]
I think blaze messed up somewhere or just forgot that backup sounds existed and forgot to exclude that in the pitch change thing

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
