### ISSUE TITLE
Part tweaks

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#423]
It would be nice to flesh out some existing features of part placement, namely defaultParts and additionalParts.

With defaultParts, it would be nice if when you placed a part that had a defaultPart (like a bench seat with two invisaseat defaultParts), the default part placed with it, rather than just being when a vehicle is placed.

With additionalParts, it would be great if a part could have multiple additionalParts. The situation I see this being used is my tilt-cab trucks, where the seats are additionalParts to the engine, so you can only place the seats when the cab is down.

**Comment by DonBruce64** [comment]
The first is do-able right out of the gate.  The second will break packs that use additonalParts due to them being lists rather than single entries.  If you're willing to take the flak for that and others are okay with it, then I can make the change.

**Comment by DrprofLuigi** [comment]
Hm, maybe for maximum backwards-compatibility, the single-use can remain 'additionalPart', and you just add 'additionalParts' with an s at the end to signify it's a list. ¯\_(ツ)_/¯

If not, I'd ask folks in the discord. I know War_Monger would like it.

**Comment by DonBruce64** [comment]
I mean, I *could* make it so MTS uses both.  But I really hate "special cases" in the code.  Though I could just leave it in for a few versions till folks update and then take it out.  I did that for the loading code changes.

**Comment by DonBruce64** [comment]
Closing this, as both were implemented in V18.4.0.  No more double-item tickets though.  They stay open too long!
