### ISSUE TITLE
Moveable hitboxes

### ISSUE THREAD

**Issue by Liquid-Banana** [DonBruce64/MinecraftTransportSimulator#426]
For example, a door having to open at the side of a RV to allow you to walk inside

**Comment by DonBruce64** [comment]
Doors are purely animations, and don't actually move anything.  The don't have hitboxes that can rotate because they'd only rotate on the client.  Now if you mean parts that move with their hitboxes, that's different.

**Comment by Liquid-Banana** [comment]
So it would be possible to make hitboxes move with a part, like a wing part, so you can make a wing have to fold to fit in a hangar?

**Comment by DonBruce64** [comment]
In theory, yes.  But there's not code to do that.  What you're doing to run into is how you tell the part to move.  That's going to require either a button press, or a switch on the panel.

**Comment by DonBruce64** [comment]
As hitboxes for parts were implemented in V18.4.0, and parts can move, and such parts can be made to come default with the vehicle, I'm going to consider this done.
