### ISSUE TITLE
Hitboxes for attachable parts

### ISSUE THREAD

**Issue by Liquid-Banana** [DonBruce64/MinecraftTransportSimulator#427]
For example a pod underneath a skycrane, or a big tank on a trailer

**Comment by DonBruce64** [comment]
Do-able, but would require some work to differentiate between parts with those hitboxes and those without.  You'd essentially have to define them like you do vehicles.  I'll add this as a possible to the list.

**Comment by fsendventd** [comment]
This would be great to have for things like different landing gear configurations or folded wings as parts on planes as well.

**Comment by DonBruce64** [comment]
Implemented in V18.4.0.
