### ISSUE TITLE
Multiple Text Fields for Vehicles

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#428]
Basically, when you right-click a vehicle with a nametag, it opens a similar GUI to signs allowing multiple entries. This would be most useful for busses and police cars, as well as utility vehicle fleets.

It would allow you to have things like cop cars with 'XXPD', license plate #, precinct #, and car number. I know you love GUIs, but I figured it was worth tossing out there.

**Comment by DonBruce64** [comment]
I mean, it *would* allow me to get rid of name-tag specific code...  And such a GUI really isn't hard to code.  I could also do it with #413 as that's also a text-breaking change.  Might hit these two at the same time.

**Comment by fsendventd** [comment]
There was something I wanted to use this for as well... I just can't remember what...

**Comment by SYDoukou** [comment]
Time for aircraft tail numbers and other customizable stuff

**Comment by DonBruce64** [comment]
Flagging this as a backburner as I'll be putting it in when I re-do the animations for duration and delay in V19.  That'll take a while, and will break all the animations for packs, so it'll be a good time to break text markings too.

**Comment by DonBruce64** [comment]
Added in V19.0.0.
