### ISSUE TITLE
Fuel Pump displaying internal name for Buildcraft fluid instead of in-game name

### ISSUE THREAD

**Issue by Chronosock** [DonBruce64/MinecraftTransportSimulator#431]
Buildcraft fluids show up in-game as "Light Fuel (Cool)", and internally this shows up as fuel_light in the Buildcraft jar file, with the Hot and Searing heat states being appended later and finally showing up as fuel_light_heat_1 and fuel_light_heat_2 respectively.

The fuel pump block is currently displaying fuel_light and other internally used names instead of the in-game Light Fuel (Cool) name of the fluid.

Versions of MTS and Buildcraft I am using are:
Immersive Vehicles-1.12.2-18.2.0.jar
buildcraft-all-7.99.24.6.jar

Edit: Same thing happens for jerrycans

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
