### ISSUE TITLE
Engine overhaul code is confusing me.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#432]
This is mostly about turboprops. I know that as of right now they're supposed to be regular engine_aircraft, but if they provide jet thrust do I need to put a bypass ratio in? Along those lines, will I eventually need to switch to engine_jet? It's not making much, if any, sense to me. Thought I'd put in a ticket so it can be answered in a more technical way, perhaps using code snippets if you need to.

**Comment by DonBruce64** [comment]
Tickets is for bugs and features.  Not for answering code questions that aren't in the mod yet or documented in the handbook.  Discord for that, please.
