### ISSUE TITLE
Bug with fuel

### ISSUE THREAD

**Issue by MrLaser398** [DonBruce64/MinecraftTransportSimulator#434]
When the fuel tank is full and you try to start the vehicle, the fuel level drops instantly to zero and won't let me use the vehicle. I need help!

**Comment by fsendventd** [comment]
Did you change your engine from gasoline to diesel or vise versa? That's all I can think of that would cause this.

**Comment by DonBruce64** [comment]
Version number would also be helpful here.

**Comment by DonBruce64** [comment]
Closing due to no response.
