### ISSUE TITLE
the truck with the MTS addon (main)

### ISSUE THREAD

**Issue by wdaybr** [DonBruce64/MinecraftTransportSimulator#435]
Hi. I do not know if this is a bug or not but the truck in the newest version is really glitchy. it stutters alot. and seems like its falling when its on flat ground.

**Comment by DonBruce64** [comment]
Do you have a video of this happening?  It's rather hard for me to tell what's going on without one.

**Comment by DonBruce64** [comment]
Closing due to no response from creator.
