### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by MCEventHorizon** [DonBruce64/MinecraftTransportSimulator#436]
https://gist.github.com/MCEventHorizon/22733dc6d4e5027f99a1ee839eb5d7f2

**Comment by DonBruce64** [comment]
Going to need to know which vehicle you placed at the time of this crash, from which pack, and which version of the pack you used.

**Comment by MCEventHorizon** [comment]
Didn't place any vehicles, it was a newly generated world, after the world was reset, I couldn't replicate the crash.

**Comment by DonBruce64** [comment]
Impossible.  The crash report you sent indicates that there's a vehicle that had a bad JSON that was being rendered at the time of the crash: `java.lang.NullPointerException: ERROR: Rotatable part definition:$Gearshift is missing a rotationAxis in the vehicle JSON!`

**Comment by MCEventHorizon** [comment]
Since I can't replicate it now even when placing vehicles, should I close it for now?

**Comment by DonBruce64** [comment]
Er, I'd say so.  If I can't know which vehicle has the issue, then it'll be impossible for me to test or tell the pack authors to fix.
