### ISSUE TITLE
a customization engine parts

### ISSUE THREAD

**Issue by VirtualGaming1** [DonBruce64/MinecraftTransportSimulator#437]
so instead of engine being just one part. think that engines could have parts on it as well and could do hours on the parts and depend on that part it could effect of what that part dose like engine hours you have but those parts can be replaced to fix that issue. and to customize the engine they must use the engine crane to change the parts on it.

parts could be: effects
alternator: Battery charging speed
Gears : can have different gearing setup [if worn out: have issue shifting gears or some gears my not work anymore]
piston: Engine top RPM, torque, HP
and many others

**Comment by DonBruce64** [comment]
Not doing this.  Engines are already hard to place, and hours confuse a lot of players.  Can you imagine needing to do whole overhauls on them, and place little parts on them you can barely see?  Not a good idea.
