### ISSUE TITLE
MTS's Glass render works on vehicle "parts", but not part "Parts"

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#438]
The windows seem to be rendering the whole of the vehicle texture rather than glass
Part type: Custom
Name: $windowR, $windowL
useVehicleTexture : true

![2020-05-23_18 50 41](https://user-images.githubusercontent.com/63666200/82746091-e2659f80-9d40-11ea-855a-08dc8aaec675.png)

**Comment by DonBruce64** [comment]
Yup, that's a bug all right.

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
