### ISSUE TITLE
Area around the crosshairs gets glitchy when in a vehicle

### ISSUE THREAD

**Issue by SanjivanM** [DonBruce64/MinecraftTransportSimulator#439]
This doesn't happen when using just MTS, so I suspect it's a mod which draws near the crosshairs?

I don't currently have a screenshot of the bug, it's on another computer.  I'll put that up ASAP, I just wanted to get this up here.

Here's an approximate paint . net render of what it looks like, an area around the crosshairs gets inverted: Not really a huge annoyance, it just looks wacky
![2020-05-26_10 41 52](https://user-images.githubusercontent.com/33943333/82932814-dabf1a00-9f3d-11ea-8274-654a70edb2ed.png)
The area was ~1 square inch on the computer I usually play on (24" monitor)

Tested with these mods, saw no issue:
[mods.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4684030/mods.txt)

Here's the list of mods I usually play with (NOTE: The mods prefixed "SM" may not be released yet, those are ones that I've made)
[mods.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4684052/mods.txt)

**Comment by SanjivanM** [comment]
OK, took a little while longer than expected, but here's the actual screenshot
![2020-05-25_22 33 46](https://user-images.githubusercontent.com/33943333/83053269-559f3800-a005-11ea-92a2-817bbd3b8cd7.png)
The mods used in this one are the second "mods.txt"

**Comment by DonBruce64** [comment]
Question: if you go into the P-key config menu, and turn off the HUD so nothing renders, does the issue go away?  Does this also happen in third-person?

**Comment by SanjivanM** [comment]
Yeah, but in 3rd person, the crosshairs aren't visible, so there's no glitched area.  I assume it's something interfering with the crosshair drawing methods, either in MTS of some other mod

**Comment by DonBruce64** [comment]
Fair enough.  Did you try turning off the HUD?  Also, have you tried without any instruments in the HUD?  Need to isolate what part of MTS's rendering causes this issue.

**Comment by SanjivanM** [comment]
I don't think I've tried turning off the HUD, here's the options that I've tried (individually).  This happens with instruments and without instruments.
![2020-05-28_14 20 33](https://user-images.githubusercontent.com/33943333/83216453-26c8b500-a11e-11ea-88be-72169b50b9b2.png)
![2020-05-28_14 20 57](https://user-images.githubusercontent.com/33943333/83216468-32b47700-a11e-11ea-9e68-01dc319ab48d.png)

**Comment by DonBruce64** [comment]
Okay?  So what are the results of those options being set or un-set?

**Comment by SanjivanM** [comment]
They still gave the same glitchy area.  Should've mentioned that, sorry

**Comment by DonBruce64** [comment]
What if both are set?  If you don't render the HUD and make it transparent?

**Comment by SanjivanM** [comment]
I haven't tested that yet, I'll test and report tomorrow

**Comment by SanjivanM** [comment]
Both set to not display/transparent HUD:
![2020-05-29_14 49 38](https://user-images.githubusercontent.com/33943333/83311451-21be4100-a1c4-11ea-8ce3-a7cc73bae3fa.png)
![2020-05-29_14 49 42](https://user-images.githubusercontent.com/33943333/83311455-24b93180-a1c4-11ea-8d5b-2481969e337b.png)

Also, this only occurs when you are in command of/ driving a vehicle:
![2020-05-29_14 48 49](https://user-images.githubusercontent.com/33943333/83311487-41556980-a1c4-11ea-8536-415a924db3fe.png)
![2020-05-29_14 48 45](https://user-images.githubusercontent.com/33943333/83311496-461a1d80-a1c4-11ea-8126-e8cd5da23329.png)

**Comment by DonBruce64** [comment]
Interesting.  So not rendering the HUD makes the issue go away.  If you go into a vehicle, and set renderHud to true, but transp to true, what happens?

**Comment by SanjivanM** [comment]
Starting with HUD off/ transp. off, outside a vehicle, entering it, then setting them to true still causes the glitch.  Turning transparency off doesn't fix it; however, not rendering the HUD doesn't cause the glitch.

**Comment by DonBruce64** [comment]
Okay, now you're confusing me. Can you tell me what happens in these cases:

1. HUD rendering off, transparency off.
2. HUD rendering on, transparency off.
3. HUD rendering off, transparency on.
4. HUD rendering on, transparency on.
5. HUD rendering on, transparency on, and with instruments in the HUD.
6. HUD rendering on, transparency on, and with out instruments in the HUD.

I don't care about you being in a seat that doesn't bring up the HUD, as I know it's something in the HUD that's causing this.  But I need all permutations of the configs tested. I need to know which condition causes this to happen to try to make a fix.

**Comment by SanjivanM** [comment]
HUD rendering off, transparency off. > > > > > > > > > > > > > > > > > > > No glitch
HUD rendering on, transparency off.  > > > > > > > > > > > > > > > > > > > glitch
HUD rendering off, transparency on.  > > > > > > > > > > > > > > > > > > > No glitch
HUD rendering on, transparency on. > > > > > > > > > > > > > > > > > > > > glitch
HUD rendering on, transparency on, and with instruments in the HUD.  > > > glitch
HUD rendering on, transparency on, and with out instruments in the HUD.  > glitch

Where "glitch" is the inverted (64*64 pixel) area centered on the crosshairs

**Comment by DonBruce64** [comment]
Now this, this I should be able to fix.  I'm not sure why having the HUD render with transparency causes the glitch, as that prevents all rendering entirely if you don't have instruments.  It must be something I set to render the HUD background itself that's causing this error.  One last question set:

HUD rendering **off**, transparency on, and with instruments in the HUD. 
HUD rendering **off**, transparency on, and with out instruments in the HUD.

**Comment by SanjivanM** [comment]
HUD rendering off, transparency on, and with instruments in the HUD. ======= No glitch
HUD rendering off, transparency on, and with out instruments in the HUD. === No glitch

**Comment by DonBruce64** [comment]
Okay, was not expecting this, as I do texture rendering for instruments.  I must set something when rendering the HUD that I don't un-set later...

**Comment by DonBruce64** [comment]
You know, I think I may know what's going on.  I think I might be messing with the alpha settings and leaving them disabled so MC doesn't make the whole crosshair texture bits transparent.  Can you tell me if this works for you?  It's an experimental version, so make sure to backup your world before using.
[Immersive Vehicles-1.12.2-18.3.0.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4835035/Immersive.Vehicles-1.12.2-18.3.0.zip)

**Comment by SanjivanM** [comment]
Yep, that fixed the issue!

**Comment by DonBruce64** [comment]
Nice!  I had a few odd issues with the HUD when re-doing the instruments and found some "dirty" OpenAL states, so good to see that's taken care of them.  Will mark this as closed when I drop the release, but feel free to hang on to that one as mostly everything in there is final.  Only exception is the plane physics, so if you aren't about to go flying that should be fine.

**Comment by SanjivanM** [comment]
ok, thanks!

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
