### ISSUE TITLE
Joystick input 

### ISSUE THREAD

**Issue by FightingPickles** [DonBruce64/MinecraftTransportSimulator#440]
When two people are in an aircraft and one is using a joystick the other has no control over anything that the joystick sends constant input for (rudder, throttle, etc)  the control surfaces can be seen slightly jittering as if the keyboard player is trying to move them but losing to the joystick faster input. Suggest adding a "release controls" button. Also when a joystick is unplugged the game still registers it as plugged in requiring keyboard override be turned off. (unplugging only tested on osx so not sure if mod issue or osx handling of USB devices)

**Comment by DonBruce64** [comment]
I only address one issue per ticket.  For this ticket, I'm choosing to address the bug as that's something more people have complained about.

**Comment by DonBruce64** [comment]
Changed my mind.  Going to address the dual-control, as I already have a second ticket for the blocking for missing sticks.

**Comment by DonBruce64** [comment]
Implemented in V18.4.0.
