### ISSUE TITLE
Turn_indicator does not work on "car" type vehicles

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#441]
I forgot to put in a ticket for this the other day, so i'm just now putting one in.

As the name of this ticket suggests, the animation type Turn_Indicator does not work gauges/instruments, or animated parts when this animation type is used on "car" type vehicles.

**Comment by DonBruce64** [comment]
That's more of a design oversight on my part than a bug, but will fix.

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
