### ISSUE TITLE
Suggestion: Way to entirely prevent cranking sounds from changing pitch.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#444]
Mainly intending to use this on large turboprops that are designed to only play their cranking sound once, but also use enough battery to make the pitch go down a bit before it starts. Alternatively an actual 24-volt option for the electrical could be added, but that seems more complicated.

**Comment by DonBruce64** [comment]
This sounds like the cutoff for low battery needs to be adjusted, or electrical usage needs to be tweaked, as there's already an option to prevent pitch from changing.

**Comment by fsendventd** [comment]
Hence the "entirely". The current one isn't entirely.

**Comment by DonBruce64** [comment]
Going to leave this here as something for a PR, seeing as how the sound code has already been messed with once via a PR.

**Comment by fsendventd** [comment]
> 
> 
> Going to leave this here as something for a PR, seeing as how the sound code has already been messed with once via a PR.

Oooookay.... I guess I'll be throwing myself into the sound code, since I can't release until it's fixed.
