### ISSUE TITLE
Crash on Aerwhale Crash

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#445]
What it says on the tin. When the blimp dies, so too dies the server. 
[crash-2020-05-22_04.58.38-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4713878/crash-2020-05-22_04.58.38-server.txt)

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
