### ISSUE TITLE
[Suggestion: Jack (car lift)] 

### ISSUE THREAD

**Issue by FranklinMCA** [DonBruce64/MinecraftTransportSimulator#446]
This just an idea and the pack should need this for car mechanic. A functional car lift, there is an example pic under. 
![HTB1rdWyX7fb_uJkSmRyq6zWxVXaB jpg_350x350](https://user-images.githubusercontent.com/58149488/83514245-8e428400-a4d3-11ea-832d-2140f1f48139.jpg)

**Comment by DonBruce64** [comment]
Not going to happen.  There are far too many car shapes and sizes to make a lift like that work.  Not to mention the lift is pretty useless unless you can drive the car onto it.  And if you can drive the car, there's no reason for a lift in the first place.
