### ISSUE TITLE
[BUG?] You can attempt to put the car in gear... while it's already in gear?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#447]
When an automatic engine is in Drive, you can drive forward like normal, and you won't be able to shift into gear since you're _already_ in gear... until you get into anything higher than first gear.
After the car automatically shifts up, the driver can spam the ShiftUp control which momentarily puts the car into first gear, and then back into the automatically chosen gear! 
This can't be good for engines, transmissions, or the shifter itself...

**Comment by DonBruce64** [comment]
Yup, that's a bug all right.  But an odd one.

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
