### ISSUE TITLE
[Suggestion] Potential for OreDict support in vehicle/part crafting?

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#449]
This has been creating a huge issue in large modpacks with a lot of different ways to make the same thing, sometimes you don't get (for example) the flavor of steel that you need to make an UNU vehicle. Possible?

**Comment by DonBruce64** [comment]
If you can figure out how OreDict works in 1.12.2 and 1.15.X and get it put into a WrapperOreDict class so I don't touch any OreDict classes in the main code, then yes.  Otherwise, I ain't touching the Forge jank.  I already have enough issues with their regular janky systems.

**Comment by SanjivanM** [comment]
My solution is to use an OreDictionary converter mod, specifically this one.  It can be configured to convert specified OreDict entries too

link: https://github.com/Brycey92/OreDictionaryConverter/releases/

**Comment by DonBruce64** [comment]
Nope.  I'm not going to pull in a mod to use a core feature of Forge/MC.  Try again.

**Comment by DonBruce64** [comment]
So, it turns out OreDict is gone as of 1.13+.  Don't want to try to support a system that's not work-able in future MC-versions, so I'm going to have to flag this as a wontdo as it's not a good idea to lock the code into a specific system that Forge sees fit to not maintain.
