### ISSUE TITLE
Request: Roads

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#45]
Roads in MTS would solve the big problem of vehicles not being able to go up slopes. However, they could also add some cool new functionality.

If roads were set up like tracks in IR, where you had a menu such as number of lanes, 1-way vs 2-way, lane width etc., then you could make NPC vehicles.

You could even implement sign functionality. If you have a speed limit sign, the vehicles will drive that fast (could also be set in the menu). Intersection roads would make it easier to set up traffic lights. You set up the intersection in the menu (lanes of each crossroad and signal timing), then it could link to any poles attached to each corner and subsequently each signal on said pole.

**Comment by DonBruce64** [comment]
While I agree that roads would be nice, they are NOT a fix for the shoddy slope code in MTS right now.  That needs to be fixed well enough that vehicles are able to go up and down blocks without spinning their wheels.

If I do implement roads, I'd like to do so in a dynamic form, where you'd simply put down markers of some sort to indicate to MTS what road is what and then NPCs would be able to follow them.  Stripe blocks seem like a good option, as they'd allow for a freeform road that NPCs could easily be programmed to follow.

All said, however, this is a long way off unless I get someone to help with the code.  To get this feature I'll need to add a whole road-following system to an NPC that I don't even have yet.

**Comment by DonBruce64** [comment]
New developments have made me finally decide to not implement roads in MTS.  The primary reason is that Flenix of the Flenix'sRoads mod is re-making his mod, which does roads far better than what I have time to do.  Considering that he has his full dev time to work on roads, I'd rather not split some of mine off of vehicle systems to try to do something that someone else is already doing quite well.  That's just a way to not get new vehicles in.
