### ISSUE TITLE
[Suggestion: SpeedCam]

### ISSUE THREAD

**Issue by FranklinMCA** [DonBruce64/MinecraftTransportSimulator#451]
![traffipax-onroad-2](https://user-images.githubusercontent.com/58149488/83977668-9733bb00-a902-11ea-92bf-e8b93030dac2.jpg)

Its very useful for rp servers.

**Comment by DonBruce64** [comment]
Yup, that's a camera.  But how on earth is it supposed to work?

**Comment by FranklinMCA** [comment]
The camera would check the speed of the cars, and if the speed of a car is higher than allowed, it would take a picture and the player would be fined. For taking money should use Flex's Small Money Mod.

**Comment by FranklinMCA** [comment]
A player needs the permission to put and set up the cam's speed or something.

**Comment by DonBruce64** [comment]
Not going to do this.  You're asking for MTS to require another mod to use this item, plus you can't just "take a picture" in Minecraft.  This is one of those things that sounds like a good idea, but is far harder than you realize.
