### ISSUE TITLE
Divide by zero error

### ISSUE THREAD

**Issue by FightingPickles** [DonBruce64/MinecraftTransportSimulator#455]
Kinda lost control of a plane, and it (nearly?) inverted, game crashed with divide by zero error almost immediately after. Not able to reliably reproduce.
[crash-2020-05-26_14.16.17-client (1).txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4756344/crash-2020-05-26_14.16.17-client.1.txt)

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
