### ISSUE TITLE
Fuel Configuration Doesn't Exist

### ISSUE THREAD

**Issue by Kokokorii** [DonBruce64/MinecraftTransportSimulator#457]
Error and crash log attached. 

The mod had been functioning perfectly with the creative/fueless engines. However, no matter what kind of fuel I use, trying to start a car with a gasoline engine causes the game to crash with an unknown error.

After this when I try to load the world it gives the error attached below.

Do I need to configure the type of fuel I'm using before loading the world? If so, how to I access the config file?
![Error](https://user-images.githubusercontent.com/66892694/84583107-e8402500-adc2-11ea-8510-1fb699e0c4e1.PNG)
[crash-2020-06-13_22.04.50-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4775764/crash-2020-06-13_22.04.50-server.txt)

**Comment by DonBruce64** [comment]
You're running an outdated version of MTS that doesn't generate configs correctly.  This bug has since been patched.  See issue #281

**Comment by DonBruce64** [comment]
Apparently un-fixed.

**Comment by DonBruce64** [comment]
Appears to be fixed after all?
