### ISSUE TITLE
Game crashed when I teleported to the location near flying plane

### ISSUE THREAD

**Issue by Faelris** [DonBruce64/MinecraftTransportSimulator#459]
Hi!
My friend was flying a plane. I teleported (/tppos) to a position on the ground near him and my game crashed due "The game crashed whilst ticking entity". The friend didn't get that error though.
Here's the crash-log: 
[crash-2020-06-16_15_39_05-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/4786736/crash-2020-06-16_15_39_05-client.txt)

**Comment by DonBruce64** [comment]
Yup, that's a bug on my end.  Will fix.

**Comment by DonBruce64** [comment]
Should be fixed in V18.3.0.
