### ISSUE TITLE
[BUG] If you hold shift while right clicking a seat, you gain telepathy and float.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#461]
Basically if you hold shift and enter a seat, Steve seems to dismount before he mounts.
This results in him floating in mid-air, and he can move around (though slowly, and he can't go up or down.)
The only way to rid yourself of the curse of no gravity is to hop into a seat normally again.

(I'm not sure if it's actually because MTS dismounts you before you mount, but something's going wrong for sure)

Additional notes are that you're _extremely_ slow, are in the sitting animation during all of this, and shifting in mid air doesn't do anything.

**Comment by DonBruce64** [comment]
Can confirm.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V18.3.0.
