### ISSUE TITLE
[Sugggestion/Idea: Car breakage]

### ISSUE THREAD

**Issue by FranklinMCA** [DonBruce64/MinecraftTransportSimulator#465]
Will u add this in the future? It will be more realistic. Are you planning to do this?

Example:
![Glendale-GTASA-beater-front](https://user-images.githubusercontent.com/58149488/85226212-af153f80-b3d6-11ea-9670-d903d7c057ed.jpg)

**Comment by RishiMenon2004** [comment]
That is highly unlikely, it requires (to my knowledge) crumble physics. Which if you know about how screwed up forge is right now, it's not the easiest thing to do. But I might be wrong, so I'll let THE MAN handle this

**Comment by DonBruce64** [comment]
You are correct.  I am not doing vehicle damage models.  For one, it's horrid for pack authors to do as most of their models are made of single large shapes, not multiple small shapes that can deform.  For another, it's a TON of math and collision checks, and requires someone who can spend days coding such a system.  i.e. NOT me.
