### ISSUE TITLE
[Request] Drift physics

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#47]
Pull handbrake, turn wheel, drift.

I'd vastly prefer Carbon/World/UG2 style as opposed to the ridiculous arcade-like drifting of the Iceberg engine. If at all possible, I'd like to be able to come at a hard turn or spot a mountain up ahead and simply pull handbrake and normal brakes, turn wheel, and then accelerate and steer opposite out of the drift, or something similar - more realistic is better.

We can burnout, how come we can't drift? :P

**Comment by DonBruce64** [comment]
The problem with drifting is that it's a whole nother system to get the vehicle to turn like that.  During normal driving, and all other maneuvers except drifting, a vehicle will turn on it's rear axle while the front wheels move in an arc.  All of the MTS physics systems, and even the center point of the models, are set to do this.  Implementing a drift system would require re-tooling the rendering code to dynamically change the render rotation point.  Re-doing the physics code to allow for rotation on the front wheels.  And re-doing the JSON to define this new front turn point.  All in all, it's a whole lot of work for a feature that only appeals to a limited segment.  If someone else wants to submit a Pull Request for this, I'll be happy to review, but I'm not doing this myself.
