### ISSUE TITLE
Turn Signal/Headlights Keybinds Request

### ISSUE THREAD

**Issue by bobgrey1997** [DonBruce64/MinecraftTransportSimulator#474]
As it currently is, turn signals are either operated automatically when you begin turning the vehicle, or manually in the control panel. Headlights are only operated manually in this panel.
In reality, turn signals are operated manually before turning the vehicle (usually while the vehicle is in motion). Operating the control panel while in motion is similar to letting go of the wheel as you do not have control over the vehicle's movement. As such, these features should be able to be operated via keybinds while driving. However, many players may not have enough available keys to bind, so these features should still remain in the control panel as an optional method of operating them.
Personally, I'd set my signals keybinds as Q and E for left and right, respectively, and headlights as L (this is a familiar setting for me from American Truck Simulator, as this how I have it set up on there as well), while rebinding Inventory and Drop to I and (probably Del), respectively. However, these are quite essential keys for most players who do not change them. As such, I'd suggest not having a default keybind at all, but rather leave it unbinded. This would make it so the only method of operating these features manually is via the Control Panel by default, until the player binds them manually.
[EDIT]
IF a default _has_ to be set (due to some kind of code limitation or something), I'd suggest numpad keys (4, 5, and 6; for left signal, headlight, and right signal, respectively) are as good as any. I don't believe they have uses in vanilla by default.

**Comment by RishiMenon2004** [comment]
Um, laptops don't have numpads, most of the time. So I suggest [ ], as defaults maybe. Headlights using L will have a conflict with minecraft advancements button.

**Comment by DonBruce64** [comment]
Eh, I could care less about the advancements colliding.  L is commonly used in games, so MC can just have the advancement key re-bound.  And since numpad is a default and won't collide, I feel it's a good one to have for a feature most people won't use.  Will use the 456 keyset and have this in the next release.

**Comment by fsendventd** [comment]
...can you really not control the cars when you're in the panel? I find that I can still drive just fine with it up, and fly for that matter.

**Comment by RishiMenon2004** [comment]
> Eh, I could care less about the advancements colliding. L is commonly used in games, so MC can just have the advancement key re-bound. And since numpad is a default and won't collide, I feel it's a good one to have for a feature most people won't use. Will use the 456 keyset and have this in the next release.

_But..., laptops with no numpads_

**Comment by DonBruce64** [comment]
Well, then just re-bind the keys to a non-numpad.  It ain't that hard, and the whole point is to make it so the keys aren't in a spot that's commonly-bound, but allow for players to bind the keys, should they wish.  That's the whole point of having variable keybinds.

**Comment by DonBruce64** [comment]
Implemented in V18.4.0.
