### ISSUE TITLE
Suggestion: Add the config option to completely disable the "glass textures" on the vehicles.

### ISSUE THREAD

**Issue by rundownturner4** [DonBruce64/MinecraftTransportSimulator#475]
I really like the IV vehicle models, i think they are really well made but i'm personally not such a huge fan of the "glass window textures" that are present on most of the vehicle models. So i propose adding the option to completely disable the "glass textures" on all of the vehicles in the config file, for those that don't want them. There is already an option in the config file to disable the rendering of the glass window textures from the inside of the vehicles, so it wouldn't be a massive pain in the back to also add a config option for completely disabling the glass textures on all vehicles.

**Comment by DonBruce64** [comment]
Implemented in V18.4.0.
