### ISSUE TITLE
[BUG] Engines seem to have less power than before

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#479]
I was testing my car for a PR I was doing, when I realised that my car didn't seem to go faster than 20 km/h, when it used to hit 60km/h. I think @NightScale5755 can vouch too, https://discordapp.com/channels/232316230852280320/407041732988108810/729131341978796032. @fsendventd as well

**Comment by fsendventd** [comment]
To be specific, car engines don't have nearly the same amount of power as before. Planes seem fine. However, the flaps are weird, but that's for another issue.

**Comment by boot2big** [comment]
Can confirm, downloading directly from Curse without fucking with anything seems to have messed up vehicle engines.

**Comment by DonBruce64** [comment]
This should be easy to fix, as I didn't change too much between 18.3.0 and 18.4.0.

**Comment by RishiMenon2004** [comment]
So this issue can be closed now right?

**Comment by DonBruce64** [comment]
Doesn't get closed till the release is dropped.  Otherwise folks will just put in another ticket.

**Comment by RishiMenon2004** [comment]
ah ok

**Comment by DonBruce64** [comment]
Fixed in V18.5.0.
