### ISSUE TITLE
(Bug) In MTS versions 18.3 and above, flaps provide a ton of lift.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#480]
Like, way too much lift. At least twice as much as they did before. I got planes flying at 5 m/s using full flaps (Comanche), but they behaved roughly the same as in older versions with no flaps. Something's off.

**Comment by fsendventd** [comment]
...I want to update this, vehicles seem to have more lift in general in the newer versions. 18.4 for sure, haven't tested 18.3 yet, but they do land rather easily compared to how they were before. Though flaps do seem to increase the already-too-high lift by a larger percentage than they did.

**Comment by DonBruce64** [comment]
If you're able to pinpoint which version, it'll allow me to do a pre-post on the physics formulas to see if I have bad maths somewheres.

**Comment by DonBruce64** [comment]
Fixed in V18.5.0.
