### ISSUE TITLE
(Bug) Current documentation in handbook for wheels doesn't match code.

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#481]
What it says on the tin. As far as I can tell, we're still using types of "wheel" and "pontoon" and "tread", instead of "ground_wheel" and such like the handbook says. Been trying with the new system for a while and it refuses to register my wheels.

**Comment by DonBruce64** [comment]
What version are you using?  I thought I patched the ground_ prefix issue in V18.4.0?

**Comment by fsendventd** [comment]
I'm on V18.4.0, and it doesn't seem to work. The one wheel I left as ground_wheel for testing still doesn't load. Is it perhaps because I have it as ground_wheel_ul (for ultralight, it's a super tiny wheel) instead of just ground_wheel?

**Comment by DonBruce64** [comment]
Fixed in V18.5.0.
