### ISSUE TITLE
Hard-to-control vehicle clumbing system.

### ISSUE THREAD

**Issue by RyabchikPtichka** [DonBruce64/MinecraftTransportSimulator#484]
Hello, friends. Sorry for my strange request.
Can I configurate the physics of transport collisions and reduce the distance between climbing? For example, a car needs to pass five blocks in order to step higher and not crash. It is possible to get the same effect, but at a distance of, for example, two blocks?

**Comment by DonBruce64** [comment]
You can, but such climbing is not related to the physics.  Rather, it is related to the vehicle model itself, and how the pack author decides to add collision boxes.  If they make a lot of low ones, then the vehicle will perform poorly on hills.  If they make them higher, it will practically drive up walls.  Nothing much you can do about it except ask the authors to fix it.  I dislike sports cars that blow up when you hit a wood slab as much as the next guy...
