### ISSUE TITLE
[PACKARD] Gauge defies expectations and becomes another gauge while still functioning as its own gauge... sort of

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#486]
Oh my, that's quite a big label for such a small tin!

https://youtu.be/ZsTi08MkdTY

**Comment by DonBruce64** [comment]
This is due to the gauge not clamping.  I suspect it's on the OCP side, so flagging it as a packard, but it might be core code.  Will find out when I get around to updating the OCP.

**Comment by DonBruce64** [comment]
Fixed in V17 of the OCP.
