### ISSUE TITLE
[ENHANCEMENT] Boolean dependent part installation

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#487]
So basically what it should be doing is, it checks if a certain condition, in our case, it checks if a part has been installed then we can install only one type of part, but if it hasn't then we can install only another type of part. For example (From Oskar) : Installing a wider wheel when a wide fender is installed, but a normal wheel when it is not. Just an idea for customisation from Oskar, decided to ticket it for future, if it can't be done now.

**Comment by DonBruce64** [comment]
What you're asking for here is additionalParts, or customParts that have specific subParts.  Both can currently be used to do what you want.
