### ISSUE TITLE
Immersive Vehicles pitch-bends vanilla & modded sound effects based on player's Y velocity

### ISSUE THREAD

**Issue by floral-qua-floral** [DonBruce64/MinecraftTransportSimulator#488]
When Immersive Vehicles is present, certain sound effects from vanilla (and other mods) will be pitch-bent according to the player's Y velocity.

How to reproduce:
1. Set up a clean modpack environment with Forge 1.12.2 and Immersive Vehicles.
2. Enter a world in Creative mode (Survival also works, but it's much faster to test in Creative)
3. Fly up at least 30-40 blocks and give yourself a snowball.
4. While holding right-click to continually throw the snow, stop flying and fall back to the ground. The pitch of the throwing sound effect will drop as you accelerate downwards, and once you hit the ground again the pitch will return to normal.

The issue can also be observed on sounds such as glass shattering, with precise timing and a keen ear, but snowballs are much more reliable to test the problem with.

When mods such as Dynamic Surroundings are present, the issue becomes significantly more bothersome, as it affects sound effects from that mod as well - this is especially noticeable with sound effects that persist for a longer period of time than snowball throws, such as the sound that plays when you draw a sword. Sound effects that are long enough will even pitch-bend in real time as your velocity changes, which can cause extremely awkward-sounding distortion if a player is, for instance, jumping or taking knockback, which will cause the pitch to change rapidly as the player moves up and down.

From my testing, it appears that the issue affects all versions from [IV 17.4.0](https://www.curseforge.com/minecraft/mc-mods/minecraft-transport-simulator/files/2916893) and onwards. It does not affect [IV 17.3.1](https://www.curseforge.com/minecraft/mc-mods/minecraft-transport-simulator/files/2910917) or earlier.

**Comment by fsendventd** [comment]
I mean, this is *technically* realistic. If you throw a snowball and then fall away from the flying snowball, the whoosh will be Doppler shifted. But then when you hit the ground, you aren't moving relative to the snowball anymore. Though it's definitely interesting that it only happens with this mod installed... 

Did you test without Dynamic Surroundings? Last I checked it adds Doppler shifting effects to basically every sound.

**Comment by floral-qua-floral** [comment]
Even if it's realistic, it's definitely outside the scope of this mod to be altering the vanilla & modded sounds play so dramatically without any config. And it certainly doesn't feel realistic in terms of the sword sounds from DS warbling in pitch as you jump.

I have tested without DS, that's what the How To Reproduce section describes. The only mod that is necessary to reproduce the behaviour is Immersive Vehicles itself, you don't even need any vehicle packs.

**Comment by DonBruce64** [comment]
That's a fair point.  I'll look into this and try to isolate the doppler effects to MTS-only.  This will be hard, however, as the doppler code is normally handled in the main OpenAL sound system, which does all the heavy-lifting for it.  If I disable this, I'll have to re-code all the doppler formulas myself.   Really, MC should work with doppler stuff out of the box, but perhaps there's a reason why it doesn't and this is just such a reason.

**Comment by DonBruce64** [comment]
That makes sense.  Doppler is based on speed, and you can pick it up easier by falling.

**Comment by DonBruce64** [comment]
Corrected in V19.0.0.  The only sounds that have doppler now are IV sounds, and their doppler isn't as sensitive to Y-velocity changes anymore.
