### ISSUE TITLE
[BUG] Cruise Control becomes useless when throttle is controlled by a joystick.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#489]
At first, I thought CC was just borked, but upon removing my joystick assignments to Gas, it worked.

**Comment by DonBruce64** [comment]
Hrm, that makes sense, as the vehicle is setting the throttle to one position, and the JS is setting it to another.  Still, I should be able to fix that.  Only issue is getting it working so you can still press the gas with CC on, but not drop below the CC speed.

**Comment by DonBruce64** [comment]
Fixed in V18.5.0.
