### ISSUE TITLE
[Request] Separate parts for car shells (Please hear me out)

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#49]
As opposed to the car body being 1 model, have the car chassis have hardpoints for fenders, hoods, hood, frame, etc. - they all spawn instantly when the car is spawned, but can be damaged separately and even broken off/replaced with a freshly crafted part.
This would indirectly, enable pack authors to create aftermarket parts for their cars, or even others' cars, such as an aftermarket skirt or wide body kit. It would also allow directional damage - cars whose front half was damaged, would display the damage on only that side.

**Comment by DonBruce64** [comment]
What you are asking for is essentially what the Custom part type is for.  The only difference here is that you wish for the parts to come spawned with the vehicle.  This, however, is not what MTS is designed for.  The code of MTS is made to allow you to build up your vehicle like how you do a house in MC, not to give you a complete vehicle of the pack author's choosing.

If pack authors wish to start making parts in the aftermarket business, I suggest they standardize like how the have done with bumper stickers in Dr. Professor Luigi's packs.  This way pack makers can have cross-compatible parts from different packs.  I would think spoilers are one such area that can be easily standardized to fit multiple vehicles...
