### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by cgiigc** [DonBruce64/MinecraftTransportSimulator#490]
How do you destroy a vehicle?

And how do you pick up a part?

**Comment by boot2big** [comment]
Get a wrench from the MTS core creative menu.

You can destroy a vehicle by holding shift, and left clicking a vehicle.


Likewise, you can simply left click a part (wheel, seat, engine) without holding shift to remove a part.

**Comment by boot2big** [comment]
For future reference and questions, it may be advised to read the ingame manual. @cgiigc
![image](https://user-images.githubusercontent.com/53581325/87254209-d3e95980-c44e-11ea-8364-4db3a3347e28.png)
![image](https://user-images.githubusercontent.com/53581325/87254218-e6639300-c44e-11ea-95a5-1ce48c4e8d8a.png)
