### ISSUE TITLE
[BUG?] Strange reverse beeper behavior

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#491]
When a vehicle is put into reverse while running, then turned off, the beeper keeps beeping.
But if a vehicle is turned off, _then_ put into reverse, it doesn't beep.

If a vehicle in reverse and beeping is picked up, it won't be beeping when placed down.

(applies to bigTruck)

**Comment by DonBruce64** [comment]
Fixed in V19.1.0.
