### ISSUE TITLE
Odometer.

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#492]
Simple. Add an odometer instrument, that shows engine runtime hours.

**Comment by DonBruce64** [comment]
I'll add the hours variable, but it's up to the pack folks to implement the instrument itself.

**Comment by SanjivanM** [comment]
Umm... odometers measure travelled distance, not engine hours (https://en.wikipedia.org/wiki/Odometer)

**Comment by DonBruce64** [comment]
We know this, but on the Discord we discussed that hours are more important as they affect the vehicle.

**Comment by SanjivanM** [comment]
So a gauge rather than holding the engine in your hand?

**Comment by boot2big** [comment]
Would certainly be more convenient to know you've fucked up while still moving rather than pulling over or landing, then wrenching an engine or three. Also, it'd look really cool.

**Comment by DonBruce64** [comment]
Added "enigne_hours" variable in V19.2.0.  This allows for the ability of an instrument with pseudo-odometer status.  Now it's up to pack creators to make use of it.
