### ISSUE TITLE
Sliding vehicles / Unknown forces causing vehicles to slide when not moving

### ISSUE THREAD

**Issue by Mrleplayz** [DonBruce64/MinecraftTransportSimulator#494]
Stopping with any kind of vehicle will sometimes result in sliding movement that is really slow, the player might not even notice it.
Vehicles slide and after a few minutes they slide into a wall or off a cliff.

The only way to stop it is to either try and stop the vehicle again ( not sure if it ALWAYS happens ) or to reload the world with the vehicle not moving.

From my experience, it doesn't matter if it's in gear, if the parking brake is on or if the engine is on, it will always slide.

-Cipher ( On Discord )

**Comment by wqsadsddsdf** [comment]
I've solved that issue through driving forward just a bit, turning on parking brake and selecting the N gear.

**Comment by DonBruce64** [comment]
This should be fixed in V19.0.0.  Can anyone confirm?

**Comment by DonBruce64** [comment]
Pinging @DonBruce64 and @wqsadsddsdf prior to closing just in case notifications didn't get sent out.

**Comment by DonBruce64** [comment]
Meant to ping @Mrleplayz , not myself.  Pesky Git...

**Comment by DonBruce64** [comment]
Closing due to no response and assumption the issue doesn't exist in V19.
