### ISSUE TITLE
No Option to Start Vehicle

### ISSUE THREAD

**Issue by KeganATSMC** [DonBruce64/MinecraftTransportSimulator#496]
First off, I Like the fact that a radio has been added but when i go into controls there is No Option to Start the Vehicle even when i add all the parts can someone fix or explain this issue thanks

**Comment by DonBruce64** [comment]
There is an option to start the vehicle.  If you read the in-game manual, or asked anyone on the Discord, or watched the YouTube video on the Curse page, you'd know how.  GitHub is not for asking for mod help.  It's for bugs.

**Comment by KeganATSMC** [comment]
ok thanks
