### ISSUE TITLE
Tickets cannot put NPCs in the car

### ISSUE THREAD

**Issue by letov1934** [DonBruce64/MinecraftTransportSimulator#501]
Tickets do not see NPCs as something alive, because of this they cannot get into the car.

**Comment by DonBruce64** [comment]
Which NPCs?  Cause if you mean villagers, I've tested with them, and can confirm they can be put into cars with tickets.

**Comment by Jimmy805** [comment]
I think NPC he said is NPCs from a mod called CustomNPCs. Actually, I have also done it and I can't bring NPCs to vehicles.

**Comment by DonBruce64** [comment]
Well, you can't click them.  But if you're in the vehicle and right-click the ticket they'll load up.

**Comment by Jimmy805** [comment]
Ok, I will try it when I'm in my free time. Thank you!

**Comment by Woody-0w0** [comment]
Looking forward a compat with CustomNPCs mod!

**Comment by DonBruce64** [comment]
But one already exists.... "But if you're in the vehicle and right-click the ticket they'll load up."

**Comment by Jimmy805** [comment]
Lol. I think he may want you to let them drive cars.

**Comment by DonBruce64** [comment]
Yeah, that ain't gonna happen.  That'd require route planning, which ain't easy to code at all.

**Comment by Jimmy805** [comment]
And it seems to involve artificial intelligence. You know... making NPCs drive realistic vehicles is very difficult because we players sometimes also have to spend some time studying on how to drive them.

**Comment by DonBruce64** [comment]
Closing as tickets don't put NPCs in vehicles by clicking them anymore.  They do this by clicking the vehicle.  Should work with CNPCs now.
