### ISSUE TITLE
Mobs stay in place after taking damage

### ISSUE THREAD

**Issue by letov1934** [DonBruce64/MinecraftTransportSimulator#502]
Mobs stay in place after taking damage. If you put a mob (for example villager) in the car, after taking damage from another mob outside the car, the villager will stay in place and not depend on his seat. Cured by re-entering the world.

**Comment by DonBruce64** [comment]
"the villager will stay in place and not depend on his seat" I don't understand what you mean by this.  Are you saying the villager does not leave his seat?

**Comment by DonBruce64** [comment]
Closing due to no response, and suspected invalidation with V19.0.0 systems.
