### ISSUE TITLE
[ENHANCEMENT] Radio Block

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#503]
What it says in the title, a radio block that uses the radio code for vehicles. Idea by Shady, he thought _Why be so desperate for a radio so that that you have to have a car in your living room?_ and then he said _Hey! MTS already has the radio code so what if that could be used for a block?_ Heh! So um, yeah posting this ticket for him

**Comment by DonBruce64** [comment]
Implemented in V19.1.0.
