### ISSUE TITLE
[BUG] NullPointerException following plane crash causes server crash/ lockup

### ISSUE THREAD

**Issue by KTaylorIII** [DonBruce64/MinecraftTransportSimulator#506]
The plane in question was an Oak MC-172 with the following components:
- Lycoming 0-360 Plane Engine
- Small 2-Bladed Propeller

From the earlier screenshots on Discord, it appears the engine value was set to null before the plane explosion called the explode engine function. Null checks for all vehicle destruction-related functions should be implemented to ignore the null value. Optional<T> is another possibility to eliminate the possibility of null values.

This post will be updated with the crash log once the full crash file is obtained sometime this morning.

EDIT: Sorry for the late update, but I still have yet to receive the log from the server admin. I'll keep this updated

**Comment by DonBruce64** [comment]
Closing due to lack of response, and suspected invalidation of the crash given V19.0.0 system overhauls.
