### ISSUE TITLE
[Suggestion] Load Textures and OBJ objects in subfolders

### ISSUE THREAD

**Issue by Tim3Game** [DonBruce64/MinecraftTransportSimulator#509]
This could help pack makers with organization of textures and objects. The textures/objects would load based on the jsondef file location. For instance, if there would be a `sign_gasstation_price.json` file in the `jsondefs.poles.gasstation` folder, it would firstly try to find the texture in `textures.poles.gasstation` and if it wouldn't find the texture, it would try the default folder `textures.poles`, the same would be for objects.

**Comment by DonBruce64** [comment]
Implemented in 19.4.0.  See the new pack-loading system where you use a JSON file and specify the folder structure.  Handbook section 2.0.
