### ISSUE TITLE
Stuck in vehicle, can't move within it.

### ISSUE THREAD

**Issue by WolfyGamingWorld** [DonBruce64/MinecraftTransportSimulator#510]
When I spawn a vehicle, I can move freely, but when I go somewhere and completely stop it, I keep glitching inside the vehicle and can't move or move very slowly.
The trailer works fine but the main RV doesn't
Bug video: https://streamable.com/k5kt6f

Edit: This happens to all vehicles sometimes.

**Comment by fsendventd** [comment]
This is due to our hitboxes being a little weird sometimes, and it isn't something that I think we can fix. There are some big changes coming with the next update, though, and one of them could help it a bit.

**Comment by DonBruce64** [comment]
I'm closing this, as I've done all I can do with the hitboxes on my end in V19.0.0.  The rest is up to pack authors to make proper dismounting positions that don't collide with hitboxes.
