### ISSUE TITLE
Can't move while the vehicle is moving, not sure if it's intended.

### ISSUE THREAD

**Issue by WolfyGamingWorld** [DonBruce64/MinecraftTransportSimulator#511]
Bug video: https://streamable.com/plej8c

This happens in every vehicle after the vehicles moves and then stops.

**Comment by fsendventd** [comment]
Looks like something with interior hitboxes, as a lot of people don't properly use them. Also our hitboxes can be a little jittery at times. It's probably normal, not something we can really fix.

**Comment by DonBruce64** [comment]
Actually, I've got that decently fixed in the V19 update.  So once that drops I'll call this fixed.  For now, you'll just have to ride in a seat or stop the vehicle.

**Comment by DonBruce64** [comment]
Just realized this is for the same root cause as #510.  Marking as duplicate.
