### ISSUE TITLE
[BetterPortals] Visual issue when in F5, video link here.

### ISSUE THREAD

**Issue by WolfyGamingWorld** [DonBruce64/MinecraftTransportSimulator#512]
Bug video: https://streamable.com/eminqj

Edit: This happens in every vehicle, and another bug related to this, if a vehicle is placed and I F5, all placed vehicles "move" relative to the camera. When I go back in First Person, it's normal.

**Comment by fsendventd** [comment]
What other mods are you running?

**Comment by WolfyGamingWorld** [comment]
| State  | ID                                           | Version                 | Source                                               | Signature                                |
	|:------ |:-------------------------------------------- |:----------------------- |:---------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft                                    | 1.12.2                  | minecraft.jar                                        | None                                     |
	| LCHIJA | mcp                                          | 9.42                    | minecraft.jar                                        | None                                     |
	| LCHIJA | FML                                          | 8.0.99.99               | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
	| LCHIJA | forge                                        | 14.23.5.2847            | forge-1.12.2-14.23.5.2847.jar                        | None                                     |
	| LCHIJA | creativecoredummy                            | 1.0.0                   | minecraft.jar                                        | None                                     |
	| LCHIJA | micdoodlecore                                |                         | minecraft.jar                                        | None                                     |
	| LCHIJA | com.elytradev.movingworld.common.asm.coremod |                         | minecraft.jar                                        | None                                     |
	| LCHIJA | obfuscate                                    | 0.2.6                   | minecraft.jar                                        | None                                     |
	| LCHIJA | srm-hooks                                    | 1.12.2-1.0.0            | minecraft.jar                                        | None                                     |
	| LCHIJA | securitycraft                                | v1.8.19.3               | [1.12.2]+SecurityCraft+v1.8.19.3.jar                 | None                                     |
	| LCHIJA | forgeendertech                               | 1.12.2-4.5.4.0          | ForgeEndertech-1.12.2-4.5.4.0-build.0534.jar         | None                                     |
	| LCHIJA | adlods                                       | 1.12.2-1.0.8.0          | AdLods-1.12.2-1.0.8.0-build.0504.jar                 | None                                     |
	| LCHIJA | adpother                                     | 1.12.2-1.2.8.0          | AdPother-1.12.2-1.2.8.0-build.0544.jar               | None                                     |
	| LCHIJA | advancedsharing                              | 1.3                     | AdvancedSharing-1.12.2-1.3.jar                       | None                                     |
	| LCHIJA | orbis-lib                                    | 0.2.0                   | orbis-lib-1.12.2-0.2.0+build411.jar                  | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | aether                                       | 0.3.0                   | aether_ii-1.12.2-0.3.0+build411-universal.jar        | db341c083b1b8ce9160a769b569ef6737b3f4cdf |
	| LCHIJA | mts                                          | 18.5.0                  | Immersive+Vehicles-1.12.2-18.5.0.jar                 | None                                     |
	| LCHIJA | mtsaircooled                                 | 1.0.1                   | Air-Cooled+Pack+[MTS]+1.10.2-14.0.0-1.0.1.jar        | None                                     |
	| LCHIJA | backpack                                     | 3.0.2                   | backpack-3.0.2-1.12.2.jar                            | None                                     |
	| LCHIJA | forgelin                                     | 1.8.4                   | Forgelin-1.8.4.jar                                   | None                                     |
	| LCHIJA | betterportals                                | 0.3.7.7                 | betterportals-0.3.7.7.jar                            | None                                     |
	| LCHIJA | bibliocraft                                  | 2.4.5                   | BiblioCraft[v2.4.5][MC1.12.2].jar                    | None                                     |
	| LCHIJA | buildinggadgets                              | 2.8.0                   | BuildingGadgets-2.8.0.jar                            | None                                     |
	| LCHIJA | cdm                                          | 0.4.1                   | cdm-0.4.1-mc1.12.2.jar                               | None                                     |
	| LCHIJA | chameleon                                    | 1.12-4.1.3              | Chameleon-1.12-4.1.3.jar                             | None                                     |
	| LCHIJA | chancecubes                                  | 1.12.2-5.0.2.345        | ChanceCubes-1.12.2-5.0.2.345.jar                     | None                                     |
	| LCHIJA | chiselsandbits                               | 14.33                   | chiselsandbits-14.33.jar                             | None                                     |
	| LCHIJA | classicbar                                   | @VERSION@               | classicbar-0.5.3.jar                                 | None                                     |
	| LCHIJA | extendedrenderer                             | v1.0                    | coroutil-1.12.1-1.2.37.jar                           | None                                     |
	| LCHIJA | coroutil                                     | 1.12.1-1.2.37           | coroutil-1.12.1-1.2.37.jar                           | None                                     |
	| LCHIJA | configmod                                    | v1.0                    | coroutil-1.12.1-1.2.37.jar                           | None                                     |
	| LCHIJA | opframe                                      | 1.4.0                   | OnlinePicFrame_v1.4.40_mc1.12.2.jar                  | None                                     |
	| LCHIJA | playerrevive                                 | 1.0                     | PlayerRevive_v1.2.35_mc1.12.2.jar                    | None                                     |
	| LCHIJA | creativecore                                 | 1.10.0                  | CreativeCore_v1.10.16_mc1.12.2.jar                   | None                                     |
	| LCHIJA | cxlibrary                                    | 1.6.1                   | cxlibrary-1.12.1-1.6.1.jar                           | None                                     |
	| LCHIJA | movingworld                                  | 1.12-6.353              | movingworld-1.12-6.353-full.jar                      | None                                     |
	| LCHIJA | davincisvessels                              | @DVESSELSVER@           | davincisvessels-1.12-6.355-full.jar                  | None                                     |
	| LCHIJA | dimdoors                                     | 1.12.2-3.1.2+UNOFFICIAL | DimensionalDoors-1.12.2-3.1.2-UNOFFICIAL.jar         | None                                     |
	| LCHIJA | dynamictrees                                 | 1.12.2-0.9.8            | DynamicTrees-1.12.2-0.9.8.jar                        | None                                     |
	| LCHIJA | exoticbirds                                  | 1.0                     | Exotic+Birds+1.12.2-3.2.0.jar                        | None                                     |
	| LCHIJA | unuparts                                     | 3.5.0                   | UNU+Parts+Pack+[MTS]+1.12.2-18.0.0-3.5.0.jar         | None                                     |
	| LCHIJA | unuverse                                     | 1.3.0                   | Expanded+UNUverse+Pack+[MTS]+1.12.2-18.0.0-1.3.0.jar | None                                     |
	| LCHIJA | galacticraftcore                             | 4.0.2.280               | GalacticraftCore-1.12.2-4.0.2.280.jar                | None                                     |
	| LCHIJA | extrabitmanipulation                         | 1.12.2-3.4.1            | ExtraBitManipulation-1.12.2-3.4.1.jar                | None                                     |
	| LCHIJA | cfm                                          | 6.3.1                   | furniture-6.3.1-1.12.2.jar                           | None                                     |
	| LCHIJA | galacticraftplanets                          | 4.0.2.280               | Galacticraft-Planets-1.12.2-4.0.2.280.jar            | None                                     |
	| LCHIJA | ivairlinerpack                               | 1.0.0                   | Golden_Airport_Pack_Immersive_Vehicles_2.2.2.jar     | None                                     |
	| LCHIJA | waila                                        | 1.8.26                  | Hwyla-1.8.26-B41_1.12.2.jar                          | None                                     |
	| LCHIJA | icbmclassic                                  | 1.12.2-4.0.1.75         | ICBM-classic-1.12.2-4.0.1b75.jar                     | None                                     |
	| LCHIJA | trackapi                                     | 1.2                     | TrackAPI-1.2.jar                                     | None                                     |
	| LCHIJA | immersiverailroading                         | 1.7.3                   | ImmersiveRailroading-1.7.3_1.12.2.jar                | None                                     |
	| LCHIJA | universalmodcore                             | 1.0.0                   | ImmersiveRailroading-1.7.3_1.12.2.jar                | None                                     |
	| LCHIJA | ironchest                                    | 1.12.2-7.0.67.844       | ironchest-1.12.2-7.0.72.847.jar                      | None                                     |
	| LCHIJA | iv_tpp                                       | 2.0.0                   | IV_Trin_Part_Pack_2.11.0.jar                         | None                                     |
	| LCHIJA | jei                                          | 4.15.0.297              | jei_1.12.2-4.15.0.297.jar                            | None                                     |
	| LCHIJA | liquidspack                                  | 1.0.0                   | Liquid's-Vehicles-Pack-v2.2.jar                      | None                                     |
	| LCHIJA | mtsofficialpack                              | 16.0.0                  | MTS_Official_Pack_V16.jar                            | None                                     |
	| LCHIJA | mai                                          | 1.0.5                   | mackrel_automotive_industries_1.0.5.jar              | None                                     |
	| LCHIJA | malisiscore                                  | 1.12.2-6.5.1-SNAPSHOT   | malisiscore-1.12.2-6.5.1.jar                         | None                                     |
	| LCHIJA | malisisdoors                                 | 1.12.2-7.3.0            | malisisdoors-1.12.2-7.3.0.jar                        | None                                     |
	| LCHIJA | mcwbridges                                   | 1.0.4                   | mcw-bridges-1.0.4-mc1.12.2.jar                       | None                                     |
	| LCHIJA | mcef                                         | 0.9                     | Minecraft-Chromium-Embedded-Framework-1.12.2.jar     | None                                     |
	| LCHIJA | morefurnaces                                 | 1.10.5                  | MoreFurnaces-1.12.2-1.10.6.jar                       | None                                     |
	| LCHIJA | kadwinjpvehicles                             | 2.0.0                   | MTS_Kadwin_JP_Vehicles_Pack.jar                      | None                                     |
	| LCHIJA | mw                                           | 0.4.5.2                 | mw_2.0-0.4.5.2_mc1.12.2.jar                          | None                                     |
	| LCHIJA | packingtape                                  | 0.7.6                   | PackingTape-1.12.2-0.7.6.jar                         | None                                     |
	| LCHIJA | randallag                                    | 1.0.0                   | Randall_AG_v0.5.jar                                  | None                                     |
	| LCHIJA | realistictorches                             | 2.1.1                   | RealisticTorches-1.12.2-2.1.1.jar                    | None                                     |
	| LCHIJA | refinedstorage                               | 1.6.15                  | refinedstorage-1.6.15.jar                            | 57893d5b90a7336e8c63fe1c1e1ce472c3d59578 |
	| LCHIJA | rsgauges                                     | 1.2.4                   | rsgauges-1.12.2-1.2.4.jar                            | ed58ed655893ced6280650866985abcae2bf7559 |
	| LCHIJA | scp                                          | 2.3.1                   | SCP+Lockdown-1.12.2-2.3.1-dev.jar                    | None                                     |
	| LCHIJA | secretroomsmod                               | 5.6.4                   | secretroomsmod-1.12.2-5.6.4.jar                      | None                                     |
	| LCHIJA | sereneseasons                                | 1.2.18                  | SereneSeasons-1.12.2-1.2.18-universal.jar            | None                                     |
	| LCHIJA | sgcraft                                      | 2.0.3                   | SGCraft-2.0.4-bugfix-1.jar                           | None                                     |
	| LCHIJA | simplycats                                   | 1.12.2-0.0.3.1          | simplycats-1.12.2-0.0.3.1.jar                        | None                                     |
	| LCHIJA | storagedrawers                               | 1.12.2-5.4.0            | StorageDrawers-1.12.2-5.4.0.jar                      | None                                     |
	| LCHIJA | storagetech                                  | 6.0                     | StorageTech+R6.0.jar                                 | None                                     |
	| LCHIJA | tinymobfarm                                  | 1.0.5                   | TinyMobFarm-1.12.2-1.0.5.jar                         | None                                     |
	| LCHIJA | torohealthmod                                | 1.12.2-11               | torohealth-1.12.2-11.jar                             | None                                     |
	| LCHIJA | unucivil                                     | 3.5.0                   | UNU+Civilian+Pack+[MTS]+1.12.2-18.0.0-3.5.0.jar      | None                                     |
	| LCHIJA | unumilitary                                  | 3.5.1                   | UNU+Military+Pack+[MTS]+1.12.2-18.0.0-3.5.1.jar      | None                                     |
	| LCHIJA | vehicle                                      | 0.44.1                  | vehicle-mod-0.44.1-1.12.2.jar                        | None                                     |
	| LCHIJA | weather2                                     | 1.12.1-2.6.12           | weather2-1.12.1-2.6.12.jar                           | None                                     |
	| LCHIJA | webdisplays                                  | 1.0                     | Web-Displays-Mod-1.12.2.jar                          | None                                     |
	| LCHIJA | worldedit                                    | 6.1.10                  | worldedit-forge-mc1.12.2-6.1.10-dist.jar             | None                                     |
	| LCHIJA | phosphor-lighting                            | 1.12.2-0.2.6            | phosphor-1.12.2-0.2.6+build50.jar                    | f0387d288626cc2d937daa504e74af570c52a2f1 |
	| LCHIJA | immersiveengineering                         | 0.12-98                 | ImmersiveEngineering-0.12-98.jar                     | None                                     |
	| LCHIJA | midnight                                     | 0.3.5                   | themidnight-0.3.5.jar                                | None                                     |
	| LCHIJA | adchimneys                                   | 1.12.2-3.5.14.0         | AdChimneys-1.12.2-3.5.14.0-build.0505.jar            | None                                     |

**Comment by DonBruce64** [comment]
Oh my....  Well, I can say the root cause is some mod that's mis-representing the location of the camera to MTS.  Likely some rendering mod.  Until you can find out which one, there's not much I can do about it.  I don't think it's Optifine, however, as lots of people run that one, and they don't have this issue.

**Comment by DonBruce64** [comment]
So, I think I may have seen a similar bug when I was doing tests for V19.0.0 systems.  Can you try on this new version and report back if the same thing happens?  @WolfyGamingWorld ?

**Comment by WolfyGamingWorld** [comment]
Yup, just tested and it's still present.

**Comment by WolfyGamingWorld** [comment]
![2020-09-19_13 49 23](https://user-images.githubusercontent.com/54710356/93665418-fb782600-fa7e-11ea-9e5c-245a5624dfe9.png)
Now it's even worse

**Comment by DonBruce64** [comment]
Dang it...  Are you able to isolate it to a specific mod?  I don't know anyone else who has had this problem, so I don't know what to do to re-produce it on my end.  If you start removing mods and can figure out which one makes this happen, I can test with that mod and see how it reacts to changes I make and possibly fix this issue.

**Comment by DonBruce64** [comment]
I had another user with this same issue.  They said it was BetterFPS, but you aren't using that mod, and someone else who had it said they didn't have that issue, so might not be related.  That being said, others are having this issue, so I can confirm it's not a one-time thing.

**Comment by WolfyGamingWorld** [comment]
I have isolated the mod, the bug is caused by BetterPortals v0.3.7.7

**Comment by DonBruce64** [comment]
Interesting.  It would appear another user on Curse has the same issue.  I'll need to do some advanced debugging to fix this.  Putting it on the backburner for now as first-person still works fine, and since it's only BetterPortals, I suspect it's on their end.  Does this happen on other BetterPortals versions?
