### ISSUE TITLE
[Handbook] A more in depth guide to .Json making using the new interfaces

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#514]
While the handbook covers most of the basics for pack making, certain parts may be confusing or not as clear. A updated guide to making .Json could assist in making the process easier for beginners. This updated handbook could include examples of formatting sections, and using the new-ish interface for rotations and whatnot. Furthermore, a video in the style of the earlier blender guides could be done

**Comment by RishiMenon2004** [comment]
Hmm, now that we're bringing code sections in why not just write a github wiki? I mean, all of us could contribute to that, and we wouldn't need to keep downloading the file either. `and this`

**Comment by DonBruce64** [comment]
I like the wiki idea.  Especially since it can be a group project of what y'all know, and I can help fill in any blanks.  The best people to make pack documentation are the folks who make packs!  Closing this ticket with the knowledge that a wiki will be forthcoming.
