### ISSUE TITLE
[BUG] (V19) Creative Engines not shown in the search tab

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#515]
:| what it says in the tile

**Comment by DonBruce64** [comment]
This is indeed a bug, but one that will have to wait for item abstraction.  It appears the MC search system culls items with the same name but different NBT, and the only way for me to get the item to be different is to make another item, and that isn't possible with MTS right now.

**Comment by DonBruce64** [comment]
Fixed in V19.0.0.
