### ISSUE TITLE
[BUG/PACKARD?] (V19) Gauge positions seem to be swapped on Z Axis

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#517]
Seems to affect all vehicles... 
![image](https://user-images.githubusercontent.com/53581325/92774703-bb70bf00-f36b-11ea-8d35-a1d2d6c2b9d4.png)
![image](https://user-images.githubusercontent.com/53581325/92774763-c88dae00-f36b-11ea-996d-fcabab7af140.png)
![image](https://user-images.githubusercontent.com/53581325/92774844-dd6a4180-f36b-11ea-8dbc-bdad991d5580.png)
![image](https://user-images.githubusercontent.com/53581325/92775201-2e7a3580-f36c-11ea-9586-4544515db5d2.png)

**Comment by DonBruce64** [comment]
Noticed this right after the beta build and fixed.  It's not that the Z-axis is swapped, it's that I accidentally used the y axis value for the z-axis.
Oh, and while appreciate the bug documentation, could we keep the V19 bugs on Discord?  I'd prefer the GitHub be the public-facing bug tracker, so having it contain beta build bugs might confuse some people.
