### ISSUE TITLE
[Suggestion] Instruments that use text rendering of variable values

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#519]
This would allow for true digital instruments (airspeed and altitude especially). Particularly useful for making a HUD.

If this is actually feasible I may be able to get it working myself and add via PR.

**Comment by DonBruce64** [comment]
It's possible, but would require some work.  Check the RenderInstruments file, but basically what needs to be done is this:

When you are rendering the instruments, MTS basically just renders all the textures on the instrument sheet, with rotations, translations, and lighting changes.  If you wanted text you'd have to bypass this rendering of textures, render text, and then re-bind the instrument texture for the next run.  I've got a re-bind texture option in the rendering interface that makes this easier, which is what I use on vehicle text, so it's possible for sure.

**Comment by DonBruce64** [comment]
Added in V19.3.0.
