### ISSUE TITLE
Signs settling snow bug

### ISSUE THREAD

**Issue by DrakeBD** [DonBruce64/MinecraftTransportSimulator#52]
![2018-11-28_17 30 26](https://user-images.githubusercontent.com/1292832/49223119-b5e3f800-f3d5-11e8-9af1-d1ea091b3bb9.png)

Snow settling on top of signs looks odd to say the least maybe fix that so snow cant settle on them at all

**Comment by DonBruce64** [comment]
For sure can find a way to fix this.  Snow doesn't appear on ladders, so I should be able to somehow mimic the code.

**Comment by DrakeBD** [comment]
> For sure can find a way to fix this. Snow doesn't appear on ladders, so I should be able to somehow mimic the code.

Thanks for looking into this issue most appreciated

**Comment by DonBruce64** [comment]
For some reason no matter what I do I can't get snow to appear on the signs (or any MTS decor) on my end.  I suspect there's something different between your setup and mine.  For starters I'd say we try ruling out other mods.  Can you duplicate that world and try with just MTS installed and let me know if snow accumulates?
![2018-12-10_19 48 58](https://user-images.githubusercontent.com/15241611/49772984-e1f45880-fcb4-11e8-9b02-3d7c23e713f2.png)

**Comment by DrakeBD** [comment]
@DonBruce64 It could be dynamic surroundings or serene seasons changes to snow that is causing the bug then ill do further testing to nail down the cause and resubmit to the appropriate mod author for compatability fixes

**Comment by DonBruce64** [comment]
@DrakeBD If I get time I'll try it out.  But likely you will get time first.  If that's the case, and if you find out it's another mod causing the conflict, could you let me know?  There may be something in MTS that I can do on my side to make it play better with the conflicting mod.

**Comment by DonBruce64** [comment]
Closing this issue as it's been a month without any response and marking as another mod's fault.
