### ISSUE TITLE
[Bug] (V19) Rotors magically spin in reverse when engine is off

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#521]
Rotors speed up in the reverse direction while on the ground. This makes it take longer for helicopters to start, as the starter must negate this rotation prior to achieving engine start. It also kills players as they leave the helicopter in survival, so that's significant.

This could be prevented by adding a some kind of a braking force to the rotor when the engine is off and the aircraft is on the ground.

Edit: This may or may not be a separate issue, but the rotor seems to destroy items near the helicopter as well. This results in items not dropping if a player is killed by the rotor, as well the vehicle item itself if it is broken with a wrench.

**Comment by DonBruce64** [comment]
Marking as a bug, but closing, as beta build bugs don't belong on GitHub.  Tis fixed anyways, so I can actually close in good faith.
