### ISSUE TITLE
[V19] Cars getting flung to NaN 2 : electric boogaloo  

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#523]
The issue doesn't seem to appear on thinner vehicles, or at least on the scout

On the other hand, the thunderbird still refuses to work and just NaN-s itself at the thought of being sideways

Maybe the cause _might_ be because it's still using moving parts (wheels), but MTS doesn't like it so it gives up since other vehicles haven't had the same buggy behavior

**Comment by DonBruce64** [comment]
Fixed in V19.1.0.
