### ISSUE TITLE
Jumper cables don't work.

### ISSUE THREAD

**Issue by Orvngex** [DonBruce64/MinecraftTransportSimulator#525]
So I just lifted off and my plane's engines suddenly shut off, then I noticed the battery is dead. I bring in my scout to jump it just to see:
"Engines linked. Transmitting power."
Immediately followed by:
"The two engines now have the same battery level. Breaking Link."
I go to see the battery in the plane, which is still dead, and the battery in the scout is full!
Not sure why this happened, not sure if I'm just stupid, but any help would be appreciated! Thanks!

**Comment by DonBruce64** [comment]
Just tried this myself and can 100% confirm jumper cables are borked.  Will fix.

**Comment by Orvngex** [comment]
Thank you, one other thing I would like to mention is that after doing a roll in a plane, looking around becomes really weird, idk why.

**Comment by DonBruce64** [comment]
Rodger that.  I've seen that a couple of times.  Would you be able to put it in a separate ticket so I can track that?

**Comment by DonBruce64** [comment]
Fixed in V19.2.0.
