### ISSUE TITLE
[BUG] Tickets can pick up boss mobs.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#526]
It says it all on the tin, and in the videos on Discord.

(ender dragon, wither, and I presume guardian/elder guardian)

**Comment by DonBruce64** [comment]
Yeah, making a wither your passenger into a base is only fun ONCE.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V19.2.0.
