### ISSUE TITLE
[Bug] Gun pitch mis-calculation

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#528]
If the if an aircraft with guns is pitched down and pointed any direction but north, the gun fires as if the helicopter were pitched up, proportionate to how far away from north the helicopter is turned. It seems as if the gun's orientation is being calculated globally, not relative to the aircraft.

See the rocket pods on my AH-64 for reference.

**Comment by DonBruce64** [comment]
Fixed in V19.3.0.
