### ISSUE TITLE
I may be totally missing it, but I can't figure out how to disable automatic startup in vehicles

### ISSUE THREAD

**Issue by Orvngex** [DonBruce64/MinecraftTransportSimulator#529]
I would like to get in my plane without it starting on it's own, it also auto starts when putting animals or npcs into the plane. Any help?

**Comment by DonBruce64** [comment]
The auto-starting is a config option in the config file.  You can turn if off from said config option if you want the older, manual-start style of controls.

**Comment by Orvngex** [comment]
okay, I have looked in config and can't find it lol. Is it "electric start" because I tried that and it doesn't work..

**Comment by DonBruce64** [comment]
Nope.  autostartEngines.

**Comment by Orvngex** [comment]
w h e r e, i am having such a hard time finding it. Is it in the normal config file or somewhere else?

**Comment by Orvngex** [comment]
welp just realised there are 2 config files, found it, thanks lol

**Comment by DonBruce64** [comment]
Ah, you must have an old config file.  What files do you have?

**Comment by Orvngex** [comment]
![image](https://user-images.githubusercontent.com/46629454/94502102-04789e00-01c9-11eb-93c6-3578b3ebb8e5.png)

**Comment by DonBruce64** [comment]
Ah, mts.cfg is old and isn't used any-more.  That's from like V15 days.  Sorry about the confusion.  I really should see if there's a way to delete that one automatically...

**Comment by Orvngex** [comment]
nah it's all good, I should have seen it anyway

**Comment by DonBruce64** [comment]
Well, I went ahead and put in code to delete that old file anyways, so hopefully it'll prevent the same confusion from other players.  S'all good!

**Comment by Orvngex** [comment]
alright, thank you so much for your help, also thank you for quick responses and fast updates. It really shows how much you care about the mod and it's users. Good job
