### ISSUE TITLE
[Bug] Additional Parts don't inherit mirroring correctly

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#530]
Specifically, when 2 rotors are additionalParts for one engine, they don't mirror correctly when has a positive x position, and the other has a negative x position.

**Comment by DonBruce64** [comment]
Closing as based on our discussions and the system, parts do mirror themselves, but not always in the same way, but in ways that are functional and cause the least amount of jank.
