### ISSUE TITLE
Vehicles don't accelerate or fall quickly out of the sky.

### ISSUE THREAD

**Issue by Orvngex** [DonBruce64/MinecraftTransportSimulator#533]
For example, if I shut my engines off in a plane from any height, it will just fall slowly straight down and land safely. Obviously, this wouldn't happen in real life.

**Comment by Orvngex** [comment]
also how do I change the crater size after a plane crashes?

**Comment by DonBruce64** [comment]
I mean, no.  But does the plane actually fall *straight* down, or does it glide?  Because planes can definitely glide to safety, even if the engine dies.

**Comment by Orvngex** [comment]
Straight down, like a nose dive, just slowly. Also, for some reason it doesn't happen every time.

**Comment by DonBruce64** [comment]
I'm wondering if the plane is stalling and it fouls up the physics and instead of tilting down like a normal plane, it gets stuck and just flat-stalls...  What IV version is this on, and what plane do you most normally see this on?

**Comment by Orvngex** [comment]
it happens on all of them, sometimes they will glide properly, and sometimes they will just look almost straight down and fall slowly then land safely, from very high altitudes as well.

**Comment by DonBruce64** [comment]
Fixed in V19.6.0.
