### ISSUE TITLE
Player is seated outside and the vehicle doesn't move

### ISSUE THREAD

**Issue by DhruvPRO295** [DonBruce64/MinecraftTransportSimulator#537]
I'm currently using Forge 1.12.2 
When I try to enter a vehicle, it makes me sit outside the vehicle and I'll be in the position of sitting. 
And also after sometime the vehicle doesn't move front or back as if it is being blocked by something even when it is in the open.

**Comment by DonBruce64** [comment]
I've seen the seat issue occasionally, but haven't been able to catch it when it happens.  Will try to figure it out whenever it does.
