### ISSUE TITLE
[sticky note] Paint Gun

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#538]
A tool to change a vehicle's color without crafting a new one. Basically a relocated drafting bench "color" section.
Click on a vehicle to open the GUI. Works like any crafting bench, with ingredients shown on the right, a vehicle hologram in the middle, and a selection bar with confirm button. The top half of the text display the vehicle name and the bottom half the color variant.

![paint gui](https://user-images.githubusercontent.com/45642968/94994334-87369a00-05c9-11eb-9303-786add9181f0.png)
(This is the same format and diameter as the crafting GUI)

Some QoL additions:
1. Show the color variant being clicked on. Ex. when clicking on a green car, the GUI opens at the green page. 
2. A warning when clicking on a vehicle without multiple color variants.
3. Dropped vehicle items visually showing the color variant and/or have a tag in its name.

Things to be discussed:
1. Should vehicles have a default texture when first crafted?
2. Should the creative inventory still show every variant of a vehicle?

**Comment by DonBruce64** [comment]
Added in V19.3.0.
