### ISSUE TITLE
[Bug] Guns won't reload

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#541]
In previous versions of MTS, I've noticed that you can't reload a gun with a different type of bullet of the same diameter (e.g. loading an explosive-type after firing all of a normal-type).

As of v19.3, however, this seems to have extended to the same type of bullet. **Once a gun has been initially loaded, it can't be loaded again**, before or after firing the initial bullets. autoReload doesn't seem to reload guns from an interactable_crate on the vehicle either.

**Comment by DonBruce64** [comment]
Fixed in 19.4.0.
