### ISSUE TITLE
Crash when moving to UNU Parts Pack

### ISSUE THREAD

**Issue by SwarVillagerPro97** [DonBruce64/MinecraftTransportSimulator#544]
I Have Several Problems About The Pack, It Crashes In The Inventory While UNU Is My Only Mod In The Game. Is This Caused By No Texture Errors In The Inventory? Please Help! I Have UNU Parts Pack 4.0.0

**Comment by DonBruce64** [comment]
Yup, that's a UNU pack issue.  They load multiple items in their latest release, which doesn't work well with V19 systems. Either downgrade to V18, or install Immersive Engineering which keeps that pack from mis-behaving, or don't touch any of the purple checker icons.

**Comment by SwarVillagerPro97** [comment]
One more thing Bruce, Why the MI-24 Helicopter has a difficult to add the engine and the propeller? this is my last bug question. sorry

**Comment by DonBruce64** [comment]
You'd have to ask the pack author about that one.  I don't maintain any helicopters.

**Comment by SwarVillagerPro97** [comment]
Ok thank you

**Comment by bravecal91** [comment]
I get the feeling the same thing may happen with people who use JEI to view UNU parts, however there is always the chance that this method won't crash the game. I may test this theory, as if it works it can provide people with a way to avoid the creative menu (And therefore crashes) completely.

**Comment by DonBruce64** [comment]
Closed as UNU parts pack V4 was released just now, and does not have this issue.
