### ISSUE TITLE
[Bug] Player is killed when exiting a helicopter

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#545]
When leaving a helicopter without shutting down the engine first, a player can be killed by the rotor/propeller instantly. When this happens, the player's items are destroyed. Part of the problem seems to be that the propeller's hitbox is about 2 blocks high, which can easily make it extend into the seat's dismount position.

Of course, this can be prevented by shutting the engine off first, but many real life applications involve getting out of a still-running helicopter.

**Comment by DonBruce64** [comment]
This is a mix of part placement, and hitboxes being too large.  I can fix the hitbox being too big, though it's no longer as big as it used to be in prior versions.  Will tweak.

**Comment by DonBruce64** [comment]
Fixed the best I can in 19.4.0.  Other half of this is making the propeller hitboxes far enough away from the vehicle that you don't hit them when you dismount.  Can re-visit this later if it becomes an issue.
