### ISSUE TITLE
[Bug] Freeze when throwing Eye of Ender from plane

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#55]
I right-clicked to throw an Eye of Ender while flying an MC-172, in order to find a stronghold. Instantly it froze up and had to be killed. Nothing in logs.

**Comment by DonBruce64** [comment]
Odd.  I can't seem to reproduce this bug.  Are you sure there was nothing in the logs?  Usually MC puts *something* in there when it locks up.

**Comment by DonBruce64** [comment]
Closing and marking as invalid as I couldn't reproduce this bug, and no logs were found to allow me to troubleshoot, and it's been a month without a response.
