### ISSUE TITLE
Mobs plunged under the surface when walking by a vehicle.

### ISSUE THREAD

**Issue by Orvngex** [DonBruce64/MinecraftTransportSimulator#550]
When any mob walks by any vehicle, the mob will be sent about 2 blocks underground, or at least until it's head is submerged. However, it won't always suffocate.

**Comment by DonBruce64** [comment]
Is the vehicle moving during this time, or is it staying still?  Because I've always had issues with moving vehicle moving players in places they don't want to go due to MC trying to keep the player out of the vehicle's collision boxes.

**Comment by Orvngex** [comment]
engine off, completely still.

**Comment by DonBruce64** [comment]
Very odd.  I haven't seen that before.  Do you have a video you can post?

**Comment by Orvngex** [comment]
I can provide a video, but it will likely be tomorrow. It is on the newest version.

**Comment by Orvngex** [comment]
here is the video: https://youtu.be/tZELEVDt6xY

**Comment by DonBruce64** [comment]
Odd.  I've never seen that in my tests.  And I've run into plenty of zombies.  Would you be able to join the Discord so I can throw some test builds at you?  It's easier for me than doing things through Git.  Just ping me when you get on.  Username is the same.
Link: https://discord.gg/KaaSUjm

**Comment by Orvngex** [comment]
I joined, thank you

**Comment by DonBruce64** [comment]
I'm pretty sure this is fixed in V19.5.0.  If not, please let me know or re-open the issue.
