### ISSUE TITLE
[Bug] cameraObject positions seem to be relative to the player, not the vehicle

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#554]
While testing having a cameraObject mounted on the nose of my AH-64, I noticed that the position of the camera seemed to be way further forward and lower than it should have been. Checking the view from each of the pilot seats, I realized that the view from the back seat was slightly higher than the one from the front seat, indicating that the offset was due to the camera position being relative to the player's location.

**Comment by DonBruce64** [comment]
Fixed in V19.5.0.  You also get extra cameras too!
