### ISSUE TITLE
[BUG?] MTS vehicle collision no longer plays nice with MalisisDoors Garage Door.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#556]
Normally (and in previous versions) a car would've just breezed through an open door as if it were nothing (since it's open)

However, it seems that now they don't wanna play ball, and so my truck just gets stuck.
**https://cdn.discordapp.com/attachments/289084393442639872/765399321725239306/2020-10-12_22-22-41.mp4** (Video is also in #garage)

**Comment by DonBruce64** [comment]
I've had folks mention this.  I wonder if there's something funky going on.  Will check into this when I get a momement.

**Comment by DonBruce64** [comment]
Fixed in V19.5.0.
