### ISSUE TITLE
Borked animations when several of the same vehicle are present.

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#559]
When several vehicles of the same type are in an area (unsure if this applies to different vehicles), door animations will only trigger when the door of the first placed vehicle is activated. This will trigger the animations of every other vehicle no matter the state of their doors, and the animated state of every other vehicle will not correspond with their door position.

**Comment by DonBruce64** [comment]
Fixed in V19.5.0.
