### ISSUE TITLE
Request: (foreseeable future) Sub-rotational parts

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#56]
Allow rotatable parts to rotate with other parts; example: the Cat225’s arm, there are three points of rotation, it would look weird if only the arm would rotate and not the two other points at the arm would stay in their location.

**Comment by DonBruce64** [comment]
This is already do-able in the current system by rotating arm section 1 normally, and then rotating arm section 2 by the same rotation as arm 1, and then by it's own rotation.  There are no limits to the number of rotations you can apply to a part, or to the points you rotate them by.  In fact, this is how the hydraulics work IRL as each segment has its own cylinder.
