### ISSUE TITLE
Edit: Rendering crashes while climbing ladder

### ISSUE THREAD

**Issue by chj990707** [DonBruce64/MinecraftTransportSimulator#561]
Edit: When player is climbing the ladder, Rendering(InterfaceRender.java, line number 507) causes nullexception. This doesn't happen on touching the ladder but on random moment while climbing or descending, cannot be sure on precise condition of it.

**Comment by chj990707** [comment]
Can recreate this; while on ladder, look at the ladder and turn the camera to bottom direction.

**Comment by DonBruce64** [comment]
Fixed in V19.5.0.
