### ISSUE TITLE
[Suggestion] Add GUI/HUD for cameras (per camera)

### ISSUE THREAD

**Issue by war-monger** [DonBruce64/MinecraftTransportSimulator#562]
![Gunner2](https://user-images.githubusercontent.com/8458556/96339826-f9e15400-1064-11eb-899a-4a5dd681e767.jpg)
![Gunner](https://user-images.githubusercontent.com/8458556/96339828-fa79ea80-1064-11eb-99cf-3ad97d79fc18.jpg)

**Comment by gyrohero** [comment]
Upvote

**Comment by DonBruce64** [comment]
Someone gives me a overlay to add on their pack, I'll add this feature.

**Comment by DonBruce64** [comment]
Implemented in V19.6.0.
