### ISSUE TITLE
[BUG] Black overlay appears when inventory or pause menu is opened while in a controller seat

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#571]
Overlay doesn't block the view of any of the buttons, it just blackens the background.

![image](https://user-images.githubusercontent.com/53581325/96766748-8e232200-13a9-11eb-994c-e52693b58396.png)
(Space race button is unrelated, from another mod.)

**Comment by DonBruce64** [comment]
![2020-10-21_19 11 18](https://user-images.githubusercontent.com/15241611/96803413-dfdfa280-13d1-11eb-86e9-0858e134ea90.png)
I don't see an issue with the screen?

**Comment by DonBruce64** [comment]
Is this related to a specific instrument or vehicle or panel?

**Comment by DonBruce64** [comment]
Fixed in V19.8.0.
