### ISSUE TITLE
Placing a 'route' sign causes a crash

### ISSUE THREAD

**Issue by flameoguy** [DonBruce64/MinecraftTransportSimulator#573]
My game version is 1.12.2. I am running this mod alongside IC2 classics and Buildcraft. Most street signs seem to work fine when adding them to a pole, but upon placing a route marker the window closes. Trying to load the world only causes the game to close again.

**Comment by DonBruce64** [comment]
Literally just had someone report this on the Discord.  Turns out the route sign was fouled up in the latest OCP update.  Currently waiting on Curse to approve the fixed pack.

**Comment by DonBruce64** [comment]
Curse just approved.  Marking this as closed as of OCP V19.
