### ISSUE TITLE
[Suggestion] Doors auto-close on movement

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#574]
Once the car is going a certain speed, some doors should auto-close. That speed could be the same speed as when the brakes auto-apply in simple throttle mode.

This would have to be a true/false because we wouldn't want windows/convertibles to auto-close!

**Comment by DonBruce64** [comment]
I would prefer to have this another way than speed-based due to player confusion.  Any alternate thoughts?

**Comment by DonBruce64** [comment]
Did this in commit 244e348674ea7254d5b0a6549e521dd4504ee35f. Forgot to reference issue number.

**Comment by DonBruce64** [comment]
Implemented in V19.9.0.
