### ISSUE TITLE
[BUG] Lights works only viewed from the side

### ISSUE THREAD

**Issue by Rihnami** [DonBruce64/MinecraftTransportSimulator#575]
![2020-10-23_21 58 05](https://user-images.githubusercontent.com/73362627/97044201-689a4200-157c-11eb-89fb-9c8c62817655.png)
![2020-10-23_22 05 14](https://user-images.githubusercontent.com/73362627/97044211-6c2dc900-157c-11eb-986f-e15cc74f422e.png)

**Comment by DonBruce64** [comment]
Ironically, that image is too dark for me to see what's going on.  Can you brighten it up a bit?

**Comment by Rihnami** [comment]
I think this cone of light wurks like a filters, if look from the side, they overlap
![2020-10-23_21 58 05](https://user-images.githubusercontent.com/73362627/97067758-66aaa000-15c9-11eb-93ef-7388f853e245.png)
![2020-10-23_22 05 14](https://user-images.githubusercontent.com/73362627/97067760-69a59080-15c9-11eb-8b57-0094c16735e7.png)

**Comment by DonBruce64** [comment]
Again, still too dark on that bottom picture.  Are you using some shaders or something?  Or a darkeness mod?

**Comment by Rihnami** [comment]
Yes, it's Dynamic Darkness mod https://www.curseforge.com/minecraft/mc-mods/dynamic-darkness

**Comment by DonBruce64** [comment]
If you remove that mod, does the issue go away?

**Comment by Rihnami** [comment]
Yes, but vanilla Minecraft night is so bright and lights is pointless. Can you brighten them up?

**Comment by DonBruce64** [comment]
I can, but it'll be FAR too bright for vanilla night.  I might be able to do a config or auto-checking setting.  Would you be able to join the Discord so I can throw a few test builds at you?

**Comment by Rihnami** [comment]
Ok. i'm already joined
Nickname: Fox#4701

**Comment by DonBruce64** [comment]
Fixed in V19.8.0.
