### ISSUE TITLE
[Suggestion] two config suggestions

### ISSUE THREAD

**Issue by Greenjoe12345** [DonBruce64/MinecraftTransportSimulator#579]
So I have two config suggestions. I imagine this will need a second page on the config menu implemented
1. Disable automatic blinkers/ indicators. Now that there are keyboard controls for indicators, it would be good to be able to disable the auto indicators as it is annoying that they turn on every time you turn.
2. Swap full throttle to forwards + mod key. Currently forwards and mod key together give you half acceleration, it would  be neat to have half throttle be able to be toggled to just forwards, so you're not always flooring it everywhere without pressing the mod key.

**Comment by DonBruce64** [comment]
Disabling the auto-indicators wouldn't wholly disable them from appearing on multiplayer instances, as their states are controlled on a per-client basis.  Coding packets for the lights is possible, but would lead to complications as I wouldn't know who's client to look at for the lights.  Though I suppose I could put that into a control-packet system.  What do you think?

Swapping throttle though, is easy, as that's already in the control system.

**Comment by DonBruce64** [comment]
Implemented both in V19.8.0.
