### ISSUE TITLE
[OCP] Add RR Crossing sign.

### ISSUE THREAD

**Issue by DonBruce64** [DonBruce64/MinecraftTransportSimulator#58]
I see no reason why we can't make something like this.  It's simple, and doesn't come in nearly any packs.

**Comment by fsendventd** [comment]
Darn, I should have been faster.

**Comment by obsidian29** [comment]
I'm sorry I don't have this done yet. My mom had radiofrequency ablation and that's taking priority. I'll get it taken care of when things smooth over here.

**Comment by DonBruce64** [comment]
No worries.  This update cycle will take some time, and after I do it I'll have to update the OCP anyways, so I'll likely just add your sign to GitHub and leave it there in the repository until release day.

**Comment by DonBruce64** [comment]
@fsendventd @obsidian29, Need to check if this is still going in. If not, let me know and I'll close this issue.

**Comment by obsidian29** [comment]
Yeah, it is. Sorry it's taken me so long. When I get to the desktop I'll see if I can send it.

**Comment by DonBruce64** [comment]
Canceling due to lack of interest from modelers.  I can't make a sign to save my life.

**Comment by obsidian29** [comment]
I sent you the sign, it's not my fault it's not in there. If it got lost, I can send it when I get my desktop running again.
