### ISSUE TITLE
Scrolling is inverted in the MTS Manual

### ISSUE THREAD

**Issue by newbthenewbd** [DonBruce64/MinecraftTransportSimulator#583]
On Arch Linux with X11 and OpenJDK Runtime Environment (build 1.8.0_265-b01), it seems that scrolling up in the manual causes the next page to appear, while scrolling down - the previous.

If this is the case on all systems, it would seem to only require a simple change [somewhere in there](https://github.com/DonBruce64/MinecraftTransportSimulator/blob/b9768abd855246fa097948805fa77c0d7f45336c/src/main/java/minecrafttransportsimulator/guis/instances/GUIBooklet.java#L124-L129), but as I am not sure that this is definitely the case (while I definitely hope that it is, looks like a sorry piece to have problems with :upside_down_face:), I'm making this an issue and not a pull request.

Thank You from the depths of my heart for all the hard work on this great mod!

**Comment by DonBruce64** [comment]
Fixed in V19.8.0.
