### ISSUE TITLE
[Suggestion] Allow animations based on the currently selected gun's variables

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#585]
Currently, using gun variables in the vehicle JSON requires using a number at the end to refer to a specific gun. I propose that if you omit the gun number in the vehicle JSON, the animation system will get the variable from whichever gun is currently selected. In the case that multiple guns are selected (e.g. there are multiple of the same type of gun), it can simply get the first of these.

This will allow cameras that rotate with whichever gun is selected, not just one specific gun.

**Comment by DonBruce64** [comment]
Done in commit 244e348674ea7254d5b0a6549e521dd4504ee35f.  Forgot to add issue number to commit.
