### ISSUE TITLE
[OCP] Yield sign reads "Yeild".

### ISSUE THREAD

**Issue by DonBruce64** [DonBruce64/MinecraftTransportSimulator#59]
Needs to be fixed in the texture and lang files.  May cause issues in worlds that don't have the sign loaded.  Be prepared for a crash report if so...

**Comment by fsendventd** [comment]
No, the texture itself says yield, it's just the Lang file.

**Comment by DonBruce64** [comment]
The name of the texture *file* says yeild, which means it's off in the lang file and in the JSON file.

**Comment by DonBruce64** [comment]
Fixed in V09 of the OCP.
