### ISSUE TITLE
[BUG] Reloading all textures with F3+T doesn't reload textures of inventory items

### ISSUE THREAD

**Issue by baddiePRO** [DonBruce64/MinecraftTransportSimulator#594]
Client log: https://pastebin.com/WP40swwF

Before:
 ![2020-11-09_10 43 37](https://user-images.githubusercontent.com/46608342/98563737-886a7f00-2279-11eb-8478-a84093cbd33e.png)

After: 
![2020-11-09_10 44 32](https://user-images.githubusercontent.com/46608342/98563795-9ae4b880-2279-11eb-82b1-23b23160f203.png)

Block textures still work though
![2020-11-09_10 45 13](https://user-images.githubusercontent.com/46608342/98563863-acc65b80-2279-11eb-8e07-853f5fb57313.png)

**Comment by DonBruce64** [comment]
You're using an obsolete version of the mod.  This was already fixed vi #572.

**Comment by baddiePRO** [comment]
alrighty, tnx
