### ISSUE TITLE
Variables to make instruments appear and disappear, according to variables (SUGGESTION)

### ISSUE THREAD

**Issue by SpicySauseSaig** [DonBruce64/MinecraftTransportSimulator#595]
According to the current V19 code, you can only rotate and translate parts of a instrument according to values. If you can make parts of a instrument appear and disappear according to variables, it would offer a lot of benefits to both plane and car instruments.

**Comment by DonBruce64** [comment]
Really what needs to happen here is the instruments need to be changed to use the standardized VehicleAnimationSystem.  That way they get all the features of that system, like visibility and inheritance.  Will require some significant changes and a section of legacy compats, but is do-able for sure.  Flagging as backburner though as it'll take a while and it's not a hot feature request.

**Comment by DonBruce64** [comment]
This was done in abad6f285ec2d1cba45df7400a5c680881ba7338.  Haven't tested it, but it *should* work.

**Comment by DonBruce64** [comment]
Can confirm inhibitors should work in V19.10.0.  With this, you can render warning lights depending on the value of a parameter, or whatever else you wish to do with parts of the instrument that go away.
