### ISSUE TITLE
[BUG] MTS controller warning doesn't know its place, and needs to be punished.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#598]
![image](https://user-images.githubusercontent.com/53581325/99027296-e7aae680-253a-11eb-881a-9f9d32283344.png)
![image](https://user-images.githubusercontent.com/53581325/99027309-ec6f9a80-253a-11eb-9c35-913230f7858c.png)
BAD WARNING TEXT! NO MORE TREATS FOR YOU!

**Comment by DonBruce64** [comment]
Should be a simple fix.  Just need to change this line here:
https://github.com/DonBruce64/MinecraftTransportSimulator/blob/5e480ba62a7b02bb63c38c570328d4b5d41d25c1/src/main/java/minecrafttransportsimulator/guis/instances/GUIConfig.java#L347
To this:
`vehicleSelectionFaultLabel.visible = !MasterLoader.inputInterface.isJoystickSupportEnabled() && configuringControls && configuringKeyboard;`
I can't do this at the moment, but someone else might be able to get this in the meantime.

**Comment by DonBruce64** [comment]
Turns out I CAN actually do this...

**Comment by DonBruce64** [comment]
Fixed in V19.10.0.
