### ISSUE TITLE
[Valkyrien Warfare/Skies]: Vehicles fall through the ground and into the void (or are black and dismount you into the void).

### ISSUE THREAD

**Issue by DonBruce64** [DonBruce64/MinecraftTransportSimulator#6]
This is a known issue with Valkerian Warfare.  Their mod messes with the core Minecraft collision system, which MTS uses to detect blocks below vehicles.  For some reason, they are not returning the correct hitboxes for blocks that Vanilla Minecraft/Forge does, resulting in MTS not finding any collidiable blocks below the vehicles.  It is up to THAT mod to fix their hacking in Vanilla code, not MTS to accommodate said hacks.  There is already an issue on that mod's GitHub, please reference it:
https://github.com/ValkyrienWarfare/Valkyrien-Warfare-Revamped/issues/170

**Comment by KryzyKreel** [comment]
This is a late comment, so you might know how to fix this issue:

I know why the vehicle falls through the ground, you didn't add wheels to the vehicle. That's probably why it falls through, hope that clears the issue.

**Comment by DonBruce64** [comment]
No.  That is not why it falls through.  It falls because there is nothing for MTS to collide with due to VW messing with block physics.  Even if you were to add wheels, it would still fall down, through all blocks, and into the void beneath the world.

**Comment by KryzyKreel** [comment]
Man, mods do mess some things up.

**Comment by Rubyjunk** [comment]
I will investigate this issue. Thanks for redirecting people to us.

**Comment by DonBruce64** [comment]
Marking as closed as of ValkyrienSkies-1.12.2-1.0-alpha-1.  Appears a code re-write occurred that fixed this collision issue.

**Comment by DonBruce64** [comment]
Re-opening, as the next release after that alpha re-introduced the issue.  From "Valkyrien Skies 1.12.2-1.0.0" onwards, V18 vehicles again fall through the ground into the void.  For V19, the vehicles don't fall into the void visually, but they do so in Minecraft code.  Because of this, they render black, and when a player dismounts them, they are put into the void where MC thinks the vehicle is.

**Comment by DonBruce64** [comment]
Want to mention that unlike the first comments, the source of the issue isn't that vehicles aren't seeing collision blocks.  Rather, they are seeing the collision blocks, and preventing themselves from moving, but VW is forcing the vehicles to move downwards from their end.  It's why the vehicle renders above the world, but you get sent below it when you dismount.

**Comment by gatoborrachon** [comment]
Update: 
MTS: Immersive+Vehicles-1.12.2-19.11.0
VS: valkyrien-skies-1.12.2-1.1.0

now vehicles are practically functional, but there are some visual bugs and when you try to get out it appears that you die from fall damage (it even hurt you in creative)

Videos:
https://streamable.com/1m7vpk (MTS and VS only)
https://streamable.com/9nesys (A bunch of mods)

**Comment by Tri0de** [comment]
I managed to modify MTS vehicles to collide with ships and get dragged with ships.

Maybe I'll make a pull request to fix it.

**Comment by Fureniku** [comment]
Does that mean this issue was on MTS's side and not VS?

Either way speaking as a player, MTS support would be a huge bonus so
please do!

**Comment by DonBruce64** [comment]
I'm going to say no to that, simply due to the fact there's no reason MTS vehicles should, in normal circumstances, be moving into the ground downwards.  The reason for the change in this behavior is because I have internal variables that are separate from the main entity that control physics and rendering.  So the MTS physics engine knows there's ground below it and knows the vehicle didn't move, but it's being moved into the void anyways.  This is why they turn dark (due to no light), and they dismount you into the void (because the entity is down there).   In general, VS shouldn't be touching the vehicle entity at all if it's just sitting on the ground.  Especially if there aren't any ships in the area.

**Comment by Tri0de** [comment]
It kind of works https://youtu.be/ORvdkAXYJEc

**Comment by Jimmy805** [comment]
It looks strange. Now that I have both two mods installed( MTS 1.12.2--19.14.0; VS 1.12.2--1.1.6, and I don't notice anything unusual when I'm driving a vehicle from MTS, or even when I'm getting in and out of the vehicle. Is there something I'm missing?

**Comment by DonBruce64** [comment]
That's a different version that what we've seen issues on.  As I and @gatoborrachon said, it was VS 1.12.2-1.0.0, and 1.1.0 that had issues.  Could you try again with 1.1.0 and see if the issue re-appears?  It could very well have been fixed again.

**Comment by Jimmy805** [comment]
Oh yes. Just now when I used VS 1.1.0, all the vehicles I put became black. And when I change VS back to 1.1.6, all the vehicles are back to normal.

**Comment by DonBruce64** [comment]
Awesome!  I'll mark this issue as re-solved as of VS 1.1.6.  Hopefully it stays solved!
