### ISSUE TITLE
suggetion: Make parts of the gauge that don't light up, not light up

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#606]
The only sections that should be getting brighter is the green "neon", the gauge needles, and the blue screens
What ends up happening, is that everything is lit up, due to the way how MTS handles gauge lighting

![2020-11-15_13 27 43](https://user-images.githubusercontent.com/63666200/99195988-9e2ee700-2746-11eb-9f86-541f90401638.png)
![2020-11-15_13 28 22](https://user-images.githubusercontent.com/63666200/99195989-9ec77d80-2746-11eb-8650-8dabaa234c6f.png)
Ideally, this is how it should look something like this
![fake](https://user-images.githubusercontent.com/63666200/99196168-de429980-2747-11eb-9497-111f64ea04c7.png)

**Comment by DonBruce64** [comment]
Can you post your instrument texture and JSON? This should already be how the system works, providing you have your instruments set up correctly, though it is possible it's borked.

**Comment by BlazeWolf1122** [comment]
[assets.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5549237/assets.zip)

**Comment by DonBruce64** [comment]
Addressed in V19.10.0.  This required a new JSON parameter, so it won't be fixed by default. But it can be fixed with some minor JSON tweaks now.
