### ISSUE TITLE
[Enhancement] Variables for missile incoming

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#607]
This would allow for instruments that provide a warning if the vehicle is being tracked by a missile. There would be 3 variables: missile_incoming (Boolean), missile_direction (float), and missile_distance (float). If there are multiple missiles incoming, this could be limited to whichever is closest, or possibly be numbered to allow a certain number of alerts.

For implementation, the missile would just have to pass a pointer of itself to the vehicle it's locker onto, simulating its laser or radar signature.

**Comment by DonBruce64** [comment]
Should be simple.  And would be good as you could link it to an animation for an in-cockpit warning sound.  When I get to overhauling the instruments to work with the VAS, then the instrument can play the sound, so it'll be cross-compatible with different vehicles.

**Comment by gyrohero** [comment]
I was thinking that too about the sound thing. Alright, cool.

**Comment by fsendventd** [comment]
_WOMP WOMP WOMP_
Would this theoretically allow chaff or flares to be automatically deployed as well, once that's added?

**Comment by gyrohero** [comment]
@fsendventd Yeah, we can probably set it up so that they deploy based on JSON-defined clamps of the distance/direction variables

**Comment by DonBruce64** [comment]
I hesitate to have flares automatically deploy.  If only because there's not really a point in having missiles that home and lock on if they just automatically get chaffed. Plus, having chaff be part of the VAS is kinda icky.  Unless you mean a parameter, but even then, if you have a lock-on variable then that can correlate to chaff deployment without messing with variables.

**Comment by fsendventd** [comment]
@DonBruce64 You would eventually run out of flares, they'd have ammo like guns. Plenty of other games (e.g. War Thunder) have automatic flare deployment in certain vehicles, it isn't overpowered.
