### ISSUE TITLE
Something is modifying the list of loaded TileEntities in the middle of a rendering operation

### ISSUE THREAD

**Issue by Fureniku** [DonBruce64/MinecraftTransportSimulator#609]
[crash-2020-11-17_21.11.27-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5556317/crash-2020-11-17_21.11.27-client.txt)

For simplicity I'll just copy-paste the discord chat

don_bruce™Today at 9:29 PM
@Fureniku Something is modifying the list of loaded TileEntities in the middle of a rendering operation, and I'm crashing due to the modification in the middle of my rendering operations.

FurenikuToday at 9:30 PM
Very possibly little tiles

don_bruce™Today at 9:30 PM
I really should stop checking those lists....  Freaking mods are ALWAYS modifying them
Can you re-produce that bug easily?

FurenikuToday at 9:31 PM
It happens every time I log into my server, but it wasn't happening until just now. It'll crash when I'm in render range (I dropped my render range a bit and was able to move closer to the building where the problem is). However, I ran past that place twice like an hour before in the same session
So I can reproduce it in this specific situation, not sure how easily I could recreate it

**Comment by DonBruce64** [comment]
Added work-around in V19.10.0 to prevent this issue.
