### ISSUE TITLE
[Suggestion] Smoke system for airplanes

### ISSUE THREAD

**Issue by MiszkoPro** [DonBruce64/MinecraftTransportSimulator#611]
Hey don! Just wanted to suggest a fun thing that would be very usefull for me, smoke systems! Since I'm working on a little something that includes aerobatic planes I need this feature. It would also be nice to have coloured smoke but since that would mess with custom particles I don't know if it's possible. (Including a picture of what exactly do I have on my mind)
![Hero_Smoking-Airplanes_1920x1080](https://user-images.githubusercontent.com/74724201/99683113-4662e980-2a80-11eb-8597-3456d8ebe1d2.jpg)

**Comment by DonBruce64** [comment]
This should be easy enough to add.  However!  There has been a history of people requesting this feature for planes that never get into a pack.  So I'm going to hold off on it until your planes are ready and flying.  Also, this would likely require something similar to the bullet code and gun code for "canisters" of smoke that come with the plane, and the gun code is currently being overhauled to work with missiles and such, and I don't want to interrupt Gyro's workflow.

**Comment by fsendventd** [comment]
> 
> 
> This should be easy enough to add. However! There has been a history of people requesting this feature for planes that never get into a pack. So I'm going to hold off on it until your planes are ready and flying. Also, this would likely require something similar to the bullet code and gun code for "canisters" of smoke that come with the plane, and the gun code is currently being overhauled to work with missiles and such, and I don't want to interrupt Gyro's workflow.

@DonBruce64 I have a vehicle in a pack that would use it...

**Comment by gyrohero** [comment]
Implemented in 19.11.0
