### ISSUE TITLE
[SUGGESTION] config option for overheating/how different biomes affect overheating.

### ISSUE THREAD

**Issue by baddiePRO** [DonBruce64/MinecraftTransportSimulator#613]
Just want a way to tweak/disable engine overheating, and how fast hotter biomes make engines overheat.

**Comment by DonBruce64** [comment]
Could you be a little more specific?  What exactly are you seeing that you'd like changed with the configs?

**Comment by baddiePRO** [comment]
I was thinking we could have a variable for how quickly engines overheat, where 1 is default, and 0 disables it completely. Also an option to disable biome specific engine temp would be nice.

**Comment by DonBruce64** [comment]
I could do that.  But biomes would be tricky.  Is there an issue with the biome temps?  Because I'd rather fix that than try to figure out what the best "average" temp would be to have for disabling the biome temps.

**Comment by baddiePRO** [comment]
it feels like engines overheat too fast in desert biomes, especially airplane engines where it has to be a high rpm to actually be useful. although I'm probably dumb for making my base in the desert in the first place.

**Comment by DonBruce64** [comment]
So, I'm going to table this config for the moment until @fsendventd gets a chance to re-do the propeller force physics, as there's a good chance the reason you're overheating is because the propeller doesn't produce enough thrust and you're having to over-rev the engine, not that the temps are causing problems.  If this is still an issue after the physics overhaul, I'll 100% add the functionality.

**Comment by fsendventd** [comment]
> 
> 
> So, I'm going to table this config for the moment until @fsendventd gets a chance to re-do the propeller force physics, as there's a good chance the reason you're overheating is because the propeller doesn't produce enough thrust and you're having to over-rev the engine, not that the temps are causing problems. If this is still an issue after the physics overhaul, I'll 100% add the functionality.

@DonBruce64 Aircraft engines run at near-max RPM regardless of what the propeller code looks like, that's how they should be. If you could achieve max speed in an aircraft at only 60% RPM then the propellers would be producing too much thrust and would need to be nerfed.

**Comment by DonBruce64** [comment]
In that case, I'll get right on this.

**Comment by baddiePRO** [comment]
y'all are awesome, thanks!

**Comment by DonBruce64** [comment]
Implemented in V19.11.0.
