### ISSUE TITLE
Crafting Recipes for planes/helicopters not appearing in JEI

### ISSUE THREAD

**Issue by MillenniumAlpha** [DonBruce64/MinecraftTransportSimulator#614]
When I search up how to make a plane/helicopter in JEI and I click one of icons it doesn't show the crafting recipe same with the parts used to make the plane/helicopter.

Version of Immersive Vehicles I am using:
https://www.curseforge.com/minecraft/mc-mods/minecraft-transport-simulator/files/3109263

Version of the two packs I am using:
https://www.curseforge.com/minecraft/mc-mods/transport-simulator-official-vehicle-set/files/3089105
https://www.curseforge.com/minecraft/mc-mods/gyro_heros-helicopter-pack-iv-mts/files/3110660

Version of JEI I am using:
https://www.curseforge.com/minecraft/mc-mods/jei/files/3040523

**Comment by DonBruce64** [comment]
This is a duplicate of #450
