### ISSUE TITLE
SUGGESTION: Permissions for server owners.

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#618]
Hey, it's me again. Here with another odd suggestion.
Perhaps permission nodes for servers. Permissions would be enabled in the config. They'd essentially allow for the following:
* A perm node required for editing vehicles. This includes adding/removing parts, and editing the instruments. Useful for Roleplay servers (Hint Gramados Hint), because not everyone IRL knows how to work with vehicles.
* A perm node required for creating vehicle parts/using the MTS-Benches. For the same reasons as above.
* A perm node required to drive the vehicles. Mainly for those hardcore Roleplay servers.
* A perm node required to even enter the vehicle's seats. Again, for hardcore Roleplay servers.
* And finally, a perm node required to do the OP things in the config. Like OP only sign editing.

**Comment by DonBruce64** [comment]
All of these already exist.
Perm mode for editing vehicles is done by using keys to take ownership of vehicles.
Perm mode for creating vehicle parts is done by not allowing players to interact with blocks.
Perm mode for driving vehicles is done by locking them.
Perm mode for entering seat is done the same way.
Perm mode for OP thing like sign editing already exists in the config.
