### ISSUE TITLE
New light type: laser

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#621]
These lights would have a narrow beam that travels a longer distance. As a bonus: possibly make a visible and infrared variant. Then add a parameter to cameras "seeIR". Infrared lasers would be invisible except when looking through an IR-capable camera.

**Comment by DrprofLuigi** [comment]
~~Bring back json-defined lights~~

**Comment by DonBruce64** [comment]
Closing as this can be done via a generic light now.  Visibility can be toggled based on an animation, so you can make it visible if you're looking through your IR-camera on your helicopter, but not visible if you're a normal passenger.
