### ISSUE TITLE
Instruments that can be animated like parts

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#627]
I don't mean that the individual components can be animated, because obviously that's already possible. I'm talking about the instruments as a whole being able to move. This will allow a HUD-instrument that moves to always be in front of a player no matter where they look, such as those used by fighter and attack helicopter pilots. This would also help with the implementation of the locked target symbol from #626

**Comment by DonBruce64** [comment]
So what you're saying is you want to be able to animate the position of instruments on the physical vehicle like how parts can be moved?

**Comment by gyrohero** [comment]
Exactly

**Comment by DonBruce64** [comment]
In that case, it's not super hard to add animations to the instruments on the vehicle definition side.  I'll see what I can do.

**Comment by DonBruce64** [comment]
Implemented in V19.11.0.
