### ISSUE TITLE
When switching a pack to the new loader, items from that pack seem to disappear

### ISSUE THREAD

**Issue by gyrohero** [DonBruce64/MinecraftTransportSimulator#628]
I'm not sure if there's any way around this. The items despawn, though the vehicles and any parts on them do not.

**Comment by DonBruce64** [comment]
Not really any way, no.  The items on the new loader are registered under the core mod ID, not the pack, so there's no way to keep them from going "poof" when you change loaders.  TBH, I should have had them that way from the start.  Live and learn I suppose.
