### ISSUE TITLE
Players Standing on Vehicles Stutter

### ISSUE THREAD

**Issue by kandivia** [DonBruce64/MinecraftTransportSimulator#63]
Players that find themselves standing on top of vehicles, will stutter and find it difficult to get off. This also leads to "No Flying Allowed" disconnects on servers.

**Comment by DonBruce64** [comment]
This *should* be addressed better by the new collision system in the upcoming update.  I'll close this issue on release of that, but for now it's staying open for visibility.

**Comment by DonBruce64** [comment]
Turns out the new collision system didn't work.  Additionally, this bug is related to #10, as that bug details nearly the same thing.  However, to condense all the issues related to collision I'm putting them into one massive bug.  See #83 for that.
