### ISSUE TITLE
[BUG] Autoreloading (may) be borked, allowing for more ammo than the gun can hold to be loaded.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#632]
example: I have a cannon that only holds 5 bullets, but I'm able to use auto reloading to load 32 bullets in, or more.

**Comment by DonBruce64** [comment]
So can confirm this is an issue.  But only on the client-side it seems.  For some reason, bullets aren't decrementing on there.  It also would seem that auto-reload won't reload up to the capacity of the gun: I can only get your gun to auto-reload up to 1 bullet, not 5 bullets.

**Comment by DonBruce64** [comment]
Fixed in V19.11.0.
