### ISSUE TITLE
[BUG] Signs without a textObjects object don't load properly

### ISSUE THREAD

**Issue by Tim3Game** [DonBruce64/MinecraftTransportSimulator#634]
Hey, found an interesting bug, where when I place a sign and load the world again, if it has a missing ``textObjects`` object in it's ``.json`` file, it will not load correctly and produce an **NPE** in file ``TileEntityPole.java`` **line 40**. Looks like adding a simple != null  fixes that but I let that be your decision on how to solve it. Proberly this could happen on other objects in the ``.json`` files too, but I didn't currently came across another one.

latest.log: [https://paste.ee/p/gEjm4](https://paste.ee/p/gEjm4)

**Comment by DonBruce64** [comment]
Fixed in V19.11.0.
