### ISSUE TITLE
[Suggestion] Vertical center on wrapped text

### ISSUE THREAD

**Issue by Tim3Game** [DonBruce64/MinecraftTransportSimulator#637]
Hey,
Instead of just anchoring the rendered text to the top, it could be centered vertically, so when it get's wrapped and get's smaller, it retains it's position, so it doesn't drift of higher and higher. On the example image, you can see, that the smaller the text gets, the more off-center/higher it gets. This would be done on every alignment (left, center, right)

Example image:
![javaw_GEpltDfprW](https://user-images.githubusercontent.com/34278596/100553021-64ec9000-328b-11eb-9872-3ba2fc2317aa.png)

**Comment by DonBruce64** [comment]
Implemented in V19.11.0.
