### ISSUE TITLE
[suggestion?] Weapons will continue re-loading from vehicle inventory until at max cap.

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#639]
As it stands, A weapon with a capacity of say 50, will not re-load more than 1 unit of ammunition from the vehicle inventory no matter the amount in the unit. so a unit of ammunition with 1 shot will slow down the 50 capacity cannon to it's reload speed.

**Comment by gyrohero** [comment]
I believe this is addressed in #632

**Comment by DonBruce64** [comment]
Implemented in V19.11.0.
