### ISSUE TITLE
Crafting Station Enchancements

### ISSUE THREAD

**Issue by kandivia** [DonBruce64/MinecraftTransportSimulator#64]
With the multiple tabs and parts that the various crafting stations have, it gets real annoying to have to reopen the GUI and click back to where you want to be, especially when you need multiple wheels and such. Can the stations remember their place when closed and/or not close the screen every time you craft something?

**Comment by obsidian29** [comment]
I'd love that honestly. And it's so annoying to click through Blackthorne's pack. It'd be awesome to have a different selection system if possible, that isn't
click
click
click
click
click
click
click
click
click
click
ad nauseum.

**Comment by DonBruce64** [comment]
I can for sure have the stations remember what you looked at last.  But as to another crafting system, how would you suggest that work @obsidian29?

**Comment by DonBruce64** [comment]
That could be done, but it would require a re-do of the crafting GUI to allow for multiple icons.  As this issue is to have the GUI remember its last place, I'm going to do only that.  Once that's done we can address any lingering usability issues.

**Comment by DonBruce64** [comment]
Added features in V13.
