### ISSUE TITLE
[Suggestion] All vehicles having a full-brake option and a half-brake option (like with the half-throttle and the full-throttle).

### ISSUE THREAD

**Issue by CodeParrot14** [DonBruce64/MinecraftTransportSimulator#644]
All vehicles having a full-brake option and a half-brake option (like with the half-throttle and the full-throttle).

**Comment by DonBruce64** [comment]
Added something to allow this in V19.11.0.  It's not exactly what you wanted, but it should work well enough for all intents and purposes.
