### ISSUE TITLE
Request: Rocket engines (Impossible?)

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#65]
Hopefully self explanatory. Not sure if it's possible or not, though.

**Comment by DonBruce64** [comment]
Possible, but WHY?  You're already going to have issues with jets.  And the ICBM mod adds rockets for weapons and Galacticraft adds them for space travel.  What other reason would you have to use a rocket?

**Comment by DonBruce64** [comment]
Marking this as something I won't do.  While I can see rockets being fun, they really aren't what MTS is designed to emulate.  MTS is mainly for transport craft, not weaponized craft.  Yes, I know there are vehicles that use rocket-propulsion.  However they are few and far between, and are edge cases that I'm not interested in supporting.  Leave experiments with flaming thrusters to rocket mods I say.
