### ISSUE TITLE
[BUG] Fuel pumps seem to link to the first vehicle they've pumped

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#650]
Leta say you have a Blue Scout and White Brigadier.

You fill the scout up halfway, all is good.
You drive the scout away from the pump, move the GMC to the pump, click the pump and... it fills the scout, who is 30 blocks away.

Remove the scout and try to fill the GMC? It'll work until you have to refill your 172 at the pump, where it'll still fuel the GMC... who is 2k blocks away.

**Comment by DonBruce64** [comment]
Question: if you move that Blue Scout away, does the pump yell at you for the Scout being disconnected?  Does it actually stop fueling?

**Comment by boot2big** [comment]
I'm not sure, it seems to keep switching between intended behavior (closest vehicle within 16 blocks) and this behavior

**Comment by DonBruce64** [comment]
I think this got fixed with the changes I made in V19.15.5 with some PMs between me and another user.  If it's not, let me know and I'll re-open it, but they were able to re-create this by trying to place a vehicle but not having enough space, which left a phantom vehicle in the world.
