### ISSUE TITLE
Some text-on-parts issues

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#654]
First, when a vehicle has text fields, and a part has text fields, they don't get along and you get a crash. This can be seen on the UNU Scarab (bus) as it has license plates and a sign.
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5682113/latest.log)

Ideally, text fields would display the vehicle text first, then all parts and subParts in json order. If a vehicle fieldName has the same name as a part fieldName, it should be combined like all other text objects.

Next, if a vehicle has two different license plates the game crashes, but only when you try to edit the text. What's odd, is this even happens when the defaultText is the same, or the text has been changed. If both plates are the same, everything works fine.
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5682154/latest.log)

Ideally, if you change a plate, that change is reflected on all parts that use the same fieldName.

**Comment by DonBruce64** [comment]
Fixed as of V19.12.0.
