### ISSUE TITLE
Brakes lights stay on when the car is left in simpleThrottle and autoStart

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#655]
If you get out of a car with simpleThrottle and autoStart, you can't get the brake lights to turn off. One simple solution is to only have non-headlights/runninglights on when the ignition is 'ON' like in real vehicles. Or just disable the brake when players dismount since the parking brake engages anyway.

![2020-12-11_15 46 21](https://user-images.githubusercontent.com/36775575/101966265-efa68680-3bcb-11eb-89f5-91743dd51197.png)

**Comment by DonBruce64** [comment]
Fixed as of V19.12.0.
