### ISSUE TITLE
Door hitboxes of parts don't take part's rotations

### ISSUE THREAD

**Issue by Kadwinflo** [DonBruce64/MinecraftTransportSimulator#656]
Hi Bruce! i have found that if i rotate a part on a vehicle with "rot" property inside the json of the vehicle, the hitboxes from the doors of the part (inside the json of the part) won't rotate with that part as they should. it's anoying for things link containers because you can't oriantate the container using rotations

**Comment by DonBruce64** [comment]
Fixed as of V19.12.0.
