### ISSUE TITLE
[Suggestion] "invisible" seating

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#659]
Unlike the invisible seats in [part pack here], this invisible seat would instead make the playermodel invisible. This would make it possible to have better views on vehicles such as tanks while not exposing the player, or forcing them into third person. For example, something like flans mod could be done:
![2020-12-16_20 53 30](https://user-images.githubusercontent.com/33960693/102432332-50292f80-3fe1-11eb-9b57-4b5e35fde860.png)
The player has a clear view and is able to aim the main gun easily
![2020-12-16_20 53 28](https://user-images.githubusercontent.com/33960693/102432556-5ddeb500-3fe1-11eb-8e9f-c1db0f857fa7.png)
The player is also invisible, thus preventing "immersion" being ruined, while also making the vehicle more functional

**Comment by DonBruce64** [comment]
This is pretty much the whole point of the custom cameras.  You can define custom camera positions for viewpoints, and at those positions the player won't render, even if you're looking directly at them.

**Comment by boot2big** [comment]
Isn't this also possible with seat potion effects? [insert sans emote]
