### ISSUE TITLE
[BUG] Propellers do NOT cooperate with reverse gears.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#661]
https://user-images.githubusercontent.com/53581325/103188276-c8bba600-4895-11eb-9fd1-2bd54734397e.mp4

(in this video I had set the parking brake, held Gas and then put the engine into reverse while hopping out)

And yes, this froze my game

**Comment by DonBruce64** [comment]
Fixed in V19.13.0.
