### ISSUE TITLE
Shaders glitch with V19 camera system

### ISSUE THREAD

**Issue by MightyMackrel** [DonBruce64/MinecraftTransportSimulator#665]
On vehicles using the V19 camera system the camera starts to shake violently upon entering the vehicle. This could be dangerous to those with epilepsy so an urgent fix would be highly recommended... 
Attached are videos from TurboDefender and myself showing the issue: 
Turbo: https://youtu.be/r-eNAXYEBrk 
My video: https://user-images.githubusercontent.com/75394101/103941100-46997000-5126-11eb-8784-8554c4343003.mp4

**Comment by DonBruce64** [comment]
Fixed in V19.13.0.
