### ISSUE TITLE
Item getting bugged in the ground

### ISSUE THREAD

**Issue by JohnCena12345678** [DonBruce64/MinecraftTransportSimulator#667]
when you place a certain vehicle or entity after you are done using it you usually take it back into your inventory with a wrench. when you do so the item drops on the ground usually. however, it seems that the item gets bugged within a certain block.
Unless you are on that specific block where the item got bugged into, you cant see it. most importantly you cant take it.

![image](https://user-images.githubusercontent.com/44272691/104104433-9496ab00-52c1-11eb-8932-c4fa186dd460.png)
that's how items normally appear on the ground
Randomly, most of the time it gets bugged INSIDE a specific block. unless you are on that SPECIFIC BLOCK, you won't be able to see it or take it.

**Comment by DonBruce64** [comment]
Fixed in V19.13.0.
