### ISSUE TITLE
[BUG] When autostartEng is on for one player, the server copies it to all players.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#668]
If nobody has autostartEng on, nobody will have their vehicles auto start.
But if _one_ person turns it on, _everyone_ gets it.

**Comment by DonBruce64** [comment]
Yup, I can see exactly where this is happening.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V19.13.0.
