### ISSUE TITLE
Request: Nitrous Oxide Injection (Difficult? Impossible?)

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#67]
Keybind or button on dashboard to activate. Would drain at a set rate determined in the JSON for the engine. In an ideal world, it would boost power for the duration it's active, but also burn out the engine faster.

**Comment by DonBruce64** [comment]
While this is do-able, and is in the spirit of MTS, it's not something that is high on the MTS priority list.  Expect this to linger for a while, especially since the implementation would require somehow equipping vehicles with NOS, which is a fun bit full of fiddling in and of itself.

**Comment by fsendventd** [comment]
Alright. Better late than never.

**Comment by PearlCGDoesYT** [comment]
And we will need a bottle filler for the NOS for when it goes empty

**Comment by DonBruce64** [comment]
So after further thought and witnessing the scene of MTS, I don't see anyone making racing vehicles or users desiring to have super-performance.  Nearly all of them want cool vehicles that can go over ground and are fun to drive.  While Nitrous would be a fun thing to have, I don't see it being a worthwhile use of my time to code.

**Comment by fsendventd** [comment]
I should start making cars again just so you'll add all my performance enhancements.
