### ISSUE TITLE
Batteries drain and cannot be jumped.

### ISSUE THREAD

**Issue by DavinaDiva** [DonBruce64/MinecraftTransportSimulator#670]
Running a custom modpack with Immersive Vehicles - 1.12.2-19.12.0.

So we build our vehicles and it comes with some battery juice. Enough to barely start some vehicles and on others not enough to start at all. So I was able to get one vehicle working full fuel and everything required, and it ran and was able to jumpstart other vehicles. However, after leaving the game and coming back the batteries in that vehicle was dead. Lights were off and all but still died. Moving forward we made newer vehicles and have since been unable to jumpstart and charge any vehicles so we can drive them. batteries get linked and says that it's charging with jumper cables, disconnects after getting batteries to same level, but the vehicles cannot start. Is there anything we can do besides creative engines? or a little pushpack portable jumper battery or something? to me this is pretty game breaking as we cannot use the vehicles we built.

**Comment by DonBruce64** [comment]
Odd.  There should be more than enough battery juice to start a vehicle fresh.  You can get about 5-7 starts out of one before you need to let it run for a while and charge up.  There is a simpleThrottle bug that might be part of this (#668), but even so leaving the game shouldn't kill the battery unless it's out of fuel.  That's the only reason a vehicle won't start when cranking up.  Well, that or the vehicle is underwater, which I doubt is the case.

That being said, having a portable battery pack to auto-charge a vehicle's battery wouldn't be a bad idea.  The only thing I'm missing is an item texture for it.  I'll poke around our Discord for one and if I can get one I'll add such a feature to the next release.

**Comment by DavinaDiva** [comment]
Issue continues with and without the simple throttle. Any chance that battery pack would be in the next release for 1.12.2 😂😂

**Comment by DonBruce64** [comment]
Yup!  Working on the item icon right now.   Well, not *me*, but I've got the crew on it!

**Comment by DonBruce64** [comment]
Added in V19.13.0.

**Comment by DavinaDiva** [comment]
Holy cow that was faster than i thought it would be but thank you! Ill give it a shot then and hopefully it fixes everything for us. Thank you and do send the crew my thanks on behalf of my friend group as well!
