### ISSUE TITLE
[BUG] UNU Mod Packs Doesn't Load properly into 1.12.2 Server

### ISSUE THREAD

**Issue by BlackStarG5** [DonBruce64/MinecraftTransportSimulator#671]
I have all UNU packs in the mods folder of a 1.12.2 server. currently using MTS version 19.13.0. Packs like GAP load successfully but packs like UNU Civilian Pack doesn't seem to work properly. When a car is spawn through creative means it disconnects the player who spawned it. 

MTS: 19.13.0
UNU Packs: 3.5.0
UNU Civilian Pack: 3.5.0

**Comment by DonBruce64** [comment]
You'll have to get with UNU on this one.

**Comment by DonBruce64** [comment]
Closing, as UNU just dropped the V4 update, and this should be taken care of by that update.
