### ISSUE TITLE
SUGGESTION. Key functionality

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#672]
Remember that suggestion I had in the Discord for immersion? That one for keys????
Well... This YT video gave me the solution! An interactive hitbox defined in json for a player to right-click with a key that's linked to the vehicle! 
[Reposting here for relevence]
![unknown](https://user-images.githubusercontent.com/43540281/104267201-c8efa000-5456-11eb-977f-9abe984bc46b.png)

**Comment by DonBruce64** [comment]
This is actually do-able with current systems.  Just nobody has done it.  They can render the key in the ignition if the vehicle is un-locked, which signifies to car thieves that the car is just "itching" to be taken on a joy-ride.  Forcing this with a click-able would require all packs to update.  Not the best idea..  Flagging this as wontdo.
