### ISSUE TITLE
todays update to official pack broke dependencies

### ISSUE THREAD

**Issue by petulko8080** [DonBruce64/MinecraftTransportSimulator#673]
after today's update to official pack (from v19 to v20),  i got broken dependencies fro other MTS packs:
```
[09:13:58] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod mai (Mackrel Automotive Industries) requires [mtsofficialpack@[16.0.0,)]
[09:13:58] [Client thread/FATAL] [FML]: net.minecraftforge.fml.common.MissingModsException: Mod blueboyscaterpillarmtspack (MTS Caterpillar Pack) requires [mtsofficialpack@[1.0.0,)]
[09:13:58] [Client thread/ERROR] [FML]: An exception was thrown, the game will display an error screen and halt.
net.minecraftforge.fml.common.MultipleModsErrored: 
Missing Mods:
	unknown : need [16.0.0,): have missing

Missing Mods:
	unknown : need [1.0.0,): have missing

```

**Comment by DonBruce64** [comment]
I'm aware of that.  Those packs had over 1 month to make a simple change to their files and have not done so.  Until they switch to not using the OCP as a dependency (which they really shouldn't, as they don't need the OCP, they can use ANY parts pack), they won't work.  I'm going to leave this open so others know, but you'll have to get with those packs to have them fix their dependency issue.

**Comment by MightyMackrel** [comment]
MAI has a transitional beta out that circumvents this issue and updates around half the pack to V19 since December 27th, please use this.

**Comment by petulko8080** [comment]
thanks for info
omg, i don't know how I can missed info about this transitional beta with those big red letters :(
good work guys

**Comment by DonBruce64** [comment]
So, I'm closing this, as all the active packs have made the transition to the new loader.  Any pack that still has this error is abandoned, and I cannot support those packs.
