### ISSUE TITLE
[suggestion/reminder] Parameter to allow a seat to add "Inactive" to the gun selection cycle

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#677]
as the name states. just a simple parameter for the seat part on a vehicle to have an inactive state added to the weapon cycle. mainly for bombers, so that bombardiers can choose when to have the gun activated and deactivated without switching to a different seat, but is also good for systems where all weapons can/must be disarmed

**Comment by DonBruce64** [comment]
Implemented in V19.14.0.
