### ISSUE TITLE
MTS radio enhancement (Requires sound system to be altered)

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#678]
![image](https://user-images.githubusercontent.com/63666200/104830780-480e1b00-583f-11eb-97d5-19645d732ca6.png)
![image](https://user-images.githubusercontent.com/63666200/104830811-873c6c00-583f-11eb-831c-d69218141afb.png)
![image](https://user-images.githubusercontent.com/63666200/104830828-ab984880-583f-11eb-9adc-d04111f636e3.png)
![image](https://user-images.githubusercontent.com/63666200/104830851-dbdfe700-583f-11eb-9186-7b94a66e9cd8.png)
![image](https://user-images.githubusercontent.com/63666200/104830856-eac69980-583f-11eb-88b1-13dc3803bc7e.png)
![image](https://user-images.githubusercontent.com/63666200/104830865-03cf4a80-5840-11eb-8d39-b5d736ec5b84.png)
![image](https://user-images.githubusercontent.com/63666200/104830867-0cc01c00-5840-11eb-9e65-cb0d1e63ae8b.png)
![image](https://user-images.githubusercontent.com/63666200/104830880-38db9d00-5840-11eb-863c-8a894c83b871.png)
![image](https://user-images.githubusercontent.com/63666200/104830884-498c1300-5840-11eb-8e1e-c47e04d05319.png)

**Comment by DonBruce64** [comment]
This will likely happen when I make it so clients and servers can share both files and radio states.  This is a significant change to the systems, though it's also something I want to eventually do.  Vehicles and whatnot come first, however.

**Comment by DonBruce64** [comment]
Implemented in V19.15.4.
