### ISSUE TITLE
Request: Turbochargers/Superchargers (Prolly difficult)

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#68]
Turbochargers would work based off engine RPM and fuel consumption at said RPM (to simulate exhaust-driven turbines). Superchargers would work based off engine RPM and a gear ratio set in the JSON (belt-driven screws). Both would boost torque (and maybe horsepower a bit), but also cause the engine to over-rev easier and to accumulate hours faster, and maybe to use fuel a bit faster. They would have a max boost pressure also set in the JSON to prevent runaway, and turbos would have the number of them set in the JSON as well (*maybe*). Could be difficult, but worth it in my opinion. Let me know what you think.

**Comment by DonBruce64** [comment]
While I see a use for this, #67 with Nitro is my preferred solution to getting more power out of engines.  Turbo/Super chargers would require a new part system and would have to be tweaked significantly to get them to work right.  Nitro is simpler to implement and is a hair more arcade-y which I feel will work better with more people's ideas of how the cars should control.

**Comment by fsendventd** [comment]
You mean slapping a giant turbo on your engine and then blowing it up isn't arcade-y? Anyway, I fail to see how it would require a new part system. Just a few engine JSON variables. As to the tweaking, I'm the master of tweaking things until they work right.
