### ISSUE TITLE
[BUG?] Gear ratios or propeller ratios of 0 simply crash the game instead of forcibly staying in neutral.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#680]
If you use either of these... 
![image](https://user-images.githubusercontent.com/53581325/104989352-4469c800-59e8-11eb-95e4-99d2b35850b4.png)
![image](https://user-images.githubusercontent.com/53581325/104989362-492e7c00-59e8-11eb-95df-8a79ec253576.png)
... in a car, the game crashes when the car is shifted into Reverse.

(Additional note is that while this doesn't _close_ the game, it crashes the ingame server and freezes the client.)
[crash-2021-01-18_23.56.17-server.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5833723/crash-2021-01-18_23.56.17-server.txt)

**Comment by DonBruce64** [comment]
This is likely due to the shifting code affecting all engines.  Shifting shouldn't affect engines that have jet power, as those shouldn't ever shift out of "first" gear.  All others, like those that drive propellers and wheels, should.

**Comment by DonBruce64** [comment]
Fixed in V19.14.0.
