### ISSUE TITLE
Decors ignore smooth shading and triangulates all faces

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#682]
What is say in the title, decors seem to not show smooth shading, and makes things ugly by triangulating it's faces
![2021-01-19_22 37 45](https://user-images.githubusercontent.com/34656590/105068805-578f9d00-5aa7-11eb-9ae4-6fe1c0cceec7.png)
![2021-01-14_23 48 37](https://user-images.githubusercontent.com/34656590/105068853-5fe7d800-5aa7-11eb-8d45-f5537d2ec693.png)
![2021-01-14_23 48 49](https://user-images.githubusercontent.com/34656590/105068941-6f672100-5aa7-11eb-9d79-20c80c5ddaf9.png)
![2021-01-14_23 49 14](https://user-images.githubusercontent.com/34656590/105069040-8279f100-5aa7-11eb-9e49-e742ec998a7e.png)

**Comment by DonBruce64** [comment]
Fixed in V19.14.0.
