### ISSUE TITLE
[BUG] some funky stuff with the new player tweaks. 

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#689]
When the player tweaks are turned off the player is always rendered as standing, and items the player holds are always placed where they would be when standing even when the player tweaks are on.

always standing:
![2021-01-22_09 14 22](https://user-images.githubusercontent.com/44233145/105516295-f2989a80-5c92-11eb-88c1-fbe42a485c9b.png)

items being wonky (holding a seat here): 
![2021-01-22_09 18 14](https://user-images.githubusercontent.com/44233145/105516320-f9bfa880-5c92-11eb-8e50-6d007b1637b0.png)

**Comment by DonBruce64** [comment]
Fixed in V19.14.0.
