### ISSUE TITLE
Skins added by other packs are put in that pack's creative tab (or appended with "Added by X" in the desc.)

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#692]
The new(ish) skins system adds those skins directly to the pack the original vehicle is from. 

I think it would be best that skins are added to the tab of the pack that added them (for example an UNUverse UNU Steed skin is in the UNUverse tab instead of the UNU Civilian tab), that way one pack's tab doesn't get clogged with a bunch of skins added by other packs.

If this is too difficult to do, I would suggest at least appending "/nSkin Added by <packname>".

**Comment by DonBruce64** [comment]
8fab4db6e793140ae708ba5bf5b824e0ab6fa416

**Comment by DonBruce64** [comment]
Added variables to allow for this in V19.14.0.
