### ISSUE TITLE
Support for translucent textures/colored window textures

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#698]
![image](https://user-images.githubusercontent.com/63666200/106228145-fe5ef200-61a7-11eb-95cb-875449dbe366.png)
My reasoning for it is a bit confusing, so i'll try to explain better in case it needs a better way to be explained
ignoring car window glass, this can be used for high detail models that have things like bulbs inside the light housing
~~i'll be honest, my brain can't think of much else, but boy would translucent textures be nice~~
~~assuming it doesn't hate shaders~~
~~also yes i was nagging because i was converting a model from something else for MTS~~

**Comment by DonBruce64** [comment]
Added in V19.15.0.
