### ISSUE TITLE
Towed vehicles don’t interact with the world

### ISSUE THREAD

**Issue by TheOddlySeagull** [DonBruce64/MinecraftTransportSimulator#699]
Towed vehicles won’t break blocks nor having their hitboxes colliding.

**Comment by DonBruce64** [comment]
This will take some doing, but should be feasible given how forces are applied to vehicles.  I just need to have the trailer provide an equal, yet opposite, force to the vehicle.  Biggest issue will be how they handle turns, but eh, if y'all want Swift Trucking Simulator that's what y'all gonna get.

**Comment by DonBruce64** [comment]
Implemented, or Fixed depending on how you look at it, V19.15.0.
