### ISSUE TITLE
Client crash - cannot be cast to minecrafttransportsimulator.blocks.decor.BlockDecor6AxisOriented

### ISSUE THREAD

**Issue by ProsperCraft** [DonBruce64/MinecraftTransportSimulator#7]
https://gist.github.com/ProsperCraft/8019517efdbf19a9b7622a93047cc2ed

I was walking around a decorated city and had this crash.
I may have been sitting watching the lights for a while answering discord questions.

Here is a screenshot of the location of the crash. 
![2018-10-14_08 16 38](https://user-images.githubusercontent.com/4427684/46917964-8d20b400-cf89-11e8-9c1c-1272eacae8c4.png)

**Comment by DonBruce64** [comment]
This is for sure a bug.  It looks like Minecraft is attempting to load a decor Tile Entity without a block being present.  That's like having a chest inventory in a space where there is no chest.  Safe to say, that's not good.  Will fix.

**Comment by DonBruce64** [comment]
Should be fixed in 11.2.1.
