### ISSUE TITLE
Crazy physics glitch that make me travels the map

### ISSUE THREAD

**Issue by Naeso** [DonBruce64/MinecraftTransportSimulator#70]
Hello.

I was playing on a flatmap, testing the mod. And then, I was driving the basic truck (GSM something, I don't recall properlly. But It was the truck from the basic pack). While stopping my engine and my gas being down, my truck got crazy and I was ejected thought the map at X: -45705472 at some crazy speed. It was like instantly. And then my game crashed.

I can't really give you more info right now but if you need more on my specs or the mods I was using, I could give it to you later if it's important

**Comment by DonBruce64** [comment]
I'll do some testing on my end to see if I can replicate this.  It looks to be a physics bug, so will likely be something I can replicate if I do exactly what you did.

**Comment by DonBruce64** [comment]
Can't replicate.  V15 overhauls the ground physics system, and car engine physics has changed since this bug was submitted, therefore I suspect it is no longer valid.  Closing.
