### ISSUE TITLE
Vehicle thrust translation and rotational thrust via animations

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#702]
Allows for more granular control of vehicle forces, as well as opening more possibilities
Besides some things like "turnsWithSteer" (or else cars might be able to steer when stopped if somebody doesn't know how activators/inhibitors work, plus other minor "visual" artifacts), this can void some amount of vehicle physics code, as well as a few possible future tickets/pull requests ~~my understeer/oversteer pull requests that fell flat on day 0~~

Side note: There would need to be a way to make thrust global or local
Maybe a boolean value that says "localThrust" : true, or using "applyAfter" (though the applyAfter method would be "jank")

**Comment by DonBruce64** [comment]
So, having the ability to modify forces via animations is very hard.  Mainly due to how the force system is set up.  If there's handling issues, those should be solved via internal code changes, NOT external animations applied on a per-pack basis.
