### ISSUE TITLE
iv 19.14.0 gauge issue

### ISSUE THREAD

**Issue by zacharyhenry** [DonBruce64/MinecraftTransportSimulator#703]
(issue on iv 19.14.0 )

i changed the Iv version back to 19.13.1 and saw the gauges where normal but kept ovs(offical v set) v20

i have no shaders installed

forge version 14.23.5.2855

issue
https://youtu.be/meUA1R2cDck

**Comment by DonBruce64** [comment]
Odd, I haven't seen that, but haven't been looking for that either.  As this appears to be an issue with the main code, I'm flagging it as such.

**Comment by boot2big** [comment]
Another strange thing to note is that right around the top of the gauge, it reverses and goes back to the end...

**Comment by DonBruce64** [comment]
It would appear this is due to the instruments (incorrectly) specifying absolute value for their rotation.  Will have to fix when I next update the OCP.

**Comment by dino-brewster** [comment]
fun fact the brakes are messed up one i can no longer break it goes in to reverse and does not stop

**Comment by DonBruce64** [comment]
Fixed in OCP V20.
