### ISSUE TITLE
SUGGESTION A new wheel variable/type?

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#705]
here's an odd thought... How does immobile wheels sound?
I.E. A wheel type that prevents vehicle movement, useful for elevating fresh vehicles with a default part, like a cinderblock or something?

**Comment by DonBruce64** [comment]
That's already possible.  You just make a wheel part that doesn't flag itself as a wheel, and set that as the default part.  Optionally, make it a non-wheel with just collision boxes.
