### ISSUE TITLE
vehicle indestructibility

### ISSUE THREAD

**Issue by polarisow** [DonBruce64/MinecraftTransportSimulator#707]
How can I set the indestructibility of vehicles using e.g. a configuration file?

**Comment by DonBruce64** [comment]
You cannot.  There is no such config setting.

**Comment by boot2big** [comment]
Would such a config setting be possible to implement? Some racing servers might benefit from it... _glances at Trin TXS_

**Comment by DonBruce64** [comment]
Yes, such a setting would be.   I'll add it to the to-do list.

**Comment by polarisow** [comment]
When will we be able to count on new updates for the immersive vehicle modification?

**Comment by DonBruce64** [comment]
Added in V19.15.0.
