### ISSUE TITLE
No vehicle damage

### ISSUE THREAD

**Issue by polarisow** [DonBruce64/MinecraftTransportSimulator#708]
The problem with destroying the vehicle in the modification of the immersive vehicle is quite serious. An additional function in the configuration of the mod would be very useful, thanks to it many errors in collisions between vehicles and objects such as tree leaves, which are actually quite delicate, here they cause complete destruction of the vehicle. Thank you in advance and best regards.

**Comment by DonBruce64** [comment]
True.  I ended up re-opening #707 as an enhancement to add this, so I'm going to close this ticket as a duplicate.  I'll have such a config in the next release.
