### ISSUE TITLE
mtscraftingoverrides.json not working

### ISSUE THREAD

**Issue by Maenorg** [DonBruce64/MinecraftTransportSimulator#710]
Versions of Mods installed:
Immersive+Vehicles-1.12.2-19.14.0
MTS_Official_Pack_V20
UNU+Parts+Pack+[MTS]+1.12.2-19.13.0-4.0.1
UNU+Civilian+Pack+[MTS]+1.12.2-19.13.0-4.0.0

As stated on the Discord the overrides file doesn't work for parts.
When activating the recipe dump to the file it only dumps the recipes which are crafted using the Minecraft Crafting Table.
I haven't tried altering one of those recipes, but I think they may work.
Added the dumped overrides file but had to change to .txt from .json because of github.
[mtscraftingoverrides.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5975846/mtscraftingoverrides.txt)

**Comment by DonBruce64** [comment]
Ah, I think I see what's happening.  It's not dumping the modded packs, even though it *should*.  That should be fix-able easily enough.

**Comment by DonBruce64** [comment]
Fixed in V19.15.0.
