### ISSUE TITLE
[Suggestion] Regular blocks

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#711]
Add the ability to add regular blocks via MTS, along with stair and slab variants if possible.

**Comment by boot2big** [comment]
Definable slipperiness? 👀

**Comment by DonBruce64** [comment]
So, I'm not sure about this one.  Purely because I'm not sure if it'll fit into the existing MTS systems well enough or will break them and be a PITA.  I'm going to table this as a backburner until I'm sure about it.

**Comment by DonBruce64** [comment]
So, finally made up my mind.  This is gonna be a wontdo due to how it fits into MTS's systems.  There are other ways to get this, but it won't be in MTS.
