### ISSUE TITLE
Game crashed while initializing game error (no such method)

### ISSUE THREAD

**Issue by S1lent-Echo** [DonBruce64/MinecraftTransportSimulator#712]
I am trying to get a mod for myself so i can enhance my roleplay but, I cant get it to work. here is the crash file thingy 
 
[crash-2021-02-14_13.31.51-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/5978394/crash-2021-02-14_13.31.51-client.txt)

it just keeps crashing each time I try it.

**Comment by DonBruce64** [comment]
You're using a horridly obsolete version of Minecraft Forge.
You're using version 2655.
MTS uses 2768.
Forge currently recommends 2854.

Update your Forge and that error should go away.  Let me know if it doesn't.

**Comment by S1lent-Echo** [comment]
ok I will try that

**Comment by S1lent-Echo** [comment]
thank you so much it worked!

**Comment by S1lent-Echo** [comment]
but one quick question do you know how to paint the cars because when I try it does nothing.

**Comment by DonBruce64** [comment]
What are you trying?

**Comment by S1lent-Echo** [comment]
I'm trying to paint the cars in pokers garage and it doesn't work.

**Comment by DonBruce64** [comment]
Again, you need to tell me WHAT doesn't work.  What are you trying to do?  How are you trying to do it?  The steps you are taking.  Just saying "It no work" does not help me figure out why.

**Comment by S1lent-Echo** [comment]
so whenever  right click on the paint tool on a car it just says blue dye and nothing else. I cant paint it. I tried to put dyes in my inventory but that didn't work either.

**Comment by DonBruce64** [comment]
Does it require "air" in some blank areas?  Can you post a picture?  Or perhaps join the Discord?  Cause if there is a material issue, Poker needs to know.

**Comment by S1lent-Echo** [comment]
ok I will join the discord and see.

**Comment by S1lent-Echo** [comment]
it shows this 
![Screenshot (1)](https://user-images.githubusercontent.com/79059465/107889497-995e0880-6ed8-11eb-867b-0faa52a23d1f.png)

**Comment by DonBruce64** [comment]
Well, you only have that one color it would appear, as you can't select others.  You'll have to ask Poker to make more.

**Comment by S1lent-Echo** [comment]
but i cant click on it.

**Comment by DonBruce64** [comment]
Exactly what I said.  You can't select others as those buttons are greyed-out.  Therefore you can't change the color because no other colors are defined.  And therefore you need to ask Poker to make more colors.

**Comment by S1lent-Echo** [comment]
oh ok thank you.
