### ISSUE TITLE
[ENHANCEMENT] Definable maxSafeRPM?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#713]
By default if this is not specified in the engine JSON, it defaults to the MTS auto-calculated maxSafeRPM (above maxRPM when said variable is 2500 or lower, is calculated differently when maxRPM is 15k+)
However, if one wanted to make an electric motor, or a slightly more durable and/or realistic ICE, they could add and define a maxSafeRPM manually.

(example image)
![image](https://user-images.githubusercontent.com/53581325/108021086-ca7b2d80-6feb-11eb-867a-a4c5bcc66794.png)

**Comment by DonBruce64** [comment]
Surprised it took this long for someone to make this ticket.  I'll do my best to get this in.

**Comment by DonBruce64** [comment]
Added in V19.15.0.
