### ISSUE TITLE
[Bug]Crash when clicking on poles with tires etc.

### ISSUE THREAD

**Issue by TGN428** [DonBruce64/MinecraftTransportSimulator#719]
Hey
I found a bug.
The bug crashes the game when triggered. I will now tell what i did.
I started my minecraft with this mod and some content packs(the UNU Civil pack and their must have packs) and loaded in to a minecraft world. I took UNU poles and placed them. now i took a vehicle and placed it on the pole and then minecraft crashed.

Here´s the latest log from my minecraft:
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6024892/latest.log)

**Comment by DonBruce64** [comment]
There's nothing in there that indicates a crash.  Could you post the crash report?

**Comment by TGN428** [comment]
[crash-2021-02-23_16.37.59-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6029973/crash-2021-02-23_16.37.59-client.txt)
Here is the Crashreport

**Comment by DonBruce64** [comment]
Rodger that.  I know exactly where this is.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V19.15.0 due to the new pole interaction system removing this potential failure point.
