### ISSUE TITLE
It is impossible to remove a part if the subPart is smaller than the parent part

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#722]
If you place a small part (such as a hubcap) onto a larger part (like a wheel), then everything gets stuck.

You can't remove the smaller part because it is 'blocked' by the larger pert's hitbox, and you can't remove the larger part because it is locked in by the subpart. A solution to this would be to have the wrench not interact with lower-level parts during the 'breaking' interaction (but it still interacts with them on right-clicking).

**Comment by DonBruce64** [comment]
Fixed in V19.15.0.
