### ISSUE TITLE
Horrible scalability of the IV interfaces

### ISSUE THREAD

**Issue by StarterCraft** [DonBruce64/MinecraftTransportSimulator#725]
I have a 1920x1080 HD monitor, and I usually play Minecraft with the `Standard` interface scale. But on this scale, it is impossible to use IV properly, because its' interfaces look like this:
![2021-02-28_18 48 33](https://user-images.githubusercontent.com/43516901/109415771-9d6c4900-79f5-11eb-8927-65c77808a43d.png)
Furthermore, this is the config interface, and it is rendered with a normal size:
![2021-02-28_18 53 24](https://user-images.githubusercontent.com/43516901/109415915-5f235980-79f6-11eb-9ed4-8d78f4cf4dc0.png)

As you can see, the interface's size is so small that even the letters are not rendered normally, they pixelize. How do I fix this? No config options for interface scaling were found in IV configuration...

**Comment by fsendventd** [comment]
If you set your UI scale to "large" or "auto" that fixes it. Barely anyone plays on the "standard" UI option so the textures are designed for "large" and "auto" as those are much more common.

**Comment by DonBruce64** [comment]
Can you post a picture of the creative tab?  Because that config GUI should be the same size as the creative tab.

**Comment by StarterCraft** [comment]
The interface with the Standard option (full-screen mode):
![2021-03-01_08 48 58](https://user-images.githubusercontent.com/43516901/109439877-15c12180-7a6b-11eb-855c-f31f21be2a61.png)
The interface with the Auto option (full-screen mode, it is WAY too huge):
![2021-03-01_08 46 25](https://user-images.githubusercontent.com/43516901/109439904-312c2c80-7a6b-11eb-89fb-0703b63fde34.png)

**Comment by StarterCraft** [comment]
> Can you post a picture of the creative tab? Because that config GUI should be the same size as the creative tab.

There is no problem with the config tab, only with the plane UI.

**Comment by DonBruce64** [comment]
I'm flagging this as a not-bug given what you've shown.  In normal mode, the plane panel is the same size as all other GUI components.  Yes, it is small and only takes up 1/3 of the screen, but if you look at the sizes of your normal creative GUI vs the auto-scaled one, you can see that *every* GUI is being scaled properly.  You don't want the normal inventory to take up 1/2 the screen?  Well, now that you've shrunk it to 1/2 its size, you've shrunk everything to 1/2 its size.  That includes the hotbar, AND the HUD, as they're linked and part of the overlay rendering MC does.

Nothing I can do here I'm afraid.  If you want tiny GUIs, then you're going to get tiny GUIs.  Be them creative inventories, config screens, or vehicle HUDs.

**Comment by StarterCraft** [comment]
I have done some investigation today. I downloaded a specific mod called `Scaling GUIs`. It detected only a single GUI class referred to IV, and it is `minecrafttransportsimulator.mcinterface.BuilderGUI`. If this GUI class scale will be set to `LARGE` via the `Scaling GUIs`, the scale that is used for Minecraft `LARGE` setting is NOT shown, but if the entire Minecraft GUI scale will be set to `LARGE`, the IV's GUI scale will become larger.
There is something strange about the scaling issue. This is that the issue appeared in a IV version later the v15.10. I had switched to 19.14 yesterday, and I had faced this problematic issue.

**Comment by StarterCraft** [comment]
And one more detail: the scalability problem is present only with the following GUIs:
- Vehicles' instruments setup screen:  ![2021-03-01_14 26 01](https://user-images.githubusercontent.com/43516901/109459775-6b60f280-7a9a-11eb-8334-9fab7f1997e1.png)
- Vehicles' U-Panel and the basic interface of the vehicles: ![2021-03-01_14 26 20](https://user-images.githubusercontent.com/43516901/109459805-79167800-7a9a-11eb-8f15-0b8b35ee7bb1.png), ![2021-03-01_14 30 44](https://user-images.githubusercontent.com/43516901/109459935-baa72300-7a9a-11eb-9aa2-35dba320d4b6.png)
- All the production equipment (example): ![2021-03-01_14 28 00](https://user-images.githubusercontent.com/43516901/109459979-d1e61080-7a9a-11eb-9b51-d3f7d3f78366.png)

The issue is not present in the following GUIs:
- Configuration screen (opened in the top): ![2021-03-01_13 50 46](https://user-images.githubusercontent.com/43516901/109460143-1d98ba00-7a9b-11eb-9271-7951b03458a8.png)
- Beacon's GUI: ![2021-03-01_14 26 48](https://user-images.githubusercontent.com/43516901/109460213-3903c500-7a9b-11eb-8aab-645c767d7c3a.png)
- Text markers editor's GUI: ![2021-03-01_14 26 38](https://user-images.githubusercontent.com/43516901/109460313-546ed000-7a9b-11eb-9af9-4f17cbf8daa4.png)

There is a possibility that the problem holds inside of the GUIs' textures.

**Comment by StarterCraft** [comment]
It would be better to have the problematic GUIs size in the Standard scale at least two times larger.
