### ISSUE TITLE
part_present variable doesn't work on parts

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#726]
I am trying to toggle visibility on a part using the part_present variable, but it doesn't do anything. It took me an hour to realize that it was because the part_present variable just plain doesn't work on subParts.

An example of this can be seen in the UNU Standard Seat with the Seatbelt Item in the UNU DEV I pm'd you.

If subParts using part_present would much up the part number indexing (or isn't possible because they're subParts, not parts), having a subpart_present variable would work fine.

**Comment by DonBruce64** [comment]
I remember fixing this sometime, but I can't remember when. As the bug isn't present in 19.15.0 though, I'm closing this ticket.
