### ISSUE TITLE
[Sponge] Cannot reenter planes after entering and exiting

### ISSUE THREAD

**Issue by baddiePRO** [DonBruce64/MinecraftTransportSimulator#73]
I just tried to enter a plane seat after entering and exiting, and cannot even get in. there is a seat and I can only guess it is a bug.

**Comment by DonBruce64** [comment]
What mods and version of MTS are you running?  I seem to recall someone having this issue with Sponge, but I'm not sure.

**Comment by baddiePRO** [comment]
I'll send you the mudpack, if I can get it from the host lol.

**Comment by baddiePRO** [comment]
can I give you the twitch link?

**Comment by baddiePRO** [comment]
https://minecraft.curseforge.com/projects/terras-starlight

**Comment by DonBruce64** [comment]
This is due to Sponge not calling the PlayerDismountEvent during dismount operations.  Bother them for a fix as they are breaking core Forge event code!

**Comment by DonBruce64** [comment]
Should be fixed in V16.0.0.  Can't seem to get anyone to test these things...
