### ISSUE TITLE
Teleporting a random player in Multiplayer to my seat

### ISSUE THREAD

**Issue by ELIASCocaCola** [DonBruce64/MinecraftTransportSimulator#730]
Wenn im trying to sit in a seat of a Car somtimes someone else gets randomly teleported into the seat and this random happens sometimes.

**Comment by ELIASCocaCola** [comment]
Pls help

**Comment by DonBruce64** [comment]
Going to need more information.
Which IV are you using?
What are you doing when this happens?
What is the other player doing?
How far are they from you?

**Comment by ELIASCocaCola** [comment]
Ok, if i klick right klick on a seat of a vehicle someone else gets teleported into randomly, the other player can stand as far the Minecraftworld goes, the other player has to do nothing, its random witch player is teleported to my seat. It happens like all 4th try, to sit in my car. then someone else gets teleported into the seat or above the seat if the player is flying trou the world in Creativ mode. Im using my own second Computer with a Forge server and i changed nothing in the mod, im using a vpn and an ip not a port, maby this will help i hope. Question, whats IV stands for? Btw sry for my grammar im not the best in english.

**Comment by DonBruce64** [comment]
Very odd.  I haven't had anyone with this issue, but that doesn't mean it's not valid.  I'm surprised it's trying to mount them all the way across the world.

IV is Immersive Vehicles.  Or the name of this mod.  I need the version number of the file you have to ensure that I can cross-check my code with what you are seeing.

Are you running a cracked server?
Do you and your other player have normal accounts or cracked accounts?
Are you running Sponge/Bukkit/Spigot or any server-plugin system?

Asking because it sounds like the mod is getting players mixed-up, which it shouldn't be.

**Comment by ELIASCocaCola** [comment]
Im using the newest version: Immersive Vehicles-1.12.2-19.15.1.jar
Im running a normal server on my second PC (no cracked) and normal Accounts.
Im using only Forge and no Pluginsystem. I hope i helped...

**Comment by DonBruce64** [comment]
Odd.  Very odd.  When the player gets teleported, do they "ride" in the vehicle or are they dismounted and can walk around without pressing left-shift...

**Comment by ELIASCocaCola** [comment]
They can do whatever they whant, sit or walk or fly they will be teleported from everywehre and they will be randomly picked when someone is trying to sit in a vehicle. But sometimes it goes and you can normaly sit in the vehicle without someone is teleporting to you.

**Comment by DonBruce64** [comment]
Does this happen now as of V19.15.2?

**Comment by ELIASCocaCola** [comment]
Yes

**Comment by DonBruce64** [comment]
Drat.  Would you be able to join the Discord so I can throw some test builds at you to figure out exactly why players are warping to places they shouldn't?

**Comment by ELIASCocaCola** [comment]
Yes pls, i joined your Discord

**Comment by ELIASCocaCola** [comment]
Ok, Im not sure if that helps but i switched from VPN to a Port Connection, Started a new World and i installed a new Server in a new Folder, with the newest version of Forge 1.12.2 - 14.23.5.2855 and still no succes, the Bug is still there.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
