### ISSUE TITLE
[BUG?] MaxSafeRPM *seems* to be setting the maximum safe rpm to the maximum total rpm

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#731]
150cc engine json
![image](https://user-images.githubusercontent.com/53581325/110230496-5ee7fa00-7edf-11eb-901e-422381228087.png)
150cc engine ingame
![image](https://user-images.githubusercontent.com/53581325/110230499-64454480-7edf-11eb-959b-872a6f59fe43.png)

**Comment by DonBruce64** [comment]
Fixed in V19.15.1.
