### ISSUE TITLE
Constantly damage while driving

### ISSUE THREAD

**Issue by Richie1710** [DonBruce64/MinecraftTransportSimulator#733]
I'm getting damage while driving since 19.15.0

**Comment by DonBruce64** [comment]
This was reported last night and patched in commit 5dc034d073643784fe2a64e9d0df3ecaae96ca61.  Will have the fix out on Curse sometime in the next hour.

**Comment by DonBruce64** [comment]
Actually out now.  Fixed in V19.15.1.

**Comment by Richie1710** [comment]
Thanks. Tested. no damage anymore
