### ISSUE TITLE
Camera rotation animations messed up in v19.15.1

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#735]
Just putting this here in case it's needed again

![image](https://user-images.githubusercontent.com/63666200/110273555-12a5c400-7f8a-11eb-87ec-9ee9c3f6baa9.png)

https://user-images.githubusercontent.com/63666200/110273565-19ccd200-7f8a-11eb-800c-c7ca1d5fb8b6.mp4

**Comment by DonBruce64** [comment]
Fixed in V19.15.2.
