### ISSUE TITLE
15.1 Projectile hitbox issue 

### ISSUE THREAD

**Issue by mic2139** [DonBruce64/MinecraftTransportSimulator#736]

**Comment by DonBruce64** [comment]
Check this with just IV.  Issue doesn't persist.  There's some other mod causing this, and unless we can figure out which mod is mucking with arrows, then there's nothing I can do.

**Comment by mic2139** [comment]
It's "Iblis Headshots" causing the issue
It creates a thin hitbox at the centre of the head
which projectiles probably hit when fired downwards
this occurs exclusively in the latest version of IV's presence

**Comment by DonBruce64** [comment]
Fixed in V19.15.4.  Likely due to these changes: b554cafdd755b038003d9966b7458cd0bdd0a927
