### ISSUE TITLE
[ENHANCEMENT] Locking brakes/parking brakes?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#737]
1- When the parking brake is engaged, either all 4 (or more) wheels, or simply the rear wheels, "lock up" (Stops rotating, makes a ton of smoke, eventually risks popping if the wheel allows it).
If, somehow the vehicle doesn't *have* rear tires (or any wheels at all), normal braking with ground devices should still occur (Treads, front wheels, non-wheel devices, etc)
If the vehicle is moving slow enough, the wheels shouldn't lock (perhaps 3 Blocks per Second or slower)

2- An "ABS" (lockableBrakes) variable for vehicles, where by default is false, and the vehicle simply brakes normally.
However, if true, all tires (and perhaps treads) should skid when braking if the vehicle is moving fast enough, and the controller brakes too hard.

I understand if both of these suggestions are too realistic/immersive/complicated, though

**Comment by DonBruce64** [comment]
Sooo make it so you can't put the parking brake on at high speed, or it makes a lottta smoke?  What does that gain you?

**Comment by boot2big** [comment]
Mostly a lotta smoke, to be honest

It would probably look pretty cool, to be fair
