### ISSUE TITLE
FP Some of the Addon Packs are not detecting the latest version of this mod

### ISSUE THREAD

**Issue by PliskintheSaltyFork** [DonBruce64/MinecraftTransportSimulator#739]
The following addon mods only work with v16 and older.

Diamond Warriors Team Pack
https://www.curseforge.com/minecraft/mc-mods/diamond-warriors-team-mts-content-pack
Caterpillar Pack
https://www.curseforge.com/minecraft/mc-mods/transport-simulator-caterpillar-pack
The FightingPickles VP
https://www.curseforge.com/minecraft/mc-mods/fighting-pickles-vehicle-pack-for-mts-iv
Turbo's Accessories and Parts Pack
https://www.curseforge.com/minecraft/mc-mods/turbos-parts-pack

**Comment by DonBruce64** [comment]
Bringing in @RishiMenon2004 here to ask about the parts pack, as I coulda swore he updated that.

**Comment by DonBruce64** [comment]
Also, this isn't really a bug, as much as an issue with those packs.  They're still using the old loader, and hard-coding a dependency, both of which are a Bad Idea.  The Caterpillar and Pickle's packs will likely never get updated, so they're pretty much sunk.  But the other two are somewhat active, so should be fixed here.  Once those two update I'll mark this as resolved.

**Comment by DonBruce64** [comment]
Can confirm that Turbo's Pack is now updated.

**Comment by DonBruce64** [comment]
Can confirm that the Caterpillar Pack is now updated.

**Comment by boot2big** [comment]
https://www.curseforge.com/minecraft/mc-mods/diamond-warriors-team-mts-content-pack/files/3642670
Should be fixed now? close? (:

**Comment by DonBruce64** [comment]
Nope, FP is still not updated.

**Comment by DonBruce64** [comment]
After multiple attempts to contact the pack author of Fighting Pickle's pack, no resolution has been given.  Therefore, I'm closing this ticket as they have abandoned their pack and given nobody the ability to fix the issues.
