### ISSUE TITLE
Request: Fuel Canisters

### ISSUE THREAD

**Issue by Mephestrial** [DonBruce64/MinecraftTransportSimulator#74]
Fuel canisters that can only be filled at fuel pumps and use the same fuel storage code as the vehicles, thus avoiding forge's constant changes to liquid handling.

**Comment by DonBruce64** [comment]
This can easily be done if the items are carrying MTS-converted fuel rather than the liquids themselves.  Once I get an item texture I'll see what I can do about it.

**Comment by TheCactus27** [comment]
Perhaps you could use a system similar to the fuel pump, where you have place the jerrycan down in order to begin fueling. When picked up, the jerrycan holds liquids inside it, similar to immersive engineering barrels and other barrels like that.

**Comment by DonBruce64** [comment]
Added in V15.3.0.
