### ISSUE TITLE
doors collision rotated more that normal collision 

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#740]
example video here

https://user-images.githubusercontent.com/79125581/110798723-08970480-82ad-11eb-8a12-f9ec6a883206.mp4

https://user-images.githubusercontent.com/79125581/110798729-09c83180-82ad-11eb-9c0e-3515166753c4.mp4

**Comment by DonBruce64** [comment]
Fixed in V19.15.3.
