### ISSUE TITLE
Button functions/animations on signals (in terms of if you want to make a pedestrian signal button)

### ISSUE THREAD

**Issue by CodeParrot14** [DonBruce64/MinecraftTransportSimulator#741]
Animations ie pushing a button to be able to be implemented on signals.

**Comment by DonBruce64** [comment]
Not gonna happen anytime soon.  That requires:
A re-coding of the signal controller to handle crossing signals in addition to traffic signals.
A re-coding of the block-based system to handle click-able things.
A re-coding of the pole system to handle components that can be clicked.
