### ISSUE TITLE
Permanent subParts block a part from being removed

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#742]
Mt Turrets and MGs have permanent invisaseats on them, which means they cannot be removed without the part being removed. I would suggest that permanent parts do not prevent a parent part from being removed (but non-permanent parts still do).

**Comment by DonBruce64** [comment]
See commit: f17626a3d9a402b3a523d1902708f95d0d21a2e0

**Comment by DonBruce64** [comment]
Fixed in V19.15.3.
