### ISSUE TITLE
(Suggestion) Add a friction modifier for wheels based on the material of the block below

### ISSUE THREAD

**Issue by d-v-n-t** [DonBruce64/MinecraftTransportSimulator#747]
It would allow pack makers to create wheels that are more efficient on some materials. The idea is to have a modifier that would take the wheel's motivefriction and lateralfriction properties, and multiply them for some materials. 

It could be added to the json in such a way: _(credits to TurboDefender for this syntax)_
```
 "frictionModifier": {
     "rock": 0.4,
     "ground": 1.2
 }
```
What this example would do for a wheel with `"motiveFriction" : 0.70` is set its actual friction to `0.4*0.70=0.28` on rock based blocks and to `1.2*0.70=0.84` on ground based blocks like dirt. To avoid breaking packs and for people who don't want to use this, omitting a line would make the modifier for a specific material default to 1, making the friction exactly as specified in the json. 

The most interesting materials would probably be rock, ground, grass, sand, clay, ice and snow, although there are many more. 

Thanks for reading this.

**Comment by d-v-n-t** [comment]
Also, I noticed wheels are more slippy when it's raining. I guess as an upgrade to this you could have definable rain friction modifiers, to make road tires that behave kind of the same way in all weathers, and slick tires that become literally useless at the first raindrop.

I do like tires a lot.

**Comment by DonBruce64** [comment]
Added in V20.2.0.
