### ISSUE TITLE
handheld guns spaz out when changing from one gun to another

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#748]
Basically if you have a gun held in your hand, and you take another one from the inventory, the new gun will have the model of the other one, _except it's on meth and trying to impersonate an ice skater doing the triple axle or whatever_.

There is another way it spazes out too, where there is a duplicate model now, one which is permanent no matter which slot, empty or item. The other model still tries to be an ice skater.

[Exhibit A](https://youtu.be/YcTaSgyVms0)
[Exhibit B](https://youtu.be/pfUSuNP8Uc8)
and the super special and borked [Exhibit C](https://youtu.be/yUTMT8dTWx0)

**Comment by DonBruce64** [comment]
Fixed in V19.15.4.
