### ISSUE TITLE
Request: Rear gear ratios for cars

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#75]
Currently the movement and force equations seem to assume that all vehicles have a 3.55:1 rear gear ratio. I propose that this changes. A few tweaks in the code and an extra JSON variable (in the "car" section) should do. Ideally this would allow for more realistic performance from vehicles that don't have a 3.55:1 rear gear ratio,

**Comment by DonBruce64** [comment]
While I can see reasoning behind this, it's not something I'm going to do.  Every pack creator so far has made custom engines for all their vehicles, many of which are custom ONLY to those vehicles.  Because of this, there is no need for a car-specific gear ratio, even if the idea is plausible.  I do not foresee this changing any time soon.

**Comment by fsendventd** [comment]
I plan to be reusing engines between multiple vehicles, plus I want to get the most realistic performance I can out of my vehicles, most of which don't have a 3.55:1 ratio. I've never liked the idea of one engine to one vehicle. More that one vehicle has multiple engine option, some of which may be shared with other vehicles, like how it works in real life. I know it hasn't gone that way for most other packs, but me and Emerald have discussed our engines, and plan to be reusing them.

**Comment by DonBruce64** [comment]
Re-opening as this request came out of fixing issue #109.  That issue found a bug with the driveshaft ratios, and the only way to fix is to actually implement this, or make all drive ratios static.  Ratios were previously at 3.14159, so pack authors will have to adjust accordingly.

**Comment by fsendventd** [comment]
I appreciate it. Hopefully this means I don't have to do weird math and odd tuning for my engines to work better.

**Comment by DonBruce64** [comment]
Added in V14.0.0.
