### ISSUE TITLE
Cant place planes down on servers

### ISSUE THREAD

**Issue by Gewster** [DonBruce64/MinecraftTransportSimulator#750]
I'm on a forge 1.12.2 server, and I'm having trouble placing planes down with the official vehicle pack, version 20. They spawn in for around 1 second, then despawn. There is no error showing up anywhere that I can see, and there is nothing in the server console either. I think its only the planes because the cars work just fine. I only have the official vehicle pack and the base for MTS, version 19.15.3, but i have plenty of other mods. Any help would be amazing! btw, i have the mods both on the server and client

**Comment by DonBruce64** [comment]
Confirmed this is somehow related to Sponge.  Investigating.

**Comment by DonBruce64** [comment]
Fixed in V19.15.4.  This was a NASTY one.
