### ISSUE TITLE
delays on sounds does not work right

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#751]
Using forwardsDelay or reverseDelay on sounds, atleast ones that use visibility as the type, doesn't work, in 2 ways that I found.

1) Non loopings sounds are disabled fully,
2) Looping sounds are not delayed

I think that's it from me

**Comment by RishiMenon2004** [comment]
I haven't tried if it breaks other animationTypes, I'll try it uh soon

**Comment by DonBruce64** [comment]
Fixed in V19.15.4.
