### ISSUE TITLE
Using multiple visibility blocks breaks sounds. 

### ISSUE THREAD

**Issue by d-v-n-t** [DonBruce64/MinecraftTransportSimulator#754]
I'm gonna try to explain the problem I've been having for two days while trying to update my sounds to the new system. 
In theory, replacing `volumeAnimations` by `activeAnimations` is all my pack would need to work. However, most sounds simply vanish when I do that. The only sounds that play normally are either part of an animated object or only have one visibility condition. 

Here are several examples that used to work in the previous builds with volumeAnimations but won't play with the new system.
![image](https://user-images.githubusercontent.com/42881372/111902314-4c240800-8a3d-11eb-91b9-c51cd45677c9.png)
![image](https://user-images.githubusercontent.com/42881372/111902324-53e3ac80-8a3d-11eb-9aa3-81990150d9d7.png)
![image](https://user-images.githubusercontent.com/42881372/111902422-a624cd80-8a3d-11eb-95ba-aa50c8be0b0a.png)
![image](https://user-images.githubusercontent.com/42881372/111902815-81c9f080-8a3f-11eb-8a8c-e4c77100f502.png)

Many other sounds have the same problem and showing them all would be pointless. However I did try to remove some visibility conditions, with this expected result:

![image](https://user-images.githubusercontent.com/42881372/111902472-e5531e80-8a3d-11eb-80b7-aa69716a2f5b.png)

Blazewolf apparently had some problems too and I spent the whole day on this only to fail finding a working setup.

**Comment by DonBruce64** [comment]
Fixed in V19.15.5.
