### ISSUE TITLE
[Suggestion] Vehicle texture spesific DefaultParts

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#755]
Adding a way to make DefaultParts only apply to certain textures of a vehicle. Example: "Police" texture can have siren as a DefaultPart, while the same vehicle in a civilian colour scheme will not.

**Comment by DrprofLuigi** [comment]
Maybe as an expansion to this, default parts can apply the secondTone as well. This doesn't happen on my jeeps,

**Comment by DonBruce64** [comment]
Make that its own ticket, as that should happen with normal default parts, and is more of a bug than a feature like this.

**Comment by DonBruce64** [comment]
Implemented in V19.15.5.
