### ISSUE TITLE
Analog variables don't animate when they have a sound

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#756]
The following shifter animation does not work as-is, but when I remove the sounds, it works fine:

`            {
                "objectName": "$Gearshift_Manual",
                "animations": [
                    {
                        "animationType": "visibility",
                        "centerPoint": [0, 0, 0],
                        //"axis": [0, 0, 0],
                        "variable": "engine_isautomatic_1",
                        "clampMin": 0,
                        "clampMax": 0
                    },
                    {
                        "animationType": "rotation",
                        "centerPoint": [0, 0.25, 1.625],
                        "axis": [0.5, 0, 0],
                        "variable": "engine_gearshift_hvertical_1",
                        "forwardsStartSound": "unuparts:unuparts_rotation_unu_gearshift_3",
                        "reverseStartSound": "unuparts:unuparts_rotation_unu_gearshift_3"
                    },
                    {
                        "animationType": "rotation",
                        "centerPoint": [0, 0.25, 1.625],
                        "axis": [0, 0, 1],
                        "variable": "engine_gearshift_hhorizontal_1"
                    }
                ]
            }`

"It's because it's doing the 0-1 state-factoring interpolation because there are sounds on it." - don_bruce 2021

**Comment by d-v-n-t** [comment]
So it was indeed a bug. I had the same problem on my shifter, that's why I added downshift and upshift solely for sounds. If it's fixable that's great news!

**Comment by DonBruce64** [comment]
Fixed in V19.15.5.
