### ISSUE TITLE
Traffic Light Issues

### ISSUE THREAD

**Issue by tptstt** [DonBruce64/MinecraftTransportSimulator#758]
I'm not sure whether this is specific to Immersive Vehicles or if it comes from one of the many other IV-related mods we've added, but it seems to affect all traffic lights we've tested. I'm also not sure if this issue has been posted yet.

On a server I run, it looks like the traffic lights stop working when you travel too far away from them. They can be reset by re-scanning them with a signal controller. We've updated two days ago to the then most recent versions of all IV-related mods we're using. If necessary, I will add a list of all mods being used in the pack, in case one might be causing issues. (not all other mods in the pack have been checked to be up-to-date, which may be the issue?)

**Comment by DonBruce64** [comment]
Odd, I just tried TPing between two lights, and they seemed to stay.  Does this happen in single-player worlds or only on the server?

**Comment by Grrpapa** [comment]
I am running single-player and when I exit one any of my worlds and then load them again, all the traffic controllers have reset to 1 and I have to re-scan them all again.  I am on Immersive+Vehicles-1.12.2-19.15.4.jar.

**Comment by DonBruce64** [comment]
That doesn't make sense.  I was just trying that on my world and it seemed to be fine.  I can throw y'all a few betas in Discord, but right now give this a try and let me know if it works.  You'll have to change it from a zip to jar.  Git doesn't let me upload jars.
[Immersive Vehicles-1.12.2-19.15.5-BETA18.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6208290/Immersive.Vehicles-1.12.2-19.15.5-BETA18.zip)

**Comment by Grrpapa** [comment]
I just tested with the BETA18 and it still is not working properly.  It appears that every time the traffic lights and controller have to be rendered or re-rendered the controller gets reset and does not keep the number of traffic lights and crossing lights that it had.  If I re-scan it, then it finds all of them and it will work correctly again until I leave that section or exit the world.  Then when I go back, it renders the lights and controller and the controller does not have the lights and has to be scanned again.

**Comment by DonBruce64** [comment]
That doesn't make sense.  I'm able to get it to work just fine.  Does this happen in a fresh world if you remove all other mods?

**Comment by Grrpapa** [comment]
I tried it on a brand new world in creative and it still loses the count of traffic signals that were originally scanned when the traffic controller was first spawned and the scan was initiated.  I do that and the lights work perfectly, then I go to another part of the world where the place the traffic lights are is out of the focus range and when I come back into the focus range the lights will have the one closest to the controller green and the other 3 will be red and the controller shows 1X for scanned lights.  I scan again and all is well.  I exit and save the world. Then load the world again and I get the 1 green and 3 red and the controller showing 1X for scanned lights.  I can go back to version 19.14.0 and the light works fine with my other 73 mods loaded.  I really need my other 73 mods for what I do with minecraft so getting rid of any of them is not an option for me.  Having to run my minecraft game without working traffic lights is not a big deal so I will just change to 4 way stops or flashing red four way light stops and if the issue gets resolved sometime later I will go to them again.  I love the new changes to Immersive Vehicles by the way and I love being able to fly the Hero Helis easily with the new code physics.  Thank you Don Bruce and all the modelers that have created this.

**Comment by DonBruce64** [comment]
Oooh, that's different.  Do the lights that turn red and green all face the same way?  Because what that sounds like is that the controller is stuck somehow and not changing states.

**Comment by Grrpapa** [comment]
Yes they do with the one being different color being the one nearest the controller.

**Comment by Grrpapa** [comment]
This problem fix was tested by me in a beta jar from Don Bruce with his fix to test and it worked in that one.  The traffic lights and controllers worked perfectly in that one.  I suspect that when Don drops the next update on curse forge website that this problem will be marked as resolved.  Thank you Don Bruce for quickly addressing bugs and fixing them.

**Comment by DonBruce64** [comment]
Fixed in V19.15.6.
