### ISSUE TITLE
Using canFloat on a wheel makes the wheel unusable

### ISSUE THREAD

**Issue by d-v-n-t** [DonBruce64/MinecraftTransportSimulator#759]
I've discovered that this was what prevented my wheels to work properly. 

This wheel works fine:
![image](https://user-images.githubusercontent.com/42881372/112220718-dda29e00-8c26-11eb-83d8-b11b56ccb4a3.png)

But using this wheel will make the car stuck. I can install it on the vehicle but they don't turn and the vehicle doesn't move.
![image](https://user-images.githubusercontent.com/42881372/112220862-02971100-8c27-11eb-9ff0-11b9c646b0c2.png)

**Comment by DonBruce64** [comment]
Fixed in V19.15.5.
