### ISSUE TITLE
Bug: P11 not reaching takeoff speed at high altitutde

### ISSUE THREAD

**Issue by Nianor** [DonBruce64/MinecraftTransportSimulator#76]
For some reason, the P11 winds up being incapable of taking off at altitudes as low as 250 meters above bedrock.

**Comment by DonBruce64** [comment]
This is likely due to improper physics calculation of rotation while on the ground during the lower-lift high altitude area.  There is no way to fix this except get the ground physics to rotate better, and that's a whole nother issue in and of itself.

**Comment by DonBruce64** [comment]
Condensing into #83 for clarity.
