### ISSUE TITLE
[Request] defaultYaw & defaulpPitch overrides

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#764]
simply make defaultYaw/Pitch be able to be defined anywhere that minYaw/Pitch and maxYaw/Pitch can be, and make it override any defaultYaw/Pitch on the gun UNLESS it is outside of the boundary definitions being USED for min/max yaw/pitch

**Comment by DonBruce64** [comment]
Implemented in V19.15.5.
