### ISSUE TITLE
[bug] Car go down when i spawn them

### ISSUE THREAD

**Issue by Impre-visible** [DonBruce64/MinecraftTransportSimulator#765]

**Comment by Impre-visible** [comment]
I don't know why, but cars go on the floor when i spawn them

**Comment by Impre-visible** [comment]
all the mods used

![image](https://user-images.githubusercontent.com/69050895/112718616-7d488080-8ef4-11eb-92e9-a379fc5cfb68.png)

**Comment by DonBruce64** [comment]
Picture please.

**Comment by DonBruce64** [comment]
Found you joined the Discord this morning.  Vehicles need wheels.
