### ISSUE TITLE
[BUG] Middle clicking on popped tires crashes the game instead of giving nothing or the appropriate tire

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#767]
[crash-2021-03-29_00.53.54-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6219274/crash-2021-03-29_00.53.54-client.txt)

**Comment by DonBruce64** [comment]
Fixed in V19.15.6.
