### ISSUE TITLE
[Bug Again] Bullets not dealing enough damage to parts, Not triggering explosions in crates on vehicles

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#769]
bullets and guns in general are not causing full part damage, resulting in tanks not blowing eachother up, tires not popping from getting shot, etc. this issue was supposed to be fixed, and had worked previously but is currently, with the newest official release, not working once again

**Comment by DonBruce64** [comment]
Fixed in V19.15.6.
