### ISSUE TITLE
Request: Fluid Barrels

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#77]
I believe this has been discussed before, but you know the saying. They would ideally be able to go anywhere you can put a crate (or perhaps in a slot with type "barrel"). Could be filled with a bucket by clicking, and would only hold one type of fluid. Capacity would be configurable in JSON. Should show how much is in it when hovered over.

**Comment by DonBruce64** [comment]
Implemented in 13.1.0.
