### ISSUE TITLE
Plane placing issue

### ISSUE THREAD

**Issue by misikcz** [DonBruce64/MinecraftTransportSimulator#770]
Hello I have an issue with planes in mod. I just cant place plane for no reason. Do I have to place some specific blocks under place where I want to place plane ? Or I need another mod ? In Official Content Pack I can use everything... Thanks for help. (I am sorry for my english)

**Comment by DonBruce64** [comment]
Do you have a latest.log you can share?  Also, which planes are you trying to use?

**Comment by misikcz** [comment]
I am trying to place every plane that is in mod and it don't work :/

**Comment by dino-brewster** [comment]
that was i think fixed
