### ISSUE TITLE
[BUGS] Multiple reverse gear shenanighans

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#771]
One: Multiple reverse gears act like a manual shift thing, even if the engine is automatic. (This doesn't affect forward gears, which will still auto-shift)

Two: If trying to go back up a gear (from Reverse 2 to Reverse 1), tranny skips to neutral.

**Comment by DonBruce64** [comment]
Fixed in V19.15.6.
