### ISSUE TITLE
[PACKARD] *NONE* OF YOUR GEAR INDICATOR GAUGES HAVE CLAMPS!!

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#772]
Reverse gear one.
![image](https://user-images.githubusercontent.com/53581325/113468959-a34fb280-9417-11eb-8088-145a4a93d213.png)

Reverse gear two.
![image](https://user-images.githubusercontent.com/53581325/113468970-bbbfcd00-9417-11eb-8615-4d4f0ad4ec6d.png)

Y U NO CLAMP??!?!??

**Comment by DonBruce64** [comment]
Fixed in OCP V20.
