### ISSUE TITLE
Request: Gear indicator on HUD and/or dash

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#78]
Would work for both transmission types. Useful for manuals with lots of gears, or just for when you want to know what year you're in.

**Comment by fsendventd** [comment]
It would be more like the flap indicator or the pull brake than an instrument.

**Comment by DonBruce64** [comment]
Ah, in that case it would fall under the MTS Control system, which is a hard-coded rendering system for complex things.  To get something like that in I'd need to modify the control texture to include such things, which isn't hard, but does require textures to include in the first place.

**Comment by DonBruce64** [comment]
Added in V14.0.0.
