### ISSUE TITLE
[Issue] Airships

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#783]
-Parking brake not working as an anchor
-when "maxTiltAngle" is applied, the airship will end up in a steep downwards pitch after using yaw
-yaw not having much effect on the airship velocity, only gives the visual apperance of turning while velocity vector remains more or less the same. While this mechanic makes sense on an aeroplane, where most aerodynamic forces will straigten the aeroplane again after applying the rudder, this makes less sense on an airship, where the rudder is the only means of adjusting velocity.

**Comment by dino-brewster** [comment]
how do u fly the airship anyway

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
