### ISSUE TITLE
[Issue/suggestion?] Instrument sheets have to be 1024x1024, and seperate sheets for each instrument isn't possible

### ISSUE THREAD

**Issue by SpicySauseSaig** [DonBruce64/MinecraftTransportSimulator#784]
Since there is only one 1024x1024 sheet, making multiple high-res instrument (256x256 or 200x200) is virtually impossible due to the limited texture sheet size. If there was a option to make a separate sheet for each instrument, this issue would be easily solved.

**Comment by DonBruce64** [comment]
Doing this would be exceedingly difficult, and would require a bunch of code changes and tweaks to JSON that would likely break other packs.  Not prudent as this juncture.  That being said, you might be able to get away with tricking MTS and upscaling the texture x2 to 2048x2048, and dividing your pixel measurements by 1/2.  That way you'd get 4x the sheet size.  If that doesn't work, see me and I might be able to get it to do so.  I can't support multiple textures, but I might be able to support larger ones.
