### ISSUE TITLE
instrument issue 

### ISSUE THREAD

**Issue by dino-brewster** [DonBruce64/MinecraftTransportSimulator#788]
the speedometers don't start a zero so i have no clue what speed im going

**Comment by DonBruce64** [comment]
Which ones?  Which pack?

**Comment by dino-brewster** [comment]
mts official vehicle pack 
![image](https://user-images.githubusercontent.com/82777020/115306169-6aad1a00-a135-11eb-8b4f-e2029c39fa6f.png)

**Comment by DonBruce64** [comment]
Ah, that's what #703 is about.  Closing as this ticket is a duplicate.

**Comment by dino-brewster** [comment]
i did not now about that
