### ISSUE TITLE
[Enhancement] Add the ability for mobs to control vehicles, including their weapons. 

### ISSUE THREAD

**Issue by Prophet2002** [DonBruce64/MinecraftTransportSimulator#792]
At least minimal mechanics...

**Comment by DonBruce64** [comment]
Mobs can already control weapons.  Put a villager into a turret and he'll fire it for you.  Cows, on the other hand, ain't gonne ba driving anything.  As to actually *driving* the vehicles, that's not gonna happen.  Far too complex.
