### ISSUE TITLE
[Request] "Functional" Decor blocks

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#796]
Add the ability to have functional decor blocks such as chairs and chests. For chair decors, the seating position would be defined in the json file. Similar to crate parts, chest decors would have the number of inventory slots variable, but would drop the items upon being broken.

**Comment by DonBruce64** [comment]
Going to backburner this, as this would either require making it so decors can have entity functions, or just making them entities themselves.  Personally, am leaning towards the latter, as it allows for place-able parts like tires, wheels, and trailers, plus the ability to unify some older code, and allow for parts on "decors".

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
