### ISSUE TITLE
[Request] Stackable Decor Blocks

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#797]
Similar to the 1.13 Sea Pickles, clicking a decor block with a "stacking" variable would cycle through various model states defined by the pack creator (model_one_object, model_two_objects, etc). This would reduce inventory clutter when adding decors with slight model variations. 

Example of "stackability"
![image](https://user-images.githubusercontent.com/33960693/115944347-3f069880-a483-11eb-9bac-0a5455180322.png)

![image](https://user-images.githubusercontent.com/33960693/115944363-4cbc1e00-a483-11eb-9301-bf66bd803626.png)

![image](https://user-images.githubusercontent.com/33960693/115944391-78d79f00-a483-11eb-9f37-f0894c438f0d.png)

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
