### ISSUE TITLE
Request: Displayed parts/decorative part blocks

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#8]
Nianor and I were discussing the potential for placing wheels, engines, propellers, and other parts in-world to decorate garages and car junkyards. It would be awesome to have blocks that represented wheels, engines, and maybe a few other things to have laying around in chop shops.

**Comment by DonBruce64** [comment]
Not going to do this.  It'd be too hard to get uniform placement with all the different model sizes.  Not to mention the parts themselves link up as extra data for vehicles, so turning them into blocks is a whole nother hassle of it's own.
