### ISSUE TITLE
Bug: Recipes only accept oak planks

### ISSUE THREAD

**Issue by chj990707** [DonBruce64/MinecraftTransportSimulator#80]
The recipes in MTS core such as sawbench or drawing board accepts only oak planks and refuses spruce etc(not to mention forge oredic).

**Comment by DonBruce64** [comment]
I can confirm the drawing board can only use oak fences, despite being able to use any type of planks.  Will fix.  Other plank-based benches behave as expected.

**Comment by DonBruce64** [comment]
Fixed as of V13.
