### ISSUE TITLE
[Request] Custom Liveries for Aircraft + other vehicles

### ISSUE THREAD

**Issue by TrafficAhead** [DonBruce64/MinecraftTransportSimulator#800]
I know it seems fairly difficult to do something like this and I understand if it can't be possible to add.

Sure, the standard colors on all vehicles are fun and all, but I think being able to further enhance customization would be really sweet. Being able to design your own paints on your own vehicles for those who want to start fictional airlines, like a few friends and I on my server. Of course you can use texture packs, but it's a little confusing, there's no template that you can use, and overall it is inconvenient.

Being able to choose any color or adding text or some sort of design onto vehicles would make a great addition not only to the mods, but the hundreds or thousands of worlds this mod is used on.

No matter how this is achieved, whether it's an ingame system or replacing textures, this would be really neat to have.

Let me know your opinions on this.

**Comment by DonBruce64** [comment]
So, this is gonna have to be something pack authors do by allowing their vehicles to use online textures for new liveries.  As to making it internal: there's no way to do it cleanly with the current systems in place.
