### ISSUE TITLE
[Issue] Manual doesn't say anything about backfiring.

### ISSUE THREAD

**Issue by TREGuy365** [DonBruce64/MinecraftTransportSimulator#801]
I was playing on a server known as "The End of Minecraft" and had recently crafted a car. I filled it with gas and drove it around but for some reason after a while it kept backfiring. I moved the car to my house to fix it and read it up in the manual. It didn't say anything I could find about that. I looked up backfiring causes and it said something about fuel and stuff, but my gauge said it was full of fuel! Whats even worse, the oil gauge said there wasn't any in the car but didn't tell me what to use as oil. I filled it up with gas and it said it was full but it acted like it was empty. What's the problem here?

**Comment by DonBruce64** [comment]
So, the reason the car is backfiring is too many hours on the engine.  That happens if you run it over the max RPM for too long, get it too hot, or just drive it a ton.  That *should* be in the manual, but if it's not, I need to add it.  Will save this issue as a reminder to update the manual.  Though I'm debating making it a wiki rather than something in-game.

**Comment by RishiMenon2004** [comment]
uh the car manual icon things :)
![handbook_car_en](https://user-images.githubusercontent.com/34656590/117528187-8d24ab80-afee-11eb-9674-9970ba846e9c.png)

**Comment by RishiMenon2004** [comment]
and the cover and pages
![manual_pages](https://user-images.githubusercontent.com/34656590/119269363-f8889300-bc14-11eb-9341-36f7fe1d705a.png)
![manual_cover](https://user-images.githubusercontent.com/34656590/119269403-2cfc4f00-bc15-11eb-9505-978c392279fa.png)

**Comment by RishiMenon2004** [comment]
~_everyone should thank ooferine_~

**Comment by boot2big** [comment]
~~You won't overheat IVV engines and they're harder to overrev~~ 😉😉😏😏

**Comment by RishiMenon2004** [comment]
mmm double
![manual_cover](https://user-images.githubusercontent.com/34656590/122506058-2d70e580-d01b-11eb-8cfd-0f7a9e63509d.png)
![manual_pages](https://user-images.githubusercontent.com/34656590/122506056-2c3fb880-d01b-11eb-8393-7342f09966a9.png)

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
