### ISSUE TITLE
[BUG] Parts seem to randomly "disappear" if vehicle is in a chunk that gets unloaded, and reloaded.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#803]
Note that the parts actually ghost out, and only reappear if the vehicle is pocketed and replaced into the world, where physics will wig out and make your car do a handstand.

_cant have shit in detroit_

**Comment by dino-brewster** [comment]
f

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
