### ISSUE TITLE
[Bug?] Camera in Comanche randomly tilted

### ISSUE THREAD

**Issue by TrafficAhead** [DonBruce64/MinecraftTransportSimulator#804]
Sometime it happens and sometimes it doesn't but for some reason the cockpit camera for the Comanche is angled. Here's a pic of the issue.

![2021-04-27_10 10 09](https://user-images.githubusercontent.com/39660964/116256102-dfd5ac00-a740-11eb-9d9b-44669f406941.png)

**Comment by DonBruce64** [comment]
Did you just finish a loop-de-loop?

**Comment by TrafficAhead** [comment]
No. This was spawned in freshly and did not fly yet.

**Comment by DonBruce64** [comment]
Odd.  Very odd.  If you have a tilted camera, does it persist if you leave and re-enter the plane?  And if you have that tilted camera, does it persist if you leave and re-enter the world?

**Comment by TrafficAhead** [comment]
It persists, yes

**Comment by DonBruce64** [comment]
Interesting.  I see you are using shaders.  If you boot your game without them loaded, does the issue persist?

**Comment by TrafficAhead** [comment]
I think I've narrowed it down to what the problem is.
If the aircraft is spawned in while the player is sprinting and/or flying the camera will tilt. If you happen to spawn in the exact same plane due to a tag that makes this occur.

**Comment by DonBruce64** [comment]
VERY interesting.  Is that a previously-wrenched plane, or a fresh one you put parts on, or both?

**Comment by TrafficAhead** [comment]
It's both

**Comment by DonBruce64** [comment]
So, I tried this multiple times in my dev build, but couldn't get it to happen.  Are you able to join the Discord so I can throw some test builds at you?

**Comment by TrafficAhead** [comment]
Yep. I'm in. I'm njlarosa#6613

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
