### ISSUE TITLE
Distant Mobs Flickering

### ISSUE THREAD

**Issue by ToastedEggplant** [DonBruce64/MinecraftTransportSimulator#808]
Immersive Vehicles-1.12.2-19.15.7 running on forge-1.12.2-14.23.5.2855 with zero content packs installed. With the mod installed distant entities repeatedly flicker in and out of existence, with just forge installed and the mod not installed the entities do not do this. Specific entities that flicker are mobs. Zombies, Skeletons, cows, chickens, etc. Example videos included to show the issue. With MTS installed https://www.youtube.com/watch?v=ejQSj1qLyUU . Without MTS Installed https://www.youtube.com/watch?v=0aJR0ouYZLQ

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
