### ISSUE TITLE
[BUG] Vehicles do a F&F style non-moving wheelie when towed as a trailer, then the towing vehicle is removed

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#814]
https://user-images.githubusercontent.com/53581325/118708534-d8f30400-b7e9-11eb-82a0-e12c11dd656c.mp4

_sorry_

**Comment by dino-brewster** [comment]
what mts mod is that?

**Comment by boot2big** [comment]
This is a WIP version of Immersive Vehicles Vanity version 1.4 (it has not been released yet, so the truck seen in the video does not have towing capabilities yet)

**Comment by DonBruce64** [comment]
Closing as this is a bug in the beta build, and it is now fixed.
