### ISSUE TITLE
GGVP Rim Linking Crash 

### ISSUE THREAD

**Issue by dino-brewster** [DonBruce64/MinecraftTransportSimulator#816]
---- Minecraft Crash Report ----
// Why did you do that?

Time: 2021-05-18 18:11:10 EDT
Description: Error executing task

java.util.concurrent.ExecutionException: java.lang.IllegalArgumentException: Attempted to add defaultPart: general's_general_vehicles:standard_rim to: unucivil:unucivil_vehicle_unu_broker_coupe but that part doesn't exist in the pack item registry.
    at java.util.concurrent.FutureTask.report(Unknown Source)
    at java.util.concurrent.FutureTask.get(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:531)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:723)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:279)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.IllegalArgumentException: Attempted to add defaultPart: general's_general_vehicles:standard_rim to: unucivil:unucivil_vehicle_unu_broker_coupe but that part doesn't exist in the pack item registry.
    at minecrafttransportsimulator.entities.components.AEntityE_Multipart.addDefaultPart(AEntityE_Multipart.java:674)
    at minecrafttransportsimulator.entities.components.AEntityE_Multipart.addPartFromItem(AEntityE_Multipart.java:413)
    at minecrafttransportsimulator.packets.instances.PacketVehicleInteract.handle(PacketVehicleInteract.java:101)
    at minecrafttransportsimulator.packets.instances.PacketVehicleInteract.handle(PacketVehicleInteract.java:29)
    at minecrafttransportsimulator.packets.components.APacketEntity.handle(APacketEntity.java:36)
    at minecrafttransportsimulator.packets.components.InterfacePacket$WrapperHandler$1.run(InterfacePacket.java:229)
    at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
    at java.util.concurrent.FutureTask.run(Unknown Source)
    at net.minecraft.util.Util.runTask(Util.java:529)
    ... 5 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 10 (x86) version 10.0
  Java Version: 1.8.0_291, Oracle Corporation
  Java VM Version: Java HotSpot(TM) Client VM (mixed mode), Oracle Corporation
  Memory: 217077752 bytes (207 MB) / 1046937600 bytes (998 MB) up to 1046937600 bytes (998 MB)
  JVM Flags: 8 total; -XX:+UseConcMarkSweepGC -XX:-UseAdaptiveSizePolicy -XX:+CMSParallelRemarkEnabled -XX:+ParallelRefProcEnabled -XX:+CMSClassUnloadingEnabled -XX:+UseCMSInitiatingOccupancyOnly -Xmx1024M -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 37 mods loaded, 37 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                  | Version                 | Source                                           | Signature                                |
       |:------ |:------------------- |:----------------------- |:------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft           | 1.12.2                  | minecraft.jar                                    | None                                     |
       | LCHIJA | mcp                 | 9.42                    | minecraft.jar                                    | None                                     |
       | LCHIJA | FML                 | 8.0.99.99               | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge               | 14.23.5.2855            | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | infinimend          | 1.0.2                   | minecraft.jar                                    | None                                     |
       | LCHIJA | micdoodlecore       |                         | minecraft.jar                                    | None                                     |
       | LCHIJA | obfuscate           | 0.4.2                   | minecraft.jar                                    | None                                     |
       | LCHIJA | foamfixcore         | 7.7.4                   | minecraft.jar                                    | None                                     |
       | LCHIJA | techguns_core       | 1.12.2-1.0              | minecraft.jar                                    | None                                     |
       | LCHIJA | spawncontroller     | 3.0.0                   | [1.12.x][ver.3.0.0]SpawnController.jar (1).jar   | None                                     |
       | LCHIJA | astikorcarts        | 1.12.2-0.1.2.7          | astikorcarts-1.12.2-0.1.2.7.jar                  | None                                     |
       | LCHIJA | cdm                 | 0.4.1                   | cdm-0.4.1-mc1.12.2.jar                           | None                                     |
       | LCHIJA | cfm                 | 6.3.0                   | cfm-6.3.0-mc1.12.2.jar                           | None                                     |
       | LCHIJA | umm3185118519       | release 1.5 - MC 1.12.2 | Extended+ItemsOres+[1.12.2]+(release+1.5).jar    | None                                     |
       | LCHIJA | galacticraftcore    | 4.0.2.280               | GalacticraftCore-1.12.2-4.0.2.280.jar            | None                                     |
       | LCHIJA | galacticraftplanets | 4.0.2.280               | Galacticraft-Planets-1.12.2-4.0.2.280.jar        | None                                     |
       | LCHIJA | mts                 | 19.15.7                 | Immersive+Vehicles-1.12.2-19.15.7.jar            | None                                     |
       | LCHIJA | ironchest           | 1.12.2-7.0.67.844       | Iron-Chests-Mod-1.12.2.jar                       | None                                     |
       | LCHIJA | speedsterheroes     | 1.12.2-2.2.1            | SpeedsterHeroes-1.12.2-2.2.1 (1).jar             | None                                     |
       | LCHIJA | lucraftcore         | 1.12.2-2.4.10           | LucraftCore-1.12.2-2.4.10 (1).jar                | None                                     |
       | LCHIJA | moreemeraldstuff    | 1.1.3                   | MES_1.1.3_1.12.2.jar                             | None                                     |
       | LCHIJA | movillages          | 1.5.4                   | Mo-Villages-Mod-1.12.2.jar                       | None                                     |
       | LCHIJA | notenoughpets       | 2.2.0                   | NotEnoughPets-1.12.2-v2.2.0.jar                  | None                                     |
       | LCHIJA | offlineskins        | 1.12.2-v6               | OfflineSkins-Mod-1.12.2.jar                      | aaaf83332a11df02406e9f266b1b65c1306f0f76 |
       | LCHIJA | phonesalpha         | v1.11                   | pa1.11 (1).jar                                   | None                                     |
       | LCHIJA | spectrite           | 1.7.1                   | spectrite-1.7.1.jar                              | 00119cfc089819bbcd2f9166a50c7f3df88ded78 |
       | LCHIJA | swordblockingcombat | 1.0.2                   | Sword-Blocking-Combat-Mod-1.12.2 (1).jar         | 12d137bcc36051a1c2c8ea7211cfc1da1c6e9dea |
       | LCHIJA | techguns            | 2.0.2.0                 | techguns-1.12.2-2.0.2.0_pre3.2.jar               | None                                     |
       | LCHIJA | tlsywen             | 1.0                     | The-Last-Sword-You-Will-Ever-Need-Mod-1.12.2.jar | None                                     |
       | LCHIJA | trevorcraft         | 1.0.0                   | trevorcraft-ea3.jar                              | None                                     |
       | LCHIJA | unuparts            | 4.3.1                   | UNU+Parts+Pack+[MTS]+1.12.2-19.15.5-4.3.1.jar    | None                                     |
       | LCHIJA | unucivil            | 4.2.4                   | UNU+Civilian+Pack+[MTS]+1.12.2-19.15.5-4.2.4.jar | None                                     |
       | LCHIJA | unumilitary         | 4.0.0                   | UNU+Military+Pack+[MTS]+1.12.2-19.15.5-BETA2.jar | None                                     |
       | LCHIJA | vanillafix          | 1.0.10-150              | VanillaFix-1.0.10-150.jar                        | None                                     |
       | LCHIJA | vashkmat            | eh, who cares           | VASHKMAT+2.0.jar                                 | None                                     |
       | LCHIJA | vehicle             | 0.44.1                  | vehicle-0.44.1-mc1.12.2 (4).jar                  | None                                     |
       | LCHIJA | foamfix             | 0.10.5-1.12.2           | foamfix-0.10.5.jar                               | None                                     |
  Loaded coremods (and transformers): MicdoodlePlugin (MicdoodleCore-1.12.2.jar)
                                        micdoodle8.mods.miccore.MicdoodleTransformer
                                      ObfuscatePlugin (obfuscate-0.4.2-mc1.12.2 (1).jar)
                                        com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      offlineskins (OfflineSkins-1.12.2-v6-core.jar)
                                        lain.mods.skins.init.forge.asm.ASMTransformer
                                      Techguns Core (techguns-1.12.2-2.0.2.0_pre3.2.jar)
                                        techguns.core.TechgunsASMTransformer
                                      LucraftCoreCoreMod (LucraftCore-1.12.2-2.4.10 (1).jar)
                                        lucraft.mods.lucraftcore.core.LCTransformer
                                      IMLoadingPlugin (infinimend-1.12-1.0.2.jar)
                                        net.crazysnailboy.mods.infinimend.asm.IMClassTransformer
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.5.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
  Suspected Mods: Immersive Vehicles (formerly MTS) (mts)

**Comment by boot2big** [comment]
If I had to guess, you must've modified the UNU Civil jar (specifically the broker json) as this vehicle does not normally request any parts from General's General Pack.
Try redownloading the civil and general pack?

**Comment by DonBruce64** [comment]
This appears to be an issue with GGVP, as he's trying to put a GGVP wheel on an UNU vehicle.  Not that the vehicle itself is not requesting that rim.  Rather, the GGVP wheel is requesting the rim, and it's failing.  But since the crash handler always assumes DPs on vehicles, it's giving wrong information.  I'll need to adjust my wording on the crash handler, so this is both a note for me, and for Nax.

**Comment by dino-brewster** [comment]
what causes this to happen

**Comment by DonBruce64** [comment]
GGVP is broken.  Bother the owner about that.

**Comment by dino-brewster** [comment]
don bruce i will go bother nax about this crash

**Comment by DonBruce64** [comment]
Fixed in latest build of GGVP.
