### ISSUE TITLE
[BUG] Rob likes to get lost easily.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#818]
On a player's death, ROB will not reappear and the world has to be restarted (Or some other method of triggering MTS to notice)
When /kill @e is performed, ROB gets taken out with the rest of the thanos snap.

On teleportation, Rob does _NOT_ get lost, and follows the player.

**Comment by DonBruce64** [comment]
Closing as this is a beta bug, and is now fixed in the beta.
