### ISSUE TITLE
[Suggestion] Block-breaker effectors

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#821]
An effector that breaks blocks. This would be great for tunnel bores, graders, trenchers, and all sorts of eqipment. I think it would be best if combined with the two other tickets I opened (#819 and #820)

**Comment by DonBruce64** [comment]
How would one decide which blocks get broke?  Cause you prolly don't want your tunnel bore to be going through bricks or whatnot.  Or be able to use your trencher for leaves.

**Comment by DrprofLuigi** [comment]
Maybe tie it to an item? For example, if you had it tied to an iron pickaxe, then you could potentially set it so it only mines blocks that can be mined by an iron pickaxe in less than 15 ticks or something.

**Comment by DonBruce64** [comment]
I could do that.  Should it work for any item or just the standard core set?
Also, I see this maybe causing a problem with digging machines, which have to dig through dirt and stone, and one takes a shovel and one takes a pickaxe.

**Comment by DrprofLuigi** [comment]
Maybe use the hardness values by default, and if a 'specialty' tool is defined, that can affect some blocks. IRL dirt and stone are destroyed by different implements anyway.

**Comment by DonBruce64** [comment]
Dirt and stone are broken by different things, but in MC the ground is a dirt/stone mix anywhere but right at the top.  So anything that digs will need to be able to dig through both.  That being said, hardness wouldn't be a bad way to go.

What did you have in mind with the specialty tool?  Cause I can't implement that logic easily as MC hard-codes tool material breakage logic in the tool itself; it's not common code, and if a mod adds a block I won't be able to easily handle it unless it uses the same materials.

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
