### ISSUE TITLE
[BUG?] Guns will still render and be usable in spectator mode, if held while entering spectator mode. (/gamemode 3)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#822]
GHOST GUN???
THE GHOST IS STEALING MY MONNEYS

https://user-images.githubusercontent.com/53581325/119250978-ce31c980-bb71-11eb-8f1e-0b3c39e97d3a.mp4

This is obviously a bit of a weirder bug like that worldborder thing, where the solution would be too complicated for something that isn't really easily abuseable, nor would it be beneficial, but I figured I'd report it anyways just in case.

**Comment by DonBruce64** [comment]
Still, the fact that you can go into spectator, phase through a wall, and pop a cap into someone hiding behind it is a *bit* OP.  Will fix.

**Comment by dino-brewster** [comment]
dont fix it i love doing that

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
