### ISSUE TITLE
[BUG] Jet engines on a car with non-jet engines will prevent shifting with non-jet engines

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#823]
See title, try putting rockets on Rock with any geared motor (rockets will go on the sides, engine in the inside)

**Comment by boot2big** [comment]
Another interesting note is that the non engine (for example, the Insolvo Inline 2) will instantly gain jet power somehow.

**Comment by dino-brewster** [comment]
WHAT YOU CAN  DO THAT

**Comment by DonBruce64** [comment]
Are you SURE that non-jet engine is getting jet power?  Cause how would you tell with rockets on the rock that the rockets aren't doing their jet things?

**Comment by boot2big** [comment]
Because the rockets are off and the rock's I1 still thrusts the rock forward at full throttle. If that isn't a non-jet getting jet power...

**Comment by boot2big** [comment]
* To clarify, the proper jet engines WILL do jet things, but so will non-jet specified engines. Basically, non-jet engines seem to take on the behaviors of jet engines, including lack of gearboxes and jet power

**Comment by DonBruce64** [comment]
Oooh, I bet I know what's happening.  I bet the jet engines are generating thrust because the main driveshaft is forcing the rocket engines to keep their RPM.  So the I1 makes the engines turn faster, and then they generate thrust.  They *shouldn't* do that though if they aren't running.  Only propellers can generate force when they aren't running.

**Comment by DonBruce64** [comment]
So, I was wrong.  VERY wrong.  Turns out the issue was that the gears *were* shifting, but only on the server.  That shift packet never made it to the client.  So it seemed like the I1 wasn't doing anything, but in fact it was, just only on the server.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
