### ISSUE TITLE
[Suggestion] Craft could take forge plankWood dictionnary

### ISSUE THREAD

**Issue by Sablam** [DonBruce64/MinecraftTransportSimulator#825]
Hi,

I can't craft the _Immersive Vehicule_ bench that use wood plank with wood from mods, like _Biomes o'Plenty._
I can add the craft with _CraftTweaker_.
I think it could be good to use the Forge **PlankWood** dictionnary in the craft instead of the Vanilla Wood only.

Sincerely,

Sablam.

**Comment by DonBruce64** [comment]
I can adjust it to use the Forge thing.  How is that formatted?

**Comment by Sablam** [comment]
I am not a forge mod dev and I only know Forge mecanics through _[CraftTweaker](https://docs.blamejared.com/1.12/fr/Vanilla/OreDict/IOreDict/)_

Maybe with these Forge API [Class](https://skmedix.github.io/ForgeJavaDocs/javadoc/forge/1.9.4-12.17.0.2051/net/minecraftforge/oredict/OreDictionary.htm)  you can get all the wood planks with something like `getOres("plankWood")`.

I really don't know much more you should ask to one of your fellow mod dev that have already used Forge ore dict.

**Comment by DonBruce64** [comment]
No, I can't do any getOres.  That's in the Java code.  Recipies are defined in JSON files as of 1.12.2, so I need to know what to put in those text-based JSON files.  That'd be something that would be similar with craftTweaker, and in other mods that use OreDict for their crafting recipes.  But I don't know of any that do so right now.

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
