### ISSUE TITLE
[BUG] Hitboxes force spectator-mode players to float up to the top of the box as if they were standing on it.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#826]
https://user-images.githubusercontent.com/53581325/119757642-3c78d380-be73-11eb-9adc-0d222d033b5c.mp4
if pictures speak a thousand words, movies speak 24,000 a second

**Comment by DonBruce64** [comment]
Movies need to be quiet.  I'm busy watching a spoopy ghost moving on a portable base.  Will fix.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
