### ISSUE TITLE
[BUG, but minor] Gear ratios will end with a comma... despite there being no more gears.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#827]
Can't believe I've only just realized tbh, although it is such a minor bug to be fair, so it might not even be worth fixing.
![image](https://user-images.githubusercontent.com/53581325/119761549-fc691f00-be79-11eb-95aa-c76e600642a6.png)
Ideally at the end there probably shouldn't be another "**,**" unless I'm wrong about some obscure, obtuse measurement system where that's used... _oh wait, imperial_

**Comment by DonBruce64** [comment]
This is because don is a lazy coder and just loops through all gear entries and make a text line out of them by doing their number, plus a comma.  Reckon I can be less lazy.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
