### ISSUE TITLE
[BUG?] Reverse gears no longer seem to work with boat propellers

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#828]
https://user-images.githubusercontent.com/53581325/119765926-1ad31880-be82-11eb-93de-259481ace208.mp4

**Comment by DonBruce64** [comment]
Odd, so the reverse gear slows you down, but then when you're stopped it forgets what direction reverse is and makes you go forwards again?

**Comment by boot2big** [comment]
That stopping is me braking, actually. I think the slower movement might just be the gearing too.

Reverse seems to work as just forward with propellers, save for rotors that use reversing on the props themselves I guess

**Comment by DonBruce64** [comment]
Odd, do those propellers rotate the other direction when shifting into reverse?  You may have to slow down the engine or change the gear ratio on that.

**Comment by boot2big** [comment]
Nope! same way each time

**Comment by DonBruce64** [comment]
I betcha I have some incorrect absolute value somewhere.  Will fix when I get back from vacation.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
