### ISSUE TITLE
hookup_connected animation specificity

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#829]
With the newer connection groups, the hookup_connected and hitch_connected animation variables should be able to specify a hookup (like part_present_X), that way you don't have an airdrop harness visible when you're just towing it on a flatbed.

![Capture1641](https://user-images.githubusercontent.com/36775575/120062772-a9799e00-c018-11eb-8372-6df29e6eb309.PNG)

**Comment by DonBruce64** [comment]
I can do this, though it'll break all existing animations as they'll need to specify the index.  Is that a problem?

**Comment by DrprofLuigi** [comment]
Not for me, but it might be for Kadwin and Laura

**Comment by DonBruce64** [comment]
They seem to be okay with this.  So I will change it.  Flagging as bug as it's technically one.  However, note that this will be per-group, not per-connection, unless that's what you want.

**Comment by DrprofLuigi** [comment]
Per-connection would be more robust (think lockers for different trailer hitches like a fifth wheel or ball or different towing connections), but per-group would work fine.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
