### ISSUE TITLE
Models in Crafting benches seem to have inverted normals

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#831]
Models in the crafting benches appear inside-out. This seems to be on all the crafting benches.

(I'm using Immersive_Vehicles-1.12.2-20.0.0-BETA37.jar)

![image](https://user-images.githubusercontent.com/36775575/120124210-1e0f2280-c168-11eb-8cd8-a01338435182.png)

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
