### ISSUE TITLE
[Suggestion] State-based dismount position

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#834]
Have the ability for dismount position to vary based on the state of a vehicle
example: A plane on the ground will dismount on the ground beside it, while a plane docked to an airship will dismount above it

**Comment by DonBruce64** [comment]
This would be VERY tough to add.  In all honesty, I'd prefer you just dismount in the plane, and be able to either jump to the ground, or into the airship.  Say, dismount above the seat.  If it's a large plane, then just dismount in the asiale of the plane.  There's not a reason you'd leave your seat and appear in different areas, really.
