### ISSUE TITLE
AdamRK Revolver Speedloader Menu Crash

### ISSUE THREAD

**Issue by 7FeetUnder** [DonBruce64/MinecraftTransportSimulator#836]
While testing out the mod for the modpack I am developing, I noticed the game crashed when using the gun workbench and entering the tab for the MTS Heavy Industrial Pack the revolver speedloader page crashes the game, thus locking it and any of the other pages after from access. I'm submitting the crash report to hopefully aid in the issue being resolved. 

[crash-2021-06-06_22.06.18-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6605666/crash-2021-06-06_22.06.18-client.txt)

**Comment by boot2big** [comment]
This is a packard issue caused by a lack of a recipe from what I can tell

**Comment by DonBruce64** [comment]
Agreed.  @LauraDarkez, this one's on you.
`java.lang.NullPointerException: Could not parse crafting ingredients for item: mtsheavyindustrialbyadamrkadamrevolver_speedloader.  Report this to the pack author!`
