### ISSUE TITLE
[BUG] Engines that are sub-parts of parts aren't startable or interactable 

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#837]
Gearshifts won't affect them, their starter won't appear in the menu, etc.

`{
  "generic": {
    "width": 0.25,
    "height": 0.25
  },
  "rendering": {
  "textObjects":
		[
		{
		"pos": [0.005, 0.025, 0.00215],
		"rot": [0, 0, 0],
		"scale": 0.11,
		"color": "#040404",
		"fieldName": "License Plate",
		"defaultText": "ABC-1234",
		"maxLength": 8,
		"lightsUp": false,
		"renderPosition": 0
		}
		]
  },
  "general": {
    "type": "generic_licenseplate_us",
    "disableMirroring": true,
    "useVehicleTexture": false,
    "stackSize": 64,
    "modelName": "licenseplate",
    "name": "License Plate [An experiment]",
    "description": "yes",
    "materials": [
      "minecraft:iron_ingot:-1:1"
    ]
  },
    "subParts": [
	{
		"pos": [0, 0.001975, 0.000025],
		"types": ["engine_car"],
		"minValue": -1,
		"maxValue": 65536
	}
    ]
}`

**Comment by DonBruce64** [comment]
That make sense given how I coded the indexing.  Will fix.  do you have a test build?

**Comment by boot2big** [comment]
V20 Beta 30.

**Comment by DonBruce64** [comment]
Er, no.  Meant a pack that has such a setup that would cause such a bug to become apparent.

**Comment by boot2big** [comment]
IVV "V1.5" I guess, although the only difference between V1.4 (released) and that is the above JSON. Texture is irrelevant for it, but it's supposed to take a variety of parts including engines. (I'll make it more expensive soon)

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
