### ISSUE TITLE
[Bug] MTS entities don't interact with LT Entity hitboxes

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#839]
https://user-images.githubusercontent.com/33960693/121451680-0146cc00-c96c-11eb-9dcd-8032b5822dc3.mp4

**Comment by boot2big** [comment]
This was changed due to buggy behavior with LT hitboxes. Can confirm, because they STILL NaN out for me.

**Comment by DonBruce64** [comment]
While I want to do this, I can't.  LT entities don't have any collision to them.  So I can't do it.  Still, I'm leaving the code hooks in place in case things change, or we want to use this for another system.
