### ISSUE TITLE
[Feature] Configurable flap rotation speed and flap notches

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#841]
Basically what it says on the tin. Think we discussed it on Discord. Essentially the "hasFlaps" would be split into two variables, "flapSpeed" in degrees/second or degrees/tick, and "flapNotches", an array of possible positions for the flaps in degrees.

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
