### ISSUE TITLE
[PR Idea] Different interpolation types for animation

### ISSUE THREAD

**Issue by RishiMenon2004** [DonBruce64/MinecraftTransportSimulator#843]
Basically if you have a duration, another parameter can be written which specifies the interpolation type. So stuff like ease in and ease out can be done in just one animation block instead of combining 2 or 3 blocks. Also, is a PR idea not request.

**Comment by DonBruce64** [comment]
Going to close this as PR ideas should spawn discussion or PRs, not issue tickets.  Will address the PRs as they roll in.
