### ISSUE TITLE
[ENHANCEMENT] Part hitboxes crash the part instead of the car?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#844]
I remember when I first started messing around with MTS that wheels could break if they were stuck in a block. Not pop mind you, but entirely and totally be destroyed, annihilated, shredded and ultimately removed from the axle... Which wasn't that bad tbh, since it saved one the time of taking off the wheel to replace it with a new one.

I am **NOT** suggesting that said feature be readded to wheels, seats, etc *unless they have physics collision boxes.*

Lets say we have two pickup trucks. One is stock, one has a large battering ram as well as a reinforced frame and body. Realistically the ram truck should be able to take on anything until the frame or battering ram breaks, but in MTS they're both practically the same, save for the reinforced rammer being heavier and slower.

If a part has collision hitboxes and collides with a block fast enough to crash the whole car, the part itself should break first *before* the vehicle does (assuming the impact doesn't make the vehicle slow down before then)
If a part *doesn't* have collision hitboxes (AKA 99% of all MTS parts) it should retain normal behavior (which seems to be indestructible save for tire popping, or engine heat)

**Comment by boot2big** [comment]
_important note, im suggesting this because i have said ram ingame and mostly working, wouldn't do much on v19 though and i need to work on other features before releasing_

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
