### ISSUE TITLE
Allow animation variables to have numbers at the end

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#846]
There was a discussion about this a while back, not sure if it's fixed yet so just playing it safe and making a ticket.

MTS dies when you have numbers at the end of animation variables because it thinks they are for parts like engines. If they also check the _ in part variables instead of just the numbers it should be fine.

**Comment by DonBruce64** [comment]
They can already do this, but only in V20, so will leave this ticket open until V20 drops.

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
