### ISSUE TITLE
Newest version of Forge is missing Java Games Input libraries

### ISSUE THREAD

**Issue by XavierErrorLog** [DonBruce64/MinecraftTransportSimulator#850]
Hello when I go to join my single player world my Minecraft crash in says that the player has a ticking  entity can you help me fix this because it says suspects mod: MTS plus I,m using vanilla fix  

Here is the script : 
/ I bet Cylons wouldn't have this problem.

Time: 2021-06-16 18:52:23 GMT
Description: Ticking entity

java.lang.NoClassDefFoundError: net/java/games/input/ControllerEnvironment
    at minecrafttransportsimulator.controls.InterfaceInput.<clinit>(InterfaceInput.java:57)
    at minecrafttransportsimulator.controls.ControlSystem.<clinit>(ControlSystem.java:55)
    at minecrafttransportsimulator.mcinterface.WrapperPlayer.on(WrapperPlayer.java:223)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_81_WrapperPlayer_on_PlayerTickEvent.invoke(.dynamic)
    at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
    at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
    at net.minecraftforge.fml.common.FMLCommonHandler.onPlayerPostTick(FMLCommonHandler.java:370)
    at net.minecraft.entity.player.EntityPlayer.updateSize(EntityPlayer.java:378)
    at net.minecraft.entity.player.EntityPlayer.onUpdate(EntityPlayer.java:288)
    at net.minecraft.client.entity.EntityPlayerSP.onUpdate(EntityPlayerSP.java:181)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1996)
    at net.minecraft.world.World.updateEntity(World.java:1958)
    at net.minecraft.world.World.redirect$zcb000$updateEntity(World.java:4123)
    at net.minecraft.world.World.updateEntities(World.java:1762)
    at net.minecraft.client.Minecraft.runTick(Minecraft.java:1847)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1098)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.ClassNotFoundException: net.java.games.input.ControllerEnvironment
    at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
    ... 24 more
Caused by: java.lang.ArrayIndexOutOfBoundsException

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: null (net.minecraft.client.entity.EntityPlayerSP)
  Entity ID: 0
  Entity Name: XavierGaming10
  Entity's Exact location: -63.50, 69.00, 247.50
  Entity's Block location: World: (-64,69,247), Chunk: (at 0,4,7 in -4,15; contains blocks -64,0,240 to -49,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Spawns:[],SleepTimer:0s,SpawnForced:1b,Attributes:[{Base:20.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.10000000149011612d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:1.0d,Name:"generic.attackDamage"},{Base:4.0d,Name:"generic.attackSpeed"},{Base:0.0d,Name:"generic.luck"},{Base:5.0d,Name:"generic.reachDistance"}],Invulnerable:0b,FallFlying:0b,PortalCooldown:0,AbsorptionAmount:0.0f,abilities:{invulnerable:1b,mayfly:1b,instabuild:1b,walkSpeed:0.1f,mayBuild:1b,flying:0b,flySpeed:0.05f},FallDistance:0.0f,DeathTime:0s,XpSeed:0,ForgeCaps:{"dsurround:entityfx":{},"effortlessbuilding:buildmodifier":{radialMirrorDrawPlanes:0b,mirrorX:1b,mirrorY:0b,radialMirrorSlices:4,mirrorZ:0b,mirrorRadius:10,mirrorDrawLines:1b,mirrorDrawPlanes:1b,radialMirrorRadius:20,radialMirrorAlternate:0b,arrayCount:5,radialMirrorDrawLines:1b,mirrorPosX:0.5d,mirrorPosZ:0.5d,mirrorPosY:64.5d,reachUpgrade:0,arrayEnabled:0b,arrayOffsetY:0,arrayOffsetX:0,radialMirrorPosZ:0.5d,arrayOffsetZ:0,radialMirrorPosX:0.5d,radialMirrorPosY:64.5d,mirrorEnabled:0b,radialMirrorEnabled:0b},"dsurround:speech":{},"effortlessbuilding:buildmode":{}},XpTotal:0,Motion:[0.0d,-0.0784000015258789d,0.0d],SpawnY:64,UUIDLeast:0L,Health:20.0f,SpawnZ:244,foodSaturationLevel:5.0f,SpawnX:-68,HasSpawnDimensionSet:0b,Air:300s,OnGround:1b,Dimension:0,ForgeDataVersion:{minecraft:1343},Rotation:[6.7499995f,3.3f],XpLevel:0,UpdateBlocked:0b,Score:0,UUIDMost:0L,Sleeping:0b,Pos:[-63.5d,69.0d,247.5d],Fire:-20s,XpP:0.0f,EnderItems:[],DataVersion:1343,foodLevel:20,foodExhaustionLevel:0.0f,HurtTime:0s,SelectedItemSlot:0,SurgeAABB:[-63.80000001192093d,69.0d,247.19999998807907d,-63.19999998807907d,70.79999995231628d,247.80000001192093d],Inventory:[],foodTickTimer:0}

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['XavierGaming10'/0, l='MpServer', x=-63.50, y=69.00, z=247.50]]
  Chunk stats: MultiplayerChunkCache: 39, 39
  Level seed: 0
  Level generator: ID 04 - customized, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-68,64,244), Chunk: (at 12,4,4 in -5,15; contains blocks -80,0,240 to -65,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 191 game time, 191 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 11 total; [EntityBat['Bat'/32, l='MpServer', x=-77.50, y=48.00, z=286.50], EntityCreeper['Creeper'/1, l='MpServer', x=-57.50, y=37.00, z=242.50], BuilderEntity['entity.mts_entity.name'/2, l='MpServer', x=-63.50, y=69.00, z=247.50], EntityPlayerSP['XavierGaming10'/0, l='MpServer', x=-63.50, y=69.00, z=247.50], EntityPig['Pig'/8, l='MpServer', x=-70.50, y=69.00, z=293.50], EntityPig['Pig'/9, l='MpServer', x=-71.50, y=69.00, z=292.50], EntityPig['Pig'/10, l='MpServer', x=-71.50, y=69.00, z=293.50], EntityPig['Pig'/11, l='MpServer', x=-69.50, y=69.00, z=295.50], EntityBat['Bat'/28, l='MpServer', x=-94.50, y=59.00, z=269.50], EntityBat['Bat'/29, l='MpServer', x=-91.50, y=59.00, z=273.50], EntityBat['Bat'/30, l='MpServer', x=-45.50, y=18.00, z=286.50]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  
  FML: MCP 9.42 Powered by Forge 14.23.5.2855 Optifine OptiFine_1.12.2_HD_U_G5 22 mods loaded, 22 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                 | Version        | Source                                           | Signature                                |
       |:------ |:------------------ |:-------------- |:------------------------------------------------ |:---------------------------------------- |
       | LCHIJA | minecraft          | 1.12.2         | minecraft.jar                                    | None                                     |
       | LCHIJA | mcp                | 9.42           | minecraft.jar                                    | None                                     |
       | LCHIJA | FML                | 8.0.99.99      | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge              | 14.23.5.2855   | forge-1.12.2-14.23.5.2855.jar                    | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | foamfixcore        | 7.7.4          | minecraft.jar                                    | None                                     |
       | LCHIJA | extendedrenderer   | v1.0           | coroutil-1.12.1-1.2.37.jar                       | None                                     |
       | LCHIJA | coroutil           | 1.12.1-1.2.37  | coroutil-1.12.1-1.2.37.jar                       | None                                     |
       | LCHIJA | configmod          | v1.0           | coroutil-1.12.1-1.2.37.jar                       | None                                     |
       | LCHIJA | orelib             | 3.6.0.1        | OreLib-1.12.2-3.6.0.1.jar                        | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | dsurround          | 3.6.1.0        | DynamicSurroundings-1.12.2-3.6.1.0.jar           | 7a2128d395ad96ceb9d9030fbd41d035b435753a |
       | LCHIJA | effortlessbuilding | 1.12.2-2.16    | effortlessbuilding-1.12.2-2.16.jar               | None                                     |
       | LCHIJA | flansmod           | 5.10.0         | Flan's+Mod-1.12.2-5.10.0.jar                     | None                                     |
       | LCHIJA | foamfix            | 0.10.10-1.12.2 | foamfix-0.10.10-1.12.2.jar                       | None                                     |
       | LCHIJA | mts                | 19.15.5        | Immersive+Vehicles-1.12.2-19.15.5.jar            | None                                     |
       | LCHIJA | simplepartspack    | 5.7.2          | Simple+Parts-Content+Pack-1.12.2-5.7.2.jar       | None                                     |
       | LCHIJA | surge              | 2.0.77         | Surge-1.12.2-2.0.77.jar                          | d476d1b22b218a10d845928d1665d45fce301b27 |
       | LCHIJA | texfix             | 4.0            | TexFix+V-1.12-4.0.jar                            | None                                     |
       | LCHIJA | toughasnails       | 3.1.0.139      | ToughAsNails-1.12.2-3.1.0.139-universal.jar      | None                                     |
       | LCHIJA | unuparts           | 4.3.2          | UNU+Parts+Pack+[MTS]+1.12.2-19.15.5-4.3.2.jar    | None                                     |
       | LCHIJA | unucivil           | 4.2.4          | UNU+Civilian+Pack+[MTS]+1.12.2-19.15.5-4.2.4.jar | None                                     |
       | LCHIJA | vanillafix         | 1.0.10-150     | VanillaFix-1.0.10-150.jar                        | None                                     |
       | LCHIJA | weather2           | 1.12.1-2.6.12  | weather2-1.12.1-2.6.12.jar                       | None                                     |
  Loaded coremods (and transformers): TransformLoader (DynamicSurroundings-1.12.2-3.6.1.0.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-150.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.77.jar)
  Suspected Mods: Immersive Vehicles (formerly MTS) (mts)
  Launched Version: 1.12.2
  LWJGL: 3.2.3 SNAPSHOT
  OpenGL: GL4ES wrapper GL version 2.1 gl4es wrapper 1.1.4, ptitSeb
  GL Caps: VboRegions not supported, missing: OpenGL 1.3, ARB_copy_buffer
           Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because ARB_framebuffer_object is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x null
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0

**Comment by DonBruce64** [comment]
What PC, what version of Forge, what version of, what Operating system.

**Comment by XavierErrorLog** [comment]
System 
Device: MSI GP Series GP66 Leopard 
OS: Windows 10
CPU: 64 Bit
Forge : 1.12.2 - 14.23.5.2855 Universal File

**Comment by DonBruce64** [comment]
Odd, you *should* have `net/java/games/input/ControllerEnvironment`.  If you downgrade Forge to 2847 does this issue go away?

**Comment by XavierErrorLog** [comment]
Hello Sorry for not getting back with you but i fixed it i,m going to close the case since all i did was went to a older but stable version of forge

**Comment by DonBruce64** [comment]
I'm going to re-open, as IV should be compatible with all Forge versions.  Here's a beta: can you try this on a copy of that world and let me know if the issue persists?  You'll have to change the .zip to a .jar but should work then.
[Immersive Vehicles-1.12.2-20.0.0-BETA48.zip](https://github.com/DonBruce64/MinecraftTransportSimulator/files/6690763/Immersive.Vehicles-1.12.2-20.0.0-BETA48.zip)

**Comment by DonBruce64** [comment]
Closing due to no response from user, and not able to reproduce.
