### ISSUE TITLE
Problem with vehicle lights

### ISSUE THREAD

**Issue by GodARG78** [DonBruce64/MinecraftTransportSimulator#851]
I'm using Forge with Shaders, I don't know if it will have something to do with it but it causes the vehicle lights to look like this.
The Shader I use is Chocapic V6.
This version is 1.12.2. Thanks
![2021-06-17_16 07 20](https://user-images.githubusercontent.com/86077629/122458584-5b581a80-cf86-11eb-9fe2-da46ef559be1.png)
![2021-06-17_16 07 27](https://user-images.githubusercontent.com/86077629/122458611-64e18280-cf86-11eb-911a-9a1a6c265fa4.png)
![2021-06-17_16 07 32](https://user-images.githubusercontent.com/86077629/122458615-6612af80-cf86-11eb-9873-d9b79b5c32f5.png)

**Comment by DonBruce64** [comment]
That is due to shaders, yes.  Nothing I can do about it except give you configs to adjust on the config screen.  Shaders royally mess up the lighting that the base game has.

**Comment by GodARG78** [comment]
Oh it would help me too much if you give me those settings, I am very newbie in technical things, I would appreciate it too much!

**Comment by DonBruce64** [comment]
Basically, it's the settings in the P-key config screen under RENDERING.  They're all commented so they say what they do.  Look for the ones that mention shaders.  You're looking for beam blending and beam render pass, BTW.
