### ISSUE TITLE
[BUG?] Engine hours aren't affected by RPM if engine isn't running?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#852]
Can be tested by driving forwards, putting the engine into neutral and shutting it off, then putting it back into gear (preferably a lower gear in order to "overrev" the engine, you'll see that it won't gain any hours)

Could have a short delay after turning off to allow the engine to reach 0RPM before damage starts taking effect, although it might also help if non-jet engines reached 0 RPM faster when shut off

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
