### ISSUE TITLE
[ENHANCEMENT] Some gun changes

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#853]
1. Optional parameter to make guns only work with the vehicle on (movement and shooting)
2. Autonimous guns with an option to make it un-selectable, and options to wether they shall behave like a villager is using it (looking around when not engaging, or staying still until it engages an enemy)

**Comment by DonBruce64** [comment]
Only one request per ticket, please.  As such, I'm going with the first one for this ticket.  Should be do-able given that I just need to check for the same condition as the DRLs check for.

**Comment by Ilya-torshov** [comment]
Oh. Pardon, mind if i ticket the next suggestion as well?

**Comment by DonBruce64** [comment]
Un-sure.  You basically want sentry turrets for that second one, correct?

**Comment by Ilya-torshov** [comment]
Correct, yes

**Comment by DonBruce64** [comment]
Check the gun code.  There might be something in there you'd be interested in.

**Comment by LauraDarkez** [comment]
sentry code would benefit the dkz_sentinel, as long as it can be disabled until it detects a close-in. also, eventually id like to make it so that munitions can take out missiles the way the CIWS system is made for

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
