### ISSUE TITLE
[ENHANCEMENT] Configurable reverse for aircraft engines?

### ISSUE THREAD

**Issue by fsendventd** [DonBruce64/MinecraftTransportSimulator#855]
What it says on the tin. Not all aircraft piston or turboprop engines with controllable-pitch props, and certainly not all jet engines, are capable of reverse thrust. A simple "hasReverse" boolean in the engine would allow for more realism in many aircraft, preventing them from being able to reverse despite having no apparent method of doing so.

**Comment by DonBruce64** [comment]
@fsendventd tis PR material, this one.

**Comment by DonBruce64** [comment]
Closing as upon relfection I can see this causing complaints like not having NAV beacons on all aircraft.  Sure it's realistic to not have reverse thrust on some kets, but it's also annoying to players to have to deal with a jet without it and getting stuck.  Custom panels would fix this as they'd allow for such a thing, but I'll leave that for the custom panels, not an individual ticket.
