### ISSUE TITLE
custom variable that always 1

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#856]
In immersive vehicle there custom variable that have switch to control it from 0 to 1 and 1 to 0 that give many idea to many pack author for the part custom animations and many thing 
                  but if we can have custom variable that always 0 or 1? for part purpose example the plane engine housing 
![image](https://user-images.githubusercontent.com/79125581/123248943-ad62e800-d512-11eb-8c3e-bf5c67b55c76.png)
like image above if it show yes the variable will always 0 or 1 so when apply engine with that custom variable animation on plane will do thing with that variable example 
engine json:
"customVariable":["cf6"]

plane json that set visibility or any animation to "cf6" var will play
also this will give other idea up to pack authors to use this

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
