### ISSUE TITLE
[QUESTION/ENHANCEMENT] Tire drift-skidding particle animation?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#861]
Does the ground_skidding animation cover sliding/drifting as well, or only burnouts?
If not, could such a variable be implemented? (Obviously not right now, but some day?)

I ask because it seems like there's particle animations for such a thing when a tire is LC-converted through devmode but it also seems to only affect burnouts when

**Comment by DonBruce64** [comment]
It could be, but the particles generated by the burnouts are different than the skidding ones.  Though I really *should* fix that and remove that hard-code.  Noted and will take as a to-do.

**Comment by boot2big** [comment]
Am asking because I planned on using such variable to make smoke and sound when my tires skid, but no such variable exists.

**Comment by BlazeWolf1122** [comment]
> 
> 
> Does the ground_skidding animation cover sliding/drifting as well, or only burnouts?
> If not, could such a variable be implemented? (Obviously not right now, but some day?)
> 
> I ask because it seems like there's particle animations for such a thing when a tire is LC-converted through devmode but it also seems to only affect burnouts when

~~hi~~

**Comment by boot2big** [comment]
> ~hi~

I need it to work on wheels themselves, not the vehicle (would make it universal, but different from VASHKMAT)

That's part of why IVV/Trin use maxtiltangle instead of animating the parts, the end result is still similar but there's a noticable difference (plus it was smoother at the time, but easing animations changed that afaik)

**Comment by BlazeWolf1122** [comment]
_cough_ slip animation variable _cough_

**Comment by boot2big** [comment]
_cough_ idontwannacopyfromvashkmatmorethanialreadyamatthispoint _cough_

**Comment by BlazeWolf1122** [comment]
lmfao
~~but you're making too many variables tho~~

**Comment by boot2big** [comment]
_don himself said it really shouldn't be hard coded_
especially since vehicles like the ebike shouldn't have a ton of particles when it turns slightly

**Comment by BlazeWolf1122** [comment]
fair

**Comment by DonBruce64** [comment]
Added in V20.0.3.
