### ISSUE TITLE
[enhancement] ability to scale images to prevent weird stretching

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#863]
~~cowboy you're gonna hate me for this video~~
anyways, the idea came up from the fact that this advertising thing is really long and wide and errrr i could see some people not making dedicated images just for the advertising on this vehicle, so some kind of scaling option provided within the images would be a nice change of pace rather than having a bunch of stretched prius advertisements
of course, maybe i shouldn't try and fit a dead meme on the advertising things, but it's an exaggerated example so the point goes across

https://user-images.githubusercontent.com/63666200/124237308-3efec680-dacc-11eb-83c2-6c5e7b37ddf9.mp4

**Comment by DonBruce64** [comment]
Not possible.  The image application and parsing is handled internally by MC.  It's essentially a UV-mapped texture to a shape.  No changing that dynamically.  Certainly not when the mapping for the same image would be different for different things.
