### ISSUE TITLE
[Requested Adaptation] Make "activeAnimations" be able to disable wheel ground collision

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#867]
This was discussed in the mts discord, and will be useful for instances where primary wheels shift from being the dominant ground collision to not being the dominant ground collision. instances include:
Cranes: crane support feet being deployed
Backhoes: Backhoe support feet being deployed
Amphibious Vehicles: Specifically ones where the wheels tuck into the body and can not be used on land when in seamode

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
