### ISSUE TITLE
[BUG?] Instruments panel occasionally opens for other players when opened.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#869]
I don't have a video of this, but it seems that whenever someone uses a wrench to modify a vehicle's instruments, it may occasionally open for others too. (Which gets annoying for everyone since it interrupts building, risks the wrencher having unwanted instruments inserted halfway across the world by some petty jokester, etc)
May require testing on PMC as it doesn't seem to happen 100% of the time

**Comment by DonBruce64** [comment]
Which IV version is this?  Cause I know this used to be an issue, but I coulda swore as of the V20 betas the issue was gone.

**Comment by boot2big** [comment]
V19.15 (or whatever the newest forge release is, I can't remember. But it's on planesmc)

**Comment by DonBruce64** [comment]
Talked with Hashim on this one.  Turns out it happens when both players are holding wrenches.  Will have to add packets to fix.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.
