### ISSUE TITLE
Ford Tri-Motor

### ISSUE THREAD

**Issue by samuel200526** [DonBruce64/MinecraftTransportSimulator#87]
I would like you to add the Ford tri-motor in different colors

**Comment by DonBruce64** [comment]
Suggestions for vehicles are not being taken.  I do not make models, and the Official Content Pack only includes models we make specifically to showcase new features.  Please direct all vehicle suggestions to pack authors.

**Comment by samuel200526** [comment]
Ok, thanks for your Time
