### ISSUE TITLE
car refueling fees

### ISSUE THREAD

**Issue by 77RaZe77** [DonBruce64/MinecraftTransportSimulator#872]
what about the support of fueling the car so that the electronic currency is debited from the player's account, for example, the vault plugin, and plug-in for economics essentials?

**Comment by DonBruce64** [comment]
I wouldn't do this through plugins.  Rather, I would do it by taking items out of the player's inventory.  Such items would be set by the admins of the server, of course.

**Comment by boot2big** [comment]
I think I know a couple servers that'd much appreciate this

**Comment by 77RaZe77** [comment]
> Я бы не стал делать это через плагины. Скорее, я бы сделал это, вынимая предметы из инвентаря игрока. Такие элементы, конечно же, устанавливают администраторы сервера.

with items a good idea, but on most servers money is made through a plugin, so there is a need for it. Although it can be done, for example, with the help of items (checks), the player buys them, and already with them spends them on fuel for the car

**Comment by DonBruce64** [comment]
Plugins are Bukkit, not Forge, so I can't do anything about that. I can only offer compatibility with items.  If you want someone to do a plugin, you'll have to get with a plugin dev.

**Comment by 77RaZe77** [comment]
> Плагины - это Bukkit, а не Forge, поэтому я ничего не могу с этим поделать. Могу предложить только совместимость с предметами. Если вы хотите, чтобы кто-то создал плагин, вам придется иметь дело с разработчиком плагинов.

Let's make it so that each fuel has its own card, for example, a diesel card, a gasoline card, a biodiesel card, and these cards have a limit, for example, 1 card - 100 liters of fuel. After the card has 0 liters, it is automatically destroyed

**Comment by DonBruce64** [comment]
Note to self to tweak to display fuel type even if empty to let players know what fuel they are purchasing.

**Comment by DonBruce64** [comment]
Implemented in V20.0.0.
