### ISSUE TITLE
[BUG] Xbox One Controller not being detected.

### ISSUE THREAD

**Issue by deSuperNoodle** [DonBruce64/MinecraftTransportSimulator#873]
I've been wanting to use this mod with an Xbox Controller since it's easier to fly and control vehicles with a joystick but cant get the mod to detect my controller. I make sure to connect my controller before launching Minecraft but this doesn't seem to do anything. I also have a Corsair mouse which an error in the Config menu (the thing that pops up when u press P) pops up saying that this could cause problems. I don't have any other mouses currently so I'm not sure what to do.
I also made sure my PC's bluetooth wasn't the problem by checking Steam. It shows its connected and works on controller supported games.

**Comment by DonBruce64** [comment]
Would you be able to join the Discord and try one of the latest betas we have for V20?  I re-did some control system stuff in them for Android support, so it might have fixed this issue.

**Comment by DonBruce64** [comment]
Re-opening, as the fix was in the dev build and not release.  I only close tickets when they're in a released version as folks may not know about the betas.

**Comment by DonBruce64** [comment]
Fixed in V20.0.0.  Well, in a sense.  A bypass was added for Corsair mice.  But it requires manual un-plugging of said mice.
