### ISSUE TITLE
Allow Left/Right Triggers on Xbox Controller to be used as Throttle

### ISSUE THREAD

**Issue by deSuperNoodle** [DonBruce64/MinecraftTransportSimulator#874]
Not sure what I'm supposed to label this as but anyway, I would like to see (if at all possible) were we can use the left and right triggers on a Xbox Controller as throttle inputs. Holding down RT would increase throttle, holding down LT would decrease throttle.

**Comment by DonBruce64** [comment]
Using an analog axis for a digital input that's maintained isn't currently possible with the control systems available.  With analog axis, you can only set the value to the current axis state, not increment/decrement and hold.  Afraid there's nothing I can do about throttles with trigger buttons.
