### ISSUE TITLE
[ENHANCEMENT] Make instrument textures emissive when the right settings are enabled

### ISSUE THREAD

**Issue by NightScale5755** [DonBruce64/MinecraftTransportSimulator#877]
Just what it says on the tin. 
I really don't know if you already do this, but when I disabled Instrument lights for shader compat, nothing happened. No changes in the textures. 
Shader used: Continuum 2.0.4

**Comment by DonBruce64** [comment]
Closing due to 1 month of inactivity, and suspected fixing due to shader-comaptible lighting.
