### ISSUE TITLE
Flare overhaul reminder

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#878]
1. Aways face the player
2. Change size based on angle and distance:
-a. shrink when looking at it from the side
-b. shrink slower than the vehicle when moving away from it

**Comment by DonBruce64** [comment]
So, while I think this has merit, the code involved is very complex.  Right now I just bundle all like-typed flares together and render them as one object.  To do this, I'd need to split all of them out, and then do math on all of them to have them face the player.  Then do math for the player distance from the flare to get the base size.  Then do more math to get the actual size based on the "normal vector" of the flare when it's brightest, relative the vector to the player.  It's do-able, but then for some vehicles that have gobs of lights?  Not the best for performance.  Plus a code time-sink that i can ill afford right now.  I will gladly re-visit this if another coder hops on, or I run out of things to do, but for now, I'm closing this as a wontdo.
