### ISSUE TITLE
[BUG] Sign resets on water touch

### ISSUE THREAD

**Issue by Tim3Game** [DonBruce64/MinecraftTransportSimulator#88]
When water touches a sign, the sign resets to the default MTS sign, but a relog fixes it.
![2019-02-02_16 35 21](https://user-images.githubusercontent.com/34278596/52166136-9a64d880-2709-11e9-9404-84b2d99d8c41.png)
![2019-02-02_16 35 27](https://user-images.githubusercontent.com/34278596/52166137-9c2e9c00-2709-11e9-8cdb-475b55a8e8f7.png)

**Comment by DonBruce64** [comment]
Fixed in 13.1.0.
