### ISSUE TITLE
Interactable crate items able to use in hand like pocket

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#880]
Since there pack authors ask for the hand removable part (or non-Wrench_part)
 example take fire extinguisher from vehicle by hand or take bag or crate out from vehicle by hand i also have one idea to make it go good with those feature above the "usableInHand"
"Usable" In Hand is option  for interactable crate items. Example bag and suitcase from UNU parts, To be able to open it in player's hand like pocket or bags in real life and you put it in vehicles trunks. so these are idea i suggested.

**Comment by DonBruce64** [comment]
Implemented in V20.1.0.
