### ISSUE TITLE
[enhancement] Hand-removable parts variable

### ISSUE THREAD

**Issue by Ilya-torshov** [DonBruce64/MinecraftTransportSimulator#881]
A variable to define parts that can be taken off vehicles without the use of a wrench, punch it instead.

**Comment by Ooferine** [comment]
Preferably it goes straight into the inventory when punched too. You wouldn't want to see people picking up baggage scattered on the floor on the aisle.

**Comment by DonBruce64** [comment]
Implemented in V20.1.0.
