### ISSUE TITLE
[ENHANCEMENT] Engine Repair system

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#885]
Have mentioned some concepts before (removing engine and using a bench to reduce hours, clicking on an engine with json-defined items while it's in the vehicle, etc.) but frankly I would love to have any system that allows for an engine to last longer... (given you actually MAINTAIN it that is)

**Comment by DonBruce64** [comment]
So, benches are hard, as I'd need a way to override the functionality.  But, I could see about just clicking engines to repair them with materials for sure, as it's easy enough to check what's in the player's hand when clicking.  Though I would honestly prefer the bench as it's more immersive, it makes for a PITA for the coding, unless we get a whole new bench, but itself is icky.

Should it be only one item, or do we need multiple items with a mapping from item to amount of hours removed?

**Comment by boot2big** [comment]
I would prefer multiple items with definable hours, and possibly even hour caps? (Can't repair with that part until a certain amount of hours, but might be too complicated. But makes sense since you can't just put 30 pistons into a 6 cylinder engine and call it refurbished)

I say this because certain parts would be able to repair more or less, with various rewards based on the cost of the item. (... Judged by the person making them of course) Like a small repair kit for leakages, or a seafoam bottle that turns back the hour clock a little bit.

**Comment by boot2big** [comment]
An addition I just thought ahead of, maybe disallow repairs if the current item in hand would put the engine hours into the negative, or just allow the repair but make the minimum hours be zero? (Or at least close to it)

**Comment by boot2big** [comment]
One more thought that crossed my mind is showing two hours values? (Total, and effective/wear/whatever)

Basically, you'd be able to see the actual hour count that matters (which is what we have at the moment, and what repair items would lower) as well as a "total hour mileage" which only ever goes up, and can't be lowered by repairs or what-not (and shouldn't be linked to actual repair hours, as repairing an engine with 50 total and current miles to 10 current miles, then putting 20 current hours on it should read as 70 total hours)

**Comment by DonBruce64** [comment]
Given how folks are poking at code for this, I'm gonna leave it to someone else to poke.  I agree that you should be able to define an item and amount it repairs the engine, but doing so is something I shall leave up to others who have more time.

**Comment by DonBruce64** [comment]
Implemented in V20.4.0.
