### ISSUE TITLE
[BUG?] Lights seem to be inverted after new JSON light stuff

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#888]
I wanted to say this was due to lack of clamping, but adding clamps just keeps them permanently on instead of turning off when you turn on the headlights, and vice versa

![image](https://user-images.githubusercontent.com/53581325/128109387-35e61836-581e-4f5f-a75a-4a8541c622f4.png)
![image](https://user-images.githubusercontent.com/53581325/128109392-66284cfc-ea46-4ac4-a85c-98517e61b197.png)

Not related to #866 I think, though

**Comment by DonBruce64** [comment]
This is fixed in commit 08c019498c5a46b153b207c4d87c95bdc05264aa.

**Comment by DonBruce64** [comment]
Fixed in V20.0.3.
