### ISSUE TITLE
OCP phone booth bugs

### ISSUE THREAD

**Issue by obsidian29** [DonBruce64/MinecraftTransportSimulator#89]
One, the phone booth's hitbox is a solid single block. I can stand on it, thus standing IN the other half.
Two, the phone booth model disappears as soon as that solid single block leaves my FOV. So I can look up, and see it disappear before it's off my screen.

**Comment by obsidian29** [comment]
Since for some reason I can't *edit* this (I blame my out of date, and strangely impossible to update, Chrome), I will *try* to add the screenshot in *this* post. Can't preview either.

https://media.discordapp.net/attachments/457646475212488715/548597492695171112/2019-02-22_14.06.32.png

**Comment by DonBruce64** [comment]
Minecraft doesn't allow for hitboxes larger than 1 block.  This means that all decor blocks have hitboxes that are a max of that size, even if you manually set the numbers larger.  Blocks like doors and beds are actually made of two separate blocks, with the other block just being invisible.  This is hard to do well without bugs, and with most decor being small enough to fit in a 1-block size, is not going to be a feature any time soon.

The disappearing of the booth is similarly related to this, as blocks outside the field of view of players do not render.  Despite the fact the model is larger than one block, the hitbox that MC uses to determine the physical presence of the block is outside the field of view, and this causes the booth to disappear in front of you.  Changing this would lead to decor always being rendered, and that is NOT ideal for FPS and will not be done.
