### ISSUE TITLE
Entities invisible in multiplayer

### ISSUE THREAD

**Issue by crrepitv** [DonBruce64/MinecraftTransportSimulator#893]
when the server auto restart all items from the mod are invisible and i must stopp the server and delete and reupload the mod then the items are visible again mod version:1.12.2-20.0.3

**Comment by Schulrucksack** [comment]
Having the same issue

**Comment by Tampastrike** [comment]
Also having the same issue. Whenever I leave the server and rejoin the textures become invisible for all IV vehicles/blocks/entites. Rejoining/ restarting server does not fix this.

**Comment by Tampastrike** [comment]
This also seems to occur when entering other dimensions and then returning. All blocks and vehicles are accessible and can be walked into, but they are invisible.

**Comment by DonBruce64** [comment]
I just posted a beta in the Discord that *should* fix this.  We will see.

**Comment by crrepitv** [comment]
unfortunally this beta dont fixx the bug

**Comment by DonBruce64** [comment]
What is: don't fix.  How often do they go invisibile?  Is it all entities?  If you press F3+B, is there a box in front of you?  What situation causes the bug?  Need more info than "it don't work".

Also, for those of you reading who are on the Discord: that is a FAR better place to comment as I see it more often than here.  Plus that's where I post betas.  If you could get with me there, it would be appreicated.

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
