### ISSUE TITLE
[BUG?] Multiple automatic engines that power wheels seem to confuse the automatic transmissions. (Same kind of engine... example: two amc i4s)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#896]
I don't quite know how to describe it, but they sorta desync from eachother. So no matter how much you spam into the only reverse gear it has, one stays stuck in neutral. (engine 1 is in reverse, engine 2 is neutral. engine 2 is in drive, engine 1 is in neutral)

Note, this ONLY seems to happen if they're _automatic_ transmission engines, manuals are mostly unaffected. (Assuming you use ones with the same amount of gears and ratios, but that can be solved with emergency neutral shifting, etc.)

**Comment by DonBruce64** [comment]
Odd, how does this work if you get them going fast?  Does one always stay in 2nd, whereas the other will stay in 3rd?  Or does the 2nd one eventually get to 3rd?

**Comment by boot2big** [comment]
With a 5 speed engine, they skip from 1st to 3rd to 5th. Never 2nd.

With a 2 speed engine, one seems to skip to 2nd, the other stays in 1st.


Both eventually get to this part.
![image](https://user-images.githubusercontent.com/53581325/128965192-608e8f67-03e2-46f5-a4ae-897254b5d563.png)

**Comment by DonBruce64** [comment]
Ah, I betcha the engines are both sending up-shift packets that are getting handled by all the engines of the vehicle, not just the engine that sent that packet.  But I do know that even if one engine can't shift, I *should* be checking the others, as otherwise you end up with a rocket-rock situation.

**Comment by DonBruce64** [comment]
Should be sussed now.

**Comment by boot2big** [comment]
Fixed in latest build!

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
