### ISSUE TITLE
[ENHANCEMENT] Link all engine controls to one button with json option? (Not by default though)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#897]
Vaguely related to #896 in that I was testing an electric vehicle with multiple electric motors, and to my knowledge there probably isn't any (modern, at least) electric cars that have you individually enable each motor? Not a requirement, I can make it use a single motor, but it would be much appreciated

**Comment by DonBruce64** [comment]
The only issue with this is which engine state to use for the indicator for the starter/magneto switch.  Should I just pick the state of the first engine and assume all others will have the same state?  Totally not opposed to doing this, more just want to make sure I get the implementation correct.

**Comment by boot2big** [comment]
That seems like a good idea to catch the first engine state and assume it for the others, though when cranking would it be possible to crank it similarly to autoStart? (Doesn't even bother if there's no fuel, tries for a certain amount of time then stops if the engine doesn't start?)

**Comment by DonBruce64** [comment]
Potentially?  I should be able to send out that packet instead of the main starter packet.  Though is there a reason for that?  Auto-start will exist when a player gets in, switch or not.  Plus if it's for electrics, they'll be started already once you flip that switch as they idle at 0?

**Comment by DonBruce64** [comment]
Should be good now.  I didn't do auto-start as it kinda breaks the spirit of that system, but you do get single-button.

**Comment by DonBruce64** [comment]
Implemented in V20.1.0.
