### ISSUE TITLE
Adding rotation variable to steering wheel causing crash.

### ISSUE THREAD

**Issue by RottenClunker** [DonBruce64/MinecraftTransportSimulator#898]
Hello, DonBruce. While creating my own pack, I ran into a problem that completely ruined all my efforts. Adding any animation variables to the steering wheel causes crash, even while creating a new world. All animations, except for this one, are working properly. During those three-five seconds that it is possible to exist in the world, I noticed constant flashing of blocks. Why is this happening and what can be done to resolve the situation?

**Comment by boot2big** [comment]
Crashlog (and maybe video would help, but mostly just crash log) or it didn't happen

**Comment by RottenClunker** [comment]
Crash log: ---- Minecraft Crash Report ----
// Uh... Did I do that?

Time: 2021-08-11 03:56:22 MSK
Description: Rendering entity in world

java.lang.NullPointerException
    at minecrafttransportsimulator.rendering.components.RenderableTransform.<init>(RenderableTransform.java:22)
    at minecrafttransportsimulator.rendering.components.RenderableModelObject.<init>(RenderableModelObject.java:31)
    at minecrafttransportsimulator.rendering.components.OBJParser.generateRenderables(OBJParser.java:239)
    at minecrafttransportsimulator.rendering.components.ARenderEntity.parseModel(ARenderEntity.java:132)
    at minecrafttransportsimulator.rendering.instances.RenderVehicle.parseModel(RenderVehicle.java:60)
    at minecrafttransportsimulator.rendering.instances.RenderVehicle.parseModel(RenderVehicle.java:44)
    at minecrafttransportsimulator.rendering.components.ARenderEntity.render(ARenderEntity.java:62)
    at minecrafttransportsimulator.rendering.components.InterfaceEventsModelLoader$1$1.doRender(InterfaceEventsModelLoader.java:77)
    at minecrafttransportsimulator.rendering.components.InterfaceEventsModelLoader$1$1.doRender(InterfaceEventsModelLoader.java:66)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntity(RenderManager.java:413)
    at net.minecraft.client.renderer.entity.RenderManager.renderEntityStatic(RenderManager.java:393)
    at net.minecraft.client.renderer.RenderGlobal.redirect$renderEntityStatic$zbf000(RenderGlobal.java:3769)
    at net.minecraft.client.renderer.RenderGlobal.renderEntities(RenderGlobal.java:850)
    at net.minecraft.client.renderer.EntityRenderer.renderWorldPass(EntityRenderer.java:1808)
    at net.minecraft.client.renderer.EntityRenderer.renderWorld(EntityRenderer.java:1621)
    at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1390)
    at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1119)
    at net.minecraft.client.Minecraft.run(Minecraft.java:3942)
    at net.minecraft.client.main.Main.main(SourceFile:123)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being rendered --
  Entity Type: mts:mts_entity (minecrafttransportsimulator.mcinterface.BuilderEntity)
  Entity ID: 31
  Entity Name: entity.mts_entity.name
  Entity's Exact location: 1000.62, 4.46, 727.51
  Entity's Block location: World: (1000,4,727), Chunk: (at 8,0,7 in 62,45; contains blocks 992,0,720 to 1007,255,735), Region: (1,1; contains chunks 32,32 to 63,63, blocks 512,0,512 to 1023,255,1023)
  Entity's Momentum: 0.00, 0.00, 0.00
  Entity's Passengers: [EntityPlayerSP['EddieTheHead'/1, l='MpServer', x=1002.05, y=4.18, z=726.69]]
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {motionz:0.0d,savedRiderLocations0z:1.600000023841858d,savedRiderLocations0y:0.4000000059604645d,savedRiderLocations0x:0.5799999833106995d,altitudeSetting:0.0d,motiony:-9.08995101411847E-16d,autopilot:0b,motionx:0.0d,Invulnerable:0b,entityid:"EntityVehicleF_Physics",hornOn:0b,savedRiderLocationscount:1,aileronAngle:0,radio:{volume:10,randomOrder:0b,currentURL:"",lookupID:30,currentSource:0,savedRadio:1b,preset:0,uniqueUUID:"d1f2206f-473d-4386-9ec3-f6c47299fe4c"},FallDistance:0.0f,systemName:"jalopy",variablesOn6:"headlight",rudderTrim:0,locked:0b,fuelTank:{lookupID:38,fluidLevel:0.0d,fluidDispensed:0.0d,currentFluid:"",uniqueUUID:"07540753-d93f-4eca-bebb-d0e4a04f9514"},elevatorTrim:0,gearUpCommand:0b,Air:300s,positionx:1000.6210065833016d,positiony:4.4597468906466675d,cruiseControlSpeed:0.0d,positionz:727.5115313980542d,brake:100,rotationx:0.0d,rotationy:0.0d,rotationz:0.0d,Pos:[1000.6210065833016d,4.4597468906466675d,727.5115313980542d],anglesz:0.0d,anglesy:459.17045074676486d,anglesx:-2.62878166662476d,cruiseControl:0b,part_6:{isCreative:1b,lookupID:37,oilLeak:0b,savedRiderLocationscount:0,packID:"sv",variablesOncount:7,systemName:"sv_v8",variablesOn6:"headlight",fuelLeak:0b,state:6,locked:0b,uniqueUUID:"1690600b-45da-44fd-9cf6-06edd02d0e4c",hours:0.0d,temp:26.351970242331888d,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",pressure:49.0320648849177d,variablesOn0:"runninglight",rpm:300.0d,variablesOn1:"leftindicatorlight",offsetx:0.0d,offsetz:3.5625d,offsety:-0.125d,subName:"",currentGear:1,brokenStarter:0b},throttle:0,lookupID:29,part_5:{lookupID:36,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",savedRiderLocationscount:0,variablesOn0:"runninglight",variablesOn1:"leftindicatorlight",packID:"sv",offsetx:-0.5799999833106995d,variablesOncount:7,offsetz:1.7000000476837158d,offsety:0.4000000059604645d,systemName:"junkseat",variablesOn6:"headlight",subName:"",locked:0b,uniqueUUID:"c5f36d32-b08d-4cc5-87f8-17f8d9709e38"},part_4:{lookupID:35,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",savedRiderLocationscount:0,variablesOn0:"runninglight",variablesOn1:"leftindicatorlight",packID:"sv",offsetx:0.5799999833106995d,variablesOncount:7,offsetz:1.600000023841858d,offsety:0.4000000059604645d,systemName:"junkseat",variablesOn6:"headlight",subName:"",locked:0b,uniqueUUID:"3873cb98-99c3-4126-976b-44d5a21ea023"},serverDeltaRx:-15.772689999748561d,PortalCooldown:0,part_3:{isFlat:0b,lookupID:34,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",savedRiderLocationscount:0,variablesOn0:"runninglight",variablesOn1:"leftindicatorlight",packID:"sv",offsetx:1.2000000476837158d,variablesOncount:7,offsetz:3.871000051498413d,offsety:-0.20000000298023224d,systemName:"junkwheel_front",variablesOn6:"headlight",subName:"",locked:0b,uniqueUUID:"e3ef84b3-e864-4714-9857-9fb0c09a4f48"},part_2:{isFlat:0b,lookupID:33,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",savedRiderLocationscount:0,variablesOn0:"runninglight",variablesOn1:"leftindicatorlight",packID:"sv",offsetx:-1.2000000476837158d,variablesOncount:7,offsetz:3.871000051498413d,offsety:-0.20000000298023224d,systemName:"junkwheel_front",variablesOn6:"headlight",subName:"",locked:0b,uniqueUUID:"8650c57a-f4f2-4d43-bdaa-bdb5a869240c"},part_1:{isFlat:0b,lookupID:32,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",savedRiderLocationscount:0,variablesOn0:"runninglight",variablesOn1:"leftindicatorlight",packID:"sv",offsetx:-1.2000000476837158d,variablesOncount:7,offsetz:0.0d,offsety:0.0d,systemName:"junkwheel_back",variablesOn6:"headlight",subName:"",locked:0b,uniqueUUID:"214629ae-fe39-4045-baf3-b2c763dadefd"},serverDeltaRy:643.8179630480498d,part_0:{isFlat:0b,lookupID:31,ownerUUID:"",variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",variablesOn5:"rightindicatorlight",savedRiderLocationscount:0,variablesOn0:"runninglight",variablesOn1:"leftindicatorlight",packID:"sv",offsetx:1.2000000476837158d,variablesOncount:7,offsetz:0.0d,offsety:0.0d,systemName:"junkwheel_back",variablesOn6:"headlight",subName:"",locked:0b,uniqueUUID:"587d4a62-c60c-49e9-9baa-1db2b6a999e9"},serverDeltaRz:0.0d,packID:"sv",serverDeltaMz:5.984523641239819d,variablesOncount:7,serverDeltaMx:545.1953524203025d,serverDeltaMy:2.158481343883511d,flapCurrentAngle:0,reverseThrust:0b,elevatorAngle:0,uniqueUUID:"c220c4c8-104f-4918-9412-7c5007519039",Motion:[0.0d,0.0d,0.0d],flapDesiredAngle:0,ownerUUID:"",totalParts:7,UUIDLeast:-6558471189054240749L,variablesOn2:"genericlight",variablesOn3:"daytimelight",variablesOn4:"brakelight",OnGround:0b,Dimension:0,variablesOn5:"rightindicatorlight",Rotation:[-459.17044f,-2.6287816f],UpdateBlocked:0b,variablesOn0:"runninglight",electricPower:12.84695037573959d,variablesOn1:"leftindicatorlight",aileronTrim:0,UUIDMost:-8909576714210686317L,selectedBeaconName:"",subName:"",Fire:-1s,rudderAngle:0,parkingBrakeOn:0b}

-- Renderer details --
  Assigned renderer: minecrafttransportsimulator.rendering.components.InterfaceEventsModelLoader$1$1@57705b27
  Location: -1.43,0.28,0.82 - World: (-2,0,0), Chunk: (at 14,0,0 in -1,0; contains blocks -16,0,0 to -1,255,15), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Rotation: -459.17044
  Delta: 0.4399768

-- Affected level --
  Level name: MpServer
  All players: 1 total; [EntityPlayerSP['EddieTheHead'/1, l='MpServer', x=1002.05, y=4.18, z=726.69]]
  Chunk stats: MultiplayerChunkCache: 289, 289
  Level seed: 0
  Level generator: ID 01 - flat, ver 0. Features enabled: false
  Level generator options: 
  Level spawn location: World: (-175,4,998), Chunk: (at 1,0,6 in -11,62; contains blocks -176,0,992 to -161,255,1007), Region: (-1,1; contains chunks -32,32 to -1,63, blocks -512,0,512 to -1,255,1023)
  Level time: 83700 game time, 88135 day time
  Level dimension: 0
  Level storage version: 0x00000 - Unknown?
  Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
  Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
  Forced entities: 63 total; [EntityCow['Cow'/2, l='MpServer', x=1012.18, y=4.00, z=724.44], BuilderEntity['entity.mts_entity.name'/3, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/4, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/5, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/6, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/7, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/8, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/9, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/10, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/11, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/12, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/13, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/14, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/15, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/16, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/17, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/18, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/19, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/20, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/21, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/22, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/23, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/24, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/25, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/26, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/27, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/28, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/29, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/30, l='MpServer', x=1002.05, y=4.18, z=726.69], BuilderEntity['entity.mts_entity.name'/31, l='MpServer', x=1000.62, y=4.46, z=727.51], BuilderEntity['entity.mts_entity.name'/32, l='MpServer', x=1002.05, y=4.18, z=726.69], EntitySheep['Sheep'/33, l='MpServer', x=945.55, y=4.00, z=700.20], EntityCow['Cow'/34, l='MpServer', x=955.72, y=4.00, z=682.85], EntityHorse['Horse'/35, l='MpServer', x=980.97, y=4.00, z=670.12], EntityChicken['Chicken'/36, l='MpServer', x=1004.67, y=4.00, z=650.80], EntityItem['item.item.egg'/39, l='MpServer', x=969.61, y=4.00, z=692.66], EntityChicken['Chicken'/40, l='MpServer', x=978.81, y=4.00, z=679.40], EntityItem['item.item.egg'/41, l='MpServer', x=978.99, y=4.00, z=678.71], EntityChicken['Chicken'/48, l='MpServer', x=1032.15, y=4.00, z=648.63], EntitySheep['Sheep'/52, l='MpServer', x=1017.24, y=4.00, z=686.33], EntityPig['Pig'/59, l='MpServer', x=974.84, y=4.00, z=763.80], EntityPig['Pig'/60, l='MpServer', x=975.90, y=4.00, z=763.41], EntityCow['Cow'/61, l='MpServer', x=1018.31, y=4.00, z=697.80], EntityHorse['Horse'/62, l='MpServer', x=1018.95, y=4.00, z=711.11], EntitySheep['Sheep'/65, l='MpServer', x=960.22, y=4.00, z=799.24], EntityChicken['Chicken'/66, l='MpServer', x=953.63, y=4.00, z=796.52], EntityChicken['Chicken'/67, l='MpServer', x=953.26, y=4.00, z=797.10], EntityChicken['Chicken'/68, l='MpServer', x=969.40, y=4.00, z=783.00], EntityChicken['Chicken'/69, l='MpServer', x=963.53, y=4.00, z=781.95], EntityChicken['Chicken'/70, l='MpServer', x=969.50, y=4.00, z=783.50], EntityPig['Pig'/71, l='MpServer', x=977.79, y=4.00, z=761.11], EntityPig['Pig'/72, l='MpServer', x=978.27, y=4.00, z=760.15], EntityCow['Cow'/73, l='MpServer', x=1019.19, y=4.00, z=741.64], EntityChicken['Chicken'/74, l='MpServer', x=973.50, y=4.00, z=784.50], EntitySheep['Sheep'/75, l='MpServer', x=998.80, y=4.00, z=758.36], EntitySheep['Sheep'/77, l='MpServer', x=1009.31, y=4.00, z=760.61], EntitySheep['Sheep'/78, l='MpServer', x=1008.68, y=4.00, z=757.14], EntityChicken['Chicken'/94, l='MpServer', x=1051.50, y=4.00, z=803.50], EntityPig['Pig'/99, l='MpServer', x=1058.50, y=4.00, z=804.50], EntityChicken['Chicken'/117, l='MpServer', x=957.90, y=4.00, z=683.71], BuilderEntity['entity.mts_entity.name'/118, l='MpServer', x=1002.63, y=4.46, z=628.97], EntityHorse['Horse'/121, l='MpServer', x=997.14, y=4.00, z=645.83], EntityPlayerSP['EddieTheHead'/1, l='MpServer', x=1002.05, y=4.18, z=726.69]]
  Retry entities: 0 total; []
  Server brand: fml,forge
  Server type: Integrated singleplayer server

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Windows 8.1 (amd64) version 6.3
  Java Version: 1.8.0_51, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 355260920 bytes (338 MB) / 1157627904 bytes (1104 MB) up to 6979321856 bytes (6656 MB)
  JVM Flags: 8 total; -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -Xmx6656m -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump
  IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
  FML: MCP 9.42 Powered by Forge 14.23.5.2854 Optifine OptiFine_1.12.2_HD_U_G5 20 mods loaded, 20 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State  | ID                   | Version         | Source                                               | Signature                                |
       |:------ |:-------------------- |:--------------- |:---------------------------------------------------- |:---------------------------------------- |
       | LCHIJA | minecraft            | 1.12.2          | minecraft.jar                                        | None                                     |
       | LCHIJA | mcp                  | 9.42            | minecraft.jar                                        | None                                     |
       | LCHIJA | FML                  | 8.0.99.99       | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | forge                | 14.23.5.2854    | forge-1.12.2-14.23.5.2854.jar                        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | LCHIJA | ClientFixer          | 1.12.2-1.9      | minecraft.jar                                        | None                                     |
       | LCHIJA | foamfixcore          | 7.7.4           | minecraft.jar                                        | None                                     |
       | LCHIJA | baubles              | 1.5.2           | Baubles-1.12-1.5.2.jar                               | None                                     |
       | LCHIJA | codechickenlib       | 3.2.3.358       | CodeChickenLib_1.12.2_3.2.3.358_universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | mts                  | 19.15.7         | Immersive+Vehicles-1.12.2-19.15.7.jar                | None                                     |
       | LCHIJA | unuparts             | 4.3.1           | UNU+Parts+Pack+[MTS]+1.12.2-19.15.5-4.3.1.jar        | None                                     |
       | LCHIJA | unuverse             | 1.3.0           | Expanded+UNUverse+Pack+[MTS]+1.12.2-18.0.0-1.3.0.jar | None                                     |
       | LCHIJA | foamfix              | 0.10.10-1.12.2  | foamfix-0.10.10-1.12.2.jar                           | None                                     |
       | LCHIJA | waila                | 1.8.26          | Hwyla_1.8.26_B41_1.12.2.jar                          | None                                     |
       | LCHIJA | jei                  | 4.15.0.297      | jei_1.12.2-4.15.0.297.jar                            | None                                     |
       | LCHIJA | nei                  | 2.4.3           | NotEnoughItems_1.12.2_2.4.3.245_universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
       | LCHIJA | unucivil             | 4.2.4           | UNU+Civilian+Pack+[MTS]+1.12.2-19.15.5-4.2.4.jar     | None                                     |
       | LCHIJA | vanillafix           | 1.0.10-SNAPSHOT | VanillaFix-1.0.10-99.jar                             | None                                     |
       | LCHIJA | wailaharvestability  | 1.1.12          | WailaHarvestability_mc1.12_1.1.12.jar                | None                                     |
       | LCHIJA | immersiveengineering | 0.12-98         | ImmersiveEngineering-0.12-98.jar                     | None                                     |
       | LCHIJA | phosphor-lighting    | 1.12.2-0.2.6    | phosphor-1.12.2-0.2.6build50-universal.jar           | f0387d288626cc2d937daa504e74af570c52a2f1 |
  Loaded coremods (and transformers): ClientFixer (clientfixer-1.12.2-1.9.jar)
                                        com.gamerforea.clientfixer.asm.ASMTransformer
                                      IELoadingPlugin (ImmersiveEngineering-core-0.12-98.jar)
                                        blusunrize.immersiveengineering.common.asm.IEClassTransformer
                                      PhosphorFMLLoadingPlugin (phosphor-1.12.2-0.2.6build50-universal.jar)
                                        
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.10-99.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.10-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
  GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 457.66' Renderer: 'GeForce GTX 1650/PCIe/SSE2'
  Suspected Mods: Immersive Vehicles (formerly MTS) (mts)
  Launched Version: 1.12.2-forge-14.23.5.2854
  LWJGL: 2.9.4
  OpenGL: GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 457.66, NVIDIA Corporation
  GL Caps: Using GL 1.3 multitexturing.
           Using GL 1.3 texture combiners.
           Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
           Shaders are available because OpenGL 2.1 is supported.
           VBOs are available because OpenGL 1.5 is supported.
  Using VBOs: Yes
  Is Modded: Definitely; Client brand changed to 'fml,forge'
  Type: Client (map_client.txt)
  Resource Packs: 
  Current Language: English (US)
  Profiler Position: N/A (disabled)
  CPU: 8x Intel(R) Core(TM) i5-10300H CPU @ 2.50GHz
  Client Crashes Since Restart: 1
  Integrated Server Crashes Since Restart: 0


Video:

https://user-images.githubusercontent.com/73932791/128953897-2b83e304-ca44-4a3b-b5fd-be86f49a2752.mp4

**Comment by boot2big** [comment]
I cannot comment as to why the steering wheel rendering business crashes the game, but I think I know why the blocks flicker.

VanillaFix's crash recovery system doesn't play well with rendering crashes in my experience, and will usually end up messing up the screen as you see here.

**Comment by DonBruce64** [comment]
This bug is for Version 19.15.7, which is not the most recent version.  Could you try this on the most recent version and let me know what happens?

**Comment by RottenClunker** [comment]
> This bug is for Version 19.15.7, which is not the most recent version. Could you try this on the most recent version and let me know what happens?

A new issue has appeared.
Now I can't save the JSON file due to the error: "motorized/flapNotches is a list, but has no elements. this is NOT allowed!". The "flapNotches" line is created automatically and there is nothing I can do about it. Manual removal also does not bring any results.

**Comment by DonBruce64** [comment]
It should not be created automatically?  I've not seen that with any stuff the exporter does.  Or are you using the internal JSON creator?

**Comment by RottenClunker** [comment]
> It should not be created automatically? I've not seen that with any stuff the exporter does. Or are you using the internal JSON creator?

Yes, this happened together with the internal JSON creator from IV. It seems to me that this should not be the case, because, as I understood, the "flapNotches" parameter is used only for aircrafts. However, the problem with animation has already been solved. You were right - I encountered a bug from the old version. Now, the steering wheel works perfectly. Thank you for your promptness help!

**Comment by DonBruce64** [comment]
Finally fixed this.  I can drop you a beta in the Discord with the fix, or you can wait for the release version to come out.  Turns out I was flagging the JSON as needing to have that list populated, because I was under the assumption it wouldn't be created if no flaps were on the plane.  However, the exporter creates all lists, just empty, so that was not the case.

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
