### ISSUE TITLE
[BUG] Model render thing is backwards?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#901]
Maybe add a toggle to switch it back and forth if it's intentional? I think it'd be important for certain parts like tires/npcs/seats which I need to be at a specific angle for consistency

**Comment by DonBruce64** [comment]
Which model thing is this?  The one in the dev-mode editor?

**Comment by boot2big** [comment]
I can't run the build right now but might be able to in a bit. And yes, it's in the devmode editor. (The one with the OBJ, texture and position stuffs.)

**Comment by boot2big** [comment]
Just tried using the latest build available on git, didn't seem to help

**Comment by DonBruce64** [comment]
Okay, I see now what the issue is, and I KNOW I fixed it with this latest commit.

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
