### ISSUE TITLE
Lights flicker when moving with animations

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#902]
If an object is a light and has animations, it will flicker on and off (as opposed to disappearing and reappearing) when the animation is going forwards. It doesn't happen when the animation is going reverse.

https://user-images.githubusercontent.com/45642968/129439387-88ea2746-2f46-4be1-a4b0-512fc2c6d93e.mp4

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
