### ISSUE TITLE
Vehicles Despawning after autosave

### ISSUE THREAD

**Issue by Tampastrike** [DonBruce64/MinecraftTransportSimulator#905]
Finished vehicles seem to despawn or be removed from the world after a certain period of time. This is happening on a small private server hosted on serverminer. Keep in mind the vehicle will despawn even if the player is in the same chunk once an autosave occurs. The setting in forge that removes erroring ticking entities is set to false.  However this error only seems to effect vehicles that have been driven from one spot to another. For example, if i place a vehicle and let it sit after an autosave it will not despawn. However if I drive the vehicle and move it as close as 1 block away from its place point, it despawns after an autosave.  I have plenty of other vehicle mods on this server but this is the only mod with this issue. Any suggestions or settings I could play around with in my config files? The link below is a picture of the console when this occurs.

![Vehicle despawn](https://user-images.githubusercontent.com/88513617/129485269-1cc436ae-0708-44d8-8f1d-d99ad55bdc82.PNG)

**Comment by OCEAN02** [comment]
Same issue here, have had to keep respawning vehicles for players on my server.

**Comment by DonBruce64** [comment]
This should be fixed as of the latest beta on the Discord.

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.

**Comment by DonBruce64** [comment]
Was NOT fixed.

**Comment by DonBruce64** [comment]
Fixed again in V20.2.0.
