### ISSUE TITLE
Transmissions separate from engines

### ISSUE THREAD

**Issue by Blue20Boy17** [DonBruce64/MinecraftTransportSimulator#91]
It would be really awesome to have transmissions as a separate part from engines. This way, you can have one motor that can have a transmission swap, and change it's gearing in-game.

**Comment by DonBruce64** [comment]
This would require a re-do for all engines and vehicles as they would all need a new transmission.  Given the trend of pack creators making their own engines with only one variant, and the additional model needed for the transmission, I don't see the benefits outweighing the extra complexity.

**Comment by Blue20Boy17** [comment]
Dangit

**Comment by DonBruce64** [comment]
@Blue20Boy17 Ended up doing this anyways in #109.  See that ticket for details.
