### ISSUE TITLE
Heating and cooling coefficient 

### ISSUE THREAD

**Issue by EnderPK** [DonBruce64/MinecraftTransportSimulator#912]
Heating coefficient will affect to engine temperature on ground, cooling coefficient will affect to engine temperature on speed (higher air speed - stronger cooling). Also, for balance, will be required overcooling (when cooling too strong temperature drops lower than "cold" temperature, and engine starts taking damage). 

For example: you set low heating and cooling coefficient, engine will heat slower while standing, and cool on speed as standart engine. If you set high heat coefficient and low cooling coefficient, engine will heat very fast on ground and slow on speed. If you set coefficients opposite, engine will overcool on speed.

**Comment by DonBruce64** [comment]
@boot2big @BlazeWolf1122 this smells like something y'all will wanna weigh-in on.

**Comment by boot2big** [comment]
Bet, have been wanting to do this for a while and now I have a better understanding of engine business to figure this out

**Comment by DonBruce64** [comment]
@boot2big Code?  Features?  Maths?  You want it?  It's your's my friend!  This ticket is now outsourced.

**Comment by DonBruce64** [comment]
Implemented in 20.3.0.
