### ISSUE TITLE
Preheater and fuel freezing

### ISSUE THREAD

**Issue by EnderPK** [DonBruce64/MinecraftTransportSimulator#913]
In some biomes (f.e. - Snowy Tundra) engine can freeze, and you can't start it until it be heated up. For pre-launch heating you can install individual (for each engine) electrical or fuel preheater, it can be activated from control panel like engine (switch). It will add some realism, you can't easily start engine in very cold place.

**Comment by DonBruce64** [comment]
While this sounds nice at first, I can't see most players enjoying it.  I can only see it being the start of a long stream of "why can't I start engine" complaints.  As such, I'm going to flag this as a wontdo.
