### ISSUE TITLE
[BUG?] Something involving 2048x2048 instrument image sheets and visibility got fucked.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#917]
![image](https://user-images.githubusercontent.com/53581325/130344727-af6caed3-c12b-462f-80c4-ca879d125a20.png)
Normally that white line is supposed to be a temperature thing with snowflakes and stuff... its janked! It seems to show other textures, like sometimes it shows textures from parts, or just white.

Occurs in latest build from here, V20.1-ish Beta 4 iirc

**Comment by boot2big** [comment]
my brain am no work

**Comment by DonBruce64** [comment]
Yeah, there's some issues with animations still on the instruments.  I need to get em fixed.  But spent the day fighting lights instead.

**Comment by boot2big** [comment]
translations also seem to be borked because no clamps

**Comment by DonBruce64** [comment]
Just fixed the translations, but where does one get a snazzy HUD instrument like that?  That current IVV or beta build?

**Comment by boot2big** [comment]
Beta build of IVV, will be released soon.
Is an electric "gauge" screen, or alternatively an aftermarket OBD2 reader. I dunno, but it's IVV V1.5 and it was originally a debug thing I made for CVTs!

**Comment by DonBruce64** [comment]
Does this still happen as of latest beta?  If so, could I get a beta from you for testing it?

**Comment by boot2big** [comment]
Yup. Main CF release, github builds here... I'll post a beta with certain features for a certain waterfowl removed.

**Comment by boot2big** [comment]
https://www.dropbox.com/s/gj74btm9d515ary/beta_1.5_public.jar?dl=1

This link contains a beta build with a couple (currently problem-plagued) additions! Simply look for the purple/lime/orange car called the IVLabs Roadster, which automatically spawns with the bugged screen which _used_ to work before certain versions of V20ish IIRC

Alternatively, just put one into a vehicle.

Either way, the first thing you see _should_ be nothing because... the screen should be black! But it isn't, and neither do the FANCY ICONS appear!!

**Comment by DonBruce64** [comment]
Well, I see something, and it's not black nothingness.  I see that fancy text, but no icons. I'm assuming that's the issue?
![2021-09-04_19 16 48](https://user-images.githubusercontent.com/15241611/132111104-af59774a-3aae-4a07-9af2-9a04d2574437.png)

**Comment by boot2big** [comment]
Affirmative. That white thing is supposed to be a blue snowflakes thermometer thing, and... unless you have magnetos on, you shouldn't even be seeing anything. If you drain the battery on the vehicle too, it's supposed to stay off, but... it don't

**Comment by boot2big** [comment]
For reference, here's some mockups on what _should_ be happening.


If magnetos/ignition/power is off, you should see this.
![image](https://user-images.githubusercontent.com/53581325/132111325-b46c218b-d8d7-414e-b9e5-01591aa98b86.png)

If the ignition is on and the battery isn't kill, you should be seeing this.
![image](https://user-images.githubusercontent.com/53581325/132111357-33ceed76-d83e-421a-849d-5800d92dd8b4.png)

If the engine is overheating, a red steam icon will appear.
![image](https://user-images.githubusercontent.com/53581325/132111368-a771eaff-54ea-456a-980a-8cbd00b03c52.png)

If the engine has more than 60 (will increase soon) hours, this icon appears.
![image](https://user-images.githubusercontent.com/53581325/132111378-3e9860a4-6dbc-4b5d-8d72-488f19f2e2cc.png)

**Comment by DonBruce64** [comment]
Ah, figured out what was happening.  I was not re-binding the instrument texture after rendering text.  If that text was on the bottom of the component list, then it woulda all been good.  Should be fixed now.
![2021-09-04_19 39 47](https://user-images.githubusercontent.com/15241611/132111449-fc300dae-3183-4c9a-b560-c2ba8b37e96b.png)

**Comment by boot2big** [comment]
Ideally they _can't_ be on the bottom as then they'd appear over the black screen regardless of power. But thanks for fixing this! (no way in hell am i putting several visibility variables on text when i can have just one thing block it out)

**Comment by DonBruce64** [comment]
Yeah, I kinda figured that for layered sake they'd need to be in their order, hence why I didn't enforce the ~~fruit~~ text on the bottom requirement.  Thankfully I'll have text rendering a bit better once I overhaul the text rendering system, but that'll take a bit.

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
