### ISSUE TITLE
[BUG] The default particle colors for FFFFFF and below are yellow now 😭

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#918]
Devmode JSON for wheels (although really, it's only different from the one loaded in that it's always on, and the color is FFFFFF instead of 999999)
![image](https://user-images.githubusercontent.com/53581325/130356816-ba4f50db-423e-406b-8d92-a3739e2b7e0b.png)
Ingame appearance after devmode
![image](https://user-images.githubusercontent.com/53581325/130356890-e2ced2a4-91c9-4d02-9df6-3197b73e97c5.png)
![image](https://user-images.githubusercontent.com/53581325/130356905-1bf111ee-b1de-415c-9755-ee2418081fe9.png)
Here's the color set to FFFF00 as well, so I think *maybe* the blue is being dropped along the way
![image](https://user-images.githubusercontent.com/53581325/130356958-ca3010e2-a183-4601-b950-e1fb04688615.png)

**Comment by DonBruce64** [comment]
Turns out I wasn't dropping the blue.  I was just dividing it by 255 due to some old logic.  So basically all your particles would be permanently on f.lux settings.
