### ISSUE TITLE
[BUG] Animations no play sound.

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#919]
https://user-images.githubusercontent.com/53581325/130357225-1a89d79f-a97d-4fca-a53a-b7ddd2c53acf.mp4
make sure to unmute this fucker of a video                                                                      ^

Important note is that plain sound-sounds (horns, engine sounds, etc) still work though

**Comment by DonBruce64** [comment]
This is what happens when I give sounds alternate positions, but then don't assign them their defaults.  Fixed.
