### ISSUE TITLE
Sirens aren't able to place

### ISSUE THREAD

**Issue by ItzMatttt** [DonBruce64/MinecraftTransportSimulator#923]
For some reason I cannot place sirens on emergency vehicles. The place for the siren does get marked but with the red colour instead of green, so i dont know whats going on
![2021-08-26_15 25 09](https://user-images.githubusercontent.com/89421300/130970660-ddf30d38-0ac5-4586-a027-e56c0a70cbd1.png)
![2021-08-26_15 25 16](https://user-images.githubusercontent.com/89421300/130970665-6fe33c7c-503d-4afa-8d28-24322aa56a31.png)

**Comment by boot2big** [comment]
This is a packard issue for UNU among many and should be reported in their server.

**Comment by DonBruce64** [comment]
Either that or Trin.  One of the two is not working within conventions set between one of the two.  They need to talk and figure out the standards.  Will leave this up until such a time for visibility.

**Comment by DrprofLuigi** [comment]
It's an UNU thing, that's an UNU gyrophare and an UNU lightbar.

**Comment by DonBruce64** [comment]
I don't know if that should be taken as an insult or a compliment that I'm confusing UNU vehicles with Trin. ;)

**Comment by boot2big** [comment]
In fairness it would be nice if Trin emergency vehicles could directly take gyrophares though, I think that was planned even. Don't quote me on that though...

**Comment by DonBruce64** [comment]
I thought that both Trin and UNU had cross-compatible parts?  Or did that only extend to the wheels/seats/engines?  Cause I do recall Seagull made his lights parts whereas I think UNU's emergency systems were built-in to specific model variants, so perhaps Seagull didn't establish a convention on the lights when he was making them?

**Comment by boot2big** [comment]
They sorta did, but Trin gyrophares only go in specific spots and not in siren/lightbar spots IIRC, and so likewise don't take UNU siren lights as gyrophares. So yes mostly completely except for this, and vehicle-specific parts. (which I don't really expect, nor _want_, to be interusable... a Trin Rodeo softtop probably wouldn't fit on a Contractor)

**Comment by DonBruce64** [comment]
Gotcha.  @DrprofLuigi whenever this gets patched can you let me know so I can close this ticket?

**Comment by DrprofLuigi** [comment]
@DonBruce64 This is fixed in UNU V4.4.2
