### ISSUE TITLE
[BUG/ENHANCEMENT/IDFK] Change default clamps for brake light compats?

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#925]
As it is right now...
![image](https://user-images.githubusercontent.com/53581325/131206133-5d6393a5-ee56-4d6c-9fce-a747d719586d.png)
https://user-images.githubusercontent.com/53581325/131206156-d7f0d494-7340-496e-882b-dcb6d033f03d.mp4
When it should (at least AFAIK) be like...
![image](https://user-images.githubusercontent.com/53581325/131206163-1c2b0d9f-c86d-49c1-9742-d8d24c4b0c26.png)
(Just a rough estimation of what it should be)
https://user-images.githubusercontent.com/53581325/131206176-4b7295d5-0ad5-490c-920a-006474ffc75f.mp4

Unless anyone's got a car that only lights up the rear lights when you put the brake pedal through the floor. In which case, that probably isn't stock anyways. (:

**Comment by DonBruce64** [comment]
Ooop.  Will fix.  Forgot brakes were analog!

**Comment by DonBruce64** [comment]
Fixed in V20.1.0.
