### ISSUE TITLE
[BUG] Hovering your mouse over items that aren't loaded on an external server will crash your game. (At least, that's what vanillafix says)

### ISSUE THREAD

**Issue by boot2big** [DonBruce64/MinecraftTransportSimulator#926]
goddammit planesmc

[crash-2021-08-28_21.09.53-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7071735/crash-2021-08-28_21.09.53-client.txt)

**Comment by DonBruce64** [comment]
That crash report tells me absolutely nothing.  No stack trace that tells me where in my code it's crashing.  VanillaFix needs to fix that.  However, you said that you have items loaded on your client that aren't loaded on the server?  Is that correct?

**Comment by boot2big** [comment]
Correctamundo. To specific, I (formerly, though have removed it since then) had DVC and (a newer version of) DKZ with newer items that the server didn't have. UPDATE IT DAMNIT PLANESMC

**Comment by DonBruce64** [comment]
I'm tempted to mark this as a wontdo, or invalid, because having different mod versions on clients/servers will normally crash you for any mod, not just IV.  But if you can get me an actual crash report I might be able to prevent this.  No assurances.

**Comment by boot2big** [comment]
Issue is that IIRC forge automatically hides items that are installed on the client and not the server? But give me a moment and I can try to get another crash log

**Comment by boot2big** [comment]
[crash-2021-08-29_14.39.46-client.txt](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7073042/crash-2021-08-29_14.39.46-client.txt)
[latest.log](https://github.com/DonBruce64/MinecraftTransportSimulator/files/7073043/latest.log)
(latest log may be bloated because... planesmc.)

**Comment by DonBruce64** [comment]
So I cross-checked that code.  It doesn't go into any MTS code.  Rather, it just dies in the Vanilla ItemStack code. However, the line it dies on is 881.  And in my development environment, that line contains no code.  That tells me that some mod somewhere has done ASM to inject code into the ItemStack class.  I can't say if it's said mod's code, or Optifine (which I DO see in the crash report, but about 10 function calls up), or just another mod calling ItemStack code at a Bad Time that doesn't have anything to do with the ASM mod.

Either way, there's literally nothing I can do to fix this.  Well, except encourage PlanesMC to update.  So will have to close as a known issue.
