### ISSUE TITLE
Helicopter rotor able to control helicopter while on ground with engine off

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#927]
![image](https://user-images.githubusercontent.com/79125581/131241751-dd0ba3c0-3456-424e-b2ee-5b5d65ace261.png)
the helicopter rotor used to control the helicopter instead of the ailerons and elevators on planes they are spinning wings 
but here the wing not spin but it still able to control the helicopter while parking

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
