### ISSUE TITLE
Text Lighting issue when rotated

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#928]
When you rotate text, it gets lighted as if it is not rotated (as if the lighting rotated along with it). So if it is rotated 90 degrees, it is lighted opposite of how it should be (since MC seems to have two dark axies and 2 light axies).

**Comment by DonBruce64** [comment]
Just checked, and there is literally nothing I can do about this.... except code my own font renderer.  Which is actually something I want to do as it'll make the rendering pipeline a LOT easier to port to other versions, and should allow for custom fonts.  Won't do this right away, but will leave it here as a to-do.

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
