### ISSUE TITLE
Red light not working on traffic lights after setup

### ISSUE THREAD

**Issue by DeadReaper451** [DonBruce64/MinecraftTransportSimulator#929]
I just began setting up traffic lights in my city, and after finishing the controller, I noticed that when the set of lights that should be red aren't. The controllers are properly set up because green and yellow lights are appearing. I thought it could be a  rendering glitch due to something like optifine, but the red lights do flash before configuring the controller, just not when they are fully set up.

**Comment by DonBruce64** [comment]
Is this similar to #906?  Cause it sounds like it, but I can't be sure as you're saying the red light never comes on after configuring.

**Comment by DeadReaper451** [comment]
Sorry for being unclear, but my issue is that the red light never appears at all after configuring. It is not the same as #906

![2021-08-31_18 42 32](https://user-images.githubusercontent.com/49107292/131585233-f58d1fee-015e-4810-a839-dc9b301811e3.png)
![2021-08-31_18 42 41](https://user-images.githubusercontent.com/49107292/131585243-0591ee8b-40b7-4fc7-8859-bde08753041e.png)
![2021-08-31_18 42 44](https://user-images.githubusercontent.com/49107292/131585237-b6054f22-3e23-4a69-b0b0-4a32b7ef7bef.png)

**Comment by DonBruce64** [comment]
Odd.  Usually the flickering one will keep going.  Does this happen with both OCP and UNU signals?  Or just the ones from the offical pack?

**Comment by DeadReaper451** [comment]
Yes, I tested both the UNU and OCP lights, and they all do the same thing. One more thing, I am also on V21 if that helps.

**Comment by DonBruce64** [comment]
So, I think I know the issue.  If you could join the Discord I can send you a test build of the OCP to go with a beta build of the mod.  This is a two-part issue.  One is that the pack has the wrong shapes on the lights, the other is the code for the lights might be messed up.  Comparing the latest beta with the latest pack will allow me to reconcile which is which.  Code betas are available on the Discord, but I'll have to compile and send you a pack beta.

**Comment by DeadReaper451** [comment]
Ok I joined the discord as DeadReaper45 with a rocket at the end.

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
