### ISSUE TITLE
[Bug] Decor Hitboxes defined at center of block

### ISSUE THREAD

**Issue by TheCactus27** [DonBruce64/MinecraftTransportSimulator#930]
Decor hitboxes are centered at the middle of the block rather than being defined at the bottom of the block

![image](https://user-images.githubusercontent.com/33960693/131685531-3f816f19-803f-498c-bb91-968d583a0264.png)

![image](https://user-images.githubusercontent.com/33960693/131685479-dea44658-fd15-4dcf-9f73-335048191599.png)

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
