### ISSUE TITLE
Radio music not follow vehicle when active

### ISSUE THREAD

**Issue by Naxgeneral** [DonBruce64/MinecraftTransportSimulator#932]
Car radio used to play music in  you car while traveling but if your radio music not follow with your car?
this is _not spark joy_

**detail**: the radio sound not follow the vehicle and stayed at the position that radio activated

**Comment by 77RaZe77** [comment]
I have the same problem as you

**Comment by boot2big** [comment]
I can confirm this for several sounds, actually. If it isn't looping, it stays at its point of origin. If it _is_ looping, it follows it quite smoothly (like it did before)

**Comment by 77RaZe77** [comment]
yes the problem is solved thanks a lot

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
