### ISSUE TITLE
[Reminder] Add definitions of yawSpeed and pitchSpeed

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#936]
behaves pretty much the same way as minYaw/maxYaw/minPitch/maxPitch when on part slots

**Comment by DonBruce64** [comment]
Ref: f45a3a10ac34629b5c43f3ea63703e17f408ebd9

**Comment by DonBruce64** [comment]
Added in V21.0.0.
