### ISSUE TITLE
Stall sound freezes game

### ISSUE THREAD

**Issue by EdusgprNetwork** [DonBruce64/MinecraftTransportSimulator#94]
When flying aircraft I end up having ny game freezing every so often.
No crash reports, all I know it's something to do with mts:sounds/stall_buzzer.ogg trying to go off when it doesn't exist 
Currently on v13.0.0 for 1.12.2

**Comment by DonBruce64** [comment]
Can confirm this sound is being called in error.  Will fix in next release.

**Comment by DonBruce64** [comment]
Closing and marking as duplicate as this issue is identical to #96, and that issue is more descriptive as it's specifically the reverse thrust button on joysticks that calls this faulty sound to be called.
