### ISSUE TITLE
[REQUEST] make yawSpeed and pitchSpeed able to apply to seat_rider_yaw and seat_rider_pitch controlled things

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#940]
as it says on the tin

**Comment by DonBruce64** [comment]
I can see the applications for this, but I can also see that it's a fairly simple change.  So outsourcing this to another coder while I work on core systems.

**Comment by DonBruce64** [comment]
Closing this, as due to changes in variables and systems this works just fine with variableModifiers, or with "guns" themselves, just without bullets.
