### ISSUE TITLE
Parts that use vehicle texture doesn't show model in the benches/new bench item rendering?

### ISSUE THREAD

**Issue by Ooferine** [DonBruce64/MinecraftTransportSimulator#941]
Currently parts that uses vehicle texture/have blank models show up as nothing in the crafting benches. A solution would be to allow people to define whether to show the obj model or the item texture in the benches.

**Comment by DonBruce64** [comment]
So, I thought I fixed the vehicle-texture not showing anything, but the models that are nothing?  That's different.  I don't see any reason you'd model something blank, unless you're trying to hide the model on a vehicle, in which case you can just make it a square I would think?  Switching item/OBJ is tough, and I don't know where that setting would even go.

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
