### ISSUE TITLE
the tank explodes from 1 punch

### ISSUE THREAD

**Issue by 77RaZe77** [DonBruce64/MinecraftTransportSimulator#943]
the tank explodes from 1 punch when there is fuel in it
https://discord.com/channels/232316230852280320/407041732988108810/885535590714585170

**Comment by DonBruce64** [comment]
Was addressed in b3610b3b8b931fe1313573c5feb6614127fc04d1.  Will close when released.

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
