### ISSUE TITLE
Missiles cant be reloaded after firing once

### ISSUE THREAD

**Issue by HashimIsaPotato** [DonBruce64/MinecraftTransportSimulator#944]
Can be recreated by loading an AMRAAM on a wing point,firing it and attempting to reload.

https://cdn.discordapp.com/attachments/407041732988108810/886612793095241788/Minecraft_1.12.2_2021-09-12_17-56-45_online-video-cutter.com.mp4

heres a video link

**Comment by DonBruce64** [comment]
Fixed in V20.2.0.
