### ISSUE TITLE
Some mod is doing Bad Stuff and modifying the loaded entity list mid-entity-update, causing IV to crash.

### ISSUE THREAD

**Issue by RJHG56** [DonBruce64/MinecraftTransportSimulator#947]
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  LittlePatchingLoader (LittleTiles_v1.5.14_mc1.12.2.jar)
  ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
Contact their authors BEFORE contacting forge

// Sorry :(

Time: 9/21/21 11:18 PM
Description: Ticking entity

java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at minecrafttransportsimulator.mcinterface.BuilderEntityExisting.func_70030_z(BuilderEntityExisting.java:144)
	at minecrafttransportsimulator.mcinterface.ABuilderEntityBase.func_70071_h_(ABuilderEntityBase.java:49)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:911)
	at java.util.ArrayList$Itr.next(ArrayList.java:861)
	at minecrafttransportsimulator.mcinterface.BuilderEntityExisting.func_70030_z(BuilderEntityExisting.java:144)
	at minecrafttransportsimulator.mcinterface.ABuilderEntityBase.func_70071_h_(ABuilderEntityBase.java:49)
	at net.minecraft.world.World.func_72866_a(World.java:1996)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:832)
	at net.minecraft.world.World.func_72870_g(World.java:1958)

-- Entity being ticked --
Details:
	Entity Type: mts:mts_entity (minecrafttransportsimulator.mcinterface.BuilderEntityExisting)
	Entity ID: 27
	Entity Name: entity.mts_entity.name
	Entity's Exact location: -260.00, 64.05, -23.00
	Entity's Block location: World: (-260,64,-23), Chunk: (at 12,4,9 in -17,-2; contains blocks -272,0,-32 to -257,255,-17), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1762)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613)

-- Affected level --
Details:
	Level name: world
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 1276454910532681716
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-202,64,71), Chunk: (at 6,4,7 in -13,4; contains blocks -208,0,64 to -193,255,79), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 2866095 game time, 1087 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 1 (now: false), thunder time: 1 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:767)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 5.4.0-74-generic
	Java Version: 1.8.0_292, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 862632936 bytes (822 MB) / 1361575936 bytes (1298 MB) up to 1771044864 bytes (1689 MB)
	JVM Flags: 3 total; -XX:MaxMetaspaceSize=200M -Xmx1900M -Xms950M
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2855 30 mods loaded, 30 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version           | Source                                                | Signature                                |
	|:------ |:------------------ |:----------------- |:----------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2            | minecraft.jar                                         | None                                     |
	| LCHIJA | mcp                | 9.42              | minecraft.jar                                         | None                                     |
	| LCHIJA | FML                | 8.0.99.99         | forge.jar                                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2855      | forge.jar                                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | creativecoredummy  | 1.0.0             | minecraft.jar                                         | None                                     |
	| LCHIJA | littletilescore    | 1.0.0             | minecraft.jar                                         | None                                     |
	| LCHIJA | obfuscate          | 0.4.2             | minecraft.jar                                         | None                                     |
	| LCHIJA | architecturecraft  | @VERSION@         | architecturecraft-1.12-3.98.jar                       | None                                     |
	| LCHIJA | armourers_workshop | 1.12.2-0.51.0     | Armourers-Workshop-1.12.2-0.51.0.jar                  | None                                     |
	| LCHIJA | atlcraft           | MC1.12-Ver1.9     | ATLCraftCandlesMod(MC1.12-Ver1.9).jar                 | None                                     |
	| LCHIJA | chineseworkshop    | 1.2.6             | ChineseWorkshop-1.12.2_1.2.6.jar                      | None                                     |
	| LCHIJA | chisel             | MC1.12.2-1.0.2.45 | Chisel-MC1.12.2-1.0.2.45.jar                          | None                                     |
	| LCHIJA | creativecore       | 1.10.0            | CreativeCore_v1.10.61_mc1.12.2.jar                    | None                                     |
	| LCHIJA | exoticbirds        | 1.0               | Exotic Birds 1.12.2-3.2.0.jar                         | None                                     |
	| LCHIJA | fairylights        | 2.1.10            | fairylights-2.2.0-1.12.2.jar                          | None                                     |
	| LCHIJA | ferdinandsflowers  | 1.10.4.1          | Ferdinand's Flowers-1.12.x-1.10.4.1.jar               | None                                     |
	| LCHIJA | cfm                | 6.3.1             | furniture-6.3.1-1.12.2.jar                            | None                                     |
	| LCHIJA | mts                | 20.2.0            | Immersive Vehicles-1.12.2-20.2.0.jar                  | None                                     |
	| LCHIJA | helicopterpack     | 2.7.0             | Helicopter_Pack-2.7.0.jar                             | None                                     |
	| LCHIJA | littleframes       | 1.0.0             | LittleFrames_v1.0.8_mc1.12.2.jar                      | None                                     |
	| LCHIJA | littletiles        | 1.5.0             | LittleTiles_v1.5.14_mc1.12.2.jar                      | None                                     |
	| LCHIJA | mcef               | 1.11              | mcef-1.11b-1.12.2.jar                                 | None                                     |
	| LCHIJA | placeableitems     | 3.3               | placeableitems-3.3.jar                                | None                                     |
	| LCHIJA | tesp               | 2.0.0             | TESP-2.0.0.jar                                        | None                                     |
	| LCHIJA | unuparts           | 4.4.2             | UNU Parts Pack [MTS] 1.12.2-20.1.0-4.4.2.jar          | None                                     |
	| LCHIJA | unucivil           | 4.3.0             | UNU Civilian Pack [MTS] 1.12.2-20.1.0-4.3.0-BETA1.jar | None                                     |
	| LCHIJA | vehicle            | 0.44.1            | vehicle-mod-0.44.1-1.12.2.jar                         | None                                     |
	| LCHIJA | webdisplays        | 1.1               | webdisplays-1.1-1.12.2.jar                            | None                                     |
	| LCHIJA | worldedit          | 6.1.10            | worldedit-forge-mc1.12.2-6.1.10-dist.jar              | None                                     |
	| LCHIJA | kiwi               | 0.5.3.32          | Kiwi-1.12.2-0.5.3.32.jar                              | None                                     |

	Loaded coremods (and transformers): 
CreativePatchingLoader (CreativeCore_v1.10.61_mc1.12.2.jar)
  
LittlePatchingLoader (LittleTiles_v1.5.14_mc1.12.2.jar)
  com.creativemd.littletiles.LittleTilesTransformer
ObfuscatePlugin (obfuscate-0.4.2-1.12.2.jar)
  com.mrcrayfish.obfuscate.asm.ObfuscateTransformer
ShutdownPatcher (mcef-1.12.2-1.11b-coremod.jar)
  net.montoyo.mcef.coremod.ShutdownPatcher
	Profiler Position: N/A (disabled)
	Player Count: 0 / 20; []
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by DonBruce64** [comment]
Some mod is changing what entities are in the loaded entity list while my entity is being updated and checking those entities.  That is NOT allowed.  You don't go randomly changing the loaded entity list while updating entitys.  Can you repeat this crash easily?  If so, we can remove mods one by one to see which ones are doing Bad Stuff.  Otherwise, there's nothing I can do about this.  It's up to the other mod to not do shenanigans.

**Comment by DonBruce64** [comment]
Closing as user did not specify which mod was causing this, and said mod has likely updated to no longer cause this.
