### ISSUE TITLE
LMB as fire and RMB as aim for handheld guns

### ISSUE THREAD

**Issue by mic2139** [DonBruce64/MinecraftTransportSimulator#951]
much less weird and more ergonomical

**Comment by boot2big** [comment]
Maybe switch the two handed animation to RMB as well?
Another suggestion to piggyback this, but a value for constant two-handed guns? (Going action movie protag sounds fun but you probably can't aim well holding a heavy rifle or shotgun with one hand...)

**Comment by DonBruce64** [comment]
Implemented in 20.3.0.
