### ISSUE TITLE
[BUG] Signs not being destroyable after right-clicking with a wrench.

### ISSUE THREAD

**Issue by SpicySauseSaig** [DonBruce64/MinecraftTransportSimulator#953]
I was messing around with signs and ended up right clicking them with a wrench. When I did this, the hitbox shrunk down to just the pole, and when you destroy the pole the sign remains. I don't know if this is a intentional feature that's bugged or just a bug itself, but I can't find a way to destroy the signs. Also keep in mind this was discovered on a server, so it might be different in single player.

Here's an example image of the bug: 
![2021-10-01_17 52 02](https://user-images.githubusercontent.com/46188580/135700300-f9dd6ceb-2182-4858-b2e5-7b1898fa78c0.png)

**Comment by DonBruce64** [comment]
Fixed in 20.3.0.
