### ISSUE TITLE
[Suggestion] Replacing 'secondaryColor' and 'textColor' in the definitions with an improved list.

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#954]
Instead of having a secondary color and text color option for definitions, I think they should be replaced by "partColors" and "textColors". Then parts or text fields would have a "textColor" and "partColor" definition.

Example:
```
		{
			"name": "§3UNU 750 De Luxe Coupe (Apple) §7[BA-205-LTC]",
			"subName": "_apple",
			"partColors": ["_apple", "_manilla"],
			"textColors": ["#000000", "#FFFFFF"],
			"extraMaterials": ["mts:unuparts.unuparts_decor_unu_paint_apple:0:1"]
		}
		

		{
			"pos": [1.125, 0, 0],
			"types": ["ground_wheel"],
			"partColor": "_apple",
			"minValue": 0.8,
			"maxValue": 0.875
		},
		{
			"pos": [0.625, 0.1875, 2.0625],
			"isController": true,
			"types": ["seat"],
			"partColor": "_manilla",
			"dismountPos": [1.625, 0.1875, 2.0625],
			"linkedVariables": ["door_DoorFL"]
		}
```

That way you can have paint-matched wheels, and color-matched interiors. This same feature for text means that you can compensate for different livery patterns with differing colors (like a black/white baron with white fleet# on a black door and a black BTPD on the roof, but these colors are different on a blue/white vehicle.

**Comment by DonBruce64** [comment]
Implemented in 20.3.0.
