### ISSUE TITLE
idea of ​​adding a configuration option

### ISSUE THREAD

**Issue by Mastral** [DonBruce64/MinecraftTransportSimulator#956]
[CONTEXT]
I am having some problems since all the planes no longer have ILS (some mods are not up to date and some will certainly never be again too) some planes which should have ILS no longer have them, I I therefore find myself unable to use the ILS.

[proposal]
I therefore propose adding in the mod config to be able to activate or not the option of being able to put ILS on all planes (as before v20) or to leave them as now (after v20)

Thank you for taking the time to read my post.

**Comment by DonBruce64** [comment]
Implemented in 20.3.0.
