### ISSUE TITLE
Change secondTone to secondTones to allow for multiple options

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#960]
secondTone in the definitions section should be changed from a string, to a list of strings called secondTones.

This should also add a tone variable for parts. If a part doesn't have a tone specified, it does not get modified. However if it does have a tone defined (which is a number referencing the definition's secondTones list), that part should be colored to match the color in the list (or not modified if the part doesn't have a color that matches).

It would also be nice if a default part's color could match when the vehicle is first placed down, rather than needing to be modified with the paint gun.

Example:

```
		{
			"name": "§3UNU 750 Delivery (Ford) §7[BA-205-LTC]",
			"subName": "_ford",
			"extraMaterials": ["mts:unuparts.unuparts_decor_unu_paint_ford:0:1"],
			"secondTones": ["_ford", "_manilla"]
		},
		{
			"name": "§3UNU 750 Delivery (Ivory) §7[BA-205-LTC]",
			"subName": "_ivory",
			"extraMaterials": ["mts:unuparts.unuparts_decor_unu_paint_ivory:0:1"],
			"secondTones": ["_ivory", "_manilla"]
		}
```

```
		{
			"pos": [1.125, 0, 0],
			"types": ["ground_wheel"],
			"minValue": 0.8,
			"maxValue": 0.875,
			"tone": 1
		},
		{
			"pos": [0.625, 0.1875, 2.0625],
			"isController": true,
			"types": ["seat"],
			"defaultPart": "unuparts:unuparts_part_unu_seat_budget",
			"dismountPos": [1.625, 0.1875, 2.0625],
			"linkedVariables": ["door_DoorFL"],
			"tone": 2
		}
```

**Comment by DonBruce64** [comment]
Implemented in 20.3.0.
