### ISSUE TITLE
Horizontal Text Objects are positioned wrongly

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#961]
When  I lay text flat (like on the Police Baron), it seems to be off by roughly 1/2 the character height. It is too high, and also not far enough forward. When I correct for this by 1/2 the height, it is almost in the correct position, but not quite.

![2021-10-07_00 41 39](https://user-images.githubusercontent.com/36775575/136453976-a4d1b0b6-37c8-49be-94dd-3f644a081b8d.png)

**Comment by DonBruce64** [comment]
Fixed in 20.3.0.
