### ISSUE TITLE
Incompatibility with Thaumcraft 6

### ISSUE THREAD

**Issue by UzricRash** [DonBruce64/MinecraftTransportSimulator#966]
Using the version 20.2.0 with Thaumcraft leads to a bug in which the thaumometer (a critical item in thaumcraft) cannot be used at all.
Using the version 20.1.0 does not have this incompatibility.

More info:
https://reddit.com/r/Thaumcraft/comments/q4hjx5/thaumometer_does_not_work_thaumcraft_6/

**Comment by DonBruce64** [comment]
Fixed in 20.3.0.
