### ISSUE TITLE
Vehicles get stuck when hitting blocks with block breaking disabled

### ISSUE THREAD

**Issue by Cosmic-8** [DonBruce64/MinecraftTransportSimulator#968]
Whenever I try to drive up over a block, the car occasionally will get stuck. I can move forward but when I stop the car returns to the block it just climbed.

**Comment by DonBruce64** [comment]
Could you post a video with this?  And when you get stuck, could you turn on hitboxes via F3+B? I suspect you're stuck on a ground hitbox.

**Comment by Cosmic-8** [comment]
Also, just a note, block breaking is turned off in the config.

**Comment by DonBruce64** [comment]
Ah, now THAT is critical to know.  I know exactly where such things are and for sure can see block breaking causing issues with this.  Are you able to join the Discord to test some beta builds?  If so, ping me when you get there.

**Comment by DonBruce64** [comment]
Fixed as best I can in V20.5.2.
