### ISSUE TITLE
Request: Vehicle parts in NBT

### ISSUE THREAD

**Issue by DrprofLuigi** [DonBruce64/MinecraftTransportSimulator#97]
It's annoying when a car gets stuck so you've got to break it and replace it. The worst part is putting the 30 seats, 12 ads, 8 bumper stickers, 4 wheels, ♪ and an engine in an engine bay ♪

It would be nice if these parts were somehow stored in the vehicle item's NBT, much like how immersive engineering tool/gun attachments work. That way, when you break and place a vehicle, you don't need to add all the parts again.

**Comment by DonBruce64** [comment]
Seems logical.  Not 100% sure how hard it would be to implement, but IIRC all parts save themselves as items to the main system anyways, so this *should* be possible to do.

**Comment by DonBruce64** [comment]
Added in 13.1.0.
