### ISSUE TITLE
Font/Fuel label issue on Fluid Pump for MTS

### ISSUE THREAD

**Issue by ItsNiyaz** [DonBruce64/MinecraftTransportSimulator#971]
Hi, already spoke to you about this but here’s a reminder, the fluid pump crash issue that was fixed in the BETA version: Immersive_Vehicles-1.12.2-20.4.0-BETA1.jar now has an issue where the fuel name isn’t centred correctly and is partially offscreen for some fuels (such as crude oil). You mentioned changing the JSON or something but I can’t remember specifically what you said on discord - so apologies for not being able to remind you fully. Attached is the picture I sent on discord. 
![03164034-BF7A-46BE-B85B-598F36CDFD30](https://user-images.githubusercontent.com/74744932/137835962-d26174b7-693f-4879-94ba-029be431779e.png)

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
