### ISSUE TITLE
Please tell me how to solve the problem. It's urgent!

### ISSUE THREAD

**Issue by MIN8281** [DonBruce64/MinecraftTransportSimulator#973]
How can I solve this problem like picture that I upload. The photo was taken by me of other people on the plane. All of player turned off player tweak

![image](https://user-images.githubusercontent.com/92874845/138123219-657c887b-be24-40f0-807d-29e1c468fa9d.png)

**Comment by DonBruce64** [comment]
I don't see this on my end?  Did you try with no other mods installed?
![2021-11-05_23 06 33](https://user-images.githubusercontent.com/15241611/140597565-a42616a8-56c7-417b-a672-db64940be3ba.png)

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
