### ISSUE TITLE
UNU Controll panel text broken

### ISSUE THREAD

**Issue by Cosmic-8** [DonBruce64/MinecraftTransportSimulator#974]
![2021-10-20_15 47 26](https://user-images.githubusercontent.com/60713878/138183007-fa88c5ff-efa3-4b9d-9630-f5ea82d5603f.png)

**Comment by DonBruce64** [comment]
In that case, this is due to the UNU pack itself.  @DrprofLuigi is the one you need to get with.

**Comment by DonBruce64** [comment]
Closed per UNU pack author confirming fix.
