### ISSUE TITLE
road path visual modification for non-road paths

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#975]
I can't explain this so i'll let the image explain
i do wanna do a similar thing myself for my pack, but more for placing traffic cars and less for making a path
![image](https://user-images.githubusercontent.com/63666200/138537789-ae99d150-93b2-48b3-a3be-f06ac54d9dca.png)

**Comment by DonBruce64** [comment]
I actually have the code set up to allow that for roads to allow for things like bridge supports and overhead lights/power lines/etc.  Just needs a few code bits and it should work.  Though you'll also need a GUI to tell MTS what triangles to render.

**Comment by DonBruce64** [comment]
So it turns out this was *not* for components on roads.  Was for a wholly different path system.  As such, it's a wontdo.
