### ISSUE TITLE
help me the writing in the config screen is squares either black or grey or white

### ISSUE THREAD

**Issue by helpmegetaname** [DonBruce64/MinecraftTransportSimulator#979]
this a link of the squares in photo hope it helps https://imgur.com/a/bo97hpc I also have 260 mods other than MTS and its packs including optifine and other performance mods ( I tried almost all the mods in a separate pack with almost identical everything and the text was just fine) sorry for bad English

**Comment by DonBruce64** [comment]
Odd, in that case do you know which mod it is?  Or perhaps are you using a texture pack that changes the fonts?  Unless I know what causes it I won't know how to fix it.

**Comment by DonBruce64** [comment]
Closing due to no response from user.
