### ISSUE TITLE
Fuel Pumps, Fluid Loaders, and Fluid Unloaders Disconnect from Pipes after Leaving the Area or Logging out

### ISSUE THREAD

**Issue by Doublehelix13** [DonBruce64/MinecraftTransportSimulator#981]
![FuelPumpIssue](https://user-images.githubusercontent.com/40927088/139774551-59658566-8154-4e88-ab77-b4b4327638a9.png)

After logging out of a world and logging back in or going out of render distance, fuel pumps disconnect from pipes.  I tested this with both fluid ducts from Thermal Dynamics and fluid pipes from Immersive Engineering.  The fuel pumps must be broken and replaced to fix it; breaking and replacing the pipes does not work.  The same thing happens with fluid loaders and unloaders.

**Comment by Doublehelix13** [comment]
I'm using the latest version of Immersive Vehicles, 20.3.0.

**Comment by DonBruce64** [comment]
Do you remember what the last known-good version was that had these working?

**Comment by Doublehelix13** [comment]
No, sorry.  I don't remember if I encountered this bug or not in V19 and I haven't played older versions.

**Comment by Doublehelix13** [comment]
This issue is fixed in beta 9, at least as far as I've tested with Thermal Dynamics Fluiducts and Immersive Engineering Fluid Pipes.  Thank you!

**Comment by DonBruce64** [comment]
Re-opening as this isn't in the released version.  Will close when released.

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
