### ISSUE TITLE
make the ground_distance animation variable more accurate like ground devices

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#982]
"hey @don_bruce™ can you make the ground_distance animation variable more accurate like ground devices?
it can detect blocks, but not so much things like say uhhh slabs or furneiku's roads"
"Please do so when possible"

**Comment by DonBruce64** [comment]
This is impossible without significant lag, cause blocks don't have heights.  They just have collision boxes.  So you gotta get all of them, then check all of them to see which is the highest.
