### ISSUE TITLE
Mirrored part's light/emissive object doesn't mirror.

### ISSUE THREAD

**Issue by Oskiinus** [DonBruce64/MinecraftTransportSimulator#986]
Tested on Immersive Vehicles 20.4.0 Beta 4.
As the title says, we've already discussed it, also you actually might know where is the issue just by looking at those pictures.

![2021-11-08_00 40 45](https://user-images.githubusercontent.com/88764388/140666351-7e3eff2e-c775-4164-90e8-3084ded7a11c.png)
![2021-11-08_00 40 50](https://user-images.githubusercontent.com/88764388/140666353-5d0279db-f06a-4dc0-ac11-39880e7f898a.png)

Oskiinus

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
