### ISSUE TITLE
[BUG] initialvariables locks the variable open when on a part

### ISSUE THREAD

**Issue by LauraDarkez** [DonBruce64/MinecraftTransportSimulator#988]
couldnt close the doors of a turret when the turret had initial variables, and the vehicle had its own initialvariables. also trying to make initialvariables from the vehicle apply to the turret didnt work either.

**Comment by DonBruce64** [comment]
So, this was corrected in a30bebf35b0d6a88e909d185528ea0ac4def7933, which makes hitboxes on parts modify the parts variables.  Adding the IV to the turrent was causing issues because the turret was trying to modify the vehicle's variables, not its own.

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
