### ISSUE TITLE
Request: Trailer Physics

### ISSUE THREAD

**Issue by Blue20Boy17** [DonBruce64/MinecraftTransportSimulator#99]
Alright, Don...I realize how futile this one is, and you probly won't even consider, but I'm requesting it anyway...

On a scale from 1-10, what's the possibility of you adding trailer physics to MTS/IV? I've been hoping they'd show up for some time. Crayfish did it, but then again, that's the only thing Crayfish has on MTS. Otherwise, MTS is much better. I hope you can consider trailers, or at least attempt to code to see if you can come up with maybe a hint of a breakthrough.

Sorry for requesting something this difficult, but you'll probably just mark this as "wontdo". Oh well, I guess...

**Comment by DonBruce64** [comment]
Actually, I'm marking it as a duplicate, because what you are requesting has already been requested and commented on in Issue #46.  Please see that issue for more information.

**Comment by Blue20Boy17** [comment]
Aighty...how about car-hauling physics? Not with trailers, obviously. But loading a car onto a flatbed truck?
