### ISSUE TITLE
[bug] vehicles do not render when using replaymod after MTS v20

### ISSUE THREAD

**Issue by BlazeWolf1122** [DonBruce64/MinecraftTransportSimulator#990]
when you open a replay, all vehicles are invisible, including any parts.
You can still hear the sounds, and particles iirc

**Comment by DonBruce64** [comment]
This will take a bit to fix.  Issue is ROB isn't following the player, so you don't get your queue to render vehicles.

**Comment by BraveCaperCat** [comment]
Duplicate of ReplayMod/ReplayMod#675

**Comment by DonBruce64** [comment]
Fixed in V21.2.0.
