### ISSUE TITLE
Centered text allignment

### ISSUE THREAD

**Issue by Blulitron** [DonBruce64/MinecraftTransportSimulator#992]
As discussed on Discord: please change the text allignment from top to centered for sign creation etc. in order to prevent text from moving up while autoscaling is enabled.

**Comment by DonBruce64** [comment]
So I won't be able to change the alignment point, as that would change the position of text on every vehicle in every pack and make it wrong.  But what I *can* do is when I auto-scale I can move the text down the same amount I scaled to have it stay centered.  Would that work?

**Comment by Blulitron** [comment]
Yeah why not? As long as it stays centered... Or, like mentioned in Discord, just add more allignment options. Whatever is more comfortable for you.

**Comment by DonBruce64** [comment]
Fixed in V20.4.0.
